### ISSUE TITLE
len('……')得到的结果为2，zh_frontend.py在函数_merge_erhua中会assert False

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSpeech#1000]
print('finals', len(finals), finals)
print('word', len(word), word)
assert len(finals) == len(word)

打印得到的结果如下
finals 1 ['……']
word 2 ……
这算是bug还是要将这种符号提前处理一下？

**Comment by zouhan6806504** [comment]
不只是这种，出现连续的符号都会报错
比如
亲~~
——

**Comment by yt605155624** [comment]
感谢您的发现，这个应该是 pypinyin 的问题，之后有时间我修复一下，您感兴趣也可以自己规避一下，或者如果不需要儿化音的话，把 _g2p 的 with_erhua 设置为 False 先跳过试试

**Comment by yt605155624** [comment]
fixed in https://github.com/PaddlePaddle/PaddleSpeech/pull/1040
