### ISSUE TITLE
ValueError: The requested field (wave) is not foundin the data. Fields in the data is dict_keys(['utt_id', 'spk_id', 'text', 'text_lengths', 'speech_lengths', 'durations', 'speech', 'pitch', 'energy']) 

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/PaddleSpeech#1004]
训练voc1模型的时候出现了该错误，请问如何解决？
![图片](https://user-images.githubusercontent.com/14884056/141971467-551edaaa-f38e-46dd-af6a-e85289dd3b39.png)

**Comment by yt605155624** [comment]
训练 voc1 但是从报错上来看，你用的数据是 fastspeech2 的 dump 里面的 metadata?

**Comment by XYZ-916** [comment]
数据是voc1下面dump里面的metadata.jsonl

**Comment by XYZ-916** [comment]
直接运行voc1下的run.sh会生成dump的吧。

**Comment by yt605155624** [comment]
可以生成， 你 vim 一下看看生成的对不对

**Comment by yt605155624** [comment]
by the way , 会不会你不小心注释掉了 run.sh 里面的 source path.sh, 代码实际上是调用了 exps/fastspeech2 里面的预处理脚本？ 实际上是调用这个哈 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/gan_vocoder/preprocess.py

**Comment by XYZ-916** [comment]
> 可以生成， 你 vim 一下看看生成的对不对
<img width="1075" alt="QQ20211118-110932@2x" src="https://user-images.githubusercontent.com/14884056/142344872-030a60be-67bb-4e85-8e7d-480950f0912f.png">

看上去没啥问题

**Comment by XYZ-916** [comment]
> by the way , 会不会你不小心注释掉了 run.sh 里面的 source path.sh, 代码实际上是调用了 exps/fastspeech2 里面的预处理脚本？ 实际上是调用这个哈 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/gan_vocoder/preprocess.py

实际上调用的就是您上面的那个地址的代码。

**Comment by yt605155624** [comment]
我又跑了一遍代码并没有这个问题，你是不是此前跑了 fastspeech2，输入数据不小心错了，您看 data_table.py 的 58行 fields_in_data = first_example.keys() 读取的是您输入样例的 key(), 报错很明显，您输入了 fastspeech2 的数据进去，git pull 更新代码试试呢
