### ISSUE TITLE
[music]旋律支持

### ISSUE THREAD

**Issue by RedElectricity** [PaddlePaddle/PaddleSpeech#1008]
普通的tts输出只有一个调，但是我想让输出可以输出多个调(简单来说就是虚拟歌姬引擎)，请问有什么解决方案？(btw，有无相关的dataset？

目前行业有实现的例子[Synthesizer V](https://dreamtonics.com/en/synthesizerv/)，他只需用少量的人声样本就能制作清晰的音源，目前我知道paddlehub上有个声音克隆的例子，但是无法解决旋律

**Comment by yt605155624** [comment]
歌声合成这个领域应该是有相应的论文和数据的，您可以调研一下，我们还没有做类似的调研，也欢迎您给我们提供思路
