### ISSUE TITLE
Inference for Chinese ASR(Speech to Text)

### ISSUE THREAD

**Issue by Aksh97** [PaddlePaddle/PaddleSpeech#1017]
Hi, Thanks for this amazing project. Can we download/use any pretrained model to perform Chinese ASR(Speech to Text)?

And if can do it, what are the steps?

**Comment by zh794390558** [comment]
we release PaddleHub model for quick experiment, the entry point is here https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/asr_hub/run.sh

we also release pretrained model https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md here, but using this you should entry `examples`. we will add one doc for infer with pretrain model.

**Comment by jerryuhoo** [comment]
> we release PaddleHub model for quick experiment, the entry point is here https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/asr_hub/run.sh
> 
> we also release pretrained model https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md here, but using this you should entry `examples`. we will add one doc for infer with pretrain model.

试了一下，好像中文的识别率好像不是很高？是模型的原因吗？
```
[S2T][en]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/en.wav
[S2T][en]Text: i knocked at the door on the ancient side of the building
[S2T][zh]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/zh.wav
[S2T][zh]Text: 不认为跑步最重要能就是可与稳大糕的子已性高
```

**Comment by yt605155624** [comment]
我们自己测试了一下是没有问题的，请问您使用的 paddle 版本是多少？建议更新成 paddle 2.2.0 试试

**Comment by zh794390558** [comment]
> > we release PaddleHub model for quick experiment, the entry point is here https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/asr_hub/run.sh
> > we also release pretrained model https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md here, but using this you should entry `examples`. we will add one doc for infer with pretrain model.
> 
> 试了一下，好像中文的识别率好像不是很高？是模型的原因吗？
> 
> ```
> [S2T][en]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/en.wav
> [S2T][en]Text: i knocked at the door on the ancient side of the building
> [S2T][zh]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/zh.wav
> [S2T][zh]Text: 不认为跑步最重要能就是可与稳大糕的子已性高
> ```

能否提供测试音频？

**Comment by yfq512** [comment]
@jerryuhoo 你的测试效果有提升么？我之前测试的，效果很差（不知道是哪里自己配置错了？），后采用wenet了

**Comment by jerryuhoo** [comment]
> @jerryuhoo 你的测试效果有提升么？我之前测试的，效果很差（不知道是哪里自己配置错了？），后采用wenet了

等我晚上回家再试试看，我的环境是mac上自己配的，没用docker，可能有个包的版本不对，里面的参数数量不一致，我修改过，可能是这个原因。回去我再发一下详细的信息

**Comment by jerryuhoo** [comment]
> 我们自己测试了一下是没有问题的，请问您使用的 paddle 版本是多少？建议更新成 paddle 2.2.0 试试

我安装的版本是paddle 2.2.0，系统是macOS Big Sur Intel的芯片。昨天安装完运行demos/asr_hub/run.sh好像报了一个没找到python-speech-features模块的错，然后我就自己pip install了一下这个模块，版本为python-speech-features==0.6，后来使用的时候发现logfbank和mfcc报错，对应的参数不一致（忘记是在哪里调用了这两个方法的），然后我就把多的参数删了。请问一下是需要安装其他版本的python-speech-features吗？

**Comment by jerryuhoo** [comment]
> > > we release PaddleHub model for quick experiment, the entry point is here https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/asr_hub/run.sh
> > > we also release pretrained model https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md here, but using this you should entry `examples`. we will add one doc for infer with pretrain model.
> > 
> > 
> > 试了一下，好像中文的识别率好像不是很高？是模型的原因吗？
> > ```
> > [S2T][en]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/en.wav
> > [S2T][en]Text: i knocked at the door on the ancient side of the building
> > [S2T][zh]Wav: /Users/yuyifeng/Documents/GitHub/PaddleSpeech/demos/asr_hub/data/zh.wav
> > [S2T][zh]Text: 不认为跑步最重要能就是可与稳大糕的子已性高
> > ```
> 
> 能否提供测试音频？

测试音频是自带的demos/asr_hub/data/en.wav和zh.wav

**Comment by Jackwaterveg** [comment]
@jerryuhoo 我们项目使用的python-speech-features是经过了修改的版本，并且已经将该版本发包，你可以使用pip install paddlespeech-feat来进行安装。 另外，你也可以在项目的根目录下 pip install -e . 来完成paddlespeech的相关依赖的安装

**Comment by jerryuhoo** [comment]
> @jerryuhoo 我们项目使用的python-speech-features是经过了修改的版本，并且已经将该版本发包，你可以使用pip install paddlespeech-feat来进行安装。 另外，你也可以在项目的根目录下 pip install -e . 来完成paddlespeech的相关依赖的安装

感谢，在安装了paddlespeech-feat之后可以正常使用输出结果。另外在使用pip install -e .的时候报错
```
ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from paddlespeech) (from versions: none)
ERROR: No matching distribution found for paddlespeech_ctcdecoders
```
请教一下是什么原因呢？

**Comment by Jackwaterveg** [comment]
> > @jerryuhoo 我们项目使用的python-speech-features是经过了修改的版本，并且已经将该版本发包，你可以使用pip install paddlespeech-feat来进行安装。 另外，你也可以在项目的根目录下 pip install -e . 来完成paddlespeech的相关依赖的安装
> 
> 感谢，在安装了paddlespeech-feat之后可以正常使用输出结果。另外在使用pip install -e .的时候报错
> 
> ```
> ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from paddlespeech) (from versions: none)
> ERROR: No matching distribution found for paddlespeech_ctcdecoders
> ```
> 
> 请教一下是什么原因呢？

目前没有发mac版本的paddlespeech_ctcdecoders的包，你需要本地编译一下。首先确保自己安装swig 3.0+，然后进入paddlespeech/s2t/decoders/ctcdecoder/swig 接着 bash setup.sh本地编译安装paddlespeech-ctcdecoders。
如果本地没有swig，可以网上下载，然后编译安装。 如果觉得不方便，可以用另一个办法。

另外有个办法就是使用conda安装
使用mini-conda或者anaconda conda
在paddlespeech的根目录下bash setup.sh 
这可以在conda的环境下装好所有的东西
