### ISSUE TITLE
speec to text可以提供python的部署方法么？

### ISSUE THREAD

**Issue by yfq512** [PaddlePaddle/PaddleSpeech#1047]
文档看的一头雾水，shell脚本看不懂呀😂

**Comment by yfq512** [comment]
这个项目改过么？我记得我之前实现过的，现在怎么看不懂了呢😂

**Comment by zh794390558** [comment]
可以关注下 https://github.com/PaddlePaddle/PaddleSpeech/pull/1048 。 如果需要老的代码可以参看 https://github.com/PaddlePaddle/PaddleSpeech/tree/release/v1.8.5

**Comment by weizequan** [comment]
在asr_hub/hub_infer.py，s2t_en_model.speech_recognize(args.wav_en)这个函数的变量是一个audio的文件名。请问有支持直接提供audio内容的接口么？只对audio的一段来提取text。不想将裁剪的audio重新保存成文件。感谢！

**Comment by zh794390558** [comment]
参看这个吧 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/speech_recognition

**Comment by zh794390558** [comment]
> 在asr_hub/hub_infer.py，s2t_en_model.speech_recognize(args.wav_en)这个函数的变量是一个audio的文件名。请问有支持直接提供audio内容的接口么？只对audio的一段来提取text。不想将裁剪的audio重新保存成文件。感谢！

没有写这部分逻辑，你可以参考上面的paddlespeech asr的实现修改。
