### ISSUE TITLE
Output of librispeech manifest format do not match with the required format in paddlespeech/s2t/frontend/utility.py

### ISSUE THREAD

**Issue by josh-zhu** [PaddlePaddle/PaddleSpeech#1057]
In paddlespeech/s2t/frontend/utility.py, input field and token len field are required to handle with the manifest.tiny.raw, while these two fields are not contained in the output manifest file of libripeech.py .

The output format of librispeech:
json_lines.append(
                    json.dumps({
                        'utt': utt,
                        'utt2spk': utt2spk,
                        'feat': audio_filepath,
                        'feat_shape': (duration, ),  # second
                        'text': text,
                    }))
The requied formt in paddlespeech/s2t/frontend/utility.py:

        for json_data in reader:
            feat_len = json_data["input"][0]["shape"][
                0] if 'shape' in json_data["input"][0] else 1.0
            token_len = json_data["output"][0]["shape"][
                0] if 'shape' in json_data["output"][0] else 1.0
            conditions = [
                feat_len >= min_input_len,
                feat_len <= max_input_len,
                token_len >= min_output_len,
                token_len <= max_output_len,
                token_len / feat_len >= min_output_input_ratio,
                token_len / feat_len <= max_output_input_ratio,
            ]

**Comment by zh794390558** [comment]
what process calling this utility, in training or data process? And the egs is `librispeech/asr1`?

please pull the code from `develop`, and test it. 

I test under commit `1d7ce0eba8ae14fd2c1c39b6d2fa4ce7ad36f443`, that is work.

**Comment by josh-zhu** [comment]
The egs is tiny/asr0. At the data process stage, as the quick start script code, local/data.sh in tiny/asr0 will call the paddlespeech/s2t/frontend/utility.py function, which result in a error. I will test it in librispeech/asr1 to see if it is caused by different sample data format. Thank you for your help.

**Comment by zh794390558** [comment]
#1062 #1054 has fix this problem.

**Comment by josh-zhu** [comment]
appreciate it
