### ISSUE TITLE
g2p目前有语料库吗？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSpeech#1066]
搜了一下网上，似乎都只是单个字的多音列举，语句下的 polyphone 和tone sandhi没有相关数据

**Comment by yt605155624** [comment]
三声变调基于规则，应该是没有语料库的
中文多音字，g2pM 这篇文章提供了数据
英文多音字，可以参考这个 https://github.com/google-research-datasets/WikipediaHomographData
开源的数据肯定是不够好的，花钱的话可以去标贝买

**Comment by madosma** [comment]
> 三声变调基于规则，应该是没有语料库的 中文多音字，g2pM 这篇文章提供了数据 英文多音字，可以参考这个 https://github.com/google-research-datasets/WikipediaHomographData 开源的数据肯定是不够好的，花钱的话可以去标贝买你好，但是g2pm虽然处理了多音字，但拼音库又是有缺陷的不如pypinyin，有没有考虑将二者结合起来？

**Comment by yt605155624** [comment]
PYPINYIN默认应该也是处理了多音字的，多音字pypinyin和g2pm都不太好，建议额外训练一个多音字模型，或者您可以尝试一下两者结合的效果

**Comment by madosma** [comment]
谢谢你的回复，pypinyin处理多音字是以它构建的phrase dict来解决的，在考虑引入bert解决多音字问题
