### ISSUE TITLE
建议：将数据集路径放到conf/中的设置文件里

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1111]
https://github.com/PaddlePaddle/PaddleSpeech/blob/9db1710ba78c18185e5180f366ff8e5e3d70b5e2/examples/csmsc/tts3/local/preprocess.sh#L12

https://github.com/PaddlePaddle/PaddleSpeech/blob/9db1710ba78c18185e5180f366ff8e5e3d70b5e2/examples/csmsc/tts3/local/preprocess.sh#L22

以标贝tts3为例，是否能把这些路径放到设置文件里，或者作为某个可以指定的参数呢？这样可以更灵活的指定数据集路径。

**Comment by yt605155624** [comment]
这个建议不错，不过放到 run.sh 里面应该比放到 yaml 里面好，我这里各种参数太多了，写的时候也在权衡到底哪些是写死哪些是可指定，现在仅对于更常改变的做了设置，比如 config 路径，训练输出，预测时候的模型，一般数据集固定的情况下，不同的实验就可以通过改变上述参数进行
感觉如果 run.sh 里面指定参数太多了，local 里面的 shell 文件的可读性就会差一点，你有什么更好的建议嘛

**Comment by yt605155624** [comment]
还有您觉得 run.sh 给 preprocess.sh 传参数的时候，是用 $1 $2 啥的更方便，还是用 preprocess.sh --config --output 之类的更方便？
用前者，传参数的时候不太清晰，不知道具体第几个参数是干啥的，后者更清晰就是命令太长了

**Comment by jerryuhoo** [comment]
我觉得放到run.sh最开头吧，就和conf_path这些参数并列。本来我的想法是，把所有的可变的路径、模型名字这些放到一个单独的yaml里，但其实感觉好像和放在run.sh的开头也没太大区别。关于第二点其实我个人感觉也是各有各的好处，比较难以权衡。目前应该用的是第一种吧，还是不要改动比较好，如果参数一多的话，命令确实会非常的长。

**Comment by zh794390558** [comment]
数据download和format部分可以放到dataset里，统一管理。

**Comment by jerryuhoo** [comment]
包括cpu/gpu的设置也可以加一下，目前run.sh应该只支持gpu吧

**Comment by yt605155624** [comment]
> 包括cpu/gpu的设置也可以加一下，目前run.sh应该只支持gpu吧

--ngpu is the number of gpus to use, if ngpu == 0, use cpu.
