### ISSUE TITLE
about the final 'io'

### ISSUE THREAD

**Issue by azraelkuan** [PaddlePaddle/PaddleSpeech#1125]
**Describe the bug**
i have check that there is 39 finals in paddlespeech symbols, but i found a unknown 'io' final, i want to know which pinyin can generate this final??
https://github.com/PaddlePaddle/PaddleSpeech/blob/f6ca14c5fadac76833b4d1b020f39cbb0eceb825/paddlespeech/t2s/frontend/generate_lexicon.py#L29-L34

**Comment by azraelkuan** [comment]
one more question: why add tone 1 in this rule?
https://github.com/PaddlePaddle/PaddleSpeech/blob/f6ca14c5fadac76833b4d1b020f39cbb0eceb825/paddlespeech/t2s/frontend/zh_frontend.py#L245

**Comment by yt605155624** [comment]
`simple.lexicon` is the generated lexicon
`yo`
 you can see https://github.com/PaddlePaddle/PaddleSpeech/blob/f6ca14c5fadac76833b4d1b020f39cbb0eceb825/examples/csmsc/tts3/local/simple.lexicon#L181

**Comment by yt605155624** [comment]
as for tone 1 in zh_frontend.py line 245, it's for the robot style , see https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2

**Comment by azraelkuan** [comment]
for io, it seems there is no `xio, pio` like pinyin, right?

yo 哟，this is right.

**Comment by yt605155624** [comment]
yes, no xio or pio
`io`  replace `y` in `yo`, 
`iou` replace  `y` in `you`,
You can see our design principles in : https://zhuanlan.zhihu.com/p/349600439

**Comment by azraelkuan** [comment]
thanks. close this.
