### ISSUE TITLE
升级praatio到5.0

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1151]
由于Montreal-Forced-Aligner 2.0用的是praatio==5.0，是否可以考虑把paddlespeech中的praatio升级到5.0呢？这样在同时安装两个包的时候不会冲突。
需要修改的部分是把import tigo替换为textgrid。
例如在gen_duration_from_textgrid.py中：
```python
from praatio import textgrid
...
alignment = textgrid.openTextgrid(tg_path, includeEmptyIntervals=True)
```

**Comment by yt605155624** [comment]
I will check this tomorrow，cause we use MFA 1.X，I haven't met this conflict, you can also 
1. clone PaddleSpeech 
2. change the version of praatio in setup.py
3. pip install .

to install paddlespeech without package conflict
