### ISSUE TITLE
wenetspeech 模型识别同样一个test.wav，paddlespeech 要比pytorch 慢4倍

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#1177]
conformer 模型中包含 conv1d, paddle conv1d 速度慢是已知问题
![image](https://user-images.githubusercontent.com/24568452/146900542-917d3157-2527-4ffe-9d8d-62f20350379a.png)

**Comment by Jackwaterveg** [comment]
wenetspeech的第一次预测时间为2.82，后续都为0.5左右。而paddlespeech每次都是2.2几。所以估计主要问题应该是我们每次都要加载一次模型进行预测。

**Comment by yt605155624** [comment]
> wenetspeech的第一次预测时间为2.82，后续都为0.5左右。而paddlespeech每次都是2.2几。所以估计主要问题应该是我们每次都要加载一次模型进行预测。

用户模型只加载了一次
