### ISSUE TITLE
ASR run run.sh   error  

### ISSUE THREAD

**Issue by silencervan** [PaddlePaddle/PaddleSpeech#1180]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception
 [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by silencervan** [comment]
for i, batch in enumerate(data_loader):
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166

**Comment by zh794390558** [comment]
应该是内存不够，OOM了。减少worker数试试。
