### ISSUE TITLE
Mac：assert offset + x.shape[1] < self.max_len

### ISSUE THREAD

**Issue by ReBenDish** [PaddlePaddle/PaddleSpeech#1182]
Mac 12.1系统，使用python调用api进行识别的时候，会报AssertionError，不知道怎么解决

![image](https://user-images.githubusercontent.com/40975871/146924298-4eb4b32d-bb49-4c54-b6fb-b60995f08b7b.png)

**Comment by zh794390558** [comment]
确认下输入语音长度，是否超过self.max_len

**Comment by ReBenDish** [comment]
> 确认下输入语音长度，是否超过self.max_len

嗯，使用了官方的例子就可以识别，但是不知道如果要识别长文本应该怎么去修改

**Comment by zh794390558** [comment]
需要先过VAD模块。

**Comment by ReBenDish** [comment]
> 需要先过VAD模块。

VAD模块是不设计在ASRExecutor接口内的吗？那在paddlespeech的脚手架中有吗？还有一个问题是，检测出的活体人声本身就很长是不是还是无法完成整段的识别。如果切分的话难免破坏语义会影响识别吗？

**Comment by zh794390558** [comment]
目前没有做VAD的功能，cli只是ASR模型的调用，需要自己集成VAD。

> 检测出的活体人声本身就很长是不是还是无法完成整段的识别
需要VAD能且分更细粒度的停顿。
