### ISSUE TITLE
StyleFastSpeech2Inference doesn't support multiple speakers

### ISSUE THREAD

**Issue by jerryuhoo** [PaddlePaddle/PaddleSpeech#1186]
fastspeech2.py中的StyleFastSpeech2Inference目前只支持单人数据集的变速变调（标贝），是否考虑加入spk_id，以及加一个aishell3的inference的例子呢？

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/b7f4d8f1529a4e027b829f65979fea8b316e3929/paddlespeech/t2s/models/fastspeech2/fastspeech2.py#L877 参照上面的类加个 spk_id 就成了，有兴趣可以自己先搞一下
