### ISSUE TITLE
对于超长文本，语音合成最后的结果不好

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#1199]
FastSpeech2 模型是非自回归模型，这个问题是该模型本身的问题，PaddleSpeech 的中文文本前端提供了按照标点切句的功能，您可以在调用文本前端时设置 merge_sentence=False，然后按照分句一个一个合成，再把分句的结果 concat 到一起，类似于下图
![mmexport1640224872489](https://user-images.githubusercontent.com/24568452/147176584-b72daa2e-cdd5-4467-8a8a-c0ba2e834f7b.png)
目前调用时为了统一中文和英文模型，默认 merge_sentence=True

**Comment by e3u3** [comment]
input_ids = frontend.get_input_ids(input, merge_sentences=True, print_info=True)
在前端有一个merge_sentences=True参数。改成false会返回按照标点符号分句之后的句子列表。然后对列表里的每一个句子转语音，再用numpy把语音的一维数组拼接回长语音。
另外据我实验这个merge_sentences只会根据标点分割句子，无标点的文本就不行了。所以也可以自己另写一个分句函数或者暴力截断。每句长度在100以内比较合适，保证了质量也不太占显存。经测试500字的文本会占用10+GB显存。
