### ISSUE TITLE
请问speech2text可以转换到paddlelite 然后在android上运行吗

### ISSUE THREAD

**Issue by Ray8716397** [PaddlePaddle/PaddleSpeech#1206]
如题,

**Comment by zh794390558** [comment]
DS2可以，但模型太大了。

**Comment by Ray8716397** [comment]
所以目前只提供这个"conformer_wenetspeech-zh-16k" pretrained_model?

**Comment by Jackwaterveg** [comment]
目前命令行调用的化，asr只提供这个，后续会逐渐增加。但是pretrained_model 还有很多，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md，这些支持在example中使用

**Comment by wy676579037** [comment]
可以安装在安卓手机吗
