### ISSUE TITLE
使用paddlespeech asr命令的时候会产生exp/log, 其中有较大的日志文件

### ISSUE THREAD

**Issue by Jackwaterveg** [PaddlePaddle/PaddleSpeech#1211]
描述：
使用paddlespeech asr命令的时候会产生exp/log, 其中有较大的日志文件
![image](https://user-images.githubusercontent.com/87408988/147321494-26f9f97c-0a77-45a8-bb3e-6b8f5e257782.png)

复现：
安装paddlespeech后，paddlespeech asr --input xxx

期望：
日志文件尽量小，最好没有

环境：
ubuntu

**Comment by yt605155624** [comment]
Duplicate of  https://github.com/PaddlePaddle/PaddleSpeech/issues/1124

**Comment by Alc-z** [comment]
现在还是没有参数可以控制exp/log生成吗？
