### ISSUE TITLE
啥时候会有多说话人分割功能啊~

### ISSUE THREAD

**Issue by lucylqe** [PaddlePaddle/PaddleSpeech#1213]
啥时候会有多说话人分割功能啊~

**Comment by zh794390558** [comment]
是 Diarization ，还是 Seperation?
看需求人多不。

**Comment by lucylqe** [comment]
> 是 Diarization ，还是 Seperation? 看需求人多不。
就是多人对话的音频里，分辨出哪段话是哪个人说的 。应该也是个很典型的任务了吧

**Comment by zh794390558** [comment]
Diarization 在规划中

**Comment by godeity** [comment]
也是想用类似功能， 有没有初版，可以一起开发吗？

**Comment by zh794390558** [comment]
我把issue链接到我们的开发issue中。可以关注下，现在初版建设我们先来，如果有细分动作的话再联系您一起合作贡献。关注下 #1304
