### ISSUE TITLE
Failed to build pyworld bottleneck

### ISSUE THREAD

**Issue by geekchen007** [PaddlePaddle/PaddleSpeech#1220]
pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple 报错

Failed to build pyworld bottleneck
ERROR: Could not build wheels for pyworld, bottleneck, which is required to install pyproject.toml-based projects

  error: command 'XXX/envs/paddle/bin/x86_64-conda-linux-gnu-c++' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
  Building wheel for bottleneck (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: xxx/anaconda3/envs/paddle/bin/python3.7 xxx/anaconda3/envs/paddle/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpa026yewa
       cwd: /tmp/pip-install-1hmqtmzj/bottleneck_f4131d72736d4fea982e804e9fa8e0ac
  Complete output (49 lines):
  /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)

** Environment (please complete the following information):**
 - OS: [Ubuntu:16]
 - GCC/G++ Version [ 8.4]
 - Python Version [3.7]
 - PaddlePaddle Version [2.0.0]
 - Model Version [2.0.0]
 - GPU/DRIVER Informationo [Tesla V100]
 - CUDA/CUDNN Version [cuda-10.2]

**Additional context**

**Comment by yt605155624** [comment]
可以看看您的系统中是否有g++ gcc

**Comment by geekchen007** [comment]
> 
已经安装
gcc version 8.4.0 (crosstool-NG 1.24.0.133_b0863d8_dirty)

**Comment by zh794390558** [comment]
shell默认用bash

**Comment by DragonnZhang** [comment]
有相同的问题
