### ISSUE TITLE
安装PaddleSpeech出错

### ISSUE THREAD

**Issue by dean-lhb** [PaddlePaddle/PaddleSpeech#1237]
错误信息：

ERROR: Could not find a version that satisfies the requirement kaldiio (from paddlespeech) (from versions: 2.13.2, 2.13.3, 2.13.4, 2.13.6, 2.13.7, 2.13.8, 2.13.9, 2.14.0, 2.14.1, 2.15.0, 2.15.1, 2.16.0a1, 2.16.0, 2.17.0, 2.17.1, 2.17.2)
ERROR: No matching distribution found for kaldiio

环境信息：

Python 3.7.10

pip 21.3.1

CentOS Linux release 7.3.1611 (Core)

import platform
platform.architecture()
('64bit', '')

**Comment by Jackwaterveg** [comment]
请安装conda创建python环境，并且使用清华源安装paddlespeech 。文档：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md

**Comment by dean-lhb** [comment]
使用conda环境还是一样的错误

WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/25/bd/e41fb569658637eada532d60025dae1fb2d4ac04c94a45160de750d51fd9/kaldiio-2.13.2.tar.gz#sha256=36dce8d837cd2b705c6900e6085bdb5e2bfe32ee31acf592aa414d216adab7c1 (from https://pypi.tuna.tsinghua.edu.cn/simple/kaldiio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement kaldiio (from paddlespeech) (from versions: 2.13.2, 2.13.3, 2.13.4, 2.13.6, 2.13.7, 2.13.8, 2.13.9, 2.14.0, 2.14.1, 2.15.0, 2.15.1, 2.16.0a1, 2.16.0, 2.17.0, 2.17.1, 2.17.2)
ERROR: No matching distribution found for kaldiio
(/root/tools/venv) [root@izwz9amozfds88nbgfz PaddleSpeech]#

**Comment by yt605155624** [comment]
更新下  pip 试试

**Comment by dean-lhb** [comment]
pip更新之后还是一样的错误：

(/root/tools/venv) [root@izwz9amozfds88nbgfz PaddleSpeech]# pip --version
pip 21.3.1 from /root/tools/venv/lib/python3.7/site-packages/pip (python 3.7)


  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/25/bd/e41fb569658637eada532d60025dae1fb2d4ac04c94a45160de750d51fd9/kaldiio-2.13.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/tools/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mxqyoz0y/kaldiio_1ddd5b0d39f64b6f910de61c4126e200/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mxqyoz0y/kaldiio_1ddd5b0d39f64b6f910de61c4126e200/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e7b9j688
       cwd: /tmp/pip-install-mxqyoz0y/kaldiio_1ddd5b0d39f64b6f910de61c4126e200/
  Complete output (35 lines):
  WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
  ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
  ERROR: No matching distribution found for pytest-runner
  /root/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
    % (opt, underscore_opt)
  Traceback (most recent call last):
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
      subprocess.check_call(cmd)
    File "/root/tools/venv/lib/python3.7/subprocess.py", line 363, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/root/tools/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpda5lypem', '--quiet', '--index-url', 'http://mirrors.aliyun.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-mxqyoz0y/kaldiio_1ddd5b0d39f64b6f910de61c4126e200/setup.py", line 19, in <module>
      tests_require=['pytest', 'pytest-cov']
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/dist.py", line 809, in fetch_build_eggs
      replace_conflicting=True,
    File "/root/tools/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
      replace_conflicting=replace_conflicting
    File "/root/tools/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/root/tools/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/root/tools/venv/lib/python3.7/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['/root/tools/venv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpda5lypem', '--quiet', '--index-url', 'http://mirrors.aliyun.com/pypi/simple/', 'pytest-runner']' returned non-zero exit status 1.
  ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/25/bd/e41fb569658637eada532d60025dae1fb2d4ac04c94a45160de750d51fd9/kaldiio-2.13.2.tar.gz#sha256=36dce8d837cd2b705c6900e6085bdb5e2bfe32ee31acf592aa414d216adab7c1 (from https://pypi.tuna.tsinghua.edu.cn/simple/kaldiio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement kaldiio (from paddlespeech) (from versions: 2.13.2, 2.13.3, 2.13.4, 2.13.6, 2.13.7, 2.13.8, 2.13.9, 2.14.0, 2.14.1, 2.15.0, 2.15.1, 2.16.0a1, 2.16.0, 2.17.0, 2.17.1, 2.17.2)
ERROR: No matching distribution found for kaldiio

**Comment by yt605155624** [comment]
换成清华源也不行吗

**Comment by yt605155624** [comment]
先装下pytest-runner

**Comment by dean-lhb** [comment]
(/root/tools/venv) [root@izwzms8nbgfz PaddleSpeech]# pytest
==================================================================== test session starts ====================================================================
platform linux -- Python 3.7.11, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /root/PaddleSpeech
collected 3 items / 21 errors                                                                                                                               

========================================================================== ERRORS ===========================================================================
___________________________________________ ERROR collecting examples/other/1xt2x/src_deepspeech2x/test_model.py ____________________________________________
ImportError while importing test module '/root/PaddleSpeech/examples/other/1xt2x/src_deepspeech2x/test_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
examples/other/1xt2x/src_deepspeech2x/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
E   ModuleNotFoundError: No module named 'paddlespeech'
______________________________________________________ ERROR collecting examples/other/g2p/test_g2p.py ______________________________________________________
ImportError while importing test module '/root/PaddleSpeech/examples/other/g2p/test_g2p.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
examples/other/g2p/test_g2p.py:18: in <module>
    from paddlespeech.t2s.frontend.zh_frontend import Frontend as zhFrontend
E   ModuleNotFoundError: No module named 'paddlespeech'
___________________________________________ ERROR collecting examples/other/ngram_lm/s0/local/kenlm_score_test.py ___________________________________________
ImportError while importing test module '/root/PaddleSpeech/examples/other/ngram_lm/s0/local/kenlm_score_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
examples/other/ngram_lm/s0/local/kenlm_score_test.py:18: in <module>
    import jieba
E   ModuleNotFoundError: No module named 'jieba'
____________________________________________________ ERROR collecting examples/other/tn/test_textnorm.py ____________________________________________________
ImportError while importing test module '/root/PaddleSpeech/examples/other/tn/test_textnorm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
examples/other/tn/test_textnorm.py:18: in <module>
    from paddlespeech.t2s.frontend.zh_normalization.text_normlization import TextNormalizer
E   ModuleNotFoundError: No module named 'paddlespeech'
_______________________________________ ERROR collecting paddlespeech/s2t/decoders/ctcdecoder/tests/test_decoders.py ________________________________________
ImportError while importing test module '/root/PaddleSpeech/paddlespeech/s2t/decoders/ctcdecoder/tests/test_decoders.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
paddlespeech/s2t/decoders/ctcdecoder/tests/test_decoders.py:17: in <module>
    from paddlespeech.s2t.decoders import decoders_deprecated as decoder
E   ModuleNotFoundError: No module named 'paddlespeech'
___________________________________________ ERROR collecting paddlespeech/s2t/exps/deepspeech2/bin/test_export.py ___________________________________________
ImportError while importing test module '/root/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/test_export.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
____________________________________________ ERROR collecting paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py _____________________________________________
ImportError while importing test module '/root/PaddleSpeech/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
_________________________________________________ ERROR collecting paddlespeech/s2t/exps/u2/bin/test_wav.py _________________________________________________
ImportError while importing test module '/root/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/test_wav.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
_________________________________________________ ERROR collecting tests/unit/asr/deepspeech2_model_test.py _________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/asr/deepspeech2_model_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/asr/deepspeech2_model_test.py:19: in <module>
    from paddlespeech.s2t.models.ds2 import DeepSpeech2Model
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
_____________________________________________ ERROR collecting tests/unit/asr/deepspeech2_online_model_test.py ______________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/asr/deepspeech2_online_model_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/asr/deepspeech2_online_model_test.py:19: in <module>
    from paddlespeech.s2t.models.ds2_online import DeepSpeech2ModelOnline
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
____________________________________________________ ERROR collecting tests/unit/asr/error_rate_test.py _____________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/asr/error_rate_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/asr/error_rate_test.py:17: in <module>
    from paddlespeech.s2t.utils import error_rate
paddlespeech/s2t/utils/error_rate.py:19: in <module>
    import editdistance
E   ModuleNotFoundError: No module named 'editdistance'
_______________________________________________________ ERROR collecting tests/unit/asr/mask_test.py ________________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/asr/mask_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/asr/mask_test.py:19: in <module>
    from paddlespeech.s2t.modules.mask import make_non_pad_mask
paddlespeech/s2t/__init__.py:24: in <module>
    from paddlespeech.s2t.utils.log import Log
paddlespeech/s2t/utils/log.py:20: in <module>
    from loguru import logger
E   ModuleNotFoundError: No module named 'loguru'
_____________________________________________________ ERROR collecting tests/unit/asr/u2_model_test.py ______________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/asr/u2_model_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/asr/u2_model_test.py:18: in <module>
    from yacs.config import CfgNode as CN
E   ModuleNotFoundError: No module named 'yacs'
____________________________________________________ ERROR collecting tests/unit/tts/test_data_table.py _____________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_data_table.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_data_table.py:14: in <module>
    from paddlespeech.t2s.datasets.data_tabel import DataTable
paddlespeech/t2s/__init__.py:17: in <module>
    from . import datasets
paddlespeech/t2s/datasets/__init__.py:14: in <module>
    from .common import *
paddlespeech/t2s/datasets/common.py:17: in <module>
    import librosa
E   ModuleNotFoundError: No module named 'librosa'
_____________________________________________________ ERROR collecting tests/unit/tts/test_expansion.py _____________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_expansion.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_expansion.py:16: in <module>
    from paddlespeech.t2s.modules import expansion
paddlespeech/t2s/__init__.py:17: in <module>
    from . import datasets
paddlespeech/t2s/datasets/__init__.py:14: in <module>
    from .common import *
paddlespeech/t2s/datasets/common.py:17: in <module>
    import librosa
E   ModuleNotFoundError: No module named 'librosa'
________________________________________________________ ERROR collecting tests/unit/tts/test_pwg.py ________________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_pwg.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_pwg.py:15: in <module>
    import torch
E   ModuleNotFoundError: No module named 'torch'
_______________________________________________________ ERROR collecting tests/unit/tts/test_raise.py _______________________________________________________
tests/unit/tts/test_raise.py:50: in <module>
    m(paddle.randn([8, 32]).astype(paddle.int32))
../tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py:355: in __call__
    error_data.raise_new_exception()
../tools/venv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py:336: in raise_new_exception
    six.exec_("raise new_exception from None")
<string>:1: in <module>
    ???
E   ValueError: In transformed code:
E   
E       File "/root/PaddleSpeech/tests/unit/tts/test_raise.py", line 43, in call_it
E   	c = sinusoid_position_encoding(a, b)
E       File "/root/PaddleSpeech/tests/unit/tts/test_raise.py", line 26, in sinusoid_position_encoding
E           if (feature_size % 2 != 0):
E               raise ValueError("size should be divisible by 2")
E               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
E           dtype = dtype or paddle.get_default_dtype()
E   
E   
E       ValueError: size should be divisible by 2
_____________________________________________________ ERROR collecting tests/unit/tts/test_reporter.py ______________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_reporter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_reporter.py:16: in <module>
    from paddlespeech.t2s.training.reporter import report
paddlespeech/t2s/__init__.py:17: in <module>
    from . import datasets
paddlespeech/t2s/datasets/__init__.py:14: in <module>
    from .common import *
paddlespeech/t2s/datasets/common.py:17: in <module>
    import librosa
E   ModuleNotFoundError: No module named 'librosa'
_____________________________________________________ ERROR collecting tests/unit/tts/test_snapshot.py ______________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_snapshot.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_snapshot.py:20: in <module>
    from paddlespeech.t2s.training.extensions.snapshot import Snapshot
paddlespeech/t2s/__init__.py:17: in <module>
    from . import datasets
paddlespeech/t2s/datasets/__init__.py:14: in <module>
    from .common import *
paddlespeech/t2s/datasets/common.py:17: in <module>
    import librosa
E   ModuleNotFoundError: No module named 'librosa'
_______________________________________________________ ERROR collecting tests/unit/tts/test_stft.py ________________________________________________________
ImportError while importing test module '/root/PaddleSpeech/tests/unit/tts/test_stft.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/unit/tts/test_stft.py:15: in <module>
    import torch
E   ModuleNotFoundError: No module named 'torch'
__________________________________________ ERROR collecting third_party/python_kaldi_features/test/test_sigproc.py __________________________________________
ImportError while importing test module '/root/PaddleSpeech/third_party/python_kaldi_features/test/test_sigproc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tools/venv/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
third_party/python_kaldi_features/test/test_sigproc.py:1: in <module>
    from python_speech_features import sigproc
E   ModuleNotFoundError: No module named 'python_speech_features'
===================================================================== warnings summary ======================================================================
../tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:312
  /root/tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:312: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
    "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."

../tools/venv/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77
  /root/tools/venv/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    return (isinstance(seq, collections.Sequence) and

../tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:744
  /root/tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    elif dtype == np.bool:

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================== short test summary info ==================================================================
ERROR examples/other/1xt2x/src_deepspeech2x/test_model.py
ERROR examples/other/g2p/test_g2p.py
ERROR examples/other/ngram_lm/s0/local/kenlm_score_test.py
ERROR examples/other/tn/test_textnorm.py
ERROR paddlespeech/s2t/decoders/ctcdecoder/tests/test_decoders.py
ERROR paddlespeech/s2t/exps/deepspeech2/bin/test_export.py
ERROR paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py
ERROR paddlespeech/s2t/exps/u2/bin/test_wav.py
ERROR tests/unit/asr/deepspeech2_model_test.py
ERROR tests/unit/asr/deepspeech2_online_model_test.py
ERROR tests/unit/asr/error_rate_test.py
ERROR tests/unit/asr/mask_test.py
ERROR tests/unit/asr/u2_model_test.py
ERROR tests/unit/tts/test_data_table.py
ERROR tests/unit/tts/test_expansion.py
ERROR tests/unit/tts/test_pwg.py
ERROR tests/unit/tts/test_raise.py - ValueError: In transformed code:
ERROR tests/unit/tts/test_reporter.py
ERROR tests/unit/tts/test_snapshot.py
ERROR tests/unit/tts/test_stft.py
ERROR third_party/python_kaldi_features/test/test_sigproc.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 21 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================== 3 warnings, 21 errors in 2.08s ===============================================================

**Comment by yt605155624** [comment]
请参考 https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195 安装 pytest-runner 之后再安装 kaldio 和 paddlespeech

**Comment by dean-lhb** [comment]
环境问题已经解决了 谢谢回复

**Comment by dean-lhb** [comment]
你好 请问一下这个程序对内存要求很高吗 我的机器空闲内存1.5G好像不够用

(base) [root@izwz9am8nbgfz ~]# paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
phones_dict: None
[2021-12-30 10:26:19,559] [    INFO] - File /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4.zip md5 checking...
[2021-12-30 10:26:23,394] [    INFO] - Use pretrained model stored in: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4
self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
[2021-12-30 10:26:23,395] [    INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4
[2021-12-30 10:26:23,395] [    INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/default.yaml
[2021-12-30 10:26:23,395] [    INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz
self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
[2021-12-30 10:26:23,397] [    INFO] - File /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4.zip md5 checking...
[2021-12-30 10:26:23,497] [    INFO] - Use pretrained model stored in: /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4
[2021-12-30 10:26:23,498] [    INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4
[2021-12-30 10:26:23,498] [    INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4/pwg_default.yaml
[2021-12-30 10:26:23,498] [    INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz
vocab_size: 268
frontend done!
encoder_type is transformer
decoder_type is transformer
Killed

**Comment by yt605155624** [comment]
> 你好 请问一下这个程序对内存要求很高吗 我的机器空闲内存1.5G好像不够用
> 
> (base) [root@izwz9am8nbgfz ~]# paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav phones_dict: None [2021-12-30 10:26:19,559] [ INFO] - File /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4.zip md5 checking... [2021-12-30 10:26:23,394] [ INFO] - Use pretrained model stored in: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4 self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt [2021-12-30 10:26:23,395] [ INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4 [2021-12-30 10:26:23,395] [ INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/default.yaml [2021-12-30 10:26:23,395] [ INFO] - /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz self.phones_dict: /root/.paddlespeech/models/fastspeech2_csmsc-zh/fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt [2021-12-30 10:26:23,397] [ INFO] - File /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4.zip md5 checking... [2021-12-30 10:26:23,497] [ INFO] - Use pretrained model stored in: /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4 [2021-12-30 10:26:23,498] [ INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4 [2021-12-30 10:26:23,498] [ INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4/pwg_default.yaml [2021-12-30 10:26:23,498] [ INFO] - /root/.paddlespeech/models/pwgan_csmsc-zh/pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz vocab_size: 268 frontend done! encoder_type is transformer decoder_type is transformer Killed

这个我不确定，但我感觉 1.5g 一般确实不够，我一般是在 GPU 上推理的，开发机配置很高，没有考虑过内存问题，但是 aistudio 最低配置应该是可以的，您可以试一下

**Comment by dean-lhb** [comment]
好的 感谢回复

**Comment by yt605155624** [comment]
您系统自带的源应该也是阿里源吧，最近好几个用户都报了这个错，虽然指定了清华源，但是在装 pytest-runner 的时候还是用了阿里源

**Comment by dean-lhb** [comment]
是的 跟你描述的完全一样

**Comment by 00851** [comment]
为什么我一运行PaddleSpeech-develop/examples/csmsc/tts3/run.sh就FileNotFoundError: [Errno 2] No such file or directory: 'dump/train/raw/metadata.jsonl'，为什么没有这个文件，是我没运行什么命令缺失的吗还是下载的项目里没有才缺失的
