### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'float32'

### ISSUE THREAD

**Issue by ultrasev** [PaddlePaddle/PaddleSpeech#1240]
**Describe the bug**
使用 pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple 安装后，在终端使用命令行运行报错。即是无论输入什么命令，比如 `speech` 也会报错，显示 "AttributeError: module 'paddle' has no attribute 'float32'"

**Screenshots**
![](https://s2.loli.net/2021/12/29/g1lXfDNCUSGMdzw.png)

** Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - GCC/G++ Version gcc version 9.3.0
 - Python Version:  Python 3.8
 - PaddlePaddle Version: 2.0.1
 - Model Version: ?
 - GPU/DRIVER Informationo eForce RTX 2070
 - CUDA/CUDNN Version: 11.2

**Comment by yt605155624** [comment]
安装2.2.0以上的paddle

**Comment by ultrasev** [comment]
> 安装2.2.0以上的paddle

多谢，问题解决。
