### ISSUE TITLE
TTS一些小问题总结

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSpeech#1247]
文本1：产业智能化升级和开源生态共建的“大航海“计划也进阶到2.0。
问题：2.0没有被正确读出，只读了2

文本2：社区6000+小时课程向学生免费开放
问题：读成了 六零零零

文本3：现货黄金小幅上扬3美元，报1809.93美元/盎司
问题：斜杆没有读成1

文本4：两个工厂相加今年出货量预计会超1 GWh
问题：单位没读出
建议：考虑下g2p可以让用户自定义词典，将一些单位还有其他专业英文缩写翻译成中文

问题：长文本中句号的时间间隔似乎比逗号还短，句与句之间的停顿时间不够。

问题：生成音频最后一个字停得太快，希望可以增加一秒空音频在后面确保最后一个字读完

**Comment by yt605155624** [comment]
"长文本中句号的时间间隔似乎比逗号还短，句与句之间的停顿时间不够"👇
句号和逗号目前对模型来说都是 "sp" 这个 token, 时长都是模型预测的，所以可能存在逗号比句号短的情况
如果觉得停顿比较短，是否可以考虑在 concat wav 的时候给 wav 增加空音频呢？（可以看下空音频的数字表示是啥）

"生成音频最后一个字停得太快，希望可以增加一秒空音频在后面确保最后一个字读完"👇
这个问题是不是在使用 merge_sentences=True 的时候产生的？因为有的声学模型可能 "sp" 学得不好，导致最后如果有 "sp" 的话，可能有明显的噪音，所以就手动去除了最后的 "sp" (模型在训练的时候最后也是没有 "sp" 的)，昨天刚改了一版（并没有发包），默认 merge_sentences=False, 所有的分句后面都会有 "sp" 了现在（因为标点被转换成了 "sp"），一般末尾是否有 "sp" 可能会影响到最后的一个字的长短 = = 我理解手动加空音频似乎不会影响最后一个字的长短
感兴趣的话可以再看看
1）输入的文本末尾是否有标点（影响末尾是否有 sp）
2）merge_sentences 的值（影响末尾是否有 sp）
3）到底是有 sp 会变短还是没有会变短
https://github.com/PaddlePaddle/PaddleSpeech/blob/6272496d9c26736750b577fd832ea9dd4ddc4e6e/paddlespeech/t2s/frontend/zh_frontend.py#L144

**Comment by yt605155624** [comment]
![image](https://user-images.githubusercontent.com/24568452/147817783-483e7d11-5750-41e3-8b74-2f45d112b29e.png)
红框中的单位应加到判断基数词还是编号的规则里

**Comment by JiehangXie** [comment]
![20220102162632](https://user-images.githubusercontent.com/51190264/147870279-757eacff-696a-4af6-875a-3172de14a0ba.png)

红字部分连读速度过快

已定位，顿号停顿问题，换成逗号正常。

**Comment by yt605155624** [comment]
“华昌化工预计2021年预计盈利16亿-17亿元”，“-”读成了“负”，应该读成“至”

**Comment by fidding** [comment]
> 可以看下空音频的数字表示是啥

请问这个指的是什么意思？
