### ISSUE TITLE
kaldiio安装出错解决方案

### ISSUE THREAD

**Issue by Jackwaterveg** [PaddlePaddle/PaddleSpeech#1248]
问题： Could not find a version that satisfies the requirement kaldiio.

使用清华源安装pytest-runner。
`pip install pytest-runner -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by yt605155624** [comment]
一般出现问题都是因为用户默认的 pip 源是阿里源，虽然安装 paddlespeech 时指定了清华源，但是装 kaldio 的依赖 pytest-runner 时，还是因为未知原因用了阿里源
