### ISSUE TITLE
import _locale 引用出错

### ISSUE THREAD

**Issue by youufis** [PaddlePaddle/PaddleSpeech#1253]
环境：windows 11 paddlepaddle 2.2.1 第一次安装 paddlespeech `测试以下代码运行正常，后面又安装了ppgan ，结果 程序 就不行正常运行，通过分析发现 from paddlespeech.cli import ASRExecutor, TextExecutor 这一句有问题，转到定义处：__init__.py 查看：
发现：import _locale 引用出错导致，试过各种办法问题无法解决。

**Comment by yt605155624** [comment]
请列出具体的报错信息，此处的代码设计主要是因为 windows默认的编码是gbk，而我们打开文件需要 utf-8

**Comment by youufis** [comment]
> 请列出具体的报错信息，此处的代码设计主要是因为 windows默认的编码是gbk，而我们打开文件需要 utf-8
程序没有出任何报错信息，一直卡住第一行没有往下执行。

[{
	"resource": "/c:/Program Files/Python37/Lib/site-packages/paddlespeech/cli/__init__.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"_locale\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 14,
	"startColumn": 8,
	"endLineNumber": 14,
	"endColumn": 15
}]

Import "_locale" could not be resolved

测试代码：_
`from paddlespeech.cli import ASRExecutor, TextExecutor
print(”test“)`

**Comment by yt605155624** [comment]
您如果实在想使用，可以把 import _locale  和 _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8']) 注释掉，确保您系统的编码是 utf8 即可使用 paddlespeech, 否则可能需要您在某些读取文件的代码里面，设置 encoding="utf-8"

**Comment by youufis** [comment]
注释掉这两行也不行，程序还是卡住，转到定义处，再出现：
[{
	"resource": "/c:/Program Files/Python37/Lib/site-packages/paddlespeech/cli/asr/infer.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportUndefinedVariable",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "\"collate_fn_test\" is not defined",
	"source": "Pylance",
	"startLineNumber": 231,
	"startColumn": 26,
	"endLineNumber": 231,
	"endColumn": 41
}]

**Comment by yt605155624** [comment]
抱歉，我看不懂您的报错信息是什么工具打印出来的，只是看到了 "collate_fn_test" is not defined，请您找到正确的报错栈，确定哪里的 collate_fn_test 这个变量没有被定义

**Comment by yt605155624** [comment]
我看了下代码可能是 https://github.com/PaddlePaddle/PaddleSpeech/blob/f27d9d50e60e1bf7762fa7b08d21504d63f75358/paddlespeech/cli/asr/infer.py#L231 这里的问题，这里似乎确实是个 bug ，但是现在默认调用 asr 应该不会走到这行的逻辑，因为默认用的是 webnetspeech 这个模型
请问您的调用命令是什么，您是在使用 ds2_online 这个模型嘛？目前这块逻辑还没写好呢
或者说您的执行器会自动检查代码的问题？ 那您把这行的 collate_fn_test 改成 self.collate_fn_test 再试试

**Comment by youufis** [comment]
1、....那您把这行的 collate_fn_test 改成 self.collate_fn_test 再试试 ，改成这样现在没有报错。
2、可以把 import _locale 和 _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8']) 注释掉，这两行也注释掉了，

但，运行程序是没有报错，但是程序 还是一直卡住没有往下执行，也没有错误信息了。

**Comment by yt605155624** [comment]
您具体是用什么执行的？是命令行嘛？按理说报错是一定会有信息的，您发的这个报错我也不知道是什么环境产生的报错信息
我们没有在 windows 11 上测试过，您可以尝试在 aistudio 的 linux 环境测试

**Comment by youufis** [comment]
`import paddle
from paddlespeech.cli import ASRExecutor, TextExecutor
#from playsound import playsound
#import subprocess
asr_executor=ASRExecutor()
text_executor=TextExecutor()

#转音频
#ffmpeg -i subtitle_demo.mp4 -ac 1 -ar 16000 -vn input.wav
#ffmpeg -i subtitle_demo.mp4 -f mp3 -vn input.mp3
#subprocess.call("ffmpeg -i subtitle_demo.mp4 -ac 1 -ar 16000 -vn input.wav",shell=True)
#playsound("input.wav")

text=asr_executor(
    audio_file="input.wav",
    device=paddle.get_device())

result=text_executor(
    text=text,
    task="punc",
    model="ernie_linear_p3_wudao",
    device=paddle.get_device())

print(f"Text Result:\n{result}")`

以上是测试程序 ，昨天安装 paddlespeech 后，测试是没有什么问题，后面我又安装 了一下ppgan ,就发现程序无法正常工作了，主要是这句问题 import _locale，Import "_locale" could not be resolved 但在其他的win10系统 是正常的。

**Comment by youufis** [comment]
我用的vscde 编辑器
![image](https://user-images.githubusercontent.com/52397655/147809343-ad8ba301-fb58-4256-874c-4b3ec6646678.png)

**Comment by yt605155624** [comment]
那您这边确定一下安装ppgan和这个有什么关系呢，而且这个报错现在已经解决了，你那边卡住，我们也没有办法帮您定位问题啊，建议您换可以用的系统。

**Comment by youufis** [comment]
好的，非常谢谢您的耐心解答。感觉和安装ppgan有关，不能百分百确定。但肯定和paddlespeech有关，期待未来的版本能修正这个错误，我不知道如何解决，因为也没有提供报错信息。

**Comment by SkySailing** [comment]
选择其他虚拟环境，然后再选择回来, it's works for me。
