### ISSUE TITLE
linux环境中已经安装了miniconda，现在安装PaddleSpeech步骤中再安装一个minicoda，对原来的miniconda会有影响吗？

### ISSUE THREAD

**Issue by richard201410** [PaddlePaddle/PaddleSpeech#1263]
linux环境中已经安装了miniconda，现在安装PaddleSpeech步骤中再安装一个minicoda，对原来的miniconda会有影响吗？

**Comment by Jackwaterveg** [comment]
miniconda其实不用重复安装，一个就够用。当然你又安装了一个也没啥问题，不会对原来的conda有影响。使用的时候只会用某个conda，如果要选择用哪一个，需要设置系统环境变量来指定。

**Comment by richard201410** [comment]
@Jackwaterveg 谢谢。已经解决。
