### ISSUE TITLE
[docker]有没有cpu版的镜像可以用

### ISSUE THREAD

**Issue by lang101** [PaddlePaddle/PaddleSpeech#1270]
cpu环境安装一直报错，ubuntu和centos都出错，有没有cpu版的镜像可以用？

**Comment by zh794390558** [comment]
我们的环境是在官网release的docker img里创建的。可以参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html 选在docker img
