### ISSUE TITLE
“宁”转换出错

### ISSUE THREAD

**Issue by ABC0408** [PaddlePaddle/PaddleSpeech#1286]
sentence = '保持宁静'
    TTS = TTSExecutor('default.yaml')
    input_ids = TTS.frontend.get_phonemes(sentence, merge_sentences=True, print_info=True)[0]
    print(input_ids)

----------------
输出：
----------------------------
text norm results:
['保持㝉静']
----------------------------
g2p results:
[['b', 'ao3', 'ch', 'iii2', 'zh', 'u4', 'j', 'ing4']]
----------------------------
['b', 'ao3', 'ch', 'iii2', 'zh', 'u4', 'j', 'ing4']

**Comment by yt605155624** [comment]
感谢，是繁体字和简体字转换出错，我会立即修复，如果您着急可以先把该功能注释掉 
找到您安装 paddlespeech 的位置（import paddlespeech 后 `paddlespeech.__path__`）
https://github.com/PaddlePaddle/PaddleSpeech/blob/f4b0588d76660335d9d9bbfcddb0f61a5792b5b4/paddlespeech/t2s/frontend/zh_normalization/text_normlization.py#L77
注释掉这一行即可

**Comment by yt605155624** [comment]
这个问题已经在 develop 中修复，clone 代码之后在 PaddleSpeech 目录 pip install . 即可安装 develop 版本的 paddlespeech
