### ISSUE TITLE
想问一下 自动语音识别 的 识别英语的模型和 使用文档在哪里

### ISSUE THREAD

**Issue by Jzow** [PaddlePaddle/PaddleSpeech#1292]
我参考官网只看到了识别 中文的 例子，并没有找到英文的，如果有可以发我一下吗，非常感谢

**Comment by Jzow** [comment]
@zh794390558

**Comment by Jzow** [comment]
@yt605155624

**Comment by Jzow** [comment]
`Can not find pretrained resources of conformer_wenetspeech-en-16k.`

这个链接下载下来的model并没有en模型，但是代码里面注释给的是可以设置语言en
[模型地址](https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/)

**Comment by yt605155624** [comment]
asr 命令行调用暂不支持英文，可以看看 examples 里面是例子 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/librispeech

**Comment by Jzow** [comment]
@yt605155624 这个并不是我想找的，我想找的是英语语音识别模型，paddle目前不支持是吗

**Comment by Jzow** [comment]
这个代码里目前全是shell脚本，我需要的example是 python code 或者 model

**Comment by yt605155624** [comment]
> 这个代码里目前全是shell脚本，我需要的example是 python code 或者 model

自己写的代码封装即可，shell 脚本本质是在调用 python 代码

**Comment by xinyujituan** [comment]
> 这个代码里目前全是shell脚本，我需要的example是 python code 或者 model

paddlespeech asr --model transformer_librispeech --lang en --input ./en.wav -v
