### ISSUE TITLE
为什么会有如此多的shell去执行程序,为什么不去繁从简,站在使用者的角度去构建工程? [尽管是吐槽,但期望你们还是认真思考下]

### ISSUE THREAD

**Issue by rhygyj** [PaddlePaddle/PaddleSpeech#1309]
1 建议把example写的简洁统一些,不要做shell里面调用python或别的什么,虽然这些shell写的很简单,但这个真没什么必要,为什么要如此奇葩,在秀技能还是怕直接一点容易烂大街?  还是工程的同学水平太差, 只能为了实现就脚本呼叫? 假如你在考虑局部自动化,那我想说这点过程本来没那么复杂,不需要徒增没用的东西

2 看完工程的所有目录和内容, 发现工程师没去想如果简单高效的分类介绍原理 -> 训练 -> 在线服务(web) , 本来从使用者的角度去用,并不复杂的东西被构建的很复杂, 另外为什么很多说明不是中文为主, 英语虽然也没什么问题, 但都2021年了,很多顶级项目和组织都开始加入便捷的中文文档,虽然翻译有点像google translate.  这简直匪夷所思, paddlepaddle的研发团队和所在的公司姓中还是姓美? 团队的人员有没点脑子?

3 我花了5分钟不到的时间,尝试了语音识别, 但我花了近两天的时间去集成到python web构建docker镜像服务,在集成环节如此多的问题,是我从没想到的,尽管还是有些问题.

**Comment by yt605155624** [comment]
paddlespeech是一个开源库，您有任何意见都可以直接提交pr

**Comment by yaleimeng** [comment]
最奇葩的是到处出现的XXXExecutor类，文本内容居然要 作为input参数放在构造函数里面。
简直从未见过如此奇怪的设计。每操作一次需要构造一个新的对象吗？我想问百度有软件专业的人吗？
弄一个Tool类，tool.dosomething( ) 调用 很麻烦吗？
