### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by zHaOshuAnGye** [PaddlePaddle/PaddleSpeech#1315]
您好，我导入的时候发生了点问题。
之前导入paddlespeech是正常的，今天重新配了一遍，第一次import的时间过长，我以为是卡住了，就中断了。结果重新运行的时候，出现BadZipFile: File is not a zip file。重新安也没用。

`---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
/tmp/ipykernel_2495/2475697323.py in <module>
      1 import paddle
----> 2 from paddlespeech.cli import ASRExecutor, TextExecutor

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/cli/__init__.py in <module>
     20 from .st import STExecutor
     21 from .text import TextExecutor
---> 22 from .tts import TTSExecutor
     23 
     24 _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/cli/tts/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .infer import TTSExecutor

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/cli/tts/infer.py in <module>
     31 from ..utils import MODEL_HOME
     32 from paddlespeech.s2t.utils.dynamic_import import dynamic_import
---> 33 from paddlespeech.t2s.frontend import English
     34 from paddlespeech.t2s.frontend.zh_frontend import Frontend
     35 from paddlespeech.t2s.modules.normalizer import ZScore

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/t2s/__init__.py in <module>
     17 from . import datasets
     18 from . import exps
---> 19 from . import frontend
     20 from . import models
     21 from . import modules

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/t2s/frontend/__init__.py in <module>
     14 from .generate_lexicon import *
     15 from .normalizer import *
---> 16 from .phonectic import *
     17 from .punctuation import *
     18 from .tone_sandhi import *

~/anaconda3/envs/py38/lib/python3.8/site-packages/paddlespeech/t2s/frontend/phonectic.py in <module>
     16 
     17 import paddle
---> 18 from g2p_en import G2p
     19 from g2pM import G2pM
     20 

~/anaconda3/envs/py38/lib/python3.8/site-packages/g2p_en/__init__.py in <module>
----> 1 from .g2p import G2p

~/anaconda3/envs/py38/lib/python3.8/site-packages/g2p_en/g2p.py in <module>
     24     nltk.download('averaged_perceptron_tagger')
     25 try:
---> 26     nltk.data.find('corpora/cmudict.zip')
     27 except LookupError:
     28     nltk.download('cmudict')

~/anaconda3/envs/py38/lib/python3.8/site-packages/nltk/data.py in find(resource_name, paths)
    540                 if os.path.exists(p):
    541                     try:
--> 542                         return ZipFilePathPointer(p, zipentry)
    543                     except OSError:
    544                         # resource not in zipfile

~/anaconda3/envs/py38/lib/python3.8/site-packages/nltk/compat.py in _decorator(*args, **kwargs)
     39     def _decorator(*args, **kwargs):
     40         args = (args[0], add_py3_data(args[1])) + args[2:]
---> 41         return init_func(*args, **kwargs)
     42 
     43     return wraps(init_func)(_decorator)

~/anaconda3/envs/py38/lib/python3.8/site-packages/nltk/data.py in __init__(self, zipfile, entry)
    392         """
    393         if isinstance(zipfile, str):
--> 394             zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
    395 
    396         # Check that the entry exists:

~/anaconda3/envs/py38/lib/python3.8/site-packages/nltk/compat.py in _decorator(*args, **kwargs)
     39     def _decorator(*args, **kwargs):
     40         args = (args[0], add_py3_data(args[1])) + args[2:]
---> 41         return init_func(*args, **kwargs)
     42 
     43     return wraps(init_func)(_decorator)

~/anaconda3/envs/py38/lib/python3.8/site-packages/nltk/data.py in __init__(self, filename)
    933         if not isinstance(filename, str):
    934             raise TypeError("ReopenableZipFile filename must be a string")
--> 935         zipfile.ZipFile.__init__(self, filename)
    936         assert self.filename == filename
    937         self.close()

~/anaconda3/envs/py38/lib/python3.8/zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)
   1267         try:
   1268             if mode == 'r':
-> 1269                 self._RealGetContents()
   1270             elif mode in ('w', 'x'):
   1271                 # set the modified flag so central directory gets written

~/anaconda3/envs/py38/lib/python3.8/zipfile.py in _RealGetContents(self)
   1334             raise BadZipFile("File is not a zip file")
   1335         if not endrec:
-> 1336             raise BadZipFile("File is not a zip file")
   1337         if self.debug > 1:
   1338             print(endrec)

BadZipFile: File is not a zip file`

救命55

**Comment by yt605155624** [comment]
你好，请参考 
![image](https://user-images.githubusercontent.com/24568452/149073891-608bae91-90cf-4477-af61-ebbb0d899906.png)
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install.md

**Comment by zHaOshuAnGye** [comment]
wow 好了！谢谢人美心善的天使姐姐回复这么快

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/1925
