### ISSUE TITLE
expand 函数直接用 tensor 处理而不是 numpy 处理导致 fastspeech2 和 speedyspeech 训练 ips 变慢

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#1345]
see paddle issue  https://github.com/PaddlePaddle/Paddle/issues/38957

**Comment by yt605155624** [comment]
@jerryuhoo  https://github.com/PaddlePaddle/PaddleSpeech/pull/1322 这个 pr 之后训练速度变慢，收敛性变差，必要的话可以回退代码，马上会修复

**Comment by jerryuhoo** [comment]
所以现在的解决办法是先用numpy进行训练，推理的时候用paddle吗，然后再等paddlepaddle把速度慢的问题修复了再统一换成paddle tensor？

**Comment by yt605155624** [comment]
是的
