### ISSUE TITLE
应用技术问题

### ISSUE THREAD

**Issue by apmosquito** [PaddlePaddle/PaddleSpeech#1351]
想用SPEECH的语音转文字功能实现即时的会议发言转成文字功能，请问咱们这个技术可以实现吗？有相关的DEMO吗？

**Comment by zh794390558** [comment]
所有的模型都支持流式识别了。现在正在开发流式识别的demo。

**Comment by Jackwaterveg** [comment]
可以参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/4a133619a14146f5da5398ea6315a93a7ea06bb0/paddlespeech/s2t/models/ds2_online/deepspeech2.py#L157

**Comment by apmosquito** [comment]
> 

非常感谢您的回答，请问DEMO大概是什么时候会开放？

**Comment by apmosquito** [comment]
> 
https://github.com/PaddlePaddle/PaddleSpeech/issues/1351#issuecomment-1014437767

**Comment by apmosquito** [comment]
@zh794390558 非常感谢您的回答，请问DEMO大概会在什么时候开放？

**Comment by Jackwaterveg** [comment]
3月会开放

**Comment by qthui6** [comment]
快速实现deepspeech2安装的方法：https://baijiahao.baidu.com/s?id=1675202226359497084
