### ISSUE TITLE
ASRencode return different shape 

### ISSUE THREAD

**Issue by bingyulab** [PaddlePaddle/PaddleSpeech#1372]
I fellow `paddlespeech/s2t/exps/u2/bin/test_wav.py` load model. 
I want to get ARS encode result. But it return  different type. 
EX: input size is [32, 453, 80]， after encoder  turns to [32, 112, 256]
How to keep same size?

**Comment by zh794390558** [comment]
It can't keep T size, since 2 conv subsampling ( 4x reduction) before applying Transformer. If you need it, should remove conv subsampling layer and re-training model.

**Comment by bingyulab** [comment]
So I need change `conv2d` to linear, and re-train model. Am I right?

**Comment by zh794390558** [comment]
If you do pre-train of speech, i think you need add 2 conv_transpose after transformer block to upsampling from 112 to 453, then compute MSE loss of reconstruction  spectrum

**Comment by bingyulab** [comment]
Thank you. Your idea is better. I try to add zeros tensors.  I think do upsampling is much more reasonable. 
This problem is solved.
