### ISSUE TITLE
请问有没有男生的数据集连接呢？

### ISSUE THREAD

**Issue by FeiNoLabel** [PaddlePaddle/PaddleSpeech#1373]

**Comment by yt605155624** [comment]
TTS没有开源的单男性说话人音色，多说话人数据集里面都有男性

**Comment by FeiNoLabel** [comment]
谢谢
















在 2022-01-22 15:44:53，"TianYuan" ***@***.***> 写道：

TTS没有开源的单男性说话人音色，多说话人数据集里面都有男性

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
