### ISSUE TITLE
[tts] will vits support

### ISSUE THREAD

**Issue by lucasjinreal** [PaddlePaddle/PaddleSpeech#1377]
[speech] will vits support ? an e2e tts model based on transformer?

**Comment by zh794390558** [comment]
暂时没有计划。如果感兴趣，欢迎贡献代码。

**Comment by zh794390558** [comment]
[Conditional Variational Autoencoder with Adversarial Learning for End-to-End Text-to-Speech](https://arxiv.org/pdf/2106.06103.pdf)

https://github.com/jaywalnut310/vits

https://github.com/espnet/espnet/blob/f031015577/espnet2/gan_tts/vits/

**Comment by yt605155624** [comment]
VITS will be supported https://github.com/PaddlePaddle/PaddleSpeech/issues/1699
