### ISSUE TITLE
安装PaddleSpeech相关问题讨论（Windows）

### ISSUE THREAD

**Issue by qibinran** [PaddlePaddle/PaddleSpeech#1397]
无论使用怎样的安装方法，所需的C++也安装了，总是报错：

Failed to build pyworld webrtcvad bottleneck
ERROR: Could not build wheels for pyworld, bottleneck, which is required to install pyproject.toml-based projects

网上找了各种方法都不成功，诚心求教！

**Comment by Jackwaterveg** [comment]
请问有没有完整的编译报错信息截图？

**Comment by qibinran** [comment]
您好！非常感谢您回复！

有截图，如下：
![image](https://user-images.githubusercontent.com/33467840/151281956-92a4ed1f-6260-4173-b326-1c64987c9788.png)
![image](https://user-images.githubusercontent.com/33467840/151281969-4ef1209f-b2d5-4efa-8dfd-3938bd2b7d91.png)

文字版如下：
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\dell\AppData\Local\Temp\tmpwt42ry1q'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\pyworld_249e0598526848599832e86ea0e5bfca
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyworld
  copying pyworld\__init__.py -> build\lib.win-amd64-3.8\pyworld
  running build_ext
  C:\Users\dell\AppData\Local\Temp\pip-build-env-07m53pm1\overlay\Lib\site-packages\setuptools\dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
  Building wheel for webrtcvad (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-q9lvkotl\\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-q9lvkotl\\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\dell\AppData\Local\Temp\pip-wheel-mkhtbxee'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying webrtcvad.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_webrtcvad' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
  Building wheel for bottleneck (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\dell\AppData\Local\Temp\tmpwve_e3kf'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\bottleneck_25894c29468b4cd2a8dd1f4ed0454eaf
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_pytesttester.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_version.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\__init__.py -> build\lib.win-amd64-3.8\bottleneck
  creating build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\autotimeit.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench_detailed.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\__init__.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  creating build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\move.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce_axis.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\reduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\__init__.py -> build\lib.win-amd64-3.8\bottleneck\slow
  creating build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_config.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_template.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\__init__.py -> build\lib.win-amd64-3.8\bottleneck\src
  creating build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\input_modification_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\list_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\memory_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\move_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_axis_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\reduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\scalar_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\util.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\__init__.py -> build\lib.win-amd64-3.8\bottleneck\tests
  UPDATING build\lib.win-amd64-3.8\bottleneck/_version.py
  set build\lib.win-amd64-3.8\bottleneck/_version.py to '1.3.2'
  running build_ext
  running config
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bottleneck
Failed to build pyworld webrtcvad bottleneck
ERROR: Could not build wheels for pyworld, bottleneck, which is required to install pyproject.toml-based projects

辛苦您了！

**Comment by qibinran** [comment]
您好！非常感谢您回复！

有截图，如下：




文字版如下：
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\dell\AppData\Local\Temp\tmpwt42ry1q'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\pyworld_249e0598526848599832e86ea0e5bfca
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pyworld
  copying pyworld\__init__.py -> build\lib.win-amd64-3.8\pyworld
  running build_ext
  C:\Users\dell\AppData\Local\Temp\pip-build-env-07m53pm1\overlay\Lib\site-packages\setuptools\dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
  Building wheel for webrtcvad (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-q9lvkotl\\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\\setup.py'"'"'; __file__='"'"'C:\\Users\\dell\\AppData\\Local\\Temp\\pip-install-q9lvkotl\\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\dell\AppData\Local\Temp\pip-wheel-mkhtbxee'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\webrtcvad_a20fb6b5bcb249b1bb4a3ec6e4df9735\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying webrtcvad.py -> build\lib.win-amd64-3.8
  running build_ext
  building '_webrtcvad' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
  Building wheel for bottleneck (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\dell\appdata\local\programs\python\python38\python.exe' 'c:\users\dell\appdata\local\programs\python\python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\dell\AppData\Local\Temp\tmpwve_e3kf'
       cwd: C:\Users\dell\AppData\Local\Temp\pip-install-q9lvkotl\bottleneck_25894c29468b4cd2a8dd1f4ed0454eaf
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_pytesttester.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\_version.py -> build\lib.win-amd64-3.8\bottleneck
  copying bottleneck\__init__.py -> build\lib.win-amd64-3.8\bottleneck
  creating build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\autotimeit.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\bench_detailed.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  copying bottleneck\benchmark\__init__.py -> build\lib.win-amd64-3.8\bottleneck\benchmark
  creating build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\move.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\nonreduce_axis.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\reduce.py -> build\lib.win-amd64-3.8\bottleneck\slow
  copying bottleneck\slow\__init__.py -> build\lib.win-amd64-3.8\bottleneck\slow
  creating build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_config.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\bn_template.py -> build\lib.win-amd64-3.8\bottleneck\src
  copying bottleneck\src\__init__.py -> build\lib.win-amd64-3.8\bottleneck\src
  creating build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\input_modification_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\list_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\memory_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\move_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_axis_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\nonreduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\reduce_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\scalar_input_test.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\util.py -> build\lib.win-amd64-3.8\bottleneck\tests
  copying bottleneck\tests\__init__.py -> build\lib.win-amd64-3.8\bottleneck\tests
  UPDATING build\lib.win-amd64-3.8\bottleneck/_version.py
  set build\lib.win-amd64-3.8\bottleneck/_version.py to '1.3.2'
  running build_ext
  running config
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bottleneck
Failed to build pyworld webrtcvad bottleneck
ERROR: Could not build wheels for pyworld, bottleneck, which is required to install pyproject.toml-based projects



辛苦您了！








 2022-01-27 10:27:40，"Jackwaterveg" ***@***.***> 写道：

请问有没有完整的编译报错信息截图？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
C++桌面开发安装时已经勾选，不知怎么还是报错呢？

![image](https://user-images.githubusercontent.com/33467840/151282642-4a8d869b-de26-4d61-9c6a-411422680b86.png)

**Comment by Jackwaterveg** [comment]
@qibinran 本质上还是没有安装成功visual studio，C++没有执行编译，所以报错了。 装好visual studio有没有重启电脑？

**Comment by Jackwaterveg** [comment]
看一下命令行使用 `g++` 是否会有这个命令，还是找不到这个命令。

**Comment by qibinran** [comment]
谢谢您回复！
重启电脑了，重启了好几遍。













At 2022-01-27 14:15:54, "Jackwaterveg" ***@***.***> wrote:

@qibinran 本质上还是没有安装成功visual studio，C++没有执行编译，所以报错了。 装好visual studio有没有重启电脑？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by Jackwaterveg** [comment]
@qibinran 有可能是cl.exe没有找到的问题，试试看这个 https://blog.csdn.net/qq_42868008/article/details/81987852

**Comment by qibinran** [comment]
您好！输入g++，显示fatal error。
截图如下：















在 2022-01-27 14:19:36，"Jackwaterveg" ***@***.***> 写道：

看一下命令行使用 g++ 是否会有这个命令，还是找不到这个命令。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
g++运行截图：
![5](https://user-images.githubusercontent.com/33467840/151338599-f1387b30-1fc8-4966-98a8-9daa63b7e714.png)

**Comment by qibinran** [comment]
谢谢！

但是他说：
如果有像我一样未将VS安装到C盘的朋友，可以在安装路径里找，比如我这里是：
E:\VisualStudio\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64




我的VS安装在C盘，但没有他说的文件夹，也没有cl.exe的文件：
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools\VC


请问是怎么回事呢？




At 2022-01-27 14:55:19, "Jackwaterveg" ***@***.***> wrote:

@qibinran 有可能是cl.exe没有找到的问题，试试看这个 https://blog.csdn.net/qq_42868008/article/details/81987852

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
找了各种方案，bottleneck算是单独硬装上去了，但是另两个无论如何装不上去。VS C++的各种方案也试了，都没有效果。cl.exe已经按csdn博客上说的添加了环境变量。现在剩下的两个还是报错如下：

![3](https://user-images.githubusercontent.com/33467840/151384486-819a0ecf-e72c-44f9-9cbd-c4f3e5e54bb0.png)
![4](https://user-images.githubusercontent.com/33467840/151384498-20e7ab37-7486-40f8-ba89-b989e493e2a7.png)
![5](https://user-images.githubusercontent.com/33467840/151384501-90cb3052-cbc0-47f8-8014-12776947ad03.png)
![6](https://user-images.githubusercontent.com/33467840/151384503-54df5493-28f9-46a6-9fc4-84548b328826.png)
![1](https://user-images.githubusercontent.com/33467840/151384505-46e6a98c-9c1f-475c-b610-e3f12ed66f80.png)
![2](https://user-images.githubusercontent.com/33467840/151384508-b3f7c812-2142-4b0c-8563-a786feb5f586.png)

报错的篇幅比原来更长了。

**Comment by Jackwaterveg** [comment]
g++没有问题。can not run rc.exe 应该是系统找不到 rc.exe文件。http://www.jyguagua.com/?p=10049 这里有类似问题的解决方法。

**Comment by Jackwaterveg** [comment]
出现这个问题基本都是C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin 缺少了rc.exe 和 rcdll.dll两个文件。你可以在c盘搜所这两个文件，复制过去

**Comment by qibinran** [comment]
谢谢！

这两个文件复制过去，报错的内容少了，但是还是无法安装，截图如下：












在 2022-01-27 23:31:18，"Jackwaterveg" ***@***.***> 写道：

出现这个问题基本都是C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin 缺少了rc.exe 和 rcdll.dll两个文件。你可以在c盘搜所这两个文件，复制过去

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
已经装了VS，网上找了各种方案，VS2022，2019，2015版本都装了，环境路径也改了，文件也拷了，还是报错 error: Microsoft Visual C++ 14.0 or greater is required. 













在 2022-01-27 23:29:07，"Jackwaterveg" ***@***.***> 写道：

g++没有问题。can not run rc.exe 应该是系统找不到 rc.exe文件。http://www.jyguagua.com/?p=10049 这里有类似问题的解决方法。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by yt605155624** [comment]
安装对应高版本的 Visual C++  即可

**Comment by Jackwaterveg** [comment]
@qibinran 前一条回复没有发出截图

**Comment by Jackwaterveg** [comment]
@qibinran 是现在还是出现 error: Microsoft Visual C++ 14.0 or greater is required这个问题吗?

**Comment by Jackwaterveg** [comment]
可以试试看网上的办法：https://blog.csdn.net/weixin_40547993/article/details/89399825

**Comment by qibinran** [comment]
是的，现在还是这样。我把截图发过去

在 2022-01-27 23:47:52，Jackwaterveg ***@***.***> 写道：


@qibinran 是现在还是出现 error: Microsoft Visual C++ 14.0 or greater is required这个问题吗?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qibinran** [comment]
Github上不去，邮箱没能把截图发过去，不好意思。















At 2022-01-27 23:46:57, "Jackwaterveg" ***@***.***> wrote:

@qibinran 前一条回复没有发出截图

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by Jackwaterveg** [comment]
没事，你这里问题确实比较罕见。试试直接安装build tools。 还不可以的话，根据个人经验，试试安装git bash。在git bash的命令行中进行安装。

**Comment by qibinran** [comment]
谢谢回复，不同版本VS 我都试了，这个visualcppbuildtools_full.exe我也装了，还是不行。










在 2022-01-27 23:50:46，"Jackwaterveg" ***@***.***> 写道：

可以试试看网上的办法：https://blog.csdn.net/weixin_40547993/article/details/89399825

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by Jackwaterveg** [comment]
可以明天加一下微信群

**Comment by qibinran** [comment]
那太好了，盼望加微信群，非常感谢！

**Comment by Jackwaterveg** [comment]
加群方式见 repo首页

**Comment by qibinran** [comment]
![image](https://user-images.githubusercontent.com/33467840/151396809-fe291f48-1a6f-4232-a126-cce5c3a26fb0.png)
![image](https://user-images.githubusercontent.com/33467840/151396838-80192cf1-62c4-41e7-99fb-e08e8e2b1d8e.png)

**Comment by yt605155624** [comment]
请确认各个软件的版本是否符合，并且确认是否正确地配置了环境变量

**Comment by qibinran** [comment]
另外请教一下，每次报错最后都有一个：which is required to install pyproject.toml-based projects.网上说有解决方法，但是我看不了，请问把这个问题解决了是不是就可以了呢？











在 2022-01-28 00:02:01，"Jackwaterveg" ***@***.***> 写道：

可以明天加一下微信群

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
谢谢回复！

软件版本和环境变量应该没问题，各方面都试过。










在 2022-01-28 00:12:45，"TianYuan" ***@***.***> 写道：

请确认各个软件的版本是否符合，并且确认是否正确地配置了环境变量

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
> 安装对应高版本的 Visual C++ 即可

三个版本的VS C++都装了，还是不行啊。
VS C++ 14.0以上的就可以，从前面的回复来看只需要14.0版本就行，更高版本的文件和路径与14.0的不一样，安装时反而找不到。

**Comment by qibinran** [comment]
谢谢回复！不好意思我不知道repo在哪儿找，paddle别的安装说明里留的二维码联络人我已加了，但是她一直没加我到技术群。可否给我我一个repo的网址，或加群的二维码，添麻烦了，非常感谢！



在 2022-01-28 00:05:09，"Jackwaterveg" ***@***.***> 写道：

加群方式见 repo首页

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech

**Comment by qibinran** [comment]
多谢！




At 2022-01-28 09:24:45, "TianYuan" ***@***.***> wrote:

https://github.com/PaddlePaddle/PaddleSpeech

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by qibinran** [comment]
> 加群方式见 repo首页

谢谢回复！不好意思我不知道repo在哪儿找，paddle别的安装说明里留的二维码联络人我已加了，但是她一直没加我到技术群。可否给我我一个repo的网址，或加群的二维码，添麻烦了，非常感谢！


> https://github.com/PaddlePaddle/PaddleSpeech

您好！您说的加群方式就是下面这个吧，我前几天就加了，昨天和今天又请她加我进群，但是一直没有回复。我的微信：ranqibin666，可否帮助我加一下呢？非常感谢！

![image](https://user-images.githubusercontent.com/33467840/151472466-7b87927a-b354-4104-8b82-44538dc86c74.png)

**Comment by qibinran** [comment]
已经加入群了，感激不尽！

**Comment by qibinran** [comment]
问题终于解决了！还是VC++版本的问题，好像是老版装在别处没发现，把老版和2022都卸载了只剩2019版，终于装上了！谢谢各位！




在 2022-01-28 00:12:45，"TianYuan" ***@***.***> 写道：

请确认各个软件的版本是否符合，并且确认是否正确地配置了环境变量

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
















--

建立网站“口音汉语在线”：www.globalaccentchinese.com
工作单位个人主页：https://wxy.nankai.edu.cn/2019/1106/c18394a245671/page.htm

**Comment by Jackwaterveg** [comment]
好的呀  : )

**Comment by zh794390558** [comment]
nltk_data 下载参看： https://blog.csdn.net/qq_43140627/article/details/103895811

**Comment by chenjingchun** [comment]
请问win系统pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple安装成功之后，怎样开启webapi服务？
（就是使用POST请求/paddlespeech/tts这种的服务）

**Comment by kehuanjack** [comment]
Try looking at this link: http://t.csdn.cn/w5N66
