### ISSUE TITLE
jit.to_static 没有效果

### ISSUE THREAD

**Issue by sharingTSU** [PaddlePaddle/PaddleSpeech#1410]
注释掉paddlespeech/t2s/exps/synthesize_e2e.py中jit.to_static 相关代码，运行时间无明显变化。Why?

**Comment by yt605155624** [comment]
那可能是动转静花费时间数量级远小于调用模型所花的时间，为什么觉得注释掉可以减少运行时间呢？

**Comment by sharingTSU** [comment]
想看看代码里静态模型与动态模型的差异，预期动态模型会运行时间长，然而并没有。
