### ISSUE TITLE
Ubuntu18.04root源码安装Hard PaddleSpeech出错

### ISSUE THREAD

**Issue by ccbptm** [PaddlePaddle/PaddleSpeech#1421]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
Ubuntu18.04+Nidia Driver470.82.00+cuda11.2+cudnn8
conda 4.11.0+paddle_env3.7
paddle2.2
everything be essential for install paddleSpeech is ok 

**To Reproduce**
1. Go to dir 'PaddleSpeech'
2. run  'pip install -e .[develop] -i https://pypi.tuna.tsinghua.edu.cn/simple'
3. See error

**Expected behavior**
ERROR: Command errored out with exit status 1:
     command: /home/DBL/anaconda3/envs/paddle_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/DBL/MyProject/Project/PaddleSpeech/setup.py'"'"'; __file__='"'"'/home/DBL/MyProject/Project/PaddleSpeech/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/DBL/MyProject/Project/PaddleSpeech/
    Complete output (61 lines):
    running develop
    running egg_info
    writing paddlespeech.egg-info/PKG-INFO
    writing dependency_links to paddlespeech.egg-info/dependency_links.txt
    writing entry points to paddlespeech.egg-info/entry_points.txt
    writing requirements to paddlespeech.egg-info/requires.txt
    writing top-level names to paddlespeech.egg-info/top_level.txt
    reading manifest file 'paddlespeech.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'paddlespeech.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/DBL/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlespeech.egg-link (link to .)
    Adding paddlespeech 0.1.1 to easy-install.pth file
    Installing paddlespeech script to /home/DBL/anaconda3/envs/paddle_env/bin
    
    Installed /home/DBL/MyProject/Project/PaddleSpeech
    Post Install...
    apt update -y
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    Reading package lists...
    E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    E: Unable to lock directory /var/lib/apt/lists/
    W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
    W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
    Makefile:27: recipe for target 'apt.done' failed
    make: *** [apt.done] Error 100
    /home/DBL/anaconda3/envs/paddle_env/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    /home/DBL/anaconda3/envs/paddle_env/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
      % (opt, underscore_opt)
    /home/DBL/MyProject/Project/PaddleSpeech/setup.py:130: CMD: make, Error: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/DBL/MyProject/Project/PaddleSpeech/setup.py", line 259, in <module>
        setup(**setup_info)
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/DBL/MyProject/Project/PaddleSpeech/setup.py", line 160, in run
        self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/distutils/util.py", line 291, in execute
        func(*args)
      File "/home/DBL/MyProject/Project/PaddleSpeech/setup.py", line 146, in _post_install
        check_call("make")
      File "/home/DBL/MyProject/Project/PaddleSpeech/setup.py", line 133, in check_call
        raise e
      File "/home/DBL/MyProject/Project/PaddleSpeech/setup.py", line 127, in check_call
        executable="/bin/bash" if shell else executable)
      File "/home/DBL/anaconda3/envs/paddle_env/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    /home/DBL/MyProject/Project/PaddleSpeech/tools
    ----------------------------------------
  Rolling back uninstall of paddlespeech
  Moving to /home/DBL/anaconda3/envs/paddle_env/bin/paddlespeech
   from /tmp/pip-uninstall-4cfsmdx1/paddlespeech
  Moving to /home/DBL/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddlespeech.egg-link
   from /tmp/pip-uninstall-ahl4tbc0/paddlespeech.egg-link
ERROR: Command errored out with exit status 1: /home/DBL/anaconda3/envs/paddle_env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/DBL/MyProject/Project/PaddleSpeech/setup.py'"'"'; __file__='"'"'/home/DBL/MyProject/Project/PaddleSpeech/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```


**Screenshots**
![Error1](https://user-images.githubusercontent.com/45030098/152520969-ccba7fe3-8927-4e55-8c38-659d77423941.png)
![Error2](https://user-images.githubusercontent.com/45030098/152520992-aa00dad8-7b6e-4b04-ade7-52db0c3b4b3e.png)


** Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - GCC/G++ Version:7.5.0
 - Python Version:3.7(in conda virtual env)
 - PaddlePaddle Version:2.2.0
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Information:nvidia1660ti+Driver:470.82
 - CUDA/CUDNN Version:cuda-11.2+cudnn8
 - MKL Version
- TensorRT Version

**Additional context**
安装说需要root权限,我具备这个权限,但我安装paddleSpeech想使用普通使用者权限.
我应该怎么做去成功安装他

**Comment by ccbptm** [comment]
![Error0](https://user-images.githubusercontent.com/45030098/152521815-219efb22-88ee-45b3-b21c-0f0b65bcc88a.png)
![Error2](https://user-images.githubusercontent.com/45030098/152521826-0fd21732-1768-4e8c-8774-7ee2db0e38cf.png)

**Comment by Jackwaterveg** [comment]
## Analysis
You can see that the log contains `Makefile:27: recipe for target 'apt.done' failed`. The command `apt-get` needs  `root`  privilege to install package and it is necessary for installation in `hard` way. You can see [tools/Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile) to get details of this installation. 
## Solutions:
- You can add `sudo` before `apt` like 'sudo apt install xxx' in [tools/Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile)  to install `PaddleSpeech`. 
- If you want to install `PaddleSpeech` not relying on `root` privilege, you can try using 'medium' way.

**Comment by ccbptm** [comment]
Hello,I add `sudo` before apt in the tools/Makefile to isntall,but the show 
![Screenshot from 2022-02-05 11-22-30](https://user-images.githubusercontent.com/45030098/152627091-b0405065-65c4-48f6-87a2-d2d6314296b0.png)
I install Cmake(3.16.0) for my previlege by this way to install paddle:
1.Download cmake-3.16.0-Linux-x86_64.tar.gz
2.use code:`tar -zxvf cmake-3.16.0-Linux-x86_64.tar.gz'
3.edit ~/bashrc to add the path of cmake3.16.0 to this file

and now I install PaddleSpeech this show:
![Screenshot from 2022-02-05 11-22-30](https://user-images.githubusercontent.com/45030098/152628232-4d668251-bc2a-4d6c-b57c-f91014a56327.png)

Can I delete this cmake install in the tools/Makefile to solve this problem?

**Comment by ccbptm** [comment]
> ## Analysis
> You can see that the log contains `Makefile:27: recipe for target 'apt.done' failed`. The command `apt-get` needs `root` privilege to install package and it is necessary for installation in `hard` way. You can see [tools/Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile) to get details of this installation.
> 
> ## Solutions:
> * You can add `sudo` before `apt` like 'sudo apt install xxx' in [tools/Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile)  to install `PaddleSpeech`.
> * If you want to install `PaddleSpeech` not relying on `root` privilege, you can try using 'medium' way.

Can you get my answer to you in 12:14?

**Comment by Jackwaterveg** [comment]
## Analysis
This error happens while installing kenlm, which is also included in [tool/Makefile(kenlm.done)](https://github.com/PaddlePaddle/PaddleSpeech/blob/89e69ee10ee02b875af663146bc46fcf095e812a/tools/Makefile#L39).

## Solutions:
- You can add `sudo` before `cmake` and `make` in line 39. If you see log content like 'administrative prvileges', it means missing `sudo`. You can also add `sudo` in line 54, 56, 58 in    ###[Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile).
- If you do not need `kenlm` you can remve line 36 -> line 40 in [Makefile](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/tools/Makefile)

**Comment by ccbptm** [comment]
Yes ,I do it .And the thing is ok.
but I have a new question.That is how can I judge which version I install?Easy OR meduim OR Hard
Did the project have some solution to judge this?
such as install paddle by
`python`
`import paddle`
`paddle.units.check()'

**Comment by Jackwaterveg** [comment]
# Introduction
For python code, there are no differnece between `easy`, `medium` and `hard` . The core functions are same. The difference between `hard` and `medium` is that in `hard` way, some tools are installed. For example, since `kenlm` is installed, you can train or analysis ( [n-gram-example](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/ngram_lm/s0)) the n-gram language,. since `mfa` is install [mfa-example](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/mfa), you can also use it to do forced align.In a word, the `hard` way has more tools and is  more convenient for developers.

# Judge
If you can run [mfa-example](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/mfa) or  [n-gram-example](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/ngram_lm/s0). It means you install `hard` sucessfully.

**Comment by Jackwaterveg** [comment]
Did you install `PaddlleSpeech` successfully? @mocaibupt
