### ISSUE TITLE
安装PaddleSpeech一直失败

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/PaddleSpeech#1424]
用的是aistudio的notebook环境
会失败两次，第一次提示Permission denied 第二次提示版本冲突
![微信截图_20220207115041](https://user-images.githubusercontent.com/54951765/152722023-138bfd8d-abba-446e-8e22-1017fd26e5ae.png)
![微信截图_20220207115214](https://user-images.githubusercontent.com/54951765/152722052-4a7e3333-2987-4d2a-9224-4b839f360750.png)

**Comment by Jackwaterveg** [comment]
已反馈给平台，会尽快修复

**Comment by Jackwaterveg** [comment]
可以先不在notebook中安装paddlespeech。 在终端中使用命令  `pip3 install paddlespeech` 完成安装。

**Comment by Jackwaterveg** [comment]
去掉`pip install --upgrad pip`, 直接用 `pip install paddlespeech` 完成安装

**Comment by kslz** [comment]
> 

这个依赖让人头秃 我要把tabulate降级然后装blackhole吗
![微信图片_20220211101515](https://user-images.githubusercontent.com/54951765/153528119-18c853e1-c6ff-408a-adf0-a6da1fc36ba1.png)

**Comment by kslz** [comment]
> 去掉`pip install --upgrad pip`, 直接用 `pip install paddlespeech` 完成安装

好像没回复上

**Comment by Jackwaterveg** [comment]
blackhole不影响哈，是aistudio原先预装的包，paddlespeech不会使用
