### ISSUE TITLE
批量合成语音

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/PaddleSpeech#1438]
请问如何批量合成语音音频呢？

**Comment by zh794390558** [comment]
可以先参考下面编码实现

 https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-CLI-Architecture#%E8%AF%AD%E9%9F%B3%E6%A8%A1%E5%9E%8B%E7%BB%84%E5%90%88%E6%A1%88%E4%BE%8B

**Comment by yt605155624** [comment]
也可以尝试使用 examples/csmsc/tts3 里面的 shell 脚本调用
