### ISSUE TITLE
中英混合怎样处理呢？

### ISSUE THREAD

**Issue by logerlink** [PaddlePaddle/PaddleSpeech#1461]
大家好。中英混合的情况怎么处理呢？
如：喜欢唱、跳、rap、篮球
结果：https://raw.githubusercontent.com/logerlink/logerlink.github.io/master/page/2022/result.wav
rap 无法读出来了，请问有什么方案吗？或者参考资料

**Comment by zh794390558** [comment]
目前不支持中英混合。可以用中文的phone模拟rap的发音。

**Comment by logerlink** [comment]
好的
