### ISSUE TITLE
asr --lang de

### ISSUE THREAD

**Issue by luto65** [PaddlePaddle/PaddleSpeech#1467]
dear all,
currently, asr only supports english or chinese. 
Could you please document what needs to be done to add new languages (e.g. german) ?
Thankyou 
Xie Xie.

**Comment by zh794390558** [comment]
You can see https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/librispeech/asr1/README.md#transformerconformer-asr-with-librispeech this doc for introduction how to build english asr, then copy this example and modify to fit for german dataset.
