### ISSUE TITLE
请问paddlespeech支持多语种语音合成吗

### ISSUE THREAD

**Issue by jiusansan222** [PaddlePaddle/PaddleSpeech#1469]
multi-lingual and code switch speech synthesis

**Comment by yt605155624** [comment]
不支持，需要您自己找语料设计模型训练

**Comment by everschen** [comment]
我看paddlebobo不是支持中文和字母吗，比如里面有AI字符，这不算支持多语种吗？

**Comment by yt605155624** [comment]
paddlebobo 用了一种笨办法。比如 AI 他实际上输入给语音合成模型的是 诶挨

**Comment by everschen** [comment]
好吧，这个好像也是一个比较基本的需求，中文结合一些英文单词，难道现在支持的算法模型还没有吗？

**Comment by jerryuhoo** [comment]
我自己试了合并中文和英文的词典，但是会有发音的口音问题。加入language embedding可能可以解决这个问题，但是无法用于code switch，code switch估计需要对每个单词都加入language embedding，感觉太麻烦了。还有一个可能解决方法是按照这篇论文[Learning to Speak Fluently in a Foreign Language](https://arxiv.org/abs/1907.04448) 加入一个speaker classifier，不过好像也没啥效果。
