### ISSUE TITLE
ubuntu20.0.4安装PaddleSpeech失败

### ISSUE THREAD

**Issue by Ironnnnnny** [PaddlePaddle/PaddleSpeech#1476]
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [105 lines of output]
    running develop
    running egg_info
    writing paddlespeech.egg-info/PKG-INFO
    writing dependency_links to paddlespeech.egg-info/dependency_links.txt
    writing entry points to paddlespeech.egg-info/entry_points.txt
    writing requirements to paddlespeech.egg-info/requires.txt
    writing top-level names to paddlespeech.egg-info/top_level.txt
    reading manifest file 'paddlespeech.egg-info/SOURCES.txt'
    writing manifest file 'paddlespeech.egg-info/SOURCES.txt'
    running build_ext
    Creating /usr/local/lib/python3.8/dist-packages/paddlespeech.egg-link (link to .)
    paddlespeech 0.1.1 is already the active version in easy-install.pth
    Installing paddlespeech script to /usr/local/bin
    
    Installed /home/fp/Desktop/PaddleSpeech
    Post Install...
    apt update -y
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
    Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
    Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
    Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
    Fetched 336 kB in 3s (132 kB/s)
    Reading package lists...
    Building dependency tree...
    Reading state information...
    211 packages can be upgraded. Run 'apt list --upgradable' to see them.
    apt install -y bc flac jq vim tig tree pkg-config libsndfile1 libflac-dev libogg-dev libvorbis-dev libboost-dev swig python3-dev
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    Reading package lists...
    Building dependency tree...
    Reading state information...
    bc is already the newest version (1.07.1-2build1).
    bc set to manually installed.
    pkg-config is already the newest version (0.29.1-0ubuntu4).
    pkg-config set to manually installed.
    python3-dev is already the newest version (3.8.2-0ubuntu2).
    python3-dev set to manually installed.
    libsndfile1 is already the newest version (1.0.28-7ubuntu0.1).
    libsndfile1 set to manually installed.
    The following additional packages will be installed:
      libboost1.71-dev libjq1 libonig5 swig4.0 vim-common vim-runtime vim-tiny
    Suggested packages:
      libboost-doc libboost1.71-doc libboost-atomic1.71-dev
      libboost-chrono1.71-dev libboost-container1.71-dev libboost-context1.71-dev
      libboost-contract1.71-dev libboost-coroutine1.71-dev
      libboost-date-time1.71-dev libboost-exception1.71-dev libboost-fiber1.71-dev
      libboost-filesystem1.71-dev libboost-graph1.71-dev
      libboost-graph-parallel1.71-dev libboost-iostreams1.71-dev
      libboost-locale1.71-dev libboost-log1.71-dev libboost-math1.71-dev
      libboost-mpi1.71-dev libboost-mpi-python1.71-dev libboost-numpy1.71-dev
      libboost-program-options1.71-dev libboost-python1.71-dev
      libboost-random1.71-dev libboost-regex1.71-dev
      libboost-serialization1.71-dev libboost-stacktrace1.71-dev
      libboost-system1.71-dev libboost-test1.71-dev libboost-thread1.71-dev
      libboost-timer1.71-dev libboost-type-erasure1.71-dev libboost-wave1.71-dev
      libboost1.71-tools-dev libmpfrc++-dev libntl-dev swig-doc swig-examples
      swig4.0-examples swig4.0-doc ctags vim-doc vim-scripts indent
    The following NEW packages will be installed:
      flac jq libboost-dev libboost1.71-dev libflac-dev libjq1 libogg-dev libonig5
      libvorbis-dev swig swig4.0 tig tree vim vim-runtime
    The following packages will be upgraded:
      vim-common vim-tiny
    2 upgraded, 15 newly installed, 0 to remove and 209 not upgraded.
    Need to get 121 kB/19.4 MB of archives.
    After this operation, 184 MB of additional disk space will be used.
    **Err:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 flac amd64 1.3.3-1build1
      Connection failed [IP: 91.189.91.38 80]
    E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/f/flac/flac_1.3.3-1build1_amd64.deb  Connection failed [IP: 91.189.91.38 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    make: *** [Makefile:28: apt.done] Error 100
    /home/fp/Desktop/PaddleSpeech/setup.py:130: CMD: make, Error: None**
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 259, in <module>
        setup(**setup_info)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 160, in run
        self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
      File "/usr/lib/python3.8/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.8/distutils/util.py", line 303, in execute
        func(*args)
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 146, in _post_install
        check_call("make")
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 133, in check_call
        raise e
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 124, in check_call
        sp.check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    /home/fp/Desktop/PaddleSpeech/tools
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Ironnnnnny** [comment]
How can I solve this problem?

**Comment by zh794390558** [comment]
Please check you apt source, make sure apt can work.

```
Need to get 121 kB/19.4 MB of archives.
After this operation, 184 MB of additional disk space will be used.
**Err:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 flac amd64 1.3.3-1build1
  Connection failed [IP: 91.189.91.38 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/f/flac/flac_1.3.3-1build1_amd64.deb  Connection failed [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
make: *** [Makefile:28: apt.done] Error 100
```

**Comment by Ironnnnnny** [comment]
Reading package lists...
    Building dependency tree...
    Reading state information...
    cmake is already the newest version (3.16.3-1ubuntu1).
    libboost-program-options-dev is already the newest version (1.71.0.0ubuntu2).
    libboost-system-dev is already the newest version (1.71.0.0ubuntu2).
    libboost-thread-dev is already the newest version (1.71.0.0ubuntu2).
    libbz2-dev is already the newest version (1.0.8-2).
    libboost-test-dev is already the newest version (1.71.0.0ubuntu2).
    libeigen3-dev is already the newest version (3.3.7-2).
    build-essential is already the newest version (12.8ubuntu1.1).
    liblzma-dev is already the newest version (5.2.4-1ubuntu1).
    zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1.2).
    0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
    apt-get install -y gcc-5 g++-5 && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50  && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
    Reading package lists...
    Building dependency tree...
    Reading state information...
    **Package g++-5 is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
    However the following packages replace it:
      gcc-10-test-results gcc-9-test-results:i386 gcc-10-test-results:i386
      gcc-9-test-results gcc-8-test-results:i386 gcc-8-test-results
      gcc-7-test-results**
    
    Package gcc-5 is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
    
    **E: Package 'gcc-5' has no installation candidate
    E: Package 'g++-5' has no installation candidate**
    make: *** [Makefile:37: kenlm.done] Error 100
    /home/fp/Desktop/PaddleSpeech/setup.py:130: CMD: make, Error: None
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 259, in <module>
        setup(**setup_info)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 160, in run
        self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
      File "/usr/lib/python3.8/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.8/distutils/util.py", line 303, in execute
        func(*args)
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 146, in _post_install
        check_call("make")
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 133, in check_call
        raise e
      File "/home/fp/Desktop/PaddleSpeech/setup.py", line 124, in check_call
        sp.check_call(
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    /home/fp/Desktop/PaddleSpeech/tools
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Ironnnnnny** [comment]
I already updated apt source, but there was still a problem with the installation

**Comment by zh794390558** [comment]
please check error info:

```
**E: Package 'gcc-5' has no installation candidate
E: Package 'g++-5' has no installation candidate**
make: *** [Makefile:37: kenlm.done] Error 100
```

we recommend using ubuntu16, 20 not test yet.
for some reason, kenlm need gcc5

**Comment by happywch** [comment]
我使用的是ubantu22.04,但是并没有找到gcc5的源并且成功使用，但是我使用了gcc-11-test-results。使用gcc11后会出现 
libsndfile1 : 依赖: libflac12 (>= 1.3.0) 但无法安装它
     sox : 依赖: libsox-fmt-base (= 14.4.2+git20190427-3.4ubuntu1.1) 但是 14.4.2+git20190427-2+deb11u2ubuntu0.22.04.1 正要被安装
           依赖: libsox3 (= 14.4.2+git20190427-3.4ubuntu1.1) 但是 14.4.2+git20190427-2+deb11u2ubuntu0.22.04.1 正要被安装
    E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
这样的问题，我不知道是不是gcc11引起的，但是我不知道怎么解决
