### ISSUE TITLE
训练前的一些问题请教

### ISSUE THREAD

**Issue by everschen** [PaddlePaddle/PaddleSpeech#1478]
1.Download and Extract
Download CSMSC from it's [Official Website](https://test.data-baker.com/data/index/source).
这个地址进去会跳转，哪怕登入后进去也会跳转，是不是链接有更新？还是现在不支持下载了呢？

2. You can download from here [baker_alignment_tone.tar.gz](https://paddlespeech.bj.bcebos.com/MFA/BZNSYP/with_tone/baker_alignment_tone.tar.gz)
这个文件下载后，如果是docker的模式请问放在哪个目录里呢？谢谢

3.Assume the path to the dataset is ~/datasets/BZNSYP. Assume the path to the MFA result of CSMSC is ./baker_alignment_tone. Run the command below to

source path.
preprocess the dataset.
train the model.
synthesize wavs.
synthesize waveform from metadata.jsonl.
synthesize waveform from a text file.
inference using the static model.

./run.sh 
请问这个run.sh是保护了上面从source path开始的所有行为吗？
~/datasets/BZNSYP 请问这里面放哪些dataset呢？
Assume the path to the MFA result of CSMSC is ./baker_alignment_tone 是指和run.sh相同目录吗？

谢谢

**Comment by yt605155624** [comment]
是的 run.sh 包含了所有行为
标贝 CSMSC BZNSYP 是一个东西，下载下来的文件名是 BZNSYP.tar
是的 baker_alignment_tone 放到 run.sh 同级目录
由于我们平时开发是直接在 docker 里，而不是启动某个程序时同时启动 docker ，所以我就是放在这个目录，原始 dataset 的目录可以指定，参考 local/preprocess.sh
链接问题我明天看看，现在手机不太方便

**Comment by yt605155624** [comment]
关于链接，跳转之后上方有个 “业务数据” 的选项，选择语音合成之后，左侧开放数据选择 tts 语音库

**Comment by everschen** [comment]
谢谢，刚才从另一台外网电脑登入找到了这个dataset，我看到是Female的，这个没有选择是吧？
如果我要训练自己的语音模型请问该怎么弄呢？paddlespeech支持吗？
是不是可以拿已经训练好的male的语音模型，然后继续加入自己的发音来训练属于自己的语音模型呢？

多谢！

**Comment by yt605155624** [comment]
可以

**Comment by dtx525942103** [comment]
子龙姐姐，数据下载连接：https://weibo.com/ttarticle/p/show?id=2309404304785795883302&sudaref=www.baidu.com

**Comment by everschen** [comment]
开始运行了，谢谢
