### ISSUE TITLE
关于训练自己语音的问题咨询

### ISSUE THREAD

**Issue by everschen** [PaddlePaddle/PaddleSpeech#1500]
1.标贝是不是只有一个女声的open source的数据集免费下载，其他的是收费的？

2.如果需要训练自己的声音，请问怎么制作数据集，有相关文档吗？https://paddlespeech.readthedocs.io/en/latest/index.html 这里好像没有是吧？

谢谢

**Comment by yt605155624** [comment]
1.是的
2.我们只提供对开源数据集的数据处理和训练，不提供制作自己数据集的方式。

**Comment by everschen** [comment]
好的，谢谢
