### ISSUE TITLE
demos/speech_server 目录中执行  ./server.sh ，客户端访问时报 NameError: name 'Scorer' is not defined

### ISSUE THREAD

**Issue by wang01234** [PaddlePaddle/PaddleSpeech#1503]
demos/speech_server 目录中执行  ./server.sh ，可以正常启动。但通过客户端执行 ASR 时报下来错误，请问该如何解决？

异常如下：
self._ext_scorer = Scorer(beam_alpha, beam_beta,
NameError: name 'Scorer' is not defined

paddlespeech_ctcdecoders 有安装但不起作用。

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/31823117/155889226-992b3f40-1dae-4dae-afac-6b98e8df2b78.png">

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/31823117/155889242-5faaca9b-b748-4a65-9683-015afb11b2a9.png">

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/31823117/155889257-047e7567-7d17-4b63-8267-1a2deecc710b.png">

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/31823117/155889141-43bf6527-186f-4261-b5e7-40e891bb453d.png">

**Comment by lakensei** [comment]
早两天我得到了回复[https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195#discussioncomment-2248949](https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195#discussioncomment-2248949)
重新编译paddlespeech_ctcdecoders后能成功导入
