### ISSUE TITLE
语音合成:  inference:  FatalError: `Segmentation fault` is detected by the operating system.

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#1512]
你好，我在语音合成inference中，遇到以下问题：
路径：/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3/local/inference.sh

问题:
**
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1646127884 (unix time) try "date -d @1646127884" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 73394 (TID 0x7f723740c740) from PID 0 ***]

./local/inference.sh: line 18: 73394 Segmentation fault      python3 ${BIN_DIR}/../inference.py --inference_dir=${train_output_path}/inference --am=fastspeech2_aishell3 --voc=pwgan_aishell3 --text=${BIN_DIR}/../sentences.txt --output_dir=${train_output_path}/pd_infer_out --phones_dict=dump/phone_id_map.txt --speaker_dict=dump/speaker_id_map.txt --spk_id=0
**

我的 cuda是 11.2 ,    cudnn 是 8,  paddlepaddle-gpu == 2.2.2
请问这个问题是什么原因呢，怎么解决这个问题呢？

**Comment by yt605155624** [comment]
我们一般的开发环境是 cuda 10.2 , cudnn 7.6， 没有在您这么高版本的 cuda 上测试过，您这边有什么一定要用静态图推理的需求嘛？
如果采用 local/synthesize_e2e.sh 会报错嘛（可以看代码，默认是保存出静态模型然后 load 进来再推理）

**Comment by Tian14267** [comment]
> 我们一般的开发环境是 cuda 10.2 没有在您这么高版本的 cuda 上测试过，您这边有什么一定要用静态图推理的需求嘛？ 如果采用 local/synthesize_e2e.sh 会报错嘛（可以看代码，默认是保存出静态模型然后 load 进来再推理）

你好，我这边有以下情况：
1：synthesize_e2e.sh 在11.2 上面是OK的；
2：synthesize_e2e.sh的多线程并发会有问题，会报以下错误：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1646130944 (unix time) try "date -d @1646130944" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x305f7075) received by PID 114268 (TID 0x7fcfd5de8700) from PID 811561077 ***]

段错误
```
这种并发错误，在cpu版本上也会出现。请问这个该怎么解决呢

**Comment by Tian14267** [comment]
@yt605155624

**Comment by yt605155624** [comment]
如果您并不一定要在 synthesize_e2e.sh 里面使用静态图推理，可以尝试删除这一行 https://github.com/PaddlePaddle/PaddleSpeech/blob/26d413ce8f5f62938487fdf0e13a14e3c098f892/examples/csmsc/tts3/local/synthesize_e2e.sh#L25
即直接使用动态图推理，而不是转换成静态图之后再 load 进来再推理
多线程、并发，我没尝试用这些方式呢

**Comment by yt605155624** [comment]
您好，您可以帮忙看下 csmsc 目录下的 inference.sh 在您的环境下是否会报错嘛？
 /PaddlePaddle/PaddleSpeech/tree/develop/examples/csmsc/tts3/local/inference.sh

**Comment by yt605155624** [comment]
用户用了 docker 之后可以解决问题
