### ISSUE TITLE
不同的数据集会影响vocoder时间吗？

### ISSUE THREAD

**Issue by lawo123** [PaddlePaddle/PaddleSpeech#1522]
为什么我测试英文数据集和中文数据集的vocoder的时间差很多？

**Comment by yt605155624** [comment]
会，英文数据集音频时长比较长，测试时间没有意义，应该测试 RTF

**Comment by lawo123** [comment]
> 文数据集音频时长比较长，测试时间没有意义，

英文和中文的RTF也不一样，中文的要比英文的RTF高很多，这正常吗？

**Comment by yt605155624** [comment]
你是用 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/gan_vocoder/synthesize.py 测试的 RTF 嘛？ 我们主要关注中文，其实英文模型上我没有测过 RTF
一般 RTF 都是固定数据集用不同模型比较，固定模型比较不同数据集不知道是否有意义？
您的这种现象可能是正常的，因为英文的数据（ljspeech）比中文的数据（csmsc）长很多, 数据过长可能超过 GPU 并行的上限就变慢了
分享一个有意思的现象，我们在 Multi_band melgan 上把 csmsc 的测试集 mel 切分为原来的 1/10, 推理时间也不会变短，可能是因为 csmsc 的数据长度本身就没有用到 GPU 的并行能力
感兴趣可以把英文的音频长度截取为 csmsc 类似的长度再试试（直接对 mel 切片）

**Comment by lawo123** [comment]
> 主要关注中文，其实英文模型上我没有测过 RTF

我是用paddlespeech/t2s/exps/synthesize_e2e.py，在CPU测的Multi_band melgan ，截取vocoder的时间算RTF约0.2，但是原论文写的RTF约0.03

![GnThwuA9EY](https://user-images.githubusercontent.com/44777088/156483336-eb4f21ce-b223-4b54-a4a2-a2a2d5329c83.png)

**Comment by yt605155624** [comment]
Paddlespeech TTS csmsc 上的 RTF 参考 https://github.com/PaddlePaddle/PaddleSpeech/wiki/TTS-Benchmark
我们的模型的采样率是 24kHz 的，论文上是 16kHz 的，这是一个因素，此外我们的超参数与论文并不完全一致，所以不能直接比 RTF

**Comment by lawo123** [comment]
感谢您的回复。
我使用paddle的speedyspeech生成mel然后用tensorflowTTS的mb-melgan做声码器，出来的音频声音特别小。请问需要修改什么配置吗？可以这样使用吗？两个模块是在同一数据集下的预训练模型

**Comment by yt605155624** [comment]
tensorflowTTS 我没有用过，但是声学模型和声码器起码要保证特征一致才能串联使用（采样率，hop_size, win_lengh 等），并且我们对 mel 特征进行了 norm, speedyspeech 的输出是有 denorm 操作的，但是你要保证tensorflowTTS的声码器输入是否需要 norm.. 
by the way, paddlespeech 也提供了 mb-melgan

**Comment by lawo123** [comment]
paddlespeech 提供了的 mb-melgan太慢了，所以才想用tensorflowTTS，但是tensorflowTTS的中文效果不太好，所以想着用paddlespeech的speedyspeech和tensorflowTTS的mb-melgan
