### ISSUE TITLE
Parallel WaveGAN 至少训练多少步

### ISSUE THREAD

**Issue by liyuhui** [PaddlePaddle/PaddleSpeech#1526]
我自己按照csmsc格式搜集整理的语料来训练FastSpecch2+Parallel WaveGAN模型 FastSpecch2已完成153000步训练 请问Parallel WaveGAN至少需要训练到多少步 教程里要训练到400000步 目的是为了快速验证自己搜集的语料能否训练成功

**Comment by yt605155624** [comment]
40W 的时候其实早就收敛了，真正使用的时候应该不需要训练这么久，但是我这边历史的收敛曲线没有了，我们现在 5000 步会保存一个模型，我建议您把这个数字改成更小，比如 1000， 可以保存一个模型出来大概听听效果（使用 ./run.sh --stage 2 --stop_stage 2）, 另外可以用 visualdl 看下收敛曲线 
```
cd exp/default/
visualdl --host 0.0.0.0 --logdir . --port 8125
```

**Comment by liyuhui** [comment]
> 40W 的时候其实早就收敛了，真正使用的时候应该不需要训练这么久，但是我这边历史的收敛曲线没有了，我们现在 5000 步会保存一个模型，我建议您把这个数字改成更小，比如 1000， 可以保存一个模型出来大概听听效果（使用 ./run.sh --stage 2 --stop_stage 2）, 另外可以用 visualdl 看下收敛曲线
> 
> ```
> cd exp/default/
> visualdl --host 0.0.0.0 --logdir . --port 8125
> ```

好的 感谢
