### ISSUE TITLE
语音识别成文字时候报错:提示MemoryError: (ResourceExhausted) Fail to alloc memory of 5189386240 size, error code is 12.

### ISSUE THREAD

**Issue by xueyangkk** [PaddlePaddle/PaddleSpeech#1527]
华为云AI服务器 2核心8G  无GPU 

执行的指令 
`
paddlespeech asr --input a.wav 

`
a.wav 文件 18969704  

报错信息 
`
(/opt/ai/PaddleSpeech/tools/venv) root@ecs-58b4:/opt/workSpace# paddlespeech asr --input a.wav 
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: paddlespeech_ctcdecoders in /opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages (0.1.1)
/opt/ai/PaddleSpeech/tools/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py:114: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  DeprecationWarning,
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2022-03-03 16:44:46,388] [    INFO] - Preprocess audio_file:/opt/workSpace/a.wav
[2022-03-03 16:44:46,388] [    INFO] - get the preprocess conf
[2022-03-03 16:44:46,408] [    INFO] - read the audio file
[2022-03-03 16:44:46,413] [    INFO] - audio shape: (9484748,)
[2022-03-03 16:44:51,779] [    INFO] - audio feat shape: [1, 59278, 80]
MemoryError: (ResourceExhausted) Fail to alloc memory of 5189386240 size, error code is 12.
  [Hint: Expected error == 0, but received error:12 != 0:0.] (at /paddle/paddle/fluid/memory/detail/system_allocator.cc:62)
  [operator < conv2d > error](/opt/ai/PaddleSpeech/tools/venv) root@ecs-58b4:/opt/workSpace#
`

**Comment by yt605155624** [comment]
1. 请验证用我们提供的示例音频是否会报错
2. 可以把您使用的 a.wav 上传一下

**Comment by xueyangkk** [comment]
示例音频 不会报错 ，可以顺利识别出来 。速度略慢而已 。  
http://resource.xtdshop.com/a.wav

**Comment by yt605155624** [comment]
音频太长了，目前 asr 默认能处理的音频的长度是 50s 以下，即使我们能处理更长的音频，也需要先把你的音频读到内存里，而你的内存太小了，需要先用 webrtc vad 等工具裁剪音频后再调用 asr 模型

**Comment by xueyangkk** [comment]
抱歉 求教下 我们需求音频内容会很长很长 ，求教在不分割视频的情况下 ，如何使用长音频。 目前服务器是8G 都不可以吗 ？

**Comment by yt605155624** [comment]
现在的情况是，即使你的内存够了，我们的模型处理的上限也是 50s, 所以你必须裁剪你的视频音频

**Comment by xueyangkk** [comment]
能求教下 为什么模型上线只支持50s 这么奇怪的 要求呢 ？或者说的更详细些 谢谢

**Comment by yt605155624** [comment]
因为现在默认的模型是 comformer 模型，他和 transformer 模型类似，这是一个非自回归的模型，在 nlp 领域也有广泛的应用，Transformer 模型里面有 position encoding, 需要限制输入的最大长度，asr 模型的默认长度是 5000 帧，https://github.com/PaddlePaddle/PaddleSpeech/blob/6750770e54d02b38ed6e934b73c574a3525dd767/paddlespeech/s2t/modules/embedding.py#L60 按照设置， 1s 的音频是 100 帧， 5000 帧对应 50s 的音频，超出则会报 https://github.com/PaddlePaddle/PaddleSpeech/issues/1529 的错， 在 nlp 领域这个值通常是 768，即使你使用 nlp 模型也不能无脑输入巨长文本，更多细节请参考 transformer 和 conformer 论文

**Comment by zHaOshuAnGye** [comment]
> 因为现在默认的模型是 comformer 模型，他和 transformer 模型类似，这是一个非自回归的模型，在 nlp 领域也有广泛的应用，Transformer 模型里面有 position encoding, 需要限制输入的最大长度，asr 模型的默认长度是 5000 帧，
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/6750770e54d02b38ed6e934b73c574a3525dd767/paddlespeech/s2t/modules/embedding.py#L60
> 
> 按照设置， 1s 的音频是 100 帧， 5000 帧对应 50s 的音频，超出则会报 #1529 的错， 在 nlp 领域这个值通常是 768，即使你使用 nlp 模型也不能无脑输入巨长文本，更多细节请参考 transformer 和 conformer 论文

小姐姐，我想请问一下，是用gpu也需要读进内存里吗，我发现我的服务器有时候只能30s成功运行，50s、40s都会报这个错误。gpu一般都是空闲的，内存是省的不太多。
