### ISSUE TITLE
安装 PaddleSpeech 时候出错 

### ISSUE THREAD

**Issue by xueyangkk** [PaddlePaddle/PaddleSpeech#1534]
本地电脑  ubuntu 20.04 

前面都没有任何问题 运行 
`
pip install -e .[develop] -i https://pypi.tuna.tsinghua.edu.cn/simple
`
报错信息如下

`Installing collected packages: paddlespeech, gpustat, coverage, ConfigArgParse
  Running setup.py develop for paddlespeech
    ERROR: Command errored out with exit status 1:
     command: /home/zy/workSpace/PaddleSpeech/tools/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zy/workSpace/PaddleSpeech/setup.py'"'"'; __file__='"'"'/home/zy/workSpace/PaddleSpeech/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/zy/workSpace/PaddleSpeech/
    Complete output (62 lines):
    running develop
    running egg_info
    writing paddlespeech.egg-info/PKG-INFO
    writing dependency_links to paddlespeech.egg-info/dependency_links.txt
    writing entry points to paddlespeech.egg-info/entry_points.txt
    writing requirements to paddlespeech.egg-info/requires.txt
    writing top-level names to paddlespeech.egg-info/top_level.txt
    reading manifest file 'paddlespeech.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'paddlespeech.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech.egg-link (link to .)
    Adding paddlespeech 0.1.2 to easy-install.pth file
    Installing paddlespeech script to /home/zy/workSpace/PaddleSpeech/tools/venv/bin
    Installing paddlespeech_client script to /home/zy/workSpace/PaddleSpeech/tools/venv/bin
    Installing paddlespeech_server script to /home/zy/workSpace/PaddleSpeech/tools/venv/bin
    
    Installed /home/zy/workSpace/PaddleSpeech
    Post Install...
    apt update -y
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    Reading package lists...
    E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    E: Unable to lock directory /var/lib/apt/lists/
    W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
    W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
    make: *** [Makefile:27: apt.done] Error 100
    /home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    /home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:720: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
      % (opt, underscore_opt)
    /home/zy/workSpace/PaddleSpeech/setup.py:141: CMD: make, Error: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/zy/workSpace/PaddleSpeech/setup.py", line 274, in <module>
        setup(**setup_info)
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/zy/workSpace/PaddleSpeech/setup.py", line 171, in run
        self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/distutils/util.py", line 291, in execute
        func(*args)
      File "/home/zy/workSpace/PaddleSpeech/setup.py", line 157, in _post_install
        check_call("make")
      File "/home/zy/workSpace/PaddleSpeech/setup.py", line 144, in check_call
        raise e
      File "/home/zy/workSpace/PaddleSpeech/setup.py", line 138, in check_call
        executable="/bin/bash" if shell else executable)
      File "/home/zy/workSpace/PaddleSpeech/tools/venv/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    /home/zy/workSpace/PaddleSpeech/tools
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/zy/workSpace/PaddleSpeech/tools/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/zy/workSpace/PaddleSpeech/setup.py'"'"'; __file__='"'"'/home/zy/workSpace/PaddleSpeech/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

`

**Comment by yt605155624** [comment]
Permission denied 需要 sudo 权限

**Comment by cjy6666666** [comment]
开了sudo权限还是不行，求助

**Comment by cjy6666666** [comment]
开了sudo权限还是不行，求助

**Comment by olive900** [comment]
建议paddle用2.2.2版本的。

**Comment by linkec** [comment]
建议使用 Docker 部署哦，可以保证系统环境的独立性，而且不需要自行编译

**Comment by tone2158** [comment]
> 建议使用 Docker 部署哦，可以保证系统环境的独立性，而且不需要自行编译

想问一下有没有用过docker部署过这个版本的paddle:2.4.1-jupyter？有gcc的报错想请教一下

**Comment by linkec** [comment]
> > 建议使用 Docker 部署哦，可以保证系统环境的独立性，而且不需要自行编译
> 
> 想问一下有没有用过docker部署过这个版本的paddle:2.4.1-jupyter？有gcc的报错想请教一下

报什么错？

**Comment by tone2158** [comment]
> > > 建议使用 Docker 部署哦，可以保证系统环境的独立性，而且不需要自行编译
> > 
> > 
> > 想问一下有没有用过docker部署过这个版本的paddle:2.4.1-jupyter？有gcc的报错想请教一下
> 
> 报什么错？


是跟gcc相关的 我conda安装了 gcc和gxx 还是报这个错：



/opt/conda/compiler_compat/ld: cannot find /lib64/libpthread.so.0: No such file or directory
/opt/conda/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1


ERROR: Failed building wheel for pyworld
Running setup.py clean for pyworld
Building wheel for webrtcvad (setup.py) ... error
ERROR: Command errored out with exit status 1:
