### ISSUE TITLE
能否提供wenetspeech 的预训练权重？

### ISSUE THREAD

**Issue by heguodui** [PaddlePaddle/PaddleSpeech#1555]
由于训练资源有限，能否提供已经训练好的wenetspeech数据集的权重，以此方便大家做模型的微调，也避免重复训练造成资源浪费

**Comment by yt605155624** [comment]
执行完 paddlespeech asr 命令行会自动下载到 ~/.paddlespeech/models 里，或者到 https://github.com/PaddlePaddle/PaddleSpeech/blob/baec77e16049578b336f1286abb1f5d15c99f64b/paddlespeech/cli/asr/infer.py#L49 下载

**Comment by heguodui** [comment]
似乎这个是infer版本的权重，是否和训练版本的权重在精度上保持一致呢

**Comment by yt605155624** [comment]
PaddleSpeech 目前不提供 wenetspeech 上的训练代码，相应的权重是从 wenet 的开源模型转过来的，finetune 直接加载权重继续训练即可，训练的版本有可能会保存优化器的相关参数，但是这不是 finetune 步骤必须的

**Comment by tcexeexe** [comment]
想请教下，如果要在词典中添加新词（英文字母），那么是否还可以以finetune的形式训练呢？

**Comment by Jackwaterveg** [comment]
@tcexeexe 可以，但是需要去除模型的最后的映射层，让映射层完全重新训练
