### ISSUE TITLE
使用预训练模型内存不足

### ISSUE THREAD

**Issue by zHaOshuAnGye** [PaddlePaddle/PaddleSpeech#1557]
您好，我在使用如下代码进行语音识别的时候，每次输入一条40s的语音，输入多次。查看资源使用情况，跑的过程中用到了40g+的内存，且内存会随着每次的输入增加，跑着跑着就死机了。。为什么跑测试需要这么大的内存呢，是我哪里写错了吗，有什么解决的办法呢，求教了拜托🙏🏻

text = asr_executor(
      model='conformer_wenetspeech',
      lang='zh',
      sample_rate=16000,
      config=None,  # Set `config` and `ckpt_path` to None to use pretrained model.
      ckpt_path=None,
      audio_file= 一条40s的wav16k语音,
      force_yes=False,
      device='gpu:0')

text = text_executor(
      text=text,
      task='punc',
      model='ernie_linear_p7_wudao',
      lang='zh',
      config=None,
      ckpt_path=None,
      punc_vocab=None,
      device='gpu:0')

**Comment by zh794390558** [comment]
语音太长了40s，一般都是3~10s左右。

**Comment by zHaOshuAnGye** [comment]
> 语音太长了40s，一般都是3~10s左右。

好的，谢谢您！~~
再麻烦请问一下，对较长语音直接按照时间（例如10s）切分识别后拼接，因为可能会切成不完整的句子，拼接后会不会效果很不好，有必要用vad切分成较短的语音再拼接吗？
谢谢！

**Comment by zh794390558** [comment]
不需要拼接。识别保证vad不切到语音即可。
