### ISSUE TITLE
HuggingFace 上面的 PaddleSpeechASR 怎么使用

### ISSUE THREAD

**Issue by dtMndas** [PaddlePaddle/PaddleSpeech#1579]
https://huggingface.co/spaces/KPatrick/PaddleSpeechASR  上传到HuggingFace 上面的模型，怎么用transformers 模块去使用

**Comment by zh794390558** [comment]
可以看下代码 https://huggingface.co/spaces/KPatrick/PaddleSpeechASR/blob/main/app.py#L10
目前是用默认的配置。

**Comment by dtMndas** [comment]
感谢
