### ISSUE TITLE
如果下载包?

### ISSUE THREAD

**Issue by xueyangkk** [PaddlePaddle/PaddleSpeech#1580]
求教下  我想把语音识别 集成到我们的项目里   

```
import paddle

from paddlespeech.cli import ASRExecutor
from paddlespeech.cli import 
```

时候提示没有这些包 ，请问 我需要去哪里下载这些包？如何下载 ？非常感谢

**Comment by zh794390558** [comment]
默认会下载模型资源。

https://huggingface.co/spaces/KPatrick/PaddleSpeechASR/blob/main/app.py#L10

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/cli/asr/infer.py#L533

**Comment by dtMndas** [comment]
可以查看安装文档 先安装相关的packages https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md
