### ISSUE TITLE
安装时无法获取部分文件

### ISSUE THREAD

**Issue by Enoryl** [PaddlePaddle/PaddleSpeech#1585]
在Ubuntu 20.04.2 LTS执行安装命令`pip install -e .[develop] -i https://pypi.tuna.tsinghua.edu.cn/simple`时出现
Running setup.py develop for paddlespeech
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [125 lines of output]
        running develop
        running egg_info
        writing paddlespeech.egg-info/PKG-INFO
        writing dependency_links to paddlespeech.egg-info/dependency_links.txt
        writing entry points to paddlespeech.egg-info/entry_points.txt
        writing requirements to paddlespeech.egg-info/requires.txt
        writing top-level names to paddlespeech.egg-info/top_level.txt
        reading manifest file 'paddlespeech.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'paddlespeech.egg-info/SOURCES.txt'
        running build_ext
        Creating /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech.egg-link (link to .)
        Adding paddlespeech 0.2.0 to easy-install.pth file
        Installing paddlespeech script to /home/ai2021/PaddleSpeech/tools/venv/bin
        Installing paddlespeech_client script to /home/ai2021/PaddleSpeech/tools/venv/bin
        Installing paddlespeech_server script to /home/ai2021/PaddleSpeech/tools/venv/bin

        Installed /home/ai2021/PaddleSpeech
        Post Install...
        apt update -y

        WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

        Get:1 file:/var/nccl-repo-2.7.8-ga-cuda10.1  InRelease
        Ign:1 file:/var/nccl-repo-2.7.8-ga-cuda10.1  InRelease
        Get:2 file:/var/nccl-repo-2.7.8-ga-cuda10.1  Release [574 B]
        Get:2 file:/var/nccl-repo-2.7.8-ga-cuda10.1  Release [574 B]
        Hit:4 http://cn.archive.ubuntu.com/ubuntu focal InRelease
        Hit:5 http://cn.archive.ubuntu.com/ubuntu focal-updates InRelease
        Hit:6 http://cn.archive.ubuntu.com/ubuntu focal-backports InRelease
        Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
        Hit:8 https://download.sublimetext.com apt/stable/ InRelease
        Hit:9 https://download.docker.com/linux/ubuntu focal InRelease
        Reading package lists...
        Building dependency tree...
        Reading state information...
        163 packages can be upgraded. Run 'apt list --upgradable' to see them.
        apt install -y bc flac jq vim tig tree pkg-config libsndfile1 libflac-dev libogg-dev libvorbis-dev libboost-dev swig python3-dev

        WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

        Reading package lists...
        Building dependency tree...
        Reading state information...
        bc is already the newest version (1.07.1-2build1).
        bc set to manually installed.
        pkg-config is already the newest version (0.29.1-0ubuntu4).
        pkg-config set to manually installed.
        tree is already the newest version (1.8.0-1).
        libsndfile1 is already the newest version (1.0.28-7ubuntu0.1).
        libsndfile1 set to manually installed.
        vim is already the newest version (2:8.1.2269-1ubuntu5.7).
        The following additional packages will be installed:
          libboost1.71-dev libexpat1-dev libjq1 libonig5 libpython3-dev
          libpython3.8-dev python3-distutils python3-lib2to3 python3.8-dev swig4.0
          zlib1g-dev
        Suggested packages:
          libboost-doc libboost1.71-doc libboost-atomic1.71-dev
          libboost-chrono1.71-dev libboost-container1.71-dev libboost-context1.71-dev
          libboost-contract1.71-dev libboost-coroutine1.71-dev
          libboost-date-time1.71-dev libboost-exception1.71-dev libboost-fiber1.71-dev
          libboost-filesystem1.71-dev libboost-graph1.71-dev
          libboost-graph-parallel1.71-dev libboost-iostreams1.71-dev
          libboost-locale1.71-dev libboost-log1.71-dev libboost-math1.71-dev
          libboost-mpi1.71-dev libboost-mpi-python1.71-dev libboost-numpy1.71-dev
          libboost-program-options1.71-dev libboost-python1.71-dev
          libboost-random1.71-dev libboost-regex1.71-dev
          libboost-serialization1.71-dev libboost-stacktrace1.71-dev
          libboost-system1.71-dev libboost-test1.71-dev libboost-thread1.71-dev
          libboost-timer1.71-dev libboost-type-erasure1.71-dev libboost-wave1.71-dev
          libboost1.71-tools-dev libmpfrc++-dev libntl-dev swig-doc swig-examples
          swig4.0-examples swig4.0-doc
        The following NEW packages will be installed:
          flac jq libboost-dev libboost1.71-dev libexpat1-dev libflac-dev libjq1
          libogg-dev libonig5 libpython3-dev libpython3.8-dev libvorbis-dev
          python3-dev python3-distutils python3-lib2to3 python3.8-dev swig swig4.0 tig
          zlib1g-dev
        0 upgraded, 20 newly installed, 0 to remove and 163 not upgraded.
        Need to get 121 kB/16.5 MB of archives.
        After this operation, 173 MB of additional disk space will be used.
        Err:1 http://cn.archive.ubuntu.com/ubuntu focal/universe amd64 flac amd64 1.3.3-1build1
          Connection failed [IP: 91.189.91.39 80]
        E: Failed to fetch http://cn.archive.ubuntu.com/ubuntu/pool/universe/f/flac/flac_1.3.3-1build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
        E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
        make: *** [Makefile:28: apt.done] Error 100
        /home/ai2021/PaddleSpeech/tools
        /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:742: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
          % (opt, underscore_opt)
        /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:742: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
          % (opt, underscore_opt)
        /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        /home/ai2021/PaddleSpeech/setup.py:141: CMD: make, Error: None
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/ai2021/PaddleSpeech/setup.py", line 274, in <module>
            setup(**setup_info)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
            return distutils.core.setup(**attrs)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/home/ai2021/PaddleSpeech/setup.py", line 171, in run
            self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 335, in execute
            util.execute(func, args, msg, dry_run=self.dry_run)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 322, in execute
            func(*args)
          File "/home/ai2021/PaddleSpeech/setup.py", line 157, in _post_install
            check_call("make")
          File "/home/ai2021/PaddleSpeech/setup.py", line 144, in check_call
            raise e
          File "/home/ai2021/PaddleSpeech/setup.py", line 138, in check_call
            executable="/bin/bash" if shell else executable)
          File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/subprocess.py", line 363, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [125 lines of output]
    running develop
    running egg_info
    writing paddlespeech.egg-info/PKG-INFO
    writing dependency_links to paddlespeech.egg-info/dependency_links.txt
    writing entry points to paddlespeech.egg-info/entry_points.txt
    writing requirements to paddlespeech.egg-info/requires.txt
    writing top-level names to paddlespeech.egg-info/top_level.txt
    reading manifest file 'paddlespeech.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'paddlespeech.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/paddlespeech.egg-link (link to .)
    Adding paddlespeech 0.2.0 to easy-install.pth file
    Installing paddlespeech script to /home/ai2021/PaddleSpeech/tools/venv/bin
    Installing paddlespeech_client script to /home/ai2021/PaddleSpeech/tools/venv/bin
    Installing paddlespeech_server script to /home/ai2021/PaddleSpeech/tools/venv/bin

    Installed /home/ai2021/PaddleSpeech
    Post Install...
    apt update -y

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

    Get:1 file:/var/nccl-repo-2.7.8-ga-cuda10.1  InRelease
    Ign:1 file:/var/nccl-repo-2.7.8-ga-cuda10.1  InRelease
    Get:2 file:/var/nccl-repo-2.7.8-ga-cuda10.1  Release [574 B]
    Get:2 file:/var/nccl-repo-2.7.8-ga-cuda10.1  Release [574 B]
    Hit:4 http://cn.archive.ubuntu.com/ubuntu focal InRelease
    Hit:5 http://cn.archive.ubuntu.com/ubuntu focal-updates InRelease
    Hit:6 http://cn.archive.ubuntu.com/ubuntu focal-backports InRelease
    Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
    Hit:8 https://download.sublimetext.com apt/stable/ InRelease
    Hit:9 https://download.docker.com/linux/ubuntu focal InRelease
    Reading package lists...
    Building dependency tree...
    Reading state information...
    163 packages can be upgraded. Run 'apt list --upgradable' to see them.
    apt install -y bc flac jq vim tig tree pkg-config libsndfile1 libflac-dev libogg-dev libvorbis-dev libboost-dev swig python3-dev

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

    Reading package lists...
    Building dependency tree...
    Reading state information...
    bc is already the newest version (1.07.1-2build1).
    bc set to manually installed.
    pkg-config is already the newest version (0.29.1-0ubuntu4).
    pkg-config set to manually installed.
    tree is already the newest version (1.8.0-1).
    libsndfile1 is already the newest version (1.0.28-7ubuntu0.1).
    libsndfile1 set to manually installed.
    vim is already the newest version (2:8.1.2269-1ubuntu5.7).
    The following additional packages will be installed:
      libboost1.71-dev libexpat1-dev libjq1 libonig5 libpython3-dev
      libpython3.8-dev python3-distutils python3-lib2to3 python3.8-dev swig4.0
      zlib1g-dev
    Suggested packages:
      libboost-doc libboost1.71-doc libboost-atomic1.71-dev
      libboost-chrono1.71-dev libboost-container1.71-dev libboost-context1.71-dev
      libboost-contract1.71-dev libboost-coroutine1.71-dev
      libboost-date-time1.71-dev libboost-exception1.71-dev libboost-fiber1.71-dev
      libboost-filesystem1.71-dev libboost-graph1.71-dev
      libboost-graph-parallel1.71-dev libboost-iostreams1.71-dev
      libboost-locale1.71-dev libboost-log1.71-dev libboost-math1.71-dev
      libboost-mpi1.71-dev libboost-mpi-python1.71-dev libboost-numpy1.71-dev
      libboost-program-options1.71-dev libboost-python1.71-dev
      libboost-random1.71-dev libboost-regex1.71-dev
      libboost-serialization1.71-dev libboost-stacktrace1.71-dev
      libboost-system1.71-dev libboost-test1.71-dev libboost-thread1.71-dev
      libboost-timer1.71-dev libboost-type-erasure1.71-dev libboost-wave1.71-dev
      libboost1.71-tools-dev libmpfrc++-dev libntl-dev swig-doc swig-examples
      swig4.0-examples swig4.0-doc
    The following NEW packages will be installed:
      flac jq libboost-dev libboost1.71-dev libexpat1-dev libflac-dev libjq1
      libogg-dev libonig5 libpython3-dev libpython3.8-dev libvorbis-dev
      python3-dev python3-distutils python3-lib2to3 python3.8-dev swig swig4.0 tig
      zlib1g-dev
    0 upgraded, 20 newly installed, 0 to remove and 163 not upgraded.
    Need to get 121 kB/16.5 MB of archives.
    After this operation, 173 MB of additional disk space will be used.
    Err:1 http://cn.archive.ubuntu.com/ubuntu focal/universe amd64 flac amd64 1.3.3-1build1
      Connection failed [IP: 91.189.91.39 80]
    E: Failed to fetch http://cn.archive.ubuntu.com/ubuntu/pool/universe/f/flac/flac_1.3.3-1build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    make: *** [Makefile:28: apt.done] Error 100
    /home/ai2021/PaddleSpeech/tools
    /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:742: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/dist.py:742: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
      % (opt, underscore_opt)
    /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    /home/ai2021/PaddleSpeech/setup.py:141: CMD: make, Error: None
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/ai2021/PaddleSpeech/setup.py", line 274, in <module>
        setup(**setup_info)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/ai2021/PaddleSpeech/setup.py", line 171, in run
        self.execute(_post_install, (self.install_lib, ), msg="Post Install...")
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/site-packages/setuptools/_distutils/util.py", line 322, in execute
        func(*args)
      File "/home/ai2021/PaddleSpeech/setup.py", line 157, in _post_install
        check_call("make")
      File "/home/ai2021/PaddleSpeech/setup.py", line 144, in check_call
        raise e
      File "/home/ai2021/PaddleSpeech/setup.py", line 138, in check_call
        executable="/bin/bash" if shell else executable)
      File "/home/ai2021/PaddleSpeech/tools/venv/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

有尝试过修改dns，但似乎没有解决问题

**Comment by zh794390558** [comment]
确保apt安装包不会出错
```
    After this operation, 173 MB of additional disk space will be used.
    Err:1 http://cn.archive.ubuntu.com/ubuntu focal/universe amd64 flac amd64 1.3.3-1build1
      Connection failed [IP: 91.189.91.39 80]
    E: Failed to fetch http://cn.archive.ubuntu.com/ubuntu/pool/universe/f/flac/flac_1.3.3-1build1_amd64.deb  Connection failed [IP: 91.189.91.39 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    make: *** [Makefile:28: apt.done] Error 100
```
