### ISSUE TITLE
windows 安装的时候 报gbk codec can't decode byte 0x80 in position 5365

### ISSUE THREAD

**Issue by lindychan** [PaddlePaddle/PaddleSpeech#1594]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3f/84/5afa0f957d1f3053478882b40565f454f8755532b696224e880600a3d35a/soxbindings-1.2.3.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\conda1\envs\paddle-detection\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chenlin\\AppData\\Local\\Temp\\pip-install-dj_x2shn\\soxbindings\\setup.py'"'"'; __file__='"'"'C:\\Users\\ch
enlin\\AppData\\Local\\Temp\\pip-install-dj_x2shn\\soxbindings\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'
))' egg_info --egg-base 'C:\Users\chenlin\AppData\Local\Temp\pip-install-dj_x2shn\soxbindings\pip-egg-info'
         cwd: C:\Users\chenlin\AppData\Local\Temp\pip-install-dj_x2shn\soxbindings\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\chenlin\AppData\Local\Temp\pip-install-dj_x2shn\soxbindings\setup.py", line 107, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 5365: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

If you've found a bug then please create an issue with the following information:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - GCC/G++ Version [e.g. 8.3]
 - Python Version [e.g. 3.7]
 - PaddlePaddle Version [e.g. 2.0.0]
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. Tesla V100-SXM2-32GB/440.64.00]
 - CUDA/CUDNN Version [e.g. cuda-10.2]
 - MKL Version
- TensorRT Version

**Additional context**

**Comment by zh794390558** [comment]
`UnicodeDecodeError: 'gbk' codec`应该是python的编码问题试试UTF-8

**Comment by lindychan** [comment]
![image](https://user-images.githubusercontent.com/4707768/159646029-81fc1ffb-7510-4b94-8afb-368235411afd.png)
还是不行

**Comment by zh794390558** [comment]
soxbindings 不支持win系统的。

**Comment by lindychan** [comment]
> soxbindings 不支持win系统的。

are you sure?

**Comment by zh794390558** [comment]
参看 https://github.com/pseeth/soxbindings#install-from-pip
