### ISSUE TITLE
👨🏻‍🦱 TTS 男性音色（Male speaker）（如何更换音色）

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#1620]
there are no single speaker datasets for male, but in multi-speaker tts datasets(aishell3, vctk)，there are Male speakers,
You can find speaker_id_map.txt in `~/.paddlespeech/models/fastspeech2_aishell3-zh/fastspeech2_nosil_aishell3_ckpt_0.4/speaker_id_map.txt` or `~/.paddlespeech/models/fastspeech2_vctk-en/fastspeech2_nosil_vctk_ckpt_0.5/speaker_id_map.txt` and check the gender of speakers in the origin datasets(aishell3/vctk), then, use `--spk_id` to use the speaker you want in multi-speaker tts datasets

more usage for multi-speaker cli https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech

also see https://github.com/PaddlePaddle/PaddleSpeech/issues/1373

**Comment by yt605155624** [comment]
Recommended Male Speaker: 

VCTK: spk_id = 7
```bash 
paddlespeech tts --am fastspeech2_vctk --voc pwgan_vctk --input "Life was like a box of chocolates, you never know what you're gonna get." --lang en --spk_id 7 --output output_en.wav
```
aishell3: spk_id = 167 
```bash
paddlespeech tts --am fastspeech2_aishell3 --voc pwgan_aishell3 --input "你好，欢迎使用百度 飞桨深度学习框架！" --spk_id 167
```

**Comment by ayongbox** [comment]
> there are no single speaker datasets for male, but in multi-speaker tts datasets(aishell3, vctk)，there are Male speakers, You can find speaker_id_map.txt in `~/.paddlespeech/models/fastspeech2_aishell3-zh/fastspeech2_nosil_aishell3_ckpt_0.4/speaker_id_map.txt` or `~/.paddlespeech/models/fastspeech2_vctk-en/fastspeech2_nosil_vctk_ckpt_0.5/speaker_id_map.txt` and check the gender of speakers in the origin datasets(aishell3/vctk), then, use `--spk_id` to use the speaker you want in multi-speaker tts datasets
> 
> more usage for multi-speaker cli https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech
> 
> also see #1373

**How to check the gender of the speaker？**

**Comment by lynzhai** [comment]
英文下，有男性音色吗

**Comment by yt605155624** [comment]
> > there are no single speaker datasets for male, but in multi-speaker tts datasets(aishell3, vctk)，there are Male speakers, You can find speaker_id_map.txt in `~/.paddlespeech/models/fastspeech2_aishell3-zh/fastspeech2_nosil_aishell3_ckpt_0.4/speaker_id_map.txt` or `~/.paddlespeech/models/fastspeech2_vctk-en/fastspeech2_nosil_vctk_ckpt_0.5/speaker_id_map.txt` and check the gender of speakers in the origin datasets(aishell3/vctk), then, use `--spk_id` to use the speaker you want in multi-speaker tts datasets
> > more usage for multi-speaker cli https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech
> > also see #1373
> 
> **How to check the gender of the speaker？**

you should check the gender in original datasets

for example aishell3, there is a `spk-info.txt`, which contains the gender info.
```text
data_aishell3
├── ChangeLog
├── phone_set.txt
├── ReadMe.txt
├── spk-info.txt
├── test
└── train
```

```text
# voice-file name; age group; gender; accent
# In years, A:< 14, B:14 - 25, C:26 - 40, D:> 41.

SSB1837 B       female  north
SSB0578 B       female  north
SSB1216 B       female  north
SSB1161 B       female  north
...
```

**Comment by yt605155624** [comment]
Hi all, we provide the 

spk_id gender mos result in the following files
[aishell3_gender.pdf](https://github.com/PaddlePaddle/PaddleSpeech/files/8916101/aishell3_gender.pdf)
[VCTK_gender.pdf](https://github.com/PaddlePaddle/PaddleSpeech/files/8916102/VCTK_gender.pdf)

speaker info from original datasets:
[aishell3_spk-info.txt](https://github.com/PaddlePaddle/PaddleSpeech/files/9316002/aishell3_spk-info.txt)
[vctk_speaker-info.txt](https://github.com/PaddlePaddle/PaddleSpeech/files/9316003/vctk_speaker-info.txt)

**Comment by iftaken** [comment]
you can try it in [aistuido](https://aistudio.baidu.com/aistudio/projectdetail/4396529?shared=1)

**Comment by thehzzz** [comment]
请问TTS 男性音色怎样去调整合成语音的语速和音量呢？

**Comment by yt605155624** [comment]
> 请问TTS 男性音色怎样去调整合成语音的语速和音量呢？

Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/discussions/2556

**Comment by EzrealoveQXY** [comment]
> 

![image](https://user-images.githubusercontent.com/49974992/202333825-35d0df74-1c6b-40c1-b97e-24fd88d2e47b.png)
这个有使用demo吗

**Comment by treya-lin** [comment]
> Hi all, we provide the
> 
> spk_id gender mos result in the following files [aishell3_gender.pdf](https://github.com/PaddlePaddle/PaddleSpeech/files/8916101/aishell3_gender.pdf) [VCTK_gender.pdf](https://github.com/PaddlePaddle/PaddleSpeech/files/8916102/VCTK_gender.pdf)
> 
> speaker info from original datasets: [aishell3_spk-info.txt](https://github.com/PaddlePaddle/PaddleSpeech/files/9316002/aishell3_spk-info.txt) [vctk_speaker-info.txt](https://github.com/PaddlePaddle/PaddleSpeech/files/9316003/vctk_speaker-info.txt)

请问团队在训练tts的时候是不是并没有使用aishell3全部的说话人？比如 fastspeech2_aishell3_ckpt_1.1.0 我看 speaker_id_map.txt  里面是有174个人，但是aishell3原始数据集一共200多个说话人，请问训练时是有什么筛选考虑吗 ？谢谢！
