### ISSUE TITLE
paddlespeech/s2t/modules/attention.py在转换静态图的时候出错

### ISSUE THREAD

**Issue by NYF-BRICK** [PaddlePaddle/PaddleSpeech#1625]
**Describe the bug**
在运行paddlespeech/s2t/exps/u2/bin/export.py脚本将Transformer模型转换成inference格式时出错。

**Screenshots**
<img width="1200" alt="截屏2022-03-30 下午3 34 18" src="https://user-images.githubusercontent.com/30340135/160777529-e2baf8f8-d364-4a22-be1c-c5b309a51e14.png">

** Environment (please complete the following information):**
 - OS: macOS 12.2.1
 - Python Version 3.9.11
 - PaddlePaddle Version 2.2.2
 - PaddleSpeech Version r0.1.1

**Additional context**
是否是PaddlePaddle版本过高的问题？

**Comment by NYF-BRICK** [comment]
是否PaddlePaddle 2.2.2版本不支持将MultiHeadedAttention转换成inference格式？

**Comment by zh794390558** [comment]
可以尝试下develop或是2.3的paddle版本。asr的模型无法导出是已知问题。

**Comment by NYF-BRICK** [comment]
> 可以尝试下develop或是2.3的paddle版本。asr的模型无法导出是已知问题。

按照官网命令`pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/mac/cpu/develop.html` 安装好develop版本后依然是这个问题。
我看了是paddlespeech中的`paddlespeech/s2t/modules/attention.py`中自己写了一个`MultiHeadedAttention`，其中用到的`view`的是`numpy`实现的。与之类似的还有`paddlespeech/s2t/models/u2/u2.py`中`U2BaseModel.ctc_greedy_search`。

PaddleSpeech Version r0.1.1中的`paddlespeech/s2t/exps/u2/bin/export.py`是否成功运行过...

**Comment by zh794390558** [comment]
抱歉，参看下 https://github.com/PaddlePaddle/PaddleSpeech/commit/b9a1b5f28afd2cbc4add0159508788b61d940491

**Comment by NYF-BRICK** [comment]
> 抱歉，参看下 [b9a1b5f](https://github.com/PaddlePaddle/PaddleSpeech/commit/b9a1b5f28afd2cbc4add0159508788b61d940491)

按照https://github.com/PaddlePaddle/PaddleSpeech/commit/b9a1b5f28afd2cbc4add0159508788b61d940491 中的修改方法对`paddlespeech/s2t/__init__.py`进行修改后类似`AttributeError: 'Variable' object has no attribute 'view'`的错误能解决，但是出现新的问题：

1. 参数`n_batch`的值也为-1，会导致`reshape`操作失败;
<img width="1224" alt="截屏2022-03-30 下午10 24 51" src="https://user-images.githubusercontent.com/30340135/160860936-388253e2-36ec-477c-a8a8-5645d63b1375.png">

2. 将`q = self.linear_q(query).view(n_batch, -1, self.h, self.d_k)`改为`q = self.linear_q(query).view(n_batch, 2, self.h, self.d_k)`暂时避免1中的错误后，运行依然失败，有如下错误。
<img width="1309" alt="截屏2022-03-30 下午10 26 00" src="https://user-images.githubusercontent.com/30340135/160862324-35a5bb81-a1ae-4875-90b0-8c10dd7a4ee7.png">


PS：https://github.com/PaddlePaddle/PaddleSpeech/commit/b9a1b5f28afd2cbc4add0159508788b61d940491 这个地方是否应为`paddle.static.Variable.masked_fill = masked_fill`
<img width="693" alt="截屏2022-03-30 下午10 22 39" src="https://user-images.githubusercontent.com/30340135/160863329-1ec5edae-88af-4cd9-a5bb-34045b39bf87.png">

**Comment by zh794390558** [comment]
![image](https://user-images.githubusercontent.com/3038472/160963592-6a8fa223-05ed-4bbd-999f-02564a2acf89.png)

问题如上。

请问是在做asr transformer的动转静吗？这部分功能目前是无法走通的。

**Comment by NYF-BRICK** [comment]
> ![image](https://user-images.githubusercontent.com/3038472/160963592-6a8fa223-05ed-4bbd-999f-02564a2acf89.png)
> 
> 问题如上。
> 
> 请问是在做asr transformer的动转静吗？这部分功能目前是无法走通的。

是的，非常感谢你的回复。我后来简单尝试了用`paddlepaddle.nn.MultiHeadAttention`来代替了paddlespeech中的`MultiHeadedAttention`，并修改了`U2InferModel`中`ctc_greedy_search`函数及其他几个地方，能够完成动转静的操作，但是在用`inference`调用是失败的，Too naive了我╮(╯▽╰)╭。

**Comment by zh794390558** [comment]
目前的代码是streaming & non-streaming一套代码，语法灵活无法动转静。 单写离线模型应该是可以过的。

**Comment by EricLingRui** [comment]
@NYF-BRICK 请问你动转静后模型验证成功没？

**Comment by NYF-BRICK** [comment]
没有，最终选择了其他方法。
