### ISSUE TITLE
centos7 + cpu : 找不到paddleaudio.compliance

### ISSUE THREAD

**Issue by dtMndas** [PaddlePaddle/PaddleSpeech#1629]
padddleSpeech : 0.2.0 版本， paddleaudio : 0.1.0. 在导入VectorExecutor时候，报错如下：
![image](https://user-images.githubusercontent.com/9609594/160957683-c3c782f4-7896-4a24-8741-ab80da83741f.png)

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/issues/1617

**Comment by dtMndas** [comment]
thanks
