### ISSUE TITLE
How to generate MFA with tone?

### ISSUE THREAD

**Issue by phoenixsfly** [PaddlePaddle/PaddleSpeech#1645]
I want to train my own TTS model on CSMSC dataset. In data preparing stage, I have tried to run `PaddleSpeech-develop/examples/other/mfa/run.sh` to generate  MFA model and Textgrid but  got `baker_alignment` which didn't have tone. <br>
So I wanna to know hot to generate MFA with tone.

**Comment by phoenixsfly** [comment]
尝试了如下方法
- 修改[run.sh](https://github.com/PaddlePaddle/PaddleSpeech/blob/a2c0fbf241ccd0920cea84c134ca27d2cc7f3d5e/examples/other/mfa/run.sh#L7)，在第7行后面增加 `--with-tone`参数
- 修改[reorganize_baker.py](https://github.com/PaddlePaddle/PaddleSpeech/blob/a2c0fbf241ccd0920cea84c134ca27d2cc7f3d5e/examples/other/mfa/local/reorganize_baker.py#L47)，将`item[:-1]`改为`item[:]`

再运行`run.sh`就能生成带tone的MFA了，很奇怪的是paddlespeech提供训练好的MFA[baker_alignment_tone.tar.gz](https://paddlespeech.bj.bcebos.com/MFA/BZNSYP/with_tone/baker_alignment_tone.tar.gz)是带tone的，但是给出自行训练MFA的example却不带tone，需要自行修改代码。

**Comment by yt605155624** [comment]
确实如此，因为 reorganize_baker.py 好久没用了，我每次都是直接用之前跑好的 MFA 的结果，刚开始 MFA 只是用来裁剪音频前后的静音的，默认生成 lexicon 的方式也不带 tone，所以没有带 tone，感谢你提供给大家的方法～
