### ISSUE TITLE
Cento 7.5 安装Paddle 不能导入import paddle 报错如下

### ISSUE THREAD

**Issue by 979170768** [PaddlePaddle/PaddleSpeech#1654]
![image](https://user-images.githubusercontent.com/35989496/162104225-bf314591-9dd7-44ff-b385-26068b038bb7.png)

CentOS7.5
Python 3.9

**Comment by yt605155624** [comment]
paddle 相关问题到 https://github.com/PaddlePaddle/Paddle 提交 issue 会得到更加专业的回答，可以搜索 paddle issue 看看是否有类似的问题
