### ISSUE TITLE
paddlespeech_ctcdecoders 这个库windows下载不了

### ISSUE THREAD

**Issue by qqqkoko123** [PaddlePaddle/PaddleSpeech#1683]
paddlespeech_ctcdecoders 这个库下载不了，所以swig_wrapper.py没法用。。。

**Comment by zh794390558** [comment]
win无法使用，需要用linux或mac

**Comment by Jackwaterveg** [comment]
win 目前还不支持 deepspeech 2类的模型

**Comment by SWHL** [comment]
@Jackwaterveg 
- 如果想在Windows下用这个库的话，需要自己编译吧
- 但是repo似乎没有源码了，方便提供一份吗，我看之前说是有的 [#1017](https://github.com/PaddlePaddle/PaddleSpeech/issues/1017#issuecomment-981647294)

**Comment by zh794390558** [comment]
源码在这里：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/third_party/ctc_decoders/LICENSE
能解决win的编译就太好了，希望能看到PR

**Comment by Doubledongli** [comment]
> * 需要自己编译吧

我自己编译了一份，可以试试，测试阶段：pip install paddlespeech-ldd-ctcdecoders
讨论区：https://github.com/PaddlePaddle/PaddleSpeech/discussions/2148#discussion-4212874
