### ISSUE TITLE
!paddlespeech asr --lang en --model transformer_librispeech --input demo.wav  taking forever to produce output

### ISSUE THREAD

**Issue by foyezkabir** [PaddlePaddle/PaddleSpeech#1706]
![Screenshot (393)](https://user-images.githubusercontent.com/74759605/163564485-8867ca37-d9ee-4e5e-b8c6-4d1a1235beb8.png)

**Comment by foyezkabir** [comment]
I have tried to test run paddlespeech for a project. i have had provided sample audio to transcribe but as it is shown in the screenshot
the cell block is running for almost 5hrs now. Is it normal? as it was shown in the demo video, paddlespeech transcribed the given audio file in an instance.

**Comment by zh794390558** [comment]
Do the asr can work with https://paddlespeech.bj.bcebos.com/PaddleAudio/en.wav?

**Comment by foyezkabir** [comment]
Yes, it works,
The file transcribed instantly. Thanks a lot
