### ISSUE TITLE
关于asr模型的多batch推理

### ISSUE THREAD

**Issue by Chenwe111** [PaddlePaddle/PaddleSpeech#1726]
我这边想在asr的test_wav下实现多batch推理，然后我就简单的cat了两个相同的输入：（1,590,80）->（2,590,80）送入模型推理，理论上
result_transcripts出来两个推理结果应该是一样的，因为我cat的是两个相同输入。但是现在第一个结果是对的，第二个结果不对很奇怪
![image](https://user-images.githubusercontent.com/93525180/164193568-94e1ad2f-3930-4dd3-9270-2eda09950597.png)
请大佬帮我看下

**Comment by Jackwaterveg** [comment]
请问你是用了 [这里](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/s2t/exps/deepspeech2/bin/test_wav.py) 的代码吗？
使用 deepspeech2 online 模型？然后使用 run.sh 中的 stage 6 进行实验？

**Comment by Jackwaterveg** [comment]
可否再详细说明一下使用了哪个代码，做了什么修改，这样我这里可以直接定位测试来 debug 哈

**Comment by Chenwe111** [comment]
> 可否再详细说明一下使用了哪个代码，做了什么修改，这样我这里可以直接定位测试来 debug 
您好，是asr1中的test_wav,然后使用stage6的推理方式，单个短语音是可以的，但是我想多个相同时长的短语音压成多batch一起推理，您帮我看下

**Comment by Jackwaterveg** [comment]
请问是https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/s2t/exps/u2/bin/test_wav.py#L81 修改了这里吗？最好打印一下 83 行的 result_transcripts, 看下原始的结果。

**Comment by Chenwe111** [comment]
> 请问是https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/s2t/exps/u2/bin/test_wav.py#L81 修改了这里吗？最好打印一下 83 行的 result_transcripts, 看下原始的结果。

是的，我那边打印的result_transcript就是这个结果，xs可以cat成（B，T，D）的形式，那个ilen那边该怎么处理，多batch的情况的话

**Comment by Jackwaterveg** [comment]
也需要复制一份，维度是 (B)

**Comment by Chenwe111** [comment]
> 也需要复制一份，维度是 (B)
具体是怎么操作呢，我这边paddle.mean(xs, axis = [1,2])，维度对齐了底层会抛出一个c++的异常，所以我感觉我应该是错的

**Comment by Chenwe111** [comment]
> 也需要复制一份，维度是 (B)
可以了，感谢

**Comment by Jackwaterveg** [comment]
好的哈
