### ISSUE TITLE
语音翻译成文字，目前只支持英译汉吗？什么时候出个汉译英的？多谢

### ISSUE THREAD

**Issue by DidaDidaDidaD** [PaddlePaddle/PaddleSpeech#1756]
语音翻译成文字，目前只支持英译汉吗？什么时候出个汉译英的？多谢

**Comment by zh794390558** [comment]
汉译英，没有数据集。有推荐的吗？

**Comment by DidaDidaDidaD** [comment]
> 汉译英，没有数据集。有推荐的吗？

没有，我是小白，前来学习的，看到只有英译汉，想当然的以为有汉译英，运行后发现没有训练的模型。感谢各位的付出，辛苦了

**Comment by zh794390558** [comment]
st效果是开源里最好的了，可以多尝试调优下。

**Comment by yt605155624** [comment]
中文语音到英文翻译数据集 Baidu Speech Translation Corpus [BSTC Zh→En](https://ai.baidu.com/broad/subordinate?dataset=bstc)
