### ISSUE TITLE
[ TTS ] Vocoder(Pwgan): covert onnx model to TRT ERROR

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#1816]
In TTS,  I cover `Vocoder(Pwgan)` paddle model to onnx model with your code,  it is OK, and the onnx model is OK;
Then I cover that onnx model to TensorRT model, It is error.  And the error is like that:
```
Loading ONNX file from path ../data/paddle_onnx/onnx_model/pwgan_aishell3.onnx...
Beginning ONNX file parsing
[04/27/2022-21:39:16] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Completed parsing of ONNX file
Building an engine from file ../data/paddle_onnx/onnx_model/pwgan_aishell3.onnx; this may take a while...
[04/27/2022-21:39:16] [TRT] [E] 4: [network.cpp::validate::2633] Error Code 4: Internal Error (Network must have at least one output)
Completed creating Engine
Traceback (most recent call last):
  File "onnx2trt_paddle.py", line 95, in <module>
    engine = ONNX_build_engine(onnx_file_path, trt_output, write_engine)
  File "onnx2trt_paddle.py", line 44, in ONNX_build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

```
The code I use to cober TRT is just like this:
<img width="419" alt="1" src="https://user-images.githubusercontent.com/27938135/165532168-d48efcf3-3a26-4aef-8c40-e969e937752f.png">
<img width="370" alt="2" src="https://user-images.githubusercontent.com/27938135/165532198-94856e6b-2793-463b-8ec0-7e5b8a718114.png">

I covert vocoder from `pytorch --> onnx --> TRT `is OK

**So, Does** `paddle --> onnx` **model spport** `onnx --> TRT` **model ?**

** Environment (please complete the following information):**
 - OS:  Ubuntu
 - Python Version:  3.7
 - GPU/DRIVER Informationo : GeForce RTX 3090
 - CUDA/CUDNN Version : cuda-11.2
- TensorRT Version :  8.2.1.8

**Comment by yt605155624** [comment]
I have no knowledge about onnx -> trt, sorry, please make sure your onnx model can use trt first, as far as I am concerned, fastspeech2 can't not use trt, because the duration is predicted during inference, so the trt doesn't known the size of some layers

**Comment by Tian14267** [comment]
> I have no knowledge about onnx -> trt, sorry, please make sure your onnx model can use trt first, as far as I am concerned, fastspeech2 can't not use trt, because the duration is predicted during inference, so the trt doesn't known the size of some layers

Thank you very much. But vocoder model from onnx covert to TRT is also error. I guess something is wrong with onnx model. 
what I say about TRT is like this:
[https://www.jianshu.com/p/3c2fb7b45cc7](url)
[https://blog.csdn.net/weixin_42476942/article/details/113757059](url)
can you solve this problem ?

**Comment by yt605155624** [comment]
Maybe you can get more help from Paddle2Onnx, but covert onnx model to trt model may not in paddle's business scope
