### ISSUE TITLE
识别长音频的需求

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleSpeech#1819]
从其他的issue里看到最长识别时长是50s，但是在现实场景中一定是大于这个数值的，能否PaddleSpeech进行自动的切割，然后分段进行识别。使用场景可能为会议纪要。

**Comment by zh794390558** [comment]
CLI 定位是用来做模型推理的，并没有要支持产品引用。VAD这个在看，但也需要根据场景调整，这个需要自己了解怎么调。加上去了业务上也不一定能应用好。

**Comment by DidaDidaDidaD** [comment]
不管怎么说，实用才是第一的，既然有推理了，再弄个音频切分的就是了，最好的就是输入整段音频，去噪、切分、识别、断句，最后一起输出，只用vad，对于语速比较快的或者多个人一起说话的，就无法切开，还是需要punctuation，所以把这几个统一了，就完美了

**Comment by ChenjieXu** [comment]
> CLI 定位是用来做模型推理的，并没有要支持产品引用。VAD这个在看，但也需要根据场景调整，这个需要自己了解怎么调。加上去了业务上也不一定能应用好。

这可能还是要看产品定位，像视觉模型库PaddleDetection等已经在工业领域占有了一席之地，当我遇到了ASR的需求我自然而然地会想到Paddle的其他产品。VAD可能是整块拼图的最后一块，VAD+ASR+PRUNC我觉得可以解决大多数的工业场景。
这边想再问一下目前如何使用Python脚本形式进行ASR和PRUNC，doc感觉还不是很完善。

**Comment by ChenjieXu** [comment]
很早之前就关注这个repo，那时候能够支持从麦克风输入，不知道什么时候可以再有这个功能？

**Comment by DidaDidaDidaD** [comment]
今天看到一个软件叫万彩字影大师，这个就是长音频自己切分识别断句，这就是我想要的效果

**Comment by zh794390558** [comment]
> 很早之前就关注这个repo，那时候能够支持从麦克风输入，不知道什么时候可以再有这个功能？

可以参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/tests/asr/online/microphone_client.py

**Comment by charmby** [comment]
> 

确定只支持50s？传入一个20分钟的语音片段是不是不能返回结果

**Comment by zh794390558** [comment]
理论上是200s。已实际测试为准。

**Comment by zHaOshuAnGye** [comment]
不修改源码是不是最长只能识别49s
![image](https://user-images.githubusercontent.com/38178828/172526447-1b980941-4ada-48de-964d-b6353e85a828.png)
