### ISSUE TITLE
使用CLI的时候需要键盘输入

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/PaddleSpeech#1820]
使用CLI的时候需要键盘输入 INPUT（Y/N），不太理解这个是干什么用的？
能否提供使用脚本进行识别的例子？

**Comment by zh794390558** [comment]
加上 -y 就可以直接运行了。
`paddlespeech asr -y --input ./zh.wav`

**Comment by Jackwaterveg** [comment]
因为你的samplle rate 不符合模型标准，加上 -v，就可以看到 log信息了，加上 -y ，程序就帮你直接resample 了。

**Comment by ChenjieXu** [comment]
问题解决了！多谢！
