### ISSUE TITLE
长语音识别效果还不错，就是没分片，而且没有时间信息

### ISSUE THREAD

**Issue by DidaDidaDidaD** [PaddlePaddle/PaddleSpeech#1831]
长语音识别效果还不错，就是没分片，而且没有时间信息，如果使用vad，发现分片数量越多，用paddlespeech识别的效果越差，看样子和上下文有关系，但音频开始和结尾识别的错误率明显挺大的。不知道什么时候能出长语音识别，同时断句以及时间信息

**Comment by DidaDidaDidaD** [comment]
有没有银啊，长语音的识别这个才实用啊，不晓得为啥不重视这个

**Comment by LeoMax-Xiong** [comment]
时间戳的功能正在开发

**Comment by DidaDidaDidaD** [comment]
> 时间戳的功能正在开发

感谢回复，期待早日上线

**Comment by wonder2025** [comment]
能识别demo自带的音频，自己的中文普通话音频一个都识别不出来，不知道需要改哪里

**Comment by charmby** [comment]
长语音是不支持mp3吗？
paddlespeech asr --lang zh --input /home/charmby/data/20220511.mp3
/home/charmby/local/conda/envs/stock/lib/python3.8/site-packages/matplotlib/__init__.py:152: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(module.__version__) < minver:
/home/charmby/local/conda/envs/stock/lib/python3.8/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
也没有提示任何错误，也没有任何数据返回

**Comment by LeoMax-Xiong** [comment]
目前还不支持mp3格式，可以在脚本中mp3转换为wav

**Comment by yt605155624** [comment]
目前已经支持时间戳功能了，请参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_asr_server

**Comment by QuantumLiu** [comment]
> 目前已经支持时间戳功能了，请参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_asr_server

你好，链接的readme里没有时间戳相关信息

**Comment by SoulSnow** [comment]
> 

你好，这个功能只支持中文吗

**Comment by SoulSnow** [comment]
目前已经支持时间戳功能了，请参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_asr_server

你好，这个功能只支持中文吗
