### ISSUE TITLE
希望能添加一下声纹识别的教程文档

### ISSUE THREAD

**Issue by landd1897** [PaddlePaddle/PaddleSpeech#1834]

**Comment by qingen** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/audio_searching/README_cn.md
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/voxceleb
以及近期会有一档声纹直播课，到时可以关注下

**Comment by yt605155624** [comment]
教程已经更新到 https://aistudio.baidu.com/aistudio/education/group/info/25130
