### ISSUE TITLE
Add acknowledgment to WeNet

### ISSUE THREAD

**Issue by xingchensong** [PaddlePaddle/PaddleSpeech#1839]
Parts of the `speechx` projects are basically the same as the ones used inside WeNet. I would recommend adding acknowledgment to WeNet in `speechx/README.md`.

1. `websocket_server` and  `websocket_client` are basically equal to WebSocket in WeNet, see `diff` below:
<img width="960" alt="72cb781624f8454f74fa8b4be483165" src="https://user-images.githubusercontent.com/13466943/166688197-06105606-57f7-460b-8279-1e10173d311d.png">
<img width="960" alt="efabdb41e7d3d57f04465fd06edbfef" src="https://user-images.githubusercontent.com/13466943/166688318-a7556c84-f4c7-4bc4-aebf-31f43c028ecf.png">

2. `openfst patch` is identical to WeNet, it is non-trivial to find proper patches and make them work correctly in the whole WeNet project. This kind of work is time-consuming but could be easily overlooked.

**Comment by zh794390558** [comment]
Hi @xingchensong ，thanks for the reminder of the copyright issue. We have added the authors and acknowledge in the related code.https://github.com/PaddlePaddle/PaddleSpeech/pull/1849  In those code, we refer the design of the websocket in Wenet, which is compact and useful. With that help, we save lot of time and energy, speeding up the development. We are really grateful about the contributions of Wenet to the opensource software, which help us spend more time and energy on the pressing and valuable issues. Also, We are looking forward to working with Wenet to make more valuable contributions, and make the technology easier and popular.


Acknowledgement for reference repo：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/reference.md
