### ISSUE TITLE
ubuntu安装时显示版本冲突

### ISSUE THREAD

**Issue by PoPdark** [PaddlePaddle/PaddleSpeech#1867]
![image](https://user-images.githubusercontent.com/23391279/167234273-6b7aa644-6342-4b50-84ef-f19b18bfd84b.png)
我看之前的issue好像有人也出现了类似的问题，但是不知道是怎么解决的。python版本3.6.9 ubuntu版本18.04.5

**Comment by yt605155624** [comment]
pip install paddlespeech==1.0.0a
安装最新版试试，报错显示的版本都好老了。

**Comment by yt605155624** [comment]
maybe you should update your pip's version
