### ISSUE TITLE
streaming service /service 如何使用pretrained 之外的模型？

### ISSUE THREAD

**Issue by bingyulab** [PaddlePaddle/PaddleSpeech#1875]
配置文件里am 选择为['fastspeech2_csmsc_onnx', 'fastspeech2_cnndecoder_csmsc_onnx']
如何使用自己训练的模型搭建服务？

**Comment by lym0302** [comment]
把训练的模型相关文件依次对应填写到am_ckpt（这个为list类型）， am_stat，phones_dict 即可

**Comment by lym0302** [comment]
am_ckpt is a list, if am is fastspeech2_cnndecoder_csmsc_onnx, am_ckpt = [encoder model, decoder model, postnet model], if am is fastspeech2_csmsc_onnx, am_ckpt = [ckpt model]

**Comment by bingyulab** [comment]
如果我基于aishell3 finetune的模型，是否还支持呢？ 是不是只要把csmc 换成aishell3 就行了？
am_stat，phones_dict 都是string类型对吧

**Comment by lym0302** [comment]
aishell3的流式tts目前不支持，目前只支持yaml配置文件注释上写的那些，如果你想用aishell3的模型的话，可以根据https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/python/tts_engine.py 自行修改

**Comment by bingyulab** [comment]
明白。 未来会有开发计划吗？

**Comment by yt605155624** [comment]
暂时没有开发计划
如果想用 onnxruntime 推理引擎，目前多说话人的 fastspeech2 模型 paddle2onnx 有算子暂时不支持（p_norm）
如果想用 paddle 动态图作为推理引擎，自己改的话应该不算难

**Comment by makerjackie** [comment]
@lym0302 话说为啥 decoder 和 postnet 要导出为两个onnx模型呢，合并不可以吗
