### ISSUE TITLE
如何提升TTS在CPU下的推断速度？

### ISSUE THREAD

**Issue by Kevinkaiyan** [PaddlePaddle/PaddleSpeech#1908]
现在的服务器的CPU环境是4核4线程，模型使用的是fastspeech2和parallelwaveGAN，推断一个7字车牌号需要4s的时间。目前cpu占用是100%，请问如何提升推断速度，需要启动多核推断吗，还是进行模型压缩？

**Comment by yt605155624** [comment]
1. 把声学模型换成 hifigan/mb_melgan，pwgan 速度很慢，mb_melgan 速度最快，质量较差，声学模型换成 speedyspeech 可能会略快，fastspeech2_cnndecoder 也能比默认的 fastspeech2 快一点，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/csmsc/tts3/run_cnndecoder.sh
2. paddle 动态图很多算子没有支持 cpu 多线程，开了多线程提升也不明显
3. 可以试试用 onnxruntime 推理引擎，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/7178076a591fafbbabb881327bf9611b27a863bd/examples/csmsc/tts3/run.sh#L58 我们的普通机器上 onnx fastspeech2 + onnx hifigan 4 核 cpu rtf 可以到 0.3 左右
4. 模型压缩目前还没试过

**Comment by Kevinkaiyan** [comment]
> 1. 把声学模型换成 hifigan/mb_melgan，pwgan 速度很慢，mb_melgan 速度最快，质量较差，声学模型换成 speedyspeech 可能会略快，fastspeech2_cnndecoder 也能比默认的 fastspeech2 快一点，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/csmsc/tts3/run_cnndecoder.sh
> 2. paddle 动态图很多算子没有支持 cpu 多线程，开了多线程提升也不明显
> 3. 可以试试用 onnxruntime 推理引擎，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/7178076a591fafbbabb881327bf9611b27a863bd/examples/csmsc/tts3/run.sh#L58
>     我们的普通机器上 onnx fastspeech2 + onnx hifigan 4 核 cpu rtf 可以到 0.3 左右
> 4. 模型压缩目前还没试过

感谢！速度提升很显著，此外还想问一下在onnx下可以做stylefastspeech2那样的定制化操作吗？

**Comment by yt605155624** [comment]
> > 1. 把声学模型换成 hifigan/mb_melgan，pwgan 速度很慢，mb_melgan 速度最快，质量较差，声学模型换成 speedyspeech 可能会略快，fastspeech2_cnndecoder 也能比默认的 fastspeech2 快一点，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/csmsc/tts3/run_cnndecoder.sh
> > 2. paddle 动态图很多算子没有支持 cpu 多线程，开了多线程提升也不明显
> > 3. 可以试试用 onnxruntime 推理引擎，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/7178076a591fafbbabb881327bf9611b27a863bd/examples/csmsc/tts3/run.sh#L58
> >    
> >    我们的普通机器上 onnx fastspeech2 + onnx hifigan 4 核 cpu rtf 可以到 0.3 左右
> > 4. 模型压缩目前还没试过
> 
> 感谢！速度提升很显著，此外还想问一下在onnx下可以做stylefastspeech2那样的定制化操作吗？

可能需要你自己重新导出多个子模型来实现定制化调节 duration 和 pitch

**Comment by MingyuLau** [comment]
请问使用gpu的话推理速度会变快吗

**Comment by MingyuLau** [comment]
@yt605155624

**Comment by nuass** [comment]
> 1. 把声学模型换成 hifigan/mb_melgan，pwgan 速度很慢，mb_melgan 速度最快，质量较差，声学模型换成 speedyspeech 可能会略快，fastspeech2_cnndecoder 也能比默认的 fastspeech2 快一点，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/csmsc/tts3/run_cnndecoder.sh
> 2. paddle 动态图很多算子没有支持 cpu 多线程，开了多线程提升也不明显
> 3. 可以试试用 onnxruntime 推理引擎，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/7178076a591fafbbabb881327bf9611b27a863bd/examples/csmsc/tts3/run.sh#L58
>     我们的普通机器上 onnx fastspeech2 + onnx hifigan 4 核 cpu rtf 可以到 0.3 左右
> 4. 模型压缩目前还没试过

您好，非常专业的回答
我是以命令行启动，推理速度也是接近4s.
paddlespeech_server start --config_file conf/tts_online_application.yaml

能否看下tts_online_application.yaml配置怎么优化来加速
--------------
[tts_online_application.yaml.txt](https://github.com/PaddlePaddle/PaddleSpeech/files/11258681/tts_online_application.yaml.txt)
----------------------------------------
