### ISSUE TITLE
TTS功能无法输出英文语音

### ISSUE THREAD

**Issue by YukiRus** [PaddlePaddle/PaddleSpeech#1909]
使用的是简单模式的命令行输出，仅能输出中文和数字。
请问需要什么额外的配置吗？谢谢

**Comment by yt605155624** [comment]
目前 TTS 仅支持纯中文和纯英文，不支持中英文混合，如果想合成英文文本，可以采用如下命令：
```bash
paddlespeech tts --am fastspeech2_ljspeech --voc pwgan_ljspeech --lang en --input "hello world"

```

**Comment by YukiRus** [comment]
> 目前 TTS 仅支持纯中文和纯英文，不支持中英文混合，如果想合成英文文本，可以采用如下命令：
> 
> ```shell
> paddlespeech tts --am fastspeech2_ljspeech --voc pwgan_ljspeech --lang en --input "hello world"
> ```

好的，十分感谢
