### ISSUE TITLE
无法转换为音频

### ISSUE THREAD

**Issue by CHSSea** [PaddlePaddle/PaddleSpeech#1922]
我通过/paddlespeech/tts/streaming这个接口获取到音频的base64编码，但是无法转码为音频文件，尝试了MP3格式和WAV格式

**Comment by zh794390558** [comment]
base64解码后是pcm，可以保存任意格式的。

**Comment by CHSSea** [comment]
是的，但是当我转换为音频文件时，无法正常的播放

**Comment by CHSSea** [comment]
我现在换了api使用，使用/paddlespeech/tts拿到audio值后，可以顺利转为了wav。

**Comment by lym0302** [comment]
流式服务为了更快的响应，返回的string 是 int16 类型的数据转的。可以参考下述方式保存试试看？
① 将base64转成 byte：data_bytes = base64.b64decode(data_string)
② 保存音频（支持pcm 和 wav）可参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/utils/audio_process.py#L146 转成

**Comment by shaoxiang** [comment]
> 流式服务为了更快的响应，返回的string 是 int16 类型的数据转的。可以参考下述方式保存试试看？ ① 将base64转成 byte：data_bytes = base64.b64decode(data_string) ② 保存音频（支持pcm 和 wav）可参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/utils/audio_process.py#L146 转成

您好，请问使用JavaScript audio 该如何播放 base64音频呢？

**Comment by wuxiy** [comment]
> > 流式服务为了更快的响应，返回的 string 是 int16 类型的数据转码的。可以参考前面的方式保存尝试看成？ ① 将base64转字节：data_bytes = base64.b64decode(data_string) ② 保存音频（支持pcm）和 wav）可参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/utils/audio_process.py#L146转成
> 
> 您好，请问使用JavaScript音频来播放base64音频呢？

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/speech_web/web_client/src/components/SubMenu/TTS/TTST.vue 官方的这段代码有示例，需要自己修改下ws通信流程
