### ISSUE TITLE
AttributeError: 'ASRExecutor' object has no attribute 'max_len'

### ISSUE THREAD

**Issue by qiuyuzhao** [PaddlePaddle/PaddleSpeech#1932]
运行程序时候提示错误：  
File "/home/ssd/suimang/project/PaddleSpeech/paddlespeech/cli/asr/infer.py", line 371, in _check
    if audio_duration > self.max_len:
AttributeError: 'ASRExecutor' object has no attribute 'max_len'
下边是我的代码：
import paddle
from paddlespeech.cli import ASRExecutor

asr_executor = ASRExecutor()
text = asr_executor(
    model='conformer_wenetspeech',
    lang='zh',
    sample_rate=16000,
    config=None,  # Set `config` and `ckpt_path` to None to use pretrained model.
    ckpt_path=None,
    audio_file='data/zh.wav',
    force_yes=False,
    device=paddle.get_device())
print('ASR Result: \n{}'.format(text))
请问这是什么原因啊？

**Comment by prophesier** [comment]
遇到了同样的问题，发现根本原因是在paddlespeech/cli/asr/infer.py里面 在初始化maxlen之前就先调用了_check检查，
在480行左右
```
        audio_file = os.path.abspath(audio_file)
        
        paddle.set_device(device)
        self._init_from_path(model, lang, sample_rate, config, decode_method,
                             ckpt_path)
        if not self._check(audio_file, sample_rate, force_yes):
            sys.exit(-1)
```
把 if not self._check()如上放到self._init_from_path()下面，然后重新pip install . ，虽然不清楚会不会引起其他问题，但至少解决了这个报错

**Comment by Jackwaterveg** [comment]
问题现在解决啦 https://github.com/PaddlePaddle/PaddleSpeech/pull/1930
