### ISSUE TITLE
可以设置不检测paddlespeech-ctcdecoders 这个组件？

### ISSUE THREAD

**Issue by MrJson1** [PaddlePaddle/PaddleSpeech#1933]
语音识别执行命令：
paddlespeech asr --lang zh --input  C:\Users\Administrator\Desktop\test.wav -v

一直检测paddlespeech-ctcdecoders 组件但是又没起到作用，执行命令识别比较慢，是否可以去除这个检测机制
![image](https://user-images.githubusercontent.com/44693150/169677231-2ebb06ad-f1fc-4e95-bb59-92930b47159c.png)

**Comment by Jackwaterveg** [comment]
嗯，会实现一个平台判断的功能，让win系统不下载，来解决这个问题

**Comment by MrJson1** [comment]
现在怎么在windows安装paddlespeech-ctcdecoders 组件呢
