### ISSUE TITLE
ASR-python api will waiting input() don't continue

### ISSUE THREAD

**Issue by liqiujiong** [PaddlePaddle/PaddleSpeech#1937]
**Describe the bug**
i try to use asr-api of  paddleSpeech.cli，but I happen a problem that it don't working，because can't input in python runtime

**To Reproduce**

1. Go to ready environment
2. input asr python api demo
3. run it

**Expected behavior**
![image](https://user-images.githubusercontent.com/5794205/169762724-b7b0968e-1313-45dc-a46b-c3973ecfc482.png)

**Try solution**

![image](https://user-images.githubusercontent.com/5794205/169762312-cbfd6b71-4f14-4951-b2e3-6f7017ea4d5d.png)

**Comment by yt605155624** [comment]
you should add `force_yes=True` when using asr python api, please check here https://github.com/PaddlePaddle/PaddleSpeech/blob/e6ddb0cc6efe8d4706aac23009aa1a16c506bc3d/paddlespeech/cli/asr/infer.py#L99 and https://github.com/PaddlePaddle/PaddleSpeech/blob/e6ddb0cc6efe8d4706aac23009aa1a16c506bc3d/paddlespeech/cli/asr/infer.py#L477

**Comment by liqiujiong** [comment]
> you should add `force_yes=True` when using asr python api, please check here
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/e6ddb0cc6efe8d4706aac23009aa1a16c506bc3d/paddlespeech/cli/asr/infer.py#L99
> 
> and
> https://github.com/PaddlePaddle/PaddleSpeech/blob/e6ddb0cc6efe8d4706aac23009aa1a16c506bc3d/paddlespeech/cli/asr/infer.py#L477

thank you solved my problem
