### ISSUE TITLE
deepspeech2提取音频特征

### ISSUE THREAD

**Issue by qiuyuzhao** [PaddlePaddle/PaddleSpeech#1939]
请问deepspeech2提取音频特征在代码中是encoder出来的就是音频特征了么？decoder是吧提取到的音频特征和解码成文字么？

**Comment by zh794390558** [comment]
encoder输出的是hidden state.

**Comment by qiuyuzhao** [comment]
请问在模型Conv layer， Recurrent layer ，和FC layer中哪里输出的是音频的特征？

**Comment by zh794390558** [comment]
音频特征是conv的输入
