### ISSUE TITLE
音频长度和特征长度

### ISSUE THREAD

**Issue by qiuyuzhao** [PaddlePaddle/PaddleSpeech#1944]
请问输入一段音频在encoder outputs,中返会的维度是[1 T, D]，这个T要怎么和音频的长度对应上呢？

**Comment by yt605155624** [comment]
请问你说的是哪个任务的哪个模型

**Comment by qiuyuzhao** [comment]
语音识别任务的deepspeech2offline_aishell，请问这个模型的encoder返回的[1.T,D]，T如何与音频的时间对应，万分感谢

**Comment by Jackwaterveg** [comment]
这个 T 对应的是音频可以切为多少帧。比如音频是 2s，帧长 20 ms， 帧移 10ms，那么就可以切 199 帧， 所以T就是原本应该是 199，但是 encoder 是有 conv 层的， conv 会进行 subsampling，所以 T = 199 / subsampling_rate。

**Comment by qiuyuzhao** [comment]
deepspeech2offline_aishell中的采样是3倍的关系么？
