### ISSUE TITLE
2022-05-24编译paddlespeech_ctcdecoders的时候遇到setup.sh文件有换行符错误

### ISSUE THREAD

**Issue by SuperKsa** [PaddlePaddle/PaddleSpeech#1947]
今天用树莓派编译paddlespeech_ctcdecoders的时候遇到setup.sh文件有换行符错误的问题，具体报错如下：

/PaddleSpeech/third_party/ctc_decoders# `bash ./setup.sh`

/setup.sh: line 2: $'\r': command not found
/setup.sh: line 25: syntax error: unexpected end of file

---
将里面的代码复制出来放到新建的文件里就能正常编译了，`麻烦大佬们修正一下吧`

 - OS: 树莓派 Linux PI 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
 - Python Version [e.g. 3.9.2]

**Comment by Jackwaterveg** [comment]
应该是 树莓派的linux系统和 一般电脑的 ubuntu不同的问题，识别的换行符不一样，可能需要自行修改一下
