### ISSUE TITLE
PP-TTS G2P 的准确率

### ISSUE THREAD

**Issue by asr-pub** [PaddlePaddle/PaddleSpeech#1952]
>https://mp.weixin.qq.com/s/GFek2OafvXXbqsEQy5fkTg
PP-TTS 提供了针对中文场景的语音合成文本前端优化方案：针对时间、日期、电话、温度等常见非标准词进行了文本正则化处理；开源了针对中文场景的轻声变调、三声变调和“一”“不”变调等字音转换（ G2P ）解决方案。在自建的文本正则化测试集上， CER 低至0.73%；以 CSMSC 数据集的拼音标注为 Ground Truth ，**字音转换（ G2P ）的 WER 低至 2.6%**。

请问目前在 CSMSC 上面 WER = 2.6% 的 G2P 模型已经开源了吗？

**Comment by yt605155624** [comment]
目前的 G2P 和 文本正则等都已经融入了我们的文本前端流程中
计算 G2P 和 文本正则 CER/WER 请参考
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/g2p
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tn
