### ISSUE TITLE
PP-ASR超过15秒识别就越来越慢

### ISSUE THREAD

**Issue by forlor** [PaddlePaddle/PaddleSpeech#1969]

**Comment by yt605155624** [comment]
原因是目前流式识别的 attention 是关注从开始到当前 chunk 的内容，而 attention 的时间复杂度是 n2d ，n 表示序列长度，所以随着时间推移速度就会变慢
这个我们会排期优化，您也可以看看代码，在合适的位置截断输入，因为可能目前的时刻并不太需要关注太久之前的信息

**Comment by yt605155624** [comment]
这个问题已经在 https://github.com/PaddlePaddle/PaddleSpeech/pull/2016 解决，可以通过把 yaml 里面 `num_decoding_left_chunks` 这个参数修改为一个较小的正数（如，8）解决问题，数值和准确率之前需要权衡
