### ISSUE TITLE
安装paddlespeech出现如下错误，求指导

### ISSUE THREAD

**Issue by ciihai** [PaddlePaddle/PaddleSpeech#1971]
安装paddlespeech，出现如下错误：

error: could not create 'build\bdist.win-amd64\wheel\.\dtaidistance\lib\DTAIDistanceC\DTAIDistanceC.xcod
eproj\xcuserdata\wannes.xcuserdatad\xcdebugger\Breakpoints_v2.xcbkptlist': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dtaidistance

ERROR: Could not build wheels for dtaidistance, which is required to install pyproject.toml-based projects

**Comment by yt605155624** [comment]
安装相关问题参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/1397 和 https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195
类似的问题参考 https://stackoverflow.com/questions/53204916/what-is-the-meaning-of-failed-building-wheel-for-x-in-pip-install

windows 上需要安装 c++ 环境

**Comment by ciihai** [comment]
> 安装相关问题参考 #1397 和 #1195 类似的问题参考 https://stackoverflow.com/questions/53204916/what-is-the-meaning-of-failed-building-wheel-for-x-in-pip-install
> 
> windows 上需要安装 c++ 环境

有C++，paddle OCR在用
