### ISSUE TITLE
paddlespeech总是安装不上

### ISSUE THREAD

**Issue by ciihai** [PaddlePaddle/PaddleSpeech#1974]
1、已安装VS2019 ， paddleocr 好用
2、在pycharm 终端使用 pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple   安装paddlespeech
3、总是出现一下错误：
 Building wheel for dtaidistance (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dtaidistance (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [298 lines of output]
      WARNING: Numpy was not found, preparing a version without Numpy support.
 error: could not create 'build\bdist.win-amd64\wheel\.\dtaidistance\lib\DTAIDistanceC\DTAIDistanceC.xcod
eproj\xcuserdata\wannes.xcuserdatad\xcdebugger\Breakpoints_v2.xcbkptlist': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dtaidistance
Failed to build dtaidistance
ERROR: Could not build wheels for dtaidistance, which is required to install pyproject.toml-based projects

4、试过numpy 1.22.4  numpy1.22.3 ,试了网上各种办法，都不好用。
5、请指点。

**Comment by yt605155624** [comment]
你先看一下为什么你装了 numpy 却会报找不到 numpy 的问题吧

**Comment by ciihai** [comment]
我想不明白啊
能给个提示不？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 凌晨0:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSpeech] paddlespeech总是安装不上 (Issue #1974)




 
你先看一下为什么你装了 numpy 却会报找不到 numpy 的问题吧

**Comment by yt605155624** [comment]
参照文档单独安装 dtaidistance 试试https://dtaidistance.readthedocs.io/en/latest/usage/installation.html

**Comment by ciihai** [comment]
多谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 凌晨0:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSpeech] paddlespeech总是安装不上 (Issue #1974)




 
参照文档单独安装 dtaidistance 试试https://dtaidistance.readthedocs.io/en/latest/usage/installation.html

**Comment by qijigaici** [comment]
error: could not create 'build\bdist.win-amd64\wheel\.\dtaidistance\lib\DTAIDistanceC\DTAIDistanceC.xcodeproj\xcuserdata\wannes.xcuserdatad\xcdebugge
r\Breakpoints_v2.xcbkptlist': No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dtaidistance
Failed to build dtaidistance
ERROR: Could not build wheels for dtaidistance, which is required to install pyproject.toml-based projects
WARNING: Ignoring invalid distribution -ip (e:\programdata\anaconda3\envs\py39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (e:\programdata\anaconda3\envs\py39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (e:\programdata\anaconda3\envs\py39\lib\site-packages)

**Comment by yt605155624** [comment]
dtaidistance 是 paddleaudio 的依赖，paddleaudio 是 paddlespeech 的依赖，我们现在打算移除掉 dtaidistance 这个依赖

**Comment by ciihai** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 晚上8:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSpeech] paddlespeech总是安装不上 (Issue #1974)




 
dtaidistance 是 paddleaudio 的依赖，paddleaudio 是 paddlespeech 的依赖，我们现在打算移除掉 dtaidistance 这个依赖

**Comment by yt605155624** [comment]
我们已经发布了不依赖 dtaidistance 的 paddleaudio 1.0.1， 大家可以重新安装 paddlespeech 试试
@ciihai @qijigaici

**Comment by ciihai** [comment]
installed successfully

谢谢，高效率，赞

**Comment by qijigaici** [comment]
> 我们已经发布了不依赖 dtaidistance 的 paddleaudio 1.0.1，大家可以重新安装 paddlespeech @ciihai @qijigaici

优秀
