### ISSUE TITLE
fastspeech2静态图推断下怎么调整语速？

### ISSUE THREAD

**Issue by Kevinkaiyan** [PaddlePaddle/PaddleSpeech#1983]
fastspeech2的onnx模型我是从链接下载的，自己尝试将stylefastspeech2转换为onnx一直报错，有没有什么办法在fastspeech2_csmsc_onnx_0.2.0.onnx上优化语速问题呢？

**Comment by yt605155624** [comment]
我们之前调整语速都是基于动态图模型的，fastspeech2 的各个模块可以随便调，感觉如果要在 onnx 模型调整 duration 话，可能需要导出多个子模块，比如 encoder 导出一个，decoder 导出一个，这样才能加入自己的调节吧
关于导出多个模块，可以餐参考 tts3/run_cnndecoder.sh

**Comment by Kevinkaiyan** [comment]
> 我们之前调整语速都是基于动态图模型的，fastspeech2 的各个模块可以随便调，感觉如果要在 onnx 模型调整 duration 话，可能需要导出多个子模块，比如 encoder 导出一个，decoder 导出一个，这样才能加入自己的调节吧 关于导出多个模块，可以餐参考 tts3/run_cnndecoder.sh

调语速的话是需要DurationPredictor这个模块吗？

**Comment by yt605155624** [comment]
这个要看你是要自己完全决定每个音素的发音时间还是在预测出来的结果的基础上，调一定的比例。
