### ISSUE TITLE
Feature request: Please include Spanish

### ISSUE THREAD

**Issue by inglesuniversal** [PaddlePaddle/PaddleSpeech#1990]
So far I see only two languages under your documentation.

Thanks

**Comment by yt605155624** [comment]
Sorry, our R & D are all Chinese. Spanish is a small language for us. If you know anything about Spanish and Spanish speech dataset, please refer to our examples to organize new Spanish examples~

**Comment by puppetm4st3r** [comment]
its there a way or a tutorial/example for train your models for other TTS langs (like spanish)?
