### ISSUE TITLE
ted_en_zh的st任务相关问题

### ISSUE THREAD

**Issue by jannicaTan** [PaddlePaddle/PaddleSpeech#2010]
您好，我在ted_en_zh这个st任务中尝试切换数据集。
1.之前切换过相对小的数据集（6000句左右），能够运行并验证，但是验证的时候，对于读取的任何wav,hyp一直只重复同一句结果，请问什么原因呢？修改了epoch但是没有效果。
2.这次切换了一个只有400条的极小数据集（因为文本更准确），在第一步数据处理部分就出现了这个问题，请问如何修改？
`
2022-06-03 20:13:34.284 | INFO     | paddlespeech.s2t.frontend.augmentor.augmentation:__init__:123 - Augmentation: []
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleSpeech/utils/compute_mean_std.py", line 87, in <module>
    main()
  File "/home/aistudio/work/PaddleSpeech/utils/compute_mean_std.py", line 82, in main
    num_workers=args.num_workers)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/frontend/normalizer.py", line 118, in __init__
    num_workers)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/frontend/normalizer.py", line 195, in _compute_mean_std
    'mean_stat': list(all_mean_stat.tolist()),
AttributeError: 'NoneType' object has no attribute 'tolist'
`

**Comment by zh794390558** [comment]
1. 应该数据过下。可以看下是否能复现结果，可以的话尝试fintune试试。
2. 第二个问题看下/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/frontend/normalizer.py代码，追查下出错的位置。
`'mean_stat': list(all_mean_stat.tolist()), AttributeError: 'NoneType' object has no attribute 'tolist'`

6000条还是太小

**Comment by jannicaTan** [comment]
> 1. 应该数据过下。可以看下是否能复现结果，可以的话尝试fintune试试。
> 2. 第二个问题看下/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/frontend/normalizer.py代码，追查下出错的位置。
>    `'mean_stat': list(all_mean_stat.tolist()), AttributeError: 'NoneType' object has no attribute 'tolist'`
> 
> 6000条还是太小

谢谢解答
问题一的数据集太大了我之前用其中一部分跑的 hyp也是一直同一句 我重新下载全部的跑一下
问题二是我自己数据集的问题，有空白文本导致的，删除存在空白的文本就可以进行了。
还有个疑问，请问为什么配置文件的lr要设置为2.5？看了相关文档和其他任务的代码基本都为0.001 https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Adam_cn.html

**Comment by jannicaTan** [comment]
您好，我最近将自己的数据集扩充到了14000条，并进行了过滤整理，去除了空白文本。
目前已经解决一直重复同一句的问题了
我参考了asr finetune的问题回答，替换词表，然后将ted_en_zh的模型通过替换的方式替换为0.pdparams进行训练
但是遇到了以下问题：
1.我的loss前期收敛还挺快的，但是收敛到loss=33的时候就会开始小幅震荡不再有大的变化，大概30个epoch左右就会震荡然后不变。小白感觉是过拟合，请问除了增加数据集还有什么好的防止过拟合让它收敛的办法吗？主要查看哪个文件呢？尝试修改一些超参数没有什么明显变化
2.我将ASR的结果也进行了输出，对比发现有的时候ASR完全符合目标转录文本，但是翻译语句对不上目标翻译文本。并且翻译出错的句子是能够在训练集中找到原句的，感觉它并不是按单词去翻译的，而是整句直接找关系最相关的去翻译。
3.想问一下：这里out的`in_features=4864`是怎么计算的呢，这里使用预训练的时候没有对上😭
```
(embed): Conv2dSubsampling4(
      (pos_enc): PositionalEncoding(
        (dropout): Dropout(p=0.1, axis=None, mode=upscale_in_train)
      )
      (conv): Sequential(
        (0): Conv2D(1, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (1): ReLU()
        (2): Conv2D(256, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (3): ReLU()
      )
      (out): Sequential(
        (0): Linear(in_features=4864, out_features=256, dtype=float32)
      )
    )
```

**Comment by jannicaTan** [comment]
您好，我最近将自己的数据集问题编排到了 14000 条，并进行了过滤整理，删除了空白文本。
目前解决了hyp重复的问题
我根据asr-finetune的回答，替换了词表，然后将ted_en_zh的模型通过替换方式替换为0.pdparams进行了训练
但是遇到了以下问题：
 1.我的loss下降在初期还挺快的，但是收敛到loss=33的时候开始小幅度震荡，大概有 30 个epoch后震荡不变的小感觉呢。
2.我将 ASR 的结果也进行了输出，对比发现有的时候ASR与目标的识别语句完全一样，但是ST的翻译语句却和目标的翻译语句不同，而且错误的翻译语句大多能够在训练集中找到原句，感觉它并不是按照word去逐个翻译,而是找到可能性最高的一句话去输出。这是啥原因呢？
 3.想问一下：想问一下这里embedding层中的`in_features=4864`怎么计算的呢，这里预训练的时候没有对上😭
```
(embed): Conv2dSubsampling4(
      (pos_enc): PositionalEncoding(
        (dropout): Dropout(p=0.1, axis=None, mode=upscale_in_train)
      )
      (conv): Sequential(
        (0): Conv2D(1, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (1): ReLU()
        (2): Conv2D(256, 256, kernel_size=[3, 3], stride=[2, 2], data_format=NCHW)
        (3): ReLU()
      )
      (out): Sequential(
        (0): Linear(in_features=4864, out_features=256, dtype=float32)
      )
    )
```
