### ISSUE TITLE
MFA训练过程中意外中断

### ISSUE THREAD

**Issue by yrsn509** [PaddlePaddle/PaddleSpeech#2011]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
MFA训练到sat_3步骤后到生成TextGrid阶段时报错中断

**To Reproduce**
1.打开conda虚拟环境
2.键入指令：mfa train data/wav/EILEEN/split/ MFA/pinyin_eng.dict MFA/EILEEN.zip data/TextGrid/EILEEN/ --clean

**Screenshots**
![08d39dc43e6f42b4fa078cca3bc473a](https://user-images.githubusercontent.com/62604868/171990459-ee22cccf-9fa3-4200-94e5-287692942ff6.png)

** Environment (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.9.10
 - PaddlePaddle Version: 2.3
 - Model Version [e.g. 2.0.0]
 - GPU: NVIDIA RTX 2060 6GB
 - CUDA/CUDNN Version: CUDA 11.2 
 - 基于VtuberTalk(https://github.com/jerryuhoo/VTuberTalk)

**Comment by yt605155624** [comment]
MFA 相关问题建议直接去 MFA repo 询问
