### ISSUE TITLE
TTS 推理完之后内存不释放

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2024]
你好，我遇到一个问题，TTS预测万之后内存不释放的情况。详细情况如下：
**TTS模型：动态声学模型 + onnx声码器**
服务：使用Websocket 进行模型加载和部署
详情：
**1：初始加载模型和服务的时候，**会消耗GPU大概1.7G内存（如图）：
<img width="164" alt="0" src="https://user-images.githubusercontent.com/27938135/172755662-3ed4fb72-92eb-40be-b536-4b3e6005add7.png">
**2：加载完之后**进行语音合成的时候内存会涨上去。整个合成任务过程中，内存能够涨到13G左右（如图），任务结束之后，这个内存无法释放。即，无法从13G回到1.7G。
<img width="162" alt="1" src="https://user-images.githubusercontent.com/27938135/172755822-efac4ae5-133f-4a89-ad17-888e3d831624.png">
请问paddle有没有内存释放机制，能够在任务结束之后，再不关闭服务的前提下，把多出来的内存释放了？

**Comment by yt605155624** [comment]
这个去 paddle 的 issue 问下吧
