### ISSUE TITLE
ASR 测试语音时出现错误

### ISSUE THREAD

**Issue by weekdaysun** [PaddlePaddle/PaddleSpeech#2027]
环境：centos ，使用paddle 2.3.0版本，python3.9
环境安装完成
![image](https://user-images.githubusercontent.com/99238498/172830997-463c512b-9364-434f-94b1-e1550a143db0.png)
![image](https://user-images.githubusercontent.com/99238498/172831112-7f8f6328-1e24-4a04-8fe4-b134838a78c0.png)
安装完成之后，asr语音识别测试语音出现错误，如下：
![image](https://user-images.githubusercontent.com/99238498/172830720-cdc24cdc-d6b9-42fe-9478-b081a084cff1.png)
麻烦回复一下哪里的错误，是环境没有搭建好还是其他

**Comment by zh794390558** [comment]
看着像模型文件破损

**Comment by iftaken** [comment]
你试试把`/root/.paddlespeech/models/conformer_wenetspeech-zh-16k`删掉，再运行重新下载一次看看
