### ISSUE TITLE
关于标点恢复

### ISSUE THREAD

**Issue by CocaColaKing** [PaddlePaddle/PaddleSpeech#2038]
标点恢复的模块怎么训练啊？

**Comment by yt605155624** [comment]
please see : https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/iwslt2012/punc0

but the model we relesed are not trained with the wslt2012 dataset, but a big dataset used within our company

**Comment by CocaColaKing** [comment]
> 

好的，谢谢

**Comment by CocaColaKing** [comment]
使用训练的出来的模型，预测结果没有最后一位的标点？最后一个字符预测的永远是0。

**Comment by yaleimeng** [comment]
@yt605155624  我使用自己的语料（带四种标点，。？！）训练，结果也是：大部分语句能正常预测，有些语句最后一个字后面没有标点，如下图所示。原因不明。。希望答疑解惑。
另外，自己按照指引训练保存的是checkpoint（pdz格式），占空间比较大。怎样能转换成类似预训练模型（ernie_linear_p7_wudao）那种格式啊？
![image](https://user-images.githubusercontent.com/28124722/178934929-b4f0dfb1-e83f-41bc-b42d-d501232e852f.png)

**Comment by yaleimeng** [comment]
@CocaColaKing  我在paddleNLP里面基于序列标注任务已实现了标点预测。。paddlespeech依赖比较多，感觉比较重，而且得到的模型也很大。
而且在改写过程中也遇到末尾没有标点的问题，这种情况通常是遗漏了末尾处理逻辑，一般改一下解码部分代码就可以了。

**Comment by CocaColaKing** [comment]
> 

ok
