### ISSUE TITLE
paddlespeech_client 使用websocket协议连接 server失败

### ISSUE THREAD

**Issue by 91he** [PaddlePaddle/PaddleSpeech#2042]
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_tts_server
我按照上述链接进行测试，使用http协议时tts合成正常，使用websocket协议时server返回403
![image](https://user-images.githubusercontent.com/5378476/174051395-6d248c1c-f9a8-4ce5-934b-b557c3880297.png)

**Comment by mader89** [comment]
怎么解决的？

**Comment by 91he** [comment]
配置文件中的protocol错了
