### ISSUE TITLE
可以变合成边播放吗？数据比较多，pwg_infweence(mel)很慢

### ISSUE THREAD

**Issue by PCITBoy** [PaddlePaddle/PaddleSpeech#2049]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - GCC/G++ Version [e.g. 8.3]
 - Python Version [e.g. 3.7]
 - PaddlePaddle Version [e.g. 2.0.0]
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. Tesla V100-SXM2-32GB/440.64.00]
 - CUDA/CUDNN Version [e.g. cuda-10.2]
 - MKL Version
- TensorRT Version

**Additional context**

**Comment by yt605155624** [comment]
see: https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_tts_server

**Comment by linkec** [comment]
可以看下 https://www.bilibili.com/video/BV1N94y117ng 的实现方法

**Comment by yt605155624** [comment]
> 可以看下 https://www.bilibili.com/video/BV1N94y117ng 的实现方法

教程很赞，可以在 discussion 开个贴把链接放上去
