### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by PCITBoy** [PaddlePaddle/PaddleSpeech#2059]
Downloading paddlespeech_ctcdecoders-0.2.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (16.8 MB)

**Comment by linkec** [comment]
建议检查一下到 paddlespeech.bj.bcebos.com 的连接，这个是百度云的OSS服务，理论上是不需要科学上网的
