### ISSUE TITLE
[tts] Multilingual Speech Synthesis 中英文混合语音合成 

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#2064]
Input a sentence that contains both Chinese and English, and TTS outputs the corresponding audio and keeps the voice consistent

```text
hello, 你好吗？I love you！
```

see: [Learning to Speak Fluently in a Foreign Language: Multilingual Speech Synthesis and Cross-Language Voice Cloning](https://arxiv.org/abs/1907.04448)

**Comment by lym0302** [comment]
中英混合语音合成部分代码已上传，后续会完善再合入 PaddleSpeech. 
https://github.com/lym0302/PaddleSpeech/tree/train_zh_en

**Comment by yt605155624** [comment]
PR:
- mix frontend: https://github.com/PaddlePaddle/PaddleSpeech/pull/2143
- the baseline of mix model: https://github.com/PaddlePaddle/PaddleSpeech/pull/2174
- cli support: https://github.com/PaddlePaddle/PaddleSpeech/pull/2203
- mix example: https://github.com/PaddlePaddle/PaddleSpeech/pull/2234
- update cli: https://github.com/PaddlePaddle/PaddleSpeech/pull/2249

**Comment by Lennon-cheng** [comment]
@lym0302  中英文语音合成，代码大概什么时候发出呀。或者中英文语音合成代码，除了 mix_frontend 不同外，还有哪些部分不同呀，谢谢

**Comment by yt605155624** [comment]
@Lennon-cheng 你好，paddlespeech 1.1 已经支持中英文混合了，欢迎试用！参考：

训练代码：
- https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3

CLI：
- https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech 
   <img width="1034" alt="a692855833060d6a379a4cc52add5816" src="https://user-images.githubusercontent.com/24568452/186381118-447880c0-10ec-4567-937e-673f2ac39857.png">
