### ISSUE TITLE
多音字支持吗?需要怎么设置?

### ISSUE THREAD

**Issue by wangcc57** [PaddlePaddle/PaddleSpeech#2069]
多音字支持吗?需要怎么设置?

**Comment by yt605155624** [comment]
At present, pypinyin is used in G2P. You can add bad polysyllabic words to the dictionary by yourself. Refer to https://github.com/PaddlePaddle/PaddleSpeech/blob/ec759094ad37bfc8ce7a4ab93d4ea74ca17932e0/paddlespeech/t2s/frontend/zh_frontend.py#L96

**Comment by wangcc57** [comment]
load_phrases_dict({u'还书': [[u'hua2n'], [u'shu1']]}) 这个没起作用
load_phrases_dict({u'还款': [[u'hua2n'], [u'kua3n']]}) 这个可以

还有啥机关吗?

**Comment by wangcc57** [comment]
应该是分词的问题,jieba分词分的不对

**Comment by yt605155624** [comment]
You can fix the error of jieba for specific words according to your own needs by adding rules, such as https://github.com/PaddlePaddle/PaddleSpeech/blob/0fa3fdb9ee89ca399b0f63ef2117c6370dc1f33d/paddlespeech/t2s/frontend/tone_sandhi.py#L236
