### ISSUE TITLE
调用语音合成播报报错

### ISSUE THREAD

**Issue by PCITBoy** [PaddlePaddle/PaddleSpeech#2092]
ubuntu流式语音合成服务，服务是设置开机自启动，开始一两次调用语音合成正常，后面在调用服务就报OSError: [Errno -9997] Invalid sample rate，服务进程还在，只有重启之后，后续调用语音合成就没有问题

**Comment by lym0302** [comment]
请问出现这个报错的请求是什么？服务是不会因为异常而终止的，出现这个报错后再请求也仍然会报错吗？
