### ISSUE TITLE
请问支持流式语音识别再训练吗？

### ISSUE THREAD

**Issue by HandsLing** [PaddlePaddle/PaddleSpeech#2093]
我想根据自己的使用场景，增加数据再训练一下流式语音识别，请问要训练example下面的哪个文件呢？

**Comment by yt605155624** [comment]
example: https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/wenetspeech/asr1
finetune: https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972

**Comment by HandsLing** [comment]
那训练完之后，怎么把训练完的模型替换到流式语音识别部署那里去呢？替换一个model.yaml已经对应的模型就可以了么

**Comment by SmileGoat** [comment]
训练好的模型，对应的配置文件yaml上把模型路径写好，以及相关的模型结构也进行更改。

**Comment by Jackwaterveg** [comment]
如果模型的配置（模型结构 或者 特征提取方式）改变了，则需要修改 model.yaml。 而模型的参数文件(*.pdparams)也必须把原来的参数文件替换掉（参数文件位置和原来的一样）

**Comment by HandsLing** [comment]
我发现你们似乎没有给处理wenetspeech数据的脚本，没有使用wenetspeech生成manifest文件的代码，里面使用的代码只是用aishell数据

**Comment by yt605155624** [comment]
> 我发现你们似乎没有给处理wenetspeech数据的脚本，没有使用wenetspeech生成manifest文件的代码，里面使用的代码只是用aishell数据

https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/wenetspeech
