### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Doubledongli** [PaddlePaddle/PaddleSpeech#2095]
调用训练代码 PaddleSpeech\paddlespeech\s2t\exps\u2\bin\train.py 发现
![8d8c24e14acff86c64b7dfac7bc2876](https://user-images.githubusercontent.com/20540661/176392814-3356fa34-2049-40dc-bf2f-049f604e0278.png)

这个地方，如果是截取文件后缀，是不是第一个split也应该是-1而不是0

**Comment by SmileGoat** [comment]
xxx.ark:1023，文件的格式，所以是0，没有问题。
