### ISSUE TITLE
Demo Speech Web 测试问题

### ISSUE THREAD

**Issue by ansent788** [PaddlePaddle/PaddleSpeech#2099]
**Describe the bug**
Safari 测试所有功能无反应；chrome 测试端到端合成可以，流式不行，其他功能无反应。

**To Reproduce**
1. 按教程部署
2. 正常运行

**Screenshots**
Web：
![WechatIMG15](https://user-images.githubusercontent.com/33193762/176398337-afaaaf26-451c-445f-8611-5f5095c54efc.jpeg)
Server：
![WechatIMG17](https://user-images.githubusercontent.com/33193762/176398429-b814e700-7651-4765-8702-f9e2b8e3a8c4.png)

** Environment (please complete the following information):**
 - OS: CentOS 7.9.2009 x86_64
 - GCC/G++ Version 4.8.5 20150623 (Red Hat 4.8.5-44)
 - Python Version 3.7.13
 - PaddlePaddle Version 2.3.0
 - Model Version [e.g. 2.0.0]

**Comment by iftaken** [comment]
其它的都没反应可能是录音失败导致的；检查是否是因为服务部署和游览器不在同一台机器上，以IP访问时，chrome安全策略会禁止录音，修改配置重启游览器即可

[游览器安全策略](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/speech_web/README_cn.md#q%E5%90%8E%E7%AB%AF%E4%BB%A5ip%E5%9C%B0%E5%9D%80%E7%9A%84%E5%BD%A2%E5%BC%8F%E5%89%8D%E7%AB%AF%E6%97%A0%E6%B3%95%E5%BD%95%E9%9F%B3)

**Comment by ansent788** [comment]
好的，我在试下。Server与Web端都在一台服务器部署。浏览器测试时也修改过了。

发自我的iPhone
