### ISSUE TITLE
批量提取音频特征并用于音频检索

### ISSUE THREAD

**Issue by Sweet-BeanOnE** [PaddlePaddle/PaddleSpeech#2110]
目前有一个应用场景，是在许多较长的音频文件中，提供一个不定长的音频文件（一般来说在十几秒钟左右）来检索它来自哪个音频文件以及开始与结束位置。
PaddleSpeech/demos/audio_searching/项目主要参考自这里。
为了拟合输入数据得到正确的匹配结果，我尝试将大段音频文件切分成具有小段间隔且高度重叠的小音频文件并提取特征，主要根据PaddleSpeech/demos/audio_searching/src/encode.py进行改写，它看起来效果不错。但是面对大量的文件进行嵌入并提取特征时，效率太低，这是否与每次重新加载模型并初始化有关？我是不是错过了官方的批量提取接口？

**Comment by yt605155624** [comment]
在一个程序里面只有在第一次调用 Executor 的时候的会初始化模型，要看你的程序是每次重新启动一个程序，还是输入很多路径 for 循环https://github.com/PaddlePaddle/PaddleSpeech/blob/10645e72b60c0ca9025f02b8c639cc5e4335a406/demos/audio_searching/src/encode.py#L26
参考下 https://github.com/PaddlePaddle/PaddleSpeech/issues/1455

**Comment by Sweet-BeanOnE** [comment]
> 在一个程序里面只有在第一次调用 Executor 的时候的初始模式，启动你的程序是重新启动一个程序，还是输入很多用于循环
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/10645e72b60c0ca9025f02b8c639cc5e4335a406/demos/audio_searching/src/encode.py#L26
> 
> 
> 参考下#1455


我使用了
[PaddleSpeech/demos/audio_searching/src/operations/load.py](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/audio_searching/src/operations/load.py)中def extract_features(audio_dir)函数，据我观察他在from encode import get_audio_embedding时，会实例化一次程序：即vector_executor = VectorExecutor()，我并没有进行任何改动，仅仅是对extract_features函数传入文件夹路径，便可以返回结果，采用这种方式在控制台打印的info看起来与readme.md中的Output示例相同，但据我观察，使用cpu时，每次嵌入10s左右的音频会消耗2-3秒，使用gpu也不会带来特别大的提升。请问这个速度是正常现象吗？

**Comment by yt605155624** [comment]
14s 的音频 
[output_16k.wav.zip](https://github.com/PaddlePaddle/PaddleSpeech/files/9026701/output_16k.wav.zip)
，已经下载好模型的情况下，使用如下代码 
```shell
from paddlespeech.cli.vector import VectorExecutor
import time
import logging
logging.disable(logging.ERROR)
def test():
    time_1 = time.time()
    vector_executor = VectorExecutor()
    audio_emb = vector_executor(
        model='ecapatdnn_voxceleb12',
        sample_rate=16000,
        config=None, 
        ckpt_path=None,
        audio_file='./output_16k.wav',
        device=paddle.get_device())
    time_2 = time.time()
    print("time of first time:", time_2-time_1)
    
    audio_emb = vector_executor(
        model='ecapatdnn_voxceleb12',
        sample_rate=16000,
        config=None, 
        ckpt_path=None,
        audio_file='./output_16k.wav',
        device=paddle.get_device())
    print("time of second time:", time.time()-time_2)

import paddle
print("using cpu.......")
paddle.set_device('cpu')
test()
print("using gpu.......")
paddle.set_device('gpu')
test()

```
输出如下：
```text
using cpu.......
time of first time: 3.6437718868255615
time of second time: 1.489311695098877
using gpu.......
W0701 06:40:06.429261 16626 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
W0701 06:40:06.429340 16626 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
time of first time: 10.34752106666565
time of second time: 0.13157153129577637
```
第一次使用 gpu 时可能由于涉及到 gpu 的初始化等，速度会比较慢，第二次，gpu 明显比 cpu 快

**Comment by Sweet-BeanOnE** [comment]
> 14s 的音频 [output_16k.wav.zip](https://github.com/PaddlePaddle/PaddleSpeech/files/9026701/output_16k.wav.zip) ，已经下载好模型的情况下，使用如下代码
> 
> ```shell
> from paddlespeech.cli.vector import VectorExecutor
> import time
> import logging
> logging.disable(logging.ERROR)
> def test():
>     time_1 = time.time()
>     vector_executor = VectorExecutor()
>     audio_emb = vector_executor(
>         model='ecapatdnn_voxceleb12',
>         sample_rate=16000,
>         config=None, 
>         ckpt_path=None,
>         audio_file='./output_16k.wav',
>         device=paddle.get_device())
>     time_2 = time.time()
>     print("time of first time:", time_2-time_1)
>     
>     audio_emb = vector_executor(
>         model='ecapatdnn_voxceleb12',
>         sample_rate=16000,
>         config=None, 
>         ckpt_path=None,
>         audio_file='./output_16k.wav',
>         device=paddle.get_device())
>     print("time of second time:", time.time()-time_2)
> 
> import paddle
> print("using cpu.......")
> paddle.set_device('cpu')
> test()
> print("using gpu.......")
> paddle.set_device('gpu')
> test()
> ```
> 
> 输出如下：
> 
> ```
> using cpu.......
> time of first time: 3.6437718868255615
> time of second time: 1.489311695098877
> using gpu.......
> W0701 06:40:06.429261 16626 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.2
> W0701 06:40:06.429340 16626 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
> time of first time: 10.34752106666565
> time of second time: 0.13157153129577637
> ```
> 
> 第一次使用 gpu 时可能由于涉及到 gpu 的初始化等，速度会比较慢，第二次，gpu 明显比 cpu 快

真的十分感谢您的帮助，这对我来说十分有益！祝您生活愉快！
