### ISSUE TITLE
tts onnx流式部署，am和voc模型不能部署到指定的GPU

### ISSUE THREAD

**Issue by raycool** [PaddlePaddle/PaddleSpeech#2126]
paddle版本 paddlepaddle-gpu: 2.3.0.post112
1. 使用动态模型部署，指定gpu:2, 两个模型均可以部署在gpu2上。
2. 使用onnx部署，指定gpu:2，会出现一个模型部署在gpu:0, 一个模型部署在gpu:2上。
![001](https://user-images.githubusercontent.com/3365153/178140670-c4a07948-3019-4791-bb11-94c4eb950c5f.jpg)
![002](https://user-images.githubusercontent.com/3365153/178140673-9527eca5-27ab-40f2-9d9d-857bce91c286.jpeg)

**Comment by lym0302** [comment]
感谢提问，已经提交修复pr，可以按照这个方式来：https://github.com/PaddlePaddle/PaddleSpeech/pull/2129

**Comment by yt605155624** [comment]
可以等 pr 合入后, git clone PaddleSpeech 
```bash
cd PaddleSpeech
pip install . 
```
源码安装 develop 版本的 paddlespeech, 或者在安装 paddlespeech 的位置按照 pr 修改源码
