### ISSUE TITLE
💬 PaddleSpeech 文档问题留言

### ISSUE THREAD

**Issue by iftaken** [PaddlePaddle/PaddleSpeech#2131]
【这个Issue用于文档问题留言与跟进，开发者们遇到问题的地方以及相关的建议可以在这里进行留言】

PaddleSpeech文档资料
+ [【readthedoc】](https://paddlespeech.readthedocs.io/en/latest/)
+ [【飞桨PaddleSpeech语音技术】](https://aistudio.baidu.com/aistudio/education/group/info/25130)
+ [【wiki】](https://github.com/PaddlePaddle/PaddleSpeech/wiki)
+ [【FAQ】](https://github.com/PaddlePaddle/PaddleSpeech/discussions/1989)

[【Discussions】](https://github.com/PaddlePaddle/PaddleSpeech/discussions)区也有很多精华内容

目前PaddleSpeech入门教程[【PaddleSpeechStudy】](https://github.com/iftaken/PaddleSpeechStudy)在编写中，大家有想了解的问题或者Demo可以在本Issue下进行留言。

**Comment by iftaken** [comment]
新增问题：
1. TTS数据如何准备，MFA使用教程
2. C++调用声音分类模型
3. C++调用PaddleSpeech语音识别模型，加快执行效率
4. 希望能细化ASR，TTS的训练过程[【希望能细化ASR/TTS的训练流程】](https://github.com/PaddlePaddle/PaddleSpeech/issues/2132)

**Comment by lijielijie** [comment]
win系统怎么安装使用

**Comment by yt605155624** [comment]
> win系统怎么安装使用

和其他系统一样的，遇到问题在 repo 里搜一下就能搜到 windows 安装的一些经验

**Comment by BrightXiaoHan** [comment]
感谢PaddleSpeech的开发者。
我想使用其他语言调用paddlespeech_server，目前只能使用提供的`paddlespeech_client.py`脚本调用，可否提供http api接口和websockt api 接口的文档呢，方便其他编程语言进行调用？

**Comment by yt605155624** [comment]
> 感谢PaddleSpeech的开发者。 我想使用其他语言调用paddlespeech_server，目前只能使用提供的`paddlespeech_client.py`脚本调用，可否提供http api接口和websockt api 接口的文档呢，方便其他编程语言进行调用？

@BrightXiaoHan 
接口文档请参考
- [PaddleSpeech Server RESTful API](https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-Server-RESTful-API)
- [PaddleSpeech Server WebSocket API](https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-Server-WebSocket-API)

**Comment by SuperMaskv** [comment]
请问，paddlecloud/paddlespeech是官方的镜像吗？如果是的话可以提供一些文档说明吗，比如如何启动asr stream server，应该预留哪些容器端口。

**Comment by yt605155624** [comment]
> 请问，paddlecloud/paddlespeech是官方的镜像吗？如果是的话可以提供一些文档说明吗，比如如何启动asr stream server，应该预留哪些容器端口。

paddlecloud/paddlespeech 是 paddlecloud 为我们提供的镜像，使用 paddlecloud 的说明可以参考安装文档链接中的 paddlecloud 中的链接，启动 asr stream server 参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_asr_server , 端口可以自己在 config 中设置

**Comment by J-ZZ** [comment]
请问 paddlespeech中asr部分如何训练自己的数据呢?有关训练部分的代码是s2t 部分吗?
