### ISSUE TITLE
请问Ubuntu18.04在medium模式下支持声音克隆的训练吗？如果是的话，训练流程是什么

### ISSUE THREAD

**Issue by SchweitzerGAO** [PaddlePaddle/PaddleSpeech#2145]
如题

**Comment by yt605155624** [comment]
支持，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/vc1

**Comment by SchweitzerGAO** [comment]
如果是自己按照aishell3格式标注的数据也可以按照这个流程走吗，需要事先做什么预处理吗
@yt605155624

**Comment by yt605155624** [comment]
可以，按照我们的 README 即可，需要训练 MFA， README 里都有

**Comment by SchweitzerGAO** [comment]
好的谢谢，我了解了
