### ISSUE TITLE
按照教程跑语音分类报错

### ISSUE THREAD

**Issue by LZH-0225** [PaddlePaddle/PaddleSpeech#2152]
代码
import paddle
import numpy as np
import soundfile as sf
from matplotlib import pyplot as plt
from paddleaudio import load

data, sr = load(file='./dog.wav', mono=True, dtype='float32')  # 单通道，float32音频样本点

x = paddle.to_tensor(data,place=paddle.CUDAPlace(2))#需要一张完整的卡跑
n_fft = 1024#FFT样本点个数
win_length = 1024#窗函数长度
hop_length = 320#音频帧之间的间隔

spectrogram = paddle.signal.stft(x, n_fft=n_fft, win_length=win_length, hop_length=hop_length, onesided=True)  
print('spectrogram.shape: {}'.format(spectrogram.shape))
print('spectrogram.dtype: {}'.format(spectrogram.dtype))

报错
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_345753/1984477273.py in <module>
----> 1 spectrogram = paddle.signal.stft(x, n_fft=n_fft, win_length=win_length, hop_length=hop_length, onesided=True)
      2 print('spectrogram.shape: {}'.format(spectrogram.shape))
      3 print('spectrogram.dtype: {}'.format(spectrogram.dtype))

~/miniconda3/envs/py37/lib/python3.7/site-packages/paddle/signal.py in stft(x, n_fft, hop_length, win_length, window, center, pad_mode, normalized, onesided, name)
    315 
    316     if x_rank == 1:  # (batch, seq_length)
--> 317         x = x.unsqueeze(0)
    318 
    319     if hop_length is None:

~/miniconda3/envs/py37/lib/python3.7/site-packages/paddle/tensor/manipulation.py in unsqueeze(x, axis, name)
   1337     """
   1338 
-> 1339     return layers.unsqueeze(x, axis, name)
   1340 
   1341 

~/miniconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py in unsqueeze(input, axes, name)
   6570             ]
   6571         if _in_legacy_dygraph():
-> 6572             out, _ = _C_ops.unsqueeze2(input, 'axes', axes)
   6573             return out
   6574         return _C_ops.final_state_unsqueeze(input, axes)[1]

RuntimeError:   [operator < unsqueeze2 > error]

**Comment by yt605155624** [comment]
```bash
wget https://paddlespeech.bj.bcebos.com/PaddleAudio/dog.wav
```
后执行上述代码，输出
```text
spectrogram.shape: [513, 305]
spectrogram.dtype: paddle.complex64
```
请问你的 paddle 版本是什么，我在 develop 版本的 paddle 上是不报错的，请更新 paddle 到 2.3.0 或者安装 develop 版本的 python https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html

**Comment by LZH-0225** [comment]
>
我的paddle版本 
paddlepaddle-gpu          2.3.1.post116            pypi_0    pypi

**Comment by yt605155624** [comment]
请试一下别的版本的 paddle，比如 2.3.0 或者 develop，如果都不行，看你的 cuda 版本很新，可能需要去 paddle issue 提问了，此处代码还没有用到具体的套件代码，是框架的问题不是套件的问题

**Comment by SmileGoat** [comment]
遇到了相同的问题，换了个版本就可以work了。

**Comment by lizhaohuigit1** [comment]
> 遇到了相同的问题，换了个版本就可以work了。
> 请试一下别的版本的 paddle，比如 2.3.0 或者 develop，如果都不行，看你的 cuda 版本很新，可能需要去 paddle issue 提问了，此处代码还没有用到具体的套件代码，是框架的问题不是套件的问题
现在在docker跑已经没问题了

**Comment by LZH-0225** [comment]
> 请试一下别的版本的 paddle，比如 2.3.0 或者 develop，如果都不行，看你的 cuda 版本很新，可能需要去 paddle issue 提问了，此处代码还没有用到具体的套件代码，是框架的问题不是套件的问题

现在在docker跑已经没问题了

**Comment by LZH-0225** [comment]
> 遇到了相同的问题，换了个版本就可以work了。

ok，我现在在docker跑了，没啥问题了
