### ISSUE TITLE
[TTS]ErnieSAT

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#2154]
Introduction:
- https://github.com/PaddlePaddle/ERNIE/tree/repro/ernie-sat

PR:
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2052
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2117
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2263
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2287
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2316

**Comment by yt605155624** [comment]
Loss of vtck (8 gpus):
<img width="938" alt="image" src="https://user-images.githubusercontent.com/24568452/186370373-7ddd1eb2-807a-40da-b983-dd6f6559dca8.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/24568452/186370427-71823804-956c-4322-a97f-73dd60c8c26f.png">

**Comment by yt605155624** [comment]
Loss of aishell3 (8 gpus):

<img width="939" alt="image" src="https://user-images.githubusercontent.com/24568452/186371601-5e18fac9-1896-471a-bb0a-80178d85b170.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/24568452/186371802-6cd861bd-a16d-44cb-9f2b-312a1ad36c69.png">

**Comment by yt605155624** [comment]
Loss of aishell3_vctk (8 gpus):
![image](https://user-images.githubusercontent.com/24568452/186372502-fdc5bd64-61ed-4f41-bd30-483ddd8a7984.png)

![image](https://user-images.githubusercontent.com/24568452/186372638-b4f1c873-3061-46f9-b369-f7e82800cd11.png)

**Comment by sixyang** [comment]
请问从听感上来说，ErnieSAT 相对于 fastspeech2+pwgan 有什么区别吗？效果会更好一些？

**Comment by yt605155624** [comment]
效果应该差不多， ERNIE-SAT 提供了一个模型解决多个问题的跨模态模型， FS2 是纯声学模型
