### ISSUE TITLE
TTS 粵語 男聲/女聲 數據集

### ISSUE THREAD

**Issue by dentalab** [PaddlePaddle/PaddleSpeech#2160]
請問哪裡可以下載適合PaddleSpeech的粵語 男聲/女聲 數據集，謝謝！

**Comment by yt605155624** [comment]
你好，PaddleSpeech TTS 没有粤语上的案例，数据集没有专门研究过，https://commonvoice.mozilla.org/zh-CN 里面有粤语数据集你看下
