### ISSUE TITLE
voxceleb2下载不了了？

### ISSUE THREAD

**Issue by haha010508** [PaddlePaddle/PaddleSpeech#2161]
` wget http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aacaa --user ***** --password *******
--2022-07-18 15:41:36--  http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aacaa
Resolving www.robots.ox.ac.uk (www.robots.ox.ac.uk)... 129.67.94.2
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aacaa [following]
--2022-07-18 15:41:39--  https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_dev_aacaa
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-07-18 15:41:40 ERROR 404: Not Found.
`
有谁知道怎么下载吗？

**Comment by SmileGoat** [comment]
网路问题，建议使用畅通稳定的网络下载，vox2数据集非常大。或者搜索一下第三方链接。

**Comment by haha010508** [comment]
> 网路问题，建议使用畅通稳定的网络下载，vox2数据集非常大。或者搜索一下第三方链接。

不是网络问题，好像就是不提供了，你可以试试，vox1我是可以下载的

**Comment by starmoon-1134** [comment]
https://mm.kaist.ac.kr/datasets/voxceleb/

可以从这里下载，需要非个人邮箱，公司邮箱就能用，机器审核，很快就能收到邮件
