### ISSUE TITLE
该怎样进行语音情绪识别工作呢

### ISSUE THREAD

**Issue by BeyondLightYear** [PaddlePaddle/PaddleSpeech#2163]

**Comment by yt605155624** [comment]
本质是分类问题，如果有数据，按照声音分类做即可，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/esc50
情绪数据集参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/tts/tts_datasets.md
