### ISSUE TITLE
是否支持流式实时语音克隆服务呢

### ISSUE THREAD

**Issue by SchweitzerGAO** [PaddlePaddle/PaddleSpeech#2166]
在 #2145 的基础上，请问是否支持流式实时语音克隆服务呢，谢谢！

**Comment by yt605155624** [comment]
目前不支持，但是我们目前 vc1 是基于 fastspeech2 的，所以可以参照 csmsc 上的 fastspeech2_cnndecoder，用 vc1 的方式训练一个解码器是 cnndecoder 的 fastspeech2，然后导出 onnx 模型加入到服务中即可

**Comment by SchweitzerGAO** [comment]
好的谢谢，我试一试

**Comment by SchweitzerGAO** [comment]
还有一个问题，流式TTS服务是否可以更换成自己的voice cloning模型呢，也就是不用原始提供的声音进行tts

**Comment by yt605155624** [comment]
> 还有一个问题，流式TTS服务是否可以更换成自己的voice cloning模型呢，也就是不用原始提供的声音进行tts

我感觉我上面的回复已经回答了这个问题，结论就是可以，但是模型结构要符合 fastspeech2_cnndecoder 并且要导出 onnx 模型，voice cloning 模型本身就是用输入的语音进行合成

**Comment by SchweitzerGAO** [comment]
好的，谢谢&nbsp;


星际宝贝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 上午10:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSpeech] 是否支持流式实时语音克隆服务呢 (Issue #2166)





  
还有一个问题，流式TTS服务是否可以更换成自己的voice cloning模型呢，也就是不用原始提供的声音进行tts
  
我感觉我上面的回复已经回答了这个问题，结论就是可以，但是模型结构要符合 fastspeech2_cnndecoder 并且要导出 onnx 模型，voice cloning 模型本身就是用输入的语音进行合成
