### ISSUE TITLE
切换英文语音合成报错 get_input_ids() got an unexpected keyword argument 'get_tone_ids'

### ISSUE THREAD

**Issue by Betterman-qs** [PaddlePaddle/PaddleSpeech#2170]
要切换成英文语音合成时，更改了/paddlespeech/server/conf/application.yaml这个配置文件中的tts_python里面的声学模型和声码器，声学模型用的是fastspeech2_ljspeech，声码器用的pwgan_ljspeech，并且lang改为en，但是报错 get_input_ids() got an unexpected keyword argument 'get_tone_ids'

**Comment by wangtiance** [comment]
这个问题对于paddlespeech.cli.tts.TTSExecutor依然存在，我为了中文和英文合成各创造了一个object才避开
