### ISSUE TITLE
标点恢复怎样进行批处理呢？

### ISSUE THREAD

**Issue by lianyi-q** [PaddlePaddle/PaddleSpeech#2173]
请问，想要对大量文本做标点恢复，怎样调取接口来做呢？

**Comment by yt605155624** [comment]
You can try PythonAPI, the model will only init for the first time : https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/punctuation_restoration

Or you can try batch-cli : https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-CLI---Batch-Process#punc
