### ISSUE TITLE
csmsc TTS pipeline 跑不出结果

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2175]
- 下载了 fastspeech2_nosil_baker_ckpt_0.4 和 pwg_baker_ckpt_0.4 两个模型
- 然后按照 TTS 流水线 给的demo，跑不出来结果

```python
model.set_state_dict(
    paddle.load(args.fastspeech2_checkpoint)["main_params"])

这个args 是bug吗？我直接替换成了

model.set_state_dict(
    paddle.load("./fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz")["main_params"])
```

- 希望解答，谢谢

**Comment by yt605155624** [comment]
你所参考的文档只是一个简单的流水线展示，不能直接跑出结果，可以参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/csmsc/tts3 使用 tts
或者直接使用 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech

**Comment by hackerxiaobai** [comment]
- 感谢，我已经明白了，不过提个小意见，训练自己的数据集，文档感觉不够清楚，特别是MFA这一块，对于刚入门的来说，还是有点懵的
