### ISSUE TITLE
TTS 声学模型fastspeech2 和声码器hifigan，模型转换是否支持batchsize

### ISSUE THREAD

**Issue by liroda** [PaddlePaddle/PaddleSpeech#2176]
您好，实际部署模型时候，希望模型能支持batchsize 增加并发，训练完成的tts 声学模型fastspeech2 和 声码器hifigan ，在动态模型到静态模型转换加入batchsize维度报错，请问这个可以怎么解决呢？

am_inference = jit.to_static(
                am_inference,
                input_spec=[
                    InputSpec(shape=[-1,-1], dtype=paddle.int64)
                   ])

**Comment by yt605155624** [comment]
你自己看下 fastspeech_inference ，本身就不支持， batch 需要改代码

**Comment by liroda** [comment]
好的，那请教一下子龙姐，这块的话在推理阶段，如果修改成支持batchsize 版本的，输入input 的话text[batch,phoneids] 同事需要变量mask 吗？

**Comment by piekey1994** [comment]
> 你自己看下 fastspeech_inference ，本身就不支持， batch 需要改代码

请问直接改encoder_infer让它读一个pad后的batch和对应的ilens直接传给_forward做推理会有问题吗
