### ISSUE TITLE
csmsc synthesize 和 synthesize_e2e 两者跑出来的音频结果差距挺大

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2177]
- 第一次跑TTS相关的，在自己数据集上训练的模型
- csmsc synthesize 和 synthesize_e2e 两者跑出来的音频结果差距挺大
- 请问这个是合理的吗？

**Comment by hackerxiaobai** [comment]
- 我看了下代码，synthesize 是拿到音频以及对应的.lab 文件，通过MFA拿到音素对齐文件，然后跑的测试。
- synthesize_e2e 是直接一个单文本句子，通过模型跑出来的测试结果
- 所以两者差距挺大是合理的？或者是我哪里弄错了吗？想确定一下

**Comment by yt605155624** [comment]
差距挺大是什么意思，相同的文本差距大？

**Comment by hackerxiaobai** [comment]
不好意思，已经解决。感谢回答，忽略这个问题吧
