### ISSUE TITLE
流式语音识别的输入也是wav文件，怎样实现流式识别呢？

### ISSUE THREAD

**Issue by yaleimeng** [PaddlePaddle/PaddleSpeech#2179]
是遇到空白截断，然后发送一个wav文件给server吗？ 还是按固定时间间隔保存声波文件发过去？
能直接对接麦克风进行流式语音识别吗？

**Comment by zh794390558** [comment]
可以多看看代码，issue，discussion。 具体参看：https://github.com/PaddlePaddle/PaddleSpeech/discussions/1965
