### ISSUE TITLE
websocket流式服务的客户端问题

### ISSUE THREAD

**Issue by yaleimeng** [PaddlePaddle/PaddleSpeech#2185]
ASR和TTS都支持了websocket协议的流式服务，但是客户端总不能只在本机运行吧？
其他电脑怎样通过websocket协议跟服务器进行交互？麻烦提供一个非本机的客户端访问脚本。

别告诉我安装全套paddlespeech然后执行那一段示例代码。。一个客户端安装paddlepaddle太离谱。

**Comment by yaleimeng** [comment]
刚从wiki中找到了一些资料。试一试也许能行。
但是作为扩展学习资料，应该在readme.md中 链接到这些扩展资料。便于构建完整的知识体系。
甚至，直接提供一个client.py 作为样例，能更大地降低上手难度。

**Comment by yt605155624** [comment]
We are design our README.md now, maybe this is the `client.py` you want
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/server/tests
Maybe you can also find some funcs in : https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/speech_web

**Comment by yaleimeng** [comment]
that's what I want , thanks a lot~
