### ISSUE TITLE
联合流式语音识别和标点预测速度很慢

### ISSUE THREAD

**Issue by gfhjjk** [PaddlePaddle/PaddleSpeech#2186]
运行联合流式语音识别和标点预测很慢   
![图片](https://user-images.githubusercontent.com/94445730/180955793-d41bba23-a97f-47f1-8fb1-56819a428dbc.png)一个40秒的音频要500多秒

**Comment by zh794390558** [comment]
标点是ERINE模型，而且增量调用，所以会慢。

**Comment by yaleimeng** [comment]
可以在全部识别完成后调用一次标点预测。这样应该会很快。中间过程的预测没什么意义

**Comment by zh794390558** [comment]
可以单独起asr服务和标点服务，用户可以自行控制标点服务调用次数。

**Comment by THUzyt21** [comment]
已经修改为在全部识别完成后调用一次标点预测，减少了中间过程的冗余调用。
