### ISSUE TITLE
启动server时 程序killed

### ISSUE THREAD

**Issue by lroyzz** [PaddlePaddle/PaddleSpeech#2188]
![image](https://user-images.githubusercontent.com/29371605/180968051-b91e2dc0-c887-4ba5-831e-5a65513df2e7.png)

正常安装
centos
paddle.utils.run_check 正常

机器2C2G内存 是内存不足的 原因吗

**Comment by yt605155624** [comment]
大概率是的，因为 tts 的模型都不小，而且有声学模型声码器 2 个模型，可以换个配置较高的机器试下
