### ISSUE TITLE
请问标点符号的训练资料格式

### ISSUE THREAD

**Issue by jeremy110** [PaddlePaddle/PaddleSpeech#2194]
我想使用自己的data fine-tune标点符号。 
example提供的iwslt2012_zh，是来自于TED talks，文本当中的每一句字数不多。
想请问每句字数有限制?
或是一句当中最多几个标点符号?

先行感谢回覆

**Comment by yt605155624** [comment]
字数可少不可多，我们使用的基础模型是 ERNIE 3.0, ERNIE/BERT 类模型，有长度限制，一般是 256/512 个 token 等，可以具体去 PaddleNLP 看一下，超出的文本会被裁剪
一句中的标点符号没有限制，因为标点预测问题本质是一个序列标注问题，对于每一个字符，都会判断其后是无标点还是逗号句号等
如果自己有大量的数据，可以自己从头训练，因为 iwslt2012_zh 数据量很小，训练出来的模型不能用，我们 cli 里面的标点模型是用商业数据训练的

**Comment by jeremy110** [comment]
谢谢你这么快的回覆，我会再试看看
