### ISSUE TITLE
sndfile library not found

### ISSUE THREAD

**Issue by laity-slf** [PaddlePaddle/PaddleSpeech#2198]
版本都对
![WechatIMG0 1](https://user-images.githubusercontent.com/59203496/181461310-989fbf0e-8ca3-4c5a-9cae-b64aa83fa2a0.png)
的
也有libsndfile1
![1](https://user-images.githubusercontent.com/59203496/181461423-27b63f81-d290-42ae-85bb-08945a118502.png)

**Comment by yt605155624** [comment]
建议你遇到问题先自己搜索一下吧，试试
```bash
pip install libsndfile
```

**Comment by laity-slf** [comment]
> 建议你遇到问题先自己搜索一下吧，试试
> 
> ```shell
> pip install libsndfile
> ```

首先感谢你的回复，我肯定是有查过的。问题在于是ubuntu我这么部署是没问题的，可以import，但是换成debain 后其他版本都一致（paddleaudio、librosa），唯独是系统不同的 apt 中的 libsndfile1 版本不一样

**Comment by yt605155624** [comment]
> > 建议你遇到问题先自己搜索一下吧，试试
> > ```shell
> > pip install libsndfile
> > ```
> 
> 首先感谢你的回复，我肯定是有查过的。问题在于是ubuntu我这么部署是没问题的，可以import，但是换成debain 后其他版本都一致（paddleaudio、librosa），唯独是系统不同的 apt 中的 libsndfile1 版本不一样

好的，因为我们这边也没有这么多系统，一般 linux 就是 ubuntu 16.04, 所以你这个问题我们没有环境去复现，这个还是要你多查查看，有什么结论也希望可以同步给社区🤓
不过如果环境部署有问题，建议你可以直接使用 paddle 官方提供的 ubuntu 镜像~

**Comment by lizezheng** [comment]
ubuntu-16.04 apt-get install libsndfile1

**Comment by lizezheng** [comment]
ubuntu 16.04, apt-get install libsndfile1 works it out.
