### ISSUE TITLE
💬【夸夸】留言区

### ISSUE THREAD

**Issue by iftaken** [PaddlePaddle/PaddleSpeech#2199]
PaddleSpeech语音机器人 🤖  已上线，你可以在这里给陌生人留言，留一句【鼓励】他人的话 👻  ，可以是励志金句，也可以是🌈  屁，可以是你的人生座右铭，也可以是你喜欢的诗词歌句，我们筛选后会放入机器人的【夸夸 🤠  】后台，本活动长期有效，希望我们的机器人能够为你带来一些快乐 🥰  ~

参与方式：【留言类型】+ 留言内容，留言类型分为【鼓励】与【建议】，【鼓励】中的句子我们筛选后会放入后台，【建议】中的句子为建议留言，我们根据建议，对机器人内容与形式进行调整。🤓

示例一：【鼓励】留言 😝
>【鼓励】你是我见过最可爱的人！爱你！
>【鼓励】路漫漫其修远兮，吾将上下而求索！希望你克服万难，勇往直前！

示例二：【建议】留言 🧐
> 【建议】建议增加更多的音色

**添加机器人的方式**：

微信扫码，添加PaddleSpeech机器人微信：

<img width="273" alt="98a77df5450cc931b0da6a7880c38097" src="https://user-images.githubusercontent.com/30135920/181512213-b1be165b-4365-4563-b49a-308bdd8a359a.png">

**加入PaddleSpeech夸夸群聊**：

> **入群注意事项**：
> 1. 可以跟机器人互动，也可以跟群里的朋友们一起吹水！但是注意发言，文明和谐友善，不可以发广告，不可以触犯法律底线！请大家发言遵守文明公约！！！👮 
> 2. 谨防诈骗，不要随意添加陌生人 😈  的微信，保护好自己的信息安全！
> 3. 希望大家一起玩得开心😆  
> 4. 你可以@PaddleSpeech之后，跟它说 【夸夸我】【夸夸我，我是男孩子】【夸夸我，我是女孩子】等试试，期待你的加入

微信扫码，回复【语音】，加入【PaddleSpeech交流群】👻  

![71ed871c5c8ff7829ed04144bd4eb516](https://user-images.githubusercontent.com/30135920/181512966-e31155a2-b3d7-46c6-9972-bd8a2f32ea3e.png)

**Comment by dahu1** [comment]
【建议】

1. 建议增加更多可选择的音色
2. 建议聊天内容的风格可以选择， 这些可以作为机器人的配置选项。
