### ISSUE TITLE
tts voc1 中的defualt.yaml 参数设定bug

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2204]
- 问题是我自己的数据集出现了一个batch的数据中的 b['feats'].shape[0] 都小于 self.mel_threshold 这个只，导致后面的 np.stack 异常
- 其实是需要更改 default.yaml 里的 batch_max_steps 或者 n_shift 参数，但是我没有什么建议，这两个参数我直接调小 batch_max_steps，bug就不会有了，能给一些建议吗？关于调整这个参数
- bug代码问题就是 vocoder_batch_fn.py 
 ```python
# 某一个batch的数据都小于 self.mel_threshold，导致 batch 为空
 batch = [
            self._adjust_length(b['wave'], b['feats']) for b in batch
            if b['feats'].shape[0] > self.mel_threshold
        ]

```

**Comment by yt605155624** [comment]
`batch_max_steps` can be reduced, but do keep it be `n x n_shift`, but do not adjust `n_shift`, because it needs to be matched with the acoustic model's `n_shift`, otherwise you have to retrain the acoustic model

**Comment by hackerxiaobai** [comment]
ok ,thx
