### ISSUE TITLE
音频降噪的本repo有计划支持吗？

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2209]
- 如标题

**Comment by zh794390558** [comment]
目前了解的不多，有相关的好方法可以安利给我们。

**Comment by hackerxiaobai** [comment]
noisereduce 这个库效果还可以，可以缓解合成音频电音问题

**Comment by starmoon-1134** [comment]
这个模型效果不错，比SpeechBrain里提供的模型好多了

https://github.com/Rikorose/DeepFilterNet
