### ISSUE TITLE
Set device failed, please check if device '0' is already used and the parameter 'device' in the yaml file

### ISSUE THREAD

**Issue by lsfoo** [PaddlePaddle/PaddleSpeech#2227]
jetson nx 8G 
用gpu运行 ` paddlespeech_server start --config_file conf/ws_conformer_wenetspeech_application.yaml` 报错,

```
[2022-08-04 17:33:41,094] [   ERROR] - Set device failed, please check if device '0' is already used and the parameter 'device' in the yaml file
[2022-08-04 17:33:41,094] [   ERROR] - If all GPU or XPU is used, you can set the server to 'cpu'
```

而用 `paddlespeech asr --lang zh --input zh.wav ` 正常加载gpu

`W0804 17:35:40.169039 22715 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.2, Driver API Version: 10.2, Runtime API Version: 10.2
W0804 17:35:40.176759 22715 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
我认为跑步最重要的就是给我带来了身体健康`

另外 jetson nx 用gpu运行 streaming_tts_server 是正常工作的. 

当然我部署在tesla a10 24G的服务器上,也是正常的.

**Comment by lsfoo** [comment]
不好意思，我配置错了。抱歉

**Comment by lzy83925** [comment]
是设置成"gpu:0"吗？我好像怎么设置都不行啊。都报这个错

**Comment by wu-xiaohua** [comment]
我设置成device: 0，或者设置成device: “gpu:0”都不行

**Comment by qingjiaozyn** [comment]
需要怎么设置，我怎么设置都会报这种错误

**Comment by Ch180907** [comment]
> 是设置成"gpu:0"吗？我好像怎么设置都不行啊。都报这个错

请问问题解决了吗？

**Comment by lzy83925** [comment]
> > 是设置成"gpu:0"吗？我好像怎么设置都不行啊。都报这个错
> 
> 请问问题解决了吗？

完全没有解决，也没有人提过怎么解决，我退坑了，这个百度的模型坑太多

**Comment by Ch180907** [comment]
> > > 是设置成"gpu:0"吗？我好像怎么设置都不行啊。都报这个错
> > 
> > 
> > 请问问题解决了吗？
> 
> 完全没有解决，也没有人提过怎么解决，我退坑了，这个百度的模型坑太多

好的好的

**Comment by 488283943** [comment]
解决了吗？我也是设置device:0 device gpu:0都不行
root@autodl-container-085311853c-b00a9bac:~/PaddleSpeech# paddlespeech_server start --config_file ./demos/streaming_asr_server/conf/application.yaml
WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
[2024-05-09 10:30:04,756] [    INFO] - start to init the engine
[2024-05-09 10:30:04,756] [    INFO] - asr : online engine.
[2024-05-09 10:30:04,914] [   ERROR] - Set device failed, please check if device '0' is already used and the parameter 'device' in the yaml file
[2024-05-09 10:30:04,914] [   ERROR] - If all GPU or XPU is used, you can set the server to 'cpu'

**Comment by qingjiaozyn** [comment]
> 解决了吗？我也是设置device:0 device gpu:0都不行 root@autodl-container-085311853c-b00a9bac:~/PaddleSpeech# paddlespeech_server start --config_file ./demos/streaming_asr_server/conf/application.yaml WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads. PLEASE USE OMP_NUM_THREADS WISELY. [2024-05-09 10:30:04,756] [ INFO] - start to init the engine [2024-05-09 10:30:04,756] [ INFO] - asr : online engine. [2024-05-09 10:30:04,914] [ ERROR] - Set device failed, please check if device '0' is already used and the parameter 'device' in the yaml file [2024-05-09 10:30:04,914] [ ERROR] - If all GPU or XPU is used, you can set the server to 'cpu'

解决了，./demos/streaming_asr_server/conf/application.yaml按照下面的配置解决了
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/140772087/94eea430-53a3-4c34-8d57-538495418940)

**Comment by 488283943** [comment]
我是在autodl部署的，我按照你的改了yaml配置，为0为1都试了还是不行
![issue](https://github.com/PaddlePaddle/PaddleSpeech/assets/73679865/cdd00a23-6d15-4eb9-8ad2-4a262fc17743)

asr_online:
    model_type: 'conformer_online_wenetspeech'
    am_model: # the pdmodel file of am static model [optional]
    am_params:  # the pdiparams file of am static model [optional]
    lang: 'zh'
    sample_rate: 16000
    cfg_path: 
    decode_method: 
    num_decoding_left_chunks: -1
    force_yes: True
    device: 'gpu:1' # cpu or gpu:id
    decode_method: "attention_rescoring"
    continuous_decoding: True # enable continue decoding when endpoint detected
    am_predictor_conf:
        device: 'gpu' # set 'gpu:id' or 'cpu'
        switch_ir_optim: True
        glog_info: False  # True -> print glog
        summary: True  # False -> do not show predictor config
    chunk_buffer_conf:
        window_n: 7     # frame
        shift_n: 4      # frame
        window_ms: 25   # ms
        shift_ms: 10    # ms
        sample_rate: 16000
        sample_width: 2

**Comment by 488283943** [comment]
> > 解决了吗？我也是设置device:0 device gpu:0都不行 root@autodl-container-085311853c-b00a9bac:~/PaddleSpeech# paddlespeech_server start --config_file ./demos/streaming_asr_server/conf/application.yaml WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads. PLEASE USE OMP_NUM_THREADS WISELY. [2024-05-09 10:30:04,756] [ INFO] - start to init the engine [2024-05-09 10:30:04,756] [ INFO] - asr : online engine. [2024-05-09 10:30:04,914] [ ERROR] - Set device failed, please check if device '0' is already used and the parameter 'device' in the yaml file [2024-05-09 10:30:04,914] [ ERROR] - If all GPU or XPU is used, you can set the server to 'cpu'
> 
> 解决了，./demos/streaming_asr_server/conf/application.yaml按照下面的配置解决了 ![image](https://private-user-images.githubusercontent.com/140772087/329108556-94eea430-53a3-4c34-8d57-538495418940.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjMwMjIsIm5iZiI6MTcxNTIyMjcyMiwicGF0aCI6Ii8xNDA3NzIwODcvMzI5MTA4NTU2LTk0ZWVhNDMwLTUzYTMtNGMzNC04ZDU3LTUzODQ5NTQxODk0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMjQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjViMWJiNDI2MTc3Mzk4ZGJlY2FmMTgyMzQ2MThlNmY5OTQ5NmU5N2Q0ZTE5YTQxMDI5ZmEzMmUwNTU5NWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Tossk4gqi-Fg6ywDkppJ07DwIYe4iCJzEEI0RcBANE8)

我是在autodl部署的，我按照你的改了yaml配置，为0为1都试了还是不行
![issue](https://github.com/PaddlePaddle/PaddleSpeech/assets/73679865/cdd00a23-6d15-4eb9-8ad2-4a262fc17743)

asr_online:
    model_type: 'conformer_online_wenetspeech'
    am_model: # the pdmodel file of am static model [optional]
    am_params:  # the pdiparams file of am static model [optional]
    lang: 'zh'
    sample_rate: 16000
    cfg_path: 
    decode_method: 
    num_decoding_left_chunks: -1
    force_yes: True
    device: 'gpu:1' # cpu or gpu:id
    decode_method: "attention_rescoring"
    continuous_decoding: True # enable continue decoding when endpoint detected

    am_predictor_conf:
        device: 'gpu' # set 'gpu:id' or 'cpu'
        switch_ir_optim: True
        glog_info: False  # True -> print glog
        summary: True  # False -> do not show predictor config

    chunk_buffer_conf:
        window_n: 7     # frame
        shift_n: 4      # frame
        window_ms: 25   # ms
        shift_ms: 10    # ms
        sample_rate: 16000
        sample_width: 2
