### ISSUE TITLE
服务多并发出现多个并发的结果相互串了的情况

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2233]
算法：fastspeech2,  pwgan
服务部署：websocket
并发：2个并发
具体情况：并发1的文本，出来的语音确是并发2的结果；并发2的文本，出来的语音确是并发1的结果；即，两个结果搞串了。
情况追踪：
        通过追踪发现，模型的输入是正常，但是输出不正常。
      
![image](https://user-images.githubusercontent.com/27938135/183391346-7f89ca07-c9a4-42c3-8829-01ec7f21a4e2.png)
`phones_handle`的输入正常，`am_output_data`的结果却不对。请问这情况是什么原因啊，这么解决这个问题。

**Comment by yt605155624** [comment]
predictor 不是线程安全的，同一个只能在一个线程或进程使用。不同线程使用不同的 predictor 即可

**Comment by lym0302** [comment]
这个问题还在定位解决中
