### ISSUE TITLE
关于zh_en_tts/tts3任务的问题

### ISSUE THREAD

**Issue by 70557dzqc** [PaddlePaddle/PaddleSpeech#2241]
在zh_en_tts/tts3任务中，输入文字如果是15.58万元，它会念成一千五百五十八万元，自动去掉了.点号，有什么好的解决方法吗？谢谢。

**Comment by yt605155624** [comment]
应该是中英文文本前端里面的 bug，如果是纯中文的输入可以用中文模型和前端，或者手动对 `15.58` 手动文本正则为 `十五点五八`，这个问题会排期修复，也欢迎开发者提交 pr 修复
