### ISSUE TITLE
Multi Band MelGAN为什么没有英文的预训练模型？

### ISSUE THREAD

**Issue by lawo123** [PaddlePaddle/PaddleSpeech#2242]
Multi Band MelGAN为什么没有英文的预训练模型？

**Comment by yt605155624** [comment]
Paddle TTS 主打中文场景，csmsc 上的预训练模型最全，可以参考 csmsc 上的 Multi Band MelGAN 的配置和 ljpspeech 上的 PWGAN 的配置，自己训练 ljspeech 上的 MB MelGAN
