### ISSUE TITLE
KeyError: 'generator_params'

### ISSUE THREAD

**Issue by SchweitzerGAO** [PaddlePaddle/PaddleSpeech#2246]
我使用csmsc中的cnndecoder.yaml 作为配置文件训练了一个模型（也就是 #2166 中的方法），在synthesize的过程中报如题错误，请问如何解决，以及如何替换训练好按这个方法训练的模型的基准音呢，谢谢！

**Comment by yt605155624** [comment]
`generator_params` 是声码器是 ckpt 文件的 key，声学模型的 key 应该是 `main_params`, 你再检查一下你的代码吧，可以用 `paddle.load()` 加载 ckpt 文件， 查看里面有哪些 key

**Comment by SchweitzerGAO** [comment]
好的谢谢
