### ISSUE TITLE
请问语音克隆生成的声音太平淡了，没有抑扬顿挫的感觉需要怎么调整？

### ISSUE THREAD

**Issue by sixyang** [PaddlePaddle/PaddleSpeech#2247]
如题，这里采用的是 vc1 里面的方案，已经把电流音等噪音去的很好了，并且也用的高音质的 ref_audio(女声)，但是最终实现的声音效果有点平淡，就是感觉是一个调调，不像日常交流那样子。并且停顿也不自然，需要手动控制标点符号(加一些逗号等)。请问有什么优化方式吗？谢谢！

**Comment by lym0302** [comment]
vc1 的方案主要是更换音色信息。合成音频的抑扬顿挫依赖于训练集的音频。由于 aishell3数据集本身就比较平平淡淡，所以合成的音频也就比较平淡

**Comment by sixyang** [comment]
那如果想要抑扬顿挫的效果，需要对哪部分进行训练？或者是说大佬们有什么想法或者方案吗？谢谢！

**Comment by yt605155624** [comment]
换别的情感丰富的多说话人数据集试试（但我也不知道开源的中文多说话人还有什么），有个情感数据集 ESD 可以尝试（我没试过，只是知道有）

**Comment by sixyang** [comment]
> 换别的情感丰富的多说话人数据集试试（但我也不知道开源的中文多说话人还有什么），有个情感数据集 ESD 可以尝试（我没试过，只是知道有）

好的，谢谢解答

**Comment by oyb1125** [comment]
> 如题，这里采用的是 vc1 里面的方案，已经把电流音等噪音去的很好了，并且也用的高音质的 ref_audio(女声)，但是最终实现的声音效果有点平淡，就是感觉是一个调调，不像日常交流那样子。并且停顿也不自然，需要手动控制标点符号(加一些逗号等)。请问有什么优化方式吗？谢谢！

@sixyang 想请问电流音怎么去除
