### ISSUE TITLE
speedyspeech训练LJSpeech

### ISSUE THREAD

**Issue by dzcmingdi** [PaddlePaddle/PaddleSpeech#2252]
请问我怎样才能让speedyspeech训练LJSpeech数据集呢？

**Comment by yt605155624** [comment]
参照 csmsc 上的 speedyspeech、fastspeech2 和 ljspeech 上的 fastspeech2 自己构造一个 example

**Comment by dzcmingdi** [comment]
> 

好的，感谢回复。
