### ISSUE TITLE
aishell asr0示例无法运行

### ISSUE THREAD

**Issue by iftaken** [PaddlePaddle/PaddleSpeech#2266]
反馈：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell/asr0#stage-6-single-audio-file-inference

![image](https://user-images.githubusercontent.com/30135920/185374879-6a53c518-7502-4cb1-9e0a-4718832f3154.png)

问题：
test_wav.sh 是要接收四个参数 脚本运行的时候会检测传了几个参 这个里面只写了三个参数，直接运行这个截图里面的代码 好像没法运行成功

**Comment by zh794390558** [comment]
CUDA_VISIBLE_DEVICES= ./local/test_wav.sh conf/deepspeech2.yaml conf/tuning/decode.yaml exp/deepspeech2/checkpoints/avg_1 data/demo_01_03.wav

merged
