### ISSUE TITLE
中英文混合 TTS 现在还是在内侧阶段？

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2276]
我看到你们已经更新了中英文混合TTS，但是好像还是不能用啊？
paddlespeech tts --am fastspeech2_mix --voc pwgan_ljspeech --lang mix  --input "我们的声学模型使用了 Fast Speech Two, 声码器使用了 Parallel Wave GAN and Hifi GAN." --spk_id 1  --output mix_spk1.wav

**Comment by yt605155624** [comment]
今日会发布 paddlespeech 1.1.0, 发布后可用，现在可以安装 develop 版本的 paddlespeech
并且此命令已经更新，请参考 https://github.com/PaddlePaddle/PaddleSpeech/pull/2249 选择指定的 voc 和 spk_id

**Comment by yt605155624** [comment]
欢迎到 https://pypi.org/ 安装最新的 paddlespeech 1.1.x 体验中英文混合 TTS 功能

**Comment by AI-Mart** [comment]
您好，流式语音服务，支持中英文混合的合成吗？看源码 lang好像只能选英文和中文，没有mix选项？
