### ISSUE TITLE
paddlespeech如何训练自己的数据,选择使用不同框架的预训练模型测试效果

### ISSUE THREAD

**Issue by J-ZZ** [PaddlePaddle/PaddleSpeech#2278]
paddlespeech/exampeles/下有不同数据集所对应的不同处理方式以及不同的任务
1.请问如果想实现语音识别应该选择哪个数据集下的预训练模型,如果想更换预训练模型应该如何操作
2.是否有考虑在examples下设立一个专门为了训练自己数据的一个执行流程

**Comment by prcvoldermort** [comment]
这个需求很急迫
