### ISSUE TITLE
我自己训练的TTS模型，但是语料里是没有英文的，现在在inference阶段想中英文混合的生成，是不是不行啊？

### ISSUE THREAD

**Issue by hackerxiaobai** [PaddlePaddle/PaddleSpeech#2280]
如题

**Comment by yt605155624** [comment]
是的，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3 重新训练

**Comment by hackerxiaobai** [comment]
> 是的，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3 重新训练

不只是简单的按照zh_en_tts/tts3 介绍重新跑一遍代码就好了吧？是不是我的数据里也需要加入一些英文的语料啊？

**Comment by yt605155624** [comment]
zh_en_tts/tts3 有英文语料了，是 4 个数据集，如果你需要用到自己的数据集，把自己的数据作为一个新的数据集加上去就行，你自己的数据是单语的也没关系

**Comment by hackerxiaobai** [comment]
明白，非常感谢你的回复，回复贼快。👍
