### ISSUE TITLE
请问后面会支持多 speaker 的 vits 模型吗？

### ISSUE THREAD

**Issue by sixyang** [PaddlePaddle/PaddleSpeech#2282]
如题

**Comment by yt605155624** [comment]
开发者贡献了代码你可以先看下，暂时还没有时间 review，你可以先用起来，有问题直接反馈 https://github.com/PaddlePaddle/PaddleSpeech/pull/2268

**Comment by sixyang** [comment]
> 开发者贡献了代码你可以先看下，暂时还没有时间 review，你可以先用起来，有问题直接反馈 #2268

刚好看到，非常感谢各位，辛苦
