### ISSUE TITLE
声纹识别安全性问题，能别录音欺骗

### ISSUE THREAD

**Issue by zhaoyiyong** [PaddlePaddle/PaddleSpeech#2307]
1、我生成了三个录音：tellong.wav作为原始录制的模版声音；teloriginal.wav是测试由真人说话生成的录音；recording.wav是播放真人录音形成的录音（模拟使用录音冒充他人声音）；
2、我使用命令“paddlespeech vector --task score --input 'recording.wav tellong.wav'”，计算冒充人和模版声音的相似度，得到：0.5637418627738953；
3、我使用命令“paddlespeech vector --task score --input 'teloriginal.wav tellong.wav'“，计算真人说话和模版声音的相似度，得到：
0.5126219987869263
4、使用录音的相似度反而更高。这样对于系统就无法识别伪装者了。
请教这个过程有什么问题吗？

**Comment by SmileGoat** [comment]
这个过程没有问题，单条语音测试0.05的差异是属于正常范围。具体整体性能，可以建一个更大的测试集来测试。转录伪装这是一个问题，语音防攻击就是解决这类问题的，目前这套声纹系统没有特意处理这类转录问题。

**Comment by zhaoyiyong** [comment]
这种差异对于安全性是非常重要的，会造成转录伪装成功骗过系统。
“这套声纹系统没有特意处理这类转录问题”是指这种情况是正常的吗？
那如何能够加强对这种语音攻击的防范呢？在本系统中需要做哪些修改能够满足要求呢？

**Comment by SmileGoat** [comment]
在高安全新能的系统中，最好在声纹识别系统后，级联一个语音防攻击系统。

**Comment by zhaoyiyong** [comment]
语音防攻击系统，这个不太明白了。
