### ISSUE TITLE
docker 安装 paddlespeech时，测试单卡没问题，多卡测试时报  Bus error (core dumped)

### ISSUE THREAD

**Issue by wangdabee** [PaddlePaddle/PaddleSpeech#2310]
按照提供的dockerfile安装后， paddle.utils.run_check() 测试显卡时，出现以下报错：

`Python 3.7.13 (default, Aug 25 2022, 17:42:24) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0826 13:33:08.306574  4132 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0826 13:33:08.310814  4132 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
W0826 13:33:10.297623  4132 parallel_executor.cc:642] Cannot enable P2P access from 0 to 1
W0826 13:33:10.297649  4132 parallel_executor.cc:642] Cannot enable P2P access from 1 to 0
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1661491991 (unix time) try "date -d @1661491991" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7f59a9dd8000) received by PID 4132 (TID 0x7f5b04cd0700) from PID 18446744072264450048 ***]

Bus error (core dumped)`

并在当前目录下生成 core.* 文件
请问该如何解决？谢谢。

**Comment by yt605155624** [comment]
请问具体用的是哪个 docker ，是 paddlecloud 的还是 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/docker 里面的

**Comment by wangdabee** [comment]
后者 ubuntu16-gpu

**Comment by yt605155624** [comment]
ubuntu16-gpu 是我们开发者 @buchongyu2 提供的，建议你使用 paddleclould 官方提供的 docker https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install.md 里面可以找到

**Comment by yt605155624** [comment]
麻烦 @buchongyu2 有空可以关注一下这个 issue

**Comment by wangdabee** [comment]
我换了paddleclould提供的docker镜像，在 linux x86_64架构上依旧报如上错误。
paddleclould上的都是amd64架构，是跟这个有关系吗

**Comment by yt605155624** [comment]
可以到 https://github.com/PaddlePaddle/PaddleCloud 反馈你的问题，或许需要安装和你的处理器架构一致的 paddle 版本，可以按照 paddle 官方文档查看计算机环境 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html#ruhechakannindehuanjing

也可以 baidu / google 搜索相关报错, 尝试解决
```bash
libibverbs: Warning: couldn't open config directory '/etc/libibverbs.d'.
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs1
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
```

**Comment by wangdabee** [comment]
找到问题了 是因为/dev/shm 默认的是64M，内存太小  
解决方法为 在nvidia-docker run 的时候指定 --shm-size 4G 即可。
谢谢各位。
