### ISSUE TITLE
请问原版vits的数据集&filelist如何转到paddlespeech训练？

### ISSUE THREAD

**Issue by RyougiShiki-214** [PaddlePaddle/PaddleSpeech#2320]
原版vits的train_filelist.txt.cleaned似乎在这里无法使用，paddle文档提到要用MFA提取音素，但非中英文语种数据集很难做MFA处理，是否可以直接用适用于原版vits的train_filelist.txt.cleaned搭配数据集训练？

即：
音频文件|speakerID|国际音标

`
DUMMY2/p364/p364_240.wav|88|ɪt hɐd hˈæpənd tə hˌɪm.

DUMMY2/p280/p280_148.wav|52|ɪt ɪz ˈoʊpən sˈiːzən ɑːnðɪ ˈoʊld fˈɜːm.

DUMMY2/p231/p231_320.wav|50|haʊˈɛvɚ, hiː ɪz ɐ kˈoʊtʃ, ænd hiː ɹɪmˈeɪnz ɐ kˈoʊtʃ æt hˈɑːɹt.

DUMMY2/p282/p282_129.wav|83|ɪt ɪz nˌɑːɾə jˈuːtˈɜːn.

DUMMY2/p254/p254_015.wav|41|ðə ɡɹˈiːks jˈuːzd tʊ ɪmˈædʒɪn ðˌɐɾɪt wʌzɐ sˈaɪn fɹʌmðə ɡˈɑːdz tə foːɹtˈɛl wˈɔːɹ ɔːɹ hˈɛvi ɹˈeɪn.

DUMMY2/p228/p228_285.wav|57|ðə sˈɔŋz ɑːɹ dʒˈʌst sˌoʊ ɡˈʊd.

DUMMY2/p334/p334_307.wav|38|ɪf ðeɪ dˈoʊnt, ðeɪ kæn ɛkspˈɛkt ðɛɹ fˈʌndɪŋ təbi kˈʌt.

DUMMY2/p287/p287_081.wav|77|aɪv nˈɛvɚ sˈiːn ˈɛnɪθˌɪŋ lˈaɪk ɪt.

DUMMY2/p247/p247_083.wav|14|ɪt ɪz ɐ dʒˈɑːb kɹiːˈeɪʃən skˈiːm.

DUMMY2/p264/p264_051.wav|65|wiː wɜː lˈiːdɪŋ baɪ tˈuː ɡˈoʊlz.

DUMMY2/p335/p335_058.wav|49|lˈɛts sˈiː ðæt ˈɪnkɹiːs ˌoʊvɚ ðə jˈɪɹz.

DUMMY2/p236/p236_225.wav|75|ðɛɹ ɪz nˈoʊ kwˈɪk fˈɪks.

DUMMY2/p374/p374_353.wav|11|ænd ðæt bɹˈɪŋz ˌʌs tə ðə pˈɔɪnt.`

是否可以通过这样的filelists&数据集训练？

**Comment by yt605155624** [comment]
没有研究过 VITS 原版，VITS 本身不需要 duration 信息，用 MFA 只是为了和其他模型的处理保持一致，训练时只用到音素，所以可以直接输入音素，国际音标是音素的一种，可以把上述数据集处理成我们的格式后（metadata.jsonl）训练

**Comment by RyougiShiki-214** [comment]
> 没有研究过 VITS 原版，VITS 本身不需要 duration 信息，用 MFA 只是为了和其他模型的处理保持一致，训练时只用到音素，所以可以直接输入音素，国际音标是音素的一种，可以把上述数据集处理成我们的格式后（metadata.jsonl）训练

感谢回复，请问哪里可以找到paddlespeech-vits能读取的metadata.json格式的规范，或者样例metadata.json文件，以便进行数据集处理？谢谢

**Comment by yt605155624** [comment]
你按照 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/csmsc/vits 跑一遍数据预处理就清楚了，具体 vits 需要的 key 在 https://github.com/PaddlePaddle/PaddleSpeech/blob/2c4c254f718c2b7a4d68fae98a0e5fc3861313b4/paddlespeech/t2s/datasets/am_batch_fn.py#L446
