### ISSUE TITLE
streaming asr GPU利用率不到4%

### ISSUE THREAD

**Issue by JaheimLee** [PaddlePaddle/PaddleSpeech#2322]
本地用流式识别方式跑个长时间的音频文件，GPU利用率一直很低，怎么可以提升利用率啊？

**Comment by JaheimLee** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/ed16f96a9cb027d250bdcf1d3d33ff7151e2d301/paddlespeech/server/utils/audio_handler.py#L113
是不是这里的影响啊。我本地的文件x_len有200多万，chunk会有2000个，应该效率低下的原因吧。这个85是怎么定的？改它的话conf文件里需不需要也改动些东西？

**Comment by zh794390558** [comment]
asr是GPU和CPU同时跑做推理，会有切换。暂时没有太好的办法，如果有想法可以多交流。
