### ISSUE TITLE
下载的模型放到哪个路径 Where should I put models in path?

### ISSUE THREAD

**Issue by idreamerhx** [PaddlePaddle/PaddleSpeech#2326]
## General Question

服务器不能下载，手工下载了
https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz

运行命令仍然会自动下载

已经查了文档，尝试了下面类似的命令：
paddlespeech asr --model conformer_wenetspeech --ckpt_path /opt/paddlespeech-models/asr1_conformer_wenetspeech_ckpt_0.1.1.model --lang zh --input zh.wav

自己下载的模型应该放到哪个路径？或者命令行可以指定路径吗？

谢谢，简单问题麻烦加到文档里。

**Comment by idreamerhx** [comment]
同时尝试了模型解压到~/.paddlespeech/models/conformer_wenetspeech-zh-16k/1.0
也没解决

**Comment by yt605155624** [comment]
可能需要把压缩包和解压缩之后的文件同时放到 `${HOME}/.paddlespeech/models/conformer_wenetspeech-zh-16k/1.0/`

```text
${HOME}/.paddlespeech/models/conformer_wenetspeech-zh-16k/1.0/
├── asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar
└── asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz
```
现在的程序是检查指定路径是否存在指定 md5 值的压缩包，再决定是否要下载

**Comment by idreamerhx** [comment]
确实是这样，开始要把压缩包放在哪个路径。

ls ~/.paddlespeech/models/conformer_wenetspeech-zh-16k/1.0/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar/
conf/       data/       exp/        model.yaml



谢谢

**Comment by idreamerhx** [comment]
谢谢

**Comment by idreamerhx** [comment]
路径是在这里面定义的
https://github.com/PaddlePaddle/PaddleSpeech/blob/d1c70a780985e226c00a1d4c6e22626c4f668444/paddlespeech/resource/pretrained_models.py

**Comment by idreamerhx** [comment]
> /opt/pyvenv-paddlespeech/lib/python3.8/site-packages/paddlespeech/cli/utils.py(135)download_and_decompress()
-> if os.path.isfile(filepath) and download._md5check(filepath,
(Pdb) p filepath
'/root/.paddlespeech/models/G2PWModel_1.1.zip'

**Comment by Noahs007** [comment]
Windows 下可以修改模型目录吗，一下子 C 盘就满了 😂

**Comment by lijianxin520** [comment]
windows下应该设置放到哪个路径呀？能否自定义设置存放路径？

**Comment by Samge0** [comment]
关于缓存路径的个人笔记（只使用speech的话，配置PPSPEECH_HOME环境变量就好，配置完毕后，需要重启ide/vscode才能读取最新的环境变量）：

20240125新增paddle的缓存路径：
https://blog.csdn.net/wang7301/article/details/128921153
https://paddlenlp.readthedocs.io/zh/latest/FAQ.html#q1-2-paddlenlp
https://github.com/PaddlePaddle/PaddleSpeech/issues/2712

HUB_HOME=F:\.cache\paddle\.paddlehub
PPNLP_HOME=F:\.cache\paddle\.paddlehub
PPSPEECH_HOME=F:\.cache\paddle\.paddlespeech
PPAUDIO_HOME=F:\.cache\paddle\.paddleaudio
PPOCR_HOME=F:\.cache\paddle\.paddleocr
PPDETECTION_HOME=F:\.cache\paddle\.paddledetection
PPGAN_HOME=F:\.cache\paddle\.paddlegan
PPSEG_HOME=F:\.cache\paddle\.paddleseg
PPCLAS_HOME=F:\.cache\paddle\.paddleclas
PPREC_HOME=F:\.cache\paddle\.paddlerec

使用powershell命令添加环境变量：
[Environment]::SetEnvironmentVariable("HUB_HOME", "F:\.cache\paddle\.paddlehub", "user")
[Environment]::SetEnvironmentVariable("PPNLP_HOME", "F:\.cache\paddle\.paddlenlp", "user")
[Environment]::SetEnvironmentVariable("PPSPEECH_HOME", "F:\.cache\paddle\.paddlespeech", "user")
[Environment]::SetEnvironmentVariable("PPAUDIO_HOME", "F:\.cache\paddle\.paddleaudio", "user")
[Environment]::SetEnvironmentVariable("PPOCR_HOME", "F:\.cache\paddle\.paddleocr", "user")
[Environment]::SetEnvironmentVariable("PPDETECTION_HOME", "F:\.cache\paddle\.paddledetection", "user")
[Environment]::SetEnvironmentVariable("PPGAN_HOME", "F:\.cache\paddle\.paddlegan", "user")
[Environment]::SetEnvironmentVariable("PPSEG_HOME", "F:\.cache\paddle\.paddleseg", "user")
[Environment]::SetEnvironmentVariable("PPCLAS_HOME", "F:\.cache\paddle\.paddleclas", "user")
[Environment]::SetEnvironmentVariable("PPREC_HOME", "F:\.cache\paddle\.paddlerec", "user")


修改环境变量后，需要重启ide/vscode。
vscode有时候存在假重启，导致环境变量不生效。这时候需要进入任务管理器》性能监视器》搜索vscode，将关联的程序够kill掉后才算真正的重启，这时候环境变量才会生效。不然，也可以选择重启电脑，娃哈哈。
