### ISSUE TITLE
[TTS][Server] 支持中英文混合语音合成

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#2330]
1. engine_warmup.py 添加了 tts_engine.lang == 'mix'的分支，避免paddlespeech_server 启动失败。
2. application.yaml中tts_python中am和lang改为 #2249 需要的模型参数
3. client 端调用时传入 spk_id （推荐 174）

感兴趣的开发者可以加一下 1 提个 pr

**Comment by sixyang** [comment]
请问多数据集训练出来的模型效果会更好一些吗？(fastspeech2+pwgan)，我尝试了一下，发现英文部分切换很生硬。

**Comment by yt605155624** [comment]
我们目前测试 4 个数据集训练出来的比 ljspeech + csmsc + 1000 条单人中英文的效果好(这个旧版本 https://github.com/PaddlePaddle/PaddleSpeech/pull/2203 现在已不可用)


当然如果有单人中英文双语的效果是最好的, 这个是开发者自己用单人中英文双语训练的效果（下载后后缀改成 .wav）

https://user-images.githubusercontent.com/24568452/187644138-aa3b5369-b292-4e4b-bcd2-8de3be2b7a3f.mp4

```text
大家好，我是parrot虚拟老师，我们来读一首诗，我与春风皆过客， I and the spring breeze are passing by,你携秋水揽星河， you take the autumn water to take the galaxy
```

**Comment by wutl92** [comment]
> 我们目前测试 4 个数据集训练出来的比 ljspeech + csmsc + 1000 条单人中英文的效果好(这个旧版本 #2203 现在已不可用)
> 
> 当然如果有单人中英文双语的效果是最好的, 这个是开发者自己用单人中英文双语训练的效果（下载后后缀改成 .wav）
> 
>  _.mp4 
> ```
> 大家好，我是parrot虚拟老师，我们来读一首诗，我与春风皆过客， I and the spring breeze are passing by,你携秋水揽星河， you take the autumn water to take the galaxy
> ```

你好我想请教下streaming服务的 可以使用了吗？升级了1.1.3paddlespeech版本了。用命令模式可以生成中英的语音。现在使用服务模式，API接口调用配置了 说不支持
![image](https://user-images.githubusercontent.com/19256826/188552583-507e3adb-dc6c-4034-ad2a-4ceaf5e22584.png)
![image](https://user-images.githubusercontent.com/19256826/188552641-853ab492-6754-49d6-9d0f-ffdea4b49d72.png)

**Comment by yt605155624** [comment]
@wutl92 非流式 TTS 可以自己参照上面修改后支持中英文混合合成，流式 TTS 需要自己训练中英文混合流式模型

**Comment by unparalleled-ysj** [comment]
@yt605155624 请问下有流式语音合成原理的相关文档吗 [PP-TTS：流式语音合成原理及服务部署](https://aistudio.baidu.com/aistudio/projectdetail/3885352) 这个打不开了

**Comment by yt605155624** [comment]
> PP-TTS：流式语音合成原理及服务部署

我这边能打开，你可能需要先加入 “飞桨PaddleSpeech语音技术课程” 才能打开

**Comment by unparalleled-ysj** [comment]
> > PP-TTS：流式语音合成原理及服务部署
> 
> 我这边能打开，你可能需要先加入 “飞桨PaddleSpeech语音技术课程” 才能打开

可以了，感谢

**Comment by lucasjinreal** [comment]
着音频打不开了，目前github伤的mix是最新的吗？

**Comment by AI-Mart** [comment]
> @wutl92 非流式 TTS 可以自己参照上面修改后支持中英文混合合成，流式 TTS 需要自己训练中英文混合流式模型

目前流式的官方支持了吗？
