### ISSUE TITLE
Punctuation Restoration Pretrained Model

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSpeech#2338]
I have executed your "Punctuation Restoration" part It was executed successfully. But I can't able to find out the exact path where the pre-trained model "ernie-1.0" was saved in the local machine.  I have searched the model in this location "${HOME}/.paddlenlp/models/ernie-1.0" but didn't find any.  However, I have checked in another location also "/home/kiit/.paddlespeech/models/ernie_linear_p7_wudao-punc-zh/ernie_linear_p7_wudao-punc-zh.tar/ckpt/model_state.pdparams".   So .pdparms is a model or not?

**Comment by yt605155624** [comment]
As stated in the email

yes this is Punctuation Restoration model，which use ernie-1.0 as backbone and add some classification layers

@THUzyt21 Please follow this issue

**Comment by ghost** [comment]
If i want to execute the pretrained punctuation restoration model solely then how to proceed?

**Comment by zh794390558** [comment]
We put pretrained model  in here https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md#punctuation-restoration-models. The recipe is example/iwslt2022
