### ISSUE TITLE
Pretrained Punctuation Restoration model

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSpeech#2339]
import paddle
from paddlespeech.cli.text import TextExecutor
text_executor = TextExecutor()
result = text_executor(
    text='今天的天气真不错啊你下午有空吗我想约你一起去吃饭',
    task='punc',
    lang='zh',
    config=None,
    ckpt_path=None,
    punc_vocab=None,
    device=paddle.get_device())
print('Text Result: \n{}'.format(result))

I have executed the above code without mentioning the path of pretrained model. But still it is executed how?

**Comment by zh794390558** [comment]
It has a default model, and will download pre-trained model.

**Comment by THUzyt21** [comment]
It will download the model to {$HOME}/.paddlenlp/models/ernie-1.0 by default, and then automatically call the model parameters at this location for punctuation recovery.
