### ISSUE TITLE
关于ppASR 语音识别开源项目

### ISSUE THREAD

**Issue by new786786** [PaddlePaddle/PaddleSpeech#2340]
中文训练的可以正常运行，但是英文其他语言不能正常运行

原因 中文连续写的语言种类   

比如 数据集  {"audio_filepath": "C:\\xunlei\\data_thchs30\\data\\A11_1.wav", "duration": 8.84, "text": "我爱中国"}

但是 英文和其他语言 {"audio_filepath": "C:\\xunlei\\data_thchs30\\data\\A11_1.wav", "duration": 8.84, "text": "i love china"}

text 字段有空格 训练的时候出错

出错，错误信息: ''

[2022-08-31 23:52:40.751534 ERROR  ] reader:__getitem__:49 - 数据: ['E:\\ai_ai\\PPASR-master\\dataset\\voice\\1.wav', 'bu dorini hëlila qaynatqan caqqan bol issiqida iciwalghin'] 出错，错误信息: '<unk>'

 line 43 in __getitem__

**Comment by zh794390558** [comment]
英文的处理参看 example/librispeech的脚本。其它语音有特殊处理，需要针对代码自行修改。

**Comment by yt605155624** [comment]
https://github.com/yeyupiaoling/PPASR 是飞桨 PPDE 夜雨飘零开发，不是 PaddleSpeech 官方维护的，可以到项目 repo 的 issue 区提问
