### ISSUE TITLE
train models with gpu memory error

### ISSUE THREAD

**Issue by Logan-SUN** [PaddlePaddle/PaddleSpeech#2341]
## General Question
I try to train a s2t model by paddlespeech on our owns machine with 7 gpus, but always report error about having no aviliable GPU memory, I have set batch_size ==8 and wav-id is sorted by name,  our dataset contains 300+  million audios totally.
Can anyone help me solve this gpu memory issue please? THX

**Comment by Zth9730** [comment]
What is the approximate duration of each audio in your dataset?  If the input audios are very long, more GPU memory  is required.

**Comment by Logan-SUN** [comment]
I have checked that the maximum  duration of our audio is less then 10 seconds, thanks by the way. The error I have captured as followed:
![image](https://user-images.githubusercontent.com/29516612/188097615-c1c8c941-9fce-4b82-8757-ee9722c8a628.png)

**Comment by Zth9730** [comment]
Are you using the same model structure and configuration as our repository provides? Whether to add or delete modules or change model size?

**Comment by Logan-SUN** [comment]
I used the same model structure and configuration as your pretrained model named  asr1_conformer_wenetspeech_ckpt_0.1.1.model which is published on websit.
![image](https://user-images.githubusercontent.com/29516612/188389319-f53212d7-4a52-4fb0-87f7-03f7f2122157.png)

**Comment by zh794390558** [comment]
Your GPU mem is not enough, please reduce batchsize to fit you GPU device.
