### ISSUE TITLE
[TTS]PaddleSpeech Server RESTful API接口报错

### ISSUE THREAD

**Issue by byteszard** [PaddlePaddle/PaddleSpeech#2342]
/demos/speech_server按照文档启动服务，配置文件参照conf下的application.yaml.

**Describe the bug**
`GET  /paddlespeech/tts/streaming/samplerate` 报错。`paddlespeech/server/restful/tts_api ` 171行

![image](https://user-images.githubusercontent.com/16896367/187853730-c6fef83a-b4b5-47fa-a576-d231537ed041.png)

PaddleSpeech使用1.1.3版本
![image](https://user-images.githubusercontent.com/16896367/187854734-40778942-6515-4495-965e-02d401ef822f.png)

另外，`/paddlespeech/tts`这个接口是否可以考虑取消`save_path`参数，服务端的保存路径为啥要让客户端决定。

**Comment by lym0302** [comment]
我这边启动没有问题。shell 脚本和命令行都没问题。请问你是什么操作的时候会有这个问题呢？
另外，save_path 确实可以去掉

**Comment by byteszard** [comment]
我是参考`/demos/speech_server/start_multi_progress_server.py`启动的，配置文件使用`conf`下的`application.yaml`，不是通过命令行

**Comment by lym0302** [comment]
目前这个脚本的多线程方式实现不了多线程效果，所以推荐使用readme的方式启动
