### ISSUE TITLE
Punctuation Restoration Part

### ISSUE THREAD

**Issue by Banerjee1234** [PaddlePaddle/PaddleSpeech#2343]
At the time of training model is generated but at the time of testing when we are given the path of trained model into the config file. 
However, it is only executing without giving the path of pretrained model how is it possible?

**Comment by yt605155624** [comment]
Are you telling about Punctuation Restoration testing in 
```text
paddlespeech text --input 今天的天气真不错啊你下午有空吗我想约你一起去吃饭
```
or in

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/iwslt2012/punc0/local/test.sh

??

By the way, please sort out your sentence order. I can't understand it

I guess you are telling about Punctuation Restoration testing in CLI, we call the punc model in cli 
https://github.com/PaddlePaddle/PaddleSpeech/blob/795eb7bd1012f0c6110357726d18c0fab1582708/paddlespeech/cli/text/infer.py#L134 
and it calls the following line without input `ckpt_path`!
https://github.com/PaddlePaddle/PaddleSpeech/blob/795eb7bd1012f0c6110357726d18c0fab1582708/paddlespeech/text/models/ernie_linear/ernie_linear.py#L39 
we input `cfg_path` into `ErnieForTokenClassification.from_pretrained()` and the `ErnieForTokenClassification.from_pretrained()` will load the ckpt model in the same directory of `cfg_path`, for example, the `cfg_path` is `model_config.json` and `from_pretrained()` will load `model_state.pdparams` in the same dir (if you rename the `model_state.pdparams`, may be your program will report an error )，for more details of `from_pretrained()`, please check https://github.com/PaddlePaddle/PaddleNLP
![image](https://user-images.githubusercontent.com/24568452/187890131-0f775934-16c0-4220-b955-963e3edbada9.png)

**Comment by THUzyt21** [comment]
The pre training model is downloaded to the hidden {$HOME} /.paddlenlp/ directory. You can check its path.Use the "la" command to find it.
