### ISSUE TITLE
Punctuation Restoration 

### ISSUE THREAD

**Issue by Anupro123** [PaddlePaddle/PaddleSpeech#2344]
After training i got "snapshot_iter_1926.pdz" model. But kindly tell me the steps how to use this model "snapshot_iter_1926.pdz" for testing.

**Comment by yt605155624** [comment]
the testing in example are not the same with the testing in cli, in cli we use 
![image](https://user-images.githubusercontent.com/24568452/188043428-95d4b9e9-c60f-41aa-a954-b098fe32cdf0.png)
but in example, we use *.pdz, you can use `stage 2` and `stage 3` of  https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/iwslt2012/punc0/run.sh to testing *.pdz

In the future, we will align testing method in cli and example

**Comment by THUzyt21** [comment]
You can modify the "run.sh" to use the model trained by you.
<img width="389" alt="66f7754ddf371fbe1ddbccaaebcd6add" src="https://user-images.githubusercontent.com/91456992/188045822-222ad698-b4b4-4d6b-b95d-04e96b202ec6.png">
Just modify the "ckpt_name".
