### ISSUE TITLE
Text Punctuation

### ISSUE THREAD

**Issue by DrMukherjee** [PaddlePaddle/PaddleSpeech#2345]
When i have remove the "ernie_v1_chn_base.pdparams" file from this particuar catin "paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams" then it doesnot generate the output. From this it is concluded that the trained model is not working it is dependent on  ernie_v1_chn_base.pdparams file only
conf_path=. /PaddleSpeech/examples/iwslt2012/punc0/conf
train_output_path=./PaddleSpeech/examples/iwslt2012/punc0/conf_path=/home/anasua/Desktop/PaddleSpeech/examples/iwslt2012/punc0/conf
train_output_path=. /PaddleSpeech/examples/iwslt2012/punc0/
ckpt_name=./paddlespeech/models/ernie_linear_p7_wudao-punc-zh/1.0/ernie_linear_p7_wudao-punc-zh.tar/ckpt/snapshot_iter_1284.pdz
paddlespeech text --input 因此我可以在互联网上出售我的烘烤食品和诸如此类的东西我
们聚到了一起去探望那些家庭什么的除此以外还有一些为介绍奖项的人所设置的小平台和一
些别的玩意环绕在舞台周围大家都很饿了无名树的果实看起来象熟了的芒果那么美味中国公
民有信仰宗教的自由和不信仰宗教、宣传无神论的自由无信与迷信二者宁愿无信也不要迷信
信必须智信把它描述为无神论的一种宗教信仰将会更恰当一些她本来是个无神论者可是现在
她说自己的信仰改变了不伯莎如果你是个无神论者我不能再和你交往所以就因为你是个无神
论者我就不能庆祝这些节日了散兵坑里不存在无神论者已与集体安全条约组织成员国谈论过
这一问题他们的名气服饰和作品确实使我陶醉令我着迷卡弗夫妇抚养了孤儿乔治并让他随他
们姓了卡弗\n,

**Comment by yt605155624** [comment]
please refer to https://github.com/PaddlePaddle/PaddleSpeech/issues/2344#issuecomment-1234987030 , you cannot move *.pdz to ${HOME}/.paddlespeech/models/ernie_linear_p7_wudao-punc-zh/1.0/

**Comment by zh794390558** [comment]
ernie_v1_chn_base.pdparams 这是模型需要的，不能删除。
