### ISSUE TITLE
关于ASR中加载KenLM 的问题

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2346]
你好，请问下ASR里面说“ CTC beam search decoder”需要加载KenLM 模型，这个在哪加载啊，我好像没有找到加载的接口？
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/asr/quick_start.md
![image](https://user-images.githubusercontent.com/27938135/188410805-44f4ad58-a10d-4a47-95bc-78b1171b57d1.png)

**Comment by Zth9730** [comment]
可查看[paddlespeech/s2t/decoders](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/s2t/decoders)中相关代码

**Comment by Tian14267** [comment]
> 可查看[paddlespeech/s2t/decoders](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/s2t/decoders)中相关代码

好的谢谢。我看这个 kenlm模型貌似在`Conformer`和`Transformer`模型中无法使用的吧？
另外，我再看 **PaddleSpeech/examples/aishell/asr0/** 这个目录的时候，里面的test运行时，报这个错误：
```
  File "/ultra/fffan/0_TTS/temp/PaddleSpeech/PaddleSpeech_asr/paddlespeech/s2t/io/collator.py", line 230, in from_config
    assert 'augmentation_config' in config
AssertionError
```
查看代码发现，代码里有这几行：
```
        assert 'augmentation_config' in config
        assert 'keep_transcription_text' in config
        assert 'mean_std_filepath' in config
        assert 'vocab_filepath' in config
        assert 'spectrum_type' in config
        assert 'n_fft' in config
```
这些配置在模型配置中并没有。请问这是啥情况

**Comment by SmileGoat** [comment]
可以在 PaddleSpeech/examples/aishell/asr0/ conf/tuning/decoder.ymal
中查看配置，然后源码可以在上述decoder中查看
