### ISSUE TITLE
[S2T]aishell 训练时报错

### ISSUE THREAD

**Issue by im73** [PaddlePaddle/PaddleSpeech#2360]
装好环境之后，通过aishell/asr1里面的脚本run.sh进行训练, 在创建模型参数的时候提示config里面没有num_conv_layers这个选项，见图1
<img width="990" alt="image" src="https://user-images.githubusercontent.com/36858700/189056068-c6c16c42-b50f-4206-b244-59c731ca952c.png">
**图1 报错信息**
然后看了一下对应的run.sh里的config，见图2
<img width="630" alt="image" src="https://user-images.githubusercontent.com/36858700/189056461-74946394-830b-4c36-9cb1-c0371b903298.png">
**图2 run.sh里面的配置参数**
发现默认提供的conformer.ymal里面没有对应的num_conv_layer的参数，请问是我的配置文件选择出了问题吗？

**Comment by Zth9730** [comment]
aishell/asr1默认是训练conformer，但从你错误信息中看是训练了deepspeech2，如果想训练deepseech2模型，可以参考aishell/asr0
