### ISSUE TITLE
[S2T]如何不输入Y/N

### ISSUE THREAD

**Issue by QuantumLiu** [PaddlePaddle/PaddleSpeech#2365]
**Describe the bug**
1. 如图在命令行调用时，即使加了 -y 选项，还是要求我输入y/n
2. 在使用python接口ASRExecutor时如何避免输入y/n

**To Reproduce**
`paddlespeech asr -y --input chunks\03_human_1.wav 
`
**Expected behavior**
不用输入Y/N

**Screenshots**
![image](https://user-images.githubusercontent.com/21980268/189188783-217c10e2-4ee5-4d28-9eb7-86092f08c3aa.png)

**Environment (please complete the following information):**
 - OS:win10
 - Python Version 3.7
 - PaddlePaddle Version [gpu          2.3.1.post112 ]
 - Model Version [paddlespeech              1.1.3 ]

**Comment by mxzgn** [comment]
文件设置为同样采样率则不用输入了，可以看看转码有一个转化
