### ISSUE TITLE
KeyError: 'phone_ids'

### ISSUE THREAD

**Issue by Wemmons831** [PaddlePaddle/PaddleSpeech#2366]
Hello I got a Key Error (KeyError: 'phone_ids') while running `paddlespeech tts --input "hello world" --output output.wav`

Windows 11
fresh conda environment with python 3.7
followed the instuctions as listed here for easy https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install.md
0 install errors

**Comment by yt605155624** [comment]
the default model of `paddlespeech tts` is Chinese model, so please input Chinese, for more details please check https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech
