### ISSUE TITLE
CSMSC/vits报错

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2368]
使用预训练模型在运行examples/csmsc/vits的例子时出现下面这个报错，提示我找不到这个模块，但是我看代码里面有这个文件，请问是什么原因？
![image](https://user-images.githubusercontent.com/62881198/189265764-12148087-7905-4466-a76c-3f978e6bd12d.png)

**Comment by yt605155624** [comment]
是否没有执行 
```bash
source path.sh
```
声明环境变量

**Comment by oyb1125** [comment]
![image](https://user-images.githubusercontent.com/62881198/189271495-f06cb212-75a4-4c85-a720-e4b438a0471c.png)
执行了 我照着这个来的

**Comment by yt605155624** [comment]
看看是不是环境里有其他 paddlespeech (比如 python 环境里面 lib/python3.7/site-packages/ 是不是有安装的旧版本的 paddlespeech), 执行的并不是 PaddleSpeech-develop 里面的 paddlespeech, 另外建议通过 git clone 的方式下载代码，而不是压缩包

我看你的环境是 windows, source path.sh 是 linux 上的命令，有可能直接执行是无效的，要不换 git bash 里面运行试试

example 里面的东西建议在 linux 上使用，可以尝试使用 aistudio 的机器资源

**Comment by oyb1125** [comment]
好的，解决了。就是环境里的paddlespeech太旧了，更新了一下就好了，谢谢！
