### ISSUE TITLE
[TTS]英文开头的A发音错误怎么解决？

### ISSUE THREAD

**Issue by lawo123** [PaddlePaddle/PaddleSpeech#2377]
A: Among many others, I have taken Western Economics, International Trade, Marketing and Principles of Accounting. Here is my score book, from which you can learn much more about me.
这句话开始的A发音错误，怎么解决呢？
[20.zip](https://github.com/PaddlePaddle/PaddleSpeech/files/9556348/20.zip)

**Comment by yt605155624** [comment]
我听起来感觉没什么太大的问题，如果你觉得问题比较大，可以把中间音素打印出来看对不对，如果不对，就修改成正确的(英文前端用的 g2p_en，可以看看有没有修改字典的接口)，如果对，但是发音还是觉得有问题，可能是模型没学好，或者语料本身这个发音就不好，可以再学学或者自己收集表现不好的单词的语料加到训练集中

**Comment by lawo123** [comment]
看了一下g2p_en出来的结果是错误的，我试了一下百度翻译读的是对的。如果我们自己修改音素，中间的规则不太好加，什么时候修改，什么时候不改。

**Comment by yt605155624** [comment]
我看了下 among 的音素是没问题的
```bash
paddlespeech tts --am fastspeech2_ljspeech --voc hifigan_ljspeech --lang en --input  "among"
```
```text
phonemes: ['<s>', 'AH0', 'M', 'AH1', 'NG', '</s>']
```
与 cmudict 保持一致
<img width="237" alt="image" src="https://user-images.githubusercontent.com/24568452/190044695-e62db0e5-d762-484f-a384-555afa97e79c.png">

不过 g2p 不能完全依赖开源库，需要根据业务 badcase 修改某些发音，合成效果也不能完全依赖开源数据集

**Comment by lawo123** [comment]
A: Among many others,最开始的A：发音错误，应该读EY1,读的是AH0

**Comment by yt605155624** [comment]
> A: Among many others,最开始的A：发音错误，应该读EY1,读的是AH0

那这里我跟你理解不一致， among 不管是我从小学的还是字典上的描述，都感觉 A 的发音应该是 AH0(额) 而不是 EY1(唉)
<img width="306" alt="image" src="https://user-images.githubusercontent.com/24568452/190075289-a0e2bda6-8b80-4720-a066-2aef419e26ae.png">


cmudict 音素具体发音可参考 http://www.speech.cs.cmu.edu/cgi-bin/cmudict

**Comment by lawo123** [comment]
那可能是我没描述清楚，我指的是A：的发音不是among中a的发音
![image](https://user-images.githubusercontent.com/44777088/190085510-7831b011-9104-4c32-8965-3c1847e3f00c.png)

**Comment by yt605155624** [comment]
> 那可能是我没描述清楚，我指的是A：的发音不是among中a的发音 ![image](https://user-images.githubusercontent.com/44777088/190085510-7831b011-9104-4c32-8965-3c1847e3f00c.png)

A 是多音字，确实不好解决，在 USA 的时候和你这种情况念 ei， 但是在句子中，"I have a banana" 的时候念 额，所以需要你自己加英文多音字预测模块来解决这个问题，或者加一些规则来判断，常见英文多音字参考 https://github.com/google-research-datasets/WikipediaHomographData （但是没有 A）
