### ISSUE TITLE
请问自己 finetune 的 tts 模型能够改变语速吗？

### ISSUE THREAD

**Issue by sixyang** [PaddlePaddle/PaddleSpeech#2383]
代码参考的 [finetune](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/other/tts_finetune/tts3/README.md) 这里，请问一下，这里的 fastspeech2 能调节语速吗？
stylefs 里面需要 tts 的流程，但是我想直接给定一个音频，然后调节其语速，找了一圈，感觉其他的效果都不怎么好，请问有什么推荐吗？谢谢！

**Comment by yt605155624** [comment]
在仓库里面搜 change_speed 有后处理函数

**Comment by yaleimeng** [comment]
@yt605155624 调优完成了，合成的声音有些刺啦刺啦的噪声，这个或许能通过一些方法改善，暂且放下。
我想问的是：调优之后的TTS模型怎样应用到流式推理？ 我尝试仿照tts调优run.sh里面最后一步e2e预测的参数去修改/demos/streaming_tts_server中的conf文件，结果引擎不能初始化。
