### ISSUE TITLE
No stack trace in paddle, may be caused by external reasons.

### ISSUE THREAD

**Issue by michelleqyhqyh** [PaddlePaddle/PaddleSpeech#2384]
W0915 09:12:33.177958 2665464 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
W0915 09:12:33.180549 2665465 gpu_resources.cc:91] device: 1, cuDNN Version: 8.2.
rank: 1, pid: 2665465, parent_pid: 2665115
multiple speaker fastspeech2!
spk_num: 283
rank: 0, pid: 2665464, parent_pid: 2665115
multiple speaker fastspeech2!
spk_num: 283
samplers done!
dataloaders done!
vocab_size: 388
samplers done!
dataloaders done!
vocab_size: 388
model done!
optimizer done!
model done!
optimizer done!
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1663204373 (unix time) try "date -d @1663204373" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2665465 (TID 0x7fe4bb7fb740) from PID 0 ***]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1663204373 (unix time) try "date -d @1663204373" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 2665464 (TID 0x7fc432385740) from PID 0 ***]

Traceback (most recent call last):
  File "/resources/qyh/TTS/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 212, in <module>
    main()
  File "/resources/qyh/TTS/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/train.py", line 206, in main
    dist.spawn(train_sp, (args, config), nprocs=args.ngpu)
  File "/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 565, in spawn
    while not context.join():
  File "/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 373, in join
    self._throw_exception(error_index)
  File "/home/qyh/anaconda3/envs/cuda1100/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 381, in _throw_exception
    (error_index, name))
Exception: Process 0 terminated with signal SIGSEGV

When I run in CUDA_VISIBLE_DEVICES='0,6,7' ./local/train.sh ./conf/default.yaml ./train in PaddleSpeech-develop/examples/zh_en_tts/tts3, I meet this error. Can you help me to fix it?

**Comment by yt605155624** [comment]
I have searched your problem `No stack trace in paddle, may be caused by external reasons.` in the issue of https://github.com/PaddlePaddle/Paddle, I think it may caused by the version of paddlepaddle, cudnn and cuda, could you please share these versions? or try to find answers in https://github.com/PaddlePaddle/Paddle ?

for example this issue: https://github.com/PaddlePaddle/Paddle/issues/44261 maybe you can try to train with 1 gpu(change `ngpu` in `local/train.sh`) to check whether the problem is caused by dist.spwan()

**Comment by michelleqyhqyh** [comment]
> I have searched your problem `No stack trace in paddle, may be caused by external reasons.` in the issue of https://github.com/PaddlePaddle/Paddle, I think it may caused by the version of paddlepaddle, cudnn and cuda, could you please share these versions? or try to find answers in https://github.com/PaddlePaddle/Paddle ?
> 
> for example this issue: [PaddlePaddle/Paddle#44261](https://github.com/PaddlePaddle/Paddle/issues/44261) maybe you can try to train with 1 gpu(change `ngpu` in `local/train.sh`) to check whether the problem is caused by dist.spwan()

Thank you very much! It can run when I : conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
