### ISSUE TITLE
input audio file from gdrive

### ISSUE THREAD

**Issue by ezekny** [PaddlePaddle/PaddleSpeech#2404]
Hello, thanks for the answer to the previous question paddlespeech. i have successfully installed the paddlespeech and now working according to the guide shown in the tutorial.
Meanwhile, i will like to input my audio file from google drive and get the corresponding chinese and english text. Up till now i could not achieve that. Can somebody help out on this as well. Thanks.
The code is as follows:

**from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)
expr_file = "/content/gdrive/MyDrive/Colab Notebooks/paddle3/hs.wav"**

i used this to ensure the sample rate is inline with the model

**_from scipy.io.wavfile import read as read_wav
import os
#os.chdir('path') # change to the file directory
sampling_rate, data=read_wav(expr_file) # enter your filename
print (sampling_rate)_**

However, when i execute
**!paddlespeech asr --lang zh --input expr_file**
i received this error

_/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[2022-09-18 16:30:46,212] [   ERROR] - Please input the right audio file path_

What am i missing from the code?

**Comment by yt605155624** [comment]
maybe you should check this line https://github.com/PaddlePaddle/PaddleSpeech/blob/7e4f3b029ca9a74262036fe124eac4068d793654/paddlespeech/cli/asr/infer.py#L352

Do `paddlespeech` and `expr_file` in the same computer? Sorry, I'm not familiar with gdrive, but `paddlespeech` can only load the `*.wav` in the same machine

**Comment by yaleimeng** [comment]
you can  download that .wav file from gdrive first,  and then run the command  with a local file path.
