### ISSUE TITLE
Paddle2ONNX 转存失败

### ISSUE THREAD

**Issue by JJun-Guo** [PaddlePaddle/PaddleSpeech#2409]
## General Question
使用Paddle2ONNX对声纹模型转存，报错失败
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Failed to parse paddlepaddle model from read content.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.

**Comment by yt605155624** [comment]
Paddle2ONNX 的输入是静态模型，需要先走通动转静
<img width="673" alt="image" src="https://user-images.githubusercontent.com/24568452/190989115-fe6e1208-28b5-4fbc-bb6a-9788a41341a5.png">

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/csmsc/tts3/run.sh 是 TTS 转 ONNX 模型全流程，其中动转静在 synthesize_e2e.sh 这个调用中实现的

**Comment by JJun-Guo** [comment]
声纹模型的输入输出维度是多大呢

**Comment by zh794390558** [comment]
这些参数可以看下配置文件或者打印下输入输出看下。
