### ISSUE TITLE
How to adjust the speed of speech？

### ISSUE THREAD

**Issue by michelleqyhqyh** [PaddlePaddle/PaddleSpeech#2410]
I used PaddleSpeech-develop/examples/zh_en_tts/tts3 to train the model. But when I test, I think the speed of speech is a little bit fast. Is there any method which can adjust the speed of speech？

**Comment by yt605155624** [comment]
you can use post-process method to change the speed of speech, try to search `change_speed` function in PaddleSpeech

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2383

**Comment by michelleqyhqyh** [comment]
> you can use post-process method to change the speed of speech, try to search `change_speed` function in PaddleSpeech

How can I code "PaddleSpeech-develop/paddlespeech/t2s/exps/synthesize_e2e.py" with  `change_speed` function in PaddleSpeech to generate wav-form file?

**Comment by michelleqyhqyh** [comment]
> > you can use post-process method to change the speed of speech, try to search `change_speed` function in PaddleSpeech
> 
> How can I code "PaddleSpeech-develop/paddlespeech/t2s/exps/synthesize_e2e.py" with `change_speed` function in PaddleSpeech to generate wav-form file?

I finished it! Thank you ~~

**Comment by peiqianggao** [comment]
@michelleqyhqyh Hi ~ want to know how did you finish it, Thanks a lot

**Comment by futureflsl** [comment]
> > > you can use post-process method to change the speed of speech, try to search `change_speed` function in PaddleSpeech
> > 
> > 
> > How can I code "PaddleSpeech-develop/paddlespeech/t2s/exps/synthesize_e2e.py" with `change_speed` function in PaddleSpeech to generate wav-form file?
> 
> I finished it! Thank you ~~

can you share the method how to change the speed of speech?
