### ISSUE TITLE
[TTS] 合成语音中的 "1" 念法为 yao, 再用语音识别出来为 "幺"

### ISSUE THREAD

**Issue by monkeydp** [PaddlePaddle/PaddleSpeech#2419]
**Describe the bug**
初始文本: `你好, 你的验证码是 991347`
合成语音后再识别文本: `你好你的验证码是九九幺三四七`

初始文本中的 `1` 被识别成了 `幺`

**To Reproduce**
1. `paddlespeech tts --input "你好，你的验证码是 991347" --output demo.wav`
2. `paddlespeech asr --lang zh --input demo.wav`

**Expected behavior**
期望初始文本中的 `1` 被识别成了 `一`

**Environment (please complete the following information):**
 - OS: Docker Ubuntu18 (构建于 ./docker/ubuntu18-cpu/Dockerfile)

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/a17baad534e3e6397d262de63c11881582ee7f15/paddlespeech/t2s/frontend/zh_normalization/num.py#L106 修改源码 `alt_one=False`
