### ISSUE TITLE
Problems with the pronunciation of abbreviated characters

### ISSUE THREAD

**Issue by michelleqyhqyh** [PaddlePaddle/PaddleSpeech#2428]
I used PaddleSpeech-develop/examples/zh_en_tts/tts3 to train the model. But when I test, I found when I input a sentence "AI 智能" or ”SCI文献“，it will pronunce a continuous sound but not one by one word （like A. I., or S. C. I.）. How can I solve this problem?

**Comment by yt605155624** [comment]
input “A I 智能" or ”S C I文献“，but "A" maybe pronunce "额"，because we still don't have polyphone model in English, try "诶 I 智能"
