### ISSUE TITLE
with s-norm or without s-norm ???

### ISSUE THREAD

**Issue by JJun-Guo** [PaddlePaddle/PaddleSpeech#2440]
请问声纹识别复现的是without s-norm的model吗？with s-norm的代码没有吗？

**Comment by SmileGoat** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/vector/exps/ecapa_tdnn/test.py#L96 norm的方式可选

**Comment by JJun-Guo** [comment]
> 

请问s-norm是否需要训练还是单独后处理就可以呢？

**Comment by JJun-Guo** [comment]
> https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/vector/exps/ecapa_tdnn/test.py#L96 norm的方式可选

请问验证过s-norm中两个参数cohort_size和n_train_snts对结果的影响吗？
