### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2441]
![bcfae547bf3622ba43a544ec4ae3d1f](https://user-images.githubusercontent.com/108966996/191884046-72dbf042-029d-4f75-846e-4757b7ee3fa1.jpg)
![微信图片_20220923105440](https://user-images.githubusercontent.com/108966996/191884103-6d6cde41-b410-49ae-8c99-d52657e6fe6f.jpg)
为什么运行了setup.py之后还是没有相关的库呀

**Comment by yt605155624** [comment]
在 PaddleSpeech 执行 `pip install .` 同时安装依赖和 paddlespeech, 执行 `python3 setup.py install` 仅仅安装 paddlespeech 不安装依赖

有什么依赖没成功安装再安装一遍就是了

**Comment by hufuqiang123** [comment]
> 
那请问怎么安装相应相应得依赖库呢

**Comment by AlphaMind123** [comment]
> 在 Paddlespeech 执行安装同时执行`pip install .`依赖和 paddlespeech, 执行`python3 setup.py install`安装 paddlespeech 不安装依赖
> 
> 有什么没有成功安装再安装就是依赖了

可是差的有点多啊，装了好几个库了

**Comment by yt605155624** [comment]
理论上 `pip install .` 执行成功是不会有问题的，你可以检查下是不是这步就执行失败了
