### ISSUE TITLE
为什么第二天要重新安装库

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2446]
为什么前一天缺少的包都安装了，第二天进去怎么又要重新安装呢
![Snipaste_2022-09-24_09-53-32](https://user-images.githubusercontent.com/108966996/192075170-29c1f523-0b43-415e-b657-03c56f873e1c.png)

**Comment by yt605155624** [comment]
AISTUDIO 每次进入环境相当于新建了一个全新的系统
