### ISSUE TITLE
PaddleSpeech Create Srt file

### ISSUE THREAD

**Issue by imohuan** [PaddlePaddle/PaddleSpeech#2447]
# Qustion
Is it possible to quickly convert an hour-long audio to a srt subtitle file?

# Individual
I had a preliminary understanding of PaddleSpeech converting audio to text, but my text didn't even have punctuation.
Maybe it's my code.

**Comment by yt605155624** [comment]
try to use this demo to generate punc https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/punctuation_restoration

**Comment by imohuan** [comment]
> try to use this demo to generate punc https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/punctuation_restoration

Thank you very much for your answer. The punctuation can be recovered. Can you use the use of SRT files?

**Comment by imohuan** [comment]
I hope to realize the local voice transfer srt subtitles, so I found padderPeech

**Comment by imohuan** [comment]
Why ? You didn't answer my question about srt subtitles.

**Comment by twoDogy** [comment]
#3123 已增加生成srt功能。
