### ISSUE TITLE
脚本执行结果

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2448]
![image](https://user-images.githubusercontent.com/108966996/192087100-d7a4e4ff-fce7-457a-9ca2-51117c8d2685.png)
请问这个脚本执行之后为什么不训练呢

**Comment by yt605155624** [comment]
应该是代码里设置了用4卡训练但是你实际只有2块卡，看下代码吧

**Comment by AlphaMind123** [comment]
> 应该是代码里设置了用4卡训练但是你实际只有2块卡，看下代码吧

那个path.sh是不是要运行，如果运行，指令是否为'!source path.sh'
我看了教程，但是我用了这个命令，但是运行不了

**Comment by AlphaMind123** [comment]
> 应该是代码里设置了用4卡训练但是你实际只有2块卡，看下代码吧

但是我改成了用1卡训练的

**Comment by yt605155624** [comment]
> > 应该是代码里设置了用4卡训练但是你实际只有2块卡，看下代码吧
> 
> 那个path.sh是不是要运行，如果运行，指令是否为'!source path.sh' 我看了教程，但是我用了这个命令，但是运行不了

可以换成 %source path.sh ， jupyter 里面用 ! 不会影响到之后的命令
