### ISSUE TITLE
请问是否有同时支持中英文的ASR模型

### ISSUE THREAD

**Issue by UprightNeether** [PaddlePaddle/PaddleSpeech#2453]
如果预训练的模型只支持中文的话，实际适用场景很受限制

**Comment by yt605155624** [comment]
目前不支持，已经在开发计划中了

**Comment by yaleimeng** [comment]
借楼问一下， @yt605155624  离线TTS已经支持中英文混合，能不能迁移到流式TTS上去？

**Comment by yt605155624** [comment]
> 借楼问一下， @yt605155624 离线TTS已经支持中英文混合，能不能迁移到流式TTS上去？

可以自己训练一个中英文混合的 fastspeech2_cnndecoder, 导出 onnx 模型迁移到流式 TTS 服务中，目前中英文混合的模型的 default fastspeech2，不能支持流式

**Comment by yaleimeng** [comment]
谢谢回复
