### ISSUE TITLE
example/csmsc/tts3里边synthesize_streaming.sh 和inference_streaming.sh的区别？

### ISSUE THREAD

**Issue by panxin801** [PaddlePaddle/PaddleSpeech#2455]
您好，很感谢你们公开这么好的工作。再看了代码以后我对比这两个文件的区别发现他们的区别在于：
- synthesize_streaming这个脚本中包含了静态图的转换，但是在inference_streaming中没有静态图的转换；
- synthesize_streaming合成mel是分的chunk，Mel拼接一起产生的wav。inference_streaming也是这个过程。其实在这个过程中他们是一样的。

期待您的回复，谢谢您。

**Comment by yt605155624** [comment]
在 PaddleSpeech(或者 Paddle) 的语境中，一般 inference 代表用静态图进行推理，所以 synthesize_* 是用动态图推理（实际上是加载动态图之后进行了动转静再用 load 进来后推理，但是这不是真正的静态图推理，动转静的代码也可以注释），inference_* 是用静态图推理，二者所加载的模型不同

**Comment by panxin801** [comment]
谢谢您的回复，我明白其中的区别了。谢谢您的回复
