### ISSUE TITLE
将文本数据集转化为语音数据集

### ISSUE THREAD

**Issue by MingyuLau** [PaddlePaddle/PaddleSpeech#2458]
我想把一个文本数据集转化为语音数据集，请问paddlespeech里面有提供转换的代码吗

**Comment by yaleimeng** [comment]
使用TTS就可以了。[参考文档](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/text_to_speech/README_cn.md)

**Comment by MingyuLau** [comment]
多谢

**Comment by MingyuLau** [comment]
对了，这个转换可以使用多线程吗，数据量有点多

**Comment by yt605155624** [comment]
可以自己参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/63f70c9fd002594ada80c8e39875d5c24a1cdf25/paddlespeech/t2s/exps/fastspeech2/preprocess.py#L164 写多线程，需要自己研究现状是否线程安全

**Comment by yt605155624** [comment]
PaddleSpeech 恰巧有串联 OCR 和 TTS 的 demo：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/story_talker
