### ISSUE TITLE
[S2T] aishell/asr1 训练过程卡住不动

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2459]
你好，我发现一个问题，对于ASR训练（文件夹：examples/aishell/asr1）,训练到中间部分的时候，就直接卡住不动了，主要有以下情况：
1：单卡训练的时候，训练到中间部分，训练就卡住了，GPU也完全不动了，GPU内存却正常占用；
![image](https://user-images.githubusercontent.com/27938135/192408393-6ce0f5e4-7cbc-43cf-80e5-72db30478aaa.png)
打印的日志只更新到26号，训练epoch到25就不动了（设置的epoch是30）;

2: 双卡训练的时候，也一样的情况。重启之后，1个epoch都没训练就卡住了。状态和上面一样。
![image](https://user-images.githubusercontent.com/27938135/192408745-3ebd652d-cb24-4242-8535-b06cab46f69c.png)
![image](https://user-images.githubusercontent.com/27938135/192408785-4a4771e4-e00d-4513-8d62-d6fdc6f9e06d.png)
这两张卡一直处于静止状态。请问这个问题是什么情况啊

**Comment by Tian14267** [comment]
训练卡住不动，GPU也静止不动，这个情况我换了三台服务器都做了验证，训练数据用过aishell数据，也用过自己的数据，都一样的情况，有时候刚训练就卡住，有时候训练到中间卡住。机器和GPU是没问题的。

**Comment by zh794390558** [comment]
好的，我们试试看能复现问题不。

能调小batchsize试试吗？

**Comment by Zth9730** [comment]
能否提供一下模型配置？

**Comment by Tian14267** [comment]
> 



> 能否提供一下模型配置？

回头我试试小batch的情况。
@Zth9730 模型配置使用的transformer模型，具体配置为默认的。只改动过batch。

**Comment by Tian14267** [comment]
@zh794390558 @Zth9730 
哈喽，我尝试了小batch（16），也是一样的情况。换成 `conformer` 进行训练，只训练到epoch=8就不动了。日志更新只到凌晨2点，GPU内存正常占用
![image](https://user-images.githubusercontent.com/27938135/192713746-f55b66d2-d9ad-4642-a8e3-b1af050cfaa6.png)
手动`kill`之后在接着训练的话，是可以接着训练的。

**Comment by Tian14267** [comment]
@zh794390558 你好，我还没明白“`Chang memory allocator strategy `”如何change。另外，我调小batch也是一样的情况。
<img width="393" alt="4146cc11c316d9eae0bb29aa33a445cdb3ea2f56d3760bd838102d919221715fQzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNTgyNjQ1NjYzX3YyXEltYWdlRmlsZXNcMTY2NDUwMjUyNDc3MV9CQ0RBMzQ3QS1CNjI4LTQyYzgtQTM0NC0xOTdGMzcxNUYxMjMucG5n" src="https://user-images.githubusercontent.com/27938135/193173106-126767f4-9ccc-45cc-b7d1-875f46816a5a.png">
<img width="1487" alt="7dd2ef0f27a4c754e4596677febd75033302c4f6d2bd5e57446ba68f0cc25027QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNTgyNjQ1NjYzX3YyXEltYWdlRmlsZXNcMTY2NDUwMjUzNTk5Ml9GNTc3RDU1NS1BMDUxLTRjOGYtQjg0Mi0wOTY4M0NBNUNGQ0EucG5n" src="https://user-images.githubusercontent.com/27938135/193173118-67cb11c6-cfc0-444b-9eed-0df3d8c46ca1.png">
请问如何调整`memory allocator strategy`

**Comment by Zth9730** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/32243340/193175096-142e5b95-02ff-484f-9a31-9476fcbcfd0a.png">
这样改动试一试，另外你是cuda 11.4？可以尝试一下cuda 10.2。

**Comment by Tian14267** [comment]
@Zth9730 好的，非常感谢，我修改试试。另外，我是cuda 11.2 。图上只是nvidia的驱动版本。

**Comment by Tian14267** [comment]
@zh794390558 @Zth9730 哈喽，你好。我尝试了`Chang memory allocator strategy`，但是还是会出现卡死的情况。请问你们那边能复现和解决这个问题吗？cuda 11.2
