### ISSUE TITLE
标点恢复example中的预训练模型如何使用

### ISSUE THREAD

**Issue by laity-slf** [PaddlePaddle/PaddleSpeech#2470]
## General Question

官网给出的调用方式是这个
<img width="774" alt="image" src="https://user-images.githubusercontent.com/59203496/192670983-6e20cf5c-d26c-474d-84db-6379fbfe31c3.png">

但我model=None 实际上会报错，因为后续有一个从model_type 取子字符串的操作。
<img width="772" alt="image" src="https://user-images.githubusercontent.com/59203496/192672100-b3018e6d-79fa-44cc-8d00-2cae4a90ff4d.png">

然后按照如下的调用方式也会报错，原因应该是无法识别defaut.yaml 文件
<img width="773" alt="image" src="https://user-images.githubusercontent.com/59203496/192672373-2e386d46-14c4-48ab-a0db-8168b941e990.png">

请问我该如何解决？

**Comment by yt605155624** [comment]
标点恢复 example 中训练的模型格式，和 cli 里面的模型格式由于历史原因不一致，目前 cli 中正在尝试使用 example 中训练的模型格式，参考这个未合入的 pr：https://github.com/PaddlePaddle/PaddleSpeech/pull/2421
暂时可尝试使用 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/iwslt2012/punc0/local/punc_restore.sh 对 example 训练的标点模型格式进行调用

**Comment by laity-slf** [comment]
> 标点恢复 example 中训练的模型格式，和 cli 里面的模型格式由于历史原因不一致，目前 cli 中正在尝试使用 example 中训练的模型格式，参考这个未合入的 pr：#2421 暂时可尝试使用 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/iwslt2012/punc0/local/punc_restore.sh 对 example 训练的标点模型格式进行调用

感谢回复
