### ISSUE TITLE
where is synthesize.py??

### ISSUE THREAD

**Issue by lucasjinreal** [PaddlePaddle/PaddleSpeech#2474]
where is synthesize.py??

**Comment by yt605155624** [comment]
We `source path.sh` in `run.sh`, please check `path.sh` for `${BIN_DIR}`

**Comment by lucasjinreal** [comment]
okk.  Seems the mix voice quality not very good, do u know why? (compare with pure synthesis result)

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/issues/2330
