### ISSUE TITLE
请问语音转文字是否支持选择声道?

### ISSUE THREAD

**Issue by monkeydp** [PaddlePaddle/PaddleSpeech#2476]

**Comment by yt605155624** [comment]
Please input the 16k 16 bit 1 channel wav file.

**Comment by yaleimeng** [comment]
@yt605155624  其实我想改造一下，让离线识别也能直接接受numpy数据，省去单通道wav文件存取环节。。
因为目前拿到语音数据的话，只有流式ASR识别能接受（也需要改写），但流式识别需要等待很长时间。

**Comment by yt605155624** [comment]
@yaleimeng 欢迎提交 pr

**Comment by yaleimeng** [comment]
看了一下代码发现挺麻烦的。因为平常使用的都是通过soundfile打开，直接拿到numpy张量就是语音帧。
但是离线ASR http服务接收的东西是通过f.read( )读取二进制数据，进行base64编码，然后又utf-8解码的字符串，在前面输入这一段基本没法转换。
待会再看看接受之后，推理里面的情况。
