### ISSUE TITLE
[S2T] 在example/aishell/asr1中如何fine-tuning？

### ISSUE THREAD

**Issue by Ardang666** [PaddlePaddle/PaddleSpeech#2479]
在 example/aishell/asr1 中，train相关的代码里面，并没有找到如何fine-tuning，请问一下，如何在仓库提供的 asr1_transformer_aishell_ckpt_0.1.1.model.tar.gz 基础上，进行fine-tuning？

**Comment by Ardang666** [comment]
自问自答：--checkpoint_path exp/${ckpt_name}/checkpoints/avg_20

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972
