### ISSUE TITLE
local variable 'wav_all' referenced before assignment 

### ISSUE THREAD

**Issue by MingyuLau** [PaddlePaddle/PaddleSpeech#2480]
在运行语音合成[demo](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech) 的时候报了如下错误：

`File"/home/user/.conda/envs/mmlab/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "o2s.py", line 58, in convertor
    device=paddle.get_device())
  File "/home/user/yl/PaddleSpeech/paddlespeech/cli/utils.py", line 328, in _warpper
    return executor_func(self, *args, **kwargs)
  File "/home/user/yl/PaddleSpeech/paddlespeech/cli/tts/infer.py", line 708, in __call__
    self.infer_onnx(text=text, lang=lang, am=am, spk_id=spk_id)
  File "/home/user/yl/PaddleSpeech/paddlespeech/cli/tts/infer.py", line 537, in infer_onnx
    self._outputs['wav'] = wav_all
UnboundLocalError: local variable 'wav_all' referenced before assignment
`

**Comment by yt605155624** [comment]
应该是之前的执行步骤就有问题，可以在源码 `"/home/user/yl/PaddleSpeech/paddlespeech/cli/tts/infer.py", line 537,` 多 print 些信息看看

**Comment by MingyuLau** [comment]
这个问题不是一运行就报错，而是转换到一定数量的时候就会报错@ yt605155624

**Comment by yt605155624** [comment]
你多打印些 log 吧，看看是不是有资源没释放，我们没有用大量数据跑过
如果有大量的数据需要合成，也可以直接用 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/csmsc/tts3
