### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2486]
请问run.sh里面的ips变量的意义是什么
-->

**Comment by yt605155624** [comment]
## 指标计算方法，细节介绍
- reader_cost。1个Step数据加载用时，单位：秒(sec)。

  - N个Step打印1条日志时，reader_cost为N个Step数据加载用时的平均值
  - 建议(但不强制)使用DataLoader，而非DataFeeder
- batch_cost。1个Step训练用时，单位：秒(sec)。batch_cost = reader_cost + exe.run（训练）时间。
  - batch_cost中必须包含reader_cost时间
  - N个Step打印1条日志时，batch_cost为N个Step训练用时的平均值
  - 不建议将模型其它计算逻辑计入batch_cost用时中，尤其是比较耗时的逻辑
- ips。单卡每秒处理的样本数，单位如：images/sec、sequences/sec、tokens/sec、words/sec、frames/sec等。

  - 样本，是images、sequences、tokens、words、frames的统称，不同模型的单位不一样，下文中的样本指的是能够反应模型吞吐数据能力的基本数据单元
  - ips核心目标是统计模型的吞吐性能，提供统一的、标准的性能对比指标
  - 每个Step都打印1条日志时，ips计算方法： 该Step样本数 / batch_cost
  - N个Step打印1条日志时， ips 计算方法：N轮Step样本总数 / N轮batch_cost总和，每个Step样本数不同时，注意特殊处理
  - ips为单卡吞吐量： 无论动态图、静态图、单卡、多卡，所计算的ips均为单卡值。如需计算多卡ips，由Benchmark脚本负责累加
- samples。 对于每个Step样本数可能不同的模型（大多为NLP模型），需要计算samples。samples代表上次打印到本次打印，新完成训练的样本数量。

  - 需要打印samples的原因：Benchmark在计算总体ips时，如果每Step样本数相同，对每条打印的ips求平均即可。但如果每个Step样本数不同，Benchmark需要拿到本次打印的samples，加和，再除以总体耗时。
  - 对于静态图，samples=多卡总samples数/卡数
  - 对于动态图，每张卡的samples分别打印
  - 对于每轮训练样本数固定的模型，无需计算、打印samples。
- 建议每轮训练，均Fetch所需Variable。Paddle底层Fetch机制已优化，不会严重消耗时间。

**Comment by AlphaMind123** [comment]
> ## 指标计算方法，细节介绍
> * reader_cost。1个Step数据加载用时，单位：秒(sec)。
>   
>   * N个Step打印1条日志时，reader_cost为N个Step数据加载用时的平均值
>   * 建议(但不强制)使用DataLoader，而非DataFeeder
> * batch_cost。1个Step训练用时，单位：秒(sec)。batch_cost = reader_cost + exe.run（训练）时间。
>   
>   * batch_cost中必须包含reader_cost时间
>   * N个Step打印1条日志时，batch_cost为N个Step训练用时的平均值
>   * 不建议将模型其它计算逻辑计入batch_cost用时中，尤其是比较耗时的逻辑
> * ips。单卡每秒处理的样本数，单位如：images/sec、sequences/sec、tokens/sec、words/sec、frames/sec等。
>   
>   * 样本，是images、sequences、tokens、words、frames的统称，不同模型的单位不一样，下文中的样本指的是能够反应模型吞吐数据能力的基本数据单元
>   * ips核心目标是统计模型的吞吐性能，提供统一的、标准的性能对比指标
>   * 每个Step都打印1条日志时，ips计算方法： 该Step样本数 / batch_cost
>   * N个Step打印1条日志时， ips 计算方法：N轮Step样本总数 / N轮batch_cost总和，每个Step样本数不同时，注意特殊处理
>   * ips为单卡吞吐量： 无论动态图、静态图、单卡、多卡，所计算的ips均为单卡值。如需计算多卡ips，由Benchmark脚本负责累加
> * samples。 对于每个Step样本数可能不同的模型（大多为NLP模型），需要计算samples。samples代表上次打印到本次打印，新完成训练的样本数量。
>   
>   * 需要打印samples的原因：Benchmark在计算总体ips时，如果每Step样本数相同，对每条打印的ips求平均即可。但如果每个Step样本数不同，Benchmark需要拿到本次打印的samples，加和，再除以总体耗时。
>   * 对于静态图，samples=多卡总samples数/卡数
>   * 对于动态图，每张卡的samples分别打印
>   * 对于每轮训练样本数固定的模型，无需计算、打印samples。
> * 建议每轮训练，均Fetch所需Variable。Paddle底层Fetch机制已优化，不会严重消耗时间。

请问epoch参数设置在哪个文件里面

**Comment by yt605155624** [comment]
conf/*.yaml

**Comment by AlphaMind123** [comment]
请问在哪里设置使用fbank特征还是specAugment



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月29日 16:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSpeech] 参数问题 (Issue #2486) |

conf/*.yaml

**Comment by AlphaMind123** [comment]
> > ## 指标计算方法，细节介绍
> > 
> > * reader_cost。1个Step数据加载用时，单位：秒(sec)。
> >   
> >   * N个Step打印1条日志时，reader_cost为N个Step数据加载用时的平均值
> >   * 建议(但不强制)使用DataLoader，而非DataFeeder
> > * batch_cost。1个Step训练用时，单位：秒(sec)。batch_cost = reader_cost + exe.run（训练）时间。
> >   
> >   * batch_cost中必须包含reader_cost时间
> >   * N个Step打印1条日志时，batch_cost为N个Step训练用时的平均值
> >   * 不建议将模型其它计算逻辑计入batch_cost用时中，尤其是比较耗时的逻辑
> > * ips。单卡每秒处理的样本数，单位如：images/sec、sequences/sec、tokens/sec、words/sec、frames/sec等。
> >   
> >   * 样本，是images、sequences、tokens、words、frames的统称，不同模型的单位不一样，下文中的样本指的是能够反应模型吞吐数据能力的基本数据单元
> >   * ips核心目标是统计模型的吞吐性能，提供统一的、标准的性能对比指标
> >   * 每个Step都打印1条日志时，ips计算方法： 该Step样本数 / batch_cost
> >   * N个Step打印1条日志时， ips 计算方法：N轮Step样本总数 / N轮batch_cost总和，每个Step样本数不同时，注意特殊处理
> >   * ips为单卡吞吐量： 无论动态图、静态图、单卡、多卡，所计算的ips均为单卡值。如需计算多卡ips，由Benchmark脚本负责累加
> > * samples。 对于每个Step样本数可能不同的模型（大多为NLP模型），需要计算samples。samples代表上次打印到本次打印，新完成训练的样本数量。
> >   
> >   * 需要打印samples的原因：Benchmark在计算总体ips时，如果每Step样本数相同，对每条打印的ips求平均即可。但如果每个Step样本数不同，Benchmark需要拿到本次打印的samples，加和，再除以总体耗时。
> >   * 对于静态图，samples=多卡总samples数/卡数
> >   * 对于动态图，每张卡的samples分别打印
> >   * 对于每轮训练样本数固定的模型，无需计算、打印samples。
> > * 建议每轮训练，均Fetch所需Variable。Paddle底层Fetch机制已优化，不会严重消耗时间。
> 
> 请问epoch参数设置在哪个文件里面

请问在哪里设置使用fbank特征还是specAugment

**Comment by yt605155624** [comment]
这些问题请你自己看代码吧，后续这种问题不会再回复 ：）
