### ISSUE TITLE
使用ONNXRuntime推理的cpu_thread和python多线程的线程数是什么关系，会起冲突吗？

### ISSUE THREAD

**Issue by MingyuLau** [PaddlePaddle/PaddleSpeech#2490]
在用文本数据合成语音的时候使用了ONNXRuntime推理的模型：
`tts_executor = TTSExecutor()
    wav_file = tts_executor(
        text=text,
        output=outputpath,
        am='fastspeech2_vctk',
        voc='hifigan_ljspeech',
        lang='en',
        use_onnx=True,
        cpu_threads=14)`
同时我将python多线程的pool的WORKERS数量也设置为14，请问这两个之间会发生冲突吗？

**Comment by yt605155624** [comment]
这块不是很清楚呢，可以到 onnxruntime 问问？

但是有一个建议，onnxruntime-cpu 不代表 cpu_threads 越大速度就越快，因为多线程之间可能有交互，反而速度会变慢，我们默认的 2 或者 4 就是比较好的值，再大会慢，具体看硬件

**Comment by MingyuLau** [comment]
好的谢谢
