### ISSUE TITLE
关于语音识别预训练模型的加载问题

### ISSUE THREAD

**Issue by NICECPU** [PaddlePaddle/PaddleSpeech#2494]
## General Question
请问我在PaddleSpeech\examples\aishell\asr1 路径下的训练时，我想要加载预训练权重，通过
wget https://paddlespeech.bj.bcebos.com/s2t/aishell/asr1/asr1_transformer_aishell_ckpt_0.1.1.model.tar.gz
tar xzvf asr1_transformer_aishell_ckpt_0.1.1.model.tar.gz
source path.sh
当我执行上面的语句时，执行到source path.sh ,提示我The standard file /home/aistudio/PaddleSpeech/tools/kaldi/tools/config/common_path.sh is not present, can not using Kaldi!
我很疑惑为什么没有这个文件，是不是我遗漏了什么步骤

**Comment by Ardang666** [comment]
就是说你没用 kaldi而已，你可以安装kaldi也可以不用。
继续执行也没有问题

**Comment by NICECPU** [comment]
> 

是的，我已经明白了，谢谢你的回复
