### ISSUE TITLE
包问题

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2495]
![image](https://user-images.githubusercontent.com/108966996/193975287-df3f3e0e-92ba-4eda-b872-9954d5919913.png)
为什么我这样安装包之后它还是会显示没有这个module
![image](https://user-images.githubusercontent.com/108966996/193975360-8a5d95a3-b0e5-40c3-be01-ef3b371d79bb.png)

**Comment by yt605155624** [comment]
请按照我们在 aistudio 教程中提供的安装方式，你这种 -t 不知道是否能正常找到

**Comment by AlphaMind123** [comment]
> 请按照我们在 aistudio 教程中提供的安装方式，你这种 -t 不知道是否能正常找到

![image](https://user-images.githubusercontent.com/108966996/194683888-860a2ace-d9ae-44dd-a565-88eef7415272.png)
ke可是持久化安装的示例是这样的

**Comment by AlphaMind123** [comment]
> 请按照我们在 aistudio 教程中提供的安装方式，你这种 -t 不知道是否能正常找到

![image](https://user-images.githubusercontent.com/108966996/194683912-8901d292-c800-4525-8850-2e08d68ecbe0.png)
