### ISSUE TITLE
test输出问题

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2507]
![image](https://user-images.githubusercontent.com/108966996/194707961-cd017d97-5c36-4ee8-a7c2-e6db41ae7f07.png)

运行stage3test的时候，输出打印为什么hyp是空的

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/2387 修改 log 等级获取更多信息，此外，可在代码 https://github.com/paddlepaddle/PaddleSpeech/blob/develop/paddlespeech/cli/text/infer.py 中 print 更多信息进行调试

**Comment by Zth9730** [comment]
测试用的模型是否是训练好的模型？很可能用了个训练不好或者没训练的模型进行了测试。

**Comment by AlphaMind123** [comment]
> 测试用的模型是否是训练好的模型？很可能用了个训练不好或者没训练的模型进行了测试。

我只先跑了2个epoch后进行了下测试，意思是像这种完全可能一个字也没有预测出来？

**Comment by Zth9730** [comment]
是的

**Comment by AlphaMind123** [comment]
> 是的
好的谢谢
