### ISSUE TITLE
有关标点符号的训练问题

### ISSUE THREAD

**Issue by laity-slf** [PaddlePaddle/PaddleSpeech#2509]
## General Question

就是在我使用自己数据训练的时候发现，后面的文字他不会进行标点恢复。
比如：
Punctuation Restoration Result: 新华社北京10月8日电记者从有关方面获悉，中国共产党第二十次全国代表大会新闻中心将于10月12日启用，并开始对外接待服务新闻中心记者接待服务区设在北京新世纪日航饭店新闻中心将热情为前来采访党的二十大的香港特别行政区澳门特别行政区台湾地区的媒体记者和外国媒体记者办理采访证件受理采访申请组织大会新闻发布会和记者招待会安排记者参加大会采访活动。

造成这个现象的原因是模型没有收敛么？？？

但是我看loss其实已经在震荡了。

数据采用的是清华新闻数据集：
部分数据如下，我对字符数少于20个的行会直接过滤；
<img width="976" alt="image" src="https://user-images.githubusercontent.com/59203496/194716083-05ad3302-9e62-452b-8aa3-9b631fbcd435.png">

有没有大佬给个意见=-=
我先多train 几个epoch看看

**Comment by zh794390558** [comment]
标点恢复只有，。？！四个输出。训练数据需要做预处理。

**Comment by laity-slf** [comment]
> 

您好，我这边是做了预处理的    把、转为，把！；换成了。  不知道您说的预处理还有哪些  ”“ 这些也要换成 ，吗

**Comment by zh794390558** [comment]
" 《 》这些都可以删除的。

**Comment by laity-slf** [comment]
> 
您好，是删除的。我现在修改了解码的方法，能够生成了。原因应该是长度的关系，训练时候设置的长度是100，预测那边没有resize，所以有gap

**Comment by yt605155624** [comment]
@laity-slf 你好，相应的修改方便提个 pr 或者具体列一些代码位置看一下嘛

**Comment by laity-slf** [comment]
### 就放一下代码吧，其实也是参考的训练过程。因为我训练的模型，超过长度100多就不会加上标点符号了，但是下载的预训练模型可以做到，这点我也没找到原因。但是改写之后这个问题基本上能够解决；
```
def preprocess(text, punc_list):
        clean_text = _clean_text(text, punc_list)
        assert len(clean_text) > 0, f'Invalid input string: {text}'
        tokenized_input = tokenizer(
            list(clean_text), return_length=True, is_split_into_words=True)
        # padding +  resize seq_len=100
        pad_len = 100 - (tokenized_input['seq_len'] - 2) % 100
        tokenized_input['input_ids'] = tokenized_input['input_ids'][1:-1] + [0] * pad_len
        _inputs = dict()
        _inputs['input_ids'] = np.array(
            tokenized_input['input_ids'], dtype='int64').reshape(-1, 100)
        _inputs['seg_ids'] = [[0] * _inputs['input_ids'].shape[1]] * _inputs["input_ids"].shape[0]
        _inputs['pad_len'] = pad_len
        return _inputs
```
这边我看没有用到原来的_inputs['seq_len']  所以就干脆保存了pad_len，对应下面取tokens的时候可以用到；
```
    logits, _ = model(input_ids, seg_ids)
    preds = paddle.argmax(logits, axis=-1).squeeze(0)
    # TODO fix % 等字符的问题，原因在于ernie-1.0的分词器无法识别%；可以遍历一遍token，将原本的【unk】 替换成输入的token
    # TODO 或者可以直接采用输入(clean_text)，去掉转token的这一步；因为是一一对应的；
    tokens = tokenizer.convert_ids_to_tokens(
        _inputs['input_ids'].reshape(-1)[:-pad_len])
    labels = preds[:-pad_len].tolist()
```
这里也有个小问题，我写在了TODO里面。就是ernie-1.0那边是一个词一个词切分的，那么为什么不直接让token=clean_text,因为也是一一对应的，而且不会有一些unk符号的问题

**Comment by yt605155624** [comment]
由于本身也不是做 nlp 的，只能说下我的拙劣的建议：
1. 我们提供的预训练模型是在一个巨大无比的数据集上训练的(训练集纯文本 68G 左右)
2. 是否按照你的数据集的分布，重新设置训练时的 seq_len 试试
3. `为什么不直接让token=clean_text` 这种问题或许可以直接去 PaddleNLP 试着问问

**Comment by laity-slf** [comment]
> 

好的，非常感谢！

**Comment by yt605155624** [comment]
问了下 PaddleNLP 的同事，ERNIE finetune 的时候 seq_len 的设置，一般需要跟模型实际使用的长度匹配上，128、256、512 都行，但最大一般也不能超过 512。

**Comment by laity-slf** [comment]
> 问了下 PaddleNLP 的同事，ERNIE finetune 的时候 seq_len 的设置，一般需要跟模型实际使用的长度匹配上，128、256、512 都行，但最大一般也不能超过 512。
好的，麻烦了
