### ISSUE TITLE
❗❗[Server]declarative() got an unexpected keyword argument 'property'

### ISSUE THREAD

**Issue by Plutoisme** [PaddlePaddle/PaddleSpeech#2512]
按照官网教程：https://aistudio.baidu.com/aistudio/projectdetail/4668770?forkThirdPart=1
在服务器端部署paddle时：

# 进入根目录
cd /home/aistudio/PaddleSpeech
# 开启服务
paddlespeech_server start --config_file ./paddlespeech/server/conf/application.yaml

报错显示：
[2022-10-09 11:30:23,153] [    INFO] - start to init the engine
[2022-10-09 11:30:23,154] [    INFO] - asr : python engine.
[2022-10-09 11:30:31,894] [   ERROR] - Failed to start server.
[2022-10-09 11:30:31,895] [   ERROR] - declarative() got an unexpected keyword argument 'property'

求解，个人猜测可能是版本问题遗留的一个bug？

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/2387 修改 log 等级获取更多信息

**Comment by Plutoisme** [comment]
> 参考 #2387 修改 log 等级获取更多信息

按照链接所提到的修改方式，在log.py和executor.py两个文件下进行了logging.INFO->logging.DEBUG的修改，执行paddlespeech_server start --config_file ./paddlespeech/server/conf/application.yaml命令报错仍旧没有多余的补充信息。

PS：我是在paddle的fork了项目，直接使用AI STUDIO运行的。

**Comment by zh794390558** [comment]
`property` 是paddle 2.4rc 中新增的功能，如果用到paddlespeech develop的代码的话，需要使用paddle 的 dev版本或 >=2.4rc

**Comment by yt605155624** [comment]
安装 paddlepaddle-gpu 2.4rc：
```bash
python3 -m pip install paddlepaddle-gpu==2.4.0rc0 -i https://mirror.baidu.com/pypi/simple
```

**Comment by JYCcx** [comment]
使用aistudio运行deep speed和在本地环境运行时都出现了没有data/mean_std的情况和以下问题
![1666521220085](https://user-images.githubusercontent.com/116490558/197387247-89604e92-4fc0-463f-a32c-dfc2eb7f94ba.png)

**Comment by yt605155624** [comment]
@JYCcx 参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/2557 看看最新版的教程是否已经可以了，另外类似问题建议新开一个 issue，你的这个问题和此 issue 没有任何关系，容易被我们漏掉

**Comment by shenhua4286** [comment]
> `property` 是paddle 2.4rc 中新增的功能，如果用到paddlespeech develop的代码的话，需要使用paddle 的 dev版本或 >=2.4rc

升级版本成功解决
