### ISSUE TITLE
英伟达官方无此安装包  CuDNN7.5 (for  CUDA 10.2)

### ISSUE THREAD

**Issue by 312shan** [PaddlePaddle/PaddleSpeech#2520]
##  install_cn.md 写gpu2.4rc依赖是 CUDA 10.2， CuDNN7.5 

通过看英伟达官方提供的 [cudnn列表](https://developer.nvidia.com/rdp/cudnn-archive)，没发现 CuDNN7.5  for cuda10.2；

所以你们的 [install_cn.md ](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md)文件是否编写有误？

如果是paddle自己编译或者开发的 cudnn，可否提供一下下载链接？

**Comment by yt605155624** [comment]
确实，CUDA 和 CUDNN 版本配套参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
