### ISSUE TITLE
使用paddlespeech asr 报错

### ISSUE THREAD

**Issue by armada2013** [PaddlePaddle/PaddleSpeech#2526]
运行 paddlespeech asr --lang zh --input zh.wav时，报错paddlespeech/models/conformer_u2pp_wenetspeech-zh-16k/1.1/asr1_chunk_conformer_u2pp_wenetspeech_ckpt_1.1.3.model.tar/model.yaml 找不到，请问这是什么原因呢？

**Comment by zh794390558** [comment]
搜索下 asr1_chunk_conformer_u2pp_wenetspeech_ckpt_1.1.3.model.tar 目录中个是否有这个文件。

**Comment by Zth9730** [comment]
建议更新到最新的仓库代码，删除已下载的本地包，重新执行试一试。
本地包默认在 ~/.paddlespeech/models

**Comment by jackeymango** [comment]
遇到相同问题，安装pip包就没有问题，使用源码就有问题

**Comment by jackeymango** [comment]
> 搜索下 asr1_chunk_conformer_u2pp_wenetspeech_ckpt_1.1.3.model.tar 目录中个是否有这个文件。

确实是没有的，需要下载新的模型嘛

**Comment by Zth9730** [comment]
是的，要下载新模型

**Comment by jackeymango** [comment]
> 是的，要下载新模型

删了，再使用源代码下载里面还是没有model.yaml

**Comment by yt605155624** [comment]
[💫 安装 develop 版本的 paddlespeech ](https://github.com/PaddlePaddle/PaddleSpeech/issues/2472)

**Comment by zh794390558** [comment]
chmod +x ~/.paddlespeech/models/*
