### ISSUE TITLE
tts-streaming相关问题请教

### ISSUE THREAD

**Issue by yiluzhuimeng** [PaddlePaddle/PaddleSpeech#2529]
1.介绍中说am-encoder中FFT-block模块没有转化成卷积，但是推理时候是一个音素一个音素进行，这样会对结果造成影响吧？
2.tts-streaming的训练代码有开源吗？
3.VITS如果想做流式模型训练和推理，需要改哪几个模块？
谢谢

**Comment by zh794390558** [comment]
> 1.介绍中说am-encoder中FFT-block模块没有转化成卷积，但是推理时候是一个音素一个音素进行，这样会对结果造成影响吧？

没有影响，你可以校验下输出。

> 2.tts-streaming的训练代码有开源吗？

代码已经开源。

**Comment by yiluzhuimeng** [comment]
你好，不理解fastSpeech2为了做流式处理，am-decoder中FFT-block模块转化成卷积，而am-encoder中FFT-block模块没有转化成卷积，我的理解FFT-block其中包含attention，需要上下文的信息，这样逐个一个音素推理不会对结果造成影响，其中的原理是什么呢、

**Comment by yiluzhuimeng** [comment]
> > 1.介绍中说am-encoder中FFT-block模块没有转化成卷积，但是推理时候是一个音素一个音素进行，这样会对结果造成影响吧？
> 
> 没有影响，你可以校验下输出。
> 
> > 2.tts-streaming的训练代码有开源吗？
> 
> 代码已经开源。


你好，不理解fastSpeech2为了做流式处理，am-decoder中FFT-block模块转化成卷积，而am-encoder中FFT-block模块没有转化成卷积，我的理解FFT-block其中包含attention，需要上下文的信息，这样逐个一个音素推理不会对结果造成影响，其中的原理是什么呢、

**Comment by yt605155624** [comment]
FastSpeech2 流式推理时不是 “逐个一个音素推理”，而是 encoder 的输出 pad 一些上下文信息后进行推理再移除 pad 部分对应的输出，原理是 “CNN 的局部感受野”，参考 [AIStudio Courses](https://aistudio.baidu.com/aistudio/course/introduce/25130) / 第七章：语音合成 / [流式语音合成技术揭秘与实践](https://aistudio.baidu.com/aistudio/education/lessonvideo/3344509) （需要加入课程才能看）

**Comment by panxin801** [comment]
您好 ，请问 VITS如果想做流式模型训练和推理，需要改哪几个模块？ 谢谢您的回复

**Comment by 15755841658** [comment]
@yiluzhuimeng 请问您有将VITS做成流式了吗，需要改哪几个模块？谢谢您的回复

**Comment by panxin801** [comment]
> @yiluzhuimeng 请问您有将VITS做成流式了吗，需要改哪几个模块？谢谢您的回复

您好，后来没有在做这个工作，实在不好意思。

**Comment by yiluzhuimeng** [comment]
VITS 流式合成=== vits解码器也是hifigan，参考paddleSpeech中对于hifigan流式合成的改造，实际上也是对卷积进行改造
