### ISSUE TITLE
[TTS]静态模型转 Paddle-Lite 失败问题汇总

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#2540]
![WechatIMG45](https://user-images.githubusercontent.com/24568452/196322601-fbfe0f51-24c2-4c84-ad89-e68759f9ad99.jpeg)
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2487
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2534 
- https://github.com/PaddlePaddle/Paddle-Lite/issues/9556
- https://github.com/PaddlePaddle/Paddle-Lite/issues/9563

**Comment by LiuChiachi** [comment]
Paddle-Lite
