### ISSUE TITLE
[S2T] ASR : 多卡训练aishell数据报错：'RelPositionMultiHeadedAttention' object has no attribute 'weight'

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2541]
**具体报错信息如下：**
![image](https://user-images.githubusercontent.com/27938135/196336381-7bf0fb1e-5d0d-4997-bbd9-0d0a30888a7b.png)
![image](https://user-images.githubusercontent.com/27938135/196336418-203250ed-299d-4650-9ec4-b458e67edfb8.png)
**我的paddle版本是这个：**
![image](https://user-images.githubusercontent.com/27938135/196336457-4ee1ebb1-6ed0-4117-80f7-410d0b67ec4b.png)
**请问这个报错是什么情况？**

**Comment by zh794390558** [comment]
我们在check这个问题。
