### ISSUE TITLE
paddlespeech paddlenlp报错

### ISSUE THREAD

**Issue by laity-slf** [PaddlePaddle/PaddleSpeech#2550]
## General Question

当我使用python=3.7.12 ，paddlepaddle版本为2.0.2，会报错。
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/59203496/196607174-98b7cddf-a603-4e32-b1e6-21f28a481b27.png">
是asr不支持这个版本的paddle吗

**Comment by yt605155624** [comment]
请安装安装文档安装指定版本的 paddle 版本，目前要求 paddle 2.4.0rc https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md

**Comment by laity-slf** [comment]
但是我现在的gpu因为 cuda driver的原因只能用这个版本的paddle。因为没有权限装driver=-=

**Comment by yt605155624** [comment]
哦，那可能就用不了了，可以在 aistudio 上试用
