### ISSUE TITLE
[S2T]AIstudio中DeepSpeech2教程的demo无法正常运行

### ISSUE THREAD

**Issue by ykx123-hub** [PaddlePaddle/PaddleSpeech#2557]
https://aistudio.baidu.com/aistudio/course/introduce/25130 
该教程中语音识别的DeepSpeech2的demo无法正常运行，出现的错误的具体代码段如下：
![微信图片_20221019224727](https://user-images.githubusercontent.com/74460795/196724940-f9d500c6-cf97-40b2-ae84-e504abc72277.jpg)
![微信图片_20221019224735](https://user-images.githubusercontent.com/74460795/196725032-b3733ed7-cce1-4490-947b-bd356db4ad67.jpg)
经检查，发现下载下来的deepspeech2.yaml配置文件中没有rnn_direction、num_fc_layers、fc_layers_size_list, 这个该如何解决？

**Comment by zh794390558** [comment]
修复了一个问题，教程可以跑了。你那儿应该更新下版本就可以跑了。

**Comment by cailuyu** [comment]
我这里还是有一模一样的问题,调整了下载的模型吗?我用的这个 https://paddlespeech.bj.bcebos.com/s2t/aishell/asr0/ds2.model.tar.gz 项目clone的最新分支
