### ISSUE TITLE
字音转换问题

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2560]
![image](https://user-images.githubusercontent.com/108966996/196894299-3878b33c-4970-4751-b1e6-25f74b5184e9.png)
![image](https://user-images.githubusercontent.com/108966996/196895228-f21269b2-0bbe-4df9-a8cf-e47fe986345d.png)

为什么w变成了u
![image](https://user-images.githubusercontent.com/108966996/196894808-5a4e7b9b-85b6-4dc7-9a69-5018ea8f8b1b.png)
![image](https://user-images.githubusercontent.com/108966996/196895228-f21269b2-0bbe-4df9-a8cf-e47fe986345d.png)

为什么yun4变成了vn4，zhi1为什么变成了zh iii
还有就是韵律符号怎么也没有了呢

**Comment by yt605155624** [comment]
1. 我们只用了原始数据集的拼音，没有用韵律
2. 关于 g2p 字典设计请参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/topic/frontend/g2p.md

**Comment by Lux-maker-harsh** [comment]
> 1. 我们只用了原始数据集的拼音，没有用韵律
> 2. 关于 g2p 字典设计请参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/topic/frontend/g2p.md
请问整理之后声母为什么和原数据集不一样呢

**Comment by AlphaMind123** [comment]
> 1. 我们只用了原始数据集的拼音，没有用韵律
> 2. 关于 g2p 字典设计请参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/topic/frontend/g2p.md

好的谢谢
