### ISSUE TITLE
多说话人数据集用于TTS

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/PaddleSpeech#2561]
请问一下：在用多说话人的数据集做TTS时与单一说话人的数据集有什么区别，是将各个speaker的语音分开像单一的speaker一样进行训练吗，在测试的时候合成哪个speaker的音色是不是可以设置的

**Comment by yt605155624** [comment]
多说话人训练和测试时用 `spk_id` 标志不同的说话人，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3

**Comment by AlphaMind123** [comment]
ok,thank you


| |
hfqemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月20日 18:22 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleSpeech] 多说话人数据集用于TTS (Issue #2561) |

多说话人训练和测试时用 spk_id 标志不同的说话人，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3
