### ISSUE TITLE
MacOS调用paddleSpeech_server报错

### ISSUE THREAD

**Issue by Hezzle** [PaddlePaddle/PaddleSpeech#2562]
<img width="1440" alt="截屏2022-10-19 下午9 56 38" src="https://user-images.githubusercontent.com/116180233/196980808-fbb1ae0f-7701-4f0a-9123-504593e354f2.png">

MacOS按照gitee上简单模式安装，在启动服务时路径明明正确，但是出现了上图的报错
paddlespeech_server start --config_file ./PaddleSpeech-develop/demos/speech_server/conf/application.yaml
paddlespeech_server start ./PaddleSpeech-develop/demos/speech_server/conf/application.yaml
最终都失败了
（萌新，不是很懂python，求指教）

**Comment by lym0302** [comment]
简单安装方式使用的 pip install paddlespeech 的形式吗？如果是这样的话，首先根据我们的示例自己新建一个application.yaml，然后使用指令 paddlespeech_server start --config_file <application.yaml的路径> 就可以启动了。

**Comment by yt605155624** [comment]
@Kurast703 相关报错请自己百度、谷歌搜索解决
