### ISSUE TITLE
fastspeech 等声学模型、Multi_band MelGAN等声码器流式与非流式模型的参数量，计算量区别？端侧相关

### ISSUE THREAD

**Issue by Xsx93** [PaddlePaddle/PaddleSpeech#2564]
## General Question
如题，流式模型在端侧部署时，是否会有更低的计算量，或者有更好的效果，有没有数据佐证。

**Comment by yt605155624** [comment]
关于参数量计算量您可以自己算，流式推理方式会 padding 一些前后 block 的数据，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_tts_server

目前还没有打通端侧部署，会在 Q4 尝试相关的工作 🤝
