### ISSUE TITLE
style_fs2 怎么由单人改多人？希望能有个小demo参考一下，谢谢

### ISSUE THREAD

**Issue by thehzzz** [PaddlePaddle/PaddleSpeech#2569]
style_fs2 怎么由单人改多人？希望能有个小demo参考一下，谢谢

**Comment by thehzzz** [comment]
希望能使用中英mix模型

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3/tts3
不会出 demo，请自己参考多说话人 TTS 改吧，只是多了一个 spk_id 的输入而已。

**Comment by SG-XM** [comment]
> style_fs2 怎么由单人改多人？希望能有个小demo参考一下，谢谢

想问你是否成功了,我改成多人后长句一直OOM
