### ISSUE TITLE
流式asr服务启动报错AttributeError: num_decoding_left_chunks

### ISSUE THREAD

**Issue by ShawnyinsGit** [PaddlePaddle/PaddleSpeech#2572]
流式asr服务启动报错AttributeError: num_decoding_left_chunks
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30432137/197335817-9898b704-c852-44d1-ba8f-bc362e9c6b8e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30432137/197336040-91037d71-3e21-4604-9d69-496461bcf0cf.png">

课程的配置文件示例也没有num_decoding_left_chunks字段
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/30432137/197335934-6c5d4a74-2ab6-43a9-b5fc-acfa084ce4a0.png">

paddlepaddle: 2.4.0rc0
python:3.8

**Comment by yt605155624** [comment]
是 paddlespeech 不兼容升级导致的，https://github.com/PaddlePaddle/PaddleSpeech/pull/2337 已修复，aistudio 教程近两天会修复
