### ISSUE TITLE
[TTS]example/aishell3/tts3 自己的数据集训练synthesize_e2e出来没有声音

### ISSUE THREAD

**Issue by HandsLing** [PaddlePaddle/PaddleSpeech#2574]
请问在example/aishell3/tts3 中，我用aishell3数据集训练没有问题，但是我用我自己的数据训练，不报错，但是推理出来的音频没有声音，只有 “”enenen“”的声音，请问这是怎么回事呢

**Comment by yt605155624** [comment]
请检查 
1. synthesize 时是否可以正常合成吗，如果可以证明训练的模型没有问题
2. synthesize_e2e 时候输入的 phone_id_map.txt 和训练时是否一致

**Comment by HandsLing** [comment]
不好意思，是我这边没有把phone_id_map.txt这个路径给对导致的问题，换了正确的路劲就没问题了，谢谢
