### ISSUE TITLE
语音识别可以同时识别多个文件吗

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2578]
想问一下怎么批量识别多个音频文件

**Comment by zh794390558** [comment]
参看 https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-CLI---Batch-Process

**Comment by oyb1125** [comment]
> 参看 https://github.com/PaddlePaddle/PaddleSpeech/wiki/PaddleSpeech-CLI---Batch-Process

好的，谢谢
