### ISSUE TITLE
TTS, 小样本合成项目用BML Colab运行出现bug

### ISSUE THREAD

**Issue by Plutoisme** [PaddlePaddle/PaddleSpeech#2579]
按照https://aistudio.baidu.com/aistudio/projectdetail/4573549?channelType=0&channel=0 上Paddle开源的项目，打开BML Colab进行复现。在GE2E语音生成模块前端出现bug:

{'code': -1, 'result': None, 'message': '克隆失败，检查克隆脚本是否有效'}

此时后端显示：

python3 /home/aistudio/PaddleSpeech/paddlespeech/t2s/exps/voice_cloning.py                     --am=fastspeech2_aishell3                     --am_config=source/model/fastspeech2_nosil_aishell3_vc1_ckpt_0.5/default.yaml                     --am_ckpt=source/model/fastspeech2_nosil_aishell3_vc1_ckpt_0.5/snapshot_iter_96400.pdz                     --am_stat=source/model/fastspeech2_nosil_aishell3_vc1_ckpt_0.5/speech_stats.npy                     --voc=pwgan_aishell3                     --voc_config=source/model/pwg_aishell3_ckpt_0.5/default.yaml                     --voc_ckpt=source/model/pwg_aishell3_ckpt_0.5/snapshot_iter_1000000.pdz                     --voc_stat=source/model/pwg_aishell3_ckpt_0.5/feats_stats.npy                     --ge2e_params_path=source/model/ge2e_ckpt_0.3/step-3000000.pdparams                     --text="欢迎使用飞桨语音套件"                     --input-dir=/home/aistudio/PaddleSpeech/demos/speech_web/speech_server/tmp_dir/ge2e                     --output-dir=source/wav/vc/out                     --phones-dict=source/model/fastspeech2_nosil_aishell3_vc1_ckpt_0.5/phone_id_map.txt                     --ngpu=1
        
运行结果： 139
INFO:     127.0.0.1:41752 - "POST /vc/clone_g2p HTTP/1.1" 200 OK

**Comment by iftaken** [comment]
项目没有问题啊，使用最新的代码项目从头到尾跑了一遍，可以正常运行呀，确定是在Aistudio环境下运行且前面的代码都运行正常了吗？
![image](https://user-images.githubusercontent.com/30135920/197536766-1d32f8ad-6309-4547-9e3a-2a6e1bb75f03.png)
