### ISSUE TITLE
paddlespeech_server asr 有没有办法可以降低GPU内存的使用啊？

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/PaddleSpeech#2581]
paddlespeech_server asr 有没有办法可以降低GPU内存的使用啊？

我已经修改了application.yml 中只用 engine_list: ['asr_python']
conformer_wenetspeech 模型占用内存较高2.6G，我在笔记本上做应用gpu内存有限。
预测的时候是否有可能精度减少不多前提下，精度gpu 内存使用？

如果用cpu 预测太慢了，2S以上无法接受

**Comment by zh794390558** [comment]
目前没有什么好的方法。

**Comment by jeffzhengye** [comment]
@zh794390558  quant.py 你有试过吗？ 
如果试过，大概性能有多大影响？

**Comment by zh794390558** [comment]
> @zh794390558 quant.py 你有试过吗？ 如果试过，大概性能有多大影响？

这部分还没有完全验证好，预计CPU上全流程的RTF在~0.5左右。
