### ISSUE TITLE
声音克隆单句话克隆效果很差

### ISSUE THREAD

**Issue by liangwq** [PaddlePaddle/PaddleSpeech#2583]
任务：https://aistudio.baidu.com/bj-gpu-02/user/997789/4888326/lab/tree/PaddleSpeech/demos/speech_web/speech_server/src/finetune.py
具体问题描述：
用3秒西游记中猴哥声音做克隆，效果很差
用小样本fintune教程不够详细，没有跑成功
感觉问题应该是声纹抽取、声音编码器迁移效果不够好

**Comment by yt605155624** [comment]
一句话克隆效果不如 finetune

finetune 可以直接用源码试试：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3
文档可以在看之前的直播课 [AIStudio Courses](https://aistudio.baidu.com/aistudio/course/introduce/25130)
效果可以看之前开发者的讨论：https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842

**Comment by liangwq** [comment]
用自己的语音数据，如何对齐生成可以进模型finetune的格式
是需要一个脚本处理还是怎么弄，是否可以给个教程

**Comment by yt605155624** [comment]
@liangwq 参考上述第一个链接，教程就是上面的链接 ：）， MFA 的对齐过程脚本自动进行，你只需要准备 wav 文件和对应 label 文件，文件格式链接里面都有

**Comment by liangwq** [comment]
![image](https://user-images.githubusercontent.com/9170648/198187908-b7ae153b-1bb2-4284-a2e0-277c6d3149d2.png)
单条数据finetune，抽特征部分好像出问题了
这个要怎么解决
