### ISSUE TITLE
asr性能、动转静问题

### ISSUE THREAD

**Issue by beingjoey** [PaddlePaddle/PaddleSpeech#2584]
请问项目中的ASRExecutor，是静态的还是动态的？现在是想提升一下性能有什么方法？

**Comment by zh794390558** [comment]
ds2有静态的，u2是动态的。
可以试试https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/speechx/examples/u2pp_ol/wenetspeech/README.md，具体看speechx里的文档。

**Comment by zh794390558** [comment]
u2/u2++ asr c++部署已经完成了，可以测试下： https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/speechx/examples/u2pp_ol/wenetspeech/RESULTS.md

**Comment by wqn1** [comment]
您好，u2模型动转静，现在的paddlespeech支持吗？

**Comment by wqn1** [comment]
> u2/u2++ asr c++部署已经完成了，可以测试下： https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/speechx/examples/u2pp_ol/wenetspeech/RESULTS.md

您好，现在u2模型动转静，paddlespeech支持吗？
