### ISSUE TITLE
为什么使用ERNIE-SAT声音克隆，从中文生成的英文语音完全听不懂？

### ISSUE THREAD

**Issue by guo453585719** [PaddlePaddle/PaddleSpeech#2586]
您好，我正在尝试https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3_vctk/ernie_sat的声音克隆，发现使用我自己的中文语音生成的英文语音完全听不懂，和乱码一样。

我的输入是：
--old_str="除此之外，在看电影生肉时，中文字幕搭配中文原声，让你更加声临其境。"
--new_str="In addition, when watching the movie raw meat, Chinese subtitles with the Chinese original sound, let you more immersive."

我打印了synthesize_e2e.py中的with_dur_outs，并没有发现什么问题：
with_dur_outs:{'new_wav': array([0., 0., 0., ..., 0., 0., 0.], dtype=float32), 'new_phns': ['sp', 'ch', 'u2', 'c', 'ii3', 'zh', 'iii1', 'uai4', 'sp', 'z', 'ai4', 'k', 'an4', 'd', 'ian4', 'ing3', 'sh', 'eng1', 'r', 'ou4', 'sh', 'iii2', 'sp', 'zh', 'ong1', 'uen2', 'z', 'ii4', 'm', 'u4', 'd', 'a1', 'p', 'ei4', 'zh', 'ong1', 'uen2', 'van2', 'sh', 'eng1', 'sp', 'r', 'ang4', 'n', 'i3', 'g', 'eng4', 'j', 'ia1', 'sh', 'eng1', 'l', 'in2', 'q', 'i2', 'j', 'ing4', 'sp', 'IH0', 'N', 'AH0', 'D', 'IH1', 'SH', 'AH0', 'N', 'W', 'EH1', 'N', 'W', 'AA1', 'CH', 'IH0', 'NG', 'DH', 'AH0', 'M', 'UW1', 'V', 'IY0', 'R', 'AA1', 'M', 'IY1', 'T', 'CH', 'AY0', 'N', 'IY1', 'Z', 'S', 'AH1', 'B', 'T', 'AY2', 'T', 'AH0', 'L', 'Z', 'W', 'IH1', 'DH', 'DH', 'AH0', 'CH', 'AY0', 'N', 'IY1', 'Z', 'ER0', 'IH1', 'JH', 'AH0', 'N', 'AH0', 'L', 'S', 'AW1', 'N', 'D', 'L', 'EH1', 'T', 'Y', 'UW1', 'M', 'AO1', 'R', 'spn'], 'new_mfa_start': [0, 75, 84, 91, 102, 109, 116, 120, 163, 168, 183, 196, 210, 222, 232, 249, 253, 263, 270, 279, 288, 300, 327, 345, 356, 370, 379, 387, 394, 404, 416, 425, 437, 448, 459, 468, 481, 493, 511, 522, 551, 569, 575, 588, 594, 604, 610, 620, 627, 648, 660, 671, 675, 689, 706, 711, 719, 741, 767, 779, 788, 800, 812, 824, 841, 850, 862, 871, 878, 894, 905, 926, 943, 949, 960, 966, 975, 989, 1006, 1017, 1034, 1050, 1064, 1080, 1099, 1105, 1122, 1146, 1157, 1174, 1190, 1206, 1217, 1226, 1243, 1259, 1268, 1275, 1287, 1303, 1314, 1320, 1331, 1338, 1347, 1364, 1383, 1392, 1408, 1425, 1449, 1458, 1470, 1476, 1482, 1489, 1500, 1526, 1547, 1556, 1562, 1576, 1587, 1601, 1610, 1624, 1635, 1644, 1653], 'new_mfa_end': [75, 84, 91, 102, 109, 116, 120, 163, 168, 183, 196, 210, 222, 232, 249, 253, 263, 270, 279, 288, 300, 327, 345, 356, 370, 379, 387, 394, 404, 416, 425, 437, 448, 459, 468, 481, 493, 511, 522, 551, 569, 575, 588, 594, 604, 610, 620, 627, 648, 660, 671, 675, 689, 706, 711, 719, 741, 767, 779, 788, 800, 812, 824, 841, 850, 862, 871, 878, 894, 905, 926, 943, 949, 960, 966, 975, 989, 1006, 1017, 1034, 1050, 1064, 1080, 1099, 1105, 1122, 1146, 1157, 1174, 1190, 1206, 1217, 1226, 1243, 1259, 1268, 1275, 1287, 1303, 1314, 1320, 1331, 1338, 1347, 1364, 1383, 1392, 1408, 1425, 1449, 1458, 1470, 1476, 1482, 1489, 1500, 1526, 1547, 1556, 1562, 1576, 1587, 1601, 1610, 1624, 1635, 1644, 1653, 1785], 'old_span_bdy': [767, 767], 'new_span_bdy': [767, 1785]}

我的操作应该没有问题，因为我尝试从英文语音克隆生成中文语音是成功的，虽然音色不太像，但是合成的语音质量很不错。我不知道为什么中文克隆到英文就失败，请问您能帮下我嘛？

**Comment by guo453585719** [comment]
抱歉，超链接有点问题，我尝试的是https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell3_vctk/ernie_sat#ernie-sat-with-aishell-3-and-vctk-dataset

**Comment by 2022vvvtest** [comment]
我也尝试了这个模型，输入中文语音克隆英文语音，发现生成的英文基本不对，借楼请教一下哪里出问题了。另外ERNIE-SAT可以在给出的模型上进行微调训练吗，如果可以的话大概每个音色需要多少音频

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/294d83da82be1a16b85d5710bcf5289f80fc791b/examples/aishell3_vctk/ernie_sat/local/synthesize_e2e.sh#L32 这个你们能跑通么，有没有可能是你们自己输入的参数有问题之类的 @guo453585719 @2022vvvtest 

另外 ENIE-SAT 输入太长的新文本效果不好这是存在的，可以先用短文本试试

ERNIE-SAT 微调没有做过，肯定是可以微调的，但是多少音频无法给出经验

**Comment by guo453585719** [comment]
感谢回复！./run.sh --stage 1 --stop-stage 1 可以正常跑通，训练没问题

[2022-10-27 19:14:10] [INFO] [trainer.py:167]  iter: 1/3918000, Rank: 0, text_mlm_loss: 5.941202, mlm_loss: 125.065460, loss: 131.006668, lr: 2.0171788261496964e-07, avg_reader_cost: 0.46887 sec, avg_batch_cost: 58.62713 sec, avg_samples: 40, avg_ips: 0.68228 sequences/sec
[2022-10-27 19:16:12] [INFO] [trainer.py:167]  iter: 2/3918000, Rank: 0, text_mlm_loss: 5.953725, mlm_loss: 135.143066, loss: 141.096786, lr: 4.034357652299393e-07, avg_reader_cost: 0.00038 sec, avg_batch_cost: 122.12054 sec, avg_samples: 40, avg_ips: 0.32755 sequences/sec
[2022-10-27 19:16:42] [INFO] [trainer.py:167]  iter: 3/3918000, Rank: 0, text_mlm_loss: 5.940707, mlm_loss: 120.987595, loss: 126.928299, lr: 6.051536478449089e-07, avg_reader_cost: 0.00038 sec, avg_batch_cost: 29.94240 sec, avg_samples: 40, avg_ips: 1.33590 sequences/sec

**Comment by yt605155624** [comment]
@guo453585719 请你仔细看我的回复，我说的不是训练

**Comment by guo453585719** [comment]
实在不好意思，看错文件了。synthesize_e2e.sh里面的if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; 是可以跑通的，生成的wav文件也是ok的，我还尝试更换了其他new_str，也可以生成正确的英语语音。

仅仅在克隆我自己和我朋友的英文语音时遇到了上述问题。

**Comment by guo453585719** [comment]
我尝试更换了不同的声码器，hifigan_vctk、pwgan_aishell3等，还是同样的问题

**Comment by yt605155624** [comment]
因为 synthesize_e2e.sh 里面的音频是训练集里面的，而你自己的声音不在训练集里，所以可能效果不好

**Comment by guo453585719** [comment]
emmmm，我自己的声音不在训练集里会导致克隆的音色不相似，这个我理解，我不太明白的是为什么无法合成正常的语音，现在合成出的英文语音完成听不出来任何单词，只是一些无意义音节的组合。而且很诡异的是，英到中的克隆是ok的，虽然音色不太像，但合成的中文语音质量很不错

**Comment by yt605155624** [comment]
我没有做过相关尝试，可以通过以下方式进行 debug
1. 尝试输入较短的句子，因为长句效果不好符合预期
2. 打印输入的句子的音素对不对
3. 检查 phone_id_map.txt 是否正确，即输入给模型的 phone_id 和所需的音素是否真的匹配

**Comment by guo453585719** [comment]
好的，非常感谢你的建议，我尝试下(^o^)／

**Comment by 2022vvvtest** [comment]
感谢回复！ERNIE-SAT的微调方法可以参考其它模型的教程进行（比如TTS3对multi-speaker数据进行微调），还是说需要自行修改ERNIE-SAT下train.sh里的代码进行微调

**Comment by yt605155624** [comment]
@2022vvvtest 可以参考tts3的，train.sh 不用改吧，一般是对自己的数据预处理一下
