### ISSUE TITLE
speech_web的web_client前端启动失败

### ISSUE THREAD

**Issue by treya-lin** [PaddlePaddle/PaddleSpeech#2589]
Hi I have followed the instructions in https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/speech_web and installed npm, nodejs and yarn.  I started the voice cloning service at the speech server end, and it worked fine with API, but I failed to start it at the web client end

```
PaddleSpeech/demos/speech_web/web_client$ yarn dev --port 8011
yarn run v1.22.19
$ vite --port 8011
/bin/sh: 1: vite: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is there any step missing?

**Comment by iftaken** [comment]
Make sure you have run `yarn install` to install dependencies
```bash
yarn install
```
if that doesn't work, you can try installing vite separately

```bash
yarn add vite
```
