### ISSUE TITLE
TTS英语g2p转换的问题

### ISSUE THREAD

**Issue by binbinxue** [PaddlePaddle/PaddleSpeech#2592]
## General Question

在你们群里面问过, 英语语料训练数据用到MFA的话用english_us_arpa的g2p产生的phoneme set和front end用g2p_en的phoneme set有区别, g2p_en有额外的'UW'. 还有一个问题就是，MFA对text的处理和g2p_en处理不一样，同样的词，没有多音的词，MFA产生的phonemes和g2p_en产生的phonemes不一样。它们对于punctuation的处理也不一样。比如 I'm 的话g2p_en会把它分成 I am两个词来产生phonemes, 而MFA不会。还有括号，以及其他punctuations
另外，你们的代码用MFA 1.x记得是假设phoneme sequence前后都会有silence, MFA 2.x不一定会产生leading/trailing silences. 我试了一下改它们的silence probability参数，结果是一样的。
不影响跑通训练，我觉得有可能会影响合成质量

**Comment by yt605155624** [comment]
PaddleSpeech 重点不在英文合成，所以没有过多关注英文 g2p，如果有什么可以改进的地方欢迎提交 pr

**Comment by binbinxue** [comment]
好的，我明白，谢谢！
