### ISSUE TITLE
请问fastspeech2声学模型中的while算子是在fastspeech2代码中哪个模块呢？

### ISSUE THREAD

**Issue by dzcmingdi** [PaddlePaddle/PaddleSpeech#2604]
## General Question

我想了解下while算子里面的具体内容，但是我在代码中找不到while算子。

![截图 2022-11-01 10-08-13](https://user-images.githubusercontent.com/37565801/199143162-6ffb51a0-e7ed-4487-96c9-d6ec717418e6.png)

**Comment by yt605155624** [comment]
导出的静态模型是 while 不代表动态图代码也是用 while 写的，位置是 https://github.com/PaddlePaddle/PaddleSpeech/blob/8ea289a2517aa842ff4c7797f382832cfe13b187/paddlespeech/t2s/modules/predictor/length_regulator.py#L85 你可以对比上下的算子看看

**Comment by dzcmingdi** [comment]
> 也是用 while 写的，位置是 https://github.com/PaddlePaddle/PaddleSpeech/blob/8ea289a2517aa842ff4c7797f382832cfe13b187/paddlespeech/t2s/modules/predictor/length_regulator.py#L85 你可以对比上下的算子看看

感谢感谢
