### ISSUE TITLE
in paddlespeech/cls/exps/panns/deploy/predict.py   from paddleaudio.features import melspectrogram error

### ISSUE THREAD

**Issue by wayneck** [PaddlePaddle/PaddleSpeech#2605]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).
In paddlespeech/cls/exps/panns/deploy/predict.py  file
`import numpy as np
from paddle import inference
from paddleaudio.backends import load as load_audio
from paddleaudio.datasets import ESC50
**from paddleaudio.features import melspectrogram**
from scipy.special import softmax`
the melspectrogram is error import, 
when in 'PaddleSpeech/examples/esc50/cls0' dir 
run  './run.sh 4 cpu ./export /audio/dog.wav'
got 
`--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1101 10:49:58.253744 1347346 analysis_predictor.cc:714] ======= optimize end =======
I1101 10:49:58.253801 1347346 naive_executor.cc:98] ---  skip [feed], feed -> x
I1101 10:49:58.254617 1347346 naive_executor.cc:98] ---  skip [linear_4.tmp_1], fetch -> fetch
['/home/wayne/audio/dog.wav']
W1101 10:49:58.256059 1347346 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.2
W1101 10:49:58.257632 1347346 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "/home/wayne/project/baidu/PaddleSpeech/paddlespeech/cls/exps/panns/deploy/predict.py", line 143, in <module>
    results = predictor.predict(wavs)
  File "/home/wayne/project/baidu/PaddleSpeech/paddlespeech/cls/exps/panns/deploy/predict.py", line 119, in predict
    feats = extract_features(wavs)
  File "/home/wayne/project/baidu/PaddleSpeech/paddlespeech/cls/exps/panns/deploy/predict.py", line 57, in extract_features
    feat = MelSpectrogram(waveforms[i], sr, **kwargs).transpose()
  File "/home/wayne/.local/lib/python3.8/site-packages/paddleaudio/features/layers.py", line 145, in __init__
    self.fbank_matrix = compute_fbank_matrix(
  File "/home/wayne/.local/lib/python3.8/site-packages/paddleaudio/functional/functional.py", line 179, in compute_fbank_matrix
    fftfreqs = fft_frequencies(sr=sr, n_fft=n_fft, dtype=dtype)
  File "/home/wayne/.local/lib/python3.8/site-packages/paddleaudio/functional/functional.py", line 145, in fft_frequencies
    return paddle.linspace(0, float(sr) / 2, int(1 + n_fft // 2), dtype=dtype)`
import change to 
‘from paddleaudio.compliance.librosa import melspectrogram’
then can work.

**Comment by yt605155624** [comment]
please use `paddleaudio==1.0.1` then the script before change can work

by the way, https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/cls/exps/panns/deploy/predict.py we are using `paddlespeech.audio` now, which version of PaddleSpeech script are you using now?

**Comment by wayneck** [comment]
I also use paddlespeech.audio
git log is
`
commit 4b3f6c615ebb77a3577e552d34339a85e3de73b5 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 38eb3361 b1ef4349
Author: Hui Zhang <zhtclz@foxmail.com>
Date:   Wed May 18 15:49:09 2022 +0800

    Merge pull request #1913 from Honei/timelimit
    
    [asr][server]add asr time limt configuration

commit 38eb3361f41c0b6323644dd72734e1723aa85f4b
Merge: fb4d255f 61e4b44b
Author: TianYuan <white-sky@qq.com>
Date:   Wed May 18 13:05:41 2022 +0800

    Merge pull request #1918 from Jackwaterveg/develop
`

**Comment by wayneck** [comment]
I also use paddlespeech.audio

**Comment by yt605155624** [comment]
oh, the commit is too old for now, so `paddleaudio==1.0.1` is well
