### ISSUE TITLE
[TTS]一键微调功能问题

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2607]
使用默认示例点击一键微调，终端微调完成，但是界面还是一直在微调中，前端控制台也有报错
![2022-11-01 15-15-23屏幕截图](https://user-images.githubusercontent.com/62881198/199179417-929a9b62-12b0-496f-89cc-0bcda9e19e8c.png)

**Comment by iftaken** [comment]
从后端的结果来看，并没有运行成功，如果正常开始 finetune 的话会有不同阶段的展示，比如进入训练流程，会显示step，loss等信息，请先检查环境配置是否配置正确，比如预训练模型是否下载，相应的文件是否放在正确，环境中是否有GPU环境。 后台中 finetune 使用的 cmd 执行命令行，无法显示详细的报错信息，你可以后端打印的命令单独在命令行中执行查看详细的报错信息。

你也可以在 Aistudio 中体验，建议使用V100GPU 体验
【PaddleSpeech进阶】PaddleSpeech小样本合成方案体验：https://aistudio.baidu.com/aistudio/projectdetail/4573549?sUid=2470186&shared=1&ts=1667287672428 

对比这个项目中 `env.sh` 检查自己的环境是否配置正确

**Comment by wmlgl** [comment]
下了模型吗
