### ISSUE TITLE
文件下载到电脑失败

### ISSUE THREAD

**Issue by yunqi777** [PaddlePaddle/PaddleSpeech#2609]
我从aistudio上下载我训练好的模型，但是下载一会儿就会断开
我不是打包下载，而是把文件转为压缩包之后再下载
请问各位大佬有没有什么更好的办法能稳定下载呢？

**Comment by lilith-zy** [comment]
您好，抱歉给您的使用带来不便，目前由于下载机制限制，当下载速度过低时会自动终止任务，为了保证您的文件顺利下载，建议您将文件切分为200M 大小分开下载。之后我们将尽快完善相关功能，给大家带来更好的下载体验。
