### ISSUE TITLE
请问ASR支持多个音频文件的并行处理吗？没看到例子，模型应该是支持的吧？需求是大量音频文件，想把GPU跑满。

### ISSUE THREAD

**Issue by linuxnms** [PaddlePaddle/PaddleSpeech#2612]

**Comment by oyb1125** [comment]
支持 参考这个#2578

**Comment by zh794390558** [comment]
可以参考训练里的流程执行batch test，参考https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/aishell/asr1/local/test.sh

**Comment by zh794390558** [comment]
已经实现了c++ cpu的推理，可以参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/speechx/examples/u2pp_ol/wenetspeech/README.md

**Comment by dsyrock** [comment]
请问如果在python里进行多个音频文件识别的话，这样写是对的吗？
> asr = ASRExecutor()
result1 = asr(audio_file=file1)
result2 = asr(audio_file=file2)
