### ISSUE TITLE
GPU又爆炸了(悲)

### ISSUE THREAD

**Issue by yunqi777** [PaddlePaddle/PaddleSpeech#2613]
cuda11.2
![image](https://user-images.githubusercontent.com/110005064/199388757-62ca4ce7-25ee-409b-a799-c066f6ce77a7.png)
时好时坏，怎么会这样呢？

**Comment by yunqi777** [comment]
![N0K~QBSVEI2MUK)B`SA5$OO](https://user-images.githubusercontent.com/110005064/199395261-7143e244-a80d-47bf-aafc-4585ad01d603.png)

**Comment by yt605155624** [comment]
please check https://github.com/PaddlePaddle/PaddleSpeech/issues/2599#issuecomment-1298250248
