### ISSUE TITLE
win 10系统 anaconda 安装paddlespeech webrtcvad报错，vs 2022社区版已安装

### ISSUE THREAD

**Issue by longwangtang** [PaddlePaddle/PaddleSpeech#2616]
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      copying webrtcvad.py -> build\lib.win-amd64-cpython-37
      running build_ext
      building '_webrtcvad' extension
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      creating build\temp.win-amd64-cpython-37\Release\cbits
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio\signal_processing
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio\vad
      D:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -ID:\Anaconda3\envs\paddlepaddle\include -ID:\Anaconda3\envs\paddlepaddle\Include -ID:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\ATLMFC\include -ID:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\include /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-cpython-37\Release\cbits\pywebrtcvad.obj
      pywebrtcvad.c
      D:\Anaconda3\envs\paddlepaddle\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'D:\\VisualStudio\\IDE\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
  Running setup.py clean for webrtcvad
Failed to build webrtcvad
Installing collected packages: webrtcvad, timer, textgrid, sentencepiece, opencc, jieba, flatbuffers, distance, braceexpand, appdirs, xxhash, win32-setctime, Werkzeug, websockets, typeguard, tqdm, threadpoolctl, tabulate, sniffio, regex, pyyaml, pypinyin, pydantic, pycryptodome, pybind11, pyarrow, praatio, ppft, pox, portalocker, pattern-singleton, paddle2onnx, onnxruntime, multidict, mock, lxml, llvmlite, kaldiio, jsonlines, joblib, itsdangerous, h5py, h11, g2pM, future, fsspec, frozenlist, filelock, editdistance, dill, cython, colorlog, bottleneck, Babel, audioread, asynctest, async-timeout, yarl, yacs, soundfile, scikit-learn, sacrebleu, responses, pyworld, pypinyin-dict, pooch, paddlespeech-feat, paddlefsl, numba, multiprocess, loguru, inflect, huggingface-hub, click, bce-python-sdk, anyio, aiosignal, uvicorn, starlette, seqeval, resampy, pathos, nltk, nara-wpe, flask, aiohttp, librosa, g2p-en, Flask-Babel, fastapi, visualdl, datasets, paddlenlp, paddlespeech
  Running setup.py install for webrtcvad ... error
  error: subprocess-exited-with-error

  × Running setup.py install for webrtcvad did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running install
      D:\Anaconda3\envs\paddlepaddle\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      copying webrtcvad.py -> build\lib.win-amd64-cpython-37
      running build_ext
      building '_webrtcvad' extension
      creating build\temp.win-amd64-cpython-37
      creating build\temp.win-amd64-cpython-37\Release
      creating build\temp.win-amd64-cpython-37\Release\cbits
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio\signal_processing
      creating build\temp.win-amd64-cpython-37\Release\cbits\webrtc\common_audio\vad
      D:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_WIN32 -Icbits -ID:\Anaconda3\envs\paddlepaddle\include -ID:\Anaconda3\envs\paddlepaddle\Include -ID:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\ATLMFC\include -ID:\VisualStudio\IDE\VC\Tools\MSVC\14.31.31103\include /Tccbits\pywebrtcvad.c /Fobuild\temp.win-amd64-cpython-37\Release\cbits\pywebrtcvad.obj
      pywebrtcvad.c
      D:\Anaconda3\envs\paddlepaddle\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory
      error: command 'D:\\VisualStudio\\IDE\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> webrtcvad

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by zh794390558** [comment]
建议用docker，或者搜下webrtcvad 怎么安装。

**Comment by dididiskq** [comment]
Building wheels for collected packages: webrtcvad
  Building wheel for webrtcvad (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for webrtcvad (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win32-cpython-38
      copying webrtcvad.py -> build\lib.win32-cpython-38
      running build_ext
      building '_webrtcvad' extension
      C:\Users\user\AppData\Local\Temp\pip-build-env-ojoylx89\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      error: Unable to find a compatible Visual Studio installation.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for webrtcvad
Failed to build webrtcvad
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (webrtcvad)

请教下怎么办，我也是类似问题，
