### ISSUE TITLE
小样本微调方案的采样率问题

### ISSUE THREAD

**Issue by treya-lin** [PaddlePaddle/PaddleSpeech#2632]
## 小样本微调方案的采样率问题

你好，我在学习这个文档来进行小样本微调：https://github.com/PaddlePaddle/PaddleSpeech/tree/7cc1d66863a48b50c2430059c8b84060d84b11a3/examples/other/tts_finetune/tts3
但是我对于微调样本的音频要求有点困惑。我看到提供的csmsc_mini的音频是48000Hz，ljspeech_mini的音频是22050Hz，SSB0005_mini是44100Hz。然后我看到get_duration.py和extract_feature.py里面的采样率写死是24000Hz。请问是底层的代码中已经预先将音频都上采样/降采样到24000Hz来统一处理吗？

我另外准备自己数据时对采样率需要有什么讲究吗？16kHz是不是会自动上采变成24k不会报错，只是可能效果会变差？

谢谢！

**Comment by yt605155624** [comment]
在 default.yaml 里面写死了采样率是 24kHz, 16kHz是会自动上采变成24k不会报错，效果也不会差很多，建议自己的数据最好是采样率大于 24kHz
