### ISSUE TITLE
手撸ASR

### ISSUE THREAD

**Issue by 2017040264** [PaddlePaddle/PaddleSpeech#2635]
## General Question

有没有从0手撸ASR的例子呀，感觉官方给的例子都是用的套件，原理还不太明白，想找个手撸的例子看看

**Comment by zh794390558** [comment]
后面PM会整理些文档。

**Comment by iftaken** [comment]
可以参考[《飞桨PaddleSpeech语音技术课程》](https://aistudio.baidu.com/aistudio/course/introduce/25130?directly=1&shared=1)语音识别部分
