### ISSUE TITLE
AssertionError: choose a window size 400 that is [2, 1]

### ISSUE THREAD

**Issue by dayDreamer5920** [PaddlePaddle/PaddleSpeech#2644]
代码：
import paddle
from paddlespeech.kws.models import MDTC
from paddlespeech.kws.models.mdtc import KWSModel

backbone = MDTC(
    stack_num=3,
    stack_size=4,
    in_channels=80,
    res_channels=32,
    kernel_size=5,
)
model = KWSModel(backbone=backbone, num_keywords=1)
kws_checkpoint = './kws.pdparams'
model.set_state_dict(paddle.load(kws_checkpoint))
model.eval()

import paddleaudio
from paddleaudio.compliance.kaldi import fbank

feat_func = lambda waveform, sr: fbank(
    waveform=paddle.to_tensor(waveform).unsqueeze(0), 
    sr=sr, 
    frame_shift=10, 
    frame_length=25, 
    n_mels=80)

keyword_feat = feat_func(
    *paddleaudio.load('./keyword.wav'))
non_keyword_feat = feat_func(
    *paddleaudio.load('./non-keyword.wav'))
    

print(keyword_feat.shape, non_keyword_feat.shape)

keyword_logits = model(keyword_feat.unsqueeze(0))
keyword_score = paddle.max(keyword_logits).numpy().item()
print(keyword_score)
non_keyword_logits = model(non_keyword_feat.unsqueeze(0))
non_keyword_score = paddle.max(non_keyword_logits).numpy().item()
print(non_keyword_score)

执行结果：
W1112 15:31:06.841100 17938 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.2
W1112 15:31:06.854442 17938 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "test3.py", line 29, in <module>
    keyword_feat = feat_func(
  File "test3.py", line 22, in <lambda>
    feat_func = lambda waveform, sr: fbank(
  File "/home/daydreamer/miniconda3/envs/python3.8/lib/python3.8/site-packages/paddleaudio/compliance/kaldi.py", line 458, in fbank
    waveform, window_shift, window_size, padded_window_size = _get_waveform_and_window_properties(
  File "/home/daydreamer/miniconda3/envs/python3.8/lib/python3.8/site-packages/paddleaudio/compliance/kaldi.py", line 125, in _get_waveform_and_window_properties
    assert 2 <= window_size <= len(waveform), (
AssertionError: choose a window size 400 that is [2, 1]

**Comment by yt605155624** [comment]
应该是你的音频长度太小了，小于了 window size, 可以自己在源码看下报错，应该是这个 
https://github.com/PaddlePaddle/PaddleSpeech/blob/bb7ff288a95a3733828021e0a53e04cf7e2eda28/paddlespeech/audio/compliance/kaldi.py#L125

**Comment by liuying66** [comment]
> 

我也出现了这个报错，用的是heysnips数据集里的音频，一些正样本都只有2-3秒呀？应该怎么改呢

**Comment by Change0028** [comment]
把keyword_logits = model(keyword_feat.unsqueeze(0))改成
keyword_logits = model(keyword_feat)就可以了
