### ISSUE TITLE
paddlespeech-ctcdecoders 这个包的编译步骤有提供吗

### ISSUE THREAD

**Issue by 364378743** [PaddlePaddle/PaddleSpeech#2645]
在arm64环境没有找到相关的依赖包
1.paddlespeech-ctcdecoders支持在arm64下编译后的正常使用吗？
2.如果支持那么编译的步骤有提供相关的文档吗？环境依赖，编译步骤等...

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/discussions/2148
