### ISSUE TITLE
speedyspeech batchnorm的问题

### ISSUE THREAD

**Issue by binbinxue** [PaddlePaddle/PaddleSpeech#2654]
speedyspeech用到batchnorm, 模型的输入是padded phoneme sequence, 如果dataloader没有用到bucketization的话，sample的phoneme sequence length相差会很大。以下的batch norm没有考虑到padding，虽然不影响跑通代码，但是这应该会影响到模型收敛和模型质量吧？
https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/models/speedyspeech/speedyspeech.py#L168

**Comment by yt605155624** [comment]
可以把 sampler 换成 ERNIE-SAT 的 sampler，目的是保持一个 batch 里面的长度尽可能一致（ERNIE-SAT 涉及到 mask 操作，batch 内长度不一致会影响效果）

做法在生成 metadata.jsonl 的时候先按照特征长度排序（我们现在别的模型都是按照 utt_id 排的） , 这样整个 epoch 在不 shuffle 的前提下就是按照特征长度排序的：https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/ernie_sat/normalize.py#L121  然后把 sampler 换成 ERNIE-SAT 的 sampler
https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/ernie_sat/train.py#L89 在 sampler 里面把不同的 batch 进行 shuffle（而不是像原来的 DistributedBatchSampler 一样直接把整个 epoch shuffle），这样 batch 内部还是按照特征长度排序的，但是相邻 batch 的特征长度是   shuffle 的

具体是否影响到模型收敛和模型质量，欢迎实验后反馈结果

**Comment by binbinxue** [comment]
是的，我知道可以这样，我的意思是，按目前的sampling, batch里面的sample sequence length会不一致，然后用一般的batchnorm的话，如果没有考虑到padding, 那就会造成batchnorm计算的statistics不反应真实的statistics. 因为batchnorm会用到所有的time step, 而如果有些sample的time step很小的话，batchnorm事实上是用到了padding的statistics, 就会不准确，对吧？

**Comment by binbinxue** [comment]
> 可以把 sampler 换成 ERNIE-SAT 的 sampler
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/ernie_sat/train.py#L33
> 
> ，目的是保持一个 batch 里面的长度尽可能一致（ERNIE-SAT 涉及到 mask 操作，batch 内长度不一致会影响效果），做法在生成 metadata.jsonl 的时候先按照特征长度排序（我们现在别的模型都是安装 uid 排的）
> https://github.com/PaddlePaddle/PaddleSpeech/blob/f110928195edf5a078f5f621460ac0dcd9e0cc18/paddlespeech/t2s/exps/ernie_sat/normalize.py#L121
> 
> , 然后在 sampler 里面在 batch 内 suffle
> 具体是否影响到模型收敛和模型质量，欢迎实验后反馈结果

好的，如果我做了对比后会把结果放这里

**Comment by yt605155624** [comment]
@binbinxue 有什么可以考虑到 padding 的 batchnorm 的算法可以参考吗？

**Comment by binbinxue** [comment]
我只知道tensorflow的layernorm是可以接受mask的参数，可以reshape后用layernorm加mask做了norm后再换回来
