### ISSUE TITLE
[TTS]aishell3/tts3训练时报错

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2659]
执行./run.sh --stage 1 --stop-stage 1时报错
TypeError: __init__() got an unexpected keyword argument 'enable_spk_cls'
这是什么原因

**Comment by yt605155624** [comment]
@oyb1125 已经解决了嘛？

**Comment by oyb1125** [comment]
> @oyb1125 已经解决了嘛？

解决了
