### ISSUE TITLE
如何实现指定说话人音色的方言TTS？

### ISSUE THREAD

**Issue by guo453585719** [PaddlePaddle/PaddleSpeech#2662]
请问下各位大佬，该怎么实现指定说话人音色的方言TTS？

我尝试了微调tts3的方案，已经实现了说话人A的音色，接下来我该怎么实现让A说出方言呢？是不是直接继续用方言数据集进行微调？方言数据集是由其他说话人录制的，会干扰A的音色吗？

**Comment by yt605155624** [comment]
会，需要 A 说方言的数据才行，否则 finetune 出来的是方言 spk 的音色

**Comment by guo453585719** [comment]
感谢解答！我是否可以通过指定不同的repalce spk来实现我想要的效果呢？比如说第一次finetune将A的音色替换到spk 0，然后换方言数据集继续finetune，此时指定替换spk 1。finetune完成后，fs2应该学会了说方言，然后我在合成声音的时候指定spk 0进行合成，这样可以得到A音色的方言声音。我这个理解正确吗？

**Comment by yt605155624** [comment]
根据之前开发者的反馈，指定 spk_id finetune 确实会影响到别的音色，你可以试下~ 效果我不敢保证 https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842

**Comment by guo453585719** [comment]
好的，非常感谢~
