### ISSUE TITLE
[TTS] 粤语语音合成调研

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/PaddleSpeech#2669]
粤语，又称广东话、广府话、白话。历史比较悠久，粤语是南方方言里面保留中古汉语成分较多的一种。其中最突出的特色就是它较为完整地保留了中古汉语普遍存在的入声，其声母、韵母、声调与古汉语标准韵书《广韵》高度吻合。国学大师南怀谨先生认为粤语是唐代国语。

据说，1911年中华民国成立后，首届国会中有人提议奉广州话为国语；当时来自广东的国会议员刚好过半数，通过这一法案似乎不成问题。不过，身为广东人的临时大总统孙中山为了顾全革命大局，劝说粤籍议员放弃以粤语为国语。结果，北京话以一票之差压倒广州话成为国语。

粤语目前主要分布于广东、 广西、 香港和澳门。
两省区的粤语分为广府、 四邑、 高阳、 勾漏、 吴化、 琶得、 钦廉 7 片。

片区|特点
-- | --
广府 | 是粤语中最具影响、使用人数最多的一片方言, 主要分布于广东珠江三角洲一带, 及广西西江流域上游的部分地区。还有香港、 澳门两个地区，大部分海外粤语区。
四邑 | 主要分布于广东潭江流域的一些地方。
高阳 | 主要分布于粤西南。
吴化 | 主要集中于茂名西南、 湛江以东的海湾地带。
勾漏 | 主要分布于广东西部的清远、 肇庆两市所辖的部分地 区及广西东部地带。
琶得 | 广西壮族自治区的中西部与北部的大多数地区。
钦廉 | 广西壮族自治区东南隅。

广州(广府)话是粤方言区最有 代表性的方言，当然也是大湾区最有代表性的方言，以至于一般人经常把广州话跟粤方言，甚至跟广东话混为一谈。有分城内音（东山口音）、西关口音等等。虽然西关口音被视为标准广州话口音，但现在依《广州音字典》所收字音来看，并没有专门视西关口音为主收对象，而是以当前珠三角广府人通用口音为标准。

### 港澳地区与广州粤语的区别([Ref](https://www.zhihu.com/question/20663233))
总的来说差别不大。有些差异只表现在“使用频率”上，有些则表现在“年龄层次”上，如一些香港人使用的外语借词，广州的中老年人可能听不懂，年轻 人则能听懂一部分或接近全能听懂，而一些香港人现仍使用的‘旧词’，广州的老年人则可能比年轻 人较能理解一些。

1. 腔调的区别：由于香港人成份复杂，移民众多，由此产生不少变化。比如，懒音很重，经常前后鼻音、l和n不分，声调比较高，听起来自带温柔的调性，最适合用来唱情深款款的情歌，这也是为什么香港流行歌的传唱度会特别高。
2. 部分字发音不同：上世纪70年代，香港的官方语言定为“广州粤语”，表示要有西关口音。然而在当时，香港中文大学的何文汇教授反对这一点，他认为标准粤语应该按照北宋初年的《广韵》的音。于是，在香港出现了两大流派，一是以广州话为代表的现代粤语，另一派便是遵循古籍的复古粤语。
<img src="https://user-images.githubusercontent.com/24568452/202695772-3c3ecb80-0ebc-4a83-828b-5c89fb1a215c.png" width="500">
3. 部分用词习惯不同：
香港的外来词比较多，常常会有直接用英语译音作为词语，如士多啤梨（草莓）、的士（出租车）、维他命（维生素）等。
而广式粤语受普通话影响较多，很多就是普通话按粤语读出来
<img src="https://user-images.githubusercontent.com/24568452/202695817-beb00346-b358-4dde-beeb-c263952ab619.png" width="500">

### 粤语拼音
粤语没有统一的拼音方案，甚至不同的粤语字典的拼音也会不同，现今最常用的是1993香港语言学学会粤语拼音方案，简称粤拼（英文：Jyutping）。([Ref](https://www.zhihu.com/question/39827067)，[Ref](https://www.bilibili.com/video/BV1aY4y1z76a/))
<img src="https://user-images.githubusercontent.com/24568452/202695856-d58cffae-4dfe-42a6-9836-b4e1c45e64fd.png" width="600">
<img src="https://user-images.githubusercontent.com/24568452/202695869-265bff5d-87ea-4b3a-bc62-0cda8f0ea17f.png" width="600">
<img src="https://user-images.githubusercontent.com/24568452/202695882-fcb209f1-3fb6-4e3b-a6b5-b7f1bee38da5.png" width="600">

有些韵腹可以作为结尾，而有些则需要结合韵尾。
<img src="https://user-images.githubusercontent.com/24568452/202695900-55e9ef6d-1d42-4a73-adbd-4f6e789783c3.png" width="600">

关于九声六调：
阴平、阴上、阴去、阳平、阳上、阳去、阴入、中入、阳入
<img src="https://user-images.githubusercontent.com/24568452/202695921-e3f8ea61-ee0e-48ce-ad09-ec95fc1c344d.png" width="600">

一般而言只有六调，即六种不同调值的发音（第一声到第六声）。前三种为阴，较为高，后三种为阳，较为低沉

<img src="https://user-images.githubusercontent.com/24568452/202695938-7e07882d-a73a-4aaa-80c3-7c17e01be6ba.png" width="600">

而九声，就是另外三个入声（ptk结尾，只做口型不发音）。相同点：音高相同；不同点：顿挫性（短促版本的发音，听上去就比较有顿挫感）。所以加上顿挫性的差异就有九声了。
第7声调约等于粤语发音第1声调
第8声调约等于粤语发音第3声调
第9声调约等于粤语发音第6声调
<img src="https://user-images.githubusercontent.com/24568452/202695960-e5bfefff-0a09-4d4c-bdb6-dcfa78f53874.png" width="600">
<img src="https://user-images.githubusercontent.com/24568452/202695972-099e3552-a72e-45fa-8d50-fea205413df8.png" width="600">
<img src="https://user-images.githubusercontent.com/24568452/202695991-67df8345-fd61-494e-ae66-ccf31fe49d36.png" width="600">

为什么会有这种差异：1）语音学上说，只要调值一致就是同一声调，不考虑其他因素；2）汉语语音学上说，声调的意义包含了抑扬和顿挫，抑扬就是音高和调值，而顿挫就是舒音和促声。

note：ptk本身就带有调值属性，所以后面的数字也可以不用写
所以具体含义是，九种声调，六种音高。

### 数据集

| |时长|人数|句子|话题|录制环境|格式|文本|
| -- | -- | --| --| --| --| --|--|
|https://magichub.com/datasets/guangzhou-cantonese-conversational-speech-corpus/|4.25h|20|10 </br>(需要切分)|日常|手机|wav|粤语字|
|https://magichub.com/datasets/guangzhou-cantonese-scripted-speech-corpus-daily-use-sentence/|4.06|10|4,060|日常|手机|wav|粤语字和普通话字|
|https://magichub.com/datasets/guangzhou-cantonese-scripted-speech-corpus-in-the-vehicle/|5|10|6,219|数字，</br> 命令，</br>询问|麦克风（车里|wav|粤语字|
|https://github.com/hltchkust/cantonese-asr https://storage.googleapis.com/samcah-bucket/cantonese-asr/cantonese_dataset.zip|73.6| |83,275|philosophy, politics, education, culture, lifestyle, family||fbank, npy（参数未知|
|https://github.com/gwinterstein/CantoMap|12.48|40||地图|
|Common Voice 11版|106|2943||日常|||

### 工具

1. 粤拼输入法：
- https://github.com/rime/rime-cantonese
3. 分词：
- https://github.com/wchan757/Cantonese_Word_Segmentation
- https://github.com/meganndare/cantonese-nlp
4. 一些粤语词典：
- https://github.com/Gahory/Mandarin2Cantonese/tree/main/resources
- https://github.com/mirfan899/CTTS/blob/master/misc/cantonese_mtts.lexicon
- https://github.com/soon14/cantoneseTTS/tree/master/src/cantoneseTTS
5. G2P：
- https://github.com/imdreamrunner/python-jyutping 用法简单，多音字有歧义
	<img src="https://user-images.githubusercontent.com/24568452/202696027-daf6590e-0a87-4d20-9bba-3893c238511f.png" width="500">
	
- https://github.com/jacksonllee/pycantonese 大而全，但g2p时会带有分词功能，需要后续进一步处理
	<img src="https://user-images.githubusercontent.com/24568452/202696107-6d559fb4-bc92-4f64-baca-7b717558be8e.png" width="500">
	
- https://github.com/CanCLID/ToJyutping 用法简单，支持多音字
	<img src="https://user-images.githubusercontent.com/24568452/202696203-780c2068-0b80-4f7a-aa0e-6a2973f39290.png" width="500">

**Comment by yt605155624** [comment]
[canton_new.zip](https://github.com/PaddlePaddle/PaddleSpeech/files/10681240/canton_new.zip)

**Comment by yt605155624** [comment]
PR:
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2899
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2907
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2924
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2927
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2950
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2977

**Comment by pengzhendong** [comment]
粤英混的 g2p 来了：https://github.com/pengzhendong/g2p-mix

**Comment by Yuexu742** [comment]
Hi, I'm a PhD student in Hong Kong, I'm currently conduct research about the Tanka community who speak Tanka Cantonese. Is there any dataset related to them? Thanks!
