### ISSUE TITLE
[TTS]命令行tts调用了错误的英文模型

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/PaddleSpeech#2673]
运行
tts = TTSExecutor()
tts(text="hello world", output="output.wav", lang="en")

报错提示：
![image](https://user-images.githubusercontent.com/54951765/202890199-0569c1ba-ccda-4f39-87a3-c99f1ba55358.png)

**Comment by kslz** [comment]
看起来这块是在拼接字符串
![image](https://user-images.githubusercontent.com/54951765/202890289-959bcd5c-4513-4cbd-9233-41ff152accd6.png)

**Comment by yt605155624** [comment]
你使用错了，lang='mix'
