### ISSUE TITLE
在windows上使用speech_web报错

### ISSUE THREAD

**Issue by oyb1125** [PaddlePaddle/PaddleSpeech#2676]
按照教程前后端都启动成功了
但是点击使用功能时就没反应，这是怎么回事
![image](https://user-images.githubusercontent.com/62881198/202985960-e5f4930a-06e2-436f-a12b-3418664a5a53.png)
![image](https://user-images.githubusercontent.com/62881198/202985311-b37e8e2f-7399-4499-9b19-1f74804c791b.png)
![image](https://user-images.githubusercontent.com/62881198/202986045-5030a926-3817-4958-ab1d-d8102a918823.png)

**Comment by iftaken** [comment]
你这个报错有点奇怪的，从报错上来看是8010端口没有启动拒绝服务了，前端和后端分别在本地两个不同的终端运行的吗？在游览器中输入 http://localhost:8010/docs 看看fastapi后台的服务是否启动了

**Comment by oyb1125** [comment]
> 你这个报错有点奇怪的，从报错上来看是8010端口没有启动拒绝服务了，前端和后端分别在本地两个不同的终端运行的吗？在游览器中输入 http://localhost:8010/docs 看看fastapi后台的服务是否启动了

是在两个不同的终端运行的，输入 http://localhost:8010/docs 的界面如下
![image](https://user-images.githubusercontent.com/62881198/203190330-64308d5b-1173-493b-8ed2-88a9615ea6b2.png)

**Comment by iftaken** [comment]
这个界面启动了，说明后端是启动成功了的，接下来就需要验证两个部分，一部分是后端功能完整性，通过http://localhost:8010/docs 上面的接口，可以做接口测试，确保后端功能没有问题，另一部分是确保前端和后端之前的通信OK，你可以先使用 前端中 语音合成的界面，生产一句话，如果能够生成成功就说明前后端的通信是没有问题

**Comment by oyb1125** [comment]
> 这个界面启动了，说明后端是启动成功了的，接下来就需要验证两个部分，一部分是后端功能完整性，通过http://localhost:8010/docs 上面的接口，可以做接口测试，确保后端功能没有问题，另一部分是确保前端和后端之前的通信OK，你可以先使用 前端中 语音合成的界面，生产一句话，如果能够生成成功就说明前后端的通信是没有问题

测试了语音识别的接口，正确识别出来了，后端的功能应该没有问题
![image](https://user-images.githubusercontent.com/62881198/203507504-7571b8e2-2ea9-4afa-a260-069927bc8a1a.png)
但是点击前端界面的功能就没有反应，比如语音合成
![image](https://user-images.githubusercontent.com/62881198/203508593-bbf478f1-2a8c-43b7-8ab4-e2f4db337fa6.png)
因该是前后端连接的问题，为什么会这样，百度搜了也没有解决，我对这块不是很懂

**Comment by iftaken** [comment]
你方便给paddlespeech@baidu.com发一个邮件吗？我通过邮件发您联系方式，可以远程帮您看看

**Comment by oyb1125** [comment]
好的

**Comment by iftaken** [comment]
经过排查是前端访问 localhost 对应的后端地址时增加了映射，导致前端无法找到后端地址，将前端配置中的 localhost 改成 127.0.0.1 可以解决此问题
