### ISSUE TITLE
[TTS] 流式tts输出音素在音频文件的时间戳信息

### ISSUE THREAD

**Issue by changyuzhe** [PaddlePaddle/PaddleSpeech#2678]
online-onnx 输出音素对应的时间戳信息，比如 **今天天气怎么样**，输出phone的时间戳信息。

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 自己改

**Comment by changyuzhe** [comment]
好的，谢谢。

**Comment by changyuzhe** [comment]
@yt605155624  您好，还有个问题请教下，PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py中self.acoustic_model.inference的durations输出示例如下：
Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,[10.])
Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,[8.])
...

这个数据怎么转换为有效的float32数据呢？

**Comment by yt605155624** [comment]
输出的是 paddle.Tensor, 可以 .numpy() 转成 numpy 的 ndarray

**Comment by changyuzhe** [comment]
.numpy()后是“[8.]”，这个是表示0.08么？

**Comment by yt605155624** [comment]
就是 8，表示这音素有 8 帧 ：）

**Comment by changyuzhe** [comment]
好的谢谢，音素的时间戳信息可以通过durations(单位是音频帧数)。但实际输出的音频在音素与音素之间会有停顿，而且不同音素之间的停顿时长是不同的，请问这个信息如何取到呢？

**Comment by changyuzhe** [comment]
hi，@yt605155624 tts流式引擎时间戳（词、拼音、音素）的问题还想请教下，

以下是我整理的关于时间戳细腻获取的资料，请指正
1>基于[style_fs2](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2)，模型推理输入的durations参数即为所有音素的时长，实际测试发现，音频总时长=3.6s情况下，durations总时长只有2.97s，这里有0.6s的时间是语音停顿、韵律词占用的时间，而且这部分时间没有途径可以获取，而且style_fs2如果在streaming场景下使用的话肯定会有效率上的损失【参考链接：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 】
2>基于onnx推理，输入待合成文本会根据标点切分成 N * [phone1, phone2, phone3 ... ]，phone1、2、3为音素索引，N为根据标点切分的句子数量，这种情况下是可以获取到句子级别的时间戳的，但是onnx.infer推理返回的chunk数并没有办法和音素、拼音产生联系【参考链接：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py】
3>tts训练前的数据预处理是使用mfa进行音素对齐，笨一点的方法是通过输入音素、合成后音频数据，可以获得相对准确的 词、拼音、音素 级别的时间戳，但是不适用于流式语音合成。

基于以上，有没有可能在onnx推理同时输出音素级别的时间戳呢？或者有没有其他可行的streaming下可行的方法呢？

**Comment by yt605155624** [comment]
有可能，参考一下 style_fs2 改一下模型的输出，default 的模型只输出 mel，你再多输出一下 duration, 然后重新导出静态模型和 onnx 模型就可以了

**Comment by Sloaix** [comment]
> hi，@yt605155624 tts流式引擎时间戳（词、拼音、音素）的问题还想请教下，
> 
> 以下是我整理的关于时间戳细腻获取的资料，请指正 1>基于[style_fs2](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2)，模型推理输入的durations参数即为所有音素的时长，实际测试发现，音频总时长=3.6s情况下，durations总时长只有2.97s，这里有0.6s的时间是语音停顿、韵律词占用的时间，而且这部分时间没有途径可以获取，而且style_fs2如果在streaming场景下使用的话肯定会有效率上的损失【参考链接：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 】 2>基于onnx推理，输入待合成文本会根据标点切分成 N * [phone1, phone2, phone3 ... ]，phone1、2、3为音素索引，N为根据标点切分的句子数量，这种情况下是可以获取到句子级别的时间戳的，但是onnx.infer推理返回的chunk数并没有办法和音素、拼音产生联系【参考链接：[https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py】](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py%E3%80%91) 3>tts训练前的数据预处理是使用mfa进行音素对齐，笨一点的方法是通过输入音素、合成后音频数据，可以获得相对准确的 词、拼音、音素 级别的时间戳，但是不适用于流式语音合成。
> 
> 基于以上，有没有可能在onnx推理同时输出音素级别的时间戳呢？或者有没有其他可行的streaming下可行的方法呢？

这应该是一个比较常见的需求了，根据句级时间戳，生成对应的字幕文件。

但是目前PaddleSpeech没有提供现成的支持，需要自行修改维护，考虑到时间成本和维护成本。我最后还是用了阿里云的商用方案。

如果能有PaddleSpeech提供的官方实现就好了。

**Comment by lisc199** [comment]
hello 看你们之前的讨论，duration输出的是音素的持续时间，那我怎么知道这是哪个音素呢？

**Comment by zhuxiu1234** [comment]
> > hi，@yt605155624 tts流式引擎时间戳（词、拼音、音素）的问题还想请教下，
> > 以下是我整理的关于时间戳细腻获取的资料，请指正 1>基于[style_fs2](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2)，模型推理输入的durations参数即为所有音素的时长，实际测试发现，音频总时长=3.6s情况下，durations总时长只有2.97s，这里有0.6s的时间是语音停顿、韵律词占用的时间，而且这部分时间没有途径可以获取，而且style_fs2如果在streaming场景下使用的话肯定会有效率上的损失【参考链接：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 】 2>基于onnx推理，输入待合成文本会根据标点切分成 N * [phone1, phone2, phone3 ... ]，phone1、2、3为音素索引，N为根据标点切分的句子数量，这种情况下是可以获取到句子级别的时间戳的，但是onnx.infer推理返回的chunk数并没有办法和音素、拼音产生联系【参考链接：[https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py】](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py%E3%80%91) 3>tts训练前的数据预处理是使用mfa进行音素对齐，笨一点的方法是通过输入音素、合成后音频数据，可以获得相对准确的 词、拼音、音素 级别的时间戳，但是不适用于流式语音合成。
> > 基于以上，有没有可能在onnx推理同时输出音素级别的时间戳呢？或者有没有其他可行的streaming下可行的方法呢？
> 
> 这应该是一个比较常见的需求了，根据句级时间戳，生成对应的字幕文件。
> 
> 但是目前PaddleSpeech没有提供现成的支持，需要自行修改维护，考虑到时间成本和维护成本。我最后还是用了阿里云的商用方案。
> 
> 如果能有PaddleSpeech提供的官方实现就好了。

请问提到的“阿里云的商用方案”是哪个？

**Comment by Sloaix** [comment]
> > > hi，@yt605155624 tts流式引擎时间戳（词、拼音、音素）的问题还想请教下，
> > > 以下是我整理的关于时间戳细腻获取的资料，请指正 1>基于[style_fs2](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2)，模型推理输入的durations参数即为所有音素的时长，实际测试发现，音频总时长=3.6s情况下，durations总时长只有2.97s，这里有0.6s的时间是语音停顿、韵律词占用的时间，而且这部分时间没有途径可以获取，而且style_fs2如果在streaming场景下使用的话肯定会有效率上的损失【参考链接：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 】 2>基于onnx推理，输入待合成文本会根据标点切分成 N * [phone1, phone2, phone3 ... ]，phone1、2、3为音素索引，N为根据标点切分的句子数量，这种情况下是可以获取到句子级别的时间戳的，但是onnx.infer推理返回的chunk数并没有办法和音素、拼音产生联系【参考链接：[https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py】](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/tts/online/onnx/tts_engine.py%E3%80%91) 3>tts训练前的数据预处理是使用mfa进行音素对齐，笨一点的方法是通过输入音素、合成后音频数据，可以获得相对准确的 词、拼音、音素 级别的时间戳，但是不适用于流式语音合成。
> > > 基于以上，有没有可能在onnx推理同时输出音素级别的时间戳呢？或者有没有其他可行的streaming下可行的方法呢？
> > 
> > 
> > 这应该是一个比较常见的需求了，根据句级时间戳，生成对应的字幕文件。
> > 但是目前PaddleSpeech没有提供现成的支持，需要自行修改维护，考虑到时间成本和维护成本。我最后还是用了阿里云的商用方案。
> > 如果能有PaddleSpeech提供的官方实现就好了。
> 
> 请问提到的“阿里云的商用方案”是哪个？

就是阿里云的tts，有对应的文档。
