### ISSUE TITLE
请问，fastspeech2 模型能否进行paddleslim 量化呢？声学模型部署，onnx 能否支持tensorrt 优化？

### ISSUE THREAD

**Issue by liroda** [PaddlePaddle/PaddleSpeech#2682]

**Comment by yt605155624** [comment]
fastspeech2 模型能否进行paddleslim 量化呢 -> 还没来得及尝试，可以试一下
onnx 能否支持tensorrt 优化 -> 试过 onnxruntime-trt 有些模型由于结构问题会报错，你可以再试下，onnx 我们我们都提供了，你配好 onnxruntime-trt 环境就行

**Comment by liroda** [comment]
好的，请问声学模型，paddlelite 优化前后性能差别大吗？

**Comment by yt605155624** [comment]
@liroda paddlelite 在 x86 上的推理速度没有 paddle 静态图快，paddlelite 主要是端上部署的优化， x86 推理跑通即可

**Comment by yt605155624** [comment]
@liroda 用 PaddleSlim 压缩串通流程了，还没有测效果，参考：https://github.com/PaddlePaddle/PaddleSpeech/pull/2729
