### ISSUE TITLE
ImportError: cannot import name 'load' from 'paddleaudio.backends'

### ISSUE THREAD

**Issue by MelanthaWang246** [PaddlePaddle/PaddleSpeech#2687]
## Others

<img width="723" alt="image" src="https://user-images.githubusercontent.com/61535808/203936174-a2633803-4950-47b6-8608-063e7efd786c.png">

**Comment by yt605155624** [comment]
please install paddleaudio<=1.0.1

**Comment by MelanthaWang246** [comment]
Solved. Thank you so much!

Melantha’s ipad

在 2022年11月25日，下午6:32，TianYuan ***@***.***> 写道：

﻿

please install paddleaudio<=1.0.1

**Comment by wangtiance** [comment]
paddleaudio 1.0.2 was installed by default when I pip installed paddlespeech. I hope this will be fixed somehow.

**Comment by yt605155624** [comment]
We will fix this in the next version of paddlespeech (1.3.0)
