### ISSUE TITLE
添加其他语言模型

### ISSUE THREAD

**Issue by stuyun** [PaddlePaddle/PaddleSpeech#2690]
![image](https://user-images.githubusercontent.com/8639389/204117042-0a7b0f84-e8ba-4a23-afb5-c6278a4c7e7a.png)
![image](https://user-images.githubusercontent.com/8639389/204117053-7a3d1cc1-794c-4442-b43e-a060ac6b751c.png)

**Comment by lym0302** [comment]
请问你的疑问是什么呢？lang 应该设置为 mix 哦
