### ISSUE TITLE
模型下载失败-初学

### ISSUE THREAD

**Issue by zyb8543d** [PaddlePaddle/PaddleSpeech#2694]
按照首页提示安装所有依赖包，测试时遇到模型下载问题。
```
paddlespeech asr --lang zh --input 30229_20220628133853089_right_55_16khz.wav
/home//miniconda3/envs/paddlespeech/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
RuntimeError: Download from https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz failed. Retry limit reached(paddlespeech) 
```

**Comment by lym0302** [comment]
我这边验证是可以正常下载的，应该是网络问题，可以检查网络后再试下~

**Comment by zyb8543d** [comment]
> 我这边验证是可以正常下载的，应该是网络问题，可以检查网络后再试下~

@lym0302 尝试过很多次了，下载不了，请问可以加载离线模型吗，有没有模型样例，需要准备成什么结构（去重头看一遍代码有点时间长）。

**Comment by lym0302** [comment]
你复制这个模型链接：https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz 先把模型下载到本地再想办法弄到你的机器上吧

**Comment by yaleimeng** [comment]
代码里的下载功能比较弱鸡，可以把错误提示里面的链接复制一下，通过IDM、迅雷等工具下载。
在解压缩后放到默认的目录，也就是： ~/.paddlespeech/models/conformer_wenetspeech-zh-16k/1.0/

**Comment by rogerBridge** [comment]
> 你复制这个模型链接：https://paddlespeech.bj.bcebos.com/s2t/wenetspeech/asr1_conformer_wenetspeech_ckpt_0.1.1.model.tar.gz 先把模型下载到本地再想办法弄到你的机器上吧

这个放在默认目录下好像不行, 会删除掉我放上去的模型然后重新下载
