### ISSUE TITLE
[TTS]流式接口调用失败，docker内正常调用，docker外报错

### ISSUE THREAD

**Issue by Approximetal** [PaddlePaddle/PaddleSpeech#2695]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
流式接口paddlespeech_client tts_online在docker外调用失败，docker外安装了简单版的pip库。

docker内部正常调用：
/home/PaddleSpeech/demos/streaming_tts_server bash test_client.sh
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
[2022-11-28 10:28:30,339] [    INFO] - tts http client start
[2022-11-28 10:28:30,339] [    INFO] - endpoint: http://127.0.0.1:20620/paddlespeech/tts/streaming
[2022-11-28 10:28:31,822] [    INFO] - sentence: 您好，欢迎使用百度飞桨语音合成服务。
[2022-11-28 10:28:31,822] [    INFO] - duration: 3.825 s
[2022-11-28 10:28:31,822] [    INFO] - first response: 0.1715390682220459 s
[2022-11-28 10:28:31,822] [    INFO] - final response: 1.4812896251678467 s
[2022-11-28 10:28:31,822] [    INFO] - RTF: 0.38726526148178997
[2022-11-28 10:28:31,822] [    INFO] - Audio successfully saved in output.wav
[2022-11-28 10:28:31,822] [    INFO] - The sentence has no delay in streaming synthesis.

远程服务器调用失败：
(base) xxxx:/platform_tech/xxxx/code/fastspeech2$ paddlespeech_client tts_online --server_ip 192.168.190.80 --port 20620 --protocol http --input "您好，欢迎使用百度飞桨语音合成服务。" --output paddleTTS.wav
/home/xxxx/miniconda3/lib/python3.8/site-packages/scipy/special/orthogonal.py:79: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/home/xxxx/miniconda3/lib/python3.8/site-packages/scipy/io/matlab/mio5.py:95: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from .mio5_utils import VarReader5
[2022-11-28 18:26:07,634] [    INFO] - tts http client start
[2022-11-28 18:26:07,638] [   ERROR] - Failed to synthesized audio.
[2022-11-28 18:26:07,638] [   ERROR] - 'sample_rate'

server端显示：
INFO:     192.168.190.79:51488 - "GET /paddlespeech/tts/streaming/samplerate HTTP/1.1" 404 Not Found

**Environment (please complete the following information):**
 - OS：Ubuntu
 - GCC/G++ Version [9.3]
 - Python Version [3.8]
 - PaddlePaddle Version [2.4.0]
 - CUDA/CUDNN Version [cuda-11.2]

**Comment by lym0302** [comment]
先检查下docker 内外都使用同一个版本/代码的 paddlespeech
因为这个接口是后续加的，大概率是因为容器内外版本/代码 不一致导致的这个问题

**Comment by Approximetal** [comment]
> 



> 先检查下docker 内外都使用同一个版本/代码的 paddlespeech 因为这个接口是后续加的，大概率是因为容器内外版本/代码 不一致导致的这个问题

嗯嗯，docker里面的代码是2.3版本，接口调用端用的是2.4版本

**Comment by yt605155624** [comment]
@Approximetal 我们说的是 paddlespeech 的版本不是 paddle 的版本
