### ISSUE TITLE
如何修改PaddleSpeech预训练模型默认下载路径？

### ISSUE THREAD

**Issue by 503718696** [PaddlePaddle/PaddleSpeech#2712]
如何修改PaddleSpeech预训练模型默认下载路径？

**Comment by zxcd** [comment]
目前paddlespeech的预训练模型被放在PPSPEECH_HOME下，如果需要修改下载路径可以尝试修改环境变量PPSPEECH_HOME

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/caa1dd84d447cd51f3dc97a0db16ae9e5ec0ad02/paddlespeech/utils/env.py#L44
