### ISSUE TITLE
Python API for mixed-language TTS

### ISSUE THREAD

**Issue by wangtiance** [PaddlePaddle/PaddleSpeech#2716]
Following the examples in https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/text_to_speech
I'm able to call Python API for Chinese/English TTS:

import paddle
from paddlespeech.cli.tts import TTSExecutor
    tts_executor = TTSExecutor()
    for spk_id in range(174):
        tts_executor(
            text='今天的天气不错啊',
            output=f'demo_{spk_id}.wav',
            am='fastspeech2_aishell3',
            spk_id=spk_id,
            voc='pwgan_aishell3',
            lang='zh',
            device=paddle.get_device())

But I can't set lang to 'mix' like with the command line. Is there support for mixed TTS with pretrained models in Python? Also, which vocoder is recommended for mixed TTS? Thank you!

**Comment by yt605155624** [comment]
try to update your paddlespeech or install develop version of paddlespeech, see https://github.com/PaddlePaddle/PaddleSpeech/issues/2472

for more details please check https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3

**Comment by wangtiance** [comment]
Thanks! If I want to use the pretrained model in https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3 do I need to install the dev version?

**Comment by yt605155624** [comment]
the mix TTS has been included in paddlespeech 1.2.0
