### ISSUE TITLE
deepspeech2转onnx模型怎么使用

### ISSUE THREAD

**Issue by Potato-wll** [PaddlePaddle/PaddleSpeech#2725]
我想问一下 deepspeech2转onnx模型有详细点的教程吗。我看了一下官方提供的infer_check.py代码（位于paddlespeechdevelop/speechx/examples/ds2_ol/onnx/local/infer_check.py）,显示onnx模型的输入是audio_chunk，audio_chunk_lens，chunk_state_h_box，chunk_state_c_box四个参数，最后模型预测输出也是ort_res_chunk, ort_res_lens, ort_chunk_state_h, ort_chunk_state_c四个参数，不是很理解一个音频样本怎么传入模型进行预测，最后输出结果的，官方有详细点的教程吗。

**Comment by zh794390558** [comment]
转onnx的代码参看https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/speechx/examples/ds2_ol/onnx/README.md。 ds2模型部分参看 https://aistudio.baidu.com/aistudio/education/group/info/25130 教程。 代码参看 https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/asr/online/onnx/asr_engine.py

**Comment by Potato-wll** [comment]
非常感谢您的回答，asr_engine里面也详细的说明了ASRConnectionHanddler的过程，但是作为一个新手，我还是不太会操作，能详细说一下怎么调用吗，比如说我又一个wav的音频，通过哪几步操作可以借用onnx预测后变成文字输出。期待您的回复！

**Comment by zh794390558** [comment]
先看下https://aistudio.baidu.com/aistudio/education/group/info/25130 教程理解下模型原理，本质是rnn的推理过程。

**Comment by Potato-wll** [comment]
你好，我这边看了一下教程，流式启动ASR语音识别服务是paddlespeech_server start --config_file conf/ws_conformer_application.yaml，运行客户端paddlespeech_client asr_online  --server_ip 127.0.0.1 --port 8090 --input zh.wav，这个得到了验证，能够正常运行。
我参照这个写法，像启动onnx的的asr流式服务，我看了一下conf文件夹里面ws_ds2_application.yaml对应的engine就是asr_online-onnx，我便尝试以类似的策略去启动，paddlespeech_server start --config_file conf/ws_ds2_application.yaml，但是最后报错'NoneType' object has no attribute 'init'

**Comment by zh794390558** [comment]
我是了下，没有问题的。不过onnxruntime的版本的是1.11.0才可以, 1.10会报错，如下：

![9e2f7fefe24801a7605a46b70cba6d1c](https://user-images.githubusercontent.com/3038472/206382949-0dba1382-bb7d-4bae-b70d-45e6080eaf9c.png)


paddlespeech_server start --config_file conf/ws_ds2_application.yaml

paddlespeech_client asr_online --server_ip 127.0.0.1 --port 8090 --input ./zh.wav

**Comment by Potato-wll** [comment]
不对，刚刚运行错配置文件了，现在服务可以正常启动
![image](https://user-images.githubusercontent.com/84260407/206391391-79d789a0-224c-4612-adc9-b8a4bca1b943.png)
但是预测的时候报错NameError: name 'Scorer' is not defined

**Comment by Potato-wll** [comment]
因为paddlespeech_client只支持下面这几个参数
![image](https://user-images.githubusercontent.com/84260407/206391909-78fef50d-1b31-4887-b2b2-c6f5a5807fa3.png)
所以我预测代码还是用的paddlespeech_client asr_online  --server_ip 127.0.0.1 --port 8090 --input input.wav
 运行结果如下
![image](https://user-images.githubusercontent.com/84260407/206392129-ead9bd80-a1af-4f12-86c1-99c7bd04ef91.png)

**Comment by Potato-wll** [comment]
![image](https://user-images.githubusercontent.com/84260407/206392759-59bc856f-c777-41b2-9ea4-935dbb58ee5f.png)
以上是完整的报错信息，是不是我预测的时候那行代码有问题

**Comment by Potato-wll** [comment]
方便的话，你那边能不能生成一份requirements，我照着部署一下环境，万分感谢

**Comment by zh794390558** [comment]
换linux的机器吧，我在ubuntu上测试的。
