### ISSUE TITLE
ASR解码方式有没有beam search

### ISSUE THREAD

**Issue by lesliexufdu** [PaddlePaddle/PaddleSpeech#2726]
我看文档里的解码方式，有ctc_greedy_search和ctc_prefix_beam_search等，除了ctc_greedy_search其他方式耗时都很长。
ctc_prefix_beam_search应该是用语言模型实现的，所以耗时才长吧，有没有只用beam search不加语言模型的方案，作为一个折中？

**Comment by zh794390558** [comment]
用的什么模型？

**Comment by lesliexufdu** [comment]
conformer

**Comment by lesliexufdu** [comment]
找到方法了，把语言模型设为None就行，
import paddlespeech_ctcdecoders
beam_results = paddlespeech_ctcdecoders.ctc_beam_search_decoding(
    probs_seq = out[0].tolist(),
    vocabulary = _text_featurizer.vocab_list,
    beam_size=20,
    cutoff_prob=0.99,
    cutoff_top_n=40,
    ext_scorer=None,
    blank_id=0
)
beam_results = [(res[0], res[1]) for res in beam_results]
试了一下速度，看来本来就没用语言模型？

**Comment by zh794390558** [comment]
ok
