### ISSUE TITLE
[S2T]LogMelSpectrogram抽mfcc特征报异常

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/PaddleSpeech#2730]
你好，想问下用paddle的LogMelSpectrogram抽特征出现以下报错是为什么？代码能够正常跑通，但是结束会打印异常信息。
paddle版本：2.2.2
paddleaudio版本:1.0.2

```

import numpy as np
import sys
import paddle
from paddleaudio.features import LogMelSpectrogram

feature_extractor = LogMelSpectrogram(sr=16000,
                                      n_fft=400,
                                      hop_length=160,
                                      n_mels=80)


data = paddle.randn(shape=(1, 48000))
output = feature_extractor(data)
print(output.shape, output.dtype)
```

控制台输出：
<img width="1875" alt="image" src="https://user-images.githubusercontent.com/22003927/206620983-7c67c105-6586-40c1-83a5-5c085aa176fe.png">

**Comment by SmileGoat** [comment]
hi, 同学，我这边没有复现出你的问题。我这边2.2.2是ok，另外我测试了一下2.3.1，和 2.4.1。 你要不试一试，最新的paddlepaddle==2.4.1的版本。另外：paddlepaddle>=2.4.0后，paddle中提供了接口 paddle.audio.features import LogMelSpectrogram ，也可以计算。 要是还有问题，我再跟进一下。

**Comment by will-wiki** [comment]
@SmileGoat 测试了下，应该是环境问题，另外一个环境报错
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libcufft.so) that Paddle depends on is not configured correctly. (error code is libcufft.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)
  [operator < fft_r2c > error]
重新链接下这个文件就可以了，不过之前的环境没报错只打印异常，十分感谢解答～
