### ISSUE TITLE
我安装了paddlespeech 但是还是报错了

### ISSUE THREAD

**Issue by SoulSnow** [PaddlePaddle/PaddleSpeech#2735]
PS E:\paddlepaddle\github\PaddleSpeech\demos\streaming_asr_server> python .\local\streaming_asr_server.py
Traceback (most recent call last):
  File "E:\paddlepaddle\github\PaddleSpeech\demos\streaming_asr_server\local\streaming_asr_server.py", line 16, in <module>
    from paddlespeech.cli.log import logger
ModuleNotFoundError: No module named 'paddlespeech'

**Comment by yaleimeng** [comment]
1，用pip list 确认是paddspeech否安装成功。用 pip -V 检查该pip对应的Python版本。
2，检查运行代码的Python 版本。

**Comment by SoulSnow** [comment]
谢谢，是我安装了conda 的pip 和 python pip 安装路径不一致
