### ISSUE TITLE
在线ASR推理能否启用多线程加速？

### ISSUE THREAD

**Issue by nailvcoronation** [PaddlePaddle/PaddleSpeech#2737]
目前用conformer_u2pp_online_wenetspeech模型在CPU上进行推理，推理所使用的时间要长于音频时长，无法达到实时的效果。看了一下CPU的使用情况，发现4核的CPU只有一个核跑满了，另外三个核几乎都是空闲状态。

**Comment by zh794390558** [comment]
可以用GPU推理，修改下配置文件。CPU多核的话看看paddle中是否有相关的说明吧。

**Comment by yt605155624** [comment]
可以 export OMP_NUM_THREADS=线程数 开启多线程，但是目前很多CPU算子都没有支持多线程，所以开了提速也不一定明显
