### ISSUE TITLE
PaddleSpeech可否支持下Paddle lite方便部署在嵌入式设备上

### ISSUE THREAD

**Issue by jackyzjk** [PaddlePaddle/PaddleSpeech#2743]
如题所述，如果后续支持Paddle lite的话还望到时一并给出操作说明，方便新手去部署

**Comment by yt605155624** [comment]
TTS 已经支持了
1. https://github.com/PaddlePaddle/PaddleSpeech/blob/7804c8e8f3ad66480d528d83a6d786fc0ef8e318/examples/csmsc/tts3/run.sh#L66
2. Android demo：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/TTSAndroid

并且 PaddleSpeech TTS 已经有某企业用户成功部署在词典笔上了

**Comment by jackyzjk** [comment]
- 我也想把paddlespeech运用到新产品中去，但由于是嵌入式arm体系设备paddlepaddle安装不太方便，所以才想问下paddlespeech的语音识别功能后续是否会支持paddle lite框架，我查到paddle lite就是专门用于边端设备且提供了各种体系架构的安装包。
- 另外目前paddlespeech语音识别的内容跟我想要的结果相差甚远，比如我录了一段语音`相位5增加5秒`，实际识别的结果为`向为武增加五秒`，我是个刚接触语音识别的小白对咱这块业务的专业知识欠缺太多，想问下如果想要paddlespeech识别的结果达到我想要的，我是不是应该去训练自己的模型，这个模型又该如何去训练呢，看了一下github上面的文档但太过晦涩不知道如何去下手，大神可否指点一下迷津或者咱有没有那种手把手详细介绍如何训练自己模型的教程，我特别想把paddlespeech的语音识别与语音合成功能运用新产品中去增加产品亮点，拜托了！！！

**Comment by lizezheng** [comment]
> 

jacky 你提出了几个比较好的问题。

问题1 ： paddlespeech 有支持 paddle-lite 推理框架，进而支持在端侧的部署；目前 tts 已经具备在端侧部署的案例；

问题2 :  识别效果问题；因为绝大部分的 ai 任务都做不到 一个模型适配所有场景，所以这里还是需要结合 具体的业务场景 进行 
       模型的训练，比如 am 的训练，lm的训练；
             至于怎么训练 asr 场景的模型，可以参考 paddlespeech/examples/aishell下的例子；语音识别相关的基础知识 也可以参考 paddle ai-studio中 语音相关的课程 https://aistudio.baidu.com/aistudio/education/group/info/25130

ps : 可以添加 paddlespeech RD 小姐姐微信 及  加入 paddlespeech 微信群讨论。
