### ISSUE TITLE
ubuntu22.04 安装 PaddleSpeech r1.3.0 对 onnxruntime 的依赖问题

### ISSUE THREAD

**Issue by rocket049** [PaddlePaddle/PaddleSpeech#2749]
## Others

在 `setup.py` 中指定的版本 `onnxruntime==1.11.0` 现在已经无法下载到，需要把这一行代码改成 `onnxruntime>=1.11.0`

**Comment by yt605155624** [comment]
下载不到的原因是什么，我看 pypi 里面有啊 https://pypi.org/project/onnxruntime/1.11.0/
ubuntu 16.04 可正常下载，ubuntu 20.04 报错是啥？
<img width="714" alt="image" src="https://user-images.githubusercontent.com/24568452/208089395-4b7edcc6-6d82-46b2-bef8-9c1985b7965b.png">

**Comment by HuaHuaY** [comment]
@yt605155624 
```sh
huahua@HuaHuaATX:~/VTuberTalk$ pip install onnxruntime==1.11.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.11.0 (from versions: 1.12.0, 1.12.1, 1.13.1)
ERROR: No matching distribution found for onnxruntime==1.11.0
```
可能是python版本问题，我用的3.10。pypi上1.11.0好像只支持到3.9

**Comment by yt605155624** [comment]
@HuaHuaY 好的多谢，我们发版测试只测 3.7 ~ 3.9, 如果因为 onnxruntime==1.11.0 导致无法正常安装 release 的 paddlespeech, 建议 clone PaddleSpeech 后修改 setup.py 里 onnxruntime 的版本后再进行源码安装, 参考
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2472
