### ISSUE TITLE
mix中英文流式tts模型转static报错

### ISSUE THREAD

**Issue by lzhin** [PaddlePaddle/PaddleSpeech#2751]
我用csmsc/tts3/conf/cnndecoder.yaml配置，运行zh_en_tts/tts3的run.sh，训练完后跑./local/synthesize_e2e.sh报错，请问要如何修改：
ValueError: The feeded_var_names[1]: 'spk_id' doesn't exist in pruned inference program. Please check whether 'spk_id' is a valid feed_var name, or remove it from feeded_var_names if 'spk_id' is not involved in the target_vars calculation.

**Comment by yt605155624** [comment]
csmsc/tts3/conf/cnndecoder.yaml 是单说话人的配置 zh_en_tts/tts3 需要多说话人，请搞明白原理和基础概念之后再魔改 :)

**Comment by lzhin** [comment]
> csmsc/tts3/conf/cnndecoder.yaml 是单说话人的配置 zh_en_tts/tts3 需要多说话人，请搞明白原理和基础概念之后再魔改 :)

那我想训练流式的中英文模型 大概要怎么操作呢

**Comment by lzhin** [comment]
> csmsc/tts3/conf/cnndecoder.yaml 是单说话人的配置 zh_en_tts/tts3 需要多说话人，请搞明白原理和基础概念之后再魔改 :)

那要实现流式中英文tts的话 请问大概要怎么改

**Comment by yt605155624** [comment]
你的思路没什么问题，就是 csmsc/tts3/conf/cnndecoder.yaml 和 zh_en_tts/tts3/conf/defaut.yaml 结合起来，请再看下代码细节，我上面回复地很清楚了

**Comment by a0735a** [comment]
@lzhin 关于csmsc/tts3/conf/cnndecoder.yaml 和 zh_en_tts/tts3/conf/defaut.yaml 结合起来的问题解决了吗
如果解决了，方便分享下吗
