### ISSUE TITLE
[TTS]微调tts中英混合问题

### ISSUE THREAD

**Issue by MrInouye** [PaddlePaddle/PaddleSpeech#2757]
在微调中英混合的tts模型，用的是自带的文本前端转的拼音，发现有些字母（比如QQ、app等）无法转成拼音，check_oov的时候就会被过滤掉，想问下怎样解决？

![转拼音的方法](https://user-images.githubusercontent.com/73767263/208643926-0a366be6-089e-49b5-af9d-5c508e62bb1b.png)
![拼音结果](https://user-images.githubusercontent.com/73767263/208644454-7ed7bbb2-149c-412c-a960-9e93e9e0030c.png)
![oov](https://user-images.githubusercontent.com/73767263/208644922-4dbbc14b-aa15-49c6-9189-ec29fc66aa82.png)

**Comment by yt605155624** [comment]
可以用 mix_frontend https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/frontend/mix_frontend.py, 你用的是纯中文的前端，只能解决纯中文

**Comment by MrInouye** [comment]
> 可以用 mix_frontend https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/frontend/mix_frontend.py, 你用的是纯中文的前端，只能解决纯中文

感谢解答，我还有个问题，我用的run脚本是https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/other/tts_finetune/tts3/run_mix.sh
里面设置的参数lang=zh，然后脚本https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/other/tts_finetune/tts3/local/check_oov.py
里的参数'--lang'只有zh or en，没有mix选项。
我感觉这才是导致oov的原因

**Comment by yt605155624** [comment]
@MrInouye 是的，tts_finetune 的基础模型是纯中文或者纯英文的或者中英文混合的，但是预训练的 MFA 是纯中文或者纯英文的，所以 lang 只能选 zh 或者 en，即使基础模型是中英文混合的，用于 finetune 的语料也只能是纯中文或者纯英文的
