### ISSUE TITLE
fast deploy 并发问题

### ISSUE THREAD

**Issue by kFoodie** [PaddlePaddle/PaddleSpeech#2783]
https://github.com/PaddlePaddle/PaddleSpeech/blob/96d76c83ade6dad94738ef4ae1a095dec3f858b3/demos/streaming_tts_serving_fastdeploy/streaming_tts_serving/stream_client.py#L74
value = [’哈哈', '哈哈'] 报错
‘’‘
tritonclient.utils.InferenceServerException: [request id: 0] input 'INPUT_0' already exists in request
’‘’

**Comment by lym0302** [comment]
看这个报错应该是 tritonclient的使用只支持 values 列表的长度为1。

**Comment by lym0302** [comment]
这里的 values  类似于之前服务的 input 一样，只是需要用列表的形式来封装以满足使用，与并发无关。之前的input 是一个句子，这里的 values 列表的长度也为1。
另外服务支持并发，即支持多个用户同时请求，每个用户的请求必须是1个句子。

**Comment by kFoodie** [comment]
> 这里的 values 类似于之前服务的 input 一样，只是需要用列表的形式来封装以满足使用，与并发无关。之前的input 是一个句子，这里的 values 列表的长度也为1。 另外服务支持并发，即支持多个用户同时请求，每个用户的请求必须是1个句子。

建议下个版本加个注释……虽然无关紧要……
