### ISSUE TITLE
四川话TTS前端有好的方案么

### ISSUE THREAD

**Issue by Pydataman** [PaddlePaddle/PaddleSpeech#2787]

**Comment by yt605155624** [comment]
四川话和普通话比较像，不像粤语那样发音更复杂，感觉不需要额外的前端，直接用普通话前端硬 train 即可
- https://github.com/PaddlePaddle/PaddleSpeech/discussions/2492

**Comment by Pydataman** [comment]
@yt605155624  四川话的分词不好弄 要整个字典吧 还有读音

**Comment by yt605155624** [comment]
抱歉，我不懂四川话，无法提供相应支持
