### ISSUE TITLE
关于小样本微调测试的报错【This dataset has no examples】

### ISSUE THREAD

**Issue by peiqianggao** [PaddlePaddle/PaddleSpeech#2790]
<img width="1761" alt="image" src="https://user-images.githubusercontent.com/12654801/210199150-b534dbfd-12be-4fd1-ac68-8c3afb90601b.png">

已参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/2456 及 https://github.com/PaddlePaddle/PaddleSpeech/issues/2319 ，但未能解决问题，期待答复 ~

**Comment by peiqianggao** [comment]
clone PaddleSpeech 项目代码后，切到 devlop 分支，按照 https://github.com/PaddlePaddle/PaddleSpeech/blob/7cc1d66863a48b50c2430059c8b84060d84b11a3/examples/other/tts_finetune/tts3/README.md 流程执行

**Comment by yt605155624** [comment]
请问你的操作系统是？我们现在提供的 MFA 是 ubuntu 系统上的可执行文件，如果是其他系统，请到 MFA 官网下载对应文件，我们用的是 1.x 版本 https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases?page=4
![image](https://user-images.githubusercontent.com/24568452/210291621-f32ce757-d6f8-461a-ab0e-9445327a56cd.png)

**Comment by peiqianggao** [comment]
@yt605155624 感谢回复，我切到 aistudio 中复制了这个项目运行了 
《【有手就行】使用你自己的声音做语音合成》https://aistudio.baidu.com/aistudio/projectdetail/5342586?forkThirdPart=1

但在上传数据并校验标注后，微调失败了，上传的数据有11条，日志如下，未发现报错原因 https://scdn.shidaijia.com/bug/worker_0.log

**Comment by peiqianggao** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/12654801/210298240-284786df-e096-4972-a207-57fc823d7fb9.png">
<img width="496" alt="image" src="https://user-images.githubusercontent.com/12654801/210298245-7524141c-0f96-40d1-8f49-580f0e68566a.png">

**Comment by iftaken** [comment]
从日志上已经可以看到训练的信息了，说明模型微调是OK的，报错可能是可视化过程中 Streamlit 引起的，一般重新运行一下就OK了，你可以先尝试示例数据看全流程能否跑通，或者你切换到代码版的从上到下运行

**Comment by peiqianggao** [comment]
已经解决了，感谢解答。

**Comment by NLPerxue** [comment]
> 从日志上已经可以看到训练的信息了，说明模型微调是OK的，报错可能是可视化过程中 Streamlit 引起的，一般重新运行一下就OK了，你可以先尝试示例数据看全流程能否跑通，或者你切换到代码版的从上到下运行
您好，请教一下：请问在进行单音色克隆任务时是否有过如下报错呢？我用官方给的测试数据是可以跑通的，但是上传自己的音频数据就不行。会报以下错误，请问该怎么解决呢？

![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/119272805/3a731703-e080-4ff7-b89a-66a2fd2395b4)

**Comment by truthsun22** [comment]
> 已经解决了，感谢解答。

请问是怎么解决的？

**Comment by truthsun22** [comment]
can not execute binary file的错误，应该是操作系统是arm架构的。请问从哪可以下载arm架构MFA可执行文件？

**Comment by NLPerxue** [comment]
> > 已经解决了，感谢解答。
> 
> 请问是怎么解决的？
我的情况是官方给的测试数据可以跑通，自己的数据不可以。其实是音频数据出错了，官方给的测试数据的采样率是44100（具体是多少忘了，可以写个脚本查看一下）。按照官方音频数据的格式转换后就可以了。
