### ISSUE TITLE
文本加标点，文本字数是否有限制

### ISSUE THREAD

**Issue by nuo900617** [PaddlePaddle/PaddleSpeech#2793]
## General Question

当输入文本较长时，后面部分添加的标点是乱的。请问是什么原因？
效果如下：

全国政协十号在京召开网络议政远程协商会，议题是：加强大数据时代个人信息，保护中共中央政治局常委、全国政协主席汪洋主持会议并讲话，他强调，要深入学习贯彻习近平总书记关于网络安全和个人信息保护工作的重要指示精神，以发展的眼光和辩证的思维，看待大数据时代个人信息保护问题；坚持以人民为中心，坚持政府监管、行业自律、社会参与、统筹推进，坚持标本监制，在提高信息资源利用水平的同时，科学有效保护信息安全，让大数据更好服务社会、造福人民；十四位委员与专家在全国政协机关和辽宁、安徽、湖南、贵州五个会场，以及通过手机连线方式发言，近一把式卫；委员通过移动旅职平台发表意见，大家认为，党中央高度重视大数据时代个人信息保护，有关方面做了大量工作，取得了积极成效，但传统个人信息保护制度和方式，跟不上；互联网广泛普及和数字产业迅猛发展的新形式，维护信息安全，依然任重到源；一些委员建议，要加快出台专门的个人信息保护法律，加大专项治理力度，重权，打击非法收集、交易、使用个人信息的违法犯罪活动，提高违法违规成本，最大限度挤压网络黑灰产业生存空间，要实施分级分类保护，建立个人信息利用清单强化对人，脸，识别数据爬取等技术，应用和人，肉，搜索，等行为的监、管要压，实企业主体责，任、广泛宣传个人，信息安全知识技术，和理、念，增强公、民；自我保护；意识不给违法、犯罪行为以可乘之机要加强部门；间信息共享和统、筹；协、调建、立统、一的个人，信息保护；监、管平台避免多头，执法、和重复执法、中央网信办，工业和信息化部公、安部卫生、健康委市场，监、管总局等部门；负责，同志，现场，做了互动交流

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2509
