### ISSUE TITLE
[S2T]使用源码安装whisper时调用cli会报错提示找不到mel_filters.npz

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/PaddleSpeech#2795]
环境：AIstudio
![image](https://user-images.githubusercontent.com/54951765/210551499-0c91e219-f88b-4cf2-bb38-5f51560e7b26.png)

新建环境使用pip安装后可以正常运行
![image](https://user-images.githubusercontent.com/54951765/210522435-e7a65271-882a-4ca3-905c-592453476b35.png)
![image](https://user-images.githubusercontent.com/54951765/210551402-c720dab0-9d10-4867-b42e-c394789ce6cb.png)

**Comment by zxcd** [comment]
AIstudio上是怎么用的？

**Comment by kslz** [comment]
> AIstudio上是怎么用的？

就是这样
```
paddlespeech whisper --task transcribe --input en2-16k.wav -y
```
另外我刚试了一下 两种安装方式的 `paddlespeech whisper -h` 甚至都不一样
![image](https://user-images.githubusercontent.com/54951765/210551274-1d841ea1-4dbc-4e7e-b3df-daa671f716fd.png)

**Comment by zxcd** [comment]
你这两个环境的paddle和paddlespeech版本分别是？

**Comment by kslz** [comment]
> 你这两个环境的paddle和paddlespeech版本分别是？

左边：
paddlepaddle-gpu               2.4.0.post112
paddlespeech                   1.3.0

右边：
paddlepaddle                   2.4.0
paddlespeech                   0.0.0

**Comment by zxcd** [comment]
我在aistudio上未复现到这个问题，你是怎么安装的？

可以使用：
`!git clone https://github.com/PaddlePaddle/PaddleSpeech.git`
`%cd PaddleSpeech`
`!pip install pytest-runner`
`!pip install .`

**Comment by kslz** [comment]
> 我在aistudio上未复现到这个问题，你是怎么安装的？
> 
> 可以使用： `!git clone https://github.com/PaddlePaddle/PaddleSpeech.git` `%cd PaddleSpeech` `!pip install pytest-runner` `!pip install .`

抱歉我又试了一下可以了，应该是我这个项目是以前克隆下来的，一直没更新，新克隆的很好用，打扰了
