### ISSUE TITLE
流式语音识别运行报错

### ISSUE THREAD

**Issue by gfhjjk** [PaddlePaddle/PaddleSpeech#2797]
运行流式websocket语音识别ws_conformer_wenetspeech_application_faster.yaml显示
![图片](https://user-images.githubusercontent.com/94445730/210710787-7e2ea9ca-3eea-40ab-b5f9-a42f644529d2.png)

**Comment by zxcd** [comment]
please try 
`pip install paddlespeech_ctcdecoders`

**Comment by gfhjjk** [comment]
显示这个
![图片](https://user-images.githubusercontent.com/94445730/210713411-a9e005de-244f-420d-bd73-52221ef106ab.png)

**Comment by yt605155624** [comment]
请参考 
- https://github.com/PaddlePaddle/PaddleSpeech/pull/2167

但是你报错不是因为这个，参考如下链接改下日志等级，看下具体报错
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2792

**Comment by zxcd** [comment]
你paddlespeech的安装方式是什么样的？

**Comment by gfhjjk** [comment]
安装paddlepaddle==2.4.1  paddlespeech==1.1.3,我以前安装某个版本是可以跑的，早上重新安装了下最新的环境，就跑不了了

**Comment by zxcd** [comment]
但我们paddlespeech 最新版是1.3.0，建议尝试更新一下

**Comment by gfhjjk** [comment]
我换成了1.3.0还是报上面图片那个错，我修改了日志等级，还是报一样的错

**Comment by zxcd** [comment]
更换为1.3.0之后是否可以跑通
`pip install paddlespeech_ctcdecoders`

**Comment by yt605155624** [comment]
@gfhjjk 我搜了下，这个报错似乎是paddle 报出来的，建议你自行搜索下 
- https://aistudio.baidu.com/paddle/forum/topic/show/1916624
- https://github.com/PaddlePaddle/Paddle/issues/49133

**Comment by gfhjjk** [comment]
我用paddlepaddle==2.3.1  paddlespeech==1.1.3 可以运行了
