### ISSUE TITLE
[ASR] paddlespeech的ASR流式部署有什么优势

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2798]
**大神们好。我有个问题想咨询下各位大神们。**

**Paddlespeech**的**ASR**流式部署，我看使用的是`fastapi`中的`WebSocket`进行部署的。以及有部分`APIRouter()`，这样部署和直接使用`pip install websockets`中的`websockets`，有什么样的优势和不同吗？

比如说，是效率更高吗？还是说更加能够避免某些问题？

另外，流式部署调用的时候，如果语音流传入间隔较大，是否会导致服务端无法及时收到数据和处理数据，导致服务自动关闭（ping tiomeout）呢？这样的情况可以控制和避免吗？

最后，如果使用Paddlespeech的这个部署方案，在预测器（模型）方面启动多个实例，异步调用的时候，能否实现多个实例同时预测（多个实例由同一个IP和PORT管理）

**非常感谢各位大神们的耐心阅读和解答。感谢。**

**Comment by zh794390558** [comment]
fastapi 支持 websocket，没有必要引入额外的包。另一个fastapi的底层应该是调用了websockets类似的包实现的。

间隔大会断掉服务，重新建链即可。

paddlespeech-server 是用来快速体验和部署的，高性能的部署可以关注 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/speechx 的进展。

有什么需求的话可以整理下，提一个feature request，PM会跟进的。

**Comment by iftaken** [comment]
您好，看到您正在使用PaddleSpeech，我们想进一步和您沟通下需求背景以及使用场景，以便打磨更优秀的产品，更好得支持您的项目。这是我们的联系方式：邮箱 paddlespeech@baidu.com，方便的话可以留下您的联系方式，我们 1 对 1 沟通下，谢谢！
