### ISSUE TITLE
用PyCharm使用语音转文字代码时报错

### ISSUE THREAD

**Issue by suna2000** [PaddlePaddle/PaddleSpeech#2804]
![image](https://user-images.githubusercontent.com/103914941/211036922-8e1fda56-da9b-4017-ba4e-ad7a81676dce.png)
如图，显示缺少paddle模块，在Anaconda pip安装又出现错误：
![image](https://user-images.githubusercontent.com/103914941/211037162-297ef9d2-a081-4427-8cd3-302d9b034ae1.png)

**Comment by zxcd** [comment]
目测是安装的时候缺少了common包
可以尝试pip install common
