### ISSUE TITLE
想知道在tts finetune微调模型中，可以在一个模型中微调多个自定义发音人吗

### ISSUE THREAD

**Issue by peiqianggao** [PaddlePaddle/PaddleSpeech#2805]
使用aishell多发音人模型，然后用自定义发音人A的数据集微调出来新的模型，替代了原模型中的spkid=0，

请问可以基于这个新的模型再使用自定义发音人B的数据集，替代原模型中的spkid=1，微调出包含两个自定义发音人的模型吗？

这样在使用微调后模型的时候，可以通过指定发音人id来合成不同音色的语音 ~

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842
