### ISSUE TITLE
如何设置paddlespeech的st识别中文音频并翻译为英语

### ISSUE THREAD

**Issue by wwbnjsace** [PaddlePaddle/PaddleSpeech#2806]
## General Question
如何设置paddlespeech的st识别中文音频并翻译为英语
paddlespeech st 如何设置使用什么模型，可以将中文音频文件翻译为英语文本？

**Comment by zh794390558** [comment]
st只支持en-zh，没有对应的数据集。

**Comment by zxcd** [comment]
可以尝试使用whisper模型。
调用如下：
`paddlespeech whisper --task translate --input ./zh.wav`
具体参数参考: https://github.com/PaddlePaddle/PaddleSpeech/tree/r1.3/demos/whisper

**Comment by wwbnjsace** [comment]
> 可以尝试使用whisper模型。 调用如下： `paddlespeech whisper --task translate --input ./zh.wav` 具体参数参考: https://github.com/PaddlePaddle/PaddleSpeech/tree/r1.3/demos/whisper

whisper不支持流式啊，或者已有的whisper流式速度太慢了
