### ISSUE TITLE
paddle:2.4.1-jupyter docker安装报错

### ISSUE THREAD

**Issue by tone2158** [PaddlePaddle/PaddleSpeech#2833]
我根据官网使用docker安装paddle:2.4.1-jupyter的版本的paddlepaddle后进行paddlespeech的安装
pip install paddlespeech安装过程报错找不到gcc，g++，应该是gcc的环境问题，包括还遇到了gcc-mutilib的相关报错
在 conda install gcc gxx后继续进行pip install paddlespeech，报以下图片中错误。
想请教一下 如何在docker paddle:2.4.1-jupyter容器中安装好gcc环境？

另外：paddle:2.4.1的docker环境是没问题的

  /opt/conda/compiler_compat/ld: cannot find /lib64/libpthread.so.0: No such file or directory
  /opt/conda/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
  Running setup.py clean for pyworld
  Building wheel for webrtcvad (setup.py) ... error

**Comment by linkec** [comment]
docker 版本不需要pip install， 是直接开箱即用的啊

**Comment by tone2158** [comment]
> docker 版本不需要pip install， 是直接开箱即用的啊

是安装paddlespeech的过程报错的。

/opt/conda/compiler_compat/ld: cannot find /lib64/libpthread.so.0: No such file or directory
/opt/conda/compiler_compat/ld: cannot find /usr/lib64/libpthread_nonshared.a: No such file or directory
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
----------------------------------------
ERROR: Failed building wheel for pyworld
Running setup.py clean for pyworld
Building wheel for webrtcvad (setup.py) ... error
ERROR: Command errored out with exit status 1:

**Comment by iftaken** [comment]
根据描述，并没有复现相关错误，使用是官网上的docker环境吗？[【Paddle官网入口】](https://www.paddlepaddle.org.cn/)

使用对应的docker

```bash
docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.1-jupyter
docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.4.1 /bin/bash
```

进入docker后安装PaddleSpeech

```bash
pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple
```

![image](https://user-images.githubusercontent.com/30135920/212827153-d1696edd-9760-433c-af72-be1d3f17f62b.png)
