### ISSUE TITLE
启动paddlespeech server报错Can't find "hifigan_vctk-zh" in resource.

### ISSUE THREAD

**Issue by peiqianggao** [PaddlePaddle/PaddleSpeech#2836]
使用 aishell3 的 am 想配置用 hifigan_vctk 的voc，但启动报错了，请问是什么原因呢
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/12654801/212663948-818e2dff-f401-4894-8f9d-0c5c348fd6ec.png">

**Comment by yt605155624** [comment]
hifigan_vctk 是英文的，请把 lang 改成 en
