### ISSUE TITLE
Is there an English model for streaming ASR?

### ISSUE THREAD

**Issue by adithya-tp** [PaddlePaddle/PaddleSpeech#2847]
## General Question

I tried changing the `lang` parameter in `streaming_asr_server/conf/ws_conformer_application` from 'zh' to 'en' and got the following error (when trying to run the server example given in the streaming ASR documentation):

`
AssertionError: Can't find "conformer_online_wenetspeech-en-16k" in resource. Model name must be one of ['conformer_online_wenetspeech-zh-16k', 'conformer_u2pp_online_wenetspeech-zh-16k', 'conformer_online_multicn-zh-16k', 'conformer_online_aishell-zh-16k', 'deepspeech2online_wenetspeech-zh-16k', 'deepspeech2online_aishell-zh-16k']
`

Is there any way to access English based streaming ASR engines? Do they exist yet? (The chinese engine works pretty well btw)

**Comment by zxcd** [comment]
There is no stream English ASR yet.

**Comment by litongjava** [comment]
is There stream English ASR now

**Comment by ScottXiao233** [comment]
现在是否支持流式的中英文混合的呢？
