### ISSUE TITLE
[speechX] 编译speechX出错：recipe for target 'all' failed

### ISSUE THREAD

**Issue by Tian14267** [PaddlePaddle/PaddleSpeech#2849]
大神们好。我在编译speechX的时候报错：
```
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2
```
请问这个是啥问题啊。
详细的编译LOG在压缩包里：
[nohup_log.zip](https://github.com/PaddlePaddle/PaddleSpeech/files/10526953/nohup_log.zip)

**Comment by Tian14267** [comment]
<img width="1482" alt="1" src="https://user-images.githubusercontent.com/27938135/215260219-e2114342-981f-4b09-bd7c-5949c85c383e.png">

**Comment by Tian14267** [comment]
<img width="246" alt="2" src="https://user-images.githubusercontent.com/27938135/215260336-7fe81dd7-70e0-44bc-b394-efa35768e37c.png">

**Comment by SmileGoat** [comment]
openfst 是不是没下载完成？error 是 fst/types.h 没有找到，

**Comment by SmileGoat** [comment]
openfst下载后解压，重新再编译一下，应该就可以了。
