### ISSUE TITLE
流式语音合成遇到的问题

### ISSUE THREAD

**Issue by yyanning** [PaddlePaddle/PaddleSpeech#2855]
在已经成功打开服务端的情况下，打开客户端的时候遇到了下面这个问题，请问应该怎么解决呢？
[   ERROR] - HTTPConnectionPool(host='127.0.0.1', port=8092): Max retries exceeded with url: /paddlespeech/tts/streaming/samplerate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021E36386EC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by yt605155624** [comment]
如果端口号和 protocal 都没有问题，可以尝试把 ip 地址换成绝对 ip 而不是 127.0.0.1
