### ISSUE TITLE
流式语音合成问题

### ISSUE THREAD

**Issue by yyanning** [PaddlePaddle/PaddleSpeech#2856]
请问一下，在流式语音合成中是否可以支持更改duration、pitch、energy 这些参数呢

**Comment by yaleimeng** [comment]
官方没有提供相关调整的参数。而且自己想加也不容易。因为TTS推理出来都是一连串的语音帧了，要在帧级别实时计算再输出。

**Comment by yt605155624** [comment]
更改 duration、pitch、energy 这些参数相当于推理了两遍，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2 不仅如此，流式合成我们也没有支持调速，因为流式合成的前提是 rtf<1，如果你把速度调快了，当前这条播放完下块还没合成好，就会有断断续续的听感

**Comment by i4never** [comment]
@yt605155624 推理两遍只是工程实现的问题吧？如果Fastpeech2模型的forward暴露的不是pitch这个tensor参数，而是pitch_scale/pitch_bias参数，完全可以在forward时候处理pitch的变换，energy同理。
