### ISSUE TITLE
ECAPA-TDNN语音克隆问题

### ISSUE THREAD

**Issue by xiaoyeye1117** [PaddlePaddle/PaddleSpeech#2857]
## General Question

尝试用vc2中提供的预训练模型跑了下voice cloning，但音色和参考人音色差异还蛮大呢，请问下，添加参考人音频重训speaker encoder是否会有改善呢；如果重训的话，音频采样率都是16k嘛？
另外，speaker encoder采样率是16k，声码器和合成器采样率是24k，这里采样率不匹配是不影响vc效果的吧

**Comment by yt605155624** [comment]
1. 应该不是参考人音频重新训练 speaker encoder，而是把 参考人音频 加到 vc2 的训练集里面和 aishell3 一起重新训练 vc2，可以跑一下 synthesize.sh，可以发现 vc2 对集内的 speaker 会比较像
2. 应该不影响，目前的声纹识别一般都是 16k 的，它只是一个提取特征的工具

**Comment by WhiteFu** [comment]
> 1. 应该不是参考人音频重新训练 speaker encoder，而是把 参考人音频 加到 vc2 的训练集里面和 aishell3 一起重新训练 vc2，可以跑一下 synthesize.sh，可以发现 vc2 对集内的 speaker 会比较像
> 2. 应该不影响，目前的声纹识别一般都是 16k 的，它只是一个提取特征的工具

大佬好，具体想问一下，一起训练，是说用参考人的音频做一下微调吗，
还有一个问题想请教的是，声纹识别的特征提出来之后要做什么归一化吗，方便和tts模型更好的适应。

**Comment by yt605155624** [comment]
1. 是的
2. 不做归一化，一般声纹特征都不做归一化，想做的话可以自己试试

**Comment by xiaoyeye668** [comment]
> 1. 应该不是参考人音频重新训练 speaker encoder，而是把 参考人音频 加到 vc2 的训练集里面和 aishell3 一起重新训练 vc2，可以跑一下 synthesize.sh，可以发现 vc2 对集内的 speaker 会比较像
> 2. 应该不影响，目前的声纹识别一般都是 16k 的，它只是一个提取特征的工具

肥肠感谢！
再请教一下~  重训vc2可以用tts3下的finetune脚本进行finetune嘛 ~ 或者就用vc2下的train.sh？

**Comment by xiaoyeye1117** [comment]
> 1. 应该不是参考人音频重新训练 speaker encoder，而是把 参考人音频 加到 vc2 的训练集里面和 aishell3 一起重新训练 vc2，可以跑一下 synthesize.sh，可以发现 vc2 对集内的 speaker 会比较像
> 2. 应该不影响，目前的声纹识别一般都是 16k 的，它只是一个提取特征的工具

肥肠感谢！
再请教一下~ 重训vc2可以用tts3下的finetune脚本进行finetune嘛 ~ 或者就用vc2下的train.sh？
