### ISSUE TITLE
[TTS][Android Demo]💡Paddle-Lite opt工具进行模型转换报错 -> 自行编译 develop 版本的 Paddle-Lite

### ISSUE THREAD

**Issue by Vincent2Liu** [PaddlePaddle/PaddleSpeech#2858]
在android的TTS中准备使用中英混合的声学模型fastspeech2_mix_static_0.2.0，在用OPT工具将其转换为paddlelite格式的过程中报错：
Error: This model is not supported, because 3 ops are not supported on 'arm'. These unsupported ops are: 'round, set_value,   share_data'，更换paddle_lite_opt为最新版本后转换也不成功，请问是ARM架构cpu本身对这三个算子不支持吗，还是说是模型的问题，请教？

**Comment by Vincent2Liu** [comment]
@yt605155624

**Comment by yt605155624** [comment]
如代码注释所述，https://github.com/PaddlePaddle/PaddleSpeech/blob/964211a81bb59d9f5da9a78cca95787e5bb219b8/examples/csmsc/tts3/run.sh#L66 请自行编译 develop 版本的 Paddle-Lite，目前 Paddle-Lite 的发行版（v2.12）没有支持这 3 个算子
- 编译 opt 工具参考 https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/model_optimize_tool.html
- 如果是要编译 python 包（因为我们的 shell 脚本里现在用的是 python 包带的功能而不是 opt 的二进制包，两者本质功能一样），参考 
https://www.paddlepaddle.org.cn/lite/v2.12/source_compile/linux_x86_compile_linux_x86.html
核心代码 （记得开启 --with_python=ON ）
```bash
 ./lite/tools/build_linux.sh --arch=x86 --with_python=ON --with_extra=ON
```

**Comment by Vincent2Liu** [comment]
> 如代码注释所述，
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/964211a81bb59d9f5da9a78cca95787e5bb219b8/examples/csmsc/tts3/run.sh#L66
> 
> 请自行编译 develop 版本的 Paddle-Lite，目前 Paddle-Lite 的发行版（v2.12）没有支持这 3 个算子
> * 编译 opt 工具参考 https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/model_optimize_tool.html
> * 如果是要编译 python 包（因为我们的 shell 脚本里现在用的是 python 包带的功能而不是 opt 的二进制包，两者本质功能一样），参考
>   https://www.paddlepaddle.org.cn/lite/v2.12/source_compile/linux_x86_compile_linux_x86.html
>   核心代码 （记得开启 --with_python=ON ）
> 
> ```shell
>  ./lite/tools/build_linux.sh --arch=x86 --with_python=ON --with_extra=ON
> ```

develop版本的paddlelite是支持这三个算子的是吗

**Comment by Vincent2Liu** [comment]
> 如代码注释所述，
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/964211a81bb59d9f5da9a78cca95787e5bb219b8/examples/csmsc/tts3/run.sh#L66
> 
> 请自行编译 develop 版本的 Paddle-Lite，目前 Paddle-Lite 的发行版（v2.12）没有支持这 3 个算子
> * 编译 opt 工具参考 https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/model_optimize_tool.html
> * 如果是要编译 python 包（因为我们的 shell 脚本里现在用的是 python 包带的功能而不是 opt 的二进制包，两者本质功能一样），参考
>   https://www.paddlepaddle.org.cn/lite/v2.12/source_compile/linux_x86_compile_linux_x86.html
>   核心代码 （记得开启 --with_python=ON ）
> 
> ```shell
>  ./lite/tools/build_linux.sh --arch=x86 --with_python=ON --with_extra=ON
> ```

我的valid_target是arm，这个https://www.paddlepaddle.org.cn/lite/v2.12/user_guides/model_optimize_tool.html  里面没找到编译develop版本的paddlelite的相关信息呢，能否告知一下具体的位置，多谢

**Comment by Vincent2Liu** [comment]
@yt605155624

**Comment by yt605155624** [comment]
有，请你仔细看下 ：）

**Comment by Vincent2Liu** [comment]
> 有，请你仔细看下 ：）

通过源码编译OPT工具时，在执行./lite/tools/build.sh build_optimize_tool命令时报错，如下所示
![20230201194800167](https://user-images.githubusercontent.com/45562874/216035357-9ed9fc97-b264-4ce0-8ef6-641fae381a5b.png)
请问报错是什么原因呢

**Comment by Vincent2Liu** [comment]
@yt605155624

**Comment by yt605155624** [comment]
看起来是你的代理有问题，Paddle-Lite 编译相关问题请移步 Paddle-Lite issue 区

**Comment by dota2015** [comment]
请问解决了吗？
