### ISSUE TITLE
关于 VectorExecutor抽取文本特征

### ISSUE THREAD

**Issue by yanchaoguo** [PaddlePaddle/PaddleSpeech#2869]
# from paddlespeech.cli.vector import VectorExecutor
请问paddlespeech支持同时抽取文本和语音特征吗，类似clip处理图像特征那样，基于双塔模型建立文本和语音的关联，可应用于文本对speech的检索系统

**Comment by zh794390558** [comment]
same to https://github.com/PaddlePaddle/PaddleSpeech/issues/2872
