### ISSUE TITLE
avg.sh best exp/deepspeech2/checkpoints 1  时报错  too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by 2954456878** [PaddlePaddle/PaddleSpeech#2870]
![9 VM}BY6QQ{QU$0X_YWN6L](https://user-images.githubusercontent.com/88914706/216286850-4a1cd039-a297-4b38-8628-563ff4af1ce1.png)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Failed in avg ckpt!

**Comment by zxcd** [comment]
可以使用pdb或者dump定位一下报错的具体位置。目前猜测可能是由于ckpt模型文件不存在。
