### ISSUE TITLE
punc可以导出推理模型以支持C++(如Paddle/FastDeploy或Paddle Inference)部署么？

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/PaddleSpeech#2873]

**Comment by zh794390558** [comment]
可以导出，可以参考paddlenlp中erine模型导出。

**Comment by hhxdestiny** [comment]
> 可以导出，可以参考paddlenlp中erine模型导出。

谢谢，我找到了关于erine的导出，但是未找到tokenizer部分的导出，请问这部分可以在在哪找到？

**Comment by zh794390558** [comment]
> > 可以导出，可以参考paddlenlp中erine模型导出。
> 
> 谢谢，我找到了关于erine的导出，但是未找到tokenizer部分的导出，请问这部分可以在在哪找到？

那是python的代码，无法导出。
