### ISSUE TITLE
ASRExecutor音频转汉字，含有部分英文，哪个model的效果最好？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSpeech#2888]
场景是给留学生辅导，主要语言中文，含有少量英文词汇，目前默认设置转换出来的效果
```
好的朋友们早上好呀来我给咱们共享一些屏幕好来那我们还是常规的来恰克一下能不能听到我说话呢
听到不能听到了咱们来个莫莉啊六六六都可以好的来拆可一下啊行
能听到吗诶能听到是吧好好我看你们没敲字我以为你们听不到好那我们来说一下今天咱们要干什么吧好吧那有些人如果说没有看上一节的课的话呢他可能有些差异说为什么杰森一
是直接打开了上节课的这个P皮器对吧好那我们今天因为上节课咱们留下来了一些遗留的问题对不对咱们上节课讲到了这个非的和普克的时候呢咱们就看了咱们说等到下节课的时候咱们来一起讲对不对
所以今天咱们要干的事的是咱们先把尚节课剩下的这些因用那发的知识讲完那咱们把这些新知识讲完之后再去讲一下这个拆文注理克的克特森陪神好好那么由于我之前也说了这个拆文注贝克的特
黑意思呢其实咱们写这两个小时但其实是他怎么说呢如果说它是一个喷心动斯克的话他值得两个小时你知道吗但是由于你们现在是一个陪审了那么无论说从你们个人的帕斯科的这个
啊
怎么说个人帕斯克的这个难艺程度上还是说你们准备这个帕斯克所需要的时间都比以前简单得多了你知道吧都比以前的这个门槛要低得多了所以呢就是说咱们也不需要那么长的时间来去讲你们的这个
```
感觉效果一般，需要自己训练吗？

**Comment by zxcd** [comment]
目前develop分支开源了一个中英混的识别模型，你可以尝试调用一下看看效果
`paddlespeech asr --model conformer_talcs --lang zh_en --codeswitch True --input ./ch_zh_mix.wav -v`

**Comment by zouhan6806504** [comment]
> 

尝试了一下，比纯中文的要好不少，但是真要实际使用，还是需要再训练的

**Comment by zxcd** [comment]
那你可以使用我们的模型和自己的一些数据再进行一下finetune，效果应该更好一些。

**Comment by zouhan6806504** [comment]
> 那你可以使用我们的模型和自己的一些数据再进行一下finetune，效果应该更好一些。

finetune中英文混合模型有教程吗？
我看了看https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/asr/data_preparation.md
感觉汉语可能不止这么标注吧，比如声调、多音词。再比如遇到oov词如何添加？

**Comment by zh794390558** [comment]
识别不需要考虑这些，按照release的model中的vocab处理label直接使用。
