### ISSUE TITLE
[TTS]tts_finetune/tts3/  用自己数据集finetune的时候遇到以下错误

### ISSUE THREAD

**Issue by 13604099691** [PaddlePaddle/PaddleSpeech#2889]
(TTS3.7) shang@USER-20221125QS:~/python/PaddleSpeech/examples/other/tts_finetune/tts3$ ./run.sh
check oov
get mfa result
CMD:  mfa_align ./input/lu/newdir tools/aligner/simple.lexicon tools/aligner/aishell3_model.zip ./mfa_result
align.py:60: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 142, in validate_args
  File "aligner/command_line/align.py", line 85, in align_corpus
  File "aligner/corpus.py", line 543, in speaker_utterance_info
ZeroDivisionError: division by zero
[11923] Failed to execute script align

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - GCC/G++ Version [e.g. 5]
 - Python Version [e.g. 3.7]
 - PaddlePaddle Version [e.g. 2.4]
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. RTX3090-24GB]
 - CUDA/CUDNN Version [e.g. cuda-11.6]
 - MKL Version
- TensorRT Version

**Additional context**

**Comment by yt605155624** [comment]
没遇到过这个问题，可以在 MFA 仓库搜搜报错，也可以再看看是不是提供的数据有问题不符合要求
