### ISSUE TITLE
使用attention_rescoring模式测试自己训练的模型时报错

### ISSUE THREAD

**Issue by upcmb** [PaddlePaddle/PaddleSpeech#2891]
出错的信息：
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/test.py", line 61, in <module>
    pr.runcall(main, config, args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/cProfile.py", line 121, in runcall
    return func(*args, **kw)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/test.py", line 32, in main
    main_sp(config, args)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/test.py", line 28, in main_sp
    exp.run_test()
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/training/trainer.py", line 361, in run_test
    self.test()
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/utils/mp_tools.py", line 27, in wrapper
    result = func(*args, **kwargs)
  File "<decorator-gen-532>", line 2, in test
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/exps/u2/model.py", line 401, in test
    metrics = self.compute_metrics(*batch, fout=fout)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/exps/u2/model.py", line 355, in compute_metrics
    reverse_weight=reverse_weight)
  File "<decorator-gen-524>", line 2, in decode
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 826, in decode
    reverse_weight=reverse_weight)
  File "/home/aistudio/work/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 536, in attention_rescoring
    assert hasattr(self.decoder, 'right_decoder')
AssertionError
Failed in evaluation!

使用的是配置如下：
conf_path=conf/chunk_conformer.yaml
decode_conf_path=conf/tuning/chunk_decode.yaml

chunk_conformer.yaml的内容：
############################################
#           Network Architecture           #
############################################
cmvn_file: 
cmvn_file_type: "json"
# encoder related
encoder: conformer
encoder_conf:
    output_size: 256    # dimension of attention
    attention_heads: 4
    linear_units: 2048  # the number of units of position-wise feed forward
    num_blocks: 12      # the number of encoder blocks
    dropout_rate: 0.1   # sublayer output dropout
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d # encoder input type, you can chose conv2d, conv2d6 and conv2d8
    normalize_before: True
    cnn_module_kernel: 15
    use_cnn_module: True
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'
    causal: true
    use_dynamic_chunk: true
    cnn_module_norm: 'layer_norm' # using nn.LayerNorm makes model converge faster
    use_dynamic_left_chunk: false
# decoder related
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1  # sublayer output dropout
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0
# hybrid CTC/attention
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1     # label smoothing option
    length_normalized_loss: false
    init_type: 'kaiming_uniform' # !Warning: need to convergence

###########################################
#                   Data                  #
###########################################

train_manifest: data/manifest.train
dev_manifest: data/manifest.dev
test_manifest: data/manifest.test

###########################################
#              Dataloader                 #
###########################################

vocab_filepath: data/lang_char/vocab.txt 
spm_model_prefix: ''
unit_type: 'char'
preprocess_config: conf/preprocess.yaml
feat_dim: 80
stride_ms: 10.0
window_ms: 25.0
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs 
batch_size: 32
maxlen_in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen_out: 150  # if output length > maxlen-out, batchsize is automatically reduced
minibatches: 0 # for debug
batch_count: auto
batch_bins: 0
batch_frames_in: 0
batch_frames_out: 0
batch_frames_inout: 0
num_workers: 2
subsampling_factor: 1
num_encs: 1

###########################################
#                 Training                #
###########################################
n_epoch: 240 
accum_grad: 24
global_grad_clip: 5.0
dist_sampler: True
optim: adam
optim_conf:
  lr: 0.001
  weight_decay: 1.0e-6
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
  lr_decay: 1.0
log_interval: 100
checkpoint:
  kbest_n: 50
  latest_n: 5

使用的chunk_decode.yaml内容如下：
beam_size: 10
decoding_method: attention # 'attention', 'ctc_greedy_search', 'ctc_prefix_beam_search', 'attention_rescoring'
ctc_weight: 0.5 # ctc weight for attention rescoring decode mode.
reverse_weight: 0.3 # reverse weight for attention rescoring decode mode.
decoding_chunk_size: 16 # decoding chunk size. Defaults to -1.
    # <0: for decoding, use full chunk.
    # >0: for decoding, use fixed chunk size as set.
    # 0: used for training, it's prohibited here. 
num_decoding_left_chunks: -1  # number of left chunks for decoding. Defaults to -1.
simulate_streaming: True  # simulate streaming inference. Defaults to False.
decode_batch_size: 128
error_rate_type: cer

**Comment by zxcd** [comment]
可以看一下代码，上面代码注释写的还挺清楚的。
https://github.com/PaddlePaddle/PaddleSpeech/blob/3a8ba2e24246f1283bfcfd149bd803e03987d4d3/paddlespeech/s2t/models/u2/u2.py#L535

因为你使用的decoder是transformer，所以reverse_weight不能>0.0
