### ISSUE TITLE
执行paddlespeech help 报错

### ISSUE THREAD

**Issue by 2954456878** [PaddlePaddle/PaddleSpeech#2901]
![image](https://user-images.githubusercontent.com/88914706/217702662-cbd368d1-f333-47a0-9aaa-9a1d24622d9e.png)

**Comment by zxcd** [comment]
应该是paddle安装不正确，建议按照官方文档进行安装。

**Comment by 2954456878** [comment]
> 应该是涉水安装不正确,建议按照官方文档进行安装。

pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

**Comment by 2954456878** [comment]
> 应该是涉水安装不正确,建议按照官方文档进行安装。

pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

**Comment by 2954456878** [comment]
> 应该是涉水安装不正确,建议按照官方文档进行安装。
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install pytest-runner
pip install 
都是按照文档进行安装的

**Comment by zxcd** [comment]
你完整的安装命令是什么？ 安装过程中是否报错？

**Comment by 2954456878** [comment]
> 你完整的安装命令是什么？ 安装过程中是否报错？

已解决
