### ISSUE TITLE
使用websocket_client.py 出现 keepalive timeout，中断传输

### ISSUE THREAD

**Issue by 2954456878** [PaddlePaddle/PaddleSpeech#2904]
在哪里能修改这个时长呢
![image](https://user-images.githubusercontent.com/88914706/217798468-3f1176a7-f6be-49f4-ab66-3a7a79a00274.png)

**Comment by yt605155624** [comment]
请提供详细执行命令和具体报错

**Comment by 2954456878** [comment]
> 请提供详细执行命令和具体报错
流式启动服务端，然后调用 websocket_client.py 进行检测，命令如下
python3.7 websocket_client.py --server_ip 183.230.21.79 --port 8090 --wavfile /mnt/1.wav

似乎是服务端在返回单个字开始和结束时间时用时太长，客户端长时间没有接受到数据以至于断开链接

**Comment by 2954456878** [comment]
> 请提供详细执行命令和具体报错

流式启动服务端，然后调用 websocket_client.py 进行检测，命令如下
python3.7 websocket_client.py --server_ip 127.0.0.1 --port 8090 --wavfile /mnt/1.wav

似乎是服务端在返回单个字开始和结束时间时用时太长，客户端长时间没有接受到数据以至于断开链接

**Comment by 2954456878** [comment]
> 请提供详细执行命令和具体报错
如果不需要在识别完文件后再次返回单个字的开始结束时间，应该怎么修改service代码呢
