### ISSUE TITLE
请问一下用自己的数据对声音分类模型进行微调，是要求数据一样长度嘛？或者对数据最长长度有要求嘛，大概是几秒到几秒之间合适呢？

### ISSUE THREAD

**Issue by shumeirao** [PaddlePaddle/PaddleSpeech#2906]

**Comment by zxcd** [comment]
目前我们开源的预训练模型是使用PANN数据集进行训练的。如果需要在其基础上进行微调，建议使用与该数据集类似的长度。

**Comment by shumeirao** [comment]
> 目前我们开源的预训练模型是使用PANN数据集进行训练的。如果需要在其基础上进行微调，建议使用与该数据集类似的长度。

还想请问一下我的数据集采样率是16000，模型cnn14的是32000，我的sr参数该怎么设置呢？还是我的数据要转换成32000的。

**Comment by zxcd** [comment]
数据需要转换成32000的
