### ISSUE TITLE
[TTS]使用gpu合成后显存未释放

### ISSUE THREAD

**Issue by shiyv132** [PaddlePaddle/PaddleSpeech#2908]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
我使用https://zhuanlan.zhihu.com/p/587765776中的代码块在anaconda的命令行窗口进行合成，windows11，gpu是rtx3050移动端，4g显存，发现每次运行完保存完文件之后显存一直维持在近满的状态，直到关闭窗口重进或退出python环境后重置。

**To Reproduce**
1.打开anaconda，进入虚拟环境，python版本3.8.16
2. 运行更改了待合成文本的代码块
3. 第一次合成正常，运行完后显存维持在3.7g左右，等待一两分钟无果
4. 再次合成即报错，显示（翻译）未能分配足够（大概500m）显存，剩余0，退出重新进入合成能正常运行，但又出现以上情况

**Expected behavior**

**Screenshots**
![wrong](https://user-images.githubusercontent.com/125204819/218322977-378741f9-7228-4e77-ace1-23067ce81832.png)

**Environment (please complete the following information):**
 - OS: [Windows11家庭版美版22623.1255]
 - GCC/G++ Version [gcc (MinGW.org GCC-6.3.0-1) 6.3.0]
 - Python Version [3.8.16]
 - PaddlePaddle Version [paddlepaddle-gpu  2.4.1.post117]
![image](https://user-images.githubusercontent.com/125204819/218323300-55e5cf8e-5061-4f62-9a6a-008eaa8a4bc7.png)

 - Model Version [？]声码器是pwgan_aishell3_static_1.1.0，模型是我在飞桨ai studio上代码块微调后导出的
 - GPU/DRIVER Informationo [e.g. Tesla V100-SXM2-32GB/440.64.00]
 - CUDA/CUDNN Version [cuda-11.7/cudnn8.8？or8.4]
![image](https://user-images.githubusercontent.com/125204819/218323715-829da62e-c475-40cf-8677-a12e1b0a8fd0.png)
![image](https://user-images.githubusercontent.com/125204819/218323862-ef3977a0-28f2-4ec4-9b40-5a0fc83f043c.png)
![image](https://user-images.githubusercontent.com/125204819/218323871-c49b5919-1f3e-4629-981a-eb0d36a8b973.png)

 - MKL Version
- TensorRT Version

**Additional context**
我paddlespeech本来是使用源码编译安装的，会显示paddlespeech0.0.0，于是我用pip install paddlespeech==1.3重新安装的

**Comment by iftaken** [comment]
在命令行里面变量占用的显存在关闭前是不释放的，你把这部分的代码写在py文件里面，看看多次运行是否可以

**Comment by shiyv132** [comment]
> 在命令行里面变量占用的显存在关闭前是不释放的，你把这部分的代码写在py文件里面，看看多次运行是否可以

感谢回复，是正常的就好，我是小白不懂写文件而且要经常合成新文本所以就重开吧，抱歉
还有就是paddlespeech源码编译安装的时候会自动安装版本**0.0.0**，
我是按安装说明的命令git clone https://github.com/PaddlePaddle/PaddleSpeech.git
cd PaddleSpeech
pip install pytest-runner
pip install .
安装的，不知道什么问题，希望优化一下，没问题就没事了

**Comment by iftaken** [comment]
> > 在命令行里面变量占用的显存在关闭前是不释放的，你把这部分的代码写在py文件里面，看看多次运行是否可以
> 
> 感谢回复，是正常的就好，我是小白不懂写文件而且要经常合成新文本所以就重开吧，抱歉 还有就是paddlespeech源码编译安装的时候会自动安装版本**0.0.0**， 我是按安装说明的命令git clone https://github.com/PaddlePaddle/PaddleSpeech.git cd PaddleSpeech pip install pytest-runner pip install . 安装的，不知道什么问题，希望优化一下，没问题就没事了

这是正常的，使用源码编译的方式就是最新develop版本的0.0.0，如果是pip install paddlespeech 则会安装发行版本的，带有版本号，比如当前最新发行版本是1.3，后续会持续升级
