### ISSUE TITLE
请问是否有client.py 客户端脚本进行流式传输数据到/paddlespeech/asr/streaming这个接口的，而不用客户端去下载全套paddlespeech

### ISSUE THREAD

**Issue by 2954456878** [PaddlePaddle/PaddleSpeech#2910]

**Comment by zxcd** [comment]
你是指不安装paddlespeech的情况下使用client.py进行语音识别吗

**Comment by 2954456878** [comment]
> 你是指不安装paddlespeech的情况下使用client.py进行语音识别吗

是的 不安装paddlespeech的情况下，是否有client.py脚本，进行流式传输音频流到服务端进行实时识别

**Comment by zxcd** [comment]
这个目前没有

**Comment by 2954456878** [comment]
> 这个目前没有

请问是否有这方面的计划，不可能每个客户端都需要来安装paddlespeech吧

**Comment by iftaken** [comment]
不安装PaddleSpeech 可以参考这个文件构造自己的客户端，https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/tests/asr/online/microphone_client.py，
Web版本的前端可以参考（编译后的，可以直接用）：
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/streaming_asr_server/web，
Vue 前端源码可以参考：
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/speech_web/web_client/src/components/SubMenu/ASR/RealTime/RealTime.vue
这几种都可以不用安装PaddleSpeech，但是还是建议在客户端安装PaddleSpeech，可以跟随版本迭代一起升级
