### ISSUE TITLE
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

### ISSUE THREAD

**Issue by joy0921** [PaddlePaddle/PaddleSpeech#2917]
使用paddlespeech时报错
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

环境
python3.8 pandas1.5.3

看了其他模块下相同的报错 说是python3.7升到3.8就解决了 可是我的python版本本来就是3.8 请问是什么原因

**Comment by yt605155624** [comment]
请提供下具体的使用命令

**Comment by joy0921** [comment]
> 请提供下具体的使用命令

执行案例中的命令
paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav

**Comment by yt605155624** [comment]
辛苦提供下完整的报错栈吧，看看是哪个模块引起的，你也可以再看看 pandas 的版本

**Comment by joy0921** [comment]
> 辛苦提供下完整的报错栈吧，看看是哪个模块引起的，你也可以再看看 pandas 的版本

/usr/local/lib/python3.8/site-packages/librosa/core/constantq.py:1059:DeprecationWarning:`np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations 
  dtype=np.complex,
Attributeerror:'_lzma.LZMADecompressor' object has no attribute 'needs_input'[root@877a4802b03d bin]#
这是报错信息

我也怀疑过是pandas版本问题 降低到1.4.3也不行 如果是版本问题 目前不知道pandas哪个版本适用

**Comment by yt605155624** [comment]
```bash
Python 3.8.16 (default, Dec  7 2022, 01:12:13)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
>>> pandas.__version__
'1.5.3'
>>>
```
这个您参考下吧，类似问题应该很多，可以再搜搜，实在不行换 paddle 版本

另外可以参考如下链接打印更多信息，现在报错栈不全
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2792
