### ISSUE TITLE
[TTS]粤语模型a韵的字发不出音

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSpeech#2935]
测试了几句，有几个a韵的字发不出音，分别是：
![image](https://user-images.githubusercontent.com/51190264/219414415-fb0c078a-183a-46b5-9804-3bb02ce10142.png)

然后我用“啊啊啊啊啊”试了一个极端情况，然后phone_id_map报错，应该是a相关的音没有被训练
![image](https://user-images.githubusercontent.com/51190264/219414771-30712ea1-20a6-46be-9926-e09903e66300.png)
![image](https://user-images.githubusercontent.com/51190264/219414794-a23eac57-2b9a-4ddb-82dd-bc1bd4cec6cd.png)

**Comment by JiehangXie** [comment]
🐎
“老屋飞入只外来雁，鸡同鸭讲眼碌碌”
“只”是多音字，“鸭”生成不了音

**Comment by yt605155624** [comment]
fixed by https://github.com/PaddlePaddle/PaddleSpeech/pull/2950
