### ISSUE TITLE
Docker hub上的跑不动，卡住了，缺 上lib包

### ISSUE THREAD

**Issue by bnuzhouwei** [PaddlePaddle/PaddleSpeech#2938]
手动装好后，跑不起来，一直卡着，GPU最新版本

```
OSError: cannot load library 'libsndfile.so': libsndfile.so: cannot open shared object file: No such file or directory
```

安装apt install libsndfiel1

接着报

```
TypeError: declarative() got an unexpected keyword argument 'property'λ d9ed99f2a49e /app/static/test 
```

**Comment by yt605155624** [comment]
第一个问题：
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2926
第二个问题：
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2512

**Comment by bnuzhouwei** [comment]
为什么没有通过测试的东西，就传到了DockerHub上，作为一个官方镜像发布平台也太随意了

**Comment by yt605155624** [comment]
DockerHub 上的东西应该是 PaddleCloud 提供的，可以去 PaddleCloud 反馈
