### ISSUE TITLE
在使用MFA的时候提示There were words not found in the dictionary. Would you like to abort to fix them? (Y/N)

### ISSUE THREAD

**Issue by CnYiXiaoNaiHe** [PaddlePaddle/PaddleSpeech#2941]
训练为中文语料，这种忽略（N）的话会有什么影响吗

**Comment by lym0302** [comment]
会有一些不在词典内的音素片段被分成词典内的音素，具体可以去 MFA 的官网上看看

**Comment by lym0302** [comment]
词典外的单词会变成spn，spn不在我们simple.lexicon那个发音字典里面，会在 phone_id_map.txt 里

**Comment by CnYiXiaoNaiHe** [comment]
官方考虑有时间出一些针对小白的0基础操作的视频讲解吗，从基本使用到自己动手操作。比如中文语音合成，从数据预处理标准到MFA，声学模型的训练，再到最后的合成微调。感觉视频的方式会更加直观

**Comment by yt605155624** [comment]
不会出那么细节的教程
- 文字版参考：https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842
- TTS 原理参考：https://aistudio.baidu.com/aistudio/course/introduce/25130

**Comment by CnYiXiaoNaiHe** [comment]
1. 
![image](https://user-images.githubusercontent.com/44515739/220553176-d2bd147c-4417-473f-9181-741c3d0b14c5.png)
使用MFA，run当中默认的生成字典方式。这个生成的是否符合中文词典呢

**Comment by CnYiXiaoNaiHe** [comment]
> 不会出那么细节的教程
> 
> * 文字版参考：[✨ 关于训练一个自己的TTS模型 #1842](https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842)
> * TTS 原理参考：https://aistudio.baidu.com/aistudio/course/introduce/25130
使用MFA，run当中默认的生成字典方式。这个生成的是否符合中文词典呢
