### ISSUE TITLE
非流式语音合成服务中官方案例换成自己finetune的多人说话模型后报错

### ISSUE THREAD

**Issue by myhaha** [PaddlePaddle/PaddleSpeech#2947]
在非流式语音合成服务的官方案例中，我将配置文件application.yaml中tts部分改成了如图所示
![image](https://user-images.githubusercontent.com/38137923/220529138-a01b0741-d3ce-469e-9f74-85f68de39c6d.png)
通过 paddlespeech_server start --config_file application.yaml 命令启动服务，但是报错了如图：
![image](https://user-images.githubusercontent.com/38137923/220528734-91b048b0-9e28-498e-8bad-826a93f93ebb.png)
官方给的application.yaml是关于单人模型配置的，我改成多人模型的就报错了，请问下应该怎么修改？

**Comment by yt605155624** [comment]
磁盘空间不足
