### ISSUE TITLE
关于流式服务器 并发识别的问题

### ISSUE THREAD

**Issue by 2954456878** [PaddlePaddle/PaddleSpeech#2948]
paddlespeech_server start 启动流式服务器后
通过 paddlespeech_client asr_online  进行识别调用
开启单个线程，识 时长 audio duration: 50.181, elapsed time: 26.64584755897522
开启2个线程  识别时长 audio duration: 50.181, elapsed time: 83.6750648021698

服务端是不能多线程处理识别请求吗？ 为什么同时处理2个识别请求，花费的时长翻倍

**Comment by zxcd** [comment]
目前服务暂不支持多线程。

**Comment by 2954456878** [comment]
> 目前服务暂不支持多线程。

是否有类似的开发计划，单线程服务端 只能用于测试

**Comment by zxcd** [comment]
您好，您反馈的功能已经在开发中。敬请期待 PaddleSpeech未来新功能的推出，谢谢！

**Comment by springbootyp** [comment]
> 您好，您反馈的功能已经在开发中。敬请期待 PaddleSpeech未来新功能的推出，谢谢！

你好，请问开发中是否已经完成? 有最新进展嘛？
