### ISSUE TITLE
[ASR][ERROR] - offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000

### ISSUE THREAD

**Issue by gooloosk** [PaddlePaddle/PaddleSpeech#2949]
[ERROR] - offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000
使用conformer_online_wenetspeech模型进行流式语音识别，模型启用几分钟后会这个错误。想问一下这个该如何修改改进？
[ERROR] - offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000        
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\paddlespeech\server\engine\asr\online\python\asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "D:\Anaconda3\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 375, in _decorate_function        
    return self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddlespeech\s2t\modules\subsampling.py", line 144, in forward            x, pos_emb = self.pos_enc(x, offset)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line  948, in __call__
    return self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddlespeech\s2t\modules\embedding.py", line 164, in forward
    assert offset + x.shape[
AssertionError: offset: 4992 + x.shape[1]: 16 is larger than the max_len: 5000

**Comment by zxcd** [comment]
conformer_online_wenetspeech模型输入单条语音最长50s，建议使用vad，或者其他切分方法从语音层面进行操作。

**Comment by gooloosk** [comment]
使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存

**Comment by LDBS666** [comment]
> 使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存

您好，请问在PaddleSpeech-develop的哪个路径下的哪个py文件中调用这个方法？具体在文件中的哪个位置呢？

**Comment by gooloosk** [comment]
> > 使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存
> 
> 您好，请问在PaddleSpeech-develop的哪个路径下的哪个py文件中调用这个方法？具体在文件中的哪个位置呢？

https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/asr/online/python/asr_engine.py

**Comment by LDBS666** [comment]
> > > 使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存
> > 
> > 
> > 您好，请问在PaddleSpeech-develop的哪个路径下的哪个py文件中调用这个方法？具体在文件中的哪个位置呢？
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/asr/online/python/asr_engine.py

抱歉老师，我刚才没表述清晰，我知道这个方法在您回复的这个路径文件中，我想咨询一下这个方法应该在哪个py脚本中的哪个位置进行调用？我在下图中的infer.py中的 _check() 函数中调用了这个方法，但是好像没有效果，超出max_len之后还是报错。所以在哪个位置调用这个方法才能在到达临界时间时成功的清除缓存呢？
![在哪调用model_reset()](https://github.com/PaddlePaddle/PaddleSpeech/assets/74717678/1b2c9e91-2f1b-4ffe-82b7-39057ecf5ccc)

**Comment by LDBS666** [comment]
> > > 使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存
> > 
> > 
> > 您好，请问在PaddleSpeech-develop的哪个路径下的哪个py文件中调用这个方法？具体在文件中的哪个位置呢？
> 
> https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/asr/online/python/asr_engine.py

您好，我在代码执行过程中发现，这个方法直接引用的话会报错“PaddleASRConnectionHanddler”没有实例化，改成PaddleASRConnectionHanddler().model_reset()之后报错缺少参数“asr_engine”，请问如何正确传参呀？如何往里面传参？本人新手，对这个底层代码研究还不够深入555555

**Comment by gooloosk** [comment]
> > > > 使用PaddleASRConnectionHanddler.model_reset()重置模型清除缓存
> > > 
> > > 
> > > 您好，请问在PaddleSpeech-develop的哪个路径下的哪个py文件中调用这个方法？具体在文件中的哪个位置呢？
> > 
> > https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/server/engine/asr/online/python/asr_engine.py
> 
> 您好，我在代码执行过程中发现，这个方法直接引用的话会报错“PaddleASRConnectionHanddler”没有实例化，改成PaddleASRConnectionHanddler().model_reset()之后报错缺少参数“asr_engine”，请问如何正确传参呀？如何往里面传参？本人新手，对这个底层代码研究还不够深入555555

不好意思，我也不太懂，如果你搞明白了可以贴一下解决方法
