### ISSUE TITLE
 'gbk' codec can't decode byte 0x96 in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by 19920716** [PaddlePaddle/PaddleSpeech#2954]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

![image](https://user-images.githubusercontent.com/19903385/221125827-d8670ab0-6b9b-443b-85ba-dc4555550e26.png)

**Comment by jirengu** [comment]
在windows系统上按照官方教程安装后出现类似的错误，为什么问题没解决就直接关掉Issuse了呢
