### ISSUE TITLE
[S2T]'gbk' codec can't decode byte 0x96 in position 2: illegal multibyte sequence

### ISSUE THREAD

**Issue by 19920716** [PaddlePaddle/PaddleSpeech#2955]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ win 10]
 - Python Version 3.10.6
 - PaddlePaddle Version 2.4.2  gpu
 - Model Version [2.0.0]
 - GPU/DRIVER Informationo [3070 ti]
 - CUDA/CUDNN Version cuda-10.2
 - MKL Version
- TensorRT Version

**Additional context**
![image](https://user-images.githubusercontent.com/19903385/221125895-5a490dbc-f5aa-4205-a748-aacf967b7cfe.png)

**Comment by 19920716** [comment]
![image](https://user-images.githubusercontent.com/19903385/221334210-b4b46c34-a330-493c-b651-2006109fda16.png)
修改这个就Ok了，读取中文问题

**Comment by pmwangyang** [comment]
给力，用你的方法成功了。


>
