### ISSUE TITLE
使用样例代码报错

### ISSUE THREAD

**Issue by suc-suc** [PaddlePaddle/PaddleSpeech#2956]
from paddlespeech.cli.asr.infer import ASRExecutor

audio = "zh.wav"
asr = ASRExecutor()
result = asr(audio_file=audio, force_yes=True)
print(result)
![1677227556294](https://user-images.githubusercontent.com/59003815/221131554-546d534a-6828-4801-94b2-74bcb4e05099.jpg)

**Comment by zxcd** [comment]
Duplicate with https://github.com/PaddlePaddle/PaddleSpeech/issues/2512
