### ISSUE TITLE
HifiGan的csmsc中的例子需要什么环境和库?

### ISSUE THREAD

**Issue by wrz1999** [PaddlePaddle/PaddleSpeech#2960]
HifiGan的csmsc中的例子需要什么环境和库?装了最新版本的会报错，能否提供一个指定版本的requirements.txt文件并标注对应版本号。目前在预处理阶段就卡住了。

**Comment by yt605155624** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/setup.py
