### ISSUE TITLE
[TTS] MFA 报错 No such file or directory: "xx/xx/xx/train/mfcc/raw_mfcc.0.scp

### ISSUE THREAD

**Issue by CnYiXiaoNaiHe** [PaddlePaddle/PaddleSpeech#2963]
执行如下脚本
export PATH="$MFA_DOWNLOAD_DIR/montreal-forced-aligner/bin"
if [ ! -d "$EXP_DIR/baker_alignment" ]; then
    echo "Start MFA training..."
    mfa_train_and_align $EXP_DIR/baker_corpus "$EXP_DIR/$LEXICON_NAME.lexicon" $EXP_DIR/baker_alignment -o $EXP_DIR/baker_model --clean --verbose --temp_directory $EXP_DIR/.mfa_train_and_align
    # mfa_align $EXP_DIR/baker_corpus "$EXP_DIR/$LEXICON_NAME.lexicon"  
    echo "training done!"
    echo "results: $EXP_DIR/baker_alignment"
    echo "model: $EXP_DIR/baker_model"
fi

报如下错误
![image](https://user-images.githubusercontent.com/44515739/221458737-a31b2aed-f450-4397-935d-4f2355cbf421.png)

按照#2437的方法查看到
![image](https://user-images.githubusercontent.com/44515739/221458927-4bb174fc-f72d-44ea-95d9-174509aa8257.png)

libgfortran3已经安装，但是不知道是什么原因导致的这个问题，请指教下

**Comment by yt605155624** [comment]
再仔细看下 log, 不一定是缺 libgfortran3 也可能是缺别的

**Comment by CnYiXiaoNaiHe** [comment]
log里面只有我截图的那两条信息，没有其他的信息了

**Comment by yt605155624** [comment]
去 MFA 官方仓库问问 https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

**Comment by CnYiXiaoNaiHe** [comment]
已解决，除了缺少libgfortran3库外，主要还是缺少前置条件kaldi，安装完kaldi报错基本解决了。可以给其他开发者科普下
