### ISSUE TITLE
流式语音识别,如何将单次识别时长缩短

### ISSUE THREAD

**Issue by ArvinCharl** [PaddlePaddle/PaddleSpeech#2966]
我在使用asr_engine进行流式语音识别的过程中, 发现单次识别中,最后一个字的开始:结束时间差很大, 请问如何缩短这个时长差距
(word time stamp中的最后一个字的开始时间戳和结束时间戳中间差了好多秒)
![image](https://user-images.githubusercontent.com/26082263/221577882-2e6067c6-fe77-4ae6-b1d9-27b440616fa4.png)
我使用的模型为: "conformer_online_wenetspeech"

**Comment by zxcd** [comment]
因为最后一个字的时间戳默认为语音结束，你可以看看是不是语音本身的尾部静音比较长

**Comment by ArvinCharl** [comment]
> 因为最后一个字的时间戳默认为语音结束，你可以看看是不是语音本身的尾部静音比较长

在我们的场景里面，开启流式识别后，会说一些短句来识别，说一段后会安静等待一段时间，在这个等待的过程中，之前的文本会持续输出一段时间，这个持续输出的过程就是这个最后一个字的时间戳的延长时间。安静一段时间后，文本输出会为空。我们的需求就是让其尽快认为上一段结束，也就是尽快输出空文本。请问如何进行控制呢？

**Comment by ArvinCharl** [comment]
似乎问题已解决，ctc_endpoint.py中，缩短silence-timeout即可
