### ISSUE TITLE
🌟 安装PaddleSpeech相关问题讨论（Windows，mac），以及命令行使用问题

### ISSUE THREAD

**Issue by wangling6666** [PaddlePaddle/PaddleSpeech#2967]
请问怎么在命令行运行PaddleSpeech？是在CMD中直接运行吗？为什么我的显示不是内部或外部命令，也不是可运行的程序？

**Comment by iftaken** [comment]
是不是没有正确安装PaddleSpeech呀，安装PaddleSpeech可以参考这个部分：https://github.com/PaddlePaddle/PaddleSpeech#installation
