### ISSUE TITLE
[TTS]fastspeech2_aishell3 android 报错

### ISSUE THREAD

**Issue by kFoodie** [PaddlePaddle/PaddleSpeech#2975]
fastspeech2_csmsc正常跑，换成了fastspeech2_aishell3就报错了
```
A/Paddle-Lite: [F  3/ 1 16:59: 1.950 ...lite/kernels/arm/lookup_table_compute.cc:53 Run] Check failed: (ids_data[i] < row_number): 2338328217695289344!<306 look uptable ids[i] < row_number check failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20221 (Predictor Worke), pid 20168 (e.lite.demo.tts)
```
模型用的是 https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_aishell3_pdlite_1.3.0.zip
请问是啥原因啊？怎么解决？
<img width="872" alt="08f0b755bc2b822fa3495ea0c1c7029" src="https://user-images.githubusercontent.com/16017418/222092941-6b4ab206-949b-49db-a3b1-0627d82c6a6a.png">

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2933

**Comment by kFoodie** [comment]
> Duplicate of #2933

用这个模型https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_aishell3_ckpt_1.1.0.zip，然后改了这里
![image](https://user-images.githubusercontent.com/16017418/222099715-0e6ca559-fa2f-4316-90c0-a4142643cf5b.png)
然后还是报错了。。
![image](https://user-images.githubusercontent.com/16017418/222099825-c787bb0b-c45e-44b0-b6cc-653969330218.png)

csmsc，改完int32就正常。。

**Comment by kFoodie** [comment]
解决了。新增3行代码就行。。更新后的java代码如下：
![image](https://user-images.githubusercontent.com/16017418/222102960-9a7c4f53-a25d-4896-bbd0-3fa6d8603990.png)

**Comment by ChengsongLu** [comment]
> > Duplicate of #2933
> 
> 用这个模型[https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_aishell3_ckpt_1.1.0.zip，然后改了这里](https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_aishell3_ckpt_1.1.0.zip%EF%BC%8C%E7%84%B6%E5%90%8E%E6%94%B9%E4%BA%86%E8%BF%99%E9%87%8C) ![image](https://user-images.githubusercontent.com/16017418/222099715-0e6ca559-fa2f-4316-90c0-a4142643cf5b.png) 然后还是报错了。。 ![image](https://user-images.githubusercontent.com/16017418/222099825-c787bb0b-c45e-44b0-b6cc-653969330218.png)
> 
> csmsc，改完int32就正常。。

你好，请问改完模型怎么编译成Android可以用的？
