### ISSUE TITLE
是否有可部署在ARM Linux上的中文文本处理前端Demo?

### ISSUE THREAD

**Issue by Coinsinical** [PaddlePaddle/PaddleSpeech#2981]
## General Question
目前只在utils内找到用于中文文本正则化的zh_tn.py，不知道是否有其他的组成部分（如G2P）的实现代码？看了TTSAndroid的demo，这一部分并没有实现，个人从头实现感觉比较困难

**Comment by yt605155624** [comment]
如果你的 arm Linux 可以跑 python 的话（比如 mac m1），可以直接用我们目前的 python 实现，参考 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/paddlespeech/t2s/frontend
如果想实现 java、c++ 版本的文本前端，TTS Android demo 目前不包含文本前端（暂时官方也没有人力做），但是可以参考阉割版 cpp 前端进行交叉编译后调用（需要自己写 cmake 等，我们只提供了核心代码）: 
中文前端 https://github.com/lym0302/paddlespeech_tts_cpp
英文 g2p https://github.com/yazone/g2pE_mobile

如果你也在研究 TTS Android demo, 可以扫码进这个群
![image](https://user-images.githubusercontent.com/24568452/223328246-0feb87d8-62c6-400f-9138-f8ddb8c1ee70.png)

**Comment by Coinsinical** [comment]
我的平台是aarch64的Linux开发板，我注意到目前的python实现导入paddle，我的开发板无法安装，只能使用paddle lite,请问这种情况是否会对python的前端实现有影响？还是说仅需要对代码进行微调即可使用？谢谢回答

**Comment by yt605155624** [comment]
python 前端只是用了 paddle.to_tensor() 功能，应该只需要微调就可以使用，刚才二维码发错了，已更新

**Comment by yt605155624** [comment]
@Coinsinical 开发者给我们贡献了 ARM Linux c++ 的推理代码，目前也是没有前端的（他后续计划把 https://github.com/lym0302/paddlespeech_tts_cpp 引入进来），欢迎试用 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/TTSArmLinux
 （开发者也在群里）

**Comment by Coinsinical** [comment]
感谢帮助，目前我已经完成了python使用paddle lite运行模型的部署，正在对已有的python前端进行修改适配，但是由于前端使用了paddlenlp,改动量可能比较大，如果能成功修改部署，我很乐意将代码贡献出来

**Comment by yt605155624** [comment]
看你说到开发板无法安装 paddle, 是否可以尝试源码编译 arm 版本的 paddle, 参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/arm-compile.html

**Comment by ningpengtao-coder** [comment]
想加群，麻烦再分享一下二维码。

**Comment by ChengsongLu** [comment]
> 想加群，麻烦再分享一下二维码。

1

**Comment by XTaoWang** [comment]
拉我进群 微信号：wangtao7647
