### ISSUE TITLE
[TTS]粤语TTS在numpy==1.22.4环境下报错

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/PaddleSpeech#2982]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_3653/4288988082.py in <cell line: 9>()
      7 from paddle.static import InputSpec
      8 import fastdeploy as fd
----> 9 from paddlespeech.t2s.exps.syn_utils import get_am_inference
     10 
     11 fastspeech2_model_url = "https://paddlespeech.bj.bcebos.com/Parakeet/released_models/fastspeech2/fastspeech2_canton_ckpt_1.4.0.zip"

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/__init__.py in <module>
     17 from . import exps
     18 from . import frontend
---> 19 from . import models
     20 from . import modules
     21 from . import ssml

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/models/__init__.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .ernie_sat import *
     15 from .fastspeech2 import *
     16 from .hifigan import *

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/models/ernie_sat/__init__.py in <module>
     13 # limitations under the License.
     14 from .ernie_sat import *
---> 15 from .ernie_sat_updater import *

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/models/ernie_sat/ernie_sat_updater.py in <module>
     22 
     23 from paddlespeech.t2s.modules.losses import MLMLoss
---> 24 from paddlespeech.t2s.training.extensions.evaluator import StandardEvaluator
     25 from paddlespeech.t2s.training.reporter import report
     26 from paddlespeech.t2s.training.updaters.standard_updater import StandardUpdater

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/training/__init__.py in <module>
     13 # limitations under the License.
     14 from .cli import *
---> 15 from .experiment import *

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/training/experiment.py in <module>
     21 from visualdl import LogWriter
     22 
---> 23 from paddlespeech.t2s.utils import checkpoint
     24 from paddlespeech.t2s.utils import mp_tools
     25 

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/utils/__init__.py in <module>
     13 # limitations under the License.
     14 from . import checkpoint
---> 15 from . import display
     16 from . import layer_tools
     17 from . import mp_tools

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddlespeech/t2s/utils/display.py in <module>
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 import librosa.display
     15 import matplotlib.pylab as plt
     16 

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/librosa/display.py in <module>
     47 import numpy as np
     48 from matplotlib.cm import get_cmap
---> 49 from matplotlib.axes import Axes
     50 from matplotlib.ticker import Formatter, ScalarFormatter
     51 from matplotlib.ticker import LogLocator, FixedLocator, MaxNLocator

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/matplotlib/axes/__init__.py in <module>
      2                         unicode_literals)
      3 
----> 4 from ._subplots import *
      5 from ._axes import *

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/matplotlib/axes/_subplots.py in <module>
      5 from six.moves import map
      6 
----> 7 from matplotlib.gridspec import GridSpec, SubplotSpec
      8 from matplotlib import docstring
      9 import matplotlib.artist as martist

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/matplotlib/gridspec.py in <module>
     25 
     26 import matplotlib as mpl
---> 27 from matplotlib import _pylab_helpers, tight_layout, rcParams
     28 from matplotlib.transforms import Bbox
     29 import matplotlib._layoutbox as layoutbox

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/matplotlib/tight_layout.py in <module>
     13 
     14 import matplotlib
---> 15 from matplotlib.transforms import TransformedBbox, Bbox
     16 
     17 from matplotlib.font_manager import FontProperties

/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/matplotlib/transforms.py in <module>
     40 
     41 import numpy as np
---> 42 from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
     43     update_path_extents)
     44 from numpy.linalg import inv

ImportError: numpy.core.multiarray failed to import

**Comment by yt605155624** [comment]
很奇怪，我换了个环境，Ubuntu 16.04， python 3.7.0, numpy version == 1.21.6 在命令行可以正常执行如下语句
```bash
paddlespeech tts --am fastspeech2_canton --voc pwgan_aishell3 --input "各个国家有各个国家嘅国歌" --lang canton --spk_id 10
```
执行如下语句也可以正常执行（真正调用了 `from paddlespeech.t2s.exps.syn_utils import get_am_inference`）
```bash
source path.sh

FLAGS_allocator_strategy=naive_best_fit \
FLAGS_fraction_of_gpu_memory_to_use=0.01 \
python3 ${BIN_DIR}/../synthesize_e2e.py \
  --am=fastspeech2_aishell3 \
  --am_config=fastspeech2_canton_ckpt_1.4.0/default.yaml \
  --am_ckpt=fastspeech2_canton_ckpt_1.4.0/snapshot_iter_140000.pdz \
  --am_stat=fastspeech2_canton_ckpt_1.4.0/speech_stats.npy \
  --voc=pwgan_aishell3 \
  --voc_config=pwg_aishell3_ckpt_0.5/default.yaml \
  --voc_ckpt=pwg_aishell3_ckpt_0.5/snapshot_iter_1000000.pdz \
  --voc_stat=pwg_aishell3_ckpt_0.5/feats_stats.npy \
  --lang=canton \
  --text=${BIN_DIR}/../sentences_canton.txt \
  --output_dir=exp/default/test_e2e \
  --phones_dict=fastspeech2_canton_ckpt_1.4.0/phone_id_map.txt \
  --speaker_dict=fastspeech2_canton_ckpt_1.4.0/speaker_id_map.txt \
  --spk_id=10 \
  --inference_dir=exp/default/inference
```
可能和 FD、操作系统、其他基础依赖库版本等都有关系，不是单纯 numpy 版本的问题

**Comment by JiehangXie** [comment]
测试环境：Aistudio默认环境



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月3日(星期五) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSpeech] [TTS]粤语TTS在numpy==1.22.4环境下报错 (Issue #2982)





 
很奇怪，我换了个环境，Ubuntu 16.04， python 3.7.0, numpy version == 1.21.6 在命令行可以正常执行如下语句
 paddlespeech tts --am fastspeech2_canton --voc pwgan_aishell3 --input "各个国家有各个国家嘅国歌" --lang canton --spk_id 10
 
可能和 FD、操作系统等都有关系，不是单纯 numpy 版本的问题

**Comment by yt605155624** [comment]
已验证
AIStudio paddle 2.4.0 环境下 python 版本是 3.7
![image](https://user-images.githubusercontent.com/24568452/222679631-6f8ab3af-e136-4d72-97b3-a4c66f6e7bef.png)

AIStudio paddle 2.4.1 环境下 python 版本是 3.9
安装的时候无需加 `--user`, 确实会报错
