### ISSUE TITLE
[S2T] Can't start server with zh_en model

### ISSUE THREAD

**Issue by wangtiance** [PaddlePaddle/PaddleSpeech#2985]
When I start server with such config yaml:

################### speech task: asr; engine_type: python #######################
asr_python:
    model: 'conformer_talcs'
    lang: 'zh_en'
    sample_rate: 16000
    cfg_path: # [optional]
    ckpt_path: # [optional]
    decode_method: 'attention_rescoring'
    num_decoding_left_chunks: -1
    force_yes: True
    device:  # set 'gpu:id' or 'cpu'

I get error message:

paddlespeech_server start --config_file asr.yaml
[2023-03-03 17:55:11,828] [    INFO] - start to init the engine
[2023-03-03 17:55:11,828] [    INFO] - asr : python engine.
[2023-03-03 17:55:11,916] [   ERROR] - Failed to start server.
[2023-03-03 17:55:11,916] [   ERROR] - codeswitch is true only in zh_en model

But I can't find a place to set codeswitch to True. However, 'conformer_talcs-codeswitch_zh_en-16k' is indeed in the list of available models.

**Comment by zxcd** [comment]
目前server没加入codeswitch对应参数，暂时不能调用，或者你尝试修改一下代码

**Comment by achaosss** [comment]
> 目前server没加入codeswitch对应参数，暂时不能调用，或者你尝试修改一下代码

怎么改，把asr那部分的调用方式改掉吗
