### ISSUE TITLE
请问PaddleSpeech/examples/csmsc/voc5中PTQ_static.sh跑不通

### ISSUE THREAD

**Issue by longRookie** [PaddlePaddle/PaddleSpeech#2992]
问题：请问PaddleSpeech/examples/csmsc/voc5中PTQ_static.sh跑不通
我在运行PaddleSpeech/examples/csmsc/voc5的run.sh的过程中，在stage=3时程序报错。
对应运行命令：
![image](https://user-images.githubusercontent.com/68834517/223012996-b6846af4-6c42-4186-a6e8-1d09333eb24a.png)

对应报错截图：
![image](https://user-images.githubusercontent.com/68834517/223013282-33d46563-e52e-4083-a136-5839b5d66a05.png)
这里是hifigan训练后的输出文件夹：
![image](https://user-images.githubusercontent.com/68834517/223013355-8706fff9-9111-4048-8b26-b6e1673e3cee.png)

运行环境：
![image](https://user-images.githubusercontent.com/68834517/223013528-649bd484-ef27-4ca4-ba04-5fe5ff9243a5.png)

请问，我应该如何解决

**Comment by yt605155624** [comment]
PTQ_static.sh 依赖 develop 版本的 PaddleSlim，但是现在该模型导出还有问题，正在联合 PaddleSlim 一起解决，等解决后会通知你

**Comment by longRookie** [comment]
谢谢
