### ISSUE TITLE
如何将模型训练后的pdz文件转为pdmodel

### ISSUE THREAD

**Issue by longRookie** [PaddlePaddle/PaddleSpeech#2994]
## 如何将模型训练后的pdz文件转为pdmodel
训练后得到
![image](https://user-images.githubusercontent.com/68834517/223025316-2ff6857c-cca9-41a3-b865-12ead5835b38.png)

请问我如何得到hifigan_csmsc.pdmodel

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/aae9fa7f3cb9f4daefa422fd3613d15a46e43038/examples/csmsc/tts3/run.sh#L34 把 local/synthesize_e2e.sh 里面的 pwgan 换成 hifigan(换下 stage)

**Comment by longRookie** [comment]
谢谢
