### ISSUE TITLE
[S2T]在AIstudio中安装存在依赖问题

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/PaddleSpeech#2998]
![image](https://user-images.githubusercontent.com/54951765/223350322-513c3784-5191-42aa-a7bb-c13ec9969e66.png)
复现方式：新建一个项目，然后在终端中pip install paddlespeech

**Comment by zxcd** [comment]
目前版本依赖可能有些冲突，但不影响使用，我们后续会对版本进行维护

**Comment by DongDongBan** [comment]
在自家平台上都没解决好依赖关系，谁敢用啊！

**Comment by iftaken** [comment]
> 在自家平台上都没解决好依赖关系，谁敢用啊！

非常抱歉，由于我们的问题，给您带来了不佳的体验。我们将在后续的开发中解决安装依赖的相关问题，感谢您的理解。
