### ISSUE TITLE
流式TTS并发效率问题（CPU）

### ISSUE THREAD

**Issue by 443127316** [PaddlePaddle/PaddleSpeech#3003]
大佬，您好, 问题如标题，cpu型号为：Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
1）在server端，我仿照tts_api.py 中的 async def websocket_endpoint(websocket: WebSocket)，进行编写，2）client端我仿照 audio_handler.py 中的class TTSWsHandler类 进行改写。
目前，并发数为2，感觉首包延迟和RTF呈线性增长，cpu使用效率为75%，详细情况如图：
![image](https://user-images.githubusercontent.com/22590720/223420181-3c78e6a4-341c-4969-be79-0c90f5e00470.png)
问题猜测：通过server端的log显示，请求的时候，是并行请求，但是处理任务的时候，可能是串行处理。
请问，在paddle框架中，是否遇到过类似问题，如何解决呢？

**Comment by yt605155624** [comment]
你的后端使用的是 paddle 动态图？ paddle 静态图？ onnxruntime？

**Comment by 443127316** [comment]
用的是paddle静态图

**Comment by yt605155624** [comment]
paddle 静态图推理，好像不支持多线程（比如可能需要新建多个predictor 处理彩瓷那个），具体你可以去 paddle 仓库搜搜或者提问，我也不是很清楚

**Comment by yt605155624** [comment]
另外你可以换成 onnxruntime-cpu 试试，他本身可以选择 cpu_threads

**Comment by 443127316** [comment]
我试一下onnxruntime-cpu，辛苦了啊，大佬

**Comment by 443127316** [comment]
已经使用了ONNX模型，效果拔群：
cpu型号：Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz
八字左右，并发6次，RTF约为 0.9。
供参考

**Comment by lixf071213** [comment]
可以通过paddlespeech server里用的框架uvicorn去解决吗？

**Comment by 184653090** [comment]
请问您最后有没有解决TTS服务的并发问题

**Comment by lixf071213** [comment]
> 请问您最后有没有解决TTS服务的并发问题

用官方提供的框架uvicorn去解决并发问题，这个框架可以启动多个worker去解决并发问题。
    uvicorn.run(
        "start_multi_progress_server:app",
        host=config.host,
        port=config.port,
        debug=True,
        workers=args.workers)
可以参考一下这个方法。
