### ISSUE TITLE
能否对字母数字混合的文本进行语音合成？

### ISSUE THREAD

**Issue by 0-Maxwei-0** [PaddlePaddle/PaddleSpeech#3016]
我有一段文本是字母数字混合的，例如A1234B567C89这种，我希望字母采用英文发音，数字采用中文发音，该如何实现呢？

**Comment by yt605155624** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSpeech/issues/2895

**Comment by 0-Maxwei-0** [comment]
> Duplicate of #2895

感谢回复，向再请教一下有没有参数可以控制分词的使用，比如我想合成一个字一个字念的语音，不需要考虑上下文进行分词。

**Comment by 0-Maxwei-0** [comment]
> Duplicate of #2895

thanks！
