### ISSUE TITLE
为什么我训练的声音克隆模型生成的声音是数据集里的人声，不是参考文件夹里的wav文件的人声呢？ /example/aishell3/vc1/

### ISSUE THREAD

**Issue by Vebrun** [PaddlePaddle/PaddleSpeech#3017]
其中am_ckpt是我迁移学习训练出来的单人模型，voc_ckpt是下载的预训练模型。同时我还有个疑问：voc_ckpt是需要我迁移学习吗？还是直接就用下载的预训练权重呢，readme在这点没有说明。
![image](https://user-images.githubusercontent.com/95894804/224256640-cf15f16e-a7de-4a86-93e9-6b6e2270c6ab.png)

**Comment by yt605155624** [comment]
1. 可以根据需求决定是否要用自己的数据集 finetune vocoder
2. 一句话声音克隆效果有限，可以使用小样本合成 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3

**Comment by zyb8543d** [comment]
@yt605155624 遇到同样的问题，能给解答下嘛，是我哪里设置的对吗
