### ISSUE TITLE
关于fs2的帧级别和音素级别

### ISSUE THREAD

**Issue by hhm853610070** [PaddlePaddle/PaddleSpeech#3024]
## General Question
有几个问题，如下：
1.这里的fastspeech2模型实现中关于pitch和energy使用的是帧级别还是音素级别特征啊，并且是否进行了normalization？
2.我在另一个fs2项目基础上使用了帧级别和音素级别用中文数据集进行了实验（那个项目没人维护了...），发现音素级别+nz效果最好，其它的效果都不太好，如帧级别、帧级别+nz、音素级别，或多或少都有问题，如杂音、声音失真、错误的汉字发音（发音为其它汉字），不知道是本身对于中文数据效果不太好，还是MFA对齐不够准确，又或者是其它问题，不知道你们是否进行了类似的实验吗？

**Comment by yt605155624** [comment]
音素级别，做了 norm，具体代码参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/319c805968916cf5cb9146e73fd15ce4cfbd574a/examples/csmsc/tts3/run.sh#L21
