### ISSUE TITLE
TTS推理接口无法指定gpu id

### ISSUE THREAD

**Issue by JunZhan2000** [PaddlePaddle/PaddleSpeech#3029]
用docker安装的paddlespeech，paddlespeech/t2s/exps/syn_utils.py的get_predictor函数里没有device_id参数，默认用了GPU 0。。
<img width="718" alt="image" src="https://user-images.githubusercontent.com/43952592/224693208-47596d5a-c3cc-4120-9ef2-9573d280e2ff.png">

而最新的github里的源码里是有的
（docker安装）
<img width="816" alt="image" src="https://user-images.githubusercontent.com/43952592/224693489-59eebb23-bac3-41e3-bec2-b7dac01ff398.png">
（源码安装）
<img width="510" alt="image" src="https://user-images.githubusercontent.com/43952592/224693684-2761e37a-ba58-4c9f-b9ae-107f79fc9ac3.png">

用docker安装后，指定不了gpu，这会让人很困扰

**Comment by JunZhan2000** [comment]
我自己手动修改源码，是可以的，但是花了很久定位问题

**Comment by yt605155624** [comment]
fixed by 
- https://github.com/PaddlePaddle/PaddleSpeech/pull/3019

You can
- https://github.com/PaddlePaddle/PaddleSpeech/issues/2472
