### ISSUE TITLE
[TTS] Fastspeech2训练与推断不一致

### ISSUE THREAD

**Issue by sdli1995** [PaddlePaddle/PaddleSpeech#3032]
现有的实现转换为固定文本长度推理时发现的
包含conv1d的ffn 与  pitch predictor 这些均有这个问题  

训练是都是在批数据上pad  第一层transformer layer没问题但是经过第一层之后所有的pad位置都是有数值的 第二层进行conv1d时有效长度边缘之外的值就不是0了 而推理时因为长度是有效长度 有效长度外的conv1d是pad为0的

**Comment by yt605155624** [comment]
"现有的实现转换为固定文本长度推理时发现的" 是指 fastspeech2_cnndecoder 的流式推理嘛？ 如果是流式推理，需要计算正确的 pad 值后，才能和非流式的保持一致，参考直播课 https://aistudio.baidu.com/aistudio/course/introduce/25130 流式语音合成部分
