### ISSUE TITLE
Why is there conformer model not available for english/librispeech while running the asr inference?

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3033]

**Comment by zxcd** [comment]
You can find conformer librispeech asr model here:
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md#speech-recognition-model

**Comment by khushbookk** [comment]
[--model {conformer_wenetspeech,conformer_online_wenetspeech,conformer_u2pp_online_wenetspeech,conformer_online_multicn,conformer_aishell,conformer_online_aishell,transformer_librispeech,deepspeech2online_wenetspeech,deepspeech2offline_aishell,deepspeech2online_aishell,deepspeech2offline_librispeech}]
I can't find it here, how do I run the conformer model?

**Comment by zxcd** [comment]
you can simply try add it to https://github.com/PaddlePaddle/PaddleSpeech/blob/4e9bca177a16eedc00950d7128cb707b35317d08/paddlespeech/resource/pretrained_models.py#L339

**Comment by khushbookk** [comment]
I can't figure out the value for md5.

**Comment by zxcd** [comment]
you can use `md5sum` to get md5 value.
