### ISSUE TITLE
Why do asr give less accurate results for longer length audios?

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3034]

**Comment by zxcd** [comment]
Which model do you use? 

Generally speaking, the speech length supported by the model is related to its training data and framework. If the training data of the model is short, it may not be very good for long speech. 

In this case, we recommend using vad to segment voice.

**Comment by khushbookk** [comment]
With a 3 minutes long test clip, deepspeech2offline_librispeech model gave error : "Please input audio file less then 50 seconds."
while transformer_librispeech resulted the transcript with no error. Although with a 28 sec audio chunk from the same clip , transformer_librispeech gave more accurate results.

**Comment by zxcd** [comment]
This should be because of transformer released model is better than deepspeech2.  
You can find WER(1-accuracy) information here: https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md#speech-recognition-model
