### ISSUE TITLE
中文语音识别

### ISSUE THREAD

**Issue by shudong-zhang** [PaddlePaddle/PaddleSpeech#3048]
## General Question

哪位大佬能科普一下中文语音识别是怎么编码的？英文中26个英文字母+一些标点，中文是怎么做的呢？我跑提供的语音识别demo看到log文件里有5000多个字的字典，中文在训练的时候也用这么大的字典吗？这个字典在代码里哪里能找到？

**Comment by zxcd** [comment]
一般来说字典是跟着模型走的，你下载released model的时候能够在`data/lang_chat/vocab.txt`中找到对应的字典。

**Comment by zxcd** [comment]
对于语音识别来说5000字不算大。训练和推理使用的都是一个字典，也就是`data/lang_chat/vocab.txt`。

**Comment by shudong-zhang** [comment]
> 对于语音识别来说5000字不算大。训练和推理使用的都是一个字典，也就是`data/lang_chat/vocab.txt`。

好的，多谢！
