### ISSUE TITLE
Can I do transfer learning with the transformer_librispeech_en model in speech recognition?

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3074]

**Comment by zxcd** [comment]
Of course, you can use your own dataset to fine-tune the transformer_librispeech_en model. A simple tutorial can be found here https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972

**Comment by khushbookk** [comment]
How do I load the checkpoints from the pretrained model?

**Comment by zxcd** [comment]
You can download transformer_librispeech_en model, and unzip file, eg:`PaddleSpeech/examples/librispeech/asr1`
