### ISSUE TITLE
asr 时候如何能默认输入 y？

### ISSUE THREAD

**Issue by youfanx** [PaddlePaddle/PaddleSpeech#3081]
## General Question

···
C:\Users\R-wtg>paddlespeech asr --lang zh --input d:\1.mp3
C:\Users\R-wtg\AppData\Roaming\Python\Python310\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
C:\Users\R-wtg\AppData\Roaming\Python\Python310\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\R-wtg\AppData\Roaming\Python\Python310\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\R-wtg\AppData\Roaming\Python\Python310\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\R-wtg\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\core\constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
C:\Users\R-wtg\AppData\Local\Programs\Python\Python310\lib\site-packages\paddleaudio\_extension.py:141: UserWarning: paddleaudio C++ extension is not available.
  warnings.warn("paddleaudio C++ extension is not available.")
C:\Users\R-wtg\AppData\Roaming\Python\Python310\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
2023-03-22 23:19:34.242 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
2023-03-22 23:19:34.345 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
Input(Y/N):

···
这个input 如果输入n 就退出了，输入y会继续执行， 能否默认就输入y的效果 不要再用户输入了？ 谢谢。

环境： win10   python 3.10 

PaddleSpeech： 1.4

**Comment by zxcd** [comment]
这个是语音格式不对，需要进行格式转化时候的提示。如果不想一直输入可以有两个选择，一个是自己改一下代码，不提示直接转，另一个是提前通过工具把语音转成一个规定的格式。

**Comment by youfanx** [comment]
收到 谢谢
