### ISSUE TITLE
文字转音频API 问题

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#3087]
```python
from paddlespeech.cli.tts.infer import TTSExecutor
tts = TTSExecutor()
tts(text="今天天气十分不错。", output="output.wav")
```

文字转音频

怎么在这个API基础上
自定义男女声音  发音速度

现在教程太乱   代码量太杂

**Comment by lym0302** [comment]
参考这里的代码：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/cli/tts/infer.py，这个方法只能选模型，选 spkid，不能控制发音速度。想修改速度这个看这个：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/style_fs2
