### ISSUE TITLE
基于多说话者模型finetune出自己的tts语音模型之后服务部署问题

### ISSUE THREAD

**Issue by myhaha** [PaddlePaddle/PaddleSpeech#3125]
根据以下教程finetune出自己的音色模型之后https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tts_finetune/tts3
通过以下教程部署了自己微调之后的模型，方式是将自己训练好的模型替换到 ~/.paddlespeech/models/fastspeech2_aishell3-zh/目录下，现在服务器上只能跑一个服务，我想将自己微调之后的其他音色的几个模型也部署到该服务器上应该怎么操作呢？
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/speech_server/README_cn.md

**Comment by lym0302** [comment]
不是很理解你的意思，微调之后是一个模型还是多个模型，目前 speech_server 支持一个tts 服务对应一个模型
