### ISSUE TITLE
CI报错信息

### ISSUE THREAD

**Issue by longRookie** [PaddlePaddle/PaddleSpeech#3136]
## 这个报错.........
应该如何处理
![image](https://user-images.githubusercontent.com/68834517/229826305-4b2de113-27d7-4af0-8085-ab4b926423e4.png)

**Comment by yt605155624** [comment]
代理问题，先不用管 CI, 先改好代码逻辑，CI 问题最后合入时我们会处理

**Comment by longRookie** [comment]
好的，谢谢
