### ISSUE TITLE
CI的codestyle无法通过

### ISSUE THREAD

**Issue by longRookie** [PaddlePaddle/PaddleSpeech#3138]
我在本地进行pre-commit检查；
![image](https://user-images.githubusercontent.com/68834517/230082753-bd030bae-ae36-4c68-a02e-af02d98b9c30.png)

在效率云上报错：
![image](https://user-images.githubusercontent.com/68834517/230083071-37b265c9-4fb6-4d9f-a3aa-9dc2cb203850.png)

**Comment by yt605155624** [comment]
可以关注下这个 pr https://github.com/PaddlePaddle/PaddleSpeech/pull/3128, 报错是 trailing whitespace 相关，简单的 CodeStyle 问题不影响 pr 合入

**Comment by yt605155624** [comment]
可能是你本地 flake8 版本太旧导致的，CI机器上flake8的版本是5.0.4，可以尝试更新下重新 pre-commit 修改代码风格，或者自己手动修改代码风格

**Comment by longRookie** [comment]
好的，谢谢

**Comment by longRookie** [comment]
![image](https://user-images.githubusercontent.com/68834517/230532299-5c0e3832-2c0c-4308-8e74-b7e1bd4af9ce.png)

**Comment by longRookie** [comment]
> 可能是你本地 flake8 版本太旧导致的，CI机器上flake8的版本是5.0.4，可以尝试更新下重新 pre-commit 修改代码风格，或者自己手动修改代码风格

未能复现，暂不知道具体原因
![image](https://user-images.githubusercontent.com/68834517/230536115-86d37b80-ad57-42c7-aa34-e84323f44d08.png)
