### ISSUE TITLE
[S2T]使用erine模型做标点预测，使用 gpu推理，会有内存泄漏现象

### ISSUE THREAD

**Issue by dahu1** [PaddlePaddle/PaddleSpeech#3147]
**Describe the bug**
使用 PaddleSpeech/examples/iwslt2012/punc0，finetune  ernie-3.0-base-zh 模型，做gpu的标点推理，会发现有内存泄漏的现象，（显存不会增加，内存会缓慢增加），不知道是不是paddle的版本的问题。请帮忙看一下。
使用 PaddleSpeech/docker/ubuntu16-gpu/Dockerfile 进行编译paddle 。

**Screenshots**
![image](https://user-images.githubusercontent.com/22560013/230846183-e88d1e5c-5638-4205-9e7f-a0d72ad99924.png)

**Environment (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - GCC/G++ Version [gcc (GCC) 8.2.0]
 - Python Version [Python 3.7.13]
 - PaddlePaddle Version 
    paddle-bfloat==0.1.7
    paddle2onnx==1.0.6
    paddlefsl==1.1.0
    paddlenlp==2.5.0
    paddlepaddle-gpu==2.3.1.post112
    x2paddle==1.4.0

 - Model Version [ernie-3.0-base-zh]
 - GPU/DRIVER Informationo [NVIDIA GeForce RTX 3090-24GB/470.57.02]
 - CUDA/CUDNN Version [CUDA Version: 11.4 ]

**Comment by zh794390558** [comment]
先查下是否在GPU上跑，正常应该是显存增长，内存不变吧。

另一个查看下输入的text是否过长，可以用定长的文本测试。

另一个检查下是否有reqest后中间的某些状态没有清除。

paddlepaddle-gpu版本用2.4.2稳定版本，或者develop最新开发版本。

**Comment by dahu1** [comment]
> 先查下是否在 GPU 上跑，正常应该是显存增长，内存不变吧。
> 
> 另一个查看下输入的 text 是否过长，可以用定长的文本测试。
> 
> 另一个检查下是否有 reqest 后中间的某些状态没有清除。
> 
> paddlepaddle-gpu 版本用 2.4.2 稳定版本，或者 develop 最新开发版本。

请问一下  paddlepaddle-gpu==2.4.2 安装的dockfile有吗？ OS  、GCC/G++ 、CUDA 的版本号可以提供吗？
我在本地安装有这个问题：
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
最早使用paddlepaddle-gpu==2.3.1.post112 这个版本，是因为 根据 PaddleSpeech/docker/ubuntu16-gpu/Dockerfile 可以正确编译好，而其他版本的paddle-gpu版本并没有找到 相关的dockerfile。

**Comment by zh794390558** [comment]
> 请问一下 paddlepaddle-gpu==2.4.2 安装的dockfile有吗？ OS 、GCC/G++ 、CUDA 的版本号可以提供吗？

可以看下官网的信息。docker用官网最新release的就可以。

**Comment by dahu1** [comment]
> > 请问一下 paddlepaddle-gpu==2.4.2 安装的 dockfile 有吗？ OS 、GCC/G++ 、CUDA 的版本号可以提供吗？
> 
> 可以看下官网的信息。docker 用官网最新 release 的就可以。

好的，谢谢，参考官网安装了paddlepaddle-gpu==2.4.2.post112 ，同时调整了推理代码，现在正常了，感谢答疑。
