### ISSUE TITLE
how to initialize self.visualizer? Should I use SummaryWriter?

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3192]

**Comment by zh794390558** [comment]
please see here https://github.com/PaddlePaddle/PaddleSpeech/blob/07f566e0a57417ac30f4275e745b7c6e89745c41/paddlespeech/s2t/training/trainer.py#L427

**Comment by khushbookk** [comment]
Got it. Thank you.
