### ISSUE TITLE
How to visualize the graph of the asr model? 

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3195]

**Comment by zxcd** [comment]
maybe you can try VisualDL https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/visualdl_usage_cn.html

**Comment by khushbookk** [comment]
How do I save the graph definition?
Do I have to edit the source code?

**Comment by zh794390558** [comment]
export model and visual the  model, please see  https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/examples/wenetspeech/asr1/local/export.sh


 or, print(model.summary())
