### ISSUE TITLE
ValueError: The additional config (combine_params) of `paddle.jit.save` is not supported. Failed in export!

### ISSUE THREAD

**Issue by khushbookk** [PaddlePaddle/PaddleSpeech#3204]

**Comment by zh794390558** [comment]
Please using latest paddlepaddle.

**Comment by khushbookk** [comment]
I have pulled the latest docker image "docker pull paddlecloud/paddlespeech:develop-gpu-cuda10.2-cudnn7-latest".

**Comment by zh794390558** [comment]
Please install paddlepaddle develop version:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/3038472/234785674-d8af54cc-b119-450d-aa0d-596e934872f2.png">
