### ISSUE TITLE
请问文档样音LJSpeech(英文)女声是哪一个模型和声码器生成的呢？

### ISSUE THREAD

**Issue by thehzzz** [PaddlePaddle/PaddleSpeech#3207]
### Discussed in https://github.com/PaddlePaddle/PaddleSpeech/discussions/3159

<div type='discussions-op-text'>

<sup>Originally posted by **thehzzz** April 13, 2023</sup>
地址：https://paddlespeech.readthedocs.io/en/latest/tts/demo.html
样音：Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition

我尝试了LJSpeech模型和对应的声码器，不能生成这个女声</div>

**Comment by zh794390558** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/3038472/234784707-83988304-6a35-40e7-b630-0a68e863170e.png">

仔细看下，标红的地方说明了模型。

**Comment by thehzzz** [comment]
> <img alt="图像" width="873" src="https://user-images.githubusercontent.com/3038472/234784707-83988304-6a35-40e7-b630-0a68e863170e.png">
> 
> 仔细看下，标红的地方说明了模型。

感谢回复，我想要的是“Printing, in the only sense with which we are at present concerned, differs from most if not from all the arts and crafts represented in the Exhibition” 这个找这个女音。
