### ISSUE TITLE
使用ASR推理时的ValueError，(InvalidArgument) Broadcast dimension mismatch.

### ISSUE THREAD

**Issue by great-wind** [PaddlePaddle/PaddleSpeech#3246]
## General Question

在运行下述代码时，出现了ValueError，请问怎么解决？
```
from paddlespeech.cli.asr.infer import ASRExecutor
asr = ASRExecutor()
result = asr(audio_file="zh.wav")
print(result)
```
报错信息如下：
```
[   ERROR] - (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
Traceback (most recent call last):
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/cli/asr/infer.py", line 323, in infer
    simulate_streaming=cfg.simulate_streaming)
  File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 356, in _decorate_function
    return func(*args, **kwargs)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 827, in decode
    reverse_weight=reverse_weight)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 546, in attention_rescoring
    num_decoding_left_chunks, simulate_streaming)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 428, in _ctc_prefix_beam_search
    simulate_streaming)  # (B, maxlen, encoder_dim)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 234, in _forward_encoder
    num_decoding_left_chunks=num_decoding_left_chunks
  File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/modules/encoder.py", line 184, in forward
    num_decoding_left_chunks)
  File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/modules/mask.py", line 202, in add_optional_chunk_mask
    chunk_masks = masks.logical_and(chunk_masks)  # (B, L, L)
  File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/tensor/logic.py", line 117, in logical_and
    return _C_ops.logical_and(x, y)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
```
请问这是什么原因造成的？

**Comment by guigenyi** [comment]
我也遇到了，感觉这个框架好垃圾啊

**Comment by zxcd** [comment]
能否提供一下paddle和paddlespeech的版本？

**Comment by ybb03** [comment]
遇到同样问题，容器中执行报错，使用版本如下：
paddlepaddle-gpu            2.4.0rc0
paddleslim                  2.4.1
paddlespeech                0.0.0
paddlespeech-ctcdecoders    0.2.1
paddlespeech-feat           0.1.0

**Comment by great-wind** [comment]
paddle使用的版本是paddlepaddle-gpu 2.4.0rc0；
paddlespeech使用的是develop分支；
@zxcd

**Comment by breaveSun** [comment]
我也遇到相同的问题
Name: paddlepaddle-gpu
Version: 2.4.2.post117
Name: paddleslim
Version: 2.4.1
Name: paddlespeech
Version: 0.0.0
Name: paddlespeech-ctcdecoders
Version: 0.2.1
Name: paddlespeech-feat
Version: 0.1.0
请问你们解决了嘛

**Comment by zxcd** [comment]
目前develop版本paddlespeech上会有一些适配paddle==2.5的不兼容升级。因此如果需要使用paddlepaddle-gpu<2.5的情况下，建议使用paddlespeech<=1.4.1的版本

**Comment by great-wind** [comment]
paddlepaddle-gpu 2.4.0rc0版本，结合paddlespeech1.4.0版本，可解决

**Comment by LjPro** [comment]
> paddlepaddle-gpu 2.4.0rc0版本，结合paddlespeech1.4.0版本，可解决

那是需要源码编译方式安装paddlepaddle-gpu 2.4.0rc0版本吗？

**Comment by ljh-coder** [comment]
> ## General Question
> 在运行下述代码时，出现了ValueError，请问怎么解决？
> 
> ```
> from paddlespeech.cli.asr.infer import ASRExecutor
> asr = ASRExecutor()
> result = asr(audio_file="zh.wav")
> print(result)
> ```
> 
> 报错信息如下：
> 
> ```
> [   ERROR] - (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
>   [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
> Traceback (most recent call last):
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/cli/asr/infer.py", line 323, in infer
>     simulate_streaming=cfg.simulate_streaming)
>   File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 356, in _decorate_function
>     return func(*args, **kwargs)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 827, in decode
>     reverse_weight=reverse_weight)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 546, in attention_rescoring
>     num_decoding_left_chunks, simulate_streaming)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 428, in _ctc_prefix_beam_search
>     simulate_streaming)  # (B, maxlen, encoder_dim)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/models/u2/u2.py", line 234, in _forward_encoder
>     num_decoding_left_chunks=num_decoding_left_chunks
>   File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
>     return self.forward(*inputs, **kwargs)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/modules/encoder.py", line 184, in forward
>     num_decoding_left_chunks)
>   File "/home/yuyinshibie/PaddleSpeech-develop/paddlespeech/s2t/modules/mask.py", line 202, in add_optional_chunk_mask
>     chunk_masks = masks.logical_and(chunk_masks)  # (B, L, L)
>   File "/home/root/anaconda3/envs/speech_env/lib/python3.7/site-packages/paddle/tensor/logic.py", line 117, in logical_and
>     return _C_ops.logical_and(x, y)
> ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
>   [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
> ```
> 
> 请问这是什么原因造成的？

可以参考 #3697 看看有没有帮助，可以尝试在 asr(audio_file="zh.wav",model='conformer_wenetspeech') 方法中指定模型，经测试后，可以正常使用，没有报错。
