### ISSUE TITLE
Speech Server一键部署语音服务时TTS句首句末发音不全

### ISSUE THREAD

**Issue by menfanjia** [PaddlePaddle/PaddleSpeech#3251]
## General Question
Speech Server一键部署语音服务，使用am为fastspeech2_aishell3，voc为pwgan_aishell3，生成的短句音频句首第一个字和句末最后一个字有吞音，句末吞音现象尤其严重，不加标点的话几乎听不到最后一个字。

**Comment by Javacr** [comment]
确实，我在本机跑源码，也遇到这种问题，最后一个字发音时长太短，几乎听不到

**Comment by Javacr** [comment]
我只能在每个短句的最后加一个“了”字，来解决这个问题

**Comment by Javacr** [comment]
最后发现，合成语音没有问题。不要用win10默认播放器，用音频播放器就没问题。
