### ISSUE TITLE
请问语音合成的流式推理服务(stream_TTS)支持中英文混合吗？

### ISSUE THREAD

**Issue by Tony-xubiao** [PaddlePaddle/PaddleSpeech#3269]
如果还没有的话，有可参照的过程来自行训练吗？

我所了解的信息：
pp-tts目前流式推理方案：fastspeech2_CNNDecoder + Multi Band MelGAN/HiFiGAN，支持中文，不支持中英混合
如有错漏，还请海涵，谢谢！

**Comment by zh794390558** [comment]
可以自行训练模型。

**Comment by Tony-xubiao** [comment]
ok，谢谢

**Comment by ddbegun** [comment]
请问该怎么样使模型支持流式tts合成英文呢？
