### ISSUE TITLE
[TTS]你好，安装成功了，但是运行报错了？望解答谢谢

### ISSUE THREAD

**Issue by laishujie** [PaddlePaddle/PaddleSpeech#3274]
[TTS]你好，安装成功了，但是使用的时候找不到？我使用安装命令是

python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

python ：版本3.9
cuda: 11.7
cudnn: 8.9

![截图 2023-05-25 17-23-42](https://github.com/PaddlePaddle/PaddleSpeech/assets/16934884/1a299d74-e29d-4efe-adbd-4daa14df7b1b)

**Comment by ajie425** [comment]
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/40158391/6672bd66-c498-4cfd-8a00-452b5d85038c)

**Comment by laishujie** [comment]
> ![image](https://user-images.githubusercontent.com/40158391/240947856-6672bd66-c498-4cfd-8a00-452b5d85038c.png)
pip install paddlepaddle
这样直接安装的话不是cup的版本么？我是根据官网流程安装的
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

最后的验证安装也通过了，只是引用的时候无法找到该库。所以不知道那步出问题了

**Comment by zh794390558** [comment]
paddlespeech没有安装成功，参看install.md中的方法。

**Comment by shipshipliucixin1** [comment]
> ![image](https://private-user-images.githubusercontent.com/40158391/240947856-6672bd66-c498-4cfd-8a00-452b5d85038c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTQyNDQsIm5iZiI6MTcxOTQ5Mzk0NCwicGF0aCI6Ii80MDE1ODM5MS8yNDA5NDc4NTYtNjY3MmJkNjYtYzQ5OC00Y2ZkLThhMDAtNDUyYjVkODUwMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEzMTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZGZmN2M2NjFhNDNmMjM0YjU5ZDIwNjkxYmRiZmU0OTlkOWQ5YTVmNGY1MzQ3OTAwMTNiNDQ0MTk3Njk4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dsh6lX0hT_cyQL2twjICxCjYZMU7u6DxjBEjkHiEt6w)
为什么源码编译比较好？是因为pip安装的时候会有一些必要文件没有下载下来吗？
