### ISSUE TITLE
choose a TTS model

### ISSUE THREAD

**Issue by lalimili6** [PaddlePaddle/PaddleSpeech#3280]
## General Question

Hi, dears
I want to train a TTS model, here are lots of models,
1- which one is good? 
2- which examples are good?
I want a model with good interface server time even quality is lower.
best regards

**Comment by zh794390558** [comment]
You can using the paddlespeech server default model: FastSpeech2 + HiFIGAN

**Comment by lalimili6** [comment]
Thanks,
what about VIST models? 
does Streaming synthesizing support the VIST model?

**Comment by zh794390558** [comment]
I am not sure, we do not try it.

**Comment by lalimili6** [comment]
also, these are good suggestions:
[#1908](https://github.com/PaddlePaddle/PaddleSpeech/issues/1908)
hope, try VIST as I think better model.
best regards, thanks
