### ISSUE TITLE
[S2T]declarative() got an unexpected keyword argument 'property'

### ISSUE THREAD

**Issue by itltf512116** [PaddlePaddle/PaddleSpeech#3295]
**使用容器镜像：** docker pull paddlecloud/paddlespeech:develop-cpu-latest
docker run -it -v ./paddle_volume:/mnt/volume docker.io/paddlecloud/paddlespeech:develop-cpu-latest /bin/bash

**查看版本：paddlespeech version 输出：**
Commit ID:
    5f53e902e1c85a7ec6c1645d61a26701d171428a

**执行命令：paddlespeech asr --lang zh --input /mnt/volume/zh.wav**
      其中zh.wav来源于：https://paddlespeech.bj.bcebos.com/PaddleAudio/zh.wav
输出：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.7/dist-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:1104: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
**TypeError: declarative() got an unexpected keyword argument 'property'**

这个镜像版本应该挺新的，跟[#2512](https://github.com/PaddlePaddle/PaddleSpeech/issues/2512)的升级版本好像不一样？
请问这个应该怎么解决呢？

**Comment by zh794390558** [comment]
升级paddle到2.5rc

**Comment by itltf512116** [comment]
> 升级paddle到2.5rc

@zh794390558 您好，我在容器里面执行python3 -m pip install paddlepaddle==2.5rc -i https://mirror.baidu.com/pypi/simple 
成功后执行 
   import paddle
   print(paddle.__version__)
输出 2.5.0-rc0
然后再执行paddlespeech asr --lang zh --input /mnt/volume/zh.wav  输出如下：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2023-05-31 09:13:57,362] [   ERROR] - (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:85)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/cli/asr/infer.py", line 323, in infer
    simulate_streaming=cfg.simulate_streaming)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 350, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 827, in decode
    reverse_weight=reverse_weight)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 546, in attention_rescoring
    num_decoding_left_chunks, simulate_streaming)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 428, in _ctc_prefix_beam_search
    simulate_streaming)  # (B, maxlen, encoder_dim)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/models/u2/u2.py", line 234, in _forward_encoder
    num_decoding_left_chunks=num_decoding_left_chunks
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 1253, in __call__
    return self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/encoder.py", line 184, in forward
    num_decoding_left_chunks)
  File "/usr/local/lib/python3.7/dist-packages/paddlespeech/s2t/modules/mask.py", line 202, in add_optional_chunk_mask
    chunk_masks = masks.logical_and(chunk_masks)  # (B, L, L)
  File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/logic.py", line 135, in logical_and
    return _C_ops.logical_and(x, y)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1, 0, 498] and the shape of Y = [1, 123, 123]. Received [498] in X is not equal to [123] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:85)

KeyError: 'result'

请问这个是哪里操作不对吗？

**Comment by zh794390558** [comment]
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/3038472/1d04c6d4-b407-448b-9bc5-e28ed5f41c8a)

pdb检查下为什么shape不对

**Comment by itltf512116** [comment]
> ![image](https://user-images.githubusercontent.com/3038472/242576214-1d04c6d4-b407-448b-9bc5-e28ed5f41c8a.png)
> 
> pdb检查下为什么shape不对

很抱歉我不是python开发，不知道您这个是什么意思，请问现在有可以直接使用的docker镜像吗？

**Comment by itltf512116** [comment]
paddlespeech version
Commit ID:
    52c7c1ef6a7373c332a52e006a80e59e630225cc
这个版本的镜像也是报错，这demo好像跑不起来？

**Comment by itltf512116** [comment]
解决了：
拉取镜像docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.2
然后进入容器，执行安装pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple
然后运行 paddlespeech asr --lang zh --input /mnt/volume/zh.wav ，提示缺少一个so，再执行
apt-get install libsndfile1 
成功后再次执行识别可以了

**Comment by caorufu** [comment]
感谢分享，一模一样的问题，一模一样的报错过程！！！

**Comment by RickCao-2017** [comment]
> 解决了： 拉取镜像docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.2 然后进入容器，执行安装pip install paddlespeech -i https://pypi.tuna.tsinghua.edu.cn/simple 然后运行 paddlespeech asr --lang zh --input /mnt/volume/zh.wav ，提示缺少一个so，再执行 apt-get install libsndfile1 成功后再次执行识别可以了

其实直接 pip uninstall 卸载以后重新安装就行，不用换镜像
