### ISSUE TITLE
way to fix "magic_number = pickle_module.load(f, **pickle_load_args)  EOFError: Ran out of input"

### ISSUE THREAD

**Issue by Tony-xubiao** [PaddlePaddle/PaddleSpeech#3308]
If you encounter an error similar to the one below, please note your checkpoints file and pfggan files, they could both have only file names but 0 file sizes.
![bugs](https://github.com/PaddlePaddle/PaddleSpeech/assets/48686098/0c260dce-41ef-47fd-a28e-b6368597adf8)
I used this script and had this problem：
’‘’bash scripts/download_models.sh‘’‘
which was solved by using another way to download the file and upload them to the right place

**Comment by zh794390558** [comment]
看着不是speech的问题。audio2pose不是我们负责的。

**Comment by Tony-xubiao** [comment]
sry, my bad
