### ISSUE TITLE
0英文样本的中文发音人  跨语言学习方案 是哪个项目呢

### ISSUE THREAD

**Issue by litao28** [PaddlePaddle/PaddleSpeech#3314]
跨语言学习方案可以让0英文样本的中文发音人（Chinese Standard Mandarin Speech Copus）实现同音色双语播报。 想问一下具体项目位置。另外，还想问一下，目前有500句左右中文单人音频，足够训练出比较好的效果吗

**Comment by zh794390558** [comment]
麻烦描述清楚需求，没有理解要做什么。
