### ISSUE TITLE
请问ASR有批量处理的例子吗？

### ISSUE THREAD

**Issue by thehzzz** [PaddlePaddle/PaddleSpeech#3320]
根据例子(基于 PP-ASR 的长语音转写)处理长语音转写，需要切分音频，再进行识别。在转写识别的过程中，要不断重新启动模型。请问有固定模型批量处理音频的例子吗？

asr = ASRExecutor()

long_asr_result = ""
for idx, sub_wav in tqdm.tqdm(enumerate(sub_wavs)):
    audio = f"work/temp_{idx}.wav"
    soundfile.write(audio, sub_wav, sample_rate)
    asr_result = asr(audio_file=audio, model='conformer_online_wenetspeech')
    if asr_result:
        # 有识别结果才恢复标点
        text_result = text_punc(text=asr_result)
        long_asr_result += text_result

**Comment by zh794390558** [comment]
按上面的代码加个for-loop就可以了。

**Comment by thehzzz** [comment]
如何避免不断重新加载模型？

**Comment by zh794390558** [comment]
实例化一次就可以啦
