### ISSUE TITLE
声音克隆相关

### ISSUE THREAD

**Issue by dungeon-kalath** [PaddlePaddle/PaddleSpeech#3355]
您好，
tts声音克隆，例如我们用自己的音频训练出来的声音克隆，请问可以直接用做商用吗

**Comment by zxcd** [comment]
PaddleSpeech 遵循 Apache2.0 开源协议，支持开发者们做二次开发，免费商用（Apache LICENSE 2.0 : [http://www.apache.org/licenses/LICENSE-2.0.html）](http://www.apache.org/licenses/LICENSE-2.0.html%EF%BC%89)

**Comment by zxcd** [comment]
如果你用自己的音频训练的，并且不考虑版权问题，是可以的。
