### ISSUE TITLE
Provide examples based on pre training weights.

### ISSUE THREAD

**Issue by 943fansi** [PaddlePaddle/PaddleSpeech#3363]
In voice cloning, there are two similar but different files, https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/vits/voice_cloning.py and https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/exps/voice_cloning.py. Which one should I choose to adapt to ge2e_ckpt_0.3.zip?

**Comment by zxcd** [comment]
It depends on which recipe you are using:
`./local/voice_cloning.sh` calls `${BIN_DIR}/voice_cloning.py`

**Comment by 943fansi** [comment]
@zxcd Thanks for your reply. We can find links to training, inference code, and pre training weights from the [examples](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples) folder. If you directly download the weights in the [document](https://paddlespeech.readthedocs.io/en/latest/released_model.html#voice-cloning), it will be quite confusing and difficult to find the corresponding code.
