### ISSUE TITLE
ASR识别出的方言中文过于怪异

### ISSUE THREAD

**Issue by didoll-john** [PaddlePaddle/PaddleSpeech#3365]
## General Question
尝试了一下方言识别，随便在抖音上找了一段语音，识别出来的文字只是在堆砌相似的读音，完全没有逻辑。
示例：
paddlespeech asr --lang zh --input fy.wav 
各地标方言名场面一起看看这十大方言有目有你的家乡方言吗监金化草嘛吵骂吵骂呀河南话那荣耀荣冷漠日子融四川话在一个就是矮气长沙画彪子料子陕西话好没有人心来吧简直是丧心冰狂招如情丝慕成绝上海话西萨问您们打家好好了以前K斯莱我觉得小黑屋山东话虽敢陕东天不叫天叫斜天转不掉翻掉邪妇你南画地黑门了吧你这广东话从甘听透透气猫桶雷胭雄一个东北话我是唐茂生口的胸前几天在我家买的内裤吧对啊专家买个裤的好了刚那您给个好评呗都发错户了还比啥好评啊我要的是瓶角的你给我邮过三脚楼三角的我也就认了我一百八十二十来斤你给我邮歪S嘛那我穿那不能不雷劈话走几步就家丁欧里走几步就假定欧这一刀净拽它整得我那裤衩嘎哨走快了还磨大腿底子子大腿底子给我们去黑喂我挂了

https://github.com/PaddlePaddle/PaddleSpeech/assets/134175197/290c42df-2a14-47a0-8749-0c172884a4a0

**Comment by zxcd** [comment]
目前的中文模型仅支持普通话识别，需要识别方言的话需要自己用方言的数据训练一个新的模型。

**Comment by didoll-john** [comment]
了解，谢谢。
