### ISSUE TITLE
whisper的large模型识别过于慢了，在哪个显卡下能发挥最快速度呢？后续速度有改进计划吗

### ISSUE THREAD

**Issue by mrg79433283** [PaddlePaddle/PaddleSpeech#3373]

**Comment by zxcd** [comment]
或许可以使用小一点的模型，比如medium。

**Comment by mrg79433283** [comment]
> 或许可以使用小一点的模型，比如medium。

也用过，也不咋快 
large模型，使用T4显卡，一小时wav文件识别用了快2个小时，10分钟的大概要用到18分钟
而且用小一点模型的话，会出现识别语句多次重复的情况，large也偶现

**Comment by zh794390558** [comment]
配合VAD使用。
