### ISSUE TITLE
paddlespeech 为什么当有中文英语数字时，字母读不出来？

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSpeech#3382]
可以试一下：
其中：A100读成100，  1B 读成1 等等........

paddlespeech tts --am fastspeech2_aishell3 --voc pwgan_aishell3 --input "对英伟达老黄的一些建议和忠告，或是对现在算力显卡的痛点痛批。现在ai人工智能快速发展，大语言模型层出不穷，现在有个致命的缺陷，就是算力显卡的显存太小了。可能这时候会有人跳出来说，不是可以多卡一起麻，比如一张A100显卡80G显存，那我买个8张不就是640G显存了吗。对算数是这样，但是现实总是那么残酷，啪啪打脸来的总是那么快。首先多张卡显存并不会叠加并联，你还是80G。想不到吧，为什么不是640G呢。听我一一道来。比如大模型有：1B，3B，7B，14B等等多大的模型。其中1B是一亿个参数，3B是3亿个参数，我现在用一张A100显卡80G的我只能用来训练3B的模型，7B的就超显存不行了。我也试过用8个A100并联，还开启了deepspeed_stage_2_offload。但是结果显示还是能不能运行，为什么会这样呢？因为显卡显存不能叠加，显存不能叠加，重要的是说三遍。全量8张A100只能玩3B, 多卡就是单卡。 划重点：单卡能运行起来，多卡才能运行。那这个多卡有什么用呢，说实话，没多大用处。真是打脸，作用只是快一点点，多卡的作用，这个真是冤大头。我多张A100就是为了快那么一点点，那真是搞笑了。又有人跳出来说，我可以呀。我只能呵呵了，当然可以，那是你只知其一，不知其二。  你运行的是小模型，单卡本来就可以，你现在用多卡，当然是可以的。本来就可以呀。 并不是你的多呀发挥作用的。所以吐槽开始了： 大模型横行时代，硬件显卡明显掉链子！拖了ai大模型的后腿。现在特别需要单卡显存大的显卡，起码200G起步。管它什么A100 A500 ，管它个么牌子， 只要显存大就能运行起来更大的模型，假设3090搞到几百G那就是卡王，并不是说A100才是卡王，只是单卡显存大那就是。现在只想要这一张单卡几百G的才能解决我的燃眉之急，目前市面上还没有这样的卡。现在显卡被卡脖子的不是算力，而是显存，单卡一定要大。 就算是算力弱一点也能接受，毕竟是训练，无非就是多花点时间。如果显卡显存不够那直接是致命的，直接训练不了，也启动不了大模型，这个是不能接受的。只有一种特殊的情况才需要算力超强，那就是推理的时候，必须是速度快，算力强，显存不用很大，一张A100可以对所有模型进行推理。其实现在是做显卡最好的机会，啥时候谁出个单卡大显存，支持python,我们就支持谁。ai训练迫在眉睫，算力不够时间来凑，只要不是太离谱一定大卖" --spk_id 1

**Comment by zh794390558** [comment]
训练集没有对应的发音，可以看文本前端生成的phoneme是否符合预期。

**Comment by gg22mm** [comment]
> 训练集没有对应的发音，可以看文本前端生成的phoneme是否符合预期。

就是有点怪  A100读成100， 1B 读成1 等等........

**Comment by zxcd** [comment]
中英文混合时中文和英文中间需要手动添加空格，可以尝试A 100，1 B

**Comment by gg22mm** [comment]
有空我再试，非常感谢！
