### ISSUE TITLE
请问rhy训练的模型可以转成ONNX格式吗？

### ISSUE THREAD

**Issue by Tony-xubiao** [PaddlePaddle/PaddleSpeech#3405]
我收集了一批含有韵律标注的数据，准备参照
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/rhy
训练韵律模型，请问如何将训练得到的模型转成ONNX格式？

**Comment by zxcd** [comment]
我们这边没尝试过，你可以自己试试。

**Comment by Tony-xubiao** [comment]
> 好，试过了，根据paddle官方提供的[教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/model_to_onnx_cn.html)已经顺利转了ONNX，没有问题
