### ISSUE TITLE
安装上了，也提示成功了，为啥paddlespeech_server命令工具不能用

### ISSUE THREAD

**Issue by z1060932884** [PaddlePaddle/PaddleSpeech#3427]
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/18072177/3df93da9-d20d-42f2-b35f-e9fa39ebeb50)

安装上了，也提示成功了，为啥paddlespeech_server命令工具不能用，怎么排查下哪里有问题

**Comment by zhanghzong** [comment]
find / -name paddlespeech_server  找到后 加入环境变量中去

**Comment by z1060932884** [comment]
找到了，谢谢
