### ISSUE TITLE
我在训练一个自己的TTS模型的时候遇到的问题

### ISSUE THREAD

**Issue by drinkerwhz** [PaddlePaddle/PaddleSpeech#3429]
AssertionError: Variable Shape not match, Variable [ create_parameter_3.w_0_moment1_0 ] need tensor with shape [] but load set tensor with shape [1]       我在训练一个自己的TTS模型的时候遇到的问题

**Comment by drinkerwhz** [comment]
不知道是什么原因，之前有一个 exp/default 文件，后来删掉之后重新跑了一下就好了

**Comment by zhdovelie** [comment]
你好，我也遇到了相同的报错。
这是我使用的环境信息：paddlepaddle-gpu: 2.5; cuda：11.8; 
请问你删除的exp的目录具体是在哪里呢？
