### ISSUE TITLE
ModuleNotFoundError: No module named 'paddlespeech.s2t.transform'

### ISSUE THREAD

**Issue by xiaoligang2000** [PaddlePaddle/PaddleSpeech#3444]
paddlepaddle==2.5.0rc0
paddleslim==2.4.1
paddlespeech==1.4.1

报错如下：
pwd
PaddleSpeech/examples/wenetspeech/asr1
(venvPaddle) [root@localhost asr1]# ./local/data.sh --stage 2 --stop_stage 2
Compute cmvn
Traceback (most recent call last):
  File "utils/compute_cmvn_stats.py", line 8, in <module>
    from paddlespeech.s2t.transform.transformation import Transformation
ModuleNotFoundError: No module named 'paddlespeech.s2t.transform'

paddlespeech.s2t.transform.transformation 这个要挪到哪里去了？要咋改改？

**Comment by zxcd** [comment]
https://github.com/PaddlePaddle/PaddleSpeech/blob/a1745944657feaaae2fe22201aedd6d42b0a536e/paddlespeech/audio/transform/transformation.py#L54
改成from paddlespeech.audio.transform.transformation import Transformation
