### ISSUE TITLE
你好，请问phoneme的中间加sil或者sp增加提顿时长疑问

### ISSUE THREAD

**Issue by laishujie** [PaddlePaddle/PaddleSpeech#3450]
你好，能请问下具体的操作是怎样吗？是需要重新训练，还是直接改代码即可实现呢？我浏览了好多issue都没找到答案

**Comment by zxcd** [comment]
是在输入文本里面加

**Comment by laishujie** [comment]
> 是在输入文本里面加

1.这样？“今天sil天气不错啊” 试了好像不行。
2.还有个问题是，我训练的数据集使用朗读裁剪下来的，大概5000句都是带情感数据，但是通过微调的方案，训练了好几个人，他们都有共同特点，说话快，不会停顿，给我的感觉就是只有声色不同而已，而语气都一样，无法通过数据集进行微调改变，所以很想知道fastspeech2_male模型是通过那个方案训练出来的？我要怎么才能做到训练出的模型语气和语速都发生改变呢？
