### ISSUE TITLE
deepspeech2 执行训练报错   AttributeError: module 'distutils' has no attribute 'util'

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/PaddleSpeech#3457]
conda虚拟环境python=3.8

在examples/aishell/asr0下   首先第一步处理数据完成
然后执行第二步骤训练时，命令：bash run.sh --gpus 0 --stage 1 --stop_stage 1

报错信息如下：
checkpoint name deepspeech2
using 1 gpus...
LAUNCH INFO 2023-08-08 14:07:53,618 -----------  Configuration  ----------------------
LAUNCH INFO 2023-08-08 14:07:53,618 auto_parallel_config: None
LAUNCH INFO 2023-08-08 14:07:53,618 devices: 0
LAUNCH INFO 2023-08-08 14:07:53,618 elastic_level: -1
LAUNCH INFO 2023-08-08 14:07:53,618 elastic_timeout: 30
LAUNCH INFO 2023-08-08 14:07:53,618 gloo_port: 6767
LAUNCH INFO 2023-08-08 14:07:53,618 host: None
LAUNCH INFO 2023-08-08 14:07:53,618 ips: None
LAUNCH INFO 2023-08-08 14:07:53,618 job_id: default
LAUNCH INFO 2023-08-08 14:07:53,618 legacy: False
LAUNCH INFO 2023-08-08 14:07:53,618 log_dir: log
LAUNCH INFO 2023-08-08 14:07:53,618 log_level: INFO
LAUNCH INFO 2023-08-08 14:07:53,618 log_overwrite: False
LAUNCH INFO 2023-08-08 14:07:53,618 master: None
LAUNCH INFO 2023-08-08 14:07:53,618 max_restart: 3
LAUNCH INFO 2023-08-08 14:07:53,618 nnodes: 1
LAUNCH INFO 2023-08-08 14:07:53,618 nproc_per_node: None
LAUNCH INFO 2023-08-08 14:07:53,618 rank: -1
LAUNCH INFO 2023-08-08 14:07:53,618 run_mode: collective
LAUNCH INFO 2023-08-08 14:07:53,618 server_num: None
LAUNCH INFO 2023-08-08 14:07:53,618 servers: 
LAUNCH INFO 2023-08-08 14:07:53,618 start_port: 6070
LAUNCH INFO 2023-08-08 14:07:53,618 trainer_num: None
LAUNCH INFO 2023-08-08 14:07:53,618 trainers: 
LAUNCH INFO 2023-08-08 14:07:53,618 training_script: /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/train.py
LAUNCH INFO 2023-08-08 14:07:53,618 training_script_args: ['--ngpu', '1', '--config', 'conf/deepspeech2.yaml', '--output', 'exp/deepspeech2', '--seed', '10086']
LAUNCH INFO 2023-08-08 14:07:53,619 with_gloo: 1
LAUNCH INFO 2023-08-08 14:07:53,619 --------------------------------------------------
LAUNCH INFO 2023-08-08 14:07:53,619 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-08-08 14:07:53,619 Run Pod: nnxsnj, replicas 1, status ready
LAUNCH INFO 2023-08-08 14:07:53,627 Watching Pod: nnxsnj, replicas 1, status running
/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 33, in <module>
    parser = default_argument_parser()
  File "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/training/cli.py", line 76, in default_argument_parser
    type=distutils.util.strtobool,
AttributeError: module 'distutils' has no attribute 'util'
LAUNCH INFO 2023-08-08 14:08:02,637 Pod failed
LAUNCH ERROR 2023-08-08 14:08:02,637 Container failed !!!
Container rank 0 status failed cmd ['/home/alex/anaconda3/envs/paddle_speech/bin/python3', '-u', '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/train.py', '--ngpu', '1', '--config', 'conf/deepspeech2.yaml', '--output', 'exp/deepspeech2', '--seed', '10086'] code 1 log log/workerlog.0 
env {'XDG_VTNR': '7', 'LC_PAPER': 'zh_CN.UTF-8', 'LC_ADDRESS': 'zh_CN.UTF-8', 'XDG_SESSION_ID': 'c2', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/alex', 'LC_MONETARY': 'zh_CN.UTF-8', 'CLUTTER_IM_MODULE': 'xim', 'SESSION': 'ubuntu', 'GPG_AGENT_INFO': '/home/alex/.gnupg/S.gpg-agent:0:1', 'TERM': 'xterm-256color', 'VTE_VERSION': '4205', 'XDG_MENU_PREFIX': 'gnome-', 'SHELL': '/bin/bash', 'CONDA_SHLVL': '2', 'LIBRARY_PATH': ':/usr/local/lib:/usr/local/cuda-10.2/lib64', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'CONDA_PROMPT_MODIFIER': '(paddle_speech) ', 'WINDOWID': '44040202', 'LC_NUMERIC': 'zh_CN.UTF-8', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/15943', 'GNOME_KEYRING_CONTROL': '', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'LC_ALL': 'C', 'PYTHONIOENCODING': 'UTF-8', 'USER': 'alex', 'CUDA_HOME': '/usr/local/lib:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2:', 'JRE_HOME': '/usr/local/jdk1.8.0_11/jre', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'QT_ACCESSIBILITY': '1', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'LD_LIBRARY_PATH': '/opt/TensorRT-7.2.2.3/lib:/opt/ffmpeg3.4.5/lib:/usr/local/cuda-10.2/lib64:/usr/lib/x86_64-linux-gnu::/opt/TensorRT-7.2.3.4/lib:/usr/local/lib/:/usr/local/lib/', 'BIN_DIR': '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin', 'CONDA_EXE': '/home/alex/anaconda3/bin/conda', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'MAIN_ROOT': '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'SESSION_MANAGER': 'local/alex-System-Product-Name:@/tmp/.ICE-unix/16181,unix/alex-System-Product-Name:/tmp/.ICE-unix/16181', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'FLAGS_allocator_strategy': 'naive_best_fit', '_CE_CONDA': '', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'CONDA_PREFIX_1': '/home/alex/anaconda3', 'DESKTOP_SESSION': 'ubuntu', 'PATH': '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop:/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/utils:/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop:/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/utils:/home/alex/anaconda3/envs/paddle_speech/bin:/home/alex/anaconda3/condabin:/home/alex/bin:/home/alex/.local/bin:/usr/local/jdk1.8.0_11/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib:/usr/local/cuda-10.2/bin:/usr/local/cuda-10.2:.', 'QT_IM_MODULE': 'fcitx', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'CONDA_PREFIX': '/home/alex/anaconda3/envs/paddle_speech', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', 'XDG_SESSION_TYPE': 'x11', 'PWD': '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/examples/aishell/asr0', 'JOB': 'dbus', 'XMODIFIERS': '@im=fcitx', 'JAVA_HOME': '/usr/local/jdk1.8.0_11', 'CUDA_VISIBLE_DEVICES': '0', 'GNOME_KEYRING_PID': '', 'LANG': 'zh_CN.UTF-8', 'GDM_LANG': 'zh_CN', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'IM_CONFIG_PHASE': '1', 'PYTHONDONTWRITEBYTECODE': '1', 'PAPERSIZE': 'a4', 'GDMSESSION': 'ubuntu', '_CE_M': '', 'SESSIONTYPE': 'gnome-session', 'GTK2_MODULES': 'overlay-scrollbar', 'SHLVL': '3', 'HOME': '/home/alex', 'XDG_SEAT': 'seat0', 'LANGUAGE': 'zh_CN:en_US:en', 'FLAGS_cudnn_deterministic': 'True', 'LIBGL_ALWAYS_SOFTWARE': '1', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'PYTHONPATH': '/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop:/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop:', 'CONDA_PYTHON_EXE': '/home/alex/anaconda3/bin/python', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LOGNAME': 'alex', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-xgenrfmput', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'CLASSPATH': '.:/usr/local/jdk1.8.0_11/lib:/usr/local/jdk1.8.0_11/jre/lib', 'QT4_IM_MODULE': 'fcitx', 'CONDA_DEFAULT_ENV': 'paddle_speech', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'PKG_CONFIG_PATH': ':/usr/local/lib/pkgconfig', 'INSTANCE': '', 'XDG_RUNTIME_DIR': '/run/user/1000', 'DISPLAY': ':0', 'XDG_CURRENT_DESKTOP': 'Unity', 'GTK_IM_MODULE': 'fcitx', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_TIME': 'zh_CN.UTF-8', 'LC_NAME': 'zh_CN.UTF-8', 'XAUTHORITY': '/home/alex/.Xauthority', '_': '/home/alex/anaconda3/envs/paddle_speech/bin/python3', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'nnxsnj', 'PADDLE_MASTER': '127.0.1.1:43240', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:43241', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:43241', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2023-08-08 14:08:02,637 ------------------------- ERROR LOG DETAIL -------------------------
/home/alex/anaconda3/envs/paddle_speech/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/exps/deepspeech2/bin/train.py", line 33, in <module>
    parser = default_argument_parser()
  File "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleSpeech-develop/paddlespeech/s2t/training/cli.py", line 76, in default_argument_parser
    type=distutils.util.strtobool,
AttributeError: module 'distutils' has no attribute 'util'
LAUNCH INFO 2023-08-08 14:08:02,638 Exit code 1

请问如何解决

**Comment by qingjiaozyn** [comment]
问题解决了吗？怎么处理

**Comment by w5688414** [comment]
我把相关的去掉，改成，不用这个包了：

```
    parser.add_argument(
        "--debug",
        action="store_true",
        # default=False,
        help="logging with debug mode.")
```
