### ISSUE TITLE
centos 按照安装文档Medium 安装报错

### ISSUE THREAD

**Issue by beixiang-l** [PaddlePaddle/PaddleSpeech#3506]
## General Question

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requi
res-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11ERROR: Could not find a version that satisfies the requirement paddleaudio>=1.1.0 (from paddlespeech) (from versions: 0.1.0a0, 0.1.0, 0.2.0, 0.2.1, 1.0.0a0, 1.0.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for paddleaudio>=1.1.0

# 使用环境如下
# python3.11.0
# paddlepaddle==2.5.1
# pip 23.2.1

**Comment by young1lin** [comment]
我看了其他的 issue，别人换成 python 3.9 就好了，只有这个 paddleaudio 1.1.0 没有在 python 3.11 上有。只能等他们提供 paddleaudio 1.1.0 在 python 3.11 的。

**Comment by beixiang-l** [comment]
> 我看了其他的 issue，别人换成 python 3.9 就好了，只有这个 paddleaudio 1.1.0 没有在 python 3.11 上有。只能等他们提供 paddleaudio 1.1.0 在 python 3.11 的。

是的 换了下版本起来了，但还是有蛮多问题 跟centos同样的环境我用ubuntu的机器装报Illegal instruction (core dumped)
