### ISSUE TITLE
安装PaddleSpeech后无法使用

### ISSUE THREAD

**Issue by nemoiee** [PaddlePaddle/PaddleSpeech#3547]
## Others

执行命令
` paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav`
可以正常运行

但是使用程序
```python
from paddlespeech.cli.tts.infer import TTSExecutor
tts = TTSExecutor()
tts(text="今天天气十分不错。", output="output.wav")
```

报错
```bash
ModuleNotFoundError: No module named 'paddlespeech.cli'; 'paddlespeech' is not a package
```

**Comment by sym19991125** [comment]
请问这个怎么解决的呢

**Comment by nemoiee** [comment]
> 请问这个怎么解决的呢

看一下是不是文件的名字是paddle.py或者paddlespeech.py

**Comment by sym19991125** [comment]
> > 请问这个怎么解决的呢
> 
> 看一下是不是文件的名字是 paddle.py 或者 paddlespeech.py

是这个名字，不可以这样是吗

**Comment by nemoiee** [comment]
> > > 请问这个怎么解决的呢
> > 
> > 
> > 看一下是不是文件的名字是 paddle.py 或者 paddlespeech.py
> 
> 是这个名字，不可以这样是吗

换个名字，和模块重名调用有冲突

**Comment by sym19991125** [comment]
> > > > 请问这个怎么解决的呢
> > > 
> > > 
> > > 看一下是不是文件的名字是 paddle.py 或者 paddlespeech.py
> > 
> > 
> > 是这个名字，不可以这样是吗
> 
> 换个名字，和模块重名调用有冲突

非常感谢
