### ISSUE TITLE
[TTS] paddlespeech不再支持中英双语模型了吗？

### ISSUE THREAD

**Issue by hehexiong** [PaddlePaddle/PaddleSpeech#3580]
列表里没有双语模型，只包含单语模型
AssertionError: The model "fastspeech2-mix" you want to use has not been supported, please choose other models.
The support models includes:
		speedyspeech_csmsc-zh
		fastspeech2_csmsc-zh
		fastspeech2_ljspeech-en
		fastspeech2_aishell3-zh
		fastspeech2_vctk-en
		tacotron2_csmsc-zh
		tacotron2_ljspeech-en
		pwgan_csmsc-zh
		pwgan_ljspeech-en
		pwgan_aishell3-zh
		pwgan_vctk-en
		mb_melgan_csmsc-zh
		style_melgan_csmsc-zh
		hifigan_csmsc-zh
		hifigan_ljspeech-en
		hifigan_aishell3-zh
		hifigan_vctk-en
		wavernn_csmsc-zh

**Comment by zxcd** [comment]
是支持的https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/zh_en_tts/tts3
