### ISSUE TITLE
paddlespeech语音识别是否能获取到逐字或逐音素的音频数据？

### ISSUE THREAD

**Issue by worldback** [PaddlePaddle/PaddleSpeech#3585]
paddlespeech 语音识别是否能获取到逐字或逐音素的音频数据？

**Comment by zxcd** [comment]
能否更详细描述一下你的问题？

**Comment by worldback** [comment]
asr识别的结果，能否得到字（或词、或音素）的时间戳。如"百度研究院"，"百"这个字的开始到结束时间戳为: 0.0s-0.8s, "度"这个字的开始到结束时间戳为: 0.9s-1.3s。 我在issue中搜索这个方案，说是可以参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/streaming_asr_server/ 这里面的内容。不知道通过from paddlespeech.cli.asr.infer import ASRExecutor 中的 ASRExecutor 能否获得这种时间戳， 以方便进行语音数据的切割。还是需要自己根据streaming_asr_server里的代码进行改造从而获取。

**Comment by worldback** [comment]
@zxcd 
asr识别的结果，能否得到字（或词、或音素）的时间戳。如"百度研究院"，"百"这个字的开始到结束时间戳为: 0.0s-0.8s, "度"这个字的开始到结束时间戳为: 0.9s-1.3s。 我在issue中搜索这个方案，说是可以参考：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/streaming_asr_server/ 这里面的内容。不知道通过from paddlespeech.cli.asr.infer import ASRExecutor 中的 ASRExecutor 能否获得这种时间戳， 以方便进行语音数据的切割。还是需要自己根据streaming_asr_server里的代码进行改造从而获取。

**Comment by bigmisspanda** [comment]
asr_api.py   
word_time_stamp = connection_handler.get_word_time_stamp()中已经输出了每个字的时间信息
