### ISSUE TITLE
[TTS] 模型已经下载，运行 paddlespeech tts 没有默认加载本地模型

### ISSUE THREAD

**Issue by lonngxiang** [PaddlePaddle/PaddleSpeech#3591]
paddlespeech版本1.4

![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/40717349/d2593113-4194-4c65-ad58-84c0f10e301c)
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/40717349/a5e8a9b9-8cd3-46d1-8a61-58cf0bf6e541)

![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/40717349/d7189f43-2370-4249-9a6f-5eb8a484b0fc)

**Comment by G1017** [comment]
必须要有那个压缩包，不然就会重新下载，你把那个压缩包放在那再试试

**Comment by lonngxiang** [comment]
> 必须要有那个压缩包，不然就会重新下载，你把那个压缩包放在那再试试

这压缩包是按照这路径放置吗；以前这样成功运行过，但现在出问题了
.paddlespeech\models\fastspeech2_csmsc-zh\1.0\fastspeech2_nosil_baker_ckpt_0.4

**Comment by G1017** [comment]
.paddlespeech\models路径下
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/68003593/603195fa-65f5-4c73-ac9f-dc392d4dc393)

**Comment by G1017** [comment]
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/68003593/6b1715c1-23f4-4e32-b5fa-cb86f89d91c0)

**Comment by G1017** [comment]
.paddlespeech/models/hifigan_aishell3-zh/1.0路径下
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/68003593/27005f4e-755e-4b6e-a22d-02ec51f3eb49)
 
就是不要把他的压缩包删掉，他以压缩包去判定的

**Comment by lonngxiang** [comment]
> .paddlespeech/models/hifigan_aishell3-zh/1.0路径下 ![image](https://user-images.githubusercontent.com/68003593/282359825-27005f4e-755e-4b6e-a22d-02ec51f3eb49.png)
> 
> 就是不要把他的压缩包删掉，他以压缩包去判定的

好的已解决，多谢
