### ISSUE TITLE
请问有支持英语Streaming语音ASR的模型吗？

### ISSUE THREAD

**Issue by mzgcz** [PaddlePaddle/PaddleSpeech#3600]
## General Question
从文件名看 deepspeech2offline_librispeech 模型是不支持Streaming服务的。
transformer_librispeech 模型是否支持Streaming服务呢？
@zh794390558

**Comment by zxcd** [comment]
所有模型可以见：https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md，WER列中有值的都支持英文，Acoustic Model列中命名包含Online的都支持Streaming。

**Comment by mzgcz** [comment]
> 所有模型可以见：[https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md，WER列中有值的都支持英文，Acoustic](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/released_model.md%EF%BC%8CWER%E5%88%97%E4%B8%AD%E6%9C%89%E5%80%BC%E7%9A%84%E9%83%BD%E6%94%AF%E6%8C%81%E8%8B%B1%E6%96%87%EF%BC%8CAcoustic) Model列中命名包含Online的都支持Streaming。

多谢，那就是Paddle目前没有支持英语Streaming模式的预训练模型了
