### ISSUE TITLE
ASR 语音识别 在windows本地测试 服务端已经启动 客户端怎么能够在进行转换的同时 还能加上标点预测？

### ISSUE THREAD

**Issue by 777sfdf** [PaddlePaddle/PaddleSpeech#3608]
背景
首先 代码是最新的
python版本是3.8  
paddlepaddle 版本也是最新的
环境是window10

问题描述
ASR 语音识别 在windows本地测试 服务端已经启动  是通过命令行的方式启动的
命令如下
paddlespeech_server start  --config_file   ./speech_server/conf/application.yaml
效果图如下
![图片](https://github.com/PaddlePaddle/PaddleSpeech/assets/118660349/5da70867-dc53-4a2a-9d70-78148965b10f)

客户端测试命令如下
paddlespeech_client asr  --server_ip 127.0.0.1  --port 8090 --input 123.wav  | paddlespeech text --task punc
上述命令的输出结果是没有标点符号的

效果图如下
![图片](https://github.com/PaddlePaddle/PaddleSpeech/assets/118660349/aaf43ab7-2205-415d-bcf9-8eb921941f77)

通过阅读文档 发现下边的命令在执行以后是有标点符号的
命令如下
paddlespeech asr  --input ./123.wav  | paddlespeech text --task punc
效果图如下
![图片](https://github.com/PaddlePaddle/PaddleSpeech/assets/118660349/51088d61-6400-4e47-ae74-ad060d42ce30)

期望结果

所以有没有相关的操作 或者命令 可以在服务端启动的情况下 使用客户端的asr可以完成转换的同时 还能加上标点预测

**Comment by zxcd** [comment]
需要自己启动两个服务，一个asr的服务，一个标点预测的服务
或者改一下application.yaml 例如：https://github.com/PaddlePaddle/PaddleSpeech/blob/1b8ca706d6a8e0a8b97ee21d93314a245d777a69/demos/speech_server/conf/application.yaml#L142
