### ISSUE TITLE
[S2T]基于Paddle nvidia-docker 启动时，无法正常检测到gpu

### ISSUE THREAD

**Issue by atalia** [PaddlePaddle/PaddleSpeech#3614]
下载paddle cuda 11.2 的docker，并在有gpu的机器上运行，发现容器运行时，可以查询到cuda信息
λ d5eeecb237fe /paddle/examples/tal_cs/asr1 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

但是paddle speech训练时，会报错“You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.”：
<img width="1534" alt="image" src="https://github.com/PaddlePaddle/PaddleSpeech/assets/15249755/5ea04233-c9f9-47cd-9904-87d47abe67de">

**Comment by beixiang-l** [comment]
![paddle_error](https://github.com/PaddlePaddle/PaddleSpeech/assets/47052676/7b765655-4e9a-423a-a354-eb853714bd00)
tong'y
同样遇到这个问题

**Comment by atalia** [comment]
我的问题已经解决，方法如下：
不使用nvidia-docker启动，直接用docker 启动，并加上参数--gpus all。
