### ISSUE TITLE
TTSCppFrontend

### ISSUE THREAD

**Issue by tuotuoshao** [PaddlePaddle/PaddleSpeech#3620]
**Describe the bug**
函数FrontEngineInterface::ThreeSandhi(const std::string &word,
                                      std::vector<std::string> *finals)
的实现中有finals = new std::vector<std::string>();这样的代码明显是错误的

**To Reproduce**
”美好生活“作为输入，‘美’字的音调应该从3声被修改为2声，代码逻辑确实修改了，但是由于上述写法，修改结果未能成功返回到finals参数中

**Environment (please complete the following information):**
 - OS: windows
 - GCC/G++ Version：vs2022

**Comment by kk-2000** [comment]
您好，请问为什么关闭了issue，是找到解决方案了吗
