### ISSUE TITLE
British accent is too different from real people https://www.youtube.com/@EnglishwithLucy

### ISSUE THREAD

**Issue by Pantyhose-X** [PaddlePaddle/PaddleSpeech#3673]
Maybe we can make her British Accent for training https://www.youtube.com/@EnglishwithLucy

**Comment by Ray961123** [comment]
Hello developer, thank you for your attention to the PaddleSpeech open-source project. We apologize for any inconvenience you may have encountered during development. Based on your inquiries, we suggest considering finetuning. For guidance, please refer to the following link:
TTS:https://github.com/PaddlePaddle/PaddleSpeech/discussions/1842
ASR:https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972
