### ISSUE TITLE
你好，请问为什么现在粤语模型标点符号前面的一个字都读还没有读完就结束了呢？

### ISSUE THREAD

**Issue by zx-lhb** [PaddlePaddle/PaddleSpeech#3674]
## General Question
我以前用的时候还是正常的，最近都是这样了。比如「关关雎鸠，在河之洲」，最后那个“鸠”一定还没读完就结束了。其他句子也是同理，句号、感叹号，都有这种情况。不知道你们有没有发现。
我的参数设置:
```python
wav_file = tts_executor(
        text=txt_contents,
        am='fastspeech2_canton',
        voc='hifigan_csmsc',
        lang='canton',
        spk_id=10,
        use_onnx=True,
        output='api_1.wav',
        cpu_threads=0
    )
```

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，针对该问题，建议参考：https://github.com/PaddlePaddle/PaddleSpeech/issues/3091
