### ISSUE TITLE
mac install paddlespeech_ctcdecoders 找不到匹配的包

### ISSUE THREAD

**Issue by cyqresig** [PaddlePaddle/PaddleSpeech#3675]
Mac M2 上
安装了 paddlepaddle 2.4.2， paddlespeech 2.4.1。
跑官方的第一个示例（语音转文本）时，报错提示paddlespeech_ctcdecoders 找不到，没有安装 

下面是错误信息：
python3 ./src/pp.py                            
/Users/ccc/.pyenv/versions/3.8.18/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
/Users/ccc/.pyenv/versions/3.8.18/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/Users/ccc/.pyenv/versions/3.8.18/lib/python3.8/site-packages/pip/_vendor/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from versions: none)
ERROR: No matching distribution found for paddlespeech_ctcdecoders

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
2024-02-05 23:23:51.915 | INFO     | paddlespeech.s2t.modules.ctc:<module>:45 - paddlespeech_ctcdecoders not installed!
2024-02-05 23:23:52.017 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
[1]    24004 segmentation fault  python3 ./src/pp.py
/Users/ccc/.pyenv/versions/3.8.18/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

然后尝试安装，但提示找不到匹配的版本。。。，错误信息如下
pip3 install paddlespeech_ctcdecoders
ERROR: Could not find a version that satisfies the requirement paddlespeech_ctcdecoders (from versions: none)
ERROR: No matching distribution found for paddlespeech_ctcdecoders

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，建议参考：https://github.com/PaddlePaddle/PaddleSpeech/discussions/1195

**Comment by jzhang533** [comment]
cc: @raindrops2sea @goocody
我想，我们需要一个置顶的 issue 来说明当前 PaddleSpeech 项目的维护状态，并跟社区讨论如何更好的维护项目。可以避免在每个 issue 下都做类似的回答，并得到社区的更多的帮助。
