### ISSUE TITLE
在win10上启动demos中的speech_web进行实时语音识别 如何提高实时语音转写速度

### ISSUE THREAD

**Issue by 777sfdf** [PaddlePaddle/PaddleSpeech#3676]
页面图片
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/118660349/45e7fae6-d422-424d-866d-63222a632fe9)

测试环境
win10 使用cpu
依赖版本
![Snipaste_2024-02-06_16-32-12](https://github.com/PaddlePaddle/PaddleSpeech/assets/118660349/e659bfbb-51e2-4966-9d93-7f4b15f895cb)

python版本
3.8.18

需求:
在不使用gpu的情况下 如何调整可以能让实时语音转写速度加快 因为现在的语音转写 还是有些延迟的  思路应该往哪个方面考虑

如果在 使用gpu的情况下 又该往哪个方面考虑取调整优化

期待回复 谢谢!!!

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，建议参考：https://github.com/PaddlePaddle/PaddleSpeech/discussions/1972

**Comment by Ray961123** [comment]
建议参考：https://github.com/PaddlePaddle/PaddleSpeech/issues/3578
