### ISSUE TITLE
语音合成tts，使用不用方式调用，运行的时间不一样尼？

### ISSUE THREAD

**Issue by LeFuGang** [PaddlePaddle/PaddleSpeech#3682]
## General Question

![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/28383188/f60de590-7cf0-467c-93d1-3d6eb070007f)

我用这种方式，am模型运行时间大概0.4s左右
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/28383188/eeb77175-088d-4ec9-9663-06018f213299)

![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/28383188/fc34e9c3-1bed-43c4-bee2-4cbba9f5f5f9)

我用api的方式调用的时间am模型1.1s左右，
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/28383188/dda4f4a5-a1fc-4da3-a952-2a38b6bee10f)

我很奇怪，他们模型都是一样的，怎么运行时间不一样尼

使用的都是默认参数，模型也是默认模型'fastspeech2_csmsc' ，请大佬帮忙解答下，这到底是怎么回事尼？

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)

**Comment by LeFuGang** [comment]
> 你带来了不好的开发体

我都是用你们默认的参数，模型应该一样的，能大概给个方向吗，真不知道怎么看
