### ISSUE TITLE
能不能 边录边转换文字？  像讯飞听见那样

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSpeech#3695]
能不能 边录边转换文字？  像讯飞听见那样

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)
