### ISSUE TITLE
cannot import name 'clip_grad_norm_' from 'paddle.nn.utils'

### ISSUE THREAD

**Issue by estuday** [PaddlePaddle/PaddleSpeech#3713]
我在使用官方镜像进行以下实验时 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/aishell/asr1 ，出现错误cannot import name 'clip_grad_norm_' from 'paddle.nn.utils'。
官方镜像
![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/45581281/05525f60-a049-421a-a060-0a4fb0fa1872)
这有可能是paddlepaddle版本的问题，可以说明一下哪个版本合适吗

**Comment by xjz-ai** [comment]
我也遇到了这个问题
