### ISSUE TITLE
【TTS】启动英文流式服务报错

### ISSUE THREAD

**Issue by Ankh-L** [PaddlePaddle/PaddleSpeech#3733]
根据中文的demo改了一下am和voc，启动失败，看报错好像只支持中文流式？下面是我的配置：
``
#################################################################################
#                             SERVER SETTING                                    #
#################################################################################
host: 0.0.0.0
port: 8888

# The task format in the engin_list is: <speech task>_<engine type>
# engine_list choices = ['tts_online', 'tts_online-onnx'], the inference speed of tts_online-onnx is faster than tts_online.
# protocol choices = ['websocket', 'http']
protocol: 'websocket'
engine_list: ['tts_online-onnx']
#################################################################################
#                                ENGINE CONFIG                                  #
#################################################################################

################### speech task: tts; engine_type: online-onnx #######################
tts_online-onnx:
    # am (acoustic model) choices=['fastspeech2_csmsc_onnx', 'fastspeech2_cnndecoder_csmsc_onnx']
    # fastspeech2_cnndecoder_csmsc_onnx support streaming am infer.
    am: 'fastspeech2_ljspeech_onnx'
    # am_ckpt is a list, if am is fastspeech2_cnndecoder_csmsc_onnx, am_ckpt = [encoder model, decoder model, postnet model];
    # if am is fastspeech2_csmsc_onnx, am_ckpt = [ckpt model];
    am_ckpt:   # list
    am_stat:
    phones_dict:
    tones_dict:
    speaker_dict:
    am_sample_rate: 24000
    am_sess_conf:
        device: "cpu" # set 'gpu:id' or 'cpu'
        use_trt: False
        cpu_threads: 4

    # voc (vocoder) choices=['mb_melgan_csmsc_onnx, hifigan_csmsc_onnx']
    # Both mb_melgan_csmsc_onnx and hifigan_csmsc_onnx support streaming voc inference
    voc: 'hifigan_ljspeech_onnx'
    voc_ckpt:
    voc_sample_rate: 24000
    voc_sess_conf:
        device: "cpu" # set 'gpu:id' or 'cpu'
        use_trt: False
        cpu_threads: 4

    # others
    lang: 'en'
    # am_block and am_pad only for fastspeech2_cnndecoder_onnx model to streaming am infer,
    # when am_pad set 12, streaming synthetic audio is the same as non-streaming synthetic audio
    am_block: 72
    am_pad: 10
    # voc_pad and voc_block voc model to streaming voc infer,
    # when voc model is mb_melgan_csmsc_onnx, voc_pad set 14, streaming synthetic audio is the same as non-streaming synthetic audio; The minimum value of pad can be set to 7, streaming synthetic audio sounds normal
    # when voc model is hifigan_csmsc_onnx, voc_pad set 19, streaming synthetic audio is the same as non-streaming synthetic audio; voc_pad set 14, streaming synthetic audio sounds normal
    voc_block: 36
    voc_pad: 7
    # voc_upsample should be same as n_shift on voc config.
    voc_upsample: 300
``

报错信息：
[2024-04-01 07:29:24,459] [   ERROR] - Please check config, am support: fastspeech2, voc support: hifigan_csmsc-zh or mb_melgan_csmsc.

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)

**Comment by jianghuakun** [comment]
请问解决没？我改成混合模型报错和你一样。

**Comment by Ankh-L** [comment]
不支持英文流式 @jianghuakun

**Comment by jianghuakun** [comment]
> [2024-04-01 07:29:24,459] [ ERROR] - Please check config, am support: fastspeech2, voc support: hifigan_csmsc-zh or mb_melgan_csmsc.

你这个改下报错源码判断就可以了

**Comment by ddbegun** [comment]
请问解决没？我想使用流式tts合成英文
