### ISSUE TITLE
TTS多音字问题

### ISSUE THREAD

**Issue by think4j** [PaddlePaddle/PaddleSpeech#3737]
我在使用paddlespeech来合成语音时，遇到了下面问题：
用`paddlespeech_server start --config_file application.yaml`启动服务，用`http://127.0.0.1:8090/paddlespeech/tts`来调用服务，当文本是“是否有我行人员或其他人员向你收取手续费？”时，发现行的发音为xing，正确的应该是hang。
请问这个问题该怎么处理？谢谢。

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，建议参考：https://github.com/PaddlePaddle/PaddleSpeech/issues/3297

**Comment by think4j** [comment]
已解决，在`https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/paddlespeech/t2s/frontend/polyphonic.yaml`这里添加多音字后，需要重新安装PaddleSpeech
`# 请确保目前处于PaddleSpeech项目的根目录`
`pip install . -i https://pypi.tuna.tsinghua.edu.cn/simple`
