### ISSUE TITLE
win10 迁移Miniconda 创建的env 会提示Fatal error in launcher: Unable to create process using 

### ISSUE THREAD

**Issue by 777sfdf** [PaddlePaddle/PaddleSpeech#3749]
测试环境:win10
操作:
把电脑A上Miniconda 创建的env通过conda pack的方式迁移到另外一台电脑B上 
B电脑同样是win10 并且安装的Miniconda版本给A电脑版本一致
把A电脑打包好的env环境 复制到B电脑上 解压以后  可以正常激活环境 
conda  env list  也能显示该环境
但是 使用命令paddlespeech asr --lang zh --input D:/PaddleSpeech/zh.wav会提示下方错误

报错信息:
Fatal error in launcher: Unable to create process using '"D:\CondaSPACE\envs\paddle_speech\python.exe"  "D:\CondaSpaceSoft\envs\Scripts\paddlespeech.exe" asr --lang zh --input D:/PaddleSpeech/zh.wav': ???????????

其中"D:\CondaSPACE\envs\paddle_speech\python.exe"    是A电脑上安装Miniconda 对应的安装目录

"D:\CondaSpaceSoft\envs\Scripts\paddlespeech.exe"是B电脑迁移后的Miniconda 对应的安装目录

期望:
这个解决思路 应该往哪里考虑 因为翻了很大资料 好像都没有这个问题
期待回复 谢谢!!!

**Comment by 777sfdf** [comment]
已解决

**Comment by gaohuayang** [comment]
> 已解决

你好，请问怎么解决的，我是直接复制的envs下面的虚拟环境到新电脑，也遇到了这个问题

**Comment by 777sfdf** [comment]
1.首先看下A  B 两台机器上的Miniconda 安装目录名称是否相同 
2.如果不相同   找报错信息里边的  XXX/python.exe 和  XXX/paddlespeech.exe 这两个路径
3.下载软件 wxMedit  (这个软件最好百度下怎么使用)    然后用软件打开其中一个文件  进去以后  搜索A机器上的路径   然后把A机器上的路径 替换成B机器上的路径 另外一个文件也是这样操作的
4.两个文件都修改成功后 重新进行测试即可
