### ISSUE TITLE
【问题解决】解决PaddleSpeech历史问题和BUG

### ISSUE THREAD

**Issue by kk-2000** [PaddlePaddle/PaddleSpeech#3771]
### 背景
paddlespeech目前存在一些历史问题以及长期issue，对这些问题和issue进行修复。

### 现状

1. 对2023.4.10~2024.4.10的issue进行统计和分类，对其中**未解决的BUG**进行处理。
2. 基于paddlepaddle-gpu\=\=2.6.1 paddlespeech\=\=develop对demos进行验证，对发现的问题进行修复。

### issue列表

| 序号 | issue                                                    | 说明                                               | 认领人/状态/PR号 |
| ---- | -------------------------------------------------------- |  -------- | ---------------- |
| 1 | #3777 | demos/audio_content_search的readme问题 | @kk-2000 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#3778](https://github.com/PaddlePaddle/PaddleSpeech/pull/3778)<br> | 
| 2 | #3376 | 文档落后于代码 | @kk-2000 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 3 | #3697 | asr命令未显式指定model报错KeyError | @kk-2000 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@zxcd <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#3794](https://github.com/PaddlePaddle/PaddleSpeech/pull/3794)<br> | 
| 4 | #3620 | ~~函数FrontEngineInterface存在bug~~ |  | 
| 5 | #3444 | paddlespeech.s2t.transform.transformation引入报错 | @kk-2000 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#3779](https://github.com/PaddlePaddle/PaddleSpeech/pull/3779)<br> | 
| 6 | #3536 | ~~paddleaudio构建wheel报错~~ | @kk-2000 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 7 | #3157 | utils/make_filted_shard_list.py 脚本不存在（hold） |  | 
| 8 | #3652 | merge_yi函数存在bug | @mattheliu <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#3786](https://github.com/PaddlePaddle/PaddleSpeech/pull/3786)<br> | 
| 9 | #3544 | gpu版本出错但是cpu版本可运行 | @mattheliu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@zxcd <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#3795](https://github.com/PaddlePaddle/PaddleSpeech/pull/3795)<br> | 
| 10 | #3530 | tts语音合成接口返回base64数据有误 | @mattheliu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 11 | #3339 | 连续点号导致Bug | @kk-2000 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 12 | #3158 | docker镜像bug（hold） |  | 

#### 1. 认领方式
请大家以 comment 的形式认领任务，如：

```
【报名】：1、3、12-13
```
多个任务之间需要使用中文顿号分隔，报名多个连续任务可用横线表示，如 2-5

#### 2. PR提交
- PR名称需要加前缀 **【Fix Speech Issue No.XXX】**
- PR描述中需要附上本issue
- 评论里或者 review request @zxcd  研发会进行审核

### 看板信息
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  【问题解决】解决PaddleSpeech历史问题和BUG  |  12  | 5 / 9 | 41.67% |  4  | 33.33% |
#####

## 统计信息 
> 排名不分先后 @zxcd (2) @kk-2000 (1) @mattheliu (1) 
#####

**Comment by kk-2000** [comment]
【报名】：1-3、5-6、11

**Comment by mattheliu** [comment]
【报名】：8、9、10
