### ISSUE TITLE
【问题解决】待提测和待修复的命令和目录

### ISSUE THREAD

**Issue by kk-2000** [PaddlePaddle/PaddleSpeech#3783]
### 背景
对paddlespeech的demos和example进行验证，对验证通过的命令进行提测，对验证未通过的命令进行修复，详细信息见 [适配验证表](https://doc.weixin.qq.com/sheet/e3_AakAbwboADEmvF8fzDaSqulw0fXi8?scode=AHAA0Qc9AFo1Z909DDAakAbwboADE&tab=wd6qi3)。

### 验证环境
- cuda11.7
- paddlepaddle-gpu==2.6.1
- paddlespeech==develop

### 已验证可提测
| 序号 | 命令                                                         | 目录                             | 结果 | 认领人/状态/PR号 |
| ---- | ------------------------------------------------------------ | -------------------------------- | ---- | ---- |
| 1 | paddlespeech cls --input ./cat.wav --topk 10 | demos/audio_tagging | ![Snipaste_2024-05-14_22-00-10](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/dc8cbaaa-dd94-427f-8e1b-4460228cf9d1) |  | 
| 2 | - | demos/automatic_video_subtitiles | ![Snipaste_2024-05-14_21-32-54](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/41d0162a-7e7f-400b-b9dc-e6d8a138df40) |  | 
| 3 | - | demos/custom_streaming_asr | ![client](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/bd425718-996a-40f5-8d59-7dac2bd74f7e) |  | 
| 4 | paddlespeech kws --input ./hey_snips.wav paddlespeech kws --input ./non-keyword.wav | demos/keyword_spotting | ![Snipaste_2024-05-03_20-39-38](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/a735a044-2a72-482c-9ad9-f06a24763652) |  | 
| 5 | paddlespeech text --input 今天的天气真不错啊你下午有空吗我想约你一起去吃饭 | demos/punctuation_restoration | ![Snipaste_2024-05-03_20-44-20](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/59303319-e64d-4d14-8c68-0da679617bcd) |  | 
| 6 | paddlespeech vector --task spk --input 85236145389.wav | demos/speaker_verification | ![声纹识别](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/b4dd1287-5624-4f2c-aeb1-9f6836a7618f) |  | 
| 7 | - | demos/speech_web | ![Snipaste_2024-06-03_09-22-44](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/8a0f7d61-0fad-4a5e-b932-2d7b85cd40c5) |  | 
| 8 | paddlespeech ssl --task asr --lang en --input ./en.wav | demos/speech_ssl | ![Snipaste_2024-05-03_20-54-43](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/f8a57047-02a8-48dc-9eb8-7877501a90e4) |  | 
| 9 | - | demos/speech_translation | ![docker](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/d662bc02-3a38-41f8-892d-833cdbcb4ab6) |  | 
| 10 | - | demos/streaming_asr_server | ![asr_result](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/25fc3a75-d4c9-4f70-bcf4-3eac49749afe) |  | 
| 11 | - | demos/audio_searching | ![Snipaste_2024-06-04_00-45-19](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/aa49bcb3-ded9-4876-b527-bce6c3a92428) |  | 

### 待修复

| 序号|命令                                                         | 目录                                   | 报错     | 认领人/状态/PR号 |
| ---- |------------------------------------------------------------ | -------------------------------------- | ---- | ---- |
| 12 | - | demos/audio_content_search | #3777 | @kk-2000 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" />  [#3778](https://github.com/PaddlePaddle/PaddleSpeech/pull/3778)<br> | 
| 13 | - | demos/metaverse | 报错glibc |  | 
| 14 | paddlespeech asr --input ./zh.wav -v | demos/speech_recognition | #3697 |  | 
| 15 | - | demos/speech_server | 报错glibc |  | 
| 16 | - | demos/whisper | ![Snipaste_2024-05-14_21-50-57](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/0acb8db4-1a15-40f3-b969-030ab946190f) |  | 
| 17 | - | demos/text_to_speech | 报错glibc |  | 
| 18 | - | demos/streaming_tts_server | 报错glibc |  | 
| 19 | - | demos/streaming_tts_serving_fastdeploy | ![微信图片_20240604214429](https://github.com/PaddlePaddle/PaddleSpeech/assets/52824616/b0e96a90-db7b-4ff5-826e-44a5463f9671) |  | 
| 20 | - | demos/style_fs2 | 报错glibc |  | 
#### 1. 认领方式
请大家以 comment 的形式认领任务，如：

```
【报名】：1、3、12-13
```
多个任务之间需要使用中文顿号分隔，报名多个连续任务可用横线表示，如 2-5

#### 2. PR提交
- PR名称需要加前缀 **【Speech Demo 2.6.1 No.XXX】**
- PR描述中需要附上本issue，提测文档请放到：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/tests/unit/cli
- 评论里或者 review request @zxcd  研发会进行审核
## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  已验证可提测  |  20  | 1 / 1 | 5.0% |  0  | 0.0% |
#####

## 统计信息 
> 排名不分先后 
#####

**Comment by jianghuakun** [comment]
tts server 混合模型代码有修复计划不？
