### ISSUE TITLE
【问题解决】Paddlespeech develop版本待提测和待修复的命令和目录

### ISSUE THREAD

**Issue by mattheliu** [PaddlePaddle/PaddleSpeech#3787]
## 背景
对paddlespeech的demos和example进行验证，对验证通过的命令进行提测，对验证未通过的命令进行修复，详细信息见[适配验证表](https://doc.weixin.qq.com/sheet/e3_AakAbwboADEmvF8fzDaSqulw0fXi8?scode=AHAA0Qc9AFo1Z909DDAakAbwboADE&tab=wd6qi3)

### 验证环境
- cuda11.7
- paddlepaddle-gpu==develop
- paddlespeech==develop

### 已验证可提测
| 序号  | 命令                                                                                  | 目录                               | 结果  | 认领人/状态/PR号 |
| --- | ----------------------------------------------------------------------------------- | -------------------------------- | --- | ---------- |
| 1 | paddlespeech cls --input ./cat.wav --topk 10 | demos/audio_tagging | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/1349640b-dbe2-475c-a38c-321978e4288d) |   | 
| 2 | - | demos/automatic_video_subtitiles | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/e83598f3-d4b9-49ac-882c-5ef561b85ac1) |   | 
| 3 | - | demos/custom_streaming_asr |    ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/cb71b49e-ad06-4ffc-be53-fd275b40a4e6) |   | 
| 4 | paddlespeech kws --input ./hey_snips.wav paddlespeech kws --input ./non-keyword.wav | demos/keyword_spotting | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/04a3e430-2c25-41ca-b584-9ae1fa32a4c4)  |   | 
| 5 | paddlespeech text --input 今天的天气真不错啊你下午有空吗我想约你一起去吃饭 | demos/punctuation_restoration |  ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/465e27cc-a57a-4915-8ee1-64e489aea6f4) |   | 
| 6 | paddlespeech vector --task spk --input 85236145389.wav | demos/speaker_verification |    ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/3bd46636-2bc4-431a-b930-fda15f76e6f8) |   | 
| 7 | paddlespeech asr --input ./zh.wav -v | demos/speech_recognition | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/0dd10113-c068-4c67-a7db-f7dae1a05a9a) |  | 
| 8 | - | demos/speech_translation | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/36215f46-f963-45ca-a26b-6b69ff26f730) |  | 
| 9 | - | demos/speech_web | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/edbd10fa-c3f3-42fe-a2ae-c937e805e200) |  | 
| 10 | - | demos/streaming_asr_server | ![image](https://github.com/PaddlePaddle/PaddleSpeech/assets/102272920/b63e1d4b-daa0-47c8-a999-3718cce346ce) |  | 

### 待修复
| 序号  | 命令                                                                         | 目录                                     | 结果  | 认领人/状态/PR号 |
| --- | -------------------------------------------------------------------------- | -------------------------------------- | --- | ---------- |
| 11 | paddlespeech_client acs --server_ip 127.0.0.1 --port 8090 --input ./zh.wav | demos/audio_content_search | -   |  @mattheliu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 12 | - | demos/audio_searching | -   |  @mattheliu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 13 | - | demos/metaverse | - |   | 
| 14 | paddlespeech_server start --config_file ./conf/application.yaml | demos/speech_server | -   |   | 
| 15 | paddlespeech ssl --task asr --lang en --input ./en.wav | demos/speech_ssl | -   |   | 
| 16 | - | demos/whisper | - |   | 
| 17 | - | demos/text_to_speech | - |   | 
| 18 | - | demos/streaming_tts_server | - |   | 
| 19 | - | demos/streaming_tts_serving_fastdeploy | -   |   | 
| 20 | - | demos/style_fs2 | - |   | 
| 21 | - | demos/story_talker | - |  | 

#### 1. 认领方式
请大家以 comment 的形式认领任务，如：

```
【报名】：1、3、12-13
```
多个任务之间需要使用中文顿号分隔，报名多个连续任务可用横线表示，如 2-5

#### 2. PR提交
PR名称需要加前缀 **【Speech Demo develop No.XXX】**
PR描述中需要附上本issue，提测文档请放到：
https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/tests/unit/cli
评论里或者 review request @zxcd 研发会进行审核

## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
|  已验证可提测  |  21  | 0 / 2 | 0.0% |  0  | 0.0% |
#####

## 统计信息 
> 排名不分先后 
#####

**Comment by mattheliu** [comment]
【报名】：11-12

**Comment by jianghuakun** [comment]
请问websocket 不支持混合tts和asr有修复计划不

**Comment by zxcd** [comment]
> 请问websocket 不支持混合tts和asr有修复计划不

这个属于功能新增，不属于需要修复的bug。目前对于功能新增暂无相应排期。

**Comment by jianghuakun** [comment]
> > 请问websocket 不支持混合tts和asr有修复计划不
> 
> 这个属于功能新增，不属于需要修复的bug。目前对于功能新增暂无相应排期。
请问websocket支持mix的源代码有没？自己修改能启动，但是没声音

**Comment by jianghuakun** [comment]
> > > 请问websocket 不支持混合tts和asr有修复计划不
> > 
> > 
> > 这个属于功能新增，不属于需要修复的bug。目前对于功能新增暂无相应排期。
> > 请问websocket支持mix的源代码有没？自己修改能启动，但是没声音

TTS的，比如支持fastspeech2_mix模型。源码只支持zh和en
(https://paddlespeech.bj.bcebos.com/t2s/chinse_english_mixed/models/fastspeech2_mix_ckpt_1.2.0.zip)
