### ISSUE TITLE
折腾了两天，安装不了，不是这依赖有问题，就是那莫名奇妙报个错，没法用

### ISSUE THREAD

**Issue by chenmj201601** [PaddlePaddle/PaddleSpeech#3885]

**Comment by TianQi7723** [comment]
跟你情况差不多，后来拉了个python3.10的虚拟环境，按照文档安dev版本直接成功了，之前用python3.11安各种依赖问题，主要是我知道3.8到3.10，但是我要用的其他开源的需要最低3.11，我想把他们串起来就直接在3.11那个环境搞得

**Comment by chenmj201601** [comment]
python3.9  3.10 我都试了，都有问题，cpu和gpu环境我也都试了，都不行，报错很多。。。

**Comment by chenmj201601** [comment]
`Error: Can not import paddle core while this file exists: /root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/workspace/demo2.py", line 1, in <module>
    import paddle
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/root/miniconda3/envs/paddle_demo/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
`

这个是咋回事，单独安装 paddlepaddle没有问题，然后再安装paddlespeech，然后paddle导入就报错了，安装paddlespeech好像会把paddlepaddle卸载了重装。。。

**Comment by wukongbuku** [comment]
> python3.9 3.10 我都试了，都有问题，cpu和gpu环境我也都试了，都不行，报错很多。。。

是的，当时我也鼓捣了好几天，也是各种报错，最后放弃了。
最大的问题是，好多环境都特别老，然后已经停止维护好长时间了

**Comment by TianQi7723** [comment]
![微信截图_20241115091354](https://github.com/user-attachments/assets/850e73a4-6900-49c6-a6d6-4046750f6a01)
我这边反正没啥问题，给你说下我操作流程，就是用conda起个python3.10的环境，然后安装paddle 2.5.1版本的，我安的是gpu版的，然后paddlespeech安装devlope版本，就是源码安装，命令直接用文档给的就行，安装完看speech的版本显示的是0.0.0，然后就好使了，我之前因为别的特殊原因需要用到其他开源框架，那些最低要python3.11版本的所以用的也是3.11环境，结果就各种依赖报错，然后换了3.10之后吧安装paddle不是2.5.1版本的，跟源码安装的也报依赖错，就py3.10+paddle2.5.1+paddlespeech0.0.0没问题

**Comment by TianQi7723** [comment]
> ![微信截图_20241115091354](https://private-user-images.githubusercontent.com/64953264/386419634-850e73a4-6900-49c6-a6d6-4046750f6a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzM5NDIsIm5iZiI6MTczMTYzMzY0MiwicGF0aCI6Ii82NDk1MzI2NC8zODY0MTk2MzQtODUwZTczYTQtNjkwMC00OWM2LWE2ZDYtNDA0Njc1MGY2YTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAxMjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMGE4MTAxNDMzY2MzZWFjZGE1NmU1MTQ2MGE1Yzg5NzcwNDQzM2ZkNTI5NTlmY2M4NjFiNWE4NmU3ZjY1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mpSE-2VtoV6MWOF2CaGwv_lWXbdy1TVXE6ihha-7-MY) 我这边反正没啥问题，给你说下我操作流程，就是用conda起个python3.10的环境，然后安装paddle 2.5.1版本的，我安的是gpu版的，然后paddlespeech安装devlope版本，就是源码安装，命令直接用文档给的就行，安装完看speech的版本显示的是0.0.0，然后就好使了，我之前因为别的特殊原因需要用到其他开源框架，那些最低要python3.11版本的所以用的也是3.11环境，结果就各种依赖报错，然后换了3.10之后吧安装paddle不是2.5.1版本的，跟源码安装的也报依赖错，就py3.10+paddle2.5.1+paddlespeech0.0.0没问题

哦对，还有一步，就是用这个命令安一下 conda install -y -c conda-forge sox libsndfile swig bzip2，，作者文档写的[https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md)

**Comment by chenmj201601** [comment]
> > ![微信截图_20241115091354](https://private-user-images.githubusercontent.com/64953264/386419634-850e73a4-6900-49c6-a6d6-4046750f6a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzM5NDIsIm5iZiI6MTczMTYzMzY0MiwicGF0aCI6Ii82NDk1MzI2NC8zODY0MTk2MzQtODUwZTczYTQtNjkwMC00OWM2LWE2ZDYtNDA0Njc1MGY2YTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAxMjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMGE4MTAxNDMzY2MzZWFjZGE1NmU1MTQ2MGE1Yzg5NzcwNDQzM2ZkNTI5NTlmY2M4NjFiNWE4NmU3ZjY1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mpSE-2VtoV6MWOF2CaGwv_lWXbdy1TVXE6ihha-7-MY) 我这边反正没啥问题，给你说下我操作流程，就是用conda起个python3.10的环境，然后安装paddle 2.5.1版本的，我安的是gpu版的，然后paddlespeech安装devlope版本，就是源码安装，命令直接用文档给的就行，安装完看speech的版本显示的是0.0.0，然后就好使了，我之前因为别的特殊原因需要用到其他开源框架，那些最低要python3.11版本的所以用的也是3.11环境，结果就各种依赖报错，然后换了3.10之后吧安装paddle不是2.5.1版本的，跟源码安装的也报依赖错，就py3.10+paddle2.5.1+paddlespeech0.0.0没问题
> 
> 哦对，还有一步，就是用这个命令安一下 conda install -y -c conda-forge sox libsndfile swig bzip2，，作者文档写的https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md

谢谢，我试试

**Comment by chenmj201601** [comment]
> > ![微信截图_20241115091354](https://private-user-images.githubusercontent.com/64953264/386419634-850e73a4-6900-49c6-a6d6-4046750f6a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzM5NDIsIm5iZiI6MTczMTYzMzY0MiwicGF0aCI6Ii82NDk1MzI2NC8zODY0MTk2MzQtODUwZTczYTQtNjkwMC00OWM2LWE2ZDYtNDA0Njc1MGY2YTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAxMjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMGE4MTAxNDMzY2MzZWFjZGE1NmU1MTQ2MGE1Yzg5NzcwNDQzM2ZkNTI5NTlmY2M4NjFiNWE4NmU3ZjY1NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mpSE-2VtoV6MWOF2CaGwv_lWXbdy1TVXE6ihha-7-MY) 我这边反正没啥问题，给你说下我操作流程，就是用conda起个python3.10的环境，然后安装paddle 2.5.1版本的，我安的是gpu版的，然后paddlespeech安装devlope版本，就是源码安装，命令直接用文档给的就行，安装完看speech的版本显示的是0.0.0，然后就好使了，我之前因为别的特殊原因需要用到其他开源框架，那些最低要python3.11版本的所以用的也是3.11环境，结果就各种依赖报错，然后换了3.10之后吧安装paddle不是2.5.1版本的，跟源码安装的也报依赖错，就py3.10+paddle2.5.1+paddlespeech0.0.0没问题
> 
> 哦对，还有一步，就是用这个命令安一下 conda install -y -c conda-forge sox libsndfile swig bzip2，，作者文档写的https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/install_cn.md

![image](https://github.com/user-attachments/assets/10a7dd16-f806-4af6-a9f3-decd78508d5a)

还是不行，C++好像有问题

**Comment by chenmj201601** [comment]
![image](https://github.com/user-attachments/assets/e23dc8c8-d4ec-414c-99b5-b1035ad65f62)

经常遇到这样的错误

**Comment by Ray961123** [comment]
开发者你好，感谢关注 PaddleSpeech 开源项目，抱歉给你带来了不好的开发体验，目前开源项目维护人力有限，你可以尝试通过修改 PaddleSpeech 源码的方式自己解决，或请求开源社区其他开发者的协助。飞桨开源社区交流频道：[飞桨AI Studio星河社区-人工智能学习与实训社区](https://aistudio.baidu.com/community/channel/306)

**Comment by zxcd** [comment]
> ![image](https://private-user-images.githubusercontent.com/19809251/386546893-e23dc8c8-d4ec-414c-99b5-b1035ad65f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Njk1NjIsIm5iZiI6MTczMTY2OTI2MiwicGF0aCI6Ii8xOTgwOTI1MS8zODY1NDY4OTMtZTIzZGM4YzgtZDRlYy00MTRjLTk5YjUtYjEwMzVhZDY1ZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDExMTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNGRhM2RjYmJjZWQ2Y2VkZDkyOGNlMWVkZDEzZjBiMDMyNzcwMGU5OWMwY2IxNmQ0MmMxZTlhNmY5MmU2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-fvbIOiKVGvgYJ_QNT_N_SrB_8AAjC42roHv7GB1_Oo)
> 
> 经常遇到这样的错误

这种错误一般是因为openssl的版本过低导致的，可以尝试升级下到你python对应的版本

**Comment by chenmj201601** [comment]
> > ![image](https://private-user-images.githubusercontent.com/19809251/386546893-e23dc8c8-d4ec-414c-99b5-b1035ad65f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2Njk1NjIsIm5iZiI6MTczMTY2OTI2MiwicGF0aCI6Ii8xOTgwOTI1MS8zODY1NDY4OTMtZTIzZGM4YzgtZDRlYy00MTRjLTk5YjUtYjEwMzVhZDY1ZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDExMTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNGRhM2RjYmJjZWQ2Y2VkZDkyOGNlMWVkZDEzZjBiMDMyNzcwMGU5OWMwY2IxNmQ0MmMxZTlhNmY5MmU2ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-fvbIOiKVGvgYJ_QNT_N_SrB_8AAjC42roHv7GB1_Oo)
> > 经常遇到这样的错误
> 
> 这种错误一般是因为openssl的版本过低导致的，可以尝试升级下到你python对应的版本

感谢回答，好像是libssl版本不兼容，我的系统上是libssl3，paddlepaddle需要libssl1.1，我下载了libssl1.1的包安装一下就行了。

**Comment by DazzlingGalaxy** [comment]
[文档](https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/README_cn.md)中说`paddlepaddle <= 2.5.1`，我新装的centos 7.9，python 3.8，参考这个[文章](https://blog.csdn.net/riding_horse/article/details/132278379)，注意把文章里的`yum install -y zlib perl`改成`yum install -y zlib zlib-devel perl`，不然后面会报其他错误，然后再安装
```
pip install paddlepaddle==2.5.1
pip install pytest-runner
pip install paddlespeech
```

为了防止文章失效，我写出完整的
```
yum install gcc gcc-c++

1.下载
wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz

2.解压
tar -xf openssl-1.0.2o.tar.gz
cd openssl-1.0.2o/

3.安装
yum remove -y openssl-devel
yum install -y zlib zlib-devel perl
./config --prefix=/usr/local/openssl shared zlib
make depend
make && make install

4.备份
mv /usr/bin/openssl /root/openssl
mv /usr/include/openssl/  /usr/include/openssl_bak

5.配置
echo "/usr/local/openssl/lib" >> /etc/ld.so.conf
ldconfig -v
ln -s /usr/local/openssl/bin/openssl /usr/bin/ 
ln -s /usr/local/openssl/include/openssl/ /usr/include/ 

6.测试
#openssl version
OpenSSL 1.0.2o  27 Mar 2018

7.报错解决
openssl: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
openssl: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

ln -s /usr/local/lib64/libssl.so.1.1 /usr/lib64/libssl.so.1.1
ln -s /usr/local/lib64/libcrypto.so.1.1 /usr/lib64/libcrypto.so.1.1
```

**Comment by yangzheng119** [comment]
> ![微信截图_20241115091354](https://github.com/user-attachments/assets/850e73a4-6900-49c6-a6d6-4046750f6a01) 我这边反正没啥问题，给你说下我操作流程，就是用conda起个python3.10的环境，然后安装paddle 2.5.1版本的，我安的是gpu版的，然后paddlespeech安装devlope版本，就是源码安装，命令直接用文档给的就行，安装完看speech的版本显示的是0.0.0，然后就好使了，我之前因为别的特殊原因需要用到其他开源框架，那些最低要python3.11版本的所以用的也是3.11环境，结果就各种依赖报错，然后换了3.10之后吧安装paddle不是2.5.1版本的，跟源码安装的也报依赖错，就py3.10+paddle2.5.1+paddlespeech0.0.0没问题

有用，感谢
