### ISSUE TITLE
加载预训练好的中文声学模型训练自己的模型，mean_std.npz该如何更新？

### ISSUE THREAD

**Issue by suntingfeng** [PaddlePaddle/PaddleSpeech#400]
你好，加载预训练好的中文声学模型训练自己的模型，mean_std.npz该如何更新？因为提供的mean_std.npz包含的是你们预训练数据集样本特征的均值和标准差，现在我想包含我自己样本数据和你们数据的特征的均值和标准差。这个我该如何做呢？

**Comment by suntingfeng** [comment]
我是不是可以使用自己的数据生成mean和std，然后读取提供的mean_std.npz，两者进行拼接啊？

**Comment by lfchener** [comment]
@suntingfeng 
可以参考 readme 里 **数据准备** 部分的描述：
https://github.com/PaddlePaddle/DeepSpeech#compute-mean--stddev-for-normalizer
