### ISSUE TITLE
按照docker一步一步装好，下载完data，sh run_train.sh就出错

### ISSUE THREAD

**Issue by WilliamEt** [PaddlePaddle/PaddleSpeech#405]
在example/tiny目录下
sh run_data.sh正常下载好librispeech的test-clean和dev-clean
然后 sh run_train.sh就报错
报错信息如下：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model_utils.model import DeepSpeech2Model
  File "/DeepSpeech/model_utils/model.py", line 23, in <module>
    from model_utils.network import deep_speech_v2_network
  File "/DeepSpeech/model_utils/network.py", line 62, in <module>
    class RNNCell(fluid.layers.RNNCell):
AttributeError: 'module' object has no attribute 'RNNCell'
Failed in training!
请问这是什么原因呢

**Comment by 1003657663** [comment]
这个怎么解决的呀？

**Comment by 1003657663** [comment]
这个怎么解决的呀？
