### ISSUE TITLE
Error: You are not allowed to load partial data via load_combine_op, use load_op instead

### ISSUE THREAD

**Issue by wueching** [PaddlePaddle/PaddleSpeech#408]
λ 8aa2aa3cf875 /DeepSpeech/examples/tiny ./run_infer_golden.sh
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
Download Aishell model ...
./aishell_model_fluid.tar.gz already exists, download skipped.
mean_std.npz
README.md
vocab.txt
params.pdparams
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/aishell/mean_std.npz
model_path: models/aishell
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 1
specgram_type: linear
use_gpu: 0
use_gru: 0
vocab_path: models/aishell/vocab.txt
------------------------------------------------
2020-01-03 01:31:14,458-INFO: begin to initialize the external scorer for decoding
2020-01-03 01:31:14,612-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-01-03 01:31:14,612-INFO: end initializing scorer
2020-01-03 01:31:14,613-INFO: start inference ...
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "infer.py", line 152, in <module>
    main()
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "/DeepSpeech/model_utils/model.py", line 412, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 798, in load_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 726, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, paddle::platform::Place const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const
3   paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 725, in load_vars
    attrs={'file_path': os.path.join(load_dirname, filename)})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 798, in load_params
    filename=filename)
  File "/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/DeepSpeech/model_utils/model.py", line 412, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "infer.py", line 124, in infer
    feeding_dict=data_generator.feeding)
  File "infer.py", line 148, in main
    infer()
  File "infer.py", line 152, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: You are not allowed to load partial data via load_combine_op, use load_op instead. at (/paddle/paddle/fluid/operators/load_combine_op.h:105)
  [operator < load_combine > error]
Failed in inference!

How to solve this problem?thanks.

**Comment by lfchener** [comment]
Show me the paddle version please. @wueching

**Comment by wueching** [comment]
λ 8aa2aa3cf875 /DeepSpeech/examples/tiny paddle --version
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
PaddlePaddle 1.6.2, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
@lfchener

**Comment by wueching** [comment]
λ 8aa2aa3cf875 /DeepSpeech/examples/tiny ./run_infer_golden.sh
Download language model ...
./zh_giga.no_cna_cmn.prune01244.klm already exists, download skipped.
Download Aishell model ...
./aishell_model_fluid.tar.gz already exists, download skipped.
mean_std.npz
README.md
vocab.txt
params.pdparams
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/baidu_cn1.2k/mean_std.npz
model_path: models/baidu_cn1.2k
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 0
specgram_type: linear
use_gpu: 0
use_gru: 1
vocab_path: models/baidu_cn1.2k/vocab.txt
------------------------------------------------
2020-01-03 02:25:10,600-INFO: begin to initialize the external scorer for decoding
2020-01-03 02:25:10,767-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-01-03 02:25:10,767-INFO: end initializing scorer
2020-01-03 02:25:10,768-INFO: start inference ...
finish initing model from pretrained params from models/baidu_cn1.2k

Target Transcription: 研究者们选取了十九位跑者
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 长期跑步可能是一种不需要药物来保持身材的有效方式
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 朱军系阅兵世家曾参与一九八四年阅兵军乐演奏
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 年龄从二十三岁到五十九岁
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 三四线城市依然冷清
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 扩大它们在新的芯片市场的份额
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 可以有效的抵消年龄所带来的速度劣势
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 仍在个人社群网站频繁更新动态
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 有关部门和社会各界积极响应
Output Transcription: 
Current error rate [cer] = 1.000000

Target Transcription: 巨人网络盛大游戏以及完美世界均已选择了私有化
Output Transcription: 
Current error rate [cer] = 1.000000
2020-01-03 02:26:39,531-INFO: finish inference

The results are all none,what happened?

**Comment by wueching** [comment]
env:  windows7->VMware->Ubuntu14->Docker->hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu

**Comment by bigcash** [comment]
@wueching how did you fix your first problem， about "Error: You are not allowed to load partial data via load_combine_op, use load_op instead. at (/paddle/paddle/fluid/operators/load_combine_op.h:105)"

**Comment by wueching** [comment]
set share_rnn_weights to False and use_gru to True @bigcash

**Comment by wueching** [comment]
why is the output all none?Any one can help?

**Comment by wueching** [comment]
lm_dict_size = self._ext_scorer.get_dict_size()，return 0,it shoud be the reason.

**Comment by bigcash** [comment]
@wueching thanks, it works.
my command which works:
python deploy/demo_server.py --host_ip 0.0.0.0 --host_port 10010 --warmup_manifest data/aishell/manifest.test --beam_size=300 --rnn_layer_size=1024 --alpha=2.6 --beta=5.0 --cutoff_prob=0.99 --use_gru=True --use_gpu=True --share_rnn_weights=False --mean_std_path=models/aishell/mean_std.npz --vocab_path=models/aishell/vocab.txt --model_path=models/aishell/ --lang_model_path=models/lm/zh_giga.no_cna_cmn.prune01244.klm

**Comment by duan348733684** [comment]
@wueching   how did you fix your second problem that  the results are all none....
