### ISSUE TITLE
use CN1.2K model do not have manifest_path

### ISSUE THREAD

**Issue by wanwanzaizai** [PaddlePaddle/PaddleSpeech#411]
download 2.8g lm and baidu_cn1.2k_model_fluid.tar.gz but i can't find manifest_path when i extract file

**Comment by bigcash** [comment]
baidu_cn1.2k_model_fluid.tar.gz is model, it does not have a  manifest
manifest need you to make it yourself from dataset, see "Generate Manifest" of readme
