### ISSUE TITLE
模型部署后，对长语音是否支持？

### ISSUE THREAD

**Issue by bigcash** [PaddlePaddle/PaddleSpeech#412]
您好，感谢开源！
我部署启动了deploy/demo_server.py，测试大概40分钟的语音，wav文件8000rate的有38M的时候，报内存溢出错误：Out of memory error on GPU 0.  我使用的是2080Ti的单卡进行测试的，显存11019MiB，是不是这种长语音需要对音频进行切割，一般怎样切割可以使最终结果更加准确，是固定时长切割（如按每隔10s切割）还是按录音中没有语音信号时切割的？
我也使用过百度云中提供的api进行语音转文字，是将40分钟录音文件直接提交的，是不是在服务端先进行了语音分割，然后再对所有结果合并，最后给出结果的？
多谢解惑！！

server端报错如下（使用BaiduCN1.2k模型）：
Received utterance[length=40108716] from 172.16.1.18, saved to demo_cache/20200109031539_172.16.1.18.wav.
finish initing model from pretrained params from models/BaiduCN1.2k/
W0109 11:16:28.406390 11887 operator.cc:179] mul raises an exception paddle::memory::allocation::BadAlloc, 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   paddle::memory::detail::GPUAllocator::Alloc(unsigned long*, unsigned long)
1   paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long)
2   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
3   void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long)
4   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::Allocator::Allocate(unsigned long)
6   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place, paddle::framework::proto::VarType_Type, unsigned long)
11  paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
12  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
16  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
17  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

----------------------
Error Message Summary:
----------------------

Out of memory error on GPU 0. Cannot allocate 1.912537GB memory on GPU 0, available memory is only 381.125000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.92 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:151)
----------------------------------------
Exception happened during processing of request from ('172.16.1.18', 55944)
Traceback (most recent call last):
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "deploy/demo_server.py", line 101, in handle
    transcript = self.server.audio_process_handler(filename)
  File "deploy/demo_server.py", line 195, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/home/lingbao/work/text/DeepSpeech/deploy/../model_utils/model.py", line 424, in infer_batch_probs
    return_numpy=False)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/lingbao/soft/anaconda3/envs/baidu27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
RuntimeError: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   paddle::memory::detail::GPUAllocator::Alloc(unsigned long*, unsigned long)
1   paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long)
2   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
3   void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long)
4   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::Allocator::Allocate(unsigned long)
6   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place, paddle::framework::proto::VarType_Type, unsigned long)
11  paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
12  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
16  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
17  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

----------------------
Error Message Summary:
----------------------

Out of memory error on GPU 0. Cannot allocate 1.912537GB memory on GPU 0, available memory is only 381.125000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.92 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:151)

----------------------------------------

**Comment by lfchener** [comment]
感谢关注！
40min 这么长的语音的话，建议你可以先以句子为单位进行切割，既按录音中没有语音信号的时长来作为条件切割，再进行识别。

**Comment by karlkao** [comment]
I ran into the similar issue while training with aishell dataset.
Rerunning the same training doesn't help to resolve this issue. However, GPU # may be different. For example, the attached error message shows "GPU 1", and I could find "GPU 4" or "GPU 5" in other failed instances.

----------------------
Error Message Summary:
----------------------


Out of memory error on GPU 1. Cannot allocate 411.427979MB memory on GPU 1, available memory is only 239.875000MB.

Please check whether there is any other process using GPU 1.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.92 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

 at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:151)
F0122 08:24:48.161250   272 exception_holder.h:37] std::exception caught,



W0122 08:24:48.161155   272 operator.cc:179] warpctc raises an exception paddle::memory::allocation::BadAlloc,

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   paddle::memory::detail::GPUAllocator::Alloc(unsigned long*, unsigned long)
1   paddle::memory::detail::BuddyAllocator::RefillPool(unsigned long)
2   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
3   void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long)
4   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
5   paddle::memory::allocation::Allocator::Allocate(unsigned long)
6   paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place, paddle::framework::proto::VarType_Type, unsigned long)
11  float* paddle::framework::Tensor::mutable_data<float>(paddle::framework::DDim, paddle::platform::Place, unsigned long)
12  paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
13  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::WarpCTCKernel<paddle::platform::CUDADeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
15  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
16  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
17  paddle::framework::details::ComputationOpHandle::RunImpl()
18  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
19  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
20  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
21  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
22  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

 at (/paddle/paddle/fluid/memory/detail/system_allocator.cc:151)

*** Check failure stack trace: ***
    @     0x7fa637364c0d  google::LogMessage::Fail()
    @     0x7fa6373686bc  google::LogMessage::SendToLog()
    @     0x7fa637364733  google::LogMessage::Flush()
    @     0x7fa637369bce  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa6398e75a8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7fa639981d0b  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7fa6399808ef  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7fa639980bb4  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7fa637483d13  std::_Function_handler<>::_M_invoke()
    @     0x7fa6372cfe37  std::__future_base::_State_base::_M_do_set()
    @     0x7fa6fc058a99  __pthread_once_slow
    @     0x7fa63997c702  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7fa6372d15f4  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7fa6edc83c80  (unknown)
    @     0x7fa6fc0516ba  start_thread
    @     0x7fa6fbd8741d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
Failed in training!

**Comment by bigcash** [comment]
@lfchener 多谢，在查资料时也发现了，需要预先做vad的处理。

**Comment by bigcash** [comment]
@karlkao reduce your training batch size， may be help

**Comment by ccbptm** [comment]
> @lfchener 多谢，在查资料时也发现了，需要预先做vad的处理。

你好，我现在要直接用这个去搭建一个在线中文识别的工程，但是我在线语音识别很差，想着是不是要对原始的语音数据进行一些降噪增强和其他什么处理？请问您可以稍微具体的分享一下你的vad的处理用的方法和库么？谢谢

**Comment by zh794390558** [comment]
vad试下webrtcvad。

**Comment by jkluo** [comment]
> 

@bigcash 你好，请问最后你有解决长语音的问题吗？请教一下大佬具体的解决方式。

**Comment by bigcash** [comment]
> 

就像上边说的，先把长语音用vad切分为多个语音段，然后分别asr后，结果合并起来

**Comment by bigcash** [comment]
> > 
> 
> @bigcash 你好，请问最后你有解决长语音的问题吗？请教一下大佬具体的解决方式。

就像上边说的，先用vad将长语音切分为多个短语音段，然后把结果合并起来
