### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by ArtemiyFirsov** [PaddlePaddle/PaddleSpeech#413]
Getting the error on Ubuntu 18.04 Docker installation.
Running docker with 
`sudo docker run --gpus=all -it -v $(pwd)/DeepSpeech:/DeepSpeech hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu /bin/bash`

Updated the code to the latest develop branch.

Error happens on infer 
`CUDA_VISIBLE_DEVICES=0 python infer.py --infer_manifest test_deep_speech.txt`

Manifest I am trying to infer 
`{"audio_filepath": "/DeepSpeech/test_deep_speech.wav", "duration": 30.960, "text": ""}`

So it does not even goes to the infer, it fails on data read, because the code tried to convert text to int.

UPDATE: sorry, this is in the DeepSpeech repo

![image](https://user-images.githubusercontent.com/4475110/72521299-c2533a80-388d-11ea-817f-3fcd90fb08d9.png)

**Comment by ArtemiyFirsov** [comment]
Another question is - why it needs transcription on infer stage?
I think it is not used further, but still without it it fails with error

**Comment by ArtemiyFirsov** [comment]
@lfchener, I see that is your latest commit, that did that, can you please help?

**Comment by lfchener** [comment]
Thanks for attention!
About the error happens on infer, it is a bug, we have fixed it now.
About why it needs transcription on infer stage, because we compute the WER/CER after infer each sentence, transcription is the ground truth.
Thanks again.
