### ISSUE TITLE
docker image for cpu

### ISSUE THREAD

**Issue by wanwanzaizai** [PaddlePaddle/PaddleSpeech#416]
Is there a CPU version of docker image

**Comment by wanwanzaizai** [comment]
i try it install by myself but the soundfile can not install to centos8

**Comment by loretoparisi** [comment]
It would be worth to have a CPU version.

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
