### ISSUE TITLE
Inference output majorly incorrect with aishell test sample, using "models/baidu_cn1.2k" and "models/lm/zhidao_giga.klm"

### ISSUE THREAD

**Issue by karlkao** [PaddlePaddle/PaddleSpeech#423]
sh run_infer_golden.sh
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-----------  Configuration Arguments -----------
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: models/lm/zhidao_giga.klm
mean_std_path: models/baidu_cn1.2k/mean_std.npz
model_path: models/baidu_cn1.2k
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 0
specgram_type: linear
use_gpu: 0
use_gru: 1
vocab_path: models/baidu_cn1.2k/vocab.txt
------------------------------------------------
2020-02-04 23:59:20,513-INFO: begin to initialize the external scorer for decoding
2020-02-04 23:59:23,525-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-02-04 23:59:23,525-INFO: end initializing scorer
2020-02-04 23:59:23,525-INFO: start inference ...
finish initing model from pretrained params from models/baidu_cn1.2k

Target Transcription: 开发边界将作为城市发展的刚性约定
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 成交量环比大幅增加
Output Transcription: 啊
Current error rate [cer] = 1.000000

Target Transcription: 也有限购政策在控制需求规模
Output Transcription: 我
Current error rate [cer] = 1.000000

Target Transcription: 本月中下旬小行星撞地球
Output Transcription: 我
Current error rate [cer] = 1.000000

Target Transcription: 好莱坞当红明星之前曾被盛传将扮演斯诺登
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 公司已将原有的直销模式改为经销模式
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 制定了可再生能源电价附加补贴和配额交易方案
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 坚持违法零容忍和高限处理的执法态度
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 构建良好的旅游市场环境
Output Transcription: 我
Current error rate [cer] = 1.000000

Target Transcription: 今年芯片行业并购交易额在八百亿美元以上
Output Transcription:
Current error rate [cer] = 1.000000
2020-02-05 00:00:18,121-INFO: finish inference

**Comment by nerv3890** [comment]
Just change ur inputs audio sample rate to 8k

**Comment by ccbptm** [comment]
> Just change ur inputs audio sample rate to 8k

可是用baidu_cn 1.2k Model可以在deploy中识别16kHz的实时输入啊。为什么对aishell的test数据就cer=1.0000这样呢
