### ISSUE TITLE
运行 tune.py 时总是会中断

### ISSUE THREAD

**Issue by ChenHuaYou** [PaddlePaddle/PaddleSpeech#425]
次次都会killed
python tools/tune.py 
-----------  Configuration Arguments -----------
alpha_from: 1.0
alpha_to: 3.2
batch_size: 256
beam_size: 300
beta_from: 0.1
beta_to: 0.45
cutoff_prob: 1.0
cutoff_top_n: 40
error_rate_type: wer
lang_model_path: models/lm/zhidao_giga.klm
mean_std_path: models/mean_std.npz
model_path: models
num_alphas: 45
num_batches: -1
num_betas: 8
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
trainer_count: 8
tune_manifest: data/aishell/manifest.dev
use_gpu: False
use_gru: True
vocab_path: models/vocab.txt
------------------------------------------------
2020-02-13 20:14:27,192-INFO: begin to initialize the external scorer for decoding
2020-02-13 20:25:17,093-INFO: language model: is_character_based = 1, max_order = 5, dict_size = 0
2020-02-13 20:25:17,159-INFO: end initializing scorer
2020-02-13 20:25:17,160-INFO: start tuning ...
finish initing model from pretrained params from models
Killed

**Comment by kuke** [comment]
可能是tuning过程中的内存溢出了，可以观察一下内存占用来确认。如果确定是内存溢出的问题，可以通过不断减小batch size来解决
