### ISSUE TITLE
BaiduCN1.2k  准确率超级低

### ISSUE THREAD

**Issue by ChenHuaYou** [PaddlePaddle/PaddleSpeech#428]
有没有官方demo?这么大的模型文件居然是这么偏差，不知道是不是参数没对，也没具体demo

**Comment by kuke** [comment]
这个模型结构无问题，但训练所用的语料较少，而且有偏，效果确实不好，仅作演示用

**Comment by BABALA258** [comment]
确实准确率极其低，可是号称用了1200小时的语料训练的，
