### ISSUE TITLE
paddlepaddle deepspeech2 on python3 

### ISSUE THREAD

**Issue by nayanhalder** [PaddlePaddle/PaddleSpeech#430]
Currently paddlepaddle deepspeech2 is supported only in python2.7.  is it also supported in python 3.

**Comment by lfchener** [comment]
Python3 is not supported at this time, because some third-party libraries used in deepspeech2 only support python2.

**Comment by loretoparisi** [comment]
@lfchener which is the main technical reason why Python3 is not supported right no? [Currently](https://pypi.org/project/paddlepaddle/#files) PaddlePaddle supports Python 3.7.
Thank you.

**Comment by nayanhalder** [comment]
@lfchener  thanks for your reply. It will be very nice if you please let us know when python3 version will be available.

**Comment by shoegazerstella** [comment]
[Here](https://github.com/shoegazerstella/DeepSpeech_CPU_py37) a version of DeepSpeech with Python 3.7 support for CPU use only (inference).

**Comment by loretoparisi** [comment]
> [Here](https://github.com/shoegazerstella/DeepSpeech_CPU_py37) a version of DeepSpeech with Python 3.7 support for CPU use only (inference).

@lfchener would be awesome to have this integrated in the next releases!!! kudos to @shoegazerstella 🥇

**Comment by nayanhalder** [comment]
@lfchener , @shoegazerstella thanks a lot everyone for publishing the cpu version in python3.7. Also it will be very nice if gpu version in python3 be published soon. I am using paddlepaddle deepspeech2 in gpu in python2.7.

**Comment by nayanhalder** [comment]
@lfchener , @shoegazerstella
Can you please let us know when the gpu version of paddlepaddle DeepSpeech for python3 will be published. Thanks

**Comment by loretoparisi** [comment]
@nayanhalder I have added a feature request here https://github.com/shoegazerstella/DeepSpeech_CPU_py37/issues/1

**Comment by nayanhalder** [comment]
@lfchener , @shoegazerstella
Can you please let us know when the gpu version of paddlepaddle DeepSpeech for python3 will be published. Thanks

**Comment by zh794390558** [comment]
will coming soon~
