### ISSUE TITLE
添加新的数据，怎么修改最后一层继续训练？

### ISSUE THREAD

**Issue by yzcm1232** [PaddlePaddle/PaddleSpeech#435]
fluid版本，现在有新的数据，导致了vocab尺寸变大，想在已有的预训练模型上继续训练，怎么修改最后一层的尺寸大小？在其他问题里面，还没有看到解决方案。

**Comment by lfchener** [comment]
最后一层尺寸的大小是根据模型输入的词表文件计算出来的，如果你有了新的数据，你需要重新生成词表文件，可参考 README 中 **建立词表** 部分来进行。
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/README_cn.md#%E5%BB%BA%E7%AB%8B%E8%AF%8D%E8%A1%A8
之后在训练模型中加载新生成的词表文件，模型最后一层的尺寸会是新的词表的大小。

**Comment by yzcm1232** [comment]
那之前的预训练模型，只是最后一层的大小没匹配，就不能用了吗，没办法当成训练结点，在后面的训练中指定到init_from_pretrained_model了吗，这样加入了新数据，就要重新训练，还是挺影响速度和消耗资源的。

**Comment by zh794390558** [comment]
可以考虑从pretrain模型加载参数，固定其他层的参数，finetune最后一层。
