### ISSUE TITLE
[ERROR] SIGSEGV (@0x7f20ad805b40) received by PID 38 

### ISSUE THREAD

**Issue by loretoparisi** [PaddlePaddle/PaddleSpeech#444]
We report this error on a 32GB machine

```
W0411 14:10:19.744871    38 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0411 14:10:19.751854    38 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0411 14:10:19.751888    38 init.cc:214] The detail failure signal is:
W0411 14:10:19.751909    38 init.cc:217] *** Aborted at 1586614219 (unix time) try "date -d @1586614219" if you are using GNU date ***
W0411 14:10:19.872216    38 init.cc:217] PC: @                0x0 (unknown)
W0411 14:10:20.248174    38 init.cc:217] *** SIGSEGV (@0x7f20ad805b40) received by PID 38 (TID 0x7f2907a4cf40) from PID 18446744072325454656; stack trace: ***
W0411 14:10:20.251428    38 init.cc:217]     @     0x7f2907f51730 (unknown)
W0411 14:10:20.324234    38 init.cc:217]     @     0x7f28c75be9e0 paddle::operators::math::Im2ColFunctor<>::operator()()
W0411 14:10:20.356504    38 init.cc:217]     @     0x7f28c6ba5ee7 paddle::operators::GemmConvKernel<>::Compute()
W0411 14:10:20.360272    38 init.cc:217]     @     0x7f28c6ba6563 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators14GemmConvKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEEEclEPKcSG_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W0411 14:10:20.366858    38 init.cc:217]     @     0x7f28c794c1e6 paddle::framework::OperatorWithKernel::RunImpl()
W0411 14:10:20.377954    38 init.cc:217]     @     0x7f28c794cd41 paddle::framework::OperatorWithKernel::RunImpl()
W0411 14:10:20.380899    38 init.cc:217]     @     0x7f28c79481f4 paddle::framework::OperatorBase::Run()
W0411 14:10:20.385221    38 init.cc:217]     @     0x7f28c5fc5646 paddle::framework::Executor::RunPreparedContext()
W0411 14:10:20.387609    38 init.cc:217]     @     0x7f28c5fc8c5b paddle::framework::Executor::Run()
W0411 14:10:20.387774    38 init.cc:217]     @     0x7f28c5c66fce _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbRKSt6vectorISsSaISsEEE107_vIS8_SB_SD_ibbSI_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES10_
W0411 14:10:20.388813    38 init.cc:217]     @     0x7f28c5cba8c1 pybind11::cpp_function::dispatcher()
W0411 14:10:20.392134    38 init.cc:217]     @     0x7f29080b09e4 _PyMethodDef_RawFastCallKeywords
W0411 14:10:20.394524    38 init.cc:217]     @     0x7f29080b07b0 _PyCFunction_FastCallKeywords
W0411 14:10:20.396335    38 init.cc:217]     @     0x7f2908125a5d _PyEval_EvalFrameDefault
W0411 14:10:20.398545    38 init.cc:217]     @     0x7f2908120831 _PyEval_EvalCodeWithName
W0411 14:10:20.400462    38 init.cc:217]     @     0x7f29080b1982 _PyFunction_FastCallKeywords
W0411 14:10:20.402266    38 init.cc:217]     @     0x7f29081224a2 _PyEval_EvalFrameDefault
W0411 14:10:20.404166    38 init.cc:217]     @     0x7f2908120831 _PyEval_EvalCodeWithName
W0411 14:10:20.406286    38 init.cc:217]     @     0x7f29080b1982 _PyFunction_FastCallKeywords
W0411 14:10:20.408247    38 init.cc:217]     @     0x7f29081224a2 _PyEval_EvalFrameDefault
W0411 14:10:20.409994    38 init.cc:217]     @     0x7f2908120831 _PyEval_EvalCodeWithName
W0411 14:10:20.411919    38 init.cc:217]     @     0x7f29080b1982 _PyFunction_FastCallKeywords
W0411 14:10:20.413467    38 init.cc:217]     @     0x7f29081224a2 _PyEval_EvalFrameDefault
W0411 14:10:20.414943    38 init.cc:217]     @     0x7f2908120831 _PyEval_EvalCodeWithName
W0411 14:10:20.416543    38 init.cc:217]     @     0x7f29080b1982 _PyFunction_FastCallKeywords
W0411 14:10:20.418066    38 init.cc:217]     @     0x7f29081224a2 _PyEval_EvalFrameDefault
W0411 14:10:20.419690    38 init.cc:217]     @     0x7f29080b18da _PyFunction_FastCallKeywords
W0411 14:10:20.421298    38 init.cc:217]     @     0x7f2908121bb1 _PyEval_EvalFrameDefault
W0411 14:10:20.422842    38 init.cc:217]     @     0x7f2908120831 _PyEval_EvalCodeWithName
W0411 14:10:20.424589    38 init.cc:217]     @     0x7f29080b1982 _PyFunction_FastCallKeywords
W0411 14:10:20.426334    38 init.cc:217]     @     0x7f29081224a2 _PyEval_EvalFrameDefault
W0411 14:10:20.428069    38 init.cc:217]     @     0x7f29080b18da _PyFunction_FastCallKeywords
```

The cpu is 

```
processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xb000037
cpu MHz         : 2300.086
cache size      : 46080 KB
```

**Comment by ysh329** [comment]
看了下主要信息是这里:

```shell
W0411 14:10:19.744871    38 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0411 14:10:19.751854    38 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0411 14:10:19.751888    38 init.cc:214] The detail failure signal is:
W0411 14:10:19.751909    38 init.cc:217] *** Aborted at 1586614219 (unix time) try "date -d @1586614219" if you are using GNU date ***
W0411 14:10:19.872216    38 init.cc:217] PC: @                0x0 (unknown)
W0411 14:10:20.248174    38 init.cc:217] *** SIGSEGV (@0x7f20ad805b40) received by PID 38 (TID 0x7f2907a4cf40) from PID 18446744072325454656; stack trace: ***
W0411 14:10:20.251428    38 init.cc:217]     @     0x7f2907f51730 (unknown)
W0411 14:10:20.324234    38 init.cc:217]     @     0x7f28c75be9e0 paddle::operators::math::Im2ColFunctor<>::operator()()
W0411 14:10:20.356504    38 init.cc:217]     @     0x7f28c6ba5ee7 paddle::operators::GemmConvKernel<>::Compute()
W0411 14:10:20.360272    38 init.cc:217]     @     0x7f28c6ba6563 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators14GemmConvKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEEEclEPKcSG_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W0411 14:10:20.366858    38 init.cc:217]     @     0x7f28c794c1e6 paddle::framework::OperatorWithKernel::RunImpl()
W0411 14:10:20.377954    38 init.cc:217]     @     0x7f28c794cd41 paddle::framework::OperatorWithKernel::RunImpl()
```

似乎是Im2ColFunctor的问题，你的Paddle版本是啥，直接拉下的代码嘛，有做什么改动嘛

**Comment by loretoparisi** [comment]
> 看了下主要信息是这里:
> 
> ```shell
> W0411 14:10:19.744871    38 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0411 14:10:19.751854    38 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0411 14:10:19.751888    38 init.cc:214] The detail failure signal is:
> W0411 14:10:19.751909    38 init.cc:217] *** Aborted at 1586614219 (unix time) try "date -d @1586614219" if you are using GNU date ***
> W0411 14:10:19.872216    38 init.cc:217] PC: @                0x0 (unknown)
> W0411 14:10:20.248174    38 init.cc:217] *** SIGSEGV (@0x7f20ad805b40) received by PID 38 (TID 0x7f2907a4cf40) from PID 18446744072325454656; stack trace: ***
> W0411 14:10:20.251428    38 init.cc:217]     @     0x7f2907f51730 (unknown)
> W0411 14:10:20.324234    38 init.cc:217]     @     0x7f28c75be9e0 paddle::operators::math::Im2ColFunctor<>::operator()()
> W0411 14:10:20.356504    38 init.cc:217]     @     0x7f28c6ba5ee7 paddle::operators::GemmConvKernel<>::Compute()
> W0411 14:10:20.360272    38 init.cc:217]     @     0x7f28c6ba6563 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators14GemmConvKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEEEclEPKcSG_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
> W0411 14:10:20.366858    38 init.cc:217]     @     0x7f28c794c1e6 paddle::framework::OperatorWithKernel::RunImpl()
> W0411 14:10:20.377954    38 init.cc:217]     @     0x7f28c794cd41 paddle::framework::OperatorWithKernel::RunImpl()
> ```
> 
> 似乎是Im2ColFunctor的问题，你的Paddle版本是啥，直接拉下的代码嘛，有做什么改动嘛

Thank you for the highlight. @shoegazerstella Let us check the `Im2ColFunctor` function in the case we did any modification to it.

**Comment by ysh329** [comment]
> > 看了下主要信息是这里:
> > ```shell
> > W0411 14:10:19.744871    38 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> > W0411 14:10:19.751854    38 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> > W0411 14:10:19.751888    38 init.cc:214] The detail failure signal is:
> > W0411 14:10:19.751909    38 init.cc:217] *** Aborted at 1586614219 (unix time) try "date -d @1586614219" if you are using GNU date ***
> > W0411 14:10:19.872216    38 init.cc:217] PC: @                0x0 (unknown)
> > W0411 14:10:20.248174    38 init.cc:217] *** SIGSEGV (@0x7f20ad805b40) received by PID 38 (TID 0x7f2907a4cf40) from PID 18446744072325454656; stack trace: ***
> > W0411 14:10:20.251428    38 init.cc:217]     @     0x7f2907f51730 (unknown)
> > W0411 14:10:20.324234    38 init.cc:217]     @     0x7f28c75be9e0 paddle::operators::math::Im2ColFunctor<>::operator()()
> > W0411 14:10:20.356504    38 init.cc:217]     @     0x7f28c6ba5ee7 paddle::operators::GemmConvKernel<>::Compute()
> > W0411 14:10:20.360272    38 init.cc:217]     @     0x7f28c6ba6563 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators14GemmConvKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEEEclEPKcSG_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
> > W0411 14:10:20.366858    38 init.cc:217]     @     0x7f28c794c1e6 paddle::framework::OperatorWithKernel::RunImpl()
> > W0411 14:10:20.377954    38 init.cc:217]     @     0x7f28c794cd41 paddle::framework::OperatorWithKernel::RunImpl()
> > ```
> > 
> > 
> > 似乎是Im2ColFunctor的问题，你的Paddle版本是啥，直接拉下的代码嘛，有做什么改动嘛
> 
> Thank you for the highlight. @shoegazerstella Let us check the `Im2ColFunctor` function in the case we did any modification to it.

**Comment by ysh329** [comment]
> > 看了下主要信息是这里:
> > ```shell
> > W0411 14:10:19.744871    38 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> > W0411 14:10:19.751854    38 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> > W0411 14:10:19.751888    38 init.cc:214] The detail failure signal is:
> > W0411 14:10:19.751909    38 init.cc:217] *** Aborted at 1586614219 (unix time) try "date -d @1586614219" if you are using GNU date ***
> > W0411 14:10:19.872216    38 init.cc:217] PC: @                0x0 (unknown)
> > W0411 14:10:20.248174    38 init.cc:217] *** SIGSEGV (@0x7f20ad805b40) received by PID 38 (TID 0x7f2907a4cf40) from PID 18446744072325454656; stack trace: ***
> > W0411 14:10:20.251428    38 init.cc:217]     @     0x7f2907f51730 (unknown)
> > W0411 14:10:20.324234    38 init.cc:217]     @     0x7f28c75be9e0 paddle::operators::math::Im2ColFunctor<>::operator()()
> > W0411 14:10:20.356504    38 init.cc:217]     @     0x7f28c6ba5ee7 paddle::operators::GemmConvKernel<>::Compute()
> > W0411 14:10:20.360272    38 init.cc:217]     @     0x7f28c6ba6563 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators14GemmConvKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEEEEclEPKcSG_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
> > W0411 14:10:20.366858    38 init.cc:217]     @     0x7f28c794c1e6 paddle::framework::OperatorWithKernel::RunImpl()
> > W0411 14:10:20.377954    38 init.cc:217]     @     0x7f28c794cd41 paddle::framework::OperatorWithKernel::RunImpl()
> > ```
> > 
> > 
> > 似乎是Im2ColFunctor的问题，你的Paddle版本是啥，直接拉下的代码嘛，有做什么改动嘛
> 
> Thank you for the highlight. @shoegazerstella Let us check the `Im2ColFunctor` function in the case we did any modification to it.

Hope any check result~

**Comment by shoegazerstella** [comment]
Hi @ysh329,

I adapted the code to run on CPU and with python3.7
I only adapted the inference scripts.

I am installing paddle paddle with: 
```
python -m pip install paddlepaddle
```
Code and Dockerfile are available [here](https://github.com/shoegazerstella/DeepSpeech_CPU_py37)

**Comment by loretoparisi** [comment]
@ysh329 another thing we have found out is that it systematically crashes with `32GB` resident memory, while on machines with `64GB` it runs without any issue. Are you aware of memory consumption or minimum requirements of this magnitude? Maybe this is the underlying issue.

**Comment by lfchener** [comment]
> Hi @ysh329,
> 
> I adapted the code to run on CPU and with python3.7
> I only adapted the inference scripts.
> 
> I am installing paddle paddle with:
> 
> ```
> python -m pip install paddlepaddle
> ```
> 
> Code and Dockerfile are available [here](https://github.com/shoegazerstella/DeepSpeech_CPU_py37)

![image](https://user-images.githubusercontent.com/6771821/81651398-3c26b980-9465-11ea-9232-8b5a2f3fa893.png)
DeepSpeech only supported python 2.7, please use python 2.7 try again.

**Comment by loretoparisi** [comment]
@lfchener thanks, actually we are able to run DeepSpeech on Python3.7 over CPU - https://github.com/shoegazerstella/DeepSpeech_CPU_py37
What we have found is that on machine with memory constraints it crashes (Python processed is killed) after few inferences.

**Comment by zh794390558** [comment]
maybe kill by OOMKiller, which using much memory.
https://rakeshjain-devops.medium.com/linux-out-of-memory-killer-31e477a45759
https://www.kernel.org/doc/gorman/html/understand/understand016.html
