### ISSUE TITLE
加载预训练模型后，报RuntimeError: Shape not matching

### ISSUE THREAD

**Issue by gezimonkey** [PaddlePaddle/PaddleSpeech#450]
paddlepaddle版本：1.7
使用baidu_cn1.2k_model_fluid作为预训练模型
数据为16k的wav
mean_std.npz和vocab.txt是为自己生成的

参数：
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 16
dev_manifest: data/swd/16k/manifest.dev
init_from_pretrained_model: models/baidu_cn1.2k_model_fluid/
is_local: True
learning_rate: 0.0005
max_duration: 15.0
mean_std_path: data/swd/16k/mean_std.npz
min_duration: 0.9
num_conv_layers: 2
num_epoch: 50
num_iter_print: 100
num_rnn_layers: 3
num_samples: 51000
output_model_dir: ./checkpoints/swd
rnn_layer_size: 2048
save_epoch: 1
share_rnn_weights: False
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: False
train_manifest: data/swd/16k/manifest.train
use_gpu: True
use_gru: True
use_sortagrad: True
vocab_path: data/swd/16k/vocab.txt

最后报：
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((4096L, 1133L)), while the loaded parameter (namely [ layer_5_fc_weight ]) has a shape of  ((4096, 5304)).

**Comment by lfchener** [comment]
这是因为你自己生成的 vocab.txt 中的 dict_size 和预训练模型中使用的 dict_size 不一致导致的。

**Comment by gezimonkey** [comment]
> 这是因为你自己生成的 vocab.txt 中的 dict_size 和预训练模型中使用的 dict_size 不一致导致的。

请问那要如何修改呢?

**Comment by lfchener** [comment]
> > 这是因为你自己生成的 vocab.txt 中的 dict_size 和预训练模型中使用的 dict_size 不一致导致的。
> 
> 请问那要如何修改呢?

可以直接使用预训练模型中的 vocab.txt 文件或者重新生成一个单词数量和预训练模型一致的 vocab.txt 。
