### ISSUE TITLE
Japanese Language model is giving segmentation fault

### ISSUE THREAD

**Issue by artinegi1607** [PaddlePaddle/PaddleSpeech#459]
Running a Japanese Language model is giving segmentation fault. I am getting the below error:-

W0610 14:25:22.137501 24808 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0610 14:25:22.137524 24808 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0610 14:25:22.137532 24808 init.cc:221] The detail failure signal is:

W0610 14:25:22.137540 24808 init.cc:224] *** Aborted at 1591779322 (unix time) try "date -d @1591779322" if you are using GNU date ***
W0610 14:25:22.138669 24808 init.cc:224] PC: @                0x0 (unknown)
W0610 14:25:22.138871 24808 init.cc:224] *** SIGSEGV (@0x10) received by PID 24795 (TID 0x7f4890e63700) from PID 16; stack trace: ***
W0610 14:25:22.140156 24808 init.cc:224]     @     0x7f489931df20 (unknown)
W0610 14:25:22.140625 24808 init.cc:224]     @     0x7f4863a76576 PathTrie::get_path_trie()
W0610 14:25:22.140940 24808 init.cc:224]     @     0x7f48639b430d ctc_beam_search_decoder()
W0610 14:25:22.141218 24808 init.cc:224]     @     0x7f48639b5cee _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultISt6vectorISt4pairIdNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESaISG_EEEES3_EZNS1_11_Task_stateISt5_BindIFPFSI_RKS8_IS8_IdSaIdEESaISO_EERKS8_ISF_SaISF_EEmdmP6ScorerESQ_SU_mdmSY_EESaIiEFSI_vEE6_M_runEvEUlvE_SI_EEE9_M_invokeERKSt9_Any_data
W0610 14:25:22.141551 24808 init.cc:224]     @     0x7f48639b5629 std::__future_base::_State_baseV2::_M_do_set()
W0610 14:25:22.142618 24808 init.cc:224]     @     0x7f48990cf827 __pthread_once_slow
W0610 14:25:22.142915 24808 init.cc:224]     @     0x7f48639b648c _ZNSt17_Function_handlerIFvvEZN10ThreadPool7enqueueIRFSt6vectorISt4pairIdNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESaISB_EERKS3_IS3_IdSaIdEESaISF_EERKS3_ISA_SaISA_EEmdmP6ScorerEJSJ_SN_RmRdSS_RSP_EEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSX_DpOSY_EUlvE_E9_M_invokeERKSt9_Any_data
W0610 14:25:22.143095 24808 init.cc:224]     @     0x7f48639b60e0 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN10ThreadPoolC4EmEUlvE_EEEEE6_M_runEv
W0610 14:25:22.144214 24808 init.cc:224]     @     0x7f48804ce6ef (unknown)
W0610 14:25:22.145277 24808 init.cc:224]     @     0x7f48990c76db start_thread
W0610 14:25:22.146253 24808 init.cc:224]     @     0x7f489940088f clone
W0610 14:25:22.147152 24808 init.cc:224]     @                0x0 (unknown)
Segmentation fault (core dumped)

Am I missing anything. Any help would be appreciated.

**Comment by lfchener** [comment]
I'm not sure what's the problem with error message above，would you like to show me some details such as the configs you used?
