### ISSUE TITLE
tiny sh run_train.sh inside docker: TypeError: __init__() got an unexpected keyword argument 'grad_clip'

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSpeech#462]
Hello,
I updated paddle, but run_train.sh results in error:
wget https://nero-mirror.stanford.edu/pypi/web/packages/5f/b0/769cd78f5fdc9de41d760512750e70ace87caea54502882d0818e4b3ce1d/paddlepaddle_gpu-1.6.2.post107-cp27-cp27mu-manyli$

pip install paddlepaddle_gpu-1.6.2.post107-cp27-cp27mu-manylinux1_x86_64.whl

``
λ 77050b25daa6 /DeepSpeech/examples/tiny {develop} sh run_train.sh
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 4
dev_manifest: data/tiny/manifest.tiny
init_from_pretrained_model: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_epoch: 20
num_iter_print: 1
num_rnn_layers: 3
num_samples: 64
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
save_epoch: 1
share_rnn_weights: 1
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
use_gpu: 1
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 138, in main
    train()
  File "train.py", line 133, in train
    test_off=args.test_off)
  File "/DeepSpeech/model_utils/model.py", line 290, in train
    clip_norm=gradient_clipping))
TypeError: __init__() got an unexpected keyword argument 'grad_clip'
Failed in training!
``

Thanks

**Comment by lfchener** [comment]
Please try paddlepaddle 1.8.0 or later.
https://github.com/PaddlePaddle/DeepSpeech#installation

**Comment by ghost** [comment]
I am using the docker. the docker is not good? I should install 1.8 inside the docker?

**Comment by lfchener** [comment]
> I am using the docker. the docker is not good? I should install 1.8 inside the docker?

Yes, you can update paddle version in docker.

**Comment by ghost** [comment]
> > I am using the docker. the docker is not good? I should install 1.8 inside the docker?
> 
> Yes, you can update paddle version in docker.

Which exact version of 1.8 from here? https://nero-mirror.stanford.edu/pypi/web/simple/paddlepaddle-gpu/

**Comment by plseal** [comment]
@paklau99988 
i updated paddlepaddle-gpu with this command. it works for me .
```
python -m pip install paddlepaddle-gpu==1.8.2.post107
```
