### ISSUE TITLE
Infer for a single WAV file not using  data_generator.batch_reader_creator

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleSpeech#463]
Is there an example for loading a single WAV file and inferring on that? 

Thanks

**Comment by lfchener** [comment]
This might be useful to you.
https://github.com/PaddlePaddle/DeepSpeech#trying-live-demo-with-your-own-voice

**Comment by YanqiangWang** [comment]
You can do this by modifing infer.py file:
give an input argument 'infer_manifest' (write your wav path in json format, just like this one over [here](https://github.com/PaddlePaddle/DeepSpeech#data-preparation))
and the other argument should be also given the proper value.
and return 'result_transcripts' of 'infer()' function.
(this 'result_transcripts' is the speech recognition result list.
