### ISSUE TITLE
安装报错了。。

### ISSUE THREAD

**Issue by lgd123** [PaddlePaddle/PaddleSpeech#466]
In file included from scorer.h:14,
                 from decoders_wrap.cxx:3171:
path_trie.h:10:10: fatal error: fst/fstlib.h: No such file or directory
   10 | #include "fst/fstlib.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-8kFkPd/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Ikenlm -Iopenfst-1.6.3/src/include -IThreadPool -I/usr/include/python2.7 -c decoder_utils.cpp -o build/temp.linux-x86_64-2.7/decoder_utils.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
In file included from decoder_utils.cpp:1:
decoder_utils.h:5:10: fatal error: fst/log.h: No such file or directory
    5 | #include "fst/log.h"
      |          ^~~~~~~~~~~
compilation terminated.
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-8kFkPd/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Ikenlm -Iopenfst-1.6.3/src/include -IThreadPool -I/usr/include/python2.7 -c path_trie.cpp -o build/temp.linux-x86_64-2.7/path_trie.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
In file included from scorer.h:14,
                 from scorer.cpp:1:
path_trie.h:10:10: fatal error: fst/fstlib.h: No such file or directory
   10 | #include "fst/fstlib.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-8kFkPd/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Ikenlm -Iopenfst-1.6.3/src/include -IThreadPool -I/usr/include/python2.7 -c ctc_beam_search_decoder.cpp -o build/temp.linux-x86_64-2.7/ctc_beam_search_decoder.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
In file included from path_trie.cpp:1:
path_trie.h:10:10: fatal error: fst/fstlib.h: No such file or directory
   10 | #include "fst/fstlib.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-8kFkPd/python2.7-2.7.17=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -Ikenlm -Iopenfst-1.6.3/src/include -IThreadPool -I/usr/include/python2.7 -c ctc_greedy_decoder.cpp -o build/temp.linux-x86_64-2.7/ctc_greedy_decoder.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
In file included from scorer.h:14,
                 from ctc_beam_search_decoder.h:8,
                 from ctc_beam_search_decoder.cpp:1:
path_trie.h:10:10: fatal error: fst/fstlib.h: No such file or directory
   10 | #include "fst/fstlib.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
In file included from ctc_greedy_decoder.cpp:2:
decoder_utils.h:5:10: fatal error: fst/log.h: No such file or directory
    5 | #include "fst/log.h"
      |          ^~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by lgd123** [comment]
新手不懂

**Comment by ExpressGit** [comment]
怎么解决的

**Comment by yhz5256** [comment]
怎么解决的，我也遇到这个了
