### ISSUE TITLE
Error about “RuntimeError: MD5 checksum failed”

### ISSUE THREAD

**Issue by ilove-Moretz** [PaddlePaddle/PaddleSpeech#468]
When I run examples/aishell/run_data.sh，some error happen,the error log is as follow

> MD5 Chesksum ./dataset/aishell/data_aishell.tgz ...
Traceback (most recent call last):
  File "data/aishell/aishell.py", line 110, in <module>
    main()
  File "data/aishell/aishell.py", line 106, in main
    manifest_path=args.manifest_prefix)
  File "data/aishell/aishell.py", line 85, in prepare_dataset
    filepath = download(url, md5sum, target_dir)
  File "/DeepSpeech/data_utils/utility.py", line 73, in download
    raise RuntimeError("MD5 checksum failed.")
RuntimeError: MD5 checksum failed.
Prepare Aishell failed. Terminated.

What should I do to solve this problem? Thanks

**Comment by willthefrog** [comment]
looks like an incomplete download to me, please take a look @kuke

**Comment by lfchener** [comment]
This is because your file is not completely downloaded, please check your network and download again. @ilove-Moretz

**Comment by ilove-Moretz** [comment]
I solved this problem ，I dowload the file completely，and the MD5 checksum success.
