### ISSUE TITLE
Baidu Internal English Dataset

### ISSUE THREAD

**Issue by ssteven502tw** [PaddlePaddle/PaddleSpeech#471]
Where can I find Baidu Internal English Dataset, and all these data sets are clean?

**Comment by DannyIsFunny** [comment]
Hi, we have not publish the internal English Dataset to open source community yet, we have provided open source models only.

**Comment by ssteven502tw** [comment]
@DannyIsFunny datasets are clean .wav?

**Comment by ssteven502tw** [comment]
> 嗨，我們尚未將內部English Dataset發佈到開源社區，我們僅提供了開源模型。



> Hi, we have not publish the internal English Dataset to open source community yet, we have provided open source models only.

@DannyIsFunny datasets are clean .wav?
