### ISSUE TITLE
ModuleNotFoundError: No module named 'swig_decoders' 

### ISSUE THREAD

**Issue by ExpressGit** [PaddlePaddle/PaddleSpeech#472]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'swig_decoders'

pip3 list
swig-decoders (1.1)

pip3 下可以看见，但是import失败

**Comment by lfchener** [comment]
![image](https://user-images.githubusercontent.com/6771821/86547649-32549a80-bf6c-11ea-87c1-4d1be1cec14a.png)
目前 DeepSpeech 只支持 python2.7 ，请切换 python2.7 环境重新安装。

**Comment by yeyupiaoling** [comment]
@ExpressGit 用Docker吧，省事
