### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by ML6634** [PaddlePaddle/PaddleSpeech#473]
When I downloaded the Docker image:

<pre>$ sudo nvidia-docker pull hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu
</pre>

I got: 

<pre>unexpected EOF
</pre>

May I ask how to take care of it? Thank you!

**Comment by lfchener** [comment]
This may be helpful to you:
https://stackoverflow.com/questions/53677592/docker-pull-unexpected-eof

**Comment by ML6634** [comment]
Thanks @lfchener for the link. So far, I could not find a way to fix the bug. Any further comments? Thank you!

**Comment by ML6634** [comment]
Does anybody have experience with it? Or, for you the above command went through successfully? Thank you!

**Comment by zh794390558** [comment]
make sure nvidia-docker is installed successfully , more info `https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html`

**Comment by zh794390558** [comment]
see [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) to make sure you have install the nvidia-docker  successfully.
