### ISSUE TITLE
Docker pull error

### ISSUE THREAD

**Issue by ngk512** [PaddlePaddle/PaddleSpeech#477]
Hi,

Please help, while downloading the docker image on client machine it gives an error.

**Command:** nvidia-docker pull hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu

**Error**: Error response from daemon: error unmarshalling content: invalid character '<' looking for beginning of value

Please help to fix the issue.

**Comment by zh794390558** [comment]
try `nvidia-docker pull hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu` again, then please check this error for nvidia-docker.
