### ISSUE TITLE
运行demo_server.py时，提示gcc 和 kenlm版本问题，请问应该安装什么版本哪？

### ISSUE THREAD

**Issue by Ficery1** [PaddlePaddle/PaddleSpeech#479]
2020-07-24 11:54:44,195-INFO: begin to initialize the external scorer for decoding
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  kenlm/lm/vocab.cc:43 in void lm::ngram::{anonymous}::ReadWords(int, lm::EnumerateVocab*, lm::WordIndex, uint64_t) threw FormatLoadException because `memcmp(check_unk, "<unk>", 6)'.
Vocabulary words are in the wrong place.  This could be because the binary file was built with stale gcc and old kenlm.  Stale gcc, including the gcc distributed with RedHat and OS X, has a bug that ignores pragma pack for template-dependent types.  New kenlm works around this, so you'll save memory but have to rebuild any binary files using the probing data structure.
W0724 11:54:44.449854 10056 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0724 11:54:44.449880 10056 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0724 11:54:44.449885 10056 init.cc:221] The detail failure signal is:

W0724 11:54:44.449892 10056 init.cc:224] *** Aborted at 1595562884 (unix time) try "date -d @1595562884" if you are using GNU date ***
W0724 11:54:44.451668 10056 init.cc:224] PC: @                0x0 (unknown)
W0724 11:54:44.451771 10056 init.cc:224] *** SIGABRT (@0x32100002748) received by PID 10056 (TID 0x7f0dcab5f740) from PID 10056; stack trace: ***
W0724 11:54:44.453256 10056 init.cc:224]     @     0x7f0dca9225f0 (unknown)
W0724 11:54:44.454828 10056 init.cc:224]     @     0x7f0dc9e72337 __GI_raise
W0724 11:54:44.456319 10056 init.cc:224]     @     0x7f0dc9e73a28 __GI_abort
W0724 11:54:44.457363 10056 init.cc:224]     @     0x7f0d99d2084a __gnu_cxx::__verbose_terminate_handler()
W0724 11:54:44.458148 10056 init.cc:224]     @     0x7f0d99d1ef47 __cxxabiv1::__terminate()
W0724 11:54:44.459126 10056 init.cc:224]     @     0x7f0d99d1ef7d std::terminate()
W0724 11:54:44.460006 10056 init.cc:224]     @     0x7f0d99d1f15a __cxa_throw
W0724 11:54:44.460772 10056 init.cc:224]     @     0x7f0da34ef9f6 lm::ngram::(anonymous namespace)::ReadWords()
W0724 11:54:44.461920 10056 init.cc:224]     @     0x7f0da34efe91 lm::ngram::ProbingVocabulary::LoadedBinary()
W0724 11:54:44.462857 10056 init.cc:224]     @     0x7f0da34c7199 lm::ngram::detail::GenericModel<>::GenericModel()
W0724 11:54:44.463752 10056 init.cc:224]     @     0x7f0da34beb0b lm::ngram::LoadVirtual()
W0724 11:54:44.464592 10056 init.cc:224]     @     0x7f0da35d4ecc Scorer::load_lm()
W0724 11:54:44.465605 10056 init.cc:224]     @     0x7f0da35db0f1 Scorer::setup()
W0724 11:54:44.466466 10056 init.cc:224]     @     0x7f0da35db245 Scorer::Scorer()
W0724 11:54:44.467242 10056 init.cc:224]     @     0x7f0da35905d0 _wrap_new_Scorer
W0724 11:54:44.468819 10056 init.cc:224]     @     0x7f0dcac542f4 PyEval_EvalFrameEx
W0724 11:54:44.470405 10056 init.cc:224]     @     0x7f0dcac55b19 PyEval_EvalCodeEx
W0724 11:54:44.471848 10056 init.cc:224]     @     0x7f0dcabde6ea function_call
W0724 11:54:44.473486 10056 init.cc:224]     @     0x7f0dcabb9b83 PyObject_Call
W0724 11:54:44.475044 10056 init.cc:224]     @     0x7f0dcabc8a5d instancemethod_call
W0724 11:54:44.476794 10056 init.cc:224]     @     0x7f0dcabb9b83 PyObject_Call
W0724 11:54:44.478374 10056 init.cc:224]     @     0x7f0dcac50199 PyEval_EvalFrameEx
W0724 11:54:44.480032 10056 init.cc:224]     @     0x7f0dcac55b19 PyEval_EvalCodeEx
W0724 11:54:44.481617 10056 init.cc:224]     @     0x7f0dcabde6ea function_call
W0724 11:54:44.483245 10056 init.cc:224]     @     0x7f0dcabb9b83 PyObject_Call
W0724 11:54:44.484678 10056 init.cc:224]     @     0x7f0dcabc8a5d instancemethod_call
W0724 11:54:44.486244 10056 init.cc:224]     @     0x7f0dcabb9b83 PyObject_Call
W0724 11:54:44.487712 10056 init.cc:224]     @     0x7f0dcac12b04 slot_tp_init
W0724 11:54:44.489179 10056 init.cc:224]     @     0x7f0dcac0f3bb type_call
W0724 11:54:44.490762 10056 init.cc:224]     @     0x7f0dcabb9b83 PyObject_Call
W0724 11:54:44.492444 10056 init.cc:224]     @     0x7f0dcac50199 PyEval_EvalFrameEx
W0724 11:54:44.494045 10056 init.cc:224]     @     0x7f0dcac55b19 PyEval_EvalCodeEx
Aborted

**Comment by yeyupiaoling** [comment]
为啥用docker呢
