### ISSUE TITLE
aishell下执行sh run_data.sh生成的manifest文件都为空，且mean_std.npz文件未生成，怎么解决？

### ISSUE THREAD

**Issue by YuHuasong123** [PaddlePaddle/PaddleSpeech#480]
aishell$ sh run_data.sh 
Skip downloading and unpacking. Data already exists in ./dataset/aishell.
Creating manifest data/aishell/manifest ...
-----------  Configuration Arguments -----------
count_threshold: 0
manifest_paths: ['data/aishell/manifest.train', 'data/aishell/manifest.dev']
vocab_path: data/aishell/vocab.txt
------------------------------------------------
-----------  Configuration Arguments -----------
manifest_path: data/aishell/manifest.train
num_samples: 2000
output_path: data/aishell/mean_std.npz
specgram_type: linear
------------------------------------------------
0 2000
Traceback (most recent call last):
  File "tools/compute_mean_std.py", line 51, in <module>
    main()
  File "tools/compute_mean_std.py", line 46, in main
    num_samples=args.num_samples)
  File "/home/aistudio/DeepSpeech/tools/../data_utils/normalizer.py", line 46, in __init__
    self._compute_mean_std(manifest_path, featurize_func, num_samples)
  File "/home/aistudio/DeepSpeech/tools/../data_utils/normalizer.py", line 80, in _compute_mean_std
    sampled_manifest = self._rng.sample(manifest, num_samples)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/random.py", line 325, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population
Compute mean and stddev failed. Terminated.

**Comment by ayayaya420** [comment]
科学上网

**Comment by ccbptm** [comment]
你可能需要去~/.cache的那个data里面把wav解压出来，再回原路径执行sh run_data.sh

**Comment by zh794390558** [comment]
清理下环境，重新执行下，确保数据都下载ok了。
