### ISSUE TITLE
在训练中如何设置输入音频的帧率，通道数等参数

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSpeech#483]
我们有几种不同帧率、通道数的音频数据集，按理来说应该是要统一帧率，如16k，通道数为1，我找了一番，没找到在哪里设置的。

**Comment by lfchener** [comment]
参考这里，代码里是直接根据读取的音频文件获得帧率的。
https://github.com/PaddlePaddle/DeepSpeech/blob/b3c728d46ff4eee68c45f20b0abb76e968008bcb/data_utils/audio.py#L72
可以在对应的地方进行修改。

**Comment by yeyupiaoling** [comment]
@lfchener 直接用音频原来的帧率吗？ 不是统一为16k这样吗？
