### ISSUE TITLE
请问Paddle有可应用于音频分类的模型或框架吗？

### ISSUE THREAD

**Issue by mtz1992** [PaddlePaddle/PaddleSpeech#489]

**Comment by yeyupiaoling** [comment]
@mtz1992 你可以参考这个：https://github.com/yeyupiaoling/AudioClassification-PaddlePaddle

**Comment by mtz1992** [comment]
好的，我已经看到了，请问这位大神也是paddle的开发人员么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夜雨飘零"<notifications@github.com&gt;; 
发送时间: 2020年9月17日(星期四) 下午3:43
收件人: "PaddlePaddle/DeepSpeech"<DeepSpeech@noreply.github.com&gt;; 
抄送: "漫步云端"<a75468916@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/DeepSpeech] 请问Paddle有可应用于音频分类的模型或框架吗？ (#489)





 
@mtz1992 你可以参考这个：https://github.com/yeyupiaoling/AudioClassification-PaddlePaddle

**Comment by yeyupiaoling** [comment]
不是呢

**Comment by zh794390558** [comment]
有计划做音频分类和声纹的repo。
