### ISSUE TITLE
How can we emit word confidence while decoding?

### ISSUE THREAD

**Issue by aayushkubb** [PaddlePaddle/PaddleSpeech#490]
I am trying to estimate word confidence while doing CTC decoding, one of the simplest ways I could think of is just multiplying the associated character probabilities at that particular time step to get an approximation.

However, a lot of people have been using the concept of posterior probabilities and lattice to get the word confidence.

Is there a simplified way to have word confidence estimation during decoding?

**Comment by zh794390558** [comment]
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deepspeech/decoders/swig/ctc_beam_search_decoder.cpp#L138 this is for lm rescore.
