### ISSUE TITLE
Error dimension mismatch when use specgram_type mfcc

### ISSUE THREAD

**Issue by hieuhv94** [PaddlePaddle/PaddleSpeech#492]
I use specgram type but this error happended:
----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The fed Variable audio_data should have dimensions = 3, shape = [-1, 161, -1], but received fed shape [20, 39, 200]
  [Hint: Expected DimensionIsCompatibleWith(shapes[i], in_dims) == true, but received DimensionIsCompatibleWith(shapes[i], in_dims):0 != true:1.] at (/paddle/paddle/fluid/operators/reader/read_op.cc:137)
  [operator < read > error]
Failed in training!

I don't understand why shape of audio_data is:
`if not is_infer:
            input_fields = {
                'names': ['audio_data', 'text_data', 'seq_len_data', 'masks'],
                'shapes':
                [[None, 161, None], [None, 1], [None, 1], [None, 32, 81, None]],
                'dtypes': ['float32', 'int32', 'int64', 'float32'],
                'lod_levels': [0, 1, 0, 0]
            }`
How do i resolve this issue?
Thanks

**Comment by zh794390558** [comment]
161 hard code， you should change the by yourself in 1.x
