### ISSUE TITLE
Downloaded the Docker image successfully? 

### ISSUE THREAD

**Issue by ML6634** [PaddlePaddle/PaddleSpeech#495]
When I downloaded the Docker image:

<pre>$ sudo nvidia-docker pull hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu</pre>

it sounds that it might go through:

<pre><font color="#4E9A06"><b>ml@ml-Alienware-Aurora-Ryzen-Edition</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo nvidia-docker pull hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu
[sudo] password for ml: 
latest-gpu: Pulling from paddlepaddle/deep_speech_fluid
3c21ebac6bec: Pulling fs layer 
ad9e3a7075fe: Pulling fs layer 
4b1a464a2c0a: Pulling fs layer 
3a1d7eee827d: Pulling fs layer 
29d1b31ad169: Pulling fs layer 
9136047911d4: Pulling fs layer 
f1a4b0ab792e: Pulling fs layer 
e709e5219f58: Pulling fs layer 
3a1d7eee827d: Waiting 
3d8e005a1c36: Pulling fs layer 
4fc075736176: Pulling fs layer 
9136047911d4: Waiting 
7cc82bc7830b: Pulling fs layer 
21bbd44330d8: Pulling fs layer 
e7e99a532df2: Pulling fs layer 
e709e5219f58: Waiting 
09b927152200: Waiting 
21bbd44330d8: Waiting 
3d8e005a1c36: Waiting 
e7e99a532df2: Waiting 
f9daa39c1249: Pull complete 
023c7b718089: Pull complete 
3d35ffc25700: Pull complete 
6be655d28897: Pull complete 
9b30819d4d5e: Pull complete 
d6c4b765fb1b: Pull complete 
e3d45086c12c: Pull complete 
5acb8f7358ac: Pull complete 
d55e9aaab773: Pull complete 
77384f595cd2: Pull complete 
322b275d50cf: Pull complete 
4f37ca086c1d: Pull complete 
04ceb7100848: Pull complete 
2ed81ea9c480: Pull complete 
f3a6127b27f2: Pull complete 
6a3b4f6d134a: Pull complete 
74591c1e01a3: Pull complete 
ae43c04823b6: Pull complete 
7683bf2504b7: Pull complete 
1a0cfa5c112a: Pull complete 
9f4205c52101: Pull complete 
a545aeede71b: Pull complete 
6a7b1799822a: Pull complete 
Digest: sha256:aed16d3b3fabf64ca68e182c26dd3e0458ce09228696682963f1f39d63606b46
Status: Downloaded newer image for hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu
hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu
<font color="#4E9A06"><b>ml@ml-Alienware-Aurora-Ryzen-Edition</b></font>:<font color="#3465A4"><b>~</b></font>$ git clone https://github.com/PaddlePaddle/DeepSpeech.git
Cloning into &apos;DeepSpeech&apos;...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2658 (delta 2), reused 5 (delta 2), pack-reused 2645
Receiving objects: 100% (2658/2658), 1.16 MiB | 1001.00 KiB/s, done.
Resolving deltas: 100% (1717/1717), done.
<font color="#4E9A06"><b>ml@ml-Alienware-Aurora-Ryzen-Edition</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo nvidia-docker run -it -v $(pwd)/DeepSpeech:/DeepSpeech hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu /bin/bash
[sudo] password for ml: 
<font color="#C4A000"><b>λ </b></font><font color="#D3D7CF"><b>bc95a51368df </b></font><font color="#4E9A06"><b>/</b></font> 
</pre>

However, for some lines, it still shows "Waiting".  May I ask whether I have downloaded the Docker image successfully? If not, how may I take care of this? Thanks.

**Comment by ML6634** [comment]
In addition, I am supposed to go to the directory, examples/tiny, to prepare data etc. However, I do not have the folder. examples. How to fix it? Thanks.

**Comment by slesinger** [comment]
Pull is very slow and always fails.

**Comment by zh794390558** [comment]
try one more time  to pull image, then check docker pull status.
