### ISSUE TITLE
Speaker Diarization and Modify the Neural Network

### ISSUE THREAD

**Issue by alexivaner** [PaddlePaddle/PaddleSpeech#496]
I wonder if it is possible to modify this DeepSpeech Neural network to do speaker diarization, if it is possible could you give me some clue about this? I also want to train this neural network with Traditional Chinese, could you give me some clue about this? Thank you very much for your help.

**Comment by zh794390558** [comment]
speaker diarization is a similar task with speaker verification, Deep Speech is only using for ASR task, but you can using this framework to do any task with more coding.
