### ISSUE TITLE
nvidia-docker run error

### ISSUE THREAD

**Issue by zailushang2006** [PaddlePaddle/PaddleSpeech#501]
nvidia-docker run -it -v $(pwd)/DeepSpeech:/DeepSpeech hub.baidubce.com/paddlepaddle/deep_speech_fluid:latest-gpu /bin/bash

docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.

**Comment by zh794390558** [comment]
确认nvidia-docker安装成功。
