### ISSUE TITLE
No such file or directory: 'data/librispeech/mean_std.npz'

### ISSUE THREAD

**Issue by siyangbing** [PaddlePaddle/PaddleSpeech#503]
我想利用预训练模型进行单条的语音转文字该怎么操作，我在文档中没有找到相关建议，可以帮帮我吗

**Comment by siyangbing** [comment]
help me

**Comment by zh794390558** [comment]
1. 准备数据
`pushd examples/librispeech; bash run_data.sh`
2. 自己创建manifest 文件，指包含一条语音。
3. `bash run_infer.sh` ，记得修改参数。
