### ISSUE TITLE
为什么我使用百度内部语料预训练的模型识别效果差呢 

### ISSUE THREAD

**Issue by siyangbing** [PaddlePaddle/PaddleSpeech#504]
理论上来说大语料预训练模型识别效果会好(baidu-cn1.2k),识别效果差
我的命令
python -u infer.py \
--num_samples=10 \
--beam_size=300 \
--num_proc_bsearch=8 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=2048 \
--alpha=2.6 \
--beta=5.0 \
--cutoff_prob=0.99 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=False \
--share_rnn_weights=False \
--infer_manifest='data/aishell/test.test' \
--mean_std_path='models/bd18k/mean_std.npz' \
--vocab_path='models/bd18k/vocab.txt' \
--model_path='models/bd18k' \
--lang_model_path='/home/db/下载/zhidao_giga.klm' \
--specgram_type='linear'

其中infer_manifest是自己的数据，模型是下载的预先训练的官方模型

**Comment by ayayaya420** [comment]
你好，自己的普通话数据集该如何制作，刚接触不是太了解。

**Comment by ccbptm** [comment]
我也不知道为什么，我直接用的data/aishell/manifest.test，然后cer是1.000.但是用depoly文件夹中的在线搭建的时候。baidu-cn1.2k效果被aishell model要好，但实际识别效果也不佳

**Comment by fnhweiqs** [comment]
> 我也不知道为什么，我直接用的data/aishell/manifest.test，然后cer是1.000.但是用depoly文件夹中的在线搭建的时候。baidu-cn1.2k效果被aishell model要好，但实际识别效果也不佳

你的测试音频采样率应该是 16k 吧， 需要把测试的音频的 采样率转为 8k 才行 。

**Comment by zh794390558** [comment]
注意模型用的数据和测试数据的格式是否一致。

**Comment by ccbptm** [comment]
> > 我也不知道为什么，我直接用的data/aishell/manifest.test，然后cer是1.000.但是用depoly文件夹中的在线搭建的时候。baidu-cn1.2k效果被aishell model要好，但实际识别效果也不佳
> 
> 你的测试音频采样率应该是 16k 吧， 需要把测试的音频的 采样率转为 8k 才行 。

对，把16k转成8k之后就cer就不是1了，但还是没有aishell模型效果好，但实时语音的时候还是这个好
