### ISSUE TITLE
关于cuda版本和cudnn版本问题

### ISSUE THREAD

**Issue by Rootian** [PaddlePaddle/PaddleSpeech#507]
我是用docker容器运行的，机器的cuda版本是10.0，cudnn版本是7.6.0。而docker容器里的cuda版本是9.0，cudnn没有安装。在容器里运行train.py使用gpu的时候会报错
`Cudnn error, CUDNN_STATUS_EXECUTION_FAILED`
并且运行的时候，输出信息说我用的是cudnn 7.5
请问容器里运行的时候使用的是容器外的cuda和cudnn还是容器内部的呐，我还需要升级容器内部的版本吗

**Comment by 1003657663** [comment]
请问，这个解决了吗？怎么解决的呀

**Comment by Rootian** [comment]
> 请问，这个解决了吗？怎么解决的呀

在nvidia官网下载对应版本的cudnn，在容器里安装一下就好~

**Comment by zh794390558** [comment]
使用的应该是容器内部的，可以重新装下paddle，like `python -m pip install paddlepaddle-gpu==1.8.0.post107`.
