### ISSUE TITLE
训练占用显存越来越高

### ISSUE THREAD

**Issue by Rootian** [PaddlePaddle/PaddleSpeech#512]
你好，我在使用自己的数据进行训练的时候，设置的batch_size是16，最开始的几千个batch，基本可以几十秒完成100个batch的训练，而随着训练的进行，每100个batch的训练时间越来越长，现在进行到batch 20000左右的时候，100个batch需要7分钟的时间才能完成训练，而且train loss也是在缓慢增加的，请问这是正常现象吗？

另外，最开始启动的时候占用的显存是4g，随着训练进行，每100个batch的训练速度越来越慢，占用的显存也越来越高，进行到batch 20000左右，显存的占用已经达到了7g，这种情况应该如何处理呢？

**Comment by zh794390558** [comment]
第一个epoch的训练用了SortaGrad了，所以句子长度在增加，loss增加是正常的。建议看下论文3.2
