### ISSUE TITLE
建议作者好好写一个demo

### ISSUE THREAD

**Issue by jiangliuer-beep** [PaddlePaddle/PaddleSpeech#523]
作为百度开源的框架，这是我使用体验感最糟糕的一个。
1、demo写的模糊，照着做根本运行不起来，还需要大量的调整。
2、即便有docker容器了，环境还是各种冲突。
能不能提供一个可以直接运行的demo，哪怕体积很大、效率不高，能不能先让我运行起来，识别出第一个语音文本再说。这个年代，容器占用10G、20G、30G的空间，真的很重要吗？那些各种文件，运行的时候还不是要一个个去下载！paddle提供的各种模型，又搞了各自的容器环境，我就没见的拉取一个环境就能直接运行的，各种路径冲突，文件找不到，下载不了。paddle里面的项目结构是什么？各个文件、脚本的作用是什么？要是作者能够整理下，就真的完美了！

**Comment by monkeycc** [comment]
楼主说的不错，太多坑了，examples没有能跑起来的

**Comment by zh794390558** [comment]
嗯嗯，已经收到意见，目前正在迁移2.x中，1.8原有的流程暂时没有调整。后续会将docker整理重新发布的，文档也会修改的哈。如果运行中遇到问题可以提issue哈。

**Comment by MatrixFour** [comment]
> e

感谢您的回复，我也是paddle的使用者，真心希望咱们百度的这个项目，这份事业能继续下去，并且越做越好！
我想从以下角度提出我的建议，期待能帮助到你们！
### 1、制定一份有针对性的文档。
### 2、针对不同的场景，能够提供不同的运行环境。

       说明：首先，我相信paddle的开发者肯定都是业界翘楚，对深度学习、工程架构都非常了解。但是，作为一个普通的用户，我还是难以达到你们的水平。所以我期望您能**提供一份有针对性的文档**，对于普通用户、科研学者、开发工程师，都能快速定位到合适自身需求的文档中去。一上来就贴论文地址，准备好8块RTX2080TI，下载70G的训练数据，这些要求对普通用户，初级工程师而言，即做不到，也没必要去做到。我就只想看下paddle的使用方式，或者进行轻量级的语音识别，那我就只会希望API接口能尽可能清晰，至于论文，抱歉，我真没心思去研究。当然，对于科研工作者，那有不一样了。
       其次，作为一个初学者、初级工程师，我更希望你们**提供一套能直接可以运行的案列（或者轻量级的cpu方案的训练模型）**，我的设备只有CPU，所以我不可能一上来就进行复杂的训练。随着我对paddle了解的逐渐深入，我可能希望能继续深入研究这个项目的架构，论文原理。这个时候，我期望我见到的项目会是架构清晰的，由浅入深的展示在我面前，并附赠相关的介绍、训练、测试等代码。

       为此，我也愿意参与paddle开源贡献中，作为初级使用者，我可以在你们提供的官方文档上，撰写更加详细的使用说明、算法概论等，和其他使用者交流心得，助力paddle更好的发展，但是前提是您的官方文档和资料得让我读完后，使用后，有深入研究的动力，而不是我折腾了半天，毛都没弄出来。

我见过只站在开发者自身角度写文档的项目，最终的结果就是懂这个项目的人不需要看文档，不懂的人反正也看不懂，最终项目不了了之了。

**Comment by jiangliuer-beep** [comment]
> 嗯嗯，已经收到意见，目前正在迁移2.x中，1.8原有的流程暂时没有调整。后续会将docker整理重新发布的，文档也会修改的哈。如果运行中遇到问题可以提issue哈。

感谢您的回复，我也是paddle的使用者，真心希望咱们百度的这个项目，这份事业能继续下去，并且越做越好！
我想从以下角度提出我的建议，期待能帮助到你们！
### 1、制定一份有针对性的文档。
### 2、针对不同的场景，能够提供不同的运行环境。

说明：首先，我相信paddle的开发者肯定都是业界翘楚，对深度学习、工程架构都非常了解。但是，作为一个普通的用户，我还是难以达到你们的水平。所以我期望您能**提供一份有针对性的文档**，对于普通用户、科研学者、开发工程师，都能快速定位到合适自身需求的文档中去。一上来就贴论文地址，准备好8块RTX2080TI，下载70G的训练数据，这些要求对普通用户，初级工程师而言，即做不到，也没必要去做到。我就只想看下paddle的使用方式，或者进行轻量级的语音识别，那我就只会希望API接口能尽可能清晰，至于论文，抱歉，我真没心思去研究。当然，对于科研工作者，那有不一样了。

其次，作为一个初学者、初级工程师，我更希望你们**提供一套能直接可以运行的案列（或者轻量级的cpu方案的训练模型）**，我的设备只有CPU，所以我不可能一上来就进行复杂的训练。关于这一点，我相信大多数人在学习开发中，会更多的使用自己的随身设备，即便有专用的高性能服务器，那也是在本地验证无误了，再切换上去，不可能一上来就费老大劲搭这么一套软硬件环境。随着我对paddle了解的逐渐深入，我可能希望能继续深入研究这个项目的架构，论文原理。这个时候，我期望我见到的项目会是架构清晰的，由浅入深的展示在我面前，并附赠相关的介绍、训练、测试等代码。

为此，我也愿意参与paddle开源贡献中，作为初级使用者，我可以在你们提供的官方文档上，撰写更加详细的使用说明、算法概论等，和其他使用者交流心得，助力paddle更好的发展，但是前提是您的官方文档和资料得让我读完后，使用后，有深入研究的动力，而不是我折腾了半天，毛都没弄出来。

我见过只站在开发者自身角度写文档的项目，最终的结果就是懂这个项目的人不需要看文档，不懂的人反正也看不懂，最终项目不了了之了。

**Comment by zh794390558** [comment]
感谢您的建议，我们这边考虑下如何使文档和demo更简单哈。

**Comment by 111firelicaifeng** [comment]
目前文档中给的镜像是python2还是python3的版本的？
