### ISSUE TITLE
DeepSpeech到底是python2还是python3

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#526]
教程 写这 只支持 python2.7
代码里面 却都是 python3

就算教程没更新
代码里面也有 SocketServer
python2 中这个库叫SocketServer
python3中这个库叫socketserver

所以 感觉很乱

**Comment by zh794390558** [comment]
目前develop分支上的已经升级到python3了，用的是1.8的paddle。
有错误的教程地址可以给下哈，后续订正下。

**Comment by 111firelicaifeng** [comment]
之前下载了一版是python2.7的，后来又更新为python3.6以上了，但是我拉取了几次docker镜像，里面都是python2.7的环境，希望楼主能尽快更新以下docker镜像。
