### ISSUE TITLE
如何训练中英混杂的模型呢

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleSpeech#530]

**Comment by zh794390558** [comment]
一般可以加入english character 到vocab 中。但预期不要太高，中英混杂难解，如果有好的办法欢迎反馈。

**Comment by lfxx** [comment]
> 一般可以加入english character 到vocab 中。但预期不要太高，中英混杂难解，如果有好的办法欢迎反馈。

好的，感谢您的回复，另外我自己准备了120h的普通话数据集训练，效果并不是很好，是不是因为数据集太少了呢，如何在官方的预训练模型上finetune呢

**Comment by zh794390558** [comment]
finetune 就得用同样的vocab处理下数据，从一个ckpt恢复模型，小lr训练试试。120h小时对语音来说还是太小。

**Comment by lfxx** [comment]
> finetune 就得用同样的vocab处理下数据，从一个ckpt恢复模型，小lr训练试试。120h小时对语音来说还是太小。

vocab如何处理数据呢，就是对原标注数据进行替换？

**Comment by zh794390558** [comment]
直接用提供的vocab，不自己生成了。
