### ISSUE TITLE
训练过程中，train loss : nan

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#531]
aishell训练过程中，
bash ./local/run_train.sh
-------------------------------------------
epoch: 0 , batch : 6700 ,  train loss : 64.74555
epoch: 0 , batch : 6800 ,  train loss : nan
epoch: 0 , batch : 6900 ,  train loss : nan
.......
------------------------------------------
train loss : nan
这个是什么问题导致的
有没什么影响

nvidia-smi 查看 一直正常

**Comment by yeyupiaoling** [comment]
@monkeycc 检测数据集的正确性，尝试设置更小的学习率。batch size不能太小

**Comment by lfxx** [comment]
> @monkeycc 检测数据集的正确性，尝试设置更小的学习率。batch size不能太小

我训练的时候，到了epoch5才开始报nan,如果是数据集有问题，从epoch0应该就会报nan吧,更感觉像是学习率和batch size问题，出现nan错误的时候，我的batch size是8，学习率5e-4;现在改成5e-5继续训练了

**Comment by yeyupiaoling** [comment]
@monkeycc 我说的数据集的准确性是指语音和标签直接是否对应上，而非指文件的错误。当你设置小了batch size，学习率也应该也要设置小一些。我觉得这个学习率还是大了些。

**Comment by lfxx** [comment]
> @monkeycc 我说的数据集的准确性是指语音和标签直接是否对应上，而非指文件的错误。当你设置小了batch size，学习率也应该也要设置小一些。我觉得这个学习率还是大了些。

我看您的项目里，batch size为16的时候学习率是5e-5,那如果是8的话，学习率(5e-5)/2应该会更合适些吧。另外想请教num_samples是不是根据实际数据集大小修改呢，我的训练数据有16W条音频，所以该值应该是16W吧

**Comment by yeyupiaoling** [comment]
@monkeycc 是的，num_samples可以设置为16W，这个参数是用于学习率衰减的

**Comment by lfxx** [comment]
> @monkeycc 是的，num_samples可以设置为16W，这个参数是用于学习率衰减的

num_epoch我看您设置的是200，百度官方训练脚本给的是50，不知道使用哪个比较好，200训练时间就会很长了

**Comment by yeyupiaoling** [comment]
@monkeycc 我猜官方是为了快速演示，我平时训练也是100或者200轮起步的。

**Comment by yeyupiaoling** [comment]
@monkeycc 对了，我那个项目做了比较大的更新，你可以去看一下。

**Comment by lfxx** [comment]
> @monkeycc 我猜官方是为了快速演示，我平时训练也是100或者200轮起步的。

好的，非常感谢

**Comment by yeyupiaoling** [comment]
@monkeycc 你提醒了我，我加了自动获取num_samples大小的。

**Comment by wuchaowei2012** [comment]
请问可以 相互 交换下自己制作的 语音数据集么？

**Comment by yeyupiaoling** [comment]
@wuchaowei2012 你的数据集是怎样的？

**Comment by wuchaowei2012** [comment]
都是 视频剪辑 + 标注的字幕

**Comment by wuchaowei2012** [comment]
你那里有多少，我们交换下， 做数据及太难了。

**Comment by wuchaowei2012** [comment]
你加我 微信吧 15000456023
