### ISSUE TITLE
预测中解码速度太慢

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSpeech#532]
在预测中，单独的推理也就300ms，但这个解码就要11000ms，这个解码也太慢了。有没有加快解码速度的办法？
 
https://github.com/PaddlePaddle/DeepSpeech/blob/054d795dc093e5063de1a02b23a6ac13d1cccef4/infer.py#L133-L141

在沒有损坏准确率的情况下，有没有加快解码速度的办法？如果是修改`beam_size`，准确率会下降。我从`beam_size`为500改为5，错误率从7.6%升到8.5%

**Comment by zh794390558** [comment]
num_proc_bsearch 可以调大试下，batch size 可以减小些。

**Comment by yeyupiaoling** [comment]
@zh794390558 这个不是评估，输入的就是一个文件，所以num_processes就没有用了，也没有batch size
