### ISSUE TITLE
用自己的声音尝试现场演示报错

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#535]
我用了aishell的模型进行测试，结果报错

CUDA_VISIBLE_DEVICES=0 python3 deploy/demo_server.py --host_ip localhost --host_port 8086
‘-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: /root/DeepSpeech/models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: /root/DeepSpeech/examples/aishell/data/mean_std.npz
model_path: /root/DeepSpeech/examples/aishell/checkpoints/step_final
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: False
vocab_path: /root/DeepSpeech/examples/aishell/data/vocab.txt
warmup_manifest: /root/DeepSpeech/examples/aishell/data/manifest.test-clean
’------------------------------------------------
2021-02-27 23:31:05,084-INFO: begin to initialize the external scorer for decoding
2021-02-27 23:31:08,785-INFO: language model: is_character_based = 0, max_order = 5, dict_size = 0
2021-02-27 23:31:08,785-INFO: end initializing scorer
‘-----------------------------------------------------------
Warming up ...
Warm-up Test Case %d: %s 0 /root/DeepSpeech/examples/aishell/../..//dataset/aishell/data_aishell/wav/test/S0916/BAC009S0916W0385.wav
W0227 23:31:08.934581  8325 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.1, Runtime API Version: 10.0
W0227 23:31:08.942637  8325 device_context.cc:260] device: 0, cuDNN Version: 8.0.
/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "deploy/demo_server.py", line 251, in <module>
    main()
  File "deploy/demo_server.py", line 247, in main
    start_server()
  File "deploy/demo_server.py", line 232, in start_server
    num_test_cases=3)
  File "deploy/demo_server.py", line 149, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "deploy/demo_server.py", line 208, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 420, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 170, in init_from_pretrained_model
    filename="params.pdparams")
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 804, in load_vars
    executor.run(load_prog)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

’--------------------------------------------
C++ Call Stacks (More useful to developers):
‘--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::LoadParamsFromBuffer(paddle::framework::ExecutionContext const&, paddle::platform::Place const&, std::istream*, bool, std::vector<std::string, std::allocator<std::string> > const&) const
3   paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadCombineOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

’------------------------------------------
Python Call Stacks (More useful to users):
‘------------------------------------------
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 802, in load_vars
    'model_from_memory': vars_from_memory
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 750, in load_vars
    filename=filename)
  File "/root/anaconda3/envs/DeepSpeech36/lib/python3.6/site-packages/paddle/fluid/io.py", line 876, in load_params
    filename=filename)
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 170, in init_from_pretrained_model
    filename="params.pdparams")
  File "/root/DeepSpeech/deploy/../model_utils/model.py", line 420, in infer_batch_probs
    self.init_from_pretrained_model(exe, infer_program)
  File "deploy/demo_server.py", line 208, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "deploy/demo_server.py", line 149, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "deploy/demo_server.py", line 232, in start_server
    num_test_cases=3)
  File "deploy/demo_server.py", line 247, in main
    start_server()
  File "deploy/demo_server.py", line 251, in <module>
    main()

’----------------------
Error Message Summary:
‘----------------------
UnavailableError: Not allowed to load partial data via load_combine_op, please use load_op instead.
  [Hint: Expected buffer->eof() == true, but received buffer->eof():0 != true:1.] at (/paddle/paddle/fluid/operators/load_combine_op.h:115)
  [operator < load_combine > error]

**Comment by zh794390558** [comment]
share_rnn_weights: True
use_gru: False

这个配置应该和aishell的不一致。

**Comment by monkeycc** [comment]
add_arg('host_port',        int,    8086,    "Server's IP port.")
add_arg('beam_size',        int,    500,    "Beam search width.")
add_arg('num_conv_layers',  int,    2,      "# of convolution layers.")
add_arg('num_rnn_layers',   int,    3,      "# of recurrent layers.")
add_arg('rnn_layer_size',   int,    2048,   "# of recurrent cells per layer.")
add_arg('alpha',            float,  2.5,   "Coef of LM for beam search.")
add_arg('beta',             float,  0.3,   "Coef of WC for beam search.")
add_arg('cutoff_prob',      float,  1.0,    "Cutoff probability for pruning.")
add_arg('cutoff_top_n',     int,    40,     "Cutoff number for pruning.")
add_arg('use_gru',          bool,   False,  "Use GRUs instead of simple RNNs.")
add_arg('use_gpu',          bool,   False,   "Use GPU or not.")
add_arg('share_rnn_weights',bool,   True,   "Share input-hidden weights across "
                                            "bi-directional RNNs. Not for GRU.")
add_arg('host_ip',          str,
        'localhost',
        "Server's IP address.")
add_arg('speech_save_dir',  str,
        'demo_cache',
        "Directory to save demo audios.")
add_arg('warmup_manifest',  str,
        'data/aishell/manifest.test',
        "Filepath of manifest to warm up.")
add_arg('mean_std_path',    str,
        'data/aishell/mean_std.npz',
        "Filepath of normalizer's mean & std.")
add_arg('vocab_path',       str,
        'data/aishell/vocab.txt',
        "Filepath of vocabulary.")
add_arg('model_path',       str,
        'checkpoints/aishell/step_final',
        "If None, the training starts from scratch, "
        "otherwise, it resumes from the pre-trained model.")
add_arg('lang_model_path',  str,
        'models/lm/zh_giga.no_cna_cmn.prune01244.klm',
        "Filepath for language model.")
add_arg('decoding_method',  str,
        'ctc_beam_search',
        "Decoding method. Options: ctc_beam_search, ctc_greedy",
        choices = ['ctc_beam_search', 'ctc_greedy'])
add_arg('specgram_type',    str,
        'linear',
        "Audio feature type. Options: linear, mfcc.",
        choices=['linear', 'mfcc'])

--------------------------------------------
share_rnn_weights: True
use_gru: False

不行，还是出错

**Comment by zh794390558** [comment]
share_rnn_weights: False
use_gpu: True

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
