### ISSUE TITLE
baidu_cn1.2按照8000采样报错

### ISSUE THREAD

**Issue by chasemy** [PaddlePaddle/PaddleSpeech#536]
我使用baidu_cn1.2模型进行测试,

demo_client:
data_dir='/home/audio/asr/wav/'
#data_path=os.listdir(data_dir)
#for audio_file in data_path:
audio_file = "chunk0.wav"
print(audio_file) 

(HOST, PORT) = ('localhost', 8086)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((HOST, PORT))
w=wave.open(os.path.join(data_dir,audio_file), 'r')
n = w.getnframes()
data = w.readframes(n)
s.sendall(struct.pack('>i', len(data)) + data)
received = s.recv(1024)
print(received.decode('utf-8'))

demo_server参数:

add_arg('host_port',        int,    8086,    "Server's IP port.")
add_arg('beam_size',        int,    500,    "Beam search width.")
add_arg('num_conv_layers',  int,    2,      "# of convolution layers.")
add_arg('num_rnn_layers',   int,    3,      "# of recurrent layers.")
add_arg('rnn_layer_size',   int,    2048,   "# of recurrent cells per layer.")
add_arg('alpha',            float,  2.5,   "Coef of LM for beam search.")
add_arg('beta',             float,  0.3,   "Coef of WC for beam search.")
add_arg('cutoff_prob',      float,  1,    "Cutoff probability for pruning.")
add_arg('cutoff_top_n',     int,    40,     "Cutoff number for pruning.")
add_arg('use_gru',          bool,   True,  "Use GRUs instead of simple RNNs.")
add_arg('use_gpu',          bool,   True,   "Use GPU or not.")
add_arg('share_rnn_weights',bool,   False,   "Share input-hidden weights across "
                                            "bi-directional RNNs. Not for GRU.")
add_arg('host_ip',          str,
        'localhost',
        "Server's IP address.")
add_arg('speech_save_dir',  str,
        '/home/audio/asr/temp_dir',
        "Directory to save demo audios.")
add_arg('warmup_manifest',  str,
        '/home/audio/asr/DeepSpeech/examples/aishell/data/manifest.test',
        "Filepath of manifest to warm up.")
add_arg('mean_std_path',    str,
        '/home/audio/asr/DeepSpeech/models/baidu_cn1.2k/mean_std.npz',
        "Filepath of normalizer's mean & std.")
add_arg('vocab_path',       str,
        '/home/audio/asr/DeepSpeech/models/baidu_cn1.2k/vocab.txt',
        "Filepath of vocabulary.")
add_arg('model_path',       str,
        '/home/audio/asr/DeepSpeech/models/baidu_cn1.2k/',
        "If None, the training starts from scratch, "
        "otherwise, it resumes from the pre-trained model.")
add_arg('lang_model_path',  str,
        '/home/audio/asr/DeepSpeech/models/lm/zh_giga.no_cna_cmn.prune01244.klm',
        "Filepath for language model.")
add_arg('decoding_method',  str,
        'ctc_beam_search',
        "Decoding method. Options: ctc_beam_search, ctc_greedy",
        choices = ['ctc_beam_search', 'ctc_greedy'])
add_arg('specgram_type',    str,
        'linear',
        "Audio feature type. Options: linear, mfcc.",
        choices=['linear', 'mfcc'])

_write_to_file函数:
        file = wave.open(out_filename, 'wb')
        file.setnchannels(1)
        file.setsampwidth(4)
        file.setframerate(16000)
        file.writeframes(data)

当file.setframerate(16000) 改为 file.setframerate(8000)报错:

Exception happened during processing of request from ('127.0.0.1', 60322)
Traceback (most recent call last):
  File "/home/cs/anaconda3/envs/dp/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/cs/anaconda3/envs/dp/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/home/cs/anaconda3/envs/dp/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/cs/anaconda3/envs/dp/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "server_test.py", line 114, in handle
    transcript = self.server.audio_process_handler(filename)
  File "server_test.py", line 196, in file_to_transcript
    feature = data_generator.process_utterance(filename, "")
  File "/home/audio/asr/DeepSpeech/deploy/../data_utils/data.py", line 131, in process_utterance
    speech_segment, self._keep_transcription_text)
  File "/home/audio/asr/DeepSpeech/deploy/../data_utils/featurizer/speech_featurizer.py", line 86, in featurize
    audio_feature = self._audio_featurizer.featurize(speech_segment)
  File "/home/audio/asr/DeepSpeech/deploy/../data_utils/featurizer/audio_featurizer.py", line 90, in featurize
    audio_segment.resample(self._target_sample_rate)
  File "/home/audio/asr/DeepSpeech/deploy/../data_utils/audio.py", line 410, in resample
    self.samples, self.sample_rate, target_sample_rate, filter=filter)
  File "/home/cs/anaconda3/envs/dp/lib/python3.6/site-packages/resampy/core.py", line 92, in resample
    'Only floating-point types are supported.'.format(x.dtype))
TypeError: Unable to resample signals of dtype=float32. Only floating-point types are supported.

临时语音20210302075108_127.0.0.1.wav与原始语音不一样,感觉都是杂音

**Comment by zh794390558** [comment]
应该用16k的数据吧。 resample  `Unable to resample signals of dtype=float32. Only floating-point types are supported.` 这个错误应该是 resample 不支持float32。

**Comment by DemoMoon** [comment]
manifest.test 怎么生成的呀？

**Comment by zh794390558** [comment]
参看https://github.com/PaddlePaddle/DeepSpeech/blob/transformer/examples/dataset/aishell/aishell.py

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
