### ISSUE TITLE
train out of memmory 

### ISSUE THREAD

**Issue by wwj8837817** [PaddlePaddle/PaddleSpeech#541]
显卡16G，8卡训练。
训练例子都没有问题，但是训练自己的数据集总是报oom的错误。
batch-size 64  训练10000多个batch后oom
batch-size 32 训练20000多个batch后oom
batch-size16 训练50000多个batch后oom
这是显存泄漏造的bug吗？请教该如何调试？

**Comment by zh794390558** [comment]
看下是啥oom了内存，还是显存？显存降低batch size应该没有问题。内存看你的机器负载。

**Comment by wwj8837817** [comment]
@zh794390558 是显存，在训练过程中，显存会逐渐增大，batch-size设为16，训练了1天半，其中一个卡显存溢出，训练中断。报错如下：

Out of memory error on GPU 1. Cannot allocate 148.022705MB memory on GPU 1, available memory is only 108.125000MB.

Please check whether there is any other process using GPU 1.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 at (/paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
*** Check failure stack trace: ***
    @     0x7f40a565076d  google::LogMessage::Fail()
    @     0x7f40a565421c  google::LogMessage::SendToLog()
    @     0x7f40a5650293  google::LogMessage::Flush()
    @     0x7f40a565572e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f40a87a6ec8  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f40a884208e  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7f40a883fa2f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f40a883fcf4  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f40a56adc33  std::_Function_handler<>::_M_invoke()
    @     0x7f40a54ab1b7  std::__future_base::_State_base::_M_do_set()
    @     0x7f412f8aea99  __pthread_once_slow
    @     0x7f40a883bec2  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f40a54ad614  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f40e215bc80  (unknown)
    @     0x7f412f8a76ba  start_thread
    @     0x7f412f5dd41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
Failed in training!

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。

**Comment by jeffzhengye** [comment]
我也遇到这个问题，paddle 家族这种问题真多啊，哎
