### ISSUE TITLE
No module named 'SocketServer'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSpeech#542]
根据官方 Trying Live Demo with Your Own Voice 教程

To start the demo's server, please run this in one console:

CUDA_VISIBLE_DEVICES=0 \
python3 deploy/demo_server.py \
--host_ip localhost \
--host_port 8086

报错 No module named 'SocketServer'
----------------------------------------

DeepSpeech/deploy/demo_server.py 

import SocketServer

这个 SocketServer 是在python2中使用

应该改为 socketserver

**Comment by zh794390558** [comment]
嗯嗯，好的。之后升级到2.x的就没有了。同学提个PR到1.8.5的分支上吧，谢谢哈。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
