### ISSUE TITLE
release-v1.8.5版本使用cn1.2k预训练模型难以预测的问题

### ISSUE THREAD

**Issue by haoranchen06** [PaddlePaddle/PaddleSpeech#543]
release-v1.8.5这个版本的cn1.2k模型，使用aishell的mean_std.npz
```
add_arg('mean_std_path',    str,
        'models/aishell/mean_std.npz',
        "Filepath of normalizer's mean & std.")
```
做预测时，错字率20%-40%。

但使用自带的baidu_cn1.2k_model_fluid/mean_std.npz
```
add_arg('mean_std_path',    str,
        'models/baidu_cn1.2k_model_fluid/mean_std.npz',
        "Filepath of normalizer's mean & std.")
```
做预测时输出结果全是“我”、“得”。

对此十分迷惑，希望得到解答。

**Comment by zh794390558** [comment]
测试用对应的mean std文件，不能任意换。如果觉得不太匹配，就的看下配置是否正确了。

**Comment by haoranchen06** [comment]
还有个问题，我用cn1.2k预训练模型部署demo_client和demo_sever自测的时候，无论用aishell/mean_std.npz还是baidu_cn1.2k_model_fluid/mean_std.npz，预测结果全是空白。用aishell模型自测准确率低但是能有结果，这是为什么呢？

**Comment by zh794390558** [comment]
如果离线能测试ok得话，那就server得数据问题，可能是输入得数据和训练得不匹配。可以用aishell本来得数据测试排查。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
