### ISSUE TITLE
deepspeech中遇到了 ValueError: invalid literal for int() with base 10: 'params.pdparams'

### ISSUE THREAD

**Issue by zhihenan** [PaddlePaddle/PaddleSpeech#548]
您好，我在使用前天更新的开发版中遇到了此问题：
采用的预训练模型aishell_model_fluid.tar.gz,语言模型zh_giga.no_cna_cmn.prune01244.klm,环境部署完成, 执行bash local/infer.sh 命令时出现下列错误。

-----------  Configuration Arguments -----------
checkpoint_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm
config: conf/deepspeech2.yaml
device: cpu
dump_config: None
export_path: None
nprocs: 1
opts: []
output: None
------------------------------------------------
data:
  augmentation_config: conf/augmentation.config
  batch_size: 64
  dev_manifest: data/manifest.dev
  keep_transcription_text: False
  max_duration: 27.0
  max_freq: None
  mean_std_filepath: data/mean_std.npz
  min_duration: 0.0
  n_fft: None
  num_workers: 0
  random_seed: 0
  shuffle_method: batch_shuffle
  sortagrad: True
  specgram_type: linear
  stride_ms: 10.0
  target_dB: -20
  target_sample_rate: 16000
  test_manifest: data/manifest.test
  train_manifest: data/manifest.train
  use_dB_normalization: True
  vocab_filepath: data/vocab.txt
  window_ms: 20.0
decoding:
  alpha: 2.6
  batch_size: 128
  beam_size: 300
  beta: 5.0
  cutoff_prob: 0.99
  cutoff_top_n: 40
  decoding_method: ctc_beam_search
  error_rate_type: cer
  lang_model_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm
  num_proc_bsearch: 10
model:
  num_conv_layers: 2
  num_rnn_layers: 3
  rnn_layer_size: 1024
  share_rnn_weights: False
  use_gru: True
training:
  global_grad_clip: 5.0
  lr: 0.0005
  lr_decay: 0.83
  n_epoch: 30
  weight_decay: 1e-06
2021-03-10 17:46:21,624 - INFO - Setup test Dataloader!
Traceback (most recent call last):
  File "/home/lg/DeepSpeech-develop/examples/aishell/../..//deepspeech/exps/deepspeech2/bin/infer.py", line 59, in <module>
    main(config, args)
  File "/home/lg/DeepSpeech-develop/examples/aishell/../..//deepspeech/exps/deepspeech2/bin/infer.py", line 39, in main
    main_sp(config, args)
  File "/home/lg/DeepSpeech-develop/examples/aishell/../..//deepspeech/exps/deepspeech2/bin/infer.py", line 34, in main_sp
    exp.setup()
  File "/home/lg/DeepSpeech-develop/deepspeech/exps/deepspeech2/model.py", line 337, in setup
    self.setup_model()
  File "/home/lg/DeepSpeech-develop/deepspeech/exps/deepspeech2/model.py", line 354, in setup_model
    self.test_loader.dataset, config, self.args.checkpoint_path)
  File "/home/lg/DeepSpeech-develop/deepspeech/models/deepspeech2.py", line 407, in from_pretrained
    checkpoint.load_parameters(model, checkpoint_path=checkpoint_path)
  File "/home/lg/DeepSpeech-develop/deepspeech/utils/checkpoint.py", line 84, in load_parameters
    iteration = int(os.path.basename(checkpoint_path).split("-")[-1])
ValueError: invalid literal for int() with base 10: 'zh_giga.no_cna_cmn.prune01244.klm'
Failed in inference!

在checkpoint.py   load_parameters函数中 预训练模型的处理的此步骤。 期待您的回复，感谢。

**Comment by zh794390558** [comment]
2.x的版本没有放出预训练的模型，需要重新训练。

**Comment by zhihenan** [comment]
请问一下接下来会公布2.x版本的预训练模型么？

**Comment by zhihenan** [comment]
请问一下可以提供一下2.0版本的预训练模型么，我想将demo跑通一下，学习一下。之前的版本好多坑，而且最后也没跑通。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hui ***@***.***&gt;; 
发送时间: 2021年3月11日(星期四) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/DeepSpeech] deepspeech中遇到了 ValueError: invalid literal for int() with base 10: &#39;params.pdparams&#39; (#548)





 
2.x的版本没有放出预训练的模型，需要重新训练。
 
—
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by zh794390558** [comment]
个人不太想放模型，改动模型的话还需要重新训练。最好是你能复现结果，这样代码更鲁邦。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
