### ISSUE TITLE
develop分支docker使用的是3.5版本。会报错

### ISSUE THREAD

**Issue by zhangyifei1** [PaddlePaddle/PaddleSpeech#555]
develop分支默认是python3.5版本，安装指南运行代码时会报no model resampy,导致后面的无法运行。希望开发人员可以装配docker默认为python3.7+版本

**Comment by zh794390558** [comment]
请参看 https://github.com/PaddlePaddle/DeepSpeech#setup

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
