### ISSUE TITLE
DeepSpeech识别性能问题

### ISSUE THREAD

**Issue by 535495945** [PaddlePaddle/PaddleSpeech#558]
请问下
1.现在识别一个单词需要2.3秒，请问如何提高识别效率，需要什么样的配置
2.并发识别会报错，可以并发快速识别么？

**Comment by zh794390558** [comment]
提升速度主要提升前向，和解码速度。2.3sec不知道怎么测试的。

**Comment by 535495945** [comment]
现在司使用cpu， 但是cpu只用了1核 ，如何使用多核？

**Comment by zh794390558** [comment]
cpu使用下mkldnn吧，不过这个模型还是比较大的 cpu RTF应该上不去。这个模型属于离线模型，优先考虑P4， T4吧。

**Comment by 535495945** [comment]
> 
> 
> cpu使用下mkldnn吧，不过这个模型还是比较大的 cpu RTF应该上不去。这个模型属于离线模型，优先考虑P4， T4吧。

请问如何使用mkldnn，我安装了mkldnn，但是发现并没有起作用

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
