### ISSUE TITLE
运行aishell下的export.sh报错

### ISSUE THREAD

**Issue by lfxx** [PaddlePaddle/PaddleSpeech#560]
报错如下：
AttributeError: module 'gast' has no attribute 'Index'
用的是develop分支最新版本
我用的paddle版本如下：
paddlepaddle-gpu：2.0.1.post100
gast:0.4.0

**Comment by lfxx** [comment]
> 报错如下：
> AttributeError: module 'gast' has no attribute 'Index'
> 我用的paddle版本如下：
> paddlepaddle-gpu：2.0.1.post100
> gast:0.4.0

gast降级到0.3.3解决了，不知道是不是正确的解决方法

**Comment by lfxx** [comment]
> > 报错如下：
> > AttributeError: module 'gast' has no attribute 'Index'
> > 我用的paddle版本如下：
> > paddlepaddle-gpu：2.0.1.post100
> > gast:0.4.0
> 
> gast降级到0.3.3解决了，不知道是不是正确的解决方法

运行export.sh时另外报了一个warning:
`
/home/lfxx/anaconda3/envs/deepspeech_paddle2.0/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: ../../../deepspeech/modules/rnn.py:152
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
`
rnn.py中的代码是否需要修改下

**Comment by zh794390558** [comment]
我用的2.0.0版本，没有遇到gast的问题。warning那个应该没有问题。

**Comment by lfxx** [comment]
> 我用的2.0.0版本，没有遇到gast的问题。warning那个应该没有问题。

用export导出jit模型后，checkpoint.load_parameters()并没有加载jit模型的选项，想知道如何加载使用

**Comment by zh794390558** [comment]
https://github.com/PaddlePaddle/DeepSpeech/blob/transformer/.notebook/jit_infer.ipynb

jit 是部署用的，目前还有bug还待修复。

**Comment by lfxx** [comment]
> https://github.com/PaddlePaddle/DeepSpeech/blob/transformer/.notebook/jit_infer.ipynb
> 
> jit 是部署用的，目前还有bug还待修复。

那还是用常规模型就行了吧，这两种模型是不是只有大小的区别，推理速度上有差别吗?目前在RTX2080TI上推理一个音频竟然需要0.8s,希望能早点用上tensorrt

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
