### ISSUE TITLE
docker 下运行bash run.sh 报错

### ISSUE THREAD

**Issue by zhangyifei1** [PaddlePaddle/PaddleSpeech#561]
你好，使用docker环境下，运行bash run.sh 脚本的时候，在导入数据后会报没有安装’resampy‘模块的错误。
pip3 install resampy  则会报以下错误，始终导不了包。请问是什么问题，如何解决。

![image](https://user-images.githubusercontent.com/28425091/111718595-3247c100-8895-11eb-8011-9d614f5819a0.png)

**Comment by lfxx** [comment]
> 你好，使用docker环境下，运行bash run.sh 脚本的时候，在导入数据后会报没有安装’resampy‘模块的错误。
> pip3 install resampy 则会报以下错误，始终导不了包。请问是什么问题，如何解决。
> 
> ![image](https://user-images.githubusercontent.com/28425091/111718595-3247c100-8895-11eb-8011-9d614f5819a0.png)

docker镜像还是别用了，太老旧了，一堆bug。直接用develop分支，搭建本地环境吧

**Comment by zhangyifei1** [comment]
> > 你好，使用docker环境下，运行bash run.sh 脚本的时候，在导入数据后会报没有安装’resampy‘模块的错误。
> > pip3 install resampy 则会报以下错误，始终导不了包。请问是什么问题，如何解决。
> > ![image](https://user-images.githubusercontent.com/28425091/111718595-3247c100-8895-11eb-8011-9d614f5819a0.png)
> 
> docker镜像还是别用了，太老旧了，一堆bug。直接用develop分支，搭建本地环境吧

老哥你本地跑的咋样？有什么问题没。这个环境我真是好几天了，好纠结。docker内是ubuntu16.04的版本，有点老，组件不配套。

**Comment by lfxx** [comment]
> > > 你好，使用docker环境下，运行bash run.sh 脚本的时候，在导入数据后会报没有安装’resampy‘模块的错误。
> > > pip3 install resampy 则会报以下错误，始终导不了包。请问是什么问题，如何解决。
> > > ![image](https://user-images.githubusercontent.com/28425091/111718595-3247c100-8895-11eb-8011-9d614f5819a0.png)
> > 
> > 
> > docker镜像还是别用了，太老旧了，一堆bug。直接用develop分支，搭建本地环境吧
> 
> 老哥你本地跑的咋样？有什么问题没。这个环境我真是好几天了，好纠结。docker内是ubuntu16.04的版本，有点老，组件不配套。

最新分支没啥问题，代码也很规范，照着教程来就行，可能gast版本会有问题，降级到0.3.3就能解决。想用docker的话自己搭镜像吧，官方的太老旧了

**Comment by zh794390558** [comment]
安装的问题请看下：
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/README.md#setup
我是这么用的，没有遇到问题。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
