### ISSUE TITLE
 UnavailableError: Not allowed to load partial data via load_combine_op, please use load_op instead.

### ISSUE THREAD

**Issue by yinchunlin** [PaddlePaddle/PaddleSpeech#565]
运行sh run_test_golden.sh 时遇到该问题，请问怎么处理

**Comment by zh794390558** [comment]
2.x没有test_golden的脚本了。1.8的确认下环境吧，没有遇到过这个问题。
1.8的模型，2.x 不支持。2.x没有放预训练的模型。

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
