### ISSUE TITLE
lm_dict_size = self._ext_scorer.get_dict_size()，return 0,it shoud be the reason.

### ISSUE THREAD

**Issue by yinchunlin** [PaddlePaddle/PaddleSpeech#566]
lm_dict_size = self._ext_scorer.get_dict_size()，return 0,it shoud be the reason.

_Originally posted by @wueching in https://github.com/PaddlePaddle/DeepSpeech/issues/408#issuecomment-570598781_

**Comment by yinchunlin** [comment]
lm_dict_size = self._ext_scorer.get_dict_size() where is this code could befixed？

**Comment by zh794390558** [comment]
tiny is for english model， but aishell model used? And you can try 2.x now.

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。
