### ISSUE TITLE
File contains data in an unimplemented format.

### ISSUE THREAD

**Issue by DemoMoon** [PaddlePaddle/PaddleSpeech#568]
linux同样的环境，
develop 分支 训练时候报错了。
release/v1.8.5 分支 可以正常训练。

(venvnew) [root@bogon DeepSpeech]# sh setup.sh 
Requirement already satisfied: scipy==1.2.1 in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: resampy==0.2.2 in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.2.2)
Requirement already satisfied: SoundFile==0.9.0.post1 in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.9.0.post1)
Requirement already satisfied: python_speech_features in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (0.6)
Requirement already satisfied: tensorboardX in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (2.1)
Requirement already satisfied: yacs in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (0.1.8)
Requirement already satisfied: typeguard in ./tools/venvnew/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2.11.1)
Requirement already satisfied: six>=1.3 in ./tools/venvnew/lib/python3.7/site-packages (from resampy==0.2.2->-r requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: numpy>=1.10 in ./tools/venvnew/lib/python3.7/site-packages (from resampy==0.2.2->-r requirements.txt (line 2)) (1.20.1)
Requirement already satisfied: numba>=0.32 in ./tools/venvnew/lib/python3.7/site-packages (from resampy==0.2.2->-r requirements.txt (line 2)) (0.53.0)
Requirement already satisfied: cffi>=0.6 in ./tools/venvnew/lib/python3.7/site-packages (from SoundFile==0.9.0.post1->-r requirements.txt (line 3)) (1.14.5)
Requirement already satisfied: pycparser in ./tools/venvnew/lib/python3.7/site-packages (from cffi>=0.6->SoundFile==0.9.0.post1->-r requirements.txt (line 3)) (2.20)
Requirement already satisfied: setuptools in ./tools/venvnew/lib/python3.7/site-packages (from numba>=0.32->resampy==0.2.2->-r requirements.txt (line 2)) (53.0.0)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in ./tools/venvnew/lib/python3.7/site-packages (from numba>=0.32->resampy==0.2.2->-r requirements.txt (line 2)) (0.36.0)
Requirement already satisfied: protobuf>=3.8.0 in ./tools/venvnew/lib/python3.7/site-packages (from tensorboardX->-r requirements.txt (line 5)) (3.15.6)
Requirement already satisfied: PyYAML in ./tools/venvnew/lib/python3.7/site-packages (from yacs->-r requirements.txt (line 6)) (5.4.1)
Install all dependencies successfully.

(venvnew) [root@bogon xm_test]# sh run.sh                                
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
-----------  Configuration Arguments -----------
count_threshold: 0
manifest_paths: ['data/manifest.xm']
vocab_path: data/vocab.txt
------------------------------------------------
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/scipy/fftpack/__init__.py:103: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
-----------  Configuration Arguments -----------
manifest_path: data/manifest.xm
num_samples: 1
output_path: data/mean_std.npz
specgram_type: linear
------------------------------------------------
Traceback (most recent call last):
  File "/home/develop/DeepSpeech/examples/xm_test/../..//utils/compute_mean_std.py", line 60, in <module>
    main()
  File "/home/develop/DeepSpeech/examples/xm_test/../..//utils/compute_mean_std.py", line 55, in main
    num_samples=args.num_samples)
  File "/home/develop/DeepSpeech/deepspeech/frontend/normalizer.py", line 56, in __init__
    self._compute_mean_std(manifest_path, featurize_func, num_samples)
  File "/home/develop/DeepSpeech/deepspeech/frontend/normalizer.py", line 94, in _compute_mean_std
    AudioSegment.from_file(instance["audio_filepath"])))
  File "/home/develop/DeepSpeech/deepspeech/frontend/audio.py", line 82, in from_file
    samples, sample_rate = soundfile.read(file, dtype='float32')
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/develop/DeepSpeech/examples/xm_test/dataset/xmspeech/mao.flac': File contains data in an unimplemented format.
Compute mean and stddev failed. Terminated.

(venvnew) [root@bogon xm_test]# python --version
Python 3.7.6
(venvnew) [root@bogon xm_test]# pip show paddlepaddle
Name: paddlepaddle
Version: 2.0.0
Summary: Parallel Distributed Deep Learning
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages
Requires: Pillow, gast, protobuf, requests, six, decorator, astor, numpy
Required-by: 
(venvnew) [root@bogon xm_test]#

**Comment by DemoMoon** [comment]
(venvnew) [root@bogon tiny]# sh run.sh 
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
File exists, skip downloading. (/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/test-clean/test-clean.tar.gz)
Unpacking /home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/test-clean/test-clean.tar.gz ...
Creating manifest data/manifest.test-clean ...
Traceback (most recent call last):
  File "/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/librispeech.py", line 159, in <module>
    main()
  File "/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/librispeech.py", line 124, in main
    manifest_path=args.manifest_prefix + ".test-clean")
  File "/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/librispeech.py", line 113, in prepare_dataset
    create_manifest(target_dir, manifest_path)
  File "/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/librispeech.py", line 88, in create_manifest
    audio_data, samplerate = soundfile.read(audio_filepath)
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/develop/DeepSpeech/tools/venvnew/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/develop/DeepSpeech/examples/tiny/../..//examples/dataset/librispeech/test-clean/LibriSpeech/test-clean/1089/134686/1089-134686-0000.flac': File contains data in an unimplemented format.
Prepare LibriSpeech failed. Terminated.
(venvnew) [root@bogon tiny]#

**Comment by DemoMoon** [comment]
release/v1.8.5 分支 可以正常训练。
(venv) [root@bogon DeepSpeech]#  python tools/compute_mean_std.py --num_samples 1 --specgram_type linear --manifest_path data/xm/manifest.test --output_path data/xm/mean_std.npz
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/scipy/fftpack/__init__.py:103: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/numba/core/types/__init__.py:108: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  long_ = _make_signed(np.long)
/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/numba/core/types/__init__.py:109: DeprecationWarning: `np.long` is a deprecated alias for `np.compat.long`. To silence this warning, use `np.compat.long` by itself. In the likely event your code does not need to work on Python 2 you can use the builtin `int` for which `np.compat.long` is itself an alias. Doing this will not modify any behaviour and is safe. When replacing `np.long`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ulong = _make_unsigned(np.long)
-----------  Configuration Arguments -----------
manifest_path: data/xm/manifest.test
num_samples: 1
output_path: data/xm/mean_std.npz
specgram_type: linear
------------------------------------------------

(venv) [root@bogon DeepSpeech]# pwd
/home/DeepSpeech
(venv) [root@bogon DeepSpeech]#

**Comment by zhangyifei1** [comment]
你好，请问下您使用release/v1.8.5分支，运行sh run_train.sh  训练模型的时候会报  ModuleNotFoundError: No module named 'swig_decoders'
这个错误吗？

**Comment by zhangyifei1** [comment]
> 你好，请问下您使用release/v1.8.5分支，运行sh run_train.sh 训练模型的时候会报 ModuleNotFoundError: No module named 'swig_decoders'
> 这个错误吗？

我最近一直被这个问题困扰，非常期待您的解答、

**Comment by zh794390558** [comment]
还是安装的问题soudfile 没有开 flac的支持，应该是没有安装flac相关的库。check下soundfile的安装是否支持了flac的库。最好用ubuntu的系统。

**Comment by DemoMoon** [comment]
> > 你好，请问下您使用release/v1.8.5分支，运行sh run_train.sh 训练模型的时候会报 ModuleNotFoundError: No module named 'swig_decoders'
> > 这个错误吗？
> 
> 我最近一直被这个问题困扰，非常期待您的解答、

->

**Comment by DemoMoon** [comment]
> > 你好，请问下您使用release/v1.8.5分支，运行sh run_train.sh 训练模型的时候会报 ModuleNotFoundError: No module named 'swig_decoders'
> > 这个错误吗？
> 
> 我最近一直被这个问题困扰，非常期待您的解答、
https://github.com/paddlepaddle/deepspeech/issues/113

build and install swig by source 3.0.12
cd swig
./autogen.sh
./configure
make
make install

entry decoders/swig， rerun setup.sh

**Comment by DemoMoon** [comment]
> 还是安装的问题soudfile 没有开 flac的支持，应该是没有安装flac相关的库。check下soundfile的安装是否支持了flac的库。最好用ubuntu的系统。

(venv) [root@bogon ~]# python
Python 3.7.6 (default, Mar 11 2021, 16:20:31) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soundfile as sf
>>> f = sf.SoundFile('/home/develop/DeepSpeech/examples/xm_test/dataset/xmspeech/mao.flac')
>>> len(f)
11520
>>> a=sf.read(f,dtype='float32')
From cffi callback <function SoundFile._init_virtual_io.<locals>.vio_read at 0x7f77f383d0e0>:
Traceback (most recent call last):
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1295, in vio_read
    data_read = file.readinto(buf)
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 823, in __getattr__
    "'SoundFile' object has no attribute {0!r}".format(name))
AttributeError: 'SoundFile' object has no attribute 'readinto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1300, in vio_read
    buf[0:data_read] = data
ValueError: right operand length must match slice length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening SoundFile('/home/develop/DeepSpeech/examples/xm_test/dataset/xmspeech/mao.flac', mode='r', samplerate=16000, channels=1, format='FLAC', subtype='PCM_16', endian='FILE'): File contains data in an unknown format.
>>> b = b.SoundFile('/home/DeepSpeech/dataset/librispeech/dev-clean/LibriSpeech/dev-clean/1272/128104/1272-128104-0000.flac')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'b' is not defined
>>> ab = ab.SoundFile('/home/DeepSpeech/dataset/librispeech/dev-clean/LibriSpeech/dev-clean/1272/128104/1272-128104-0000.flac')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ab' is not defined
>>> ab = sf.SoundFile('/home/DeepSpeech/dataset/librispeech/dev-clean/LibriSpeech/dev-clean/1272/128104/1272-128104-0000.flac')
>>> len(ab)
93680
>>> sb=sf.read(ab,dtype='float32')
From cffi callback <function SoundFile._init_virtual_io.<locals>.vio_read at 0x7f77f383d0e0>:
Traceback (most recent call last):
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1295, in vio_read
    data_read = file.readinto(buf)
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 823, in __getattr__
    "'SoundFile' object has no attribute {0!r}".format(name))
AttributeError: 'SoundFile' object has no attribute 'readinto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1300, in vio_read
    buf[0:data_read] = data
ValueError: right operand length must match slice length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/DeepSpeech/tools/venv/lib/python3.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening SoundFile('/home/DeepSpeech/dataset/librispeech/dev-clean/LibriSpeech/dev-clean/1272/128104/1272-128104-0000.flac', mode='r', samplerate=16000, channels=1, format='FLAC', subtype='PCM_16', endian='FILE'): File contains data in an unknown format.
>>>

**Comment by DemoMoon** [comment]
> 还是安装的问题soudfile 没有开 flac的支持，应该是没有安装flac相关的库。check下soundfile的安装是否支持了flac的库。最好用ubuntu的系统。

可能是执行 sh setup.sh ，libsndfile 没有安装，下载 libsndfile -1.0.28.tar.gz 安装完 就可以了。

**Comment by zhangyifei1** [comment]
> > 还是安装的问题soudfile 没有开 flac的支持，应该是没有安装flac相关的库。check下soundfile的安装是否支持了flac的库。最好用ubuntu的系统。
> 
> 可能是执行 sh setup.sh ，libsndfile 没有安装，下载 libsndfile -1.0.28.tar.gz 安装完 就可以了。

您好。先谢谢您的帮助。我比较新手，可以问下如何chech  soundfile的安装是否支持了flac的库呀？

**Comment by DemoMoon** [comment]
> > > 还是安装的问题soudfile 没有开 flac的支持，应该是没有安装flac相关的库。check下soundfile的安装是否支持了flac的库。最好用ubuntu的系统。
> > 
> > 
> > 可能是执行 sh setup.sh ，libsndfile 没有安装，下载 libsndfile -1.0.28.tar.gz 安装完 就可以了。
> 
> 您好。先谢谢您的帮助。我比较新手，可以问下如何chech soundfile的安装是否支持了flac的库呀？

**注意加粗部分**
1.安装flac 1.3.1
wget https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.1.tar.xz
xz -d flac-1.3.1.tar.xz
tar -xvf flac-1.3.1.tar
cd flac-1.3.1
./configure
make
make install

2. 安装 libsndfile-1.0.28    ./configure && make && make install 可以检测出libsndfile 是否支持flac 
[root@ip-10-0-1-197 libsndfile-1.0.28]# ./configure 
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether we are using the CLANG C compiler... no
checking for a sed that does not truncate output... /bin/sed
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... no
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /bin/ld -m elf_x86_64
checking if the linker (/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... no
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for windres... no
checking whether ln -s works... yes
checking for autogen... no
checking for wine... no
checking for xcode-select... no
checking for ANSI C header files... (cached) yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking whether S_IRGRP is declared... yes
checking whether the -Werror option is usable... yes
checking for simple visibility declarations... yes
checking size of wchar_t... 4
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of float... 4
checking size of double... 8
checking size of void*... 8
checking size of size_t... 8
checking size of int64_t... 8
checking size of long long... 8
checking size of off_t... 8
checking for ssize_t... yes
checking processor byte ordering... little
checking for malloc... yes
checking for calloc... yes
checking for realloc... yes
checking for free... yes
checking for open... yes
checking for read... yes
checking for write... yes
checking for lseek... yes
checking for lseek64... yes
checking for fstat... yes
checking for fstat64... yes
checking for ftruncate... yes
checking for fsync... yes
checking for snprintf... yes
checking for vsnprintf... yes
checking for gmtime... yes
checking for gmtime_r... yes
checking for localtime... yes
checking for localtime_r... yes
checking for gettimeofday... yes
checking for mmap... yes
checking for getpagesize... yes
checking for setlocale... yes
checking for pipe... yes
checking for waitpid... yes
checking for floor in -lm... yes
checking for floor... yes
checking for ceil... yes
checking for fmod... yes
checking for lround... yes
checking for lrint... yes
checking for lrintf... yes
checking for octave... no
checking for mkoctfile... no
checking for octave-config... no
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
**checking for flac >= 1.3.1 ... yes**
checking for ogg >= 1.1.3 ... yes
checking for vorbis >= 1.2.3 ... yes
checking for vorbisenc >= 1.2.3 ... yes
checking for sqlite3 >= 3.2 ... yes
checking processor clipping capabilities... none
checking alsa/asoundlib.h usability... no
checking alsa/asoundlib.h presence... no
checking for alsa/asoundlib.h... no
configure: WARNING: Touching files in directory tests/.
checking if gcc -std=gnu99 accepts -std=gnu99... yes
checking for version of gcc -std=gnu99... 4.8.5
checking if gcc -std=gnu99 accepts -Wextra... yes
checking if gcc -std=gnu99 accepts -Wdeclaration-after-statement... yes
checking if gcc -std=gnu99 accepts -Wpointer-arith... yes
checking if g++ accepts -Wextra... yes
checking if g++ accepts -Wpointer-arith... yes
checking whether to add -D_FORTIFY_SOURCE=2 to CPPFLAGS... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating src/Makefile
config.status: creating man/Makefile
config.status: creating examples/Makefile
config.status: creating tests/Makefile
config.status: creating regtest/Makefile
config.status: creating M4/Makefile
config.status: creating doc/Makefile
config.status: creating Win32/Makefile
config.status: creating Octave/Makefile
config.status: creating programs/Makefile
config.status: creating Makefile
config.status: creating src/version-metadata.rc
config.status: creating tests/test_wrapper.sh
config.status: creating tests/pedantic-header-test.sh
config.status: creating doc/libsndfile.css
config.status: creating Scripts/build-test-tarball.mk
config.status: creating libsndfile.spec
config.status: creating sndfile.pc
config.status: creating src/sndfile.h
config.status: creating echo-install-dirs
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands

-=-=-=-=-=-=-=-=-=-= Configuration Complete =-=-=-=-=-=-=-=-=-=-

  Configuration summary :

    libsndfile version : .................. 1.0.28

    Host CPU : ............................ x86_64
    Host Vendor : ......................... pc
    Host OS : ............................. linux-gnu

    Experimental code : ................... no
    Using ALSA in example programs : ...... no
    **External FLAC/Ogg/Vorbis : ............ yes**

  Tools :

    Compiler is Clang : ................... no
    Compiler is GCC : ..................... yes
    GCC version : ......................... 4.8.5
    Sanitizer enabled : ................... no
    Stack smash protection : .............. no

  Installation directories :

    Library directory : ................... /usr/local/lib
    Program directory : ................... /usr/local/bin
    Pkgconfig directory : ................. /usr/local/lib/pkgconfig
    HTML docs directory : ................. /usr/local/share/doc/

Compiling some other packages against libsndfile may require
the addition of '/usr/local/lib/pkgconfig' to the
PKG_CONFIG_PATH environment variable.

**Comment by DemoMoon** [comment]
External FLAC/Ogg/Vorbis : ............ yes

**Comment by DemoMoon** [comment]
如果不可以的话，环境变量里面再加上这句话 PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
export PKG_CONFIG_PATH
用source 刷新下环境。
