### ISSUE TITLE
bash run.sh

### ISSUE THREAD

**Issue by zhangyifei1** [PaddlePaddle/PaddleSpeech#569]
(base) root@a8e4df74e22d:/DeepSpeech/DeepSpeech-develop/examples/tiny# bash run.sh
/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py:297: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
Skip downloading and unpacking. Data already exists in /DeepSpeech/DeepSpeech-develop/examples/tiny/../..//examples/dataset/aishell.
Creating manifest data/manifest ...

/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py:297: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
-----------  Configuration Arguments -----------
count_threshold: 0
manifest_paths: ['data/manifest.train', 'data/manifest.dev']
vocab_path: data/vocab.txt
------------------------------------------------
/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py:297: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
-----------  Configuration Arguments -----------
manifest_path: data/manifest.train
num_samples: 2000
output_path: data/mean_std.npz
specgram_type: linear
------------------------------------------------
Aishell data preparation done.
using 2 gpus...
/root/anaconda3/lib/python3.8/site-packages/paddle/fluid/framework.py:297: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
Traceback (most recent call last):
  File "/DeepSpeech/DeepSpeech-develop/examples/tiny/../..//deepspeech/exps/deepspeech2/bin/train.py", line 26, in <module>
    from deepspeech.exps.deepspeech2.config import get_cfg_defaults
  File "/DeepSpeech/DeepSpeech-develop/deepspeech/exps/deepspeech2/config.py", line 16, in <module>
    from deepspeech.models.deepspeech2 import DeepSpeech2Model
  File "/DeepSpeech/DeepSpeech-develop/deepspeech/models/deepspeech2.py", line 31, in <module>
    from deepspeech.modules.ctc import CTCDecoder
  File "/DeepSpeech/DeepSpeech-develop/deepspeech/modules/ctc.py", line 23, in <module>
    from deepspeech.decoders.swig_wrapper import Scorer
  File "/DeepSpeech/DeepSpeech-develop/deepspeech/decoders/swig_wrapper.py", line 16, in <module>
    import swig_decoders
ModuleNotFoundError: No module named 'swig_decoders'

**Comment by zh794390558** [comment]
setup.sh 应该没有安装正确，check下 decoders 相关安装是否正确。建议按照reademe的方式安装，ubuntu 系统。

**Comment by zhangyifei1** [comment]
> setup.sh 应该没有安装正确，check下 decoders 相关安装是否正确。建议按照reademe的方式安装，ubuntu 系统。

![image](https://user-images.githubusercontent.com/28425091/112122495-4ecc5c00-8bfb-11eb-8bf7-7b4d0718f4ec.png)
你好，执行setup.sh，显示这个。不是安装成功了么？

**Comment by zhangyifei1** [comment]
> setup.sh 应该没有安装正确，check下 decoders 相关安装是否正确。建议按照reademe的方式安装，ubuntu 系统。

而且pip3 list也有了 ’swig-decoders‘这个包了。
![Uploading image.png…]()

**Comment by zh794390558** [comment]
python3 -c "import pkg_resources; pkg_resources.require(\"swig_decoders==1.1\")"
还是check下吧，这种应该是环境或安装的问题。
我用的release的docker，没遇到啥问题。

**Comment by zhangyifei1** [comment]
> python3 -c "import pkg_resources; pkg_resources.require("swig_decoders==1.1")"
> 还是check下吧，这种应该是环境或安装的问题。

请问显示这个是什么意思呢？
[swig-decoders 1.1 (/usr/local/lib/python3.7/dist-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg)]

**Comment by zhangyifei1** [comment]
> > python3 -c "import pkg_resources; pkg_resources.require("swig_decoders==1.1")"
> > 还是check下吧，这种应该是环境或安装的问题。
> 
> 请问显示这个是什么意思呢？
> [swig-decoders 1.1 (/usr/local/lib/python3.7/dist-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg)]

![Uploading image.png…]()

**Comment by zhangyifei1** [comment]
> python3 -c "import pkg_resources; pkg_resources.require("swig_decoders==1.1")"
> 还是check下吧，这种应该是环境或安装的问题。
> 我用的release的docker，没遇到啥问题。

![image](https://user-images.githubusercontent.com/28425091/112126494-77eeeb80-8bff-11eb-9eeb-71b1088405fb.png)
这个是运行：python3-->help()-->modules后的显示。

**Comment by zh794390558** [comment]
就是安装到 /usr/local/lib/python3.7/ 这个python环境啦，你用得是conda。所以还是环境没弄好。

还是按readme安装使用吧。

**Comment by zhangyifei1** [comment]
> 就是安装到 /usr/local/lib/python3.7/ 这个python环境啦，你用得是conda。所以还是环境没弄好。
> 
> 还是安readme安装使用吧。

那请问大佬我这种情况现在怎么操作呢？我是按照readme操作的，没有用docker,因为doceker环境装不了resampy==0.2.2这个包。

**Comment by zh794390558** [comment]
没有docker，也可以用 venv得环境。conda应该也是可以得。
先source环境，再安装。

**Comment by DemoMoon** [comment]
是因为系统没有安装swig ，需要按这个。
(venv) [root@xx deploy_demo]# swig -version
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre
Please see http://www.swig.org for reporting bugs and further information
1. 下载个swig 3.0.12 ，安装一下；
2. 去 venv Python 目录/home/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/  删除掉这个目录的所有文件；
3. 重新执行 DeepSpeech目录下的 sh setup.sh;

**Comment by DemoMoon** [comment]
是因为系统没有安装swig ，需要按这个。
(venv) [root@xx deploy_demo]# swig -version
SWIG Version 3.0.12
Compiled with g++ [x86_64-pc-linux-gnu]
Configured options: +pcre
Please see http://www.swig.org for reporting bugs and further information
1. 下载个swig 3.0.12 ，安装一下；
2. 去 venv Python 目录/home/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/  删除掉这个目录的所有文件；
3. 重新执行 DeepSpeech目录下的 sh setup.sh;

**Comment by DemoMoon** [comment]
![image](https://user-images.githubusercontent.com/5241098/112247612-8edd1e80-8c8f-11eb-92d6-dafe80315148.png)
你现在的这个目录下 ，缺少 swig_decoders.py 这个文件。

**Comment by DemoMoon** [comment]
参考 这个地址 https://github.com/paddlepaddle/deepspeech/issues/113

**Comment by JohnDoe117** [comment]
@zhangyifei1 
conda虚拟环境下
使用源码安装swig 3.0.12
添加环境变量之后会出现
缺失libpcre.so.1
你查找一下文件 应该这个文件在conda的虚拟环境下 
添加一个系统软连接即可
ln -s  /XX虚拟环境的路径XXX/libpcre.so.1 /usr/lib/libpcre.so.1
然后重新运行swig目录下的 setup.sh

**Comment by zh794390558** [comment]
请到 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问，并给出详细信息，issue后续只用来做bug report。

**Comment by zhangyifei1** [comment]
> @zhangyifei1
> conda虚拟环境下
> 使用源码安装swig 3.0.12
> 添加环境变量之后会出现
> 缺失libpcre.so.1
> 你查找一下文件 应该这个文件在conda的虚拟环境下
> 添加一个系统软连接即可
> ln -s /XX虚拟环境的路径XXX/libpcre.so.1 /usr/lib/libpcre.so.1
> 然后重新运行swig目录下的 setup.sh

感谢大佬耐心回复，经过安装，swig后，swif -vsersion后显示。
![image](https://user-images.githubusercontent.com/28425091/112280964-83561b80-8cc0-11eb-8478-ece6db9f8dff.png)
，执行cd decoders/swig   sudo sh setep.sh后。
![image](https://user-images.githubusercontent.com/28425091/112281096-a680cb00-8cc0-11eb-92d0-6409219811d6.png)
，pip3 list 还是没有swig-decoders
,执行 /xamples/tiny    sh run_train.sh   还是报错，ModuleNotFoundError: No module named 'swig_decoders'
哭了😨😭

**Comment by DemoMoon** [comment]
1.去 venv Python 目录/home/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/ 删除掉这个目录的所有文件； 
2. 去 DeepSpeech目录下执行 sh setup.sh;
