### ISSUE TITLE
请问下deepspeech输出asr结果包含概率吗？就是类似置信度的参数

### ISSUE THREAD

**Issue by zhangyifei1** [PaddlePaddle/PaddleSpeech#589]
请问下deepspeech输出asr结果包含概率吗？就是类似置信度的参数

**Comment by zh794390558** [comment]
您好，QA可以去 https://github.com/PaddlePaddle/DeepSpeech/discussions 这里提问。  这个问题和 https://github.com/PaddlePaddle/DeepSpeech/discussions/586 一样，麻烦关注下。
