### ISSUE TITLE
想将语音识别为拼音，但WER一直等于1正常吗？

### ISSUE THREAD

**Issue by gezimonkey** [PaddlePaddle/PaddleSpeech#592]
我尝试使用DeepSpeech训练自己的数据来识别带声调的拼音(例如：pu3 tong1 hua4)
数据大约有500小时采样率为16K的wav，质量一般，我进行了降噪和vad处理
训练时设置力lang_model_path为空，其他参数未动

epoch>60后，loss在0.6-1.2之间震荡
test结果全部为“< u n k >”
wer等于1

我想知道问题出在哪？

**Comment by zh794390558** [comment]
issue 只接受 bug，QA请在 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问。
