### ISSUE TITLE
有关“普通话语言模型”一节说”在两个字符之间插入空白字符“的问题

### ISSUE THREAD

**Issue by Jackie-J** [PaddlePaddle/PaddleSpeech#595]
你好！

> 在1.8.5版本的文档中，”普通话语言模型“一节，说语料库在预处理阶段要”在两个字符之间插入空白字符“。但是用 examples/aishell/run_data.sh 脚本生成的 manifest.train 文件中， text 部分的句子之间的字符没有空白字符，比如：”浙江的民营企业有着极为灵敏的商业嗅觉“，但是在 aishell 语料库中的 transcript 文件下是有空格的，比如：”而 对 楼市 成交 抑制 作用 最 大 的 限 购“。所以目前有两个疑惑点：

1. 语料库在预处理阶段要”在两个字符之间插入空白字符“的作用是什么，对训练有什么影响

2. manifest.train 文件中的 text ，需不需要在两个字符之间插入空白字符，或者是要按照类似”而 对 楼市 成交 抑制 作用 最 大 的 限 购“这样的效果插入空白字符。

**Comment by zh794390558** [comment]
issue 只接受 bug，QA请在 https://github.com/PaddlePaddle/DeepSpeech/discussions 中提问。
