### ISSUE TITLE
How to get the duration and start time of each word?

### ISSUE THREAD

**Issue by hebo1982** [PaddlePaddle/PaddleSpeech#600]
```
ds2_model.decode_batch_beam_search
```
only return text and confidence

**Comment by zh794390558** [comment]
we can not get timing info now, we will add after.

**Comment by hengshan123** [comment]
is there problem solved ? i want the duration too.

**Comment by yt605155624** [comment]
> is there problem solved ? i want the duration too.

please see examples/[datasets]/asr1 stage 4, CTC align has the function of forced alignment, which can get the corresponding time range of each word
