### ISSUE TITLE
RuntimeError: Variable's shape does not match, the Program requires a parameter with the shape of ((2048, 2048)), while the loaded parameter (namely [ layer_3_forward_rnn_weight ]) has a shape of  ((2048, 6144)).

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/PaddleSpeech#617]
python3 deploy/demo_server.py
用的模型：zh_giga.no_cna_cmn.prune01244.klm和baidu_cn1.2k_model_fluid.tar.gz
配置参数：
add_arg('beam_size',        int,    500,    "Beam search width.")
add_arg('num_conv_layers',  int,    2,      "# of convolution layers.")
add_arg('num_rnn_layers',   int,    3,      "# of recurrent layers.")
add_arg('rnn_layer_size',   int,    2048,   "# of recurrent cells per layer.")
add_arg('alpha',            float,  2.5,   "Coef of LM for beam search.")
add_arg('beta',             float,  0.3,   "Coef of WC for beam search.")
add_arg('cutoff_prob',      float,  1.0,    "Cutoff probability for pruning.")
add_arg('cutoff_top_n',     int,    40,     "Cutoff number for pruning.")
add_arg('use_gru',          bool,   False,  "Use GRUs instead of simple RNNs.")
add_arg('use_gpu',          bool,   False,   "Use GPU or not.")
add_arg('share_rnn_weights',bool,  False,   "Share input-hidden weights across "
                                            "bi-directional RNNs. Not for GRU.")

**Comment by daixiangzi** [comment]
已解决。

**Comment by a0735a** [comment]
怎么解决的，请贴一下吧
