### ISSUE TITLE
保存模型出错。

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/PaddleSpeech#624]
with fluid.program_guard(infer_program, startup_prog):  
   with fluid.unique_name.guard():  
                feeder, log_probs, inputs = self.create_network(is_infer=True)  
infer_program = infer_program.clone(for_test=True)  
exe = fluid.Executor(self._place)  
if not self._init_from_pretrained_model:  
       exit("No pretrain model file path!")
self.init_from_pretrained_model(exe, infer_program)
**fluid.io.save_inference_model("./",['masks','seq_len_data','audio_data'],[log_probs], exe,main_program=infer_program)**

InvalidArgumentError: The Tensor in the save Op's Input Variable X(softmax_0.tmp_0) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1511)
      [operator < save > error]
``

**Comment by daixiangzi** [comment]
i use baidu_cn1.2k_model_fluid.tar.gz weight

**Comment by zh794390558** [comment]
log_probs 这个没有初始化。还有1.x的现在不维护了，我也不熟悉。

**Comment by daixiangzi** [comment]
> log_probs 这个没有初始化。还有1.x的现在不维护了，我也不熟悉。

paddle刚接触，想问下这个怎么初始化哇。。

**Comment by daixiangzi** [comment]
按道理我执行了self.init_from_pretrained_model(exe, infer_program)这个就已经把参数加载进去了

**Comment by zh794390558** [comment]
你想保存的是模型参数?应该可以把所有的参数都list出来，fetch出里面的data，numpy save下来吧。

**Comment by zh794390558** [comment]
startup_prog 这个是初始化相关的逻辑，需要先执行这个。

**Comment by daixiangzi** [comment]
> startup_prog 这个是初始化相关的逻辑，需要先执行这个。

因为这个语音模型里面就一个params.pdparams,我想重新load然后保存__model__ 和__params__这种形式

**Comment by zh794390558** [comment]
为啥要这么做？之后QA可以提在discusstion里。可以参考1.8里的infer相关的代码把参数都dump出来。

**Comment by daixiangzi** [comment]
> 为啥要这么做？之后QA可以提在discusstion里。可以参考1.8里的infer相关的代码把参数都dump出来。

因为想用paddle2onnx 转onnx

**Comment by zh794390558** [comment]
> > 为啥要这么做？之后QA可以提在discusstion里。可以参考1.8里的infer相关的代码把参数都dump出来。
> 
> 因为想用paddle2onnx 转onnx

可以看下inference相关的代码，应该按照那个套路做下就行。

**Comment by daixiangzi** [comment]
恩，我试试
