### ISSUE TITLE
多进程cuda 初始化错误

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/PaddleSpeech#631]
错误信息：
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:200)

**Comment by daixiangzi** [comment]
看了iSSUES中也有很多人提到该错误，但是没有实质的解决方案？

**Comment by zh794390558** [comment]
这是哪个版本得paddle？你的cuda是哪个版本的？估计是不匹配吧。

**Comment by daixiangzi** [comment]
> 这是哪个版本得paddle？你的cuda是哪个版本的？估计是不匹配吧。

2.0版本，但是我不用多进程就可以跑通

**Comment by daixiangzi** [comment]
cuda11

**Comment by zh794390558** [comment]
> > 这是哪个版本得paddle？你的cuda是哪个版本的？估计是不匹配吧。
> 
> 2.0版本，但是我不用多进程就可以跑通

多进程是2.1修复的。目前先用2.0.2 的版本吧，多进程得先关掉。2.1还有些问题。

**Comment by daixiangzi** [comment]
> > > 这是哪个版本得paddle？你的cuda是哪个版本的？估计是不匹配吧。
> > 
> > 
> > 2.0版本，但是我不用多进程就可以跑通
> 
> 多进程是2.1修复的。目前先用2.0.2 的版本吧，多进程得先关掉。2.1还有些问题。

我刚升级到了2.1喔，但是依然存在这个问题

**Comment by zh794390558** [comment]
cuda11没有用过呀
`python -m pip install paddlepaddle-gpu==2.1.0.post112 -f https://paddlepaddle.org.cn/whl/mkl/stable.html `
有更详细的信息可以去 paddle 上提issue。
