### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by kinda830** [PaddlePaddle/PaddleSpeech#638]
aishell 下提供的预训练模型参数文件有问题，加载时报错了，报错内容如下：_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by zh794390558** [comment]
抱歉，2.x还没有提供预训练的模型。1.8的不能随便导入到2.x中。

**Comment by Leon0427** [comment]
2.x有计划提供预训练模型吗？ 啥时候提供？
