### ISSUE TITLE
pushd tools; make; popd命令,CetOS系统只有yum，没有apt-get,安装不成功

### ISSUE THREAD

**Issue by sion1989** [PaddlePaddle/PaddleSpeech#642]
pushd tools; make; popd命令,CetOS系统只有yum，没有apt-get,安装不成功

**Comment by zh794390558** [comment]
可以找下对应的centos的库的命令安装即可。

**Comment by Kkkassini** [comment]
请更新makefile适配centos

**Comment by zh794390558** [comment]
建议用ubuntu的环境，或docker。centos有很多不好的地方，所以都不在上面开发了。
