### ISSUE TITLE
百度1.8中开源的中文语音模型，会限制待识别的语音长度么

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/PaddleSpeech#644]

**Comment by zh794390558** [comment]
训练中会有限制的。

**Comment by daixiangzi** [comment]
推理中呢



我没有什么天赋，我只是生而由来的执着。


------------------ 原始邮件 ------------------
发件人: Hui Zhang ***@***.***&gt;
发送时间: 2021年5月26日 10:10
收件人: PaddlePaddle/DeepSpeech ***@***.***&gt;
抄送: daixiangzi ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[PaddlePaddle/DeepSpeech] 百度1.8中开源的中文语音模型，会限制待识别的语音长度么 (#644)





 
训练中会有限制的。

**Comment by zh794390558** [comment]
推理需要和训练匹配的。
