### ISSUE TITLE
_compute_linear_specgram算法有沒有相关资料看一下

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSpeech#649]
我看对音频特征提取默认是使用这个算法，估计是它比MFCC要好，但我没找到该算法的相关介绍和论文，有没有相关资料我看一下。

https://github.com/PaddlePaddle/DeepSpeech/blob/03e5a64d26eeab3cc81192542d369bd9a47a701e/deepspeech/frontend/featurizer/audio_featurizer.py#L170-L218

**Comment by zh794390558** [comment]
抱歉，没有相关资料。这个是很标准的提频谱的过程，只有https://github.com/PaddlePaddle/DeepSpeech/blob/03e5a64d26eeab3cc81192542d369bd9a47a701e/deepspeech/frontend/featurizer/audio_featurizer.py#L213  这部分应该是对加窗做了能量的调整。

**Comment by zh794390558** [comment]
https://blog.ailemon.net/2021/03/01/speech-acoustic-feature-extraction-the-principle-of-mfcc-and-logfbank-algorithm/
https://zhuanlan.zhihu.com/p/147386972

这两个参考下吧。

**Comment by yeyupiaoling** [comment]
好的，谢谢
