### ISSUE TITLE
Demo发散

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleSpeech#659]
新配服务器：3090+CUDA11.2+cuDNN8.1，在paddle2.1上训练自建数据集和官方数据集时train loss较大且发散。但之前在旧服务器上：2080+CUDA11.1+cuDNN8.0，在paddle2.0上训练ok。更奇怪的是将训练好的模型部署在新服务器上直接做测试的结果也有问题。不知道有没有大佬在新服务器配置上训练过
**loss:**
[INFO 2021/06/05 22:50:31 model.py:72] Train: Rank: 0, epoch: 192, step: 6106, time: 2.204s, train_loss: 421.891632
[INFO 2021/06/05 22:50:31 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6106, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:33 model.py:72] Train: Rank: 0, epoch: 192, step: 6107, time: 1.459s, train_loss: 264.403625
[INFO 2021/06/05 22:50:33 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6107, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:34 model.py:72] Train: Rank: 0, epoch: 192, step: 6108, time: 1.691s, train_loss: 301.924622
[INFO 2021/06/05 22:50:34 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6108, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:35 model.py:72] Train: Rank: 0, epoch: 192, step: 6109, time: 1.086s, train_loss: 169.005737
[INFO 2021/06/05 22:50:35 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6109, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:36 model.py:72] Train: Rank: 0, epoch: 192, step: 6110, time: 0.773s, train_loss: 102.978607
[INFO 2021/06/05 22:50:36 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6110, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:37 model.py:72] Train: Rank: 0, epoch: 192, step: 6111, time: 1.142s, train_loss: 212.450012
[INFO 2021/06/05 22:50:37 trainer.py:177] Train: Rank: 0, epoch: 192, step: 6111, dataloader time: 0.000s,
[INFO 2021/06/05 22:50:40 model.py:72] Train: Rank: 0, epoch: 192, step: 6112, time: 2.869s, train_loss: 510.787109
**预测：**
[INFO 2021/06/06 16:12:58 model.py:259] Current error rate [cer] = 1.666667
[INFO 2021/06/06 16:12:58 model.py:257]
Target Transcription: 杨海彪
Output Transcription: 这是一个不大不小的一个
[INFO 2021/06/06 16:12:58 model.py:259] Current error rate [cer] = 3.666667
[INFO 2021/06/06 16:12:58 model.py:257]
Target Transcription: 收不收短信
Output Transcription: 这是一个不大不小的一个
[INFO 2021/06/06 16:12:58 model.py:259] Current error rate [cer] = 2.000000
[INFO 2021/06/06 16:12:58 model.py:257]
Target Transcription: 我爱你我在找
Output Transcription: 这是一个不大不小的一个
更变解码参数α和β：
Target Transcription: 来首歌
Output Transcription: 这是一个在天上一个在天上一个在天上一个在天上一个在天上一个在
[INFO 2021/06/06 16:06:16 model.py:259] Current error rate [cer] = 10.000000
[INFO 2021/06/06 16:06:16 model.py:257]
Target Transcription: 会刮
Output Transcription: 这是一个在天上一个在天上一个在天上一个在天上一个在天上一个在
[INFO 2021/06/06 16:06:16 model.py:259] Current error rate [cer] = 15.000000
[INFO 2021/06/06 16:06:16 model.py:257]
Target Transcription: 听个玩笑
Output Transcription: 这是一个在天上一个在天上一个在天上一个在天上一个在天上一个在

**Comment by zh794390558** [comment]
paddle 回退到2.0试试吧，先排除下是硬件问题还是paddle版本问题。2080+CUDA11.1+cuDNN8.0，在paddle2.1可以试试。

**Comment by FrankWhh** [comment]
> 
> 
> paddle 回退到2.0试试吧，先排除下是硬件问题还是paddle版本问题。2080+CUDA11.1+cuDNN8.0，在paddle2.1可以试试。

退回paddle2.0报兼容问题，CUDA no kernel image错误。新硬件下测试OCR是OK的，loss 无异常。明天试试在旧硬件下用paddle2.1

**Comment by FrankWhh** [comment]
退回paddle2.0 post112 train ok
2080+CUDA11.1+cuDNN8.0，在paddle2.1 train loss也是发散
看着是paddle2.1版本问题
**旧服务器 paddle2.1**
[INFO 2021/06/08 14:44:25 model.py:72] Train: Rank: 0, epoch: 1, step: 261421, time: 2.348s, train_loss: 69.097511
[INFO 2021/06/08 14:44:25 trainer.py:177] Train: Rank: 0, epoch: 1, step: 261421, dataloader time: 0.000s,
[INFO 2021/06/08 14:44:26 model.py:72] Train: Rank: 0, epoch: 1, step: 261422, time: 0.477s, train_loss: 97.766014
[INFO 2021/06/08 14:44:26 trainer.py:177] Train: Rank: 0, epoch: 1, step: 261422, dataloader time: 0.000s,
[INFO 2021/06/08 14:44:26 model.py:72] Train: Rank: 0, epoch: 1, step: 261423, time: 0.472s, train_loss: 107.550858
[INFO 2021/06/08 14:44:26 trainer.py:177] Train: Rank: 0, epoch: 1, step: 261423, dataloader time: 0.000s,
[INFO 2021/06/08 14:44:27 model.py:72] Train: Rank: 0, epoch: 1, step: 261424, time: 0.478s, train_loss: 115.088768
[INFO 2021/06/08 14:44:27 trainer.py:177] Train: Rank: 0, epoch: 1, step: 261424, dataloader time: 0.000s,
**新服务器 paddle2.0**
[INFO 2021/06/08 15:08:21 model.py:72] Train: Rank: 0, epoch: 1, step: 9, time: 0.627s, train_loss: 48.579567
[INFO 2021/06/08 15:08:21 trainer.py:177] Train: Rank: 0, epoch: 1, step: 9, dataloader time: 0.000s,
[INFO 2021/06/08 15:08:21 model.py:72] Train: Rank: 0, epoch: 1, step: 10, time: 0.626s, train_loss: 41.341385
[INFO 2021/06/08 15:08:21 trainer.py:177] Train: Rank: 0, epoch: 1, step: 10, dataloader time: 0.000s,
[INFO 2021/06/08 15:08:22 model.py:72] Train: Rank: 0, epoch: 1, step: 11, time: 0.625s, train_loss: 30.631641
[INFO 2021/06/08 15:08:22 trainer.py:177] Train: Rank: 0, epoch: 1, step: 11, dataloader time: 0.000s,
[INFO 2021/06/08 15:08:23 model.py:72] Train: Rank: 0, epoch: 1, step: 12, time: 0.632s, train_loss: 30.737951
[INFO 2021/06/08 15:08:23 trainer.py:177] Train: Rank: 0, epoch: 1, step: 12, dataloader time: 0.000s,
[INFO 2021/06/08 15:08:23 model.py:72] Train: Rank: 0, epoch: 1, step: 13, time: 0.630s, train_loss: 48.181465
[INFO 2021/06/08 15:08:23 trainer.py:177] Train: Rank: 0, epoch: 1, step: 13, dataloader time: 0.000s,
[INFO 2021/06/08 15:08:24 model.py:72] Train: Rank: 0, epoch: 1, step: 14, time: 0.635s, train_loss: 31.530159

**Comment by zh794390558** [comment]
2.1 已知一个log_softmax的bug，可以关注下2.1.1版本。目前develop分支最新编译的版本是修复的。如果可以的话，试试develop最新发布的whl包。

**Comment by FrankWhh** [comment]
好的 谢谢
