### ISSUE TITLE
在损失函数中为啥不直接使用nn.CTCLoss(blank=blank, reduction='mean')呢

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleSpeech#660]
为啥不是使用这个`nn.CTCLoss(blank=blank, reduction='mean')`

而是求和`nn.CTCLoss(blank=blank, reduction='sum')`，之后在除以batch size。这样处理不是一样的结果吗？
https://github.com/PaddlePaddle/DeepSpeech/blob/fbe022fdef53ad8bd26791996e43b330849f93fd/deepspeech/modules/loss.py#L52-L54

**Comment by zh794390558** [comment]
if self.batch_average 可以是false

**Comment by yeyupiaoling** [comment]
@zh794390558 我是在想，作者这样的做法是不是又什么特殊的考虑？

**Comment by zh794390558** [comment]
可以不用除B的loss呀。

**Comment by yeyupiaoling** [comment]
那终究是我想多了。
