### ISSUE TITLE
没有推理脚本

### ISSUE THREAD

**Issue by mingo-doer** [PaddlePaddle/PaddleSpeech#663]
在这个文件路径下 /mnt/ASRT/DeepSpeech/examples/librispeech/s0/local 缺少 推理脚本infer.sh
请问在哪里下载预训练模型呢？

**Comment by zh794390558** [comment]
目前还没有提供预训练的模型，推理的脚本和test.sh一样，server封装暂时不做了，python的自己就可以搭。

**Comment by shanmon110** [comment]
推理脚本，infer.py和test.py的使用方式都一样吗？

**Comment by zh794390558** [comment]
2.x里的是一样的。后来删除了infer.py了。两个功能合在一起了，保留了test.py，能计算metric，也打出来了transcript。
