### ISSUE TITLE
升级3070后，python3进程卡住cpu 100%

### ISSUE THREAD

**Issue by hebo1982** [PaddlePaddle/PaddleSpeech#672]
开始测试1080ti，程序正常，环境：
docker运行
paddlepaddle_gpu-1.8.5.post107
cuda 10.1
cdnn 7.5
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 40%   27C    P0    58W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 47%   36C    P0    57W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 49%   30C    P0    54W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:8A:00.0 Off |                  N/A |
| 55%   29C    P0    53W / 250W |      0MiB / 11178MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+

另一台机器升级3070，环境相同，但驱动因为需要升级：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3070    Off  | 00000000:82:00.0 Off |                  N/A |
|  0%   33C    P8     6W / 220W |    303MiB /  7982MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

cuda安装10.1，使用nvcc -V查看：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

程序启动后，就夯住了，python3进程cpu 100%

W0617 04:06:56.153712   194 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 86, Driver API Version: 11.2, Runtime API Version: 10.0
W0617 04:06:56.153888   194 device_context.cc:260] device: 0, cuDNN Version: 7.5.
W0617 04:06:56.512885   194 device_context.h:155] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

![image](https://user-images.githubusercontent.com/5362672/122330705-3f448100-cf66-11eb-84ed-d102eb11fb6f.png)

**Comment by hebo1982** [comment]
很长一段时间后，出现了异常
W0617 04:25:29.168033   194 operator.cc:187] uniform_random raises an exception thrust::system::system_error, parallel_for failed: no kernel image is available for execution on the device
/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tests/test_deepspeech.py", line 4, in <module>
    from easy_deep_speech.deep_speech_api import file_to_transcript
  File "/opt/servers/deeplearning/easy_deep_speech.bak/src/easy_deep_speech/deep_speech_api.py", line 66, in <module>
    exe, infer_program, feeder, log_probs = ds2_model.init_program()
  File "/opt/servers/deeplearning/easy_deep_speech.bak/src/easy_deep_speech/deepspeech2.py", line 391, in init_program
    exe.run(startup_prog)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
RuntimeError: parallel_for failed: no kernel image is available for execution on the device

**Comment by hebo1982** [comment]
@zh794390558 

看着像是cuda版本太低导致的，升级2.1后，model就不能用了。
未来baidu的model还会开放吗？

**Comment by zh794390558** [comment]
这是跑的1.8吗？现在1.x的不在支持了。目前都迁移到2.x了，model之后会release的，不过得等模型稳定后。8k的模型不会release了，用的话从1.8把参数dump成np在用2.x的代码load吧。

**Comment by hebo1982** [comment]
> 这是跑的1.8吗？现在1.x的不在支持了。目前都迁移到2.x了，model之后会release的，不过得等模型稳定后。8k的模型不会release了，用的话从1.8把参数dump成np在用2.x的代码load吧。

是跑的1.8的。
”8k的模型不会release了，用的话从1.8把参数dump成np在用2.x的代码load吧。“
这个有相关的例子么？

**Comment by hebo1982** [comment]
@zh794390558 

是否能通过 paddle1.8 -> onnx，然后 onnx -> paddle2.1

看到有这么两个项目
https://github.com/PaddlePaddle/Paddle2ONNX
https://github.com/PaddlePaddle/X2Paddle

**Comment by zh794390558** [comment]
> @zh794390558
> 
> 是否能通过 paddle1.8 -> onnx，然后 onnx -> paddle2.1
> 
> 看到有这么两个项目
> https://github.com/PaddlePaddle/Paddle2ONNX
> https://github.com/PaddlePaddle/X2Paddle

这个不清楚。

**Comment by zh794390558** [comment]
> > 这是跑的1.8吗？现在1.x的不在支持了。目前都迁移到2.x了，model之后会release的，不过得等模型稳定后。8k的模型不会release了，用的话从1.8把参数dump成np在用2.x的代码load吧。
> 
> 是跑的1.8的。
> ”8k的模型不会release了，用的话从1.8把参数dump成np在用2.x的代码load吧。“
> 这个有相关的例子么？

从infer的例子加载program在找下1.x获取var value的接口吧。

**Comment by hebo1982** [comment]
@zh794390558 

我这边按你说的做了些尝试，现在出现一个问题，无法继续往下走了。
1 将1.8的vars 转成了 np.array，写入到了文件。
2 切换2.1读取文件，通过fluid.io.save_inference_model，将np.array转成model文件。

转np.array，写入文件。
```
    list_vars = infer_program.list_vars()
    vars_list = list(filter(None, list_vars))
    
    vars_array = []
    
    for idx in range(len(vars_list)):
        
        each_var = vars_list[idx]
        if not isinstance(each_var, Parameter):
            continue
        
        var_temp = fluid.global_scope().find_var(each_var.name)
        
        vars_array.append({
            'name': each_var.name,
            'tensor': np.array(var_temp.get_tensor())
        })

    filename = 'finalized_model.sav'
    pickle.dump(vars_array, open(filename, 'wb'))
```

从文件读取np.array，save_inference_model成2.1的model文件。
```
    filename = 'finalized_model.sav'
    loaded_model = pickle.load(open(filename, 'rb'))

    feeded_var_names = []
    target_vars = []
    
    with fluid.dygraph.guard(place):
        for var in loaded_model:
            feeded_var_names.append(var['name'])
            target_vars.append(fluid.dygraph.to_variable(var['tensor']))

    # paddle.enable_static()

    exe = fluid.Executor(fluid.CPUPlace())
    path = "./infer_model"
    fluid.io.save_inference_model(dirname=path, feeded_var_names=feeded_var_names,
        target_vars=target_vars, executor=exe)
```

ValueError: 'target_vars' should be a list of Variable.
提示target_vars 不是Variable list，fluid.dygraph.to_variable转出来的是一个Tensor对象。
怎么将np.array转成Variable?

**Comment by zh794390558** [comment]
2. 直接通过model.set_state_dict来设置参数，参数形式是一个dict即可。不需要fluid.io.save_inference_model。可以看下2.x的模型load部分。

**Comment by hebo1982** [comment]
@zh794390558 
感谢回复！尝试还是不太顺利。

代码如下：
```
    state_dict = pickle.load(open(filename, 'rb')) # 我将1.8版本的读取的vars 保存成了dict，(name: np.array)
    
    for key, param in state_dict.items():
        print(key)
        
    feat_size = 2048
    dict_size = 54
    num_conv_layers = 2
    num_rnn_layers = 3
    rnn_layer_size = 1024
    use_gru = True
    share_rnn_weights = False

    ds2_model = DeepSpeech2InferModel(
        feat_size,
        dict_size,
        num_conv_layers=num_conv_layers,
        num_rnn_layers=num_rnn_layers,
        rnn_size=rnn_layer_size,
        use_gru=use_gru,
        share_rnn_weights=share_rnn_weights)  
    
    ds2_model.set_state_dict(state_dict)  # 很多警告，提示params命名对不上
```

输出:
```
layer_2_forward_batch_norm_bias
layer_0_batch_norm_weight
layer_1_batch_norm_bias
layer_2_reverse_gru_weight
layer_4_forward_batch_norm_moving_variance
layer_3_reverse_batch_norm_bias
layer_0_batch_norm_bias
layer_0_conv2d_weight
layer_0_batch_norm_moving_mean
layer_4_forward_batch_norm_moving_mean
layer_3_reverse_batch_norm_moving_variance
layer_0_batch_norm_moving_variance
layer_4_reverse_gru_bias
layer_1_batch_norm_weight
layer_1_batch_norm_moving_mean
layer_4_reverse_gru_weight
layer_2_forward_batch_norm_moving_variance
layer_2_reverse_fc_weight
layer_3_forward_fc_weight
layer_2_forward_fc_weight
layer_2_reverse_batch_norm_weight
layer_4_reverse_fc_weight
layer_4_reverse_batch_norm_moving_mean
layer_2_reverse_batch_norm_bias
layer_2_reverse_batch_norm_moving_variance
layer_3_reverse_batch_norm_weight
layer_2_forward_gru_weight
layer_2_forward_batch_norm_moving_mean
layer_2_forward_gru_bias
layer_3_reverse_gru_weight
layer_3_forward_batch_norm_weight
layer_4_forward_batch_norm_weight
layer_3_forward_batch_norm_bias
layer_3_forward_batch_norm_moving_mean
layer_3_forward_batch_norm_moving_variance
layer_3_reverse_batch_norm_moving_mean
layer_1_batch_norm_moving_variance
layer_3_forward_gru_weight
layer_1_conv2d_weight
layer_5_fc_weight
layer_2_forward_batch_norm_weight
layer_4_forward_batch_norm_bias
layer_4_forward_gru_bias
layer_4_reverse_batch_norm_bias
layer_4_forward_gru_weight
layer_2_reverse_gru_bias
layer_2_reverse_batch_norm_moving_mean
layer_3_reverse_gru_bias
layer_4_forward_fc_weight
layer_3_reverse_fc_weight
layer_5_fc_bias
layer_3_forward_gru_bias
layer_4_reverse_batch_norm_weight
layer_4_reverse_batch_norm_moving_variance
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_in.conv.weight. encoder.conv.conv_in.conv.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_in.bn.weight. encoder.conv.conv_in.bn.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_in.bn.bias. encoder.conv.conv_in.bn.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_in.bn._mean. encoder.conv.conv_in.bn._mean is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_in.bn._variance. encoder.conv.conv_in.bn._variance is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_stack.0.conv.weight. encoder.conv.conv_stack.0.conv.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_stack.0.bn.weight. encoder.conv.conv_stack.0.bn.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1299: UserWarning: Skip loading for encoder.conv.conv_stack.0.bn.bias. encoder.conv.conv_stack.0.bn.bias is not found in the provided dict.
...类似
```

调试发现DeepSpeech2InferModel的参数名和之前的参数名不一致，无法直接设置。

**Comment by hebo1982** [comment]
2.1的params命名：

```
conv2d_0.w_0
batch_norm2d_0.w_0
batch_norm2d_0.b_0
batch_norm2d_0.w_1
batch_norm2d_0.w_2
conv2d_1.w_0
batch_norm2d_1.w_0
batch_norm2d_1.b_0
batch_norm2d_1.w_1
batch_norm2d_1.w_2
linear_0.w_0
batch_norm1d_0.w_0
batch_norm1d_0.b_0
batch_norm1d_0.w_1
batch_norm1d_0.w_2
linear_1.w_0
batch_norm1d_1.w_0
batch_norm1d_1.b_0
batch_norm1d_1.w_1
batch_norm1d_1.w_2
gru_cell_0.w_0
gru_cell_0.b_0
gru_cell_1.w_0
gru_cell_1.b_0
gru_cell_0.w_0
gru_cell_0.b_0
gru_cell_0.w_0
gru_cell_0.b_0
linear_2.w_0
batch_norm1d_2.w_0
batch_norm1d_2.b_0
batch_norm1d_2.w_1
batch_norm1d_2.w_2
linear_3.w_0
batch_norm1d_3.w_0
batch_norm1d_3.b_0
batch_norm1d_3.w_1
batch_norm1d_3.w_2
gru_cell_2.w_0
gru_cell_2.b_0
gru_cell_3.w_0
gru_cell_3.b_0
gru_cell_2.w_0
gru_cell_2.b_0
gru_cell_2.w_0
gru_cell_2.b_0
linear_4.w_0
batch_norm1d_4.w_0
batch_norm1d_4.b_0
batch_norm1d_4.w_1
batch_norm1d_4.w_2
linear_5.w_0
batch_norm1d_5.w_0
batch_norm1d_5.b_0
batch_norm1d_5.w_1
batch_norm1d_5.w_2
gru_cell_4.w_0
gru_cell_4.b_0
gru_cell_5.w_0
gru_cell_5.b_0
gru_cell_4.w_0
gru_cell_4.b_0
gru_cell_4.w_0
gru_cell_4.b_0
linear_6.w_0
linear_6.b_0
```

**Comment by zh794390558** [comment]
只需要把key对应替换成2.1的名字即可。欢迎提供导出后的模型和代码。

**Comment by hebo1982** [comment]
@zh794390558 
对比了一下参数，没什么思路配对。
看着两个版本的网络架构都不是一样的。

2.1 66组参数命名和shape
```
conv2d_0.w_0 (32, 1, 41, 11)
batch_norm2d_0.w_0 (32,)
batch_norm2d_0.b_0 (32,)
batch_norm2d_0.w_1 (32,)
batch_norm2d_0.w_2 (32,)
conv2d_1.w_0 (32, 32, 21, 11)
batch_norm2d_1.w_0 (32,)
batch_norm2d_1.b_0 (32,)
batch_norm2d_1.w_1 (32,)
batch_norm2d_1.w_2 (32,)
linear_0.w_0 (16384, 3072)
batch_norm1d_0.w_0 (3072,)
batch_norm1d_0.b_0 (3072,)
batch_norm1d_0.w_1 (3072,)
batch_norm1d_0.w_2 (3072,)
linear_1.w_0 (16384, 3072)
batch_norm1d_1.w_0 (3072,)
batch_norm1d_1.b_0 (3072,)
batch_norm1d_1.w_1 (3072,)
batch_norm1d_1.w_2 (3072,)
gru_cell_0.w_0 (3072, 1024)
gru_cell_0.b_0 (3072,)
gru_cell_1.w_0 (3072, 1024)
gru_cell_1.b_0 (3072,)
gru_cell_0.w_0 (3072, 1024)
gru_cell_0.b_0 (3072,)
gru_cell_0.w_0 (3072, 1024)
gru_cell_0.b_0 (3072,)
linear_2.w_0 (2048, 3072)
batch_norm1d_2.w_0 (3072,)
batch_norm1d_2.b_0 (3072,)
batch_norm1d_2.w_1 (3072,)
batch_norm1d_2.w_2 (3072,)
linear_3.w_0 (2048, 3072)
batch_norm1d_3.w_0 (3072,)
batch_norm1d_3.b_0 (3072,)
batch_norm1d_3.w_1 (3072,)
batch_norm1d_3.w_2 (3072,)
gru_cell_2.w_0 (3072, 1024)
gru_cell_2.b_0 (3072,)
gru_cell_3.w_0 (3072, 1024)
gru_cell_3.b_0 (3072,)
gru_cell_2.w_0 (3072, 1024)
gru_cell_2.b_0 (3072,)
gru_cell_2.w_0 (3072, 1024)
gru_cell_2.b_0 (3072,)
linear_4.w_0 (2048, 3072)
batch_norm1d_4.w_0 (3072,)
batch_norm1d_4.b_0 (3072,)
batch_norm1d_4.w_1 (3072,)
batch_norm1d_4.w_2 (3072,)
linear_5.w_0 (2048, 3072)
batch_norm1d_5.w_0 (3072,)
batch_norm1d_5.b_0 (3072,)
batch_norm1d_5.w_1 (3072,)
batch_norm1d_5.w_2 (3072,)
gru_cell_4.w_0 (3072, 1024)
gru_cell_4.b_0 (3072,)
gru_cell_5.w_0 (3072, 1024)
gru_cell_5.b_0 (3072,)
gru_cell_4.w_0 (3072, 1024)
gru_cell_4.b_0 (3072,)
gru_cell_4.w_0 (3072, 1024)
gru_cell_4.b_0 (3072,)
linear_6.w_0 (2048, 54)
linear_6.b_0 (54,)
```

1.8.5 54组参数命名和shape
```
layer_2_forward_batch_norm_bias (3072,)
layer_0_batch_norm_weight (32,)
layer_1_batch_norm_bias (32,)
layer_2_reverse_gru_weight (1024, 3072)
layer_4_forward_batch_norm_moving_variance (3072,)
layer_3_reverse_batch_norm_bias (3072,)
layer_0_batch_norm_bias (32,)
layer_0_conv2d_weight (32, 1, 41, 11)
layer_0_batch_norm_moving_mean (32,)
layer_4_forward_batch_norm_moving_mean (3072,)
layer_3_reverse_batch_norm_moving_variance (3072,)
layer_0_batch_norm_moving_variance (32,)
layer_4_reverse_gru_bias (1, 3072)
layer_1_batch_norm_weight (32,)
layer_1_batch_norm_moving_mean (32,)
layer_4_reverse_gru_weight (1024, 3072)
layer_2_forward_batch_norm_moving_variance (3072,)
layer_2_reverse_fc_weight (1312, 3072)
layer_3_forward_fc_weight (2048, 3072)
layer_2_forward_fc_weight (1312, 3072)
layer_2_reverse_batch_norm_weight (3072,)
layer_4_reverse_fc_weight (2048, 3072)
layer_4_reverse_batch_norm_moving_mean (3072,)
layer_2_reverse_batch_norm_bias (3072,)
layer_2_reverse_batch_norm_moving_variance (3072,)
layer_3_reverse_batch_norm_weight (3072,)
layer_2_forward_gru_weight (1024, 3072)
layer_2_forward_batch_norm_moving_mean (3072,)
layer_2_forward_gru_bias (1, 3072)
layer_3_reverse_gru_weight (1024, 3072)
layer_3_forward_batch_norm_weight (3072,)
layer_4_forward_batch_norm_weight (3072,)
layer_3_forward_batch_norm_bias (3072,)
layer_3_forward_batch_norm_moving_mean (3072,)
layer_3_forward_batch_norm_moving_variance (3072,)
layer_3_reverse_batch_norm_moving_mean (3072,)
layer_1_batch_norm_moving_variance (32,)
layer_3_forward_gru_weight (1024, 3072)
layer_1_conv2d_weight (32, 32, 21, 11)
layer_5_fc_weight (2048, 29)
layer_2_forward_batch_norm_weight (3072,)
layer_4_forward_batch_norm_bias (3072,)
layer_4_forward_gru_bias (1, 3072)
layer_4_reverse_batch_norm_bias (3072,)
layer_4_forward_gru_weight (1024, 3072)
layer_2_reverse_gru_bias (1, 3072)
layer_2_reverse_batch_norm_moving_mean (3072,)
layer_3_reverse_gru_bias (1, 3072)
layer_4_forward_fc_weight (2048, 3072)
layer_3_reverse_fc_weight (2048, 3072)
layer_5_fc_bias (29,)
layer_3_forward_gru_bias (1, 3072)
layer_4_reverse_batch_norm_weight (3072,)
layer_4_reverse_batch_norm_moving_variance (3072,)
```

**Comment by zh794390558** [comment]
可以参照下面的图片找下思路

![image](https://user-images.githubusercontent.com/3038472/123788438-96efce80-d90e-11eb-9550-da2ef6346cde.png)
