### ISSUE TITLE
训练的过程中，从第二个epoch开始，lr=0.00000000,train_lossp徘徊在15左右

### ISSUE THREAD

**Issue by yhz5256** [PaddlePaddle/PaddleSpeech#675]
[INFO 2021/06/19 16:01:34 model.py:61] Train: Rank: 0, epoch: 1, step: 5310, batch : 1559/1876, lr: 0.00000000, data time: 0.000s, train time: 3.019s, batch size: 64, train_loss: 16.030918
[INFO 2021/06/19 16:01:37 model.py:61] Train: Rank: 0, epoch: 1, step: 5311, batch : 1560/1876, lr: 0.00000000, data time: 0.000s, train time: 2.954s, batch size: 64, train_loss: 15.383665
[INFO 2021/06/19 16:01:40 model.py:61] Train: Rank: 0, epoch: 1, step: 5312, batch : 1561/1876, lr: 0.00000000, data time: 0.000s, train time: 3.016s, batch size: 64, train_loss: 17.136696
[INFO 2021/06/19 16:01:43 model.py:61] Train: Rank: 0, epoch: 1, step: 5313, batch : 1562/1876, lr: 0.00000000, data time: 0.001s, train time: 2.932s, batch size: 64, train_loss: 16.347980
[INFO 2021/06/19 16:01:46 model.py:61] Train: Rank: 0, epoch: 1, step: 5314, batch : 1563/1876, lr: 0.00000000, data time: 0.000s, train time: 3.120s, batch size: 64, train_loss: 12.675243
[INFO 2021/06/19 16:01:49 model.py:61] Train: Rank: 0, epoch: 1, step: 5315, batch : 1564/1876, lr: 0.00000000, data time: 0.000s, train time: 3.011s, batch size: 64, train_loss: 15.479199
[INFO 2021/06/19 16:01:52 model.py:61] Train: Rank: 0, epoch: 1, step: 5316, batch : 1565/1876, lr: 0.00000000, data time: 0.000s, train time: 2.994s, batch size: 64, train_loss: 16.016537
[INFO 2021/06/19 16:01:55 model.py:61] Train: Rank: 0, epoch: 1, step: 5317, batch : 1566/1876, lr: 0.00000000, data time: 0.001s, train time: 2.938s, batch size: 64, train_loss: 14.940930
[INFO 2021/06/19 16:01:58 model.py:61] Train: Rank: 0, epoch: 1, step: 5318, batch : 1567/1876, lr: 0.00000000, data time: 0.000s, train time: 2.984s, batch size: 64, train_loss: 16.664011
[INFO 2021/06/19 16:02:01 model.py:61] Train: Rank: 0, epoch: 1, step: 5319, batch : 1568/1876, lr: 0.00000000, data time: 0.001s, train time: 2.917s, batch size: 64, train_loss: 15.314414
[INFO 2021/06/19 16:02:04 model.py:61] Train: Rank: 0, epoch: 1, step: 5320, batch : 1569/1876, lr: 0.00000000, data time: 0.000s, train time: 3.067s, batch size: 64, train_loss: 19.256882
[INFO 2021/06/19 16:02:07 model.py:61] Train: Rank: 0, epoch: 1, step: 5321, batch : 1570/1876, lr: 0.00000000, data time: 0.001s, train time: 3.073s, batch size: 64, train_loss: 17.577530
[INFO 2021/06/19 16:02:10 model.py:61] Train: Rank: 0, epoch: 1, step: 5322, batch : 1571/1876, lr: 0.00000000, data time: 0.000s, train time: 3.058s, batch size: 64, train_loss: 13.793201
[INFO 2021/06/19 16:02:13 model.py:61] Train: Rank: 0, epoch: 1, step: 5323, batch : 1572/1876, lr: 0.00000000, data time: 0.001s, train time: 2.957s, batch size: 64, train_loss: 17.981644
[INFO 2021/06/19 16:02:16 model.py:61] Train: Rank: 0, epoch: 1, step: 5324, batch : 1573/1876, lr: 0.00000000, data time: 0.001s, train time: 3.084s, batch size: 64, train_loss: 16.675428
[INFO 2021/06/19 16:02:19 model.py:61] Train: Rank: 0, epoch: 1, step: 5325, batch : 1574/1876, lr: 0.00000000, data time: 0.000s, train time: 3.019s, batch size: 64, train_loss: 16.754436
[INFO 2021/06/19 16:02:22 model.py:61] Train: Rank: 0, epoch: 1, step: 5326, batch : 1575/1876, lr: 0.00000000, data time: 0.000s, train time: 3.084s, batch size: 64, train_loss: 12.173172
[INFO 2021/06/19 16:02:25 model.py:61] Train: Rank: 0, epoch: 1, step: 5327, batch : 1576/1876, lr: 0.00000000, data time: 0.000s, train time: 3.141s, batch size: 64, train_loss: 17.882875
[INFO 2021/06/19 16:02:28 model.py:61] Train: Rank: 0, epoch: 1, step: 5328, batch : 1577/1876, lr: 0.00000000, data time: 0.000s, train time: 2.959s, batch size: 64, train_loss: 14.933475
[INFO 2021/06/19 16:02:32 model.py:61] Train: Rank: 0, epoch: 1, step: 5329, batch : 1578/1876, lr: 0.00000000, data time: 0.001s, train time: 3.190s, batch size: 64, train_loss: 16.997902
[INFO 2021/06/19 16:02:34 model.py:61] Train: Rank: 0, epoch: 1, step: 5330, batch : 1579/1876, lr: 0.00000000, data time: 0.000s, train time: 2.941s, batch size: 64, train_loss: 16.430275
[INFO 2021/06/19 16:02:38 model.py:61] Train: Rank: 0, epoch: 1, step: 5331, batch : 1580/1876, lr: 0.00000000, data time: 0.000s, train time: 3.125s, batch size: 64, train_loss: 16.318769
[INFO 2021/06/19 16:02:41 model.py:61] Train: Rank: 0, epoch: 1, step: 5332, batch : 1581/1876, lr: 0.00000000, data time: 0.000s, train time: 3.028s, batch size: 64, train_loss: 18.299578
[INFO 2021/06/19 16:02:44 model.py:61] Train: Rank: 0, epoch: 1, step: 5333, batch : 1582/1876, lr: 0.00000000, data time: 0.000s, train time: 3.112s, batch size: 64, train_loss: 14.934775
[INFO 2021/06/19 16:02:47 model.py:61] Train: Rank: 0, epoch: 1, step: 5334, batch : 1583/1876, lr: 0.00000000, data time: 0.001s, train time: 3.093s, batch size: 64, train_loss: 17.445869
[INFO 2021/06/19 16:02:50 model.py:61] Train: Rank: 0, epoch: 1, step: 5335, batch : 1584/1876, lr: 0.00000000, data time: 0.001s, train time: 2.957s, batch size: 64, train_loss: 18.386488
[INFO 2021/06/19 16:02:53 model.py:61] Train: Rank: 0, epoch: 1, step: 5336, batch : 1585/1876, lr: 0.00000000, data time: 0.000s, train time: 2.978s, batch size: 64, train_loss: 15.902421
[INFO 2021/06/19 16:02:56 model.py:61] Train: Rank: 0, epoch: 1, step: 5337, batch : 1586/1876, lr: 0.00000000, data time: 0.000s, train time: 2.977s, batch size: 64, train_loss: 12.690172
[INFO 2021/06/19 16:02:59 model.py:61] Train: Rank: 0, epoch: 1, step: 5338, batch : 1587/1876, lr: 0.00000000, data time: 0.000s, train time: 3.012s, batch size: 64, train_loss: 13.637624
[INFO 2021/06/19 16:03:02 model.py:61] Train: Rank: 0, epoch: 1, step: 5339, batch : 1588/1876, lr: 0.00000000, data time: 0.001s, train time: 3.089s, batch size: 64, train_loss: 15.179820
[INFO 2021/06/19 16:03:05 model.py:61] Train: Rank: 0, epoch: 1, step: 5340, batch : 1589/1876, lr: 0.00000000, data time: 0.000s, train time: 2.981s, batch size: 64, train_loss: 16.540697
[INFO 2021/06/19 16:03:08 model.py:61] Train: Rank: 0, epoch: 1, step: 5341, batch : 1590/1876, lr: 0.00000000, data time: 0.001s, train time: 3.051s, batch size: 64, train_loss: 16.708530
[INFO 2021/06/19 16:03:11 model.py:61] Train: Rank: 0, epoch: 1, step: 5342, batch : 1591/1876, lr: 0.00000000, data time: 0.000s, train time: 3.056s, batch size: 64, train_loss: 14.384456
[INFO 2021/06/19 16:03:14 model.py:61] Train: Rank: 0, epoch: 1, step: 5343, batch : 1592/1876, lr: 0.00000000, data time: 0.000s, train time: 2.957s, batch size: 64, train_loss: 15.726199
[INFO 2021/06/19 16:03:17 model.py:61] Train: Rank: 0, epoch: 1, step: 5344, batch : 1593/1876, lr: 0.00000000, data time: 0.000s, train time: 3.002s, batch size: 64, train_loss: 14.959470
[INFO 2021/06/19 16:03:20 model.py:61] Train: Rank: 0, epoch: 1, step: 5345, batch : 1594/1876, lr: 0.00000000, data time: 0.001s, train time: 3.075s, batch size: 64, train_loss: 15.619622
[INFO 2021/06/19 16:03:23 model.py:61] Train: Rank: 0, epoch: 1, step: 5346, batch : 1595/1876, lr: 0.00000000, data time: 0.000s, train time: 3.058s, batch size: 64, train_loss: 15.734484
[INFO 2021/06/19 16:03:26 model.py:61] Train: Rank: 0, epoch: 1, step: 5347, batch : 1596/1876, lr: 0.00000000, data time: 0.000s, train time: 3.292s, batch size: 64, train_loss: 16.957069
[INFO 2021/06/19 16:03:29 model.py:61] Train: Rank: 0, epoch: 1, step: 5348, batch : 1597/1876, lr: 0.00000000, data time: 0.001s, train time: 3.123s, batch size: 64, train_loss: 17.215548
[INFO 2021/06/19 16:03:32 model.py:61] Train: Rank: 0, epoch: 1, step: 5349, batch : 1598/1876, lr: 0.00000000, data time: 0.000s, train time: 3.005s, batch size: 64, train_loss: 16.323082
[INFO 2021/06/19 16:03:36 model.py:61] Train: Rank: 0, epoch: 1, step: 5350, batch : 1599/1876, lr: 0.00000000, data time: 0.000s, train time: 3.110s, batch size: 64, train_loss: 16.539949
[INFO 2021/06/19 16:03:39 model.py:61] Train: Rank: 0, epoch: 1, step: 5351, batch : 1600/1876, lr: 0.00000000, data time: 0.001s, train time: 3.086s, batch size: 64, train_loss: 15.122108
[INFO 2021/06/19 16:03:42 model.py:61] Train: Rank: 0, epoch: 1, step: 5352, batch : 1601/1876, lr: 0.00000000, data time: 0.000s, train time: 3.012s, batch size: 64, train_loss: 14.657473
[INFO 2021/06/19 16:03:45 model.py:61] Train: Rank: 0, epoch: 1, step: 5353, batch : 1602/1876, lr: 0.00000000, data time: 0.001s, train time: 3.190s, batch size: 64, train_loss: 18.860703
[INFO 2021/06/19 16:03:48 model.py:61] Train: Rank: 0, epoch: 1, step: 5354, batch : 1603/1876, lr: 0.00000000, data time: 0.000s, train time: 3.012s, batch size: 64, train_loss: 18.484442
[INFO 2021/06/19 16:03:51 model.py:61] Train: Rank: 0, epoch: 1, step: 5355, batch : 1604/1876, lr: 0.00000000, data time: 0.000s, train time: 3.143s, batch size: 64, train_loss: 18.698807
[INFO 2021/06/19 16:03:54 model.py:61] Train: Rank: 0, epoch: 1, step: 5356, batch : 1605/1876, lr: 0.00000000, data time: 0.000s, train time: 3.029s, batch size: 64, train_loss: 15.407411
[INFO 2021/06/19 16:03:57 model.py:61] Train: Rank: 0, epoch: 1, step: 5357, batch : 1606/1876, lr: 0.00000000, data time: 0.000s, train time: 3.219s, batch size: 64, train_loss: 16.926647

**Comment by zh794390558** [comment]
这是哪个模型？什么配置？什么数据？

**Comment by yhz5256** [comment]
> 这是哪个模型？什么配置？什么数据？

环境是paddlepaddle2.1+cuda10.1 ，训练数据集是aishell，直接跑的example/aishell/s0/run.sh脚本
配置如下:
  augmentation_config: conf/augmentation.json
  batch_size: 64
  delta_delta: False
  dither: 1.0
  feat_dim: None
  keep_transcription_text: False
  max_freq: None
  mean_std_filepath: data/mean_std.json
  n_fft: None
  num_workers: 0
  random_seed: 0
  shuffle_method: batch_shuffle
  sortagrad: True
  specgram_type: linear
  spm_model_prefix: None
  stride_ms: 10.0
  target_dB: -20
  target_sample_rate: 16000
  unit_type: char
  use_dB_normalization: True
  vocab_filepath: data/vocab.txt
  window_ms: 20.0
data:
  dev_manifest: data/manifest.dev
  manifest: 
  max_input_len: 27.0
  max_output_input_ratio: inf
  max_output_len: inf
  min_input_len: 0.0
  min_output_input_ratio: 0.0
  min_output_len: 0.0
  test_manifest: data/manifest.test
  train_manifest: data/manifest.train
decoding:
  alpha: 1.9
  batch_size: 128
  beam_size: 300
  beta: 5.0
  cutoff_prob: 0.99
  cutoff_top_n: 40
  decoding_method: ctc_beam_search
  error_rate_type: cer
  lang_model_path: data/lm/zh_giga.no_cna_cmn.prune01244.klm
  num_proc_bsearch: 10
model:
  num_conv_layers: 2
  num_rnn_layers: 3
  rnn_layer_size: 1024
  share_rnn_weights: False
  use_gru: True
training:
  global_grad_clip: 3.0
  log_interval: 100
  lr: 0.002
  lr_decay: 0.83
  n_epoch: 50
  weight_decay: 1e-06
vocab_filepath: data/vocab.txt
vocab_filepath: data/vocab.txt

**Comment by zh794390558** [comment]
先用4卡训练下，如果还不行回退paddle到2.0.2再试下。
