### ISSUE TITLE
v1.8.5 ctc_beam_search en8k [ctc_beam_search_decoder.cpp:42] FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary

### ISSUE THREAD

**Issue by lightsailpro** [PaddlePaddle/PaddleSpeech#681]
I am getting error with version 1.8.5, "ctc_beam_search" with en8k model. The "ctc_speedy" decoder works fine. Is there any workaround/fix for "ctc_beam_search"? Thanks

[INFO 2021-06-22 08:14:12,183 model.py:475] begin to initialize the external scorer for decoding
[INFO 2021-06-22 08:15:51,802 model.py:482] language model: is_character_based = 0, max_order = 5, dict_size = 400000
[INFO 2021-06-22 08:15:51,911 model.py:486] end initializing scorer
[INFO 2021-06-22 08:15:51,912 infer.py:115] start inference ...
finish initing model from pretrained params from models/baidu_en8k
[ctc_beam_search_decoder.cpp:42] FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary
[ctc_beam_search_decoder.cpp:42] FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary
corrupted double-linked list

CUDA_VISIBLE_DEVICES=0 \
python3 -u infer.py \
--num_samples=10 \
--beam_size=500 \
--num_proc_bsearch=5 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=1024 \
--alpha=1.4 \
--beta=0.35 \
--cutoff_prob=1.0 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=True \
--share_rnn_weights=False \
--infer_manifest='data/tiny/manifest.test-clean' \
--mean_std_path='models/baidu_en8k/mean_std.npz' \
--vocab_path='models/baidu_en8k/vocab.txt' \
--model_path='models/baidu_en8k' \
--lang_model_path='models/lm/common_crawl_00.prune01111.trie.klm' \
--decoding_method='ctc_beam_search' \
--error_rate_type='wer' \
--specgram_type='linear'

**Comment by zh794390558** [comment]
1.x不在支持了。出错问题在`[ctc_beam_search_decoder.cpp:42] FATAL: "(probs_seq[i].size()) == (vocabulary.size())" check failed. The shape of probs_seq does not match with the shape of the vocabulary`，check下吧。

**Comment by lightsailpro** [comment]
I took that section of validation code out, recompiled and reinstalled. The error went away and the ctc_beam_search works fine without the validation.
