### ISSUE TITLE
python3.7启动服务出现问题

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleSpeech#707]
![image](https://user-images.githubusercontent.com/57654726/126030582-1c77d30b-2b2d-430b-b783-93a1171c55c1.png)
![image](https://user-images.githubusercontent.com/57654726/126030596-583256ea-6449-4d0b-a09f-5169a5d561b8.png)
sercer可以正常启动，但是本地音频录制就初选问题。

**Comment by zh794390558** [comment]
可能wav不是float类型的。

**Comment by xialei2821212670** [comment]
我该如何进行修改，修改demo_clinet？

**Comment by zh794390558** [comment]
用aishell里wav直接发送，看server能正常工作不。可以的话，就排查下录音和aishell wav的差异吧。

**Comment by xialei2821212670** [comment]
我启动服务默认有部分aishell的音频，控制台打印了。我发现是demo_clinet.py里面出现错误、
![image](https://user-images.githubusercontent.com/57654726/126145502-5de668d7-d71b-49fe-a8e4-585f79cafff8.png)
少了一个单词b，sent = b''.join(data_list)

**Comment by zh794390558** [comment]
嗯，应该是3.7默认str是unicode吧
