### ISSUE TITLE
导出模型报错，deepspeech.utils.checkpoint' has no attribute 'load_parameters'

### ISSUE THREAD

**Issue by shanmon110** [PaddlePaddle/PaddleSpeech#710]
File "/home/lz/DeepSpeech/deepspeech/models/deepspeech2.py", line 225, in from_pretrained
    infos = checkpoint.load_parameters(
AttributeError: module 'deepspeech.utils.checkpoint' has no attribute 'load_parameters'
Failed in export!

导出模型的时候报错，但是deepspeech.utils.checkpoint有load_parameters这个函数，怎么回事？

**Comment by zh794390558** [comment]
需要pull下develop的最新代码，之前修改的时候是 _load_parameters。

**Comment by zh794390558** [comment]
https://github.com/PaddlePaddle/DeepSpeech/pull/714 这个修复了
