### ISSUE TITLE
如何应用百度发布的“BaiduEN8k Model”模型？

### ISSUE THREAD

**Issue by shanmon110** [PaddlePaddle/PaddleSpeech#715]
https://www.paddlepaddle.org.cn/modelbasedetail/DeepSpeech2#%E5%8F%91%E5%B8%83%E6%A8%A1%E5%9E%8B

这里提供里一些发布模型，如何应用？

**Comment by zh794390558** [comment]
这是1.8的分支的代码，可以切换使用。或者自己转成2.x的使用。

**Comment by zh794390558** [comment]
可以参考 https://github.com/PaddlePaddle/DeepSpeech/issues/672 转换参数，也欢迎贡献转换后的参数。

**Comment by zh794390558** [comment]
有时间了，我们考虑下转参数的事情。

**Comment by shanmon110** [comment]
可以提供1.8分支代码的源码吗？我的邮箱cszhe.li@polyu.edu.hk, 感谢
