### ISSUE TITLE
如何添加自定义热词？

### ISSUE THREAD

**Issue by shanmon110** [PaddlePaddle/PaddleSpeech#716]
如何在此代码基础上添加热词，提高热词表的识别准确率？

**Comment by zh794390558** [comment]
热词需要修改现有的CTCDecoder的解码流程，在解码过程中加入hotword的分数，修正解码路径得分。目前暂时不支持，后续开发基于wfst的解码会考虑添加。

**Comment by tcexeexe** [comment]
> 热词需要修改现有的CTCDecoder的解码流程，在解码过程中加入hotword的分数，修正解码路径得分。目前暂时不支持，后续开发基于wfst的解码会考虑添加。
你好，想问下现在支持添加热词了吗？

**Comment by jeffzhengye** [comment]
@tcexeexe  这个功能现在支持了没有啊？

**Comment by ericg108** [comment]
> 

@zh794390558 请问现在这个支持了吗
