### ISSUE TITLE
Paddlehub部署

### ISSUE THREAD

**Issue by FrankWhh** [PaddlePaddle/PaddleSpeech#721]
尝试在Windows环境下部署，修改好modul.py文件后用hub install DeepSpeech，显示no module swig-decoder，不知该怎么解决，有成功过的吗？

**Comment by zh794390558** [comment]
我这里没有试过hub的，swig-decoder可以参看https://github.com/PaddlePaddle/DeepSpeech/blob/develop/setup.sh#L46 安装

**Comment by FrankWhh** [comment]
这个看过，安装需要bash, swig命令，Windows本身不支持
