### ISSUE TITLE
no download_model.sh in develop and release/v2.1 branch

### ISSUE THREAD

**Issue by wfchair** [PaddlePaddle/PaddleSpeech#736]
Under DeepSpeech/examples/aishell/s0/local/, I cannot find download_model.sh in develop and release/v2.1 branch, but server.sh still uses it.

**Comment by zh794390558** [comment]
多谢反馈，这部分会删除。2.x目前没有提供模型下载。

**Comment by wfchair** [comment]
谢谢回复。我想用2.1 pre-trained model，试验一下speech to text的效果。
该怎么做？有step by step manual吗？我现在尝试跑
/DeepSpeech/examples/aishell/s0/local/server.sh
成功的话，可以试验speech to text吗？

**Comment by zh794390558** [comment]
没有看明白想怎么测试？test.sh 可以测试指标的。server.sh 不要用了，那个是1.x遗留下来的。 测试语音可以自己造个manifest的文件测试。

**Comment by wfchair** [comment]
提交一个wav音频文件，得到其对应的text；
或者直接用microphone交互，得到实时的text。

**Comment by zh794390558** [comment]
用server.py 和 send.py吧。可以离线操作的。

**Comment by wfchair** [comment]
> 用server.py 和 send.py吧。可以离线操作的。

能 带上参数 说得具体些吗？尤其是我的机器spec低，自己train不现实，想用pretrain好的model，该如何操作？谢谢。
