### ISSUE TITLE
2.1中如何用已训练的模型，加入数据继续训练呢

### ISSUE THREAD

**Issue by wonder2025** [PaddlePaddle/PaddleSpeech#738]

**Comment by zh794390558** [comment]
新数据生成manifest，从原来的ckpt load后继续训练。

**Comment by wonder2025** [comment]
> 新数据生成manifest，从原来的ckpt load后继续训练。

请问代码里面改哪里呢，没找到地方

**Comment by zh794390558** [comment]
配置文件修改manifest的路径就可以了，训练时指定之前的ckpt路径，默认load最后一次的ckpt。

**Comment by wonder2025** [comment]
> 配置文件修改manifest的路径就可以了，训练时指定之前的ckpt路径，默认load最后一次的ckpt。

貌似上一个数据集产生的 vocab.txt，下一个数据集只能使用相同的该文件

**Comment by zh794390558** [comment]
是的，不能乱的。
