### ISSUE TITLE
如何使用baidu_cn1.2k_model_fluid.tar.gz模型做识别？

### ISSUE THREAD

**Issue by leesky20116** [PaddlePaddle/PaddleSpeech#758]
我看到github上的DeepSpeech能够支持python3.7和paddlepaddle 2.x，请问我要用baidu_cn1.2k_model_fluid.tar.gz模型做语音识别用几个文件，说明文档并没有说明，谢谢！

**Comment by zh794390558** [comment]
那个是1.x的model，应该不能直接用的，需要转换下参看 https://github.com/PaddlePaddle/DeepSpeech/issues/672
