### ISSUE TITLE
server.py里引用路径错误

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleSpeech#770]
**Describe the bug**
deepspeech/exps/deepspeech2/bin/deploy/server.py 里面引用的是 from deepspeech.models.deepspeech2 import DeepSpeech2Model，实际应该是 deepspeech.models.ds2，建议更新代码。

**To Reproduce**
1.  查看代码  (日期：2021-8-19)
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deepspeech/exps/deepspeech2/bin/deploy/server.py#L24
引用的是deepspeech2
2. 查看被引用的目录 https://github.com/PaddlePaddle/DeepSpeech/tree/develop/deepspeech/models
子目录只有 ds2

**Expected behavior**
server.py的引用应该跟代码一致，其他地方也可能有类似问题。

**Comment by zh794390558** [comment]
Thx，我们排查下。
