### ISSUE TITLE
如何用1.8版本微调“BaiduEN8k Model”模型？

### ISSUE THREAD

**Issue by shanmon110** [PaddlePaddle/PaddleSpeech#778]
我用1.8版本的代码跑通了测试的，但是目前我想用我自己的数据微调，但是没有提供脚本。我自己写的时候参数对不上。请问如何用1.8版本微调“BaiduEN8k Model”模型？

Many thanks for your help

**Comment by zh794390558** [comment]
可以参考这个，https://github.com/PaddlePaddle/DeepSpeech/issues/530。issue里搜finetune也能找到一些相关的。
