### ISSUE TITLE
insufficient shared memory

### ISSUE THREAD

**Issue by liweigu** [PaddlePaddle/PaddleSpeech#790]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**
在Docker下训练一段时间报错：
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough

**To Reproduce**
1. 在Docker下训练一段时间（Train: Rank: 0, epoch: 0, step: 831, batch : 832/1876,）报共享内存不足的错。
2. 在 deepspeech2.yaml 里添加以下内容后，仍然报错：
loader:
  use_shared_memory: False
deepspeech2.yaml 好像不能设置不使用共享内存。

**Expected behavior**
期望能持续训练，不报共享内存的错。

**Screenshots**

** Environment (please complete the following information):**
 - OS: Ubuntu 20.04, Docker version 19.03.9
 - GCC/G++ Version: Docker内(Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
 - Python Version: 3.8.10
 - PaddlePaddle Version: 2.1.2
 - Model Version: 从头训练
 - GPU/DRIVER Informationo: NVIDIA-SMI 460.91.03, Driver Version: 460.91.03, NVIDIA UNIX x86_64 Kernel Module  460.91.03
 - CUDA/CUDNN Version: cuda-11.2

**Comment by zh794390558** [comment]
```
nvidia-docker run --net=host --ipc=host -it --rm  -v $PWD:/workspace --name=dev registry.baidubce.com/paddlepaddle/paddle:2.0.0-gpu-cuda10.2-cudnn7 /bin/bash
```

**Comment by liweigu** [comment]
--ipc=host -v $PWD/workspace:/workspace 加上后没有出现共享内存不足了。
