### ISSUE TITLE
Trying Live Demo with Your Own Voice.

### ISSUE THREAD

**Issue by qjaden** [PaddlePaddle/PaddleSpeech#797]
根据给定的[教程](https://github.com/PaddlePaddle/DeepSpeech/blob/develop/doc/src/server.md)执行相关启动ASR服务端引擎。

但是查看了server.sh源码发现，必须制定checkpoint_path，否则退出。
相关代码如下：
`if [[ $# != 1 ]];then
   echo "usage: $1 checkpoint_path"
   exit -1
fi`

但是根据教程是可以省略checkpoint_path参数的。

其次，使用预训练模型（pre-trained Chinese model (trained with AISHELL1)）进行推理需要data/manifest.test文件。使用预训练模型还需要先训练一遍吗。。。（这不合理）。此处推测是相关教程忘记修改了。

**Comment by zh794390558** [comment]
是的，这部分基本不维护了。之后都用c++做上线了。
预训练模型是指在推理时需要一个训好的模型在，才能推理。

**Comment by qjaden** [comment]
> 是的，这部分基本不维护了。之后都用c++做上线了。
> 预训练模型是指在推理时需要一个训好的模型在，才能推理。

已经下载了zh_giga.no_cna_cmn.prune01244.klm（2.75G）预训练模型，但是没办法直接调用。

想请教一下c++做上线这个功能目前有开源吗？

**Comment by zh794390558** [comment]
zh_giga.no_cna_cmn.prune01244.klm 这个是语言模型，还需要AM才行。 c++ 还没有开源。
