### ISSUE TITLE
bash run.sh 出现报错

### ISSUE THREAD

**Issue by maomaoyu2** [PaddlePaddle/PaddleSpeech#825]
![微信截图_20210914175845](https://user-images.githubusercontent.com/30387771/133237615-7ab1ebc0-6731-4cf6-bae6-279680ad86fe.png)

**Comment by zh794390558** [comment]
这个需要安装2.2.0RC的版本，目前还没有release，可以先用develop的版本。2.2.0RC预计17号后release。
