### ISSUE TITLE
运行例子出错

### ISSUE THREAD

**Issue by qq1440837150** [PaddlePaddle/PaddleSpeech#830]
checkpoint name deepspeech2
  File "/DeepSpeech/examples/dataset/librispeech/librispeech.py", line 122
    print(f"{subset}:", file=f)
                     ^
SyntaxError: invalid syntax
Prepare LibriSpeech failed. Terminated.
![image](https://user-images.githubusercontent.com/31851742/133457098-56babf41-e985-4ec1-8d71-0094f6743f38.png)

**Comment by zh794390558** [comment]
请按照install的命令安装，并source tools/venv/bin/activate 后使用。
