### ISSUE TITLE
kenlm训练得到的模型在哪里可以下载呢

### ISSUE THREAD

**Issue by expresschen** [PaddlePaddle/PaddleSpeech#832]
For support and discussions, please use our [Discourse forums](https://github.com/PaddlePaddle/DeepSpeech/discussions).

If you've found a bug then please create an issue with the following information:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - GCC/G++ Version [e.g. 8.3]
 - Python Version [e.g. 3.7]
 - PaddlePaddle Version [e.g. 2.0.0]
 - Model Version [e.g. 2.0.0]
 - GPU/DRIVER Informationo [e.g. Tesla V100-SXM2-32GB/440.64.00]
 - CUDA/CUDNN Version [e.g. cuda-10.2]
 - MKL Version
- TensorRT Version

**Additional context**

**Comment by zh794390558** [comment]
这是是release的model，lm 也在这里 https://github.com/PaddlePaddle/DeepSpeech/blob/develop/docs/src/released_model.md#language-model-released

**Comment by expresschen** [comment]
有没有词级别的中文统计模型呢

**Comment by zh794390558** [comment]
没有。
