### ISSUE TITLE
2.1版本在 Ds2 Online Aishell Model 预训练模型上进行训练

### ISSUE THREAD

**Issue by maomaoyu2** [PaddlePaddle/PaddleSpeech#836]
请教一下，2.1版本要在在 Ds2 Online Aishell Model 预训练模型上进行训练，需要添加什么参数？

**Comment by zh794390558** [comment]
只需要准备好对应的数据，相应的预训练文件按照指定的目录放置即可（同训练目录的结构）。其他的按照你的想法来即可。
