### ISSUE TITLE
如何使用语言模型用于解码？

### ISSUE THREAD

**Issue by teng19880904** [PaddlePaddle/PaddleSpeech#950]
最近在看deepspeech-latest，发现2个问题：
1、查看aishell/s1中demo并没有使用语言模型(u2)，如何使用自训练的模型
2、TLG在解码时如何使用

希望给予帮助或者提供可以学习的资料。再次感谢🙏

**Comment by zh794390558** [comment]
1. s1没有语言模型的用法。librispeech/s2有用语言模型的用法。
 2. TLG现有代码中没有用，这部分期望用在c++的推理上用。

**Comment by teng19880904** [comment]
感谢 @zh794390558 回答，有计划TLG在c++上推断给出demo吗？

**Comment by zh794390558** [comment]
最近不行了，后面会安排上。

**Comment by teng19880904** [comment]
期待～
