### ISSUE TITLE
多语言支持

### ISSUE THREAD

**Issue by RedElectricity** [PaddlePaddle/PaddleSpeech#979]
我找来找去，都是只支持中文或者英文（不同语言会报错），就想问问能不能同时支持中英日三语的输出？（个人用Tacotron2

**Comment by yt605155624** [comment]
我们目前不支持多语言的模型，我不会日语，从中英双语的角度看，中文的音素集使用拼音，英文的音素集使用 CMUDict, 理论上只需要构造一个中英文的音素集（直接相加，或者把中英文中发音相似的音素合起来），就可以用中文数据集+英文数据集训练一个多语言模型，还需要额外增加一个 language embedding 消除语言和发音的耦合关系，应该是可以找到相应论文的

**Comment by dzcmingdi** [comment]
> 我们目前不支持多语言的模型，我不会日语，从中英双语的角度看，中文的音素集使用拼音，英文的音素集使用 CMUDict, 理论上只需要构造一个中英文的音素集（直接相加，或者把中英文中发音相似的音素合起来），就可以用中文数据集+英文数据集训练一个多语言模型，还需要额外增加一个 language embedding 消除语言和发音的耦合关系，应该是可以找到相应论文的

你好，如果我想训练一个输出德语的模型，只要准备一个德语音素集就可以了吗，可以用英语的数据集前处理代码来预处理德语数据集吗？
