### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement ConfigArgParse

### ISSUE THREAD

**Issue by XYZ-916** [PaddlePaddle/PaddleSpeech#994]
安装PaddleSpeech时出现如下错误：
命令：pip install -e .
错误：
![image](https://user-images.githubusercontent.com/14884056/141717082-b0f272fd-3435-4b64-829d-6bb21264f6f5.png)

请问如何解决，谢谢～

**Comment by yt605155624** [comment]
更新下 pip 试试

**Comment by XYZ-916** [comment]
貌似是因为AI Studio不太稳定。
