### ISSUE TITLE
建议将nltk_data下载到百度自己的服务器上

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSpeech#996]
在aistudio上运行Text-To-Speech FastSpeech2 + Parallel WaveGAN on CSMSC 下载nltk_data很慢
希望能下载到百度自己的服务器，然后通过一个download脚本加速下载过程

**Comment by yt605155624** [comment]
我没有用过 aistudio， nltk_data 应该是首次运行 jieba 的时候下载的吧，我看了下整个包只有十几兆，下载慢是因为没有翻墙嘛？https://paddlespeech.bj.bcebos.com/Parakeet/nltk_data.tar.gz 遵循您的建议，我把压缩包放到服务器上了，您 wget 下来放到自己的 home 目录应该就可以了吧
