### ISSUE TITLE
Chinese Rule Based Text Frontend的例子develop版中似乎没了？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSpeech#999]
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/docs/source/tts/zh_text_frontend.md
这个页面中描述的

现在有将以下这一套做完的吗？
Text Segmentation
Text Normalization (TN)
Word Segmentation (mainly in Chinese)
Part-of-Speech
Prosody
G2P (Grapheme-to-Phoneme, include Polyphone and Tone Sandhi, etc.)
Linguistic Features/Charactors/Phonemes

**Comment by yt605155624** [comment]
没有，现在实现了文本正则和变调，分句简单按照标点，分词用 jieba，用 pypinyin 实现了简单的多音字，例子放到了 https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/g2p 和https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/tn
